### ISSUE TITLE
Inconsistencies in description of RTCDTMFToneChangeEvent.tone

### ISSUE THREAD

**Issue by a2sheppy** [w3c/webrtc-pc#1014]
The descriptions of the tone attribute on the RTCDTMFToneChangeEvent interface vary throughout the document.

In some places, it's described as indicating that the previous tone has finished playing:

* https://w3c.github.io/webrtc-pc/#dom-rtcdtmftonechangeeventinit-tone
* https://w3c.github.io/webrtc-pc/#event-RTCDTMFSender-tonechange

Here, it's described as indicating that all tones have finished playing and that toneBuffer is empty:

* https://w3c.github.io/webrtc-pc/#dom-rtcdtmftonechangeevent-tone

(a) Which is correct?

(b) The doc needs to be revised to reflect that everywhere.

**Comment by aboba** [comment]
Looking at the definition of insertDTMF, it would appear that the tonechange event is fired when the toneBuffer is empty.

**Comment by a2sheppy** [comment]
That’s what I gather as well. The text for the event’s description needs to be updated to match everywhere.

**Comment by alvestrand** [comment]
The intent of the toneChange event was that it would fire whenever the tone changed - that is, at the end of each tone, including the one that makes the tone buffer empty.
This would be used to do things like move the highlight on a virtual dialpad if you want a visual indication that the tones are playing, or syntesize a "beep" that the user can listen to (there's no automatic feedback to the user that tones are playing).

I think this is consistent with the current description - it always says "indicates the tone that has just begun playing" or equivalent, and listing "empty string" as a special case indicating end of buffer.

If it was fired only when the tone buffer was empty, there would be no use for the "tone" argument.

**Comment by alvestrand** [comment]
There is an inconsistency that makes it look as if the event fires with an empty string argument at the end of a tone and the beginning of the inter-tone gap, even when the toneBuffer is not empty; I think this is inconsistent and should be removed.

I agree with Bernard's fix for this case.

**Comment by a2sheppy** [comment]
Certainly. The only question I had was whether it fired only at the end of the buffer, or if it fired for each individual tone, after it finished playing; This would let you know when the inter-tone gap began.
