### ISSUE TITLE
OpenSource WebRTC IdP 

### ISSUE THREAD

**Issue by Pierpaolo1992** [w3c/webrtc-pc#1017]
Hi,

i'm a student of University of Naples "Federico II", and i'm working about my master thesis, that concerns about performance analysis in two different streaming technologies: DASH and WebRTC, in the context of Digital Rights Management.
About WebRTC-part, i'm using Janus (http://janus.conf.meetecho.com) as WebRTC gateway; now i have to use a simply Identity Provider for WebRTC.

I've read draft in IETF about WebRTC security architecture, W3 specs about APIs for communications with an IdP and a lot of papers/drafts about idebtity management in WebRTC.

My questions is:

How could i implement a simply IdP? My teacher told me about Oauth, but i'm not very expert about identity provider management.

At the state of art, is there something ready-to-use? I hope answer is "yes" :)

Sincerly,

Best regards.

**Comment by alvestrand** [comment]
Please ask this on the implementor lists - Firefox is said to have an implementation.
This is not a spec issue.
