### ISSUE TITLE
Section 12.2.1.1: enum errorDetail definition

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1044]
Section 12.2.1.1 is entitled "TODO errorDetailEnum" and contains the following text:

"TODO - make a enum for all the error details? Is the enum OK for extending?"

**Comment by aboba** [comment]
Some ideas of what might be included in enum errorDetail:

SCTP errors (data channel transport)
RTCDataChannel errors (above the transport)
DTLS alerts

**Comment by alvestrand** [comment]
If it's an enum, it should all be lower-case-with-dashes.
