### ISSUE TITLE
Range checking needed for iceCandidatePoolSize

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1048]
For one, `iceCandidatePoolSize` should be using `[EnforceRange]`, so that (for example) a value of -1 isn't converted to 65535 at the WebIDL level.

We also might want to restrict the 0-65535 range further. There shouldn't be any scenario where more than a handful of pooled candidates will be needed, and allowing WebRTC to take up every single available socket is probably not desirable.

**Comment by foolip** [comment]
https://heycam.github.io/webidl/#idl-octet is the 8-bit unsigned integer type in Web IDL. Is 255 definitely large enough forever?

It's always an option to throw an exception in the prose of course, to take long as an argument and throw for values that don't make sense, at other boundaries that powers of two.

**Comment by taylor-b** [comment]
255 seems like a more-than-adequate limit, and that does simplify things. @fluffy, any objections?

**Comment by fluffy** [comment]
Agree that 255 is enough.
