### ISSUE TITLE
Section 10.3: mute signal 

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1051]
In Section 10.3 it says: 

"ISSUE 4
The mute signal mentioned in the previous paragraph is yet to be defined."

**Comment by aboba** [comment]
The paragraph in Section 10.3 before ISSUE 4 says: 

"When an RTCPeerConnection's RTP source is temporarily unable to receive media due to a loss of connection or if a mute signal has been received, it must update the muted state of the corresponding MediaStreamTrack with the value true. When media data is available again, the muted state must be updated with the value false."

[BA] Can we delete both the above paragraph and ISSUE 4?  I think this is covered by the text in Section 5.3: 

"When one of the SSRCs for RTP source media streams received by receiver is removed (either due to reception of a BYE or via timeout), the mute event is fired at track. If and when packets are received again, the unmute event is fired at track."

**Comment by taylor-b** [comment]
Was "loss of connection" meant to include the ICE "disconnected" and/or "failed" states? Or only things that happen at the RTP level?

**Comment by aboba** [comment]
@taylor-b Currently the "mute"event is only fired when an SSRC is removed via a BYE or timeout.  Since a timeout could conceivably occur due to an ICE connectivity loss, I think the answer is "both".  Here is the timeout text from RFC 3550: 

6.3.5 Timing Out an SSRC

   At occasional intervals, the participant MUST check to see if any of
   the other participants time out.  To do this, the participant
   computes the deterministic (without the randomization factor)
   calculated interval Td for a receiver, that is, with we_sent false.
   Any other session member who has not sent an RTP or RTCP packet since
   time tc - MTd (M is the timeout multiplier, and defaults to 5) is
   timed out.  This means that its SSRC is removed from the member list,
   and members is updated.  A similar check is performed on the sender
   list.  Any member on the sender list who has not sent an RTP packet
   since time tc - 2T (within the last two RTCP report intervals) is
   removed from the sender list, and senders is updated.

   If any members time out, the reverse reconsideration algorithm
   described in Section 6.3.4 SHOULD be performed.

   The participant MUST perform this check at least once per RTCP
   transmission interval.

**Comment by taylor-b** [comment]
An RTP-level timeout could definitely occur *due to* ICE connectivity loss, but should ICE connectivity loss in itself trigger the "mute" event? That's what I'm getting at. It wasn't clear to me if this was the intention of the old text in Section 10.3. I'm good with the answer being "no".

**Comment by aboba** [comment]
@taylor-b In general, the text relating to firing of the "mute" and "ended" events seems broken.  Since we do have correct text elsewhere, I think we can remove much of it.
