### ISSUE TITLE
Section 10.3: Freeing resources for incoming stream

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1063]
In Section 10.3, it says: 

      <p>When a <a>remote source</a> is notified that a
      <code><a>MediaStreamTrack</a></code>, using the source, has
      <code>ended</code> [[!GETUSERMEDIA]] the user agent MAY choose to free
      resources allocated for the incoming stream, for instance turn off the
      decoder.</p>

Is this referring to transceiver.stop() setting negotiation-needed, and after negotiation, on the remote peer the "ended" event being fired at transceiver.receiver.track?  I hope so, because I don't understand the above paragraph.

**Comment by alvestrand** [comment]
No, this is referring to the "all SSRCs got BYE, so they have gone away, and won't be coming back" condition, or the "a=msid is no longer present in the SDP" condition. I remember putting these descriptions into -msid-.

**Comment by Pehrsons** [comment]
Is it not (also) about MediaStreamTrack.stop()? I.e., a received track has been stopped so there is no way for the application to use it again.

**Comment by alvestrand** [comment]
I think "remote source" here means the stuff coming in from an RTPReceiver, so if it's intended to cover the (local) track.stop() case, it needs to be stated explicitly, I think.

**Comment by alvestrand** [comment]
Error on my side: BYE means mute, not stop. So we can't release resources in that case.
The only case where this can happen seems to be transceiver.stop().

**Comment by aboba** [comment]
@alvestrand If transceiver.receiver.track.stop() is called, then track is ended, and the receiver could turn off the decoder.  But how would the remote source be notified of this?  Suggest the following:

  <p>When a <code><a>MediaStreamTrack</a></code> track produced by
  an <code><a>RTCRtpReceiver</a></code> </var>receiver</var> has <code>ended</code> [[!GETUSERMEDIA]] (such as via a call to <code><var>receiver</var>.track.stop</code> the user agent MAY choose to free resources allocated for the incoming stream, by for instance turning off the
  decoder of <var>receiver</var>.</p>

**Comment by alvestrand** [comment]
That works for me.

I don't think the source would be notified; it's just too complicated to be worth doing. If the app wants to notify the source, he should call transceiver.stop, not receiver.track.stop.
