### ISSUE TITLE
Attaching the same track to multiple RTCRtpSenders: spec contradiction.

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1064]
The spec says "Each track to be sent is associated with exactly one RTCRtpSender, and each track to be received is associated with exactly one RTCRtpReceiver."

But with RTCRtpSender.replaceTrack it is possible to send the same track over multiple senders, which is also explained in the _NOTE_ section of _5. RTP Media API_.

The sentence needs to be updated:
- A track could be associated with one or more sender.
- A local track could be detached and not associated with any sender or receiver.
- A receiving track could be attached to one or more senders.

**Comment by aboba** [comment]
Yes. Perhaps the intent was to say that an RtpSender takes only one track as input and an RtpReceiver only outputs one track.
