### ISSUE TITLE
Need to specify which members of the encodings in "sendEncodings" are actually used

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1073]
The description of the `sendEncodings` member of `RTCRtpTransceiverInit` is currently:

> A sequence containing parameters for sending RTP encodings of media.

This somewhat implies that the full contents of the `RTCRtpEncodingParameters` are processed and used when generating an offer. But the only member that appears used by JSEP is `rid`. If this is correct, it should be clarified somewhere, either in the description of `sendEncodings` or in the `addTransceiver` steps.

**Comment by taylor-b** [comment]
Something I noticed when I started working on this: there's a "[[send encodings]]" slot on RTCRtpSender, which appears unused. Can I remove it? `sendEncodings` should only affect SDP negotiation, which means only `RTCRtpTransceiver` needs to know about it.

**Comment by aboba** [comment]
On reading the text, I wondered whether the [[send encodings]] slot exists to store the `sendEncodings` member of `RTCRtpTransceiverInit` provided to addTransceiver(), or whether it is supposed to contain sender.getParameters().encodings[] on an ongoing basis.  Currently, the setParameters() text doesn't indicate that the method modifies the [[send encodings]] slot, so perhaps it is the former?

Was the text below intended to refer to the [[send encodings]] slot?

If sendEncodings is set, then subsequent calls to createOffer will be configured to send multiple RTP encodings as defined in [JSEP] (section 5.2.2. and section 5.2.1.).

**Comment by taylor-b** [comment]
It doesn't seem like that's necessary, since the ball's in JSEP's court there. I'm not very clear on when internal slots should and shouldn't be used, but my assumption was that their purpose was to provide something with clearly defined behavior that's reference-able in other algorithms. But this is only used in one place, addTransceiver.

**Comment by aboba** [comment]
@pthatcherg @stefhak Do you recall what the intent was here?

**Comment by alvestrand** [comment]
Taylor to consult with Peter, and then remove it.

**Comment by taylor-b** [comment]
I ran into something again. The simulcast example is currently:

```
pc.addTransceiver(track, {
  direction: "sendrecv"
  encodings: [
    {
      rid: "f"
    },
    {
      rid: "h",
      scaleDownResolutionBy: 2.0
    },
    {
      rid: "q",
      scaleDownResolutionBy: 4.0
    }
  ]
});
```

So clearly, at some point the intention was that you could specify some of the encoding parameters at `addTransceiver` time. Maybe the [[send encodings]] slot was going to be used to specify this logic.

Do we still want to do this? If not, the example would need to change to do a `getParameters`/`setParameters` after `setRemoteDescription`. Maybe this would be a good interim topic.

**Comment by pthatcherg** [comment]
Yes, it was our intention originally to allow the sender to specify some
things along with the RIDs, such as the resolution scale, and perhaps the
priority or max bitrate.

But you have a good point that we would need to make clear what things are
allowed there and what things are not (codecs, for example, are, I think,
clearly not), and what interaction there would be between
setRemoteDescription and the parameters passed in there.

The tradeoff is between complexity of the spec and convenience of the
application.  Allowing the app to set a lot of those things is easier, but
then there's more to worry about with the interaction between
setRemoteDescription and the encodings set here.  Allowing the app nothing
but rids is easy to specify, but it requires more work from the app
(addTransceiver; setRemoteDescription; getParameters; setParameters).

I'm hoping there is a simple rule that allow us to get most of the benefit
for the app for little of the cost in complexity in the spec.  But
whichever we choose, I agree we need to give is some thought and it is
worthy of agenda time as an interim topic.

**Comment by aboba** [comment]
Marked as interim topic and added to slides:
https://docs.google.com/presentation/d/1cR9kNh4pTEtVbOOcIf4yi47ZDsOZVcVosr470bWWry8/edit#slide=id.g202bb5df5e_0_0

**Comment by alvestrand** [comment]
Interim comment: Need to identify what the app can change in sendEcodings. Consensus for sendEncodings where all of the non-read-only things can be set.
Need to sort error handling.

**Comment by taylor-b** [comment]
The error handling part is what I was most worried about. Going through the error cases in https://github.com/w3c/webrtc-pc/issues/763, the only one that's really relevant is "too many simulcast encodings".

For example, suppose the application calls `addTransceiver` with 3 simulcast encodings (as in the example above), and the browser only supports simulcast with VP8/VP9.

1. After the offer/answer exchange is done, H.264 and VP8 are negotiated, with H.264 having a higher priority in the remote description. What happens? I assume the implementation should choose VP8.
2. After the offer/answer exchange is done, *only* H.264 is negotiated. What happens? Is the SRD promise rejected? If so, how does the application recover?

I'd suggest that we allow `RTCRtpSender.getParameters` and `setParameters` to be called before `setRemoteDescription`, so the application could turn off the extra encodings (set `active` to `false`) and call `setRemoteDescription` again. Assuming they get an `RTCError` somehow when the promise is rejected.

Or, we could have the browser just automatically do this. But then the behavior of `addTransceiver` would be inconsistent with `setParameters`.

**Comment by ibc** [comment]
A little off-topic, but please, let's also take into account enabling simulcast without creating an offer, but an answer.
