### ISSUE TITLE
Candidate from onicecandidate event and addIceCandidate are incompatible

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1077]
The `addIceCandidate` method states:

> This method can also be used to indicate the end of remote candidates when called with an empty string for candidate.

First of all, do you mean the **member** `candidate` can be empty string or the **argument** `candidate` can be empty string? I'm guessing you mean the member but please clarify this in the description.
Please also state what should happen in case the argument `candidate` is `null`. Is this still an end of candidate indication but for all mids (as it was before)? I guess it would have to be to ensure backwards compatibility.

To the main issue: `RTCPeerConnectionIceEvent` contains an attribute `candidate` which states:

> This attribute is set to null when an event is generated to indicate the end of candidate gathering.

I guess this has just not been updated to the changes to `addIceCandidate`. I would expect the `candidate` attribute to always contain an `RTCIceCandidate` which cannot be `null` (instead, `candidate.candidate` would be an empty string).

**Comment by lgrahl** [comment]
Without knowledge of the history why *all gathering done* fires a `null` candidate, implementing `addIceCandidate` is error-prone. Users will expect that everything that comes out from the `onicecandidate` event can be thrown into `addIceCandidate` without having to check anything. But currently there is no indication on what's supposed to happen in case the `candidate` argument is `null`.

I propose a simple solution after `4.2` in the `addIceCandidate` method:
> 3. If *candidate* is `null`, return *p* immediately and resolve *p* with `undefined`.

**Comment by lgrahl** [comment]
As a follow-up question: If `candidate.candidate` can be empty string in `addIceCandidate`, where is this feature used? IIRC `onicecandidate` can only fire `RTCIceCandidate` candidates.

**Comment by lgrahl** [comment]
Sorry for the amount of edits but I am very confused by the current spec:

1. I still don't understand why the `onicecandidate` returns `null` to indicate the end of candidates and not `{ candidate: '', sdpMid: null, sdpMLineIndex: null }`? Sure, it will break backwards compatibility (to what as you already said no one implemented it?) but...
2. It also breaks forward compatibility towards `addIceCandidate` as the method allows `candidate` to be `null` but the description does not handle that case.

If 1 would be addressed and changed to `{ candidate: '', sdpMid: null, sdpMLineIndex: null }`, we could solve 2 backwards **and** forward compatibility by adding the following to the `addIceCandidate` method description after `4.2`:

> 3. If *candidate* is `null`, handle *candidate* as if it were `{ candidate: '', sdpMid: null, sdpMLineIndex: null }`.

What do you think? And again, sorry for the heavy editing.

**Comment by taylor-b** [comment]
> Users will expect that everything that comes out from the onicecandidate event can be thrown into addIceCandidate without having to check anything.

I see the argument that new users would expect that... Current users are I believe accustomed to checking `candidate != null` though.

> I still don't understand why the onicecandidate returns null

There are applications that use this `null` candidate event as a signal that candidate gathering is done, so they can get a new description with the full set of candidates and send it to the non-trickle-ICE aware endpoint.

> It also breaks forward compatibility towards addIceCandidate as the method allows candidate to be null but the description does not handle that case.

How does it allow `candidate` to be `null`? `candidate`'s type isn't nullable anywhere I can see.

Anyway, I agree what we have now is confusing; it's the result of making the minimum possible changes to allow the end-of-candidates indication to work, and not breaking backwards compatibility. Do you think the confusion could be cleared up by summarizing the different candidate signals somewhere? Or should we reconsider the choice to keep around the `null` candidate event?

**Comment by lgrahl** [comment]
Before I can respond to your questions, let me ask:

1. What is the status quo for the `onicecandidate` event? Does it only return a single event with `null` to indicate end-of-candidates or does it return both `{ candidate: '', sdpMid: null, sdpMLineIndex: null, ... }` and `null` events to indicate end-of-candidates? If not the latter, why not?
2. Does `candidate = null` have the exact same meaning as `{ candidate: '', sdpMid: null, sdpMLineIndex: null, ... }`? If not, why not?

> I see the argument that new users would expect that... Current users are I believe accustomed to checking candidate != null though.

I can only speak for myself: I stopped checking for `null` since I've read that this information can be passed to `addIceCandidate` to indicate the end of candidates. (The normal user will have no insight whether this is actually implemented or not.)

> How does it allow candidate to be null? candidate's type isn't nullable anywhere I can see.

It is: https://github.com/w3c/webrtc-pc/blob/387e0bdb4e7db21e754209f8f0a1bb5e2f3cb333/webrtc.html#L2286
And if we really want to keep backwards compatibility to the specification, I think allowing `null` is correct. But it should be handled in the description. I think we should treat `null` as if it were `{ candidate: '', sdpMid: null, sdpMLineIndex: null, ... }` (if my assumption is correct and this has the exact same meaning as `null` as specified previously). That part is missing in the description.

**Comment by taylor-b** [comment]
> Does it only return a single event with null to indicate end-of-candidates or does it return both

Both.

> It is: https://github.com/w3c/webrtc-pc/blob/387e0bdb4e7db21e754209f8f0a1bb5e2f3cb333/webrtc.html#L2286

Oh, that appears to just be one place we forgot to update. In the WebIDL it's not nullable.

> And if we really want to keep backwards compatibility to the specification, I think allowing null is correct. 

But, as far as I'm aware, no browser implemented accepting a null argument. So there shouldn't be a backwards compatibility concern.

**Comment by lgrahl** [comment]
> Also, `{ candidate: '', sdpMid: null, sdpMLineIndex: null, ... }` would be an illegal argument, since either `sdpMid` or `sdpMLineIndex` needs to be specified.

So, `null` does not have the same meaning as the new end-of-candidate event? It's end-of-candidates for a specific media stream? Now I'm starting to understand why you've left `null` in... However, having said that, non-Trickle-ICE implementations can still get the same information by waiting until end-of-candidate has been received for all media streams (although that's a little bit more complicated) - is that correct?

It just seems counter-intuitive to not being able to throw everything that comes out of the `onicecandidate` event into `addIceCandidate` without having to check anything. But I don't feel too strongly about that. Just something users and signalling solutions have to be aware of.

**Comment by aboba** [comment]
As I recall, the candidate argument to addIceCandidate was originally made nullable so as to permit a null candidate emitted by onicecandidate to be signaled without modification. Since then we have made other changes but keeping onicecandidate and addIceCandidate compatible seems like it is important.

**Comment by aboba** [comment]
Looking  at the description of `addIceCandidate`, the `candidate` argument is tested for being null:

If candidate is not null and both sdpMid and sdpMLineIndex are null, return a promise rejected with a newly created TypeError.

Did we forget to clean this up?

Also, there is a legacy `addIceCandidate` method in Section 4.3.3.1.   Does this legacy method behave the same way with respect to the candidate argument?

**Comment by lgrahl** [comment]
> If `candidate` is not null and both `sdpMid` and `sdpMLineIndex` are null, return a promise rejected with a newly created TypeError.

It could be that `candidate` actually means the member `candidate` (`candidate.candidate`). Because the `sdpMid` and `sdpMLineIndex` in this context are also members of `candidate` but lack the `candidate.` prefix.

**Comment by taylor-b** [comment]
> However, having said that, non-Trickle-ICE implementations can still get the same information by waiting until end-of-candidate has been received for all media streams (although that's a little bit more complicated) - is that correct?

Yes. Though they don't even have to do that, they can just wait for the gathering state to change to "complete".

> Is this referring to the candidate argument or the member?

The whole "if candidate is not null" part can be removed, this is left over from the previous approach.

**Comment by lgrahl** [comment]
@aboba Will this topic be discussed (as you've applied an *interim topic* label) or has it been resolved?

**Comment by aboba** [comment]
@lgrahl Do you think that the topic would benefit from discussion at the interim?

**Comment by lgrahl** [comment]
I really don't know (I also don't really know anything about this meeting - is it [this one](https://www.w3.org/2011/04/webrtc/wiki/April_4_2017)?). If you guys don't feel strongly about this issue, I don't mind the current state.
