### ISSUE TITLE
Can candidate.ufrag be null?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1078]
The `addIceCandidate` method states:

> If candidate.ufrag is neither undefined nor null, and is not equal to any ufrag present in the corresponding media description of an applied remote description, reject p with a newly created OperationError and abort these steps.

and

> In parallel, add the ICE candidate candidate as described in [JSEP] (section 4.1.16.). Use candidate.ufrag to identify the ICE generation; if the ufrag is null, process [...]

However, I don't see that `candidate.ufrag` can be `null`. The `RTCIceCandidate` interface states:

> ufrag of type DOMString, readonly

and the `RTCIceCandidateInit` members would support that:

> ufrag of type DOMString

Is the `addIceCandidate` method description slightly incorrect or can `ufrag` be `null`?

**Comment by lgrahl** [comment]
So, if I understand correctly, `ufrag` in `RTCIceCandidateInit` may be `undefined` but not `null`. And for `RTCIceCandidate` it's the opposite - it may not be `undefined` but it can be `null`. Right? But I can't find an indication in the description of `RTCIceCandidateInit` that `ufrag` is optional.

**Comment by taylor-b** [comment]
Dictionary members are optional by default, unless they say "required".

**Comment by taylor-b** [comment]
Oh, but I see that `sdpMid` and `sdpMlineIndex` are nullable and default to `null`. So we could do the same thing for `ufrag`, and then we could just say "if `ufrag` is `null`" rather than "neither `undefined` nor `null`".

**Comment by lgrahl** [comment]
> Dictionary members are optional by default, unless they say "required".

Okay.

> So we could do the same thing for ufrag, and then we could just say "if ufrag is null" rather than "neither undefined nor null".

But an `RTCIceCandidateInit` can also be passed to `addIceCandidate`, right? And as the member is optional, checking for `undefined` would still be required.

Issue can be closed from my side. :)

**Comment by taylor-b** [comment]
If it's optional but defaults to `null`, I *think* that means if a value is missing it will be set to `null` automatically at the WebIDL level.

But if you don't feel strongly about this, I'll just close the issue for now.
