### ISSUE TITLE
Update for structured cloning changes in HTML

### ISSUE THREAD

**Issue by domenic** [w3c/webrtc-pc#1089]
In https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 we changed HTML's formulation of structured cloning significantly for the better. Web RTC should update to have separate serialization and deserialization steps. This can also eliminate having to deal with the memory variable.

I can work on a pull request for this shortly. Please let me know if there are any other Web RTC specs that have structured clone integration.

**Comment by adam-be** [comment]
I don't believe that there are other WebRTC docs affected by this. A PR would be much appreciated.

**Comment by stefhak** [comment]
Re-opening as #1171 reverted #1108 and I would like to make sure we do not forget this.

**Comment by alvestrand** [comment]
This is actually directly relevant to the discussion about what the internal representation of the private key part of a stored certificate is (for some meaning of the word "is").

**Comment by stefhak** [comment]
It seems the W3C HTML spec (5.2) now _is_ updated, so PR https://github.com/w3c/webrtc-pc/pull/1108/files could be re-applied.
