### ISSUE TITLE
DTLS failures

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1092]
Currently RTCDtlsTransportState has a "failed" value, but the RTCDtlsTransport does not have an onerror EventHandler.  Is there a way for the application to obtain  information on the reason why DTLS failed?

**Comment by taylor-b** [comment]
Are there situations where a DTLS failure is actionable? Or is the failure reason only something that would be used for debugging, in which case it probably doesn't need its own error?

**Comment by rshpount** [comment]
You probably do want to differentiate between the fingerprint match failure, protocol negotiation failure due to things like crypto capabilities or version mismatch,  and DTLS protocol negotiation failure due to network error.

**Comment by aboba** [comment]
Now that browser DTLS implementations are moving to DTLS 1.2 with ECSDA support (and soon, 1.3), backward compatibility issues can arise with applications based on older code that only supports DTLS 1.0 and RSA certificates.  For example,  if an application running on a browser that defaults only to ECDSA certificates does not use the certificate management API to create an RSA certificate, it will fail to interoperate with a mobile application based on an older implementation that only supports RSA certificates.  So if the application can determine that this is what went wrong it could figure out what went wrong. 

I do not think that crypto capabilities or version mismatch negotiation failures would necessarily run afoul of the warning in the Websockets API spec, but fingerprint match failure might.  Here is the prohibition from that spec (https://html.spec.whatwg.org/multipage/comms.html#feedback-from-the-protocol):

User agents must not convey any failure information to scripts in a way that would allow a script to distinguish the following situations:

A server whose host name could not be resolved.
A server to which packets could not successfully be routed.
A server that refused the connection on the specified port.
A server that failed to correctly perform a TLS handshake (e.g., the server certificate can't be verified).
A server that did not complete the opening handshake (e.g. because it was not a WebSocket server).
A WebSocket server that sent a correct opening handshake, but that specified options that caused the client to drop the connection (e.g. the server specified a subprotocol that the client did not offer).
A WebSocket server that abruptly closed the connection after successfully completing the opening handshake.
In all of these cases, the the WebSocket connection close code would be 1006, as required by the WebSocket Protocol specification. [WSP]

Allowing a script to distinguish these cases would allow a script to probe the user's local network in preparation for an attack.

**Comment by aboba** [comment]
Conclusion from the interim was that ICE consent removes much of the security risk. So can provide information on DTLS failures.

**Comment by aboba** [comment]
Some ideas: 

1. Add "dtls-failure" value to RTCErrorDetailType. 
2. Add tlsAlert attribute to RTCError.  
3.  tlsAlert attribute contains the (D)TLS alert value when errorDetail = "dtls-failure".  Values are available here: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-6

**Comment by alvestrand** [comment]
VI: Seems to be consensus around that we need something for recoverable DTLS errors. We should provide actionable info to script.
Bernard said he would come up with something.
