### ISSUE TITLE
I think that "gatheringState" of RTCIceTransport should be changed to the name "gathererState".

### ISSUE THREAD

**Issue by gtk2k** [w3c/webrtc-pc#1105]
https://w3c.github.io/webrtc-pc/#dom-rtcicetransport
In order to distinguish it from "gatheringState" of RTCPeerConnection, I think that "gatheringState" of RTCIceTransport should be changed to the name "gathererState".

**Comment by aboba** [comment]
In RTCPeerConnection we have RTCIceGatheringState gatheringState.  In RTCIceTransport we have RTCIceGathererState gatheringState.   In the ORTC RTCIceGatherer, it is RTCIceGathererstate state.

**Comment by alvestrand** [comment]
We'd like to not change the name of implemented enums at this stage of the process.
