### ISSUE TITLE
Terminology around "setting" attributes may be incorrect

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1112]
In various places, we talk about "setting" attributes. This comes in three flavors:

1. Setting an internal slot, which is read by the attribute's getter. For example:

> Store the configuration in the [[ configuration]] internal slot.

2. Setting some abstract thing, which can be assumed to be an internal slot. For example:

> An RTCPeerConnection object has a **signaling state**, a **connection state**, an **ICE gathering state**, and an **ICE connection state**. These are initialized when the object is created.
> ...
> To update the **ICE gathering state** of an RTCPeerConnection instance _connection_, the user agent must queue a task that runs the following steps:
> ...
> 4. Set _connection_'s **ice gathering state** to newState.

This seems acceptable. Though, for consistency and to be more formal, I'd suggest just describing these things as internal slots as well.

3. Setting the attribute itself. For example:

> Set connection's pendingLocalDescription , currentLocalDescription , pendingRemoteDescription and currentRemoteDescription to null.

In WebIDL terminology, this seems as if it would be formally interpreted as "call the attribute's setter". But it's a readonly attribute, so it doesn't have a setter. Is this ok (since it's obvious enough what the intention was), or should we change these places to use an internal slot as well?

For example, say in the description of `pendingLocalDescription`:

> Returns the value of the `[[pendingLocalDescription]]` internal slot.

And change the above quote to:

> Set connection's `[[pendingLocalDescription]]` , `[[currentLocalDescription]]`, `[[pendingRemoteDescription]]` and `[[currentRemoteDescription]]` internal slots to null.

**Comment by jan-ivar** [comment]
Number 3 is definitely wrong. Some care seems to have gone into number 2, but consistency wins for me as well. Internal slots for everything.

**Comment by adam-be** [comment]
I think we have started moving towards internal slots, but there are still a lot of old spec text using "number 3" above.

**Comment by taylor-b** [comment]
@jan-ivar A question that's coming up as we're trying to fix this: what naming convention should we use for internal slots that map 1:1 to attributes? If we use the same name, we'll get duplicate definition respec errors.

**Comment by jan-ivar** [comment]
From looking at other specs, internal slots seem to use [[FooBar]] vs. attribute fooBar.

**Comment by taylor-b** [comment]
What's an example? I ran into problems even with that, since definitions aren't case sensitive.

**Comment by jan-ivar** [comment]
@taylor-b Hmm, good question. I haven't immediately found a good example to lean on, and the design guide doesn't mention it, though I happened across [this example](https://www.w3.org/2001/tag/doc/promises-guide#example-environment-ready) that either shows ignorance of the problem, or that it perhaps should not be a problem. @domenic Do you happen to know if/where internal slot naming etc. is spelled out, or do you know the answer to this question? Might it be a respec issue?

**Comment by domenic** [comment]
Overall this issue makes me happy that people are paying attention to properly specifying stuff like this, and I agree with the OP as well :).

Internal slot naming is pretty ad-hoc right now and up to the spec authors. In Bikeshed there are different namespaces for different definition types, so this doesn't come up... How to do this properly in ReSpec, hmm... Can you manually give the slots different id=""s at definition time? Autolinking should still allow you to do `<a>[[FooBar]]</a>` at reference time, I think.

@marcoscaceres, any ideas?

**Comment by taylor-b** [comment]
Giving them different `id=`s doesn't prevent the "duplicate definition" error. But something I just tried which seems to work is `[<dfn>[FooBar]</dfn>]` (in other words, enclose one set of `[]`s in the definition). Not sure if this would be considered a hack or an acceptable solution. Enclosing both sets of `[]`s in the definition almost works, but it tries to create a bibliography link (like it does for `[[JSEP]]`). I could work around this by adding extra spaces (`<dfn>[[ FooBar ]]</dfn>`). But again, this feels like a hack.

**Comment by domenic** [comment]
Oh, I think you're supposed to escape internal slots by using either `\[[FooBar]]` or `[[\FooBar]]`, one of those two.

**Comment by taylor-b** [comment]
Oh, that works! Guess I should have looked at the ReSpec documentation. Here's a PR that fixes our current uses of internal slots: https://github.com/w3c/webrtc-pc/pull/1395

**Comment by marcoscaceres** [comment]
If you need me to review ReSpec usage, happy to do that.  #1395 looks good. 

For "best practice", take a look at http://github.com/w3c/browser-payment-api

**Comment by aboba** [comment]
@stefhak Can we close this?

**Comment by adam-be** [comment]
I suspect that we still have spec text that sets attributes. It would be better to have more specific issues, but we could consider this one an umbrella bug for those.

**Comment by adam-be** [comment]
I can take a stab at producing more specific issues.

**Comment by adam-be** [comment]
Specific issue #1792
