### ISSUE TITLE
Section 12.2.4: Note

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1113]
In Section 12.2.4 there is a note: 

NOTE
The following will need to be updated when we finish out the error definitions.

**Comment by aboba** [comment]
This may be referring to the need for WebIDL for the RTCError event and RTCErrorEventInit.   Something like this: 

interface RTCError : Event {
    readonly attribute RTCErrorDetailType errorDetail;
    readonly attribute DOMString message;
    readonly attibute DOMString name;
    readonly attribute unsigned long sdpLineNumber; 
    readonly attribute unsigned short httpRequestStatusCode; 
    readonly attribute unsigned short sctpCauseCode;
    readonly attribute unsigned short tlsAlert; 
};

**Comment by stefhak** [comment]
I think we can just remove the note in section 12.2.4
