### ISSUE TITLE
"getParameters" and "setParameters" need more thorough specification

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1116]
The description of `RTCRtpSender.getParameters`, for example, is currently just:

> The getParameters method returns the RTCRtpSender object's current parameters for how track is encoded and transmitted to a remote RTCRtpReceiver.

But it's not obvious how and when these "current parameters" are populated. My understanding, from working group discussions back when the sender/receiver APIs were first being introduced, was that `getParameters` would return nothing until a remote description is set (or a local description, for an `RTCRtpReceiver`), after which the envelope of possible parameters is determined by SDP.

`setParameters` could also be more clear about all the things that are allowed to change. We already have "read-only parameter" markings where the parameter is defined, but a short summary at the top of the `setParameters` description wouldn't hurt.

**Comment by aboba** [comment]
@taylor-b  One way to think about this is that there is a [[parameters]] internal slot that is distinct for the sender and receiver.  sender.setParameters() stores validated parameters in that slot and the getParameters() methods retrieve from it.  For the sender, setting the remote description stores into the [[parameters]] internal sender slot, and for the receiver, setting the local description stores into the [[parameters]] internal receiver slot. However, addTransceiver with sendEncodings or setCodecPreferences() does not store into the sender [[parameters]] internal sender slot (or the receiver slot).  Since sender.setParameters() cannot set the negotiation-needed flag (or the number of encodings), can the contents of the [[parameters]] internal slot affect createOffer() or createAnswer()?  I suspect the answer is "no".

**Comment by aboba** [comment]
Subsets of the "current parameters" are affected by different methods: 

1. addTransceiver with sendEncodings can set rids, the number of encodings, and writeable encoding parameters on the sender.   This affects the SDP produced by createOffer/createAnswer. 

2. sender.setParameters() can reorder or remove codecs and can set writeable encoding parameters (but cannot change read-only parameters, the number of encodings or the sdpFmtpLine).  We say that setParameters cannot set the negotiation-needed flag, but do not say explicitly that setParameters does not affect the SDP produced by createOffer() and createAnswer().

3. setCodecPreferences() can reorder or remove codecs but cannot set the sdpFmtpLine.  This affects the SDP produced by createOffer/createAnswer. 

4. Calling setLocalDescription (for a receiver) or setRemoteDescription (for a sender) sets parameters from the SDP.

Can getParameters() can return a subset of the parameters, or does it only return a non-null result once setLocal (receiver) or setRemote (sender) is called?  If sender.getParameters() returns null before setRemoteDescription, can sender.setParameters() be called before setRemoteDescription? That would imply that calling getParameters after setParameters would not necessarily return the parameters that were set.

**Comment by taylor-b** [comment]
> Can getParameters() can return a subset of the parameters, or does it only return a non-null result once setLocal (receiver) or setRemote (sender) is called? If sender.getParameters() returns null before setRemoteDescription, can sender.setParameters() be called before setRemoteDescription?

What's an example of how this would be used? One thing I can think of: if an application uses `sendEncodings`, it may want to change the encoding parameters after the fact, but before `setRemoteDescription` is called. I mentioned this on #1073, as it may be needed to recover from simulcast-related errors gracefully.

> That would imply that calling getParameters after setParameters would not necessarily return the parameters that were set.

I don't follow. If the parameters were set successfully, `getParameters` should return the same thing that was set, possibly without codecs that are no longer available. Right?

**Comment by aboba** [comment]
In the example you mentioned, where `setParameters` is used to change the `encodings[]` originally set by  `setEncodings`, you might want to call `sender.getParameters()`, then modify `parameters` and call `sender.setParameters`.  So even though setRemoteDescription hasn't been called, it might be helpful for `sender.getParameters` to return a non-null value, even if some attributes of the `RTCRtpParameters` dictionary are not set at that point.

**Comment by taylor-b** [comment]
I agree. I just didn't understand what you meant by "calling getParameters after setParameters would not necessarily return the parameters that were set."

**Comment by taylor-b** [comment]
Another question that came up for me recently: if the remote description didn't signal SSRCs explicitly, what should `RTCRtpReceiver.getParameters` return in `encodings`? We could have it return a single `RTCRtpEncodingParameters`, with the `ssrc` set if a packet has been received and the SSRC is known, and `undefined` otherwise. Any opinion, @aboba? Maybe it doesn't matter, since WebRTC 1.0 only has `getParameters`, and ORTC only has `receive()`, so there's no situation where the return value of `getParameters` would be passed back into the `RTCRtpReceiver`.

**Comment by aboba** [comment]
@taylor-b I'd suggest that the contents returned by `RTCRtpReceiver.getParameters` be based solely on the information in the remote description.  So changes in the incoming ssrc_table (e.g. an SSRC conflict, receipt of a BYE, SSRC timeout, ssrc latching, etc.) would not be reflected in `RTCRtpReceiver.getParameters`.  Similarly, I wouldn't try to reflect changes in the outgoing ssrc_table in 
`RTCRtpSender.getParameters`.  If there is a need to obtain information from the outgoing or incoming ssrc_table, that is probably better handled in the Statistics API.

**Comment by taylor-b** [comment]
That would be consistent with other things in `RtpParameters`. And, if we ever do have an `RTCRtpReceiver` with both "get" and "set" methods, it would preserve the symmetry. So, makes sense to me.
