### ISSUE TITLE
RTCRtpContributingSource.getReceiver()

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1117]
Because we can't have RTCRtpContributingSource attributes change randomly within a single frame of JS execution (#1111) it is necessary to update all contributing sources of a receiver if the values of any one of them are read and to cache the result until the next frame of JS execution. Example:
```
  ...
  let sources = receiver.getContributingSources();
  assert_that(sources.length, 2);
  return Promise.resolve(sources);
}).then(function(sources) {
  // This function is executed in the next frame of JS execution,
  // sources might have been updated due to received RTP packets.
  // Within this frame of JS execution, sources must not be updated
  // again, i.e. this must always be true:
  assert_that(sources[0].timestamp, sources[0].timestamp);
  // Also:
  // sources[0].timestamp needs to be comparable to
  // sources[1].timestamp, if any one of them is updated all of
  // them needs to be updated.
});
```
In order to implement this, a contributing source needs to know of its receiver so that it can perform a new receiver.getContributingSources() to update the cache.

Should we just expose the receiver referemce with RTCRtpContributingSource.getReceiver()?

**Comment by henbos** [comment]
Also, do we make the caching explicit in the RTCRtpContributingSource description or let it be implied by descriptions elsewhere (#1111)?

**Comment by taylor-b** [comment]
In my opinion, the caching and internal references between objects should
be left as an implementation detail. Other implementers could choose
different approaches. And purely from an API perspective, a "getReceiver"
method doesn't really buy anything, since the application should already
know which receiver it got a contributing source from.

**Comment by stefhak** [comment]
I agree to you @taylor-b

**Comment by aboba** [comment]
Agree with Taylor that this is an internal implementation issue.
