### ISSUE TITLE
[TreatNullAs=EmptyString] is not allowed for USVString per Web IDL

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1118]
See issue https://github.com/heycam/webidl/issues/340

If there are good reasons to disallow `[TreatNullAs=EmptyString]` for USVString and the Web IDL spec does not change, then WebRTC should change instead. It's used here:

https://w3c.github.io/webrtc-pc/#peer-to-peer-data-api

```WebIDL
partial interface RTCPeerConnection {
    readonly attribute RTCSctpTransport? sctp;
    RTCDataChannel createDataChannel([TreatNullAs=EmptyString] USVString label,
                                     optional RTCDataChannelInit dataChannelDict);
    attribute EventHandler ondatachannel;
};
```

**Comment by foolip** [comment]
In https://github.com/heycam/webidl/issues/340 @domenic tells me it'll probably be renamed to `[LegacyTreatNullAsEmptyString]`, and I noticed [Gecko's IDL](https://github.com/mozilla/gecko-dev/blob/3abfe370ac37d2ae03f9ec169a384975c60c175f/dom/webidl/RTCPeerConnection.webidl#L138) uses just `DOMString label`.

Can anyone say why `[TreatNullAs=EmptyString]` was added in the first place? I searched for "createDataChannel(null" in httparchive and found just one instance, on https://dialpad.com/. It's hard to say without testing it, but that'd probably work just fine if the label becomes to "null" instead of "".

Chromium bug which started this:
https://bugs.chromium.org/p/chromium/issues/detail?id=667901

**Comment by dontcallmedom** [comment]
as far as I can tell, this has been marked as `[TreatNullAs=EmptyString]` since the start of the inclusion of the `DataChannel` API in 71196402bf6b0aead798e882d62519749f3dc04e. I don't think there was a lot of discussions nor justification for this.

**Comment by foolip** [comment]
@guidou @henbos, would you be comfortable with the risks related to changing this? It seems very low risk to me, but I only know Web IDL, not WebRTC :)

**Comment by guidou** [comment]
The risk looks low to me.
