### ISSUE TITLE
RTCCertificate.getAlgorithm for implicitly generated local certificates

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1120]
RTCCertificate.getAlgorithm() is described as follows:

> Returns the value of keygenAlgorithm passed in the call to generateCertificate().

It is clear what to do for RTCCertificates generated by RTCPeerConnection.generateCertificate, but for certificates generated by the RTCPeerConnection contructor when no certificate was provided, and retrieved by RTCPeerConnection.getConfiguration, it is not clear what getAlgorithm() should return.

> If no certificates value was specified, one or more new RTCCertificate instances are generated for use with this RTCPeerConnection instance.

This could mean the PC called generateCertificate and we have a known AlgorithmIdentifier, or the PC could do something implementation-specific to generate certificates. Must an AlgorithmIdentifier have been used? Do we deduce which AlgorithmIdentifier could have been used? Do we return null if certificates was generated without explicitly calling generateCertificate with an AlgorithmIdentifier?

**Comment by taylor-b** [comment]
The specification seems a bit ambiguous right now about whether generated certificates are even returned by `getConfiguration`. The next step is:

> Store the configuration, including the certificates, in a [[ configuration]] internal slot.

But I assumed this referred to only the certificates "included" in the configuration, not automatically generated certificates.

**Comment by henbos** [comment]
I agree it's vague. I interpreted it as to include the generated certificates, thinking why else would you single out certificates out of all things included in a configuration? Otherwise you could just say "Store the configuration in a [[ configuration]] internal slot."

The same vagueness is here too (setConfiguration step 4): 

> If configuration.certificates is set and the set of certificates differs from the ones used when connection was constructed, throw an InvalidModificationError.

Does it refer to the set of certificates supplied in the constructor argument or the resulting set of certificates from the constructor steps? As long as we're consistent with [[ configuration]] internal slot.

**Comment by aboba** [comment]
Since there are legacy native applications that only support DTLS 1.0 and RSA certificates, it may be useful to be able to determine if the browser is still generating an RSA certificate (and if not, to use `RTCPeerConnection.generateCertificate` to create one).  In that scenario, it would be useful for `RTCPeerConnection.getConfiguration` to return generated certificates, and then to be able to call `RTCCertificate.getAlgorithm()` for a generated certificate.

**Comment by taylor-b** [comment]
If an application knows it only supports RSA certificates, it could just use `generateCertificate` 100% of the time.

My concern is that applications may be doing something like this:

```
config = { iceServers: [...], iceTransportPolicy: "relay", ... }
pc = new RTCPeerConnection(config);

// Later on...
config.iceTransportPolicy = "all";

// Throws exception, because |config| doesn't include auto-generated certificates?
pc.setConfiguration(config);
```

It's not exactly intuitive that you need to call `getConfiguration` in order to call `setConfiguration`. So I personally think things would be simpler if we kept the rule "`getConfiguration` just returns the last set or constructed-with configuration".

**Comment by henbos** [comment]
Both good points. We could make "certificates: undefined" mean the same thing as "certificates: <default certificates>". That way getConfiguration() can contain certificates but pc.setConfiguration(config) in the above example would still work.

**Comment by henbos** [comment]
If you care about which certificates are used you should always use generateCertificates() though, and if you are interested in which certificates are used by default you can always getStats()

**Comment by stefhak** [comment]
@henbos can you do a PR?

**Comment by henbos** [comment]
As I was about to write a PR I realized this can get a bit messy. Certificates are generated asynchronously, e.g. when creating an offer: "If connection was not constructed with a set of certificates, and one has not yet been generated, wait for it to be generated." This means that we might do getConfiguration() and no certificate is generated, or we do it an some of the certificates have been generated but not all of them.

We might do getConfiguration() and get certificates: [ A ] and then we do setConfiguration a non-undefined certificates is expected to be [ A, B ]. We could say that setConfiguration expects certificates to be a subset of the true |certificates| but this would just get confusing, then certificates: [ B ] would be accepted when A is in fact the one currently in use.

I opt to leave "default certificates" undefined for default-generated, have get/setConfiguration be means to get and set configurations consistently rather than means to obtain certificate information. If you want information about certificates used you can use RTCPeerConnection.getStats() instead.

**Comment by taylor-b** [comment]
> I opt to leave "default certificates" undefined for default-generated, have get/setConfiguration be means to get and set configurations consistently rather than means to obtain certificate information. If you want information about certificates used you can use RTCPeerConnection.getStats() instead.

That sounds good to me.
