### ISSUE TITLE
Define what the default RTCDataChannel id is

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1132]
https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-createdatachannel

> If the id attribute is uninitialized (not set via the dictionary), and the DTLS role of the SCTP transport has already been negotiated, then initialize id to a value generated by the user agent, according to [RTCWEB-DATA-PROTOCOL], and skip to the next step. If no available id could be generated, or if the value of the id member of the dictionary is taken by an existing RTCDataChannel , throw a ResourceInUse exception.

However, Chrome and Firefox seem to be doing something much simpler, for `new RTCPeerConnection().createDataChannel('').id` both simply return 65535.

**Comment by taylor-b** [comment]
The default value should be `null`; this is what we decided with issue #795 during a virtual interim. So would adding this sentence to the paragraph above help?

> If the `id` attribute is `undefined` and the DTLS role of the SCTP transport hasn't been negotiated, the `id` attribute will return `null` until the DTLS role is negotiated by [setting an `RTCSessionDescription`](https://www.w3.org/TR/webrtc/#set-description).

**Comment by foolip** [comment]
For Web IDL dictionary members, the terminology is [present](https://heycam.github.io/webidl/#dfn-present) or not present, but it sounds like you're referencing both the `id` dictionary member and the `id` attribute on `RTCDataChannel` in that snippet. As part of the createDataChannel method, things can only depend on the current state of things, so the "until" bit would have to happen elsewhere, as part of to the DTLS being negotiated or some side-effect of it.

It'd be easier to review a PR. At some point it needs to say "If id is not present, then ...".

**Comment by taylor-b** [comment]
> it sounds like you're referencing both the id dictionary member and the id attribute on RTCDataChannel in that snippet

You're right, that needs a bit of wordsmithing to make it more clear.

> the "until" bit would have to happen elsewhere

It already does, in the "setting an RTCSessionDescription" steps. The "until" bit is just informative.

**Comment by foolip** [comment]
As long as informative bits have `class=note` that sounds good. Note that there is similar "until" language in https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-setconfiguration that isn't clearly separated from the normative bits.
