### ISSUE TITLE
Use [SameObject] for the FrozenArray<T> attributes that never change

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1138]
These are the readonly attributes of type `FrozenArray<T>` in the spec:
* [RTCPeerConnection](https://w3c.github.io/webrtc-pc/#interface-definition)'s `static readonly attribute FrozenArray<RTCIceServer> defaultIceServers`
* [RTCCertificate](https://w3c.github.io/webrtc-pc/#rtccertificate-interface)'s `readonly attribute FrozenArray<RTCDtlsFingerprint> fingerprints`
* [RTCTrackEvent]'s `readonly attribute FrozenArray<MediaStream> streams`

These seem like they will always return the same value. Documenting this with [SameObject] makes this obvious an means that tests can `assert_equals(certificate.fingerprints, certificate.fingerprints)` and similar, something that cannot be assumed from the current spec.

@henbos

**Comment by henbos** [comment]
Since it's an attribute and a frozen array it would seem expected that fingerprints == fingerprints even though returning by value wouldn't have any other implications since they're basically just strings.

**Comment by henbos** [comment]
It is my understanding that the fingerprints never change!

**Comment by foolip** [comment]
@henbos, care to write a PR for `fingerprints` matching what you want to implement?

**Comment by henbos** [comment]
Hang on, if dictionaries are always returned "by value", meaning they are copied, and the elements of FrozenArray\<T\> are mutable (its the references that are immutable of FrozenArray), then "SameObject" would be dangerous. To ensure dictionary are copied we need to return new FrozenArrays every time.

`certificate.fingerprints[0].foo = "bar"` should be possible if I understand WebIDL correctly, but that should not mess up future `certificate.fingerprints[0]` readings.

**Comment by henbos** [comment]
Since we have to return new fingerprints every time (dictionary copies) we have to return new arrays everytime. It seems rather pointless to use FrozenArray over sequence if its a new object every time? Though it documents constness to some extent.

**Comment by foolip** [comment]
It is indeed a bit silly that one can change the fingerprints but that this will have no effect on anything. An alternative is a `sequence< RTCDtlsFingerprint> getFingerprints()` method, which would return a new array (and objects within) every time. What would @domenic do?

**Comment by domenic** [comment]
There are two paths I guess:

1. getFingerprints() which returns mutable stuff
2. Do what the Notifications spec does and freeze the dictionaries too. This is becoming a common pattern and maybe we should be uplifting it to Web IDL. Actually the notifications spec does this wrong; it implies returning a new frozen array each time. Anyway, previous general discussion at https://www.w3.org/Bugs/Public/show_bug.cgi?id=29004

**Comment by henbos** [comment]
Considering _dictionaries are always passed by value_ when passed to/from a platform object (https://www.w3.org/TR/WebIDL-1/#idl-dictionaries) such as RTCCertificate, `sequence<RTCDtlsFingerprint> getFingerprints()` makes the most sense to me. Freezing the elements and using [SameObject] would make sense for interfaces where we can use the same reference every time. Doing so here would seem contradictory to what dictionaries are supposed to be.

Similarly it would make sense to replace `static readonly attribute FrozenArray<RTCIceServer> defaultIceServers()` with `static sequence<RTCIceServer> getDefaultIceServers()` because RTCIceServer is a dictionary. According to https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?page=1&q=RTCPeerConnection this is not implemented yet and would be easy to change.

The `readonly attribute FrozenArray<MediaStream> streams` case makes sense because MediaStream is an interface.

Shall I create a PR?

**Comment by henbos** [comment]
Note: freezing interfaces only makes sense for constants though, since freezing an interface affects all references to that interface. So FrozenArray\<MediaStream\> should not freeze its streams.

**Comment by foolip** [comment]
Aside: Web IDL is peculiar in that https://heycam.github.io/webidl/ is the URL being actively maintained.

**Comment by foolip** [comment]
`getFingerPrints()` and `getDefaultIceServers()` SGTM, with `[SameObject]` for the remaining `FrozenArray<MediaStream>`.

**Comment by domenic** [comment]
I don't think that's an accurate assessment of "what dictionaries are supposed to be". Or, perhaps, I don't think dictionaries are the right level of abstraction to be thinking about here. They're just a spec-writing tool. What JavaScript authors see are objects, and sometimes objects maintain their identity (frozen dictionaries or interfaces), and sometimes they don't (most dictionaries).

Regardless, if you're going with methods, probably don't include the `get` prefix.

**Comment by henbos** [comment]
webrtc-pc is consistently using the `get` prefix for methods.
