### ISSUE TITLE
"Firing an RTCTrackEvent event named e" is never referenced

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1141]
https://w3c.github.io/webrtc-pc/#fire-track-event

This definition is never referenced, and searching for "track event" the only relevant hit is in the introductory and seemingly non-normative text for https://w3c.github.io/webrtc-pc/#rtp-media-api: "... are surfaced to the application via the ontrack event."

It was when looking at https://github.com/w3c/webrtc-pc/pull/1129 that I wanted to know if the streams member would always have at least one member, but from the spec I cannot tell.

**Comment by foolip** [comment]
From https://github.com/w3c/webrtc-pc/issues/1135 I found that https://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks is where the event is fired, and it just isn't phrased/linked correctly.

**Comment by adam-be** [comment]
Looking through the spec we're pretty bad at referencing the "Firing an even named e"-sections. I found one link for a datachannel event.

**Comment by adam-be** [comment]
#1576 links up all event firings to their definitions.
