### ISSUE TITLE
"Callback definitions" section should go under "legacy interface extensions"

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1142]
... Since these callbacks are only used for the legacy interface extensions.

Also, `RTCStatsCallback` is not referenced anywhere. Did we forget to add a legacy `getStats` method? Or can we just remove `RTCStatsCallback`?

**Comment by fippo** [comment]
i'd prefer to remove it but then users of the legacy interface extensions will have to use a promise-based getStats.

**Comment by taylor-b** [comment]
It looks like we already decided to get rid of the legacy `getStats`, since there wasn't an interoperable legacy implementation in the first place. https://github.com/w3c/webrtc-pc/issues/924
