### ISSUE TITLE
legacy createAnswer: support for answerOptions?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1152]
4.3.3.1 currently defines the legacy createAnswer as
```
    Promise<void> createAnswer(RTCSessionDescriptionCallback successCallback,
                               RTCPeerConnectionErrorCallback failureCallback);
```
whereas the promise version allows passing RTCAnswerOptions:
```
    Promise<RTCSessionDescriptionInit> createAnswer(optional RTCAnswerOptions options);
```
Should it be possible to use the VAD option in the legacy version?

@henbos I think Chrome implemented the answer options in the non-promise version, can you check?

**Comment by henbos** [comment]
Yes, https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCPeerConnection.idl?q=RTCPeerConnection.idl&sq=package:chromium&dr&l=72

**Comment by henbos** [comment]
Wait, sorry, the VAD option?

**Comment by henbos** [comment]
The non-promise one has an optional mediaConstraints dictionary but it does not use RTCAnswerOptions.

**Comment by henbos** [comment]
The media constraints include something called "VoiceActivityDetection" which is a boolean, could it be the same thing?

**Comment by taylor-b** [comment]
It is. But it's still a constraints-based version of `createAnswer`, not an `RTCAnswerOptions` version.

**Comment by jan-ivar** [comment]
Good, since no browser supports the spec RTCAnswerOptions, there's no legacy code expecting it to work, and no reason to spec it in legacy createAnswer.

In other words, Chrome can continue to support its non-spec parameter, but there's nothing other browsers must do to support legacy code here.

**Comment by fippo** [comment]
so the only action item is to add a note pointing out that this is not supported? (principle of least surprise)

**Comment by jan-ivar** [comment]
@fippo There's no legacy code using this. People shouldn't write new code using legacy APIs. Who would be surprised?

**Comment by stefhak** [comment]
Taylor will do a PR that adds a note.
