### ISSUE TITLE
The "set an RTCSessionDescription" algorithm is unreferenced

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1155]
https://w3c.github.io/webrtc-pc/#set-description

Presumably this algorithm should be invoked by setLocalDescription and/or setRemoteDescription.

Found while reviewing https://github.com/w3c/web-platform-tests/pull/5748

**Comment by jan-ivar** [comment]
Search for "setting the RTCSessionDescription".

It is referenced in step 8 in [setLocalDescription](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-setlocaldescription()) and by [setRemoteDescription](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-setremotedescription), just not verbatim.

There's something screwy with the SLD and SRD links themselves, as most of them point to the legacy section. That may be confusing things.

**Comment by foolip** [comment]
OK, so this is invalid as stated. Using Bikeshed would be great, so that one can follow definitions back to where they are used.
