### ISSUE TITLE
Lack of validation in RTCIceCandidate constructor

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1165]
There is no validation requirement for the arguments inside `RTCIceCandidate` constructor other than that `sdpMid` and `sdpMLineIndex` must not be both `null`. This seems to imply that the values in `RTCIceCandidateInit` can be anything as long as they are of valid type.

I suspect that the rationale for this is that the actual validation is only done when the candidate is passed to `addIceCandidate`. If so it is helpful to put a note in the `RTCIceCandidate` constructor section.

I also have difficulty understanding the use of the other fields in `RTCIceCandidate` that are not in `RTCIceCandidateInit`. Since these fields are read only there doesn't seem to have way to set their values at all. There is also no place in the spec where these fields are being read, including `addIceCandidate`.

**Comment by foolip** [comment]
I also filed https://github.com/w3c/webrtc-pc/issues/1166

**Comment by stefhak** [comment]
If adding a note is enough then this is editorial.

**Comment by foolip** [comment]
"There is also no place in the spec where these fields are being read, including addIceCandidate" is not an editorial issue.

**Comment by rwaldron** [comment]
It struck me as odd that: 

> sdpMid of type DOMString, readonly, nullable
> sdpMLineIndex of type unsigned short, readonly, nullable

That is: both are nullable, but then...

> When run, if both the sdpMid and sdpMLineIndex dictionary members are null, throw a TypeError.

**Comment by foolip** [comment]
That's a case where Web IDL syntax can't express the constraints, and so it's done in prose instead. If a single dictionary member is required, the required keyword is used, but if it's more complicated, then things end up looking like this...

**Comment by soareschen** [comment]
This is now fixed by #1229.
