### ISSUE TITLE
RTCIceCandidate constructor should not require sdpMid/sdpMLineIndex

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1166]
https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate

Here's a small test for how the constructor behaves in current implementation:
https://jsbin.com/qiloyuf/edit?html,output

Testing in Chrome, Edge and Firefox. None throw for missing sdpMid/sdpMLineIndex, but:
 * Chrome requires candidate to be a non-empty string
 * Edge doesn't require any arguments at all
 * Firefox requires candidate to be present, but an empty string is OK

The safest way to align the spec with this is to require no arguments at all, matching Edge.

**Comment by stefhak** [comment]
I'm convinced that implementations not fulfilling the spec presently is a reason to remove the requirement.

**Comment by taylor-b** [comment]
Bernard said he believes Edge accepting no arguments is a bug. And Chrome will support the empty string when we implement the "end-of-candidates" signaling. So I don't think any change to the spec is necessary.

**Comment by foolip** [comment]
@taylor-b, happy to hear that `new RTCIceCandidate({ candidate: '' })` won't throw exceptions in Chrome for long, it makes no sense to distinguish between that and `new RTCIceCandidate({})` when candidate's default value is the empty string.

My main point in this bug is that *no engine* currently requires one of sdpMid/sdpMLineIndex to be present, and adding that requirement comes with a compat risk, as any code in the wild that doesn't include one of these will start throwing. Perhaps there's a very good reason for that, but at first glance it seems better to just align the spec with what is already shipping.

**Comment by foolip** [comment]
@soareschen, can you make sure that https://jsbin.com/qiloyuf/edit?html,output is covered in web-platform-tests, so that we have tests failing in all browsers for this? @rwaldron FYI

**Comment by soareschen** [comment]
Sure, it is good to clear the confusion around the constructor for RTCIceCandidate. With this, #1153 and #1165 I can write proper tests now.

So is it correct to say that the headline for this issue is no longer valid, and the issue can be closed?

And can you attach the code snippet here? JS Bin website is not working.

**Comment by foolip** [comment]
This issue should remain open, it tracks the fact that we have both an interop problem (3 different behaviors if you look closely) and a spec-implementation mismatch.

It looks like the current behavior was introduced in https://github.com/w3c/webrtc-pc/pull/606 and I see no discussion of the compat implications or comments from implementers, so this looks like an oversight. If implementers really do want to make this change, then that's fine, although it *appears* to be an unnecessary risk to me.

**Comment by foolip** [comment]
@soareschen, I don't have a copy outside of jsbin.com, I suppose it'll come back online sooner or later. It doesn't matter much, it's just a matter of creating an exhaustive RTCIceCandidate-candidate.html test, that will reveal the same thing again.

**Comment by foolip** [comment]
It's back up, and this is what is was:
```JavaScript
[
  'new RTCIceCandidate',
  'new RTCIceCandidate({})',
  'new RTCIceCandidate({ candidate: ""})',
  'new RTCIceCandidate({ candidate: "foo"})',
].forEach(expr => {
  test(() => eval(expr), expr);
});
```

**Comment by foolip** [comment]
(That was just to see what would throw, it doesn't match what the spec says.)

**Comment by taylor-b** [comment]
> My main point in this bug is that no engine currently requires one of sdpMid/sdpMLineIndex to be present, and adding that requirement comes with a compat risk, as any code in the wild that doesn't include one of these will start throwing.

I don't think this matters much, since any code in the wild doing that would fail immediately afterwards inside `addIceCandidate`. But if we want to do all the parameter checking in `addIceCandidate`, I don't see a problem with that; there's less duplication that way.

**Comment by soareschen** [comment]
I have submitted w3c/web-platform-tests#5917 to test the behavior of RTCIceCandidate constructor. Note that I follow the current editor draft to throw error if either `sdpMid` or `sdpMLineIndex` are null.

**Comment by rwaldron** [comment]
@foolip 

> The safest way to align the spec with this is to require no arguments at all, matching Edge.

I agree, this needs to land: https://github.com/w3c/webrtc-pc/pull/1153. Also, there is clarity needed for the 

@soareschen 

> Note that I follow the current editor draft to throw error if either sdpMid or sdpMLineIndex is null.

I think you meant "if both"? They are nullable, so they are allowed to be null... except: 

> When run, if both the sdpMid and sdpMLineIndex dictionary members are null, throw a TypeError.

But there seems to be some disagreement in how that's interpreted.

**Comment by soareschen** [comment]
> I think you meant "if both"?

Yes I meant both. So confusing. :)

FYI I found some discussion at #1078 addressing this confusion as well.

**Comment by foolip** [comment]
>> When run, if both the sdpMid and sdpMLineIndex dictionary members are null, throw a TypeError.
>
> But there seems to be some disagreement in how that's interpreted.

Because the dictionary members have a default value (null) I think this is unambiguous. The case where they are omitted need not be called out, because this prose operates on an IDL dictionary (not a JavaScript object) where it's impossible for them to be missing.

**Comment by stefhak** [comment]
@foolip @soareschen is there anything more we need to do here? If not I will close this issue.

**Comment by soareschen** [comment]
Yes this can be closed now. Thanks!

**Comment by foolip** [comment]
@taylor-b, do you have a Chromium bug for matching the spec on this point? If https://github.com/w3c/webrtc-pc/issues/1166#issuecomment-301128876 is correct then it should be safe, but it would be good to try it ASAP so that the spec can be fixed if it's actually not web compatible.

With such a bug filed, there's nothing further to do here.

**Comment by taylor-b** [comment]
Filed: https://bugs.chromium.org/p/chromium/issues/detail?id=735422

**Comment by stefhak** [comment]
Closing.
