### ISSUE TITLE
degradationPreference shouldn't have a default at the WebIDL level

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1173]
The fact that it has a default at the WebIDL level means that `receiver.getParameters` will always return `degradationPreference: "balanced"`, which doesn't make sense. Instead, we should specify that the `RTCRtpSender` has an internal degradation preference that defaults to "balanced", and `RTCRtpReceiver.getParameters` returns nothing for it.

**Comment by aboba** [comment]
@taylor-b  Is the issue that `degradationPreference` has no meaning for an `RTCRtpReceiver`? Or is there a more generic problem with returning a default value before an attribute has been set, possibly confusing the developer as to its eventual value?  Just trying to understand whether there is an issue with any other attribute in`RTCRtpParameters` that uses defaults: 

`RTCRtpEncodingParameters.scaleResolutionDownBy = 1`
`RTCRtpCodecParameters.channels = 1`

**Comment by taylor-b** [comment]
The issue is mostly that it has no meaning for an `RTCRtpReceiver`. `scaleResolutionDownBy` is in a similar position.

And really, there's no value in having default values in WebIDL for _anything_ in `RtpParameters`, since you're always expected to do `getParameters` followed by `setParameters`. If a parameter has a default value, `getParameters` should have returned it, and it doesn't need a default at the WebIDL level for that to happen.
