### ISSUE TITLE
Some JSEP "applying a description" steps can't occur in parallel.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1177]
The "apply a description according to JSEP" step is described as occurring entirely in parallel. But some of the JSEP steps involve creating transceivers (from new "m=" sections in a remote description) or changing their `mid` attribute, which can't occur in parallel.

So, would it be acceptable to say "In parallel, apply the description according to JSEP, performing all steps except those that modify the set of transceivers," calling out the transceiver-related steps in the "queued task" section (which we already do for the most part)?

**Comment by burnburn** [comment]
Is this clear enough?  As in, do you think the transceiver-related steps to be done are described well enough elsewhere that here you can just say to leave out modification of transceivers?

**Comment by taylor-b** [comment]
@burnburn The only transceiver modifications described by JSEP for applying a description are:

- Setting/unsetting the `mid` attribute.
- Creating a new transceiver to represent a new "m=" section added by a remote offer.

Are those modifications described well enough in WebRTC 1.0? Not quite, but they should be; that's part of what I'm suggesting.

**Comment by taylor-b** [comment]
Actually, given that the "applying a description" steps explicitly call out creating transceivers/setting MIDs in the "queued task" part, I think it's obvious enough that "in parallel, apply description according to JSEP" doesn't include those things. So I'm closing this.
