### ISSUE TITLE
Need to describe when ICE and DTLS transport objects are created/changed

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1178]
The specification mentions that:

> RTCDtlsTransport objects are constructed as a result of calls to setLocalDescription() and setRemoteDescription().

But it needs to go into more detail. Which `setLocalDescription`/`setRemoteDescription` calls cause the transports to be created (and returned by the sender/receiver `transport` attribute)? Only local descriptions? Any offer? The "applying a description" steps should answer this question.

We should also describe when the transports are changed as a result of bundling/RTCP muxing being negotiated.

**Comment by aboba** [comment]
@taylor-b Agree that more detail is needed.

**Comment by fippo** [comment]
coming from an ORTC point of view: how do generate ice-ufrag et al in createOffer without creating an ice transport (or in ORTC a gatherer but we dont have that here)?

I can see how this works for the DTLS transport since you fingerprints come from the certificate (if passed; I assume a certificate is generated if none is passed)

**Comment by taylor-b** [comment]
Well, the ORTC binding could create the `RTCIceGatherer` at the same time as the `RTCRtpTransceiver`, but then only create the `RTCIceTransport` (or only set it on the sender/receiver) when a description is set.

**Comment by aboba** [comment]
Related Issue https://github.com/w3c/webrtc-pc/issues/1406

**Comment by aboba** [comment]
From https://www.w3.org/2017/06/28-webrtc-minutes

Resolution: the group agrees with Taylor's suggestion.  Taylor will create an PR

**Comment by stefhak** [comment]
The resolution (https://github.com/w3c/webrtc-pc/issues/1178#issuecomment-318239760) was confirmed at the September VI.
