### ISSUE TITLE
editorial: 4.3.1 Operation "settled" is not defined

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1189]
> If subsequent calls are made while the returned promise of a previous call is still not settled, they are added to the queue and executed when all the previous calls have finished executing and their promises have settled.

This is promise terminology (and we don't say in the terminology section where we define that) which is only used in that paragraph and not even in the algorithm description below.

I think the first occurence could be avoided by saying "still pending" ([this](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md) 'defines' "settled" as "not pending"). For the second use I actually prefer "settled" to "fulfilled or rejected"

**Comment by burnburn** [comment]
@adam-be please review.
