### ISSUE TITLE
editorial: currentLocalDescription getting updates with candidates

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1192]
http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-currentlocaldescription
says (and a similar thing happens with pendlingLocalDescription and the corresponding remote descriptions)

> any local candidates that have been generated by the ICE Agent since the offer or answer was created.

and then repeats "plus the candidates" immediately

> complete with any local candidates that have been generated by the ICE Agent since the offer or answer was created.

I think removing the first occurence will not harm the technical requirements.

> Note that the value of currentLocalDescription.sdp need not match the value of localDescription.sdp.

This should be moved to the first paragraph since it is not a statement about the return value.

**Comment by fippo** [comment]
Done. I also wondered if the sentence about the pending* being null should be in the paragraph about the return value

**Comment by alvestrand** [comment]
I see that the current/pending local description are now described in terms of internal slots, and there's just one normative statement on adding candidates to them.
Closing this one as "overtaken by events".
