### ISSUE TITLE
editorial: createOffer description

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1193]
http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-createoffer

has a weird structure which makes it hard to understand. It think it is easy to improve. Some nitpicking first:

> including descriptions of the local MediaStreamTracks attached to this RTCPeerConnection, the codec/RTP/RTCP options supported by this implementation, 

s/options supported by this implementation/capabilities of this implementation/
would make it clearer that there is little relationship between those options and the options argument.

> and any candidates that have been gathered by the ICE Agent.

Typically the candidates won't be included (because trickle). But more importantly, the offer contains the ICE username fragment and password.

The second paragraph seems to expand upon the codec/RTP/RTCP options while carefully avoiding to use any of those words.

The third paragraph makes a general statement about the lifetime. I think its better to move it up before the second paragraph.
> Calling this method is needed to generate the ICE username fragment and password.
This last sentence expands upon the ICE description earlier but does so in a "oh btw" which is rather unhelpful. Should be split into a new paragraph and expanded a bit to include the "candidate" stuff mentioned in the first paragraph.

The fourth paragraph should probably mention that the certificates are also used to create the dtls transports later.

**Comment by fippo** [comment]
Moar nitpicking:
> for each SDP line, the generation of the SDP must follow the appropriate process for generating an offer

this seems backwards. The SDP lines are generated by the process for generating an offer. Also, generation of the SDP might be misinterpreted as referring to generation from trickle-ice.

This would be much shorter:
> The SDP is generated according to the process described in JSEP


Also: JSEP (which I assume is where the process for generating an offer is defined) calls this 'constructing an offer' now.

**Comment by burnburn** [comment]
@fippo Can you please generate one or more PRs for this?  I will assign to Bernard for review.
