### ISSUE TITLE
audioLevel of tracks, both send and receive?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1194]
RTCRtpSynchronizationSource defines audioLevel, but only for receiving packets (RTCRtpReceiver).
Does it make sense to expose this for sending tracks too? Should RTCRtpSender have getSynchronizationSources() for last sent packets?

**Comment by aboba** [comment]
For an RtpReceiver, getSynchronizationSources() could be used to provide a level indicator in a P2P (mesh) conference.  Is there a scenario for usage with an RtpSender that could not be handled with WebAudio?

**Comment by aboba** [comment]
Recommendation from TPAC is not to add this: 
https://www.w3.org/2017/11/06-webrtc-minutes.html
