### ISSUE TITLE
Stream IDs MUST be generated according to mediacapture-main, but webrtc-pc contradicts this

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1196]
Comment from @Pehrsons on #1161:

>The current draft of mediacapture-main even says that stream ids `MUST` always be generated. It doesn't allow for the `id` to be transferred from the remote side as it does for `MediaStreamTrack`.
>
>Of course webrtc-pc contradicts this by saying
>> When a MediaStream is created to represent a stream obtained from a remote peer, the id attribute is initialized from information provided by the remote source. 

The relevant part of mediacapture-main is:

> When a MediaStream object is created, the User Agent must generate an identifier string, and must initialize the object's id attribute to that string.

**Comment by fippo** [comment]
so update mediacapture-main with something like this:
```
Unless a MediaStream object is created as a part of a special purpose algorithm that specifies how the stream id must be initialized, the User Agent must generate an identifier string and initialize the object's id attribute to that string
```
which i stole from the track id description with slight modifications or is this the nail in the coffin of #1128?

**Comment by taylor-b** [comment]
That sounds good to me.

**Comment by jan-ivar** [comment]
Me too. I think the intent was always for webrtc to do this to both stream.id and track.id, not just to track.id.
