### ISSUE TITLE
RTCPeerConnectionIceEvent parameter: RTCPeerConnectionIceEventInit eventInitDict is optional

### ISSUE THREAD

**Issue by rwaldron** [w3c/webrtc-pc#1199]
The parameter table under https://w3c.github.io/webrtc-pc/#rtcpeerconnectioniceevent appears as: 

| Parameter	|Type	| Nullable| 	Optional |	Description | 
|-------------|---------|---------|--------------|----------------|
| type|DOMString|✘|✘	| 
| eventInitDict|RTCPeerConnectionIceEventInit|✘|✘	| 

However the IDL above it: 

```webidl
[Constructor(DOMString type, optional RTCPeerConnectionIceEventInit eventInitDict)]
interface RTCPeerConnectionIceEvent : Event {
    readonly attribute RTCIceCandidate? candidate;
    readonly attribute DOMString?       url;
};
```

Which includes the `optional` keyword. I think the table just needs to be updated

**Comment by adam-be** [comment]
This was fixed in #1154
