### ISSUE TITLE
what is the component for a icetransport of a datachannel?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1201]
from @stefhak's question https://github.com/w3c/webrtc-pc/pull/1170#discussion_r115938486

> what's the component if it is for a data channel?

That was for candidates where one could use http://w3c.github.io/webrtc-pc/#dom-rtcicecomponent
Which is defined as 
```
enum RTCIceComponent {
    "rtp",
    "rtcp"
};
```
which makes it awkward because the component will be "rtp" even though we're transporting SCTP, not RTP

**Comment by fippo** [comment]
oh, the spec gives the answer:
```
The ICE Transport is used for RTP (or RTP/RTCP-multiplexing), as defined in [ICE], Section 4.1.1.1. Protocols multiplexed with RTP (e.g. data channel) share its component ID.
```
not pretty but wfm. Close this?

**Comment by taylor-b** [comment]
Yeah, I think that covers it.
