### ISSUE TITLE
Need to identify if changes affect JSEP or MSID specs

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1202]
There are discussions ongoing here that may lead to changes that could affect those IETF specs. Raising this issue to make sure we don't forget.

**Comment by fluffy** [comment]
@stefhak  can you add anything about which discussions or issue you are thinking of and I will try and make sure the get tracked on JSEP too

**Comment by stefhak** [comment]
@fluffy as far as I remember this came up in the discussion about Transceivers and ICE candidates. @taylor-b do you remember more?

**Comment by taylor-b** [comment]
Well, we were talking about getting rid of track ID signaling (and only signaling stream IDs instead). Which would obviously require changing the MSID spec, and JSEP. I don't remember if there was something else.
