### ISSUE TITLE
setDirection needs an internal slot and an algorithm.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1204]
[direction](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-direction) says: *"The value of direction does not change except due to calls to setDirection."*

That seems wrong, as it appears to be changeable through addTrack and removeTrack as well.

[addTrack](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack) uses the phrase *"Enable sending direction ... "*.

[removeTrack](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-removetrack) says: *"set transceiver.direction to recvonly."*

Unfortunately, direction is a read-only attribute, so that doesn't work.

Even [setDirection](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setdirection) itself violates this: *"Set transceiver.direction to newDirection."*

Instead, I think transceiver needs a [[direction]] internal slot, and a set direction algorithm reused by the three places.

**Comment by taylor-b** [comment]
The use of terminology like "set transceiver.direction to newDirection" is a more general problem, which I tried to summarize in issue #1112. @jan-ivar, could you weigh in on that issue?

**Comment by adam-be** [comment]
#1321 adds internal two internal slots [[Direction]] and [[CurrentDirection]]

**Comment by taylor-b** [comment]
I think this is resolved by #1321. Closing.

**Comment by taylor-b** [comment]
Nevermind. The remaining work to be done is that `addTrack` and `removeTrack` should reference the same "set direction" algorithm.
