### ISSUE TITLE
Setting a remote description may cause discontinuity due to codec switching.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1207]
If an application is using `sender.setParameters` to select the sent codec, this gets wiped out when `setRemoteDescription` is called:

> The effect of reordering or removing codecs lasts until the codecs are renegotiated. After the codecs are renegotiated, they are set to the value negotiated, and setParameters needs to be called again to re-apply codec preferences.

It's a little inconvenient from an API perspective to need to call `setParameters` every time `setRemoteDescription`'s promise resolves. But the bigger issue is that one frame might end up encoded with an unintended codec before the application has a chance to switch. And it wouldn't be surprising if this causes a blip on the receive side.

Is there any reason we can't use [`codecPayloadType`](http://draft.ortc.org/#dom-rtcrtpencodingparameters-codecpayloadtype) like ORTC has, and say that once set, it doesn't change (unless the PT is removed from the remote description)? Neither Chrome nor Firefox have implemented the `setParameters` codec reordering yet, so I don't think there are backwards compatibility concerns.

**Comment by stefhak** [comment]
From: https://lists.w3.org/Archives/Public/public-webrtc/2017Jun/0057.html

"ACTION: Taylor to draft text for preferences not being blown away (and 
explain how that works when the new offer contains codecs that are 
completely different than the original one)"
