### ISSUE TITLE
RTCIceCandidate: how is extensibility handled?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1211]
http://w3c.github.io/webrtc-pc/#rtcicecandidate-interface
defines a number of attributes of the RTCIceCandidate that should be pre-parsed from the candidate string. While implementing a shim for this I noticed that my parser was emitting two additional attributes, generation and [network-cost](https://tools.ietf.org/html/draft-thatcher-ice-network-cost-01)
```
Candidate:3805835391 1 udp 2113937151 192.168.0.107 57917 typ host generation 0 
ufrag 7POS network-cost 50
```

https://tools.ietf.org/html/rfc5245#section-15.1 allows extensibility (extension-att-name and extension-att-value) so this section should at the very least mention what happens with those extra attributes.

This might be somewhat tricky since e.g. when Firefox does not implement network-cost and therefore parsing a candidate from Chrome in the constructor will at best return a string network cost "50" while a browser that understands this will return an integer 50.
This might imply that this parsing is easier to be done in a javascript library which will give a consistent answer across browsers. So far nobody has implemented this even though I have a [PR for adapter.js to shim it](https://github.com/webrtc/adapter/pull/527).

**Comment by taylor-b** [comment]
I don't think WebRTC 1.0 needs to handle this. If an application really needs to inspect non-standard attributes, it's already possible to parse the candidate string in JS; the `RTCIceCandidate` attributes are just there for convenience.

**Comment by fippo** [comment]
But if you sometimes have to parse the candidate to find out what you need you can just as well unconditionally parse it myself and get consistent behaviour.

I really like this as a convenience function for onicecandidate. And if the effort to specify it is too high then i think it should be left to javascript.

**Comment by rwaldron** [comment]
@taylor-b I need a little more clarification, I appreciate your patience. Can you explain how the values of these properties are populated? (from https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface)

- [ ] `foundation`
- [ ] `priority`
- [ ] `ip`
- [ ] `protocol`
- [ ] `port`
- [ ] `type`
- [ ] `tcpType`
- [ ] `relatedAddress`
- [ ] `relatedPort`



@foolip 

> And if the effort to specify it is too high then i think it should be left to javascript.

I think it could be as simple as adding the following sentence (or something similar) to each property definition: 

"The value of [this property foo] must be the corresponding value derived from parsing the candidate-attribute string as described by [15.1](https://tools.ietf.org/html/rfc5245#section-15.1) of [[ICE]](https://tools.ietf.org/html/rfc5245). If no corresponding value is present, the value must be `null`."

**Comment by rwaldron** [comment]
I've deleted the previous comment that I posted as I realized that I had responded to the wrong issue thread. I apologize for any bizarre confusion that may have caused 😬
