### ISSUE TITLE
Can we directly link to WebRTC-Stats for RTCStatsType?

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/webrtc-pc#1212]
Current the spec [defines an empty RTCStatsType enum](http://www.w3.org/TR/webrtc/#rtcstats-dictionary) and then explains about the emptiness. Can we just directly link to http://www.w3.org/TR/webrtc-stats/#dom-rtcstatstype to prevent this empty IDL, as the spec already does on e.g. [EventHandler](http://www.w3.org/TR/webrtc/#rtcsctptransport-interface)?

**Comment by henbos** [comment]
Other things that are defined in other specs are linked to Terminology where they are listed and a link provided to the other spec, e.g: "The terms MediaStream, MediaStreamTrack, and MediaStreamConstraints are defined in [GETUSERMEDIA]." That would make sense to do for stats stuff.
