### ISSUE TITLE
Rollback: a feature "at risk"?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1215]
The question has arisen as to whether rollback should be marked as a feature at risk.  What is the implementation status?

**Comment by aboba** [comment]
@ekr @juberti  Can you comment?

**Comment by fluffy** [comment]
There is no way to deal with broad classes of error handing without rollback. For example, A and B have a session going and are in stable state. A wants to change the session and sends a new offer to the server. The server can't send it to B and sends back an error to A of "websock to B temporarily not available". At this point A needs to rollback the change to get back to a stable state.

**Comment by fluffy** [comment]
I will note that what in JSEP there are place where if an error occurs, the implementation are required to "session MUST be restored to the state it was in before" which is not easy to implement but amounts to much the same as implementing rollback.

**Comment by aboba** [comment]
This was discussed at the virtual interim on June 28.  rollback has been implemented in FF, and there is implementation interest from Chrome, so it should not be marked as a "feature at risk".
