### ISSUE TITLE
Clarify addIceCandidate behavior when adding candidate after end of candidate

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1216]
Related to #1213.

If new ICE candidate for a media stream is added after `addIceCandidate` is called with empty string `candidate.candidate`, should that be an error?

I suspect it should result in `OperationError` when adding that to the ICE agent. But there isn't any normative definition to mandate that in any spec. This should be guarded in webrtc-pc so that the behavior can reliably be tested.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?

**Comment by soareschen** [comment]
Will do. I will make it throw `InvalidStateError` if `addIceCandidate` is called after end-of-candidates indication is given.

**Comment by soareschen** [comment]
Reflecting back on this, I think it is not a good idea to restrict call to addIceCandidate after end of candidate is added. There may be multiple ICE generations as well as ICE restart, and quite frequently clients can get disconnected and change network. 

The ICE agent should be able to handle all different scenarios, so applications should be able to forward any ICE candidate event to the remote peer regardless of the end of candidate status. It is sufficient to say that adding past end of ICE candidate _may_ cause the ICE agent to fail and return `OperationError`, and let the ICE transport handle such state management.

Closing this issue then.
