### ISSUE TITLE
Missing References to JSEP spec

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1217]
There have been a few times when I failed to find any normative definition for some behavior in webrtc-pc, only to found it later in JSEP. Some examples:

- No normative definition of valid state transitions for `RTCSignalingState`.
- `setLocalDescription` triggers ICE candidate gathering process.

If it is alright I will submit PRs to add reference to JSEP whenever I find one missing.

**Comment by burnburn** [comment]
Yes, @soareschen that would be great.  Thanks!

**Comment by soareschen** [comment]
The first part has been fixed in master branch. The second part has been evolved to #1422. Closing this issue.
