### ISSUE TITLE
Default ufrag for addIceCandidate when there are different ufrags in SDP

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1219]
Is it right to say that an SDP for remote description may have different ufrag for each media stream? i.e. when bundling is not supported. 

If so, when calling `addIceCandidate` with undefined ufrag, does "the most recent ICE generation" means that it is associated with the ufrag of the last media stream? 

And does this mean that in this case when adding ICE candidate for earlier media streams, the ufrag must be specified or it would result in error?

**Comment by taylor-b** [comment]
`addIceCandidate` requires an `sdpMid` or `sdpMLineIndex`, which identifies which media stream the candidate is being added for. So if `ufrag` is absent, the candidate is assumed to belong to the last ICE generation used by that "m=" section.

For example, if SRD is called with:

```
m=video ...
a=mid:video
a=ice-ufrag:video_ufrag_1
...
m=audio ...
a=mid:audio
a=ice-ufrag:audio_ufrag_1
```

And later with:

```
m=video ...
a=mid:video
a=ice-ufrag:video_ufrag_2
...
m=audio ...
a=mid:audio
a=ice-ufrag:audio_ufrag_2
```

Then if `addIceCandidate` is called with `{sdpMid: "audio", candidate: "..."}` with no ufrag, the candidate is assumed to belong to the ICE generation identified by "audio_ufrag_2".

Does this make sense? Is there a way the spec could be reworded to make this more clear?

**Comment by soareschen** [comment]
Thanks for clarifying. The description for the terms "ICE generation" and "ICE session" are pretty short so I wasn't very sure if different ufrags, e.g. `video_ufrag_1` and `audio_ufrag_1`, implies different ICE generation.

The thing that isn't very clear in the spec is that the following call to `addIceCandidate` would have been invalid because the ufrag and sdpMid mismatch:

```javascript
addIceCandidate({
  candidate: '...',
  sdpMid: 'video',
  ufrag: 'audio_ufrag_1'
});
```

However if the ufrag is left empty, it is not clear how the implementation figure that the correct ufrag for `sdpMid: video` is `video_ufrag_1` and not `audio_ufrag_1`.

This issue don't usually arose because current browsers generate the same ufrag for all media streams in an SDP. So it is not very clear how they should behave if they receive remote SDP containing different ufrags.

I think to fix this, we just need to update step 6 of `addIceCandidate` from:

> Use candidate.ufrag to identify the ICE generation; if the ufrag is null, process the candidate for the most recent ICE generation. If candidate.candidate is an empty string, process candidate as an end-of-candidates indication for the corresponding media description and ICE candidate generation.

to:

> Use candidate.ufrag to identify the the corresponding media description and ICE generation; if the ufrag is null, process the candidate for the corresponding media description and the most recent ICE generation. If candidate.candidate is an empty string, process candidate as an end-of-candidates indication for the corresponding media description and ICE candidate generation.

**Comment by soareschen** [comment]
Just realized the latest tip of tree draft has already updated the description, which is much clearer.

> Use candidate.ufrag to identify the ICE generation; if the ufrag is null, process the candidate for the most recent ICE generation. If candidate.candidate is an empty string, process candidate as an end-of-candidates indication for the corresponding media description and ICE candidate generation.

So then one more clarification needed is that "corresponding media description" is determined through `sdpMid` or `sdpMLineIndex` in step 3 or step 4.

**Comment by aboba** [comment]
Yes, each m-line could have a distinct ufrag.  For example, in ORTC, each RTCIceGatherer has a unique ufrag.  However, not all implementations will have a distinct ufrag for each m-line. 

@soareschen Can you submit a PR?

**Comment by soareschen** [comment]
Yes will do.

**Comment by stefhak** [comment]
@soareschen what's the status of this one now? Are you planning to author a PR?

**Comment by aboba** [comment]
Closing this issue due to lack of a response.
