### ISSUE TITLE
Invalid value for maxBitrate

### ISSUE THREAD

**Issue by jianjunz** [w3c/webrtc-pc#1223]
In an `RTCRtpParameters` object, if `RTCRtpEncodingParameters.maxBitrate` is below one of `codec`'s valid range, what's the expected result when `setParameters` is called with such an `RTCRtpParameters`? Maybe we need to add some description for this case.

For example, the valid bitrate range for Opus is 6 kbit/s to 510 kbit/s. What happens if `RTCRtpEncodingParameters.maxBitrate` is set to 5 kbit/s.

IMHO, possible solutions could be
- Silently remove the codec that only works above `RTCRtpEncodingParameters.maxBitrate`
- Return a promise rejected with a newly created `RangeError`

**Comment by taylor-b** [comment]
This relates to issue #763 (simulcast errors), and the corresponding PR, #1150. This seems like a situation where it would be reasonable to return an "invalid-encoding-parameters" RTCError, assuming we continue in that direction.

**Comment by jianjunz** [comment]
Thanks for pointing out. It is covered by the issue and PR you mentioned above.
