### ISSUE TITLE
RTCIceCandidate and candidate string parsing requirements

### ISSUE THREAD

**Issue by rwaldron** [w3c/webrtc-pc#1224]
In https://github.com/w3c/web-platform-tests/pull/5917#pullrequestreview-38431577, I included all of the properties of an RTCIceCandidate object for coverage. My understanding is that RTCIceCandidate constructor is expected to parse the contents of the provided candidate string and assign the resulting values to their corresponding instance properties, by correlating the named fields in https://tools.ietf.org/html/rfc5245#section-15.1 to their respective instance property. @soareschen [pointed out](https://github.com/w3c/web-platform-tests/pull/5917#issuecomment-302285678) that there is actually no explicit, normative prose that describes an expectation of parsing the string. 

Tangentially related, @fippo mentions writing a parser for candidate strings in this issue:  https://github.com/w3c/webrtc-pc/issues/1211 which supports the expectation I described above.

**Comment by soareschen** [comment]
This is now fixed by #1229.
