### ISSUE TITLE
Confusion on currentRemoteDescription.sdp need not match remoteDescription.sdp

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1228]
I was reading #921 and found #1004 that added:

> Note that the value of currentRemoteDescription.sdp need not match the value of remoteDescription.sdp.

When I read the sentence I interpreted it as they may be different because localDescription may point to pendingLocalDescription instead. Didn't expect that to be related to #921.

**Comment by aboba** [comment]
Is there a proposed change that would make this more clear?

**Comment by soareschen** [comment]
I think the note applies to both pending and current descriptions. It can be added as a general note under the attributes section as:

- Note that the string value of `sdp` in `pendingRemoteDescription`, `currentRemoteDescription`, `pendingLocalDescription`, and `currentLocalDescription` need not be identical to the `description.sdp` value passed to the corresponding `setRemoteDescription` or `setLocalDescription` calls. e.g. the SDP lines can be reordered and modified.
