### ISSUE TITLE
legacy methods: when are they called?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1231]
http://w3c.github.io/webrtc-pc/#legacy-interface-extensions
describes the "legacy" interface. However, there is no description for when these are called.
This decision is typically made based on the number of arguments to the function call and the type of the first argument (e.g. in createOffer)

Also: what error is thrown if the failureCallback is missing?

**Comment by adam-be** [comment]
The legacy methods overloads their modern counterparts so we're relying on the overloading functionality of WebIDL and not specifying anything explicitly. Same thing goes for the missing argument; the error would be a TypeError.
