### ISSUE TITLE
RTCPeerConnectionIceEvent constructor validation

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1232]
In the description for `RTCPeerConnectionIceEvent`:

> When firing an RTCPeerConnectionIceEvent event that contains a RTCIceCandidate object, it must include values for both sdpMid and sdpMLineIndex.

It is not very clear when does the requirement applies. Does this mean that the constructor would perform the validation and throw an error if either `sdpMid` or `sdpMLineIndex` is null? Or does this mean that an `RTCPeerConnectionIceEvent` event object that is fired from the `icecandidate` event is guaranteed by the browser to always have both `sdpMid` and `sdpMLineIndex` be not null?

**Comment by aboba** [comment]
The requirement is on the browser, so that the `icecandidate` event is guaranteed to always have both `sdpMid` and `sdpMLineIndex` non-null.
