### ISSUE TITLE
API to access certificate of remote side 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1234]
After the DTLS session is set up, there needs to be a way to get the certificate used by the other side for the case where a X.509 cert is used for identity (search for 509 in https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-12 to see more).

**Comment by aboba** [comment]
How does [RTCDtlsTransport.getRemoteCertificates() ](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#dom-rtcdtlstransport-getremotecertificates) fall short?

**Comment by fluffy** [comment]
Fixed by Bernard :-)

**Comment by fippo** [comment]
this is available via the getStats API too. But getRemoteCertificates is less confusing

**Comment by steely-glint** [comment]
Arguably, this is too late for identity purposes. 
To get a  RTCDtlsTransport you have to have either an  RTCRtpReceiver or an RTCSctpTransport 
To do that you have to have _accepted_ a media track or a DataChannel.
Ideally you want an boolean accept(Certificate) callback on the PeerConnection so you can refuse DTLS setup for certs that don't meet your criteria.
