### ISSUE TITLE
[[associated MediaStreams]] internal slot for RTCRtpSender is not used

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1237]
The only time the [[associated MediaStreams]] and [[send encodings]] internal slots are referenced in the spec is when setting the value. There is no mention of when these fields are read and how they are being used.

**Comment by aboba** [comment]
The [[associated MediaStreams]] internal slot does not seemed to be used. 

However, the[[send encodings]] internal slot is used in both setParameters and getParameters:

In `setParameters`:
"Let `N` be the number of `RTCRtpEncodingParameters` stored in sender's internal [[send encodings]] slot.... If `parameters.encodings.length` is different from `N` ..."

In `getParameters`: 
"`encodings` is set to the value of the [[send encodings]] internal slot."

**Comment by soareschen** [comment]
Yes, just saw the usage of `[[send encodings]]` was added to the 20170605 draft after this issue was raised.

**Comment by aboba** [comment]
@jan-ivar Any idea where this internal slot should be used?

**Comment by jan-ivar** [comment]
@aboba The [[[associated MediaStreams](http://w3c.github.io/webrtc-pc/#dfn-associated-mediastreams)]] is used to create the MSIDs in the SDP.

See the [final steps to create an offer](http://w3c.github.io/webrtc-pc/#dfn-steps-to-create-an-offer):
 * *"3. Given the information that was obtained from previous inspection and the current state of connection and its RTCRtpTransceiver s, generate an SDP offer, sdpString, as described in [JSEP] (section 5.2.)."*

[Section 5.2.1](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-5.2.1) says: *"For each MediaStream that was associated with the transceiver when it was created via addTrack or addTransceiver, an "a=msid" line, as specified in [I-D.ietf-mmusic-msid]"*

That seems to refer to the same thing. We should probably make that more explicit if we can.

**Comment by jan-ivar** [comment]
Nevermind that there's no way to associate a MediaStream with a transceiver using addTransceiver.

**Comment by stefhak** [comment]
@jan-ivar can you do a PR?

**Comment by adam-be** [comment]
As currently specified `[[AssociatedMediaStreams]]` is part of the information bundle that's used to create the SDP (as @jan-ivar points out above). I don't think we should start listing all the pieces of that bundle in step 3 of the algorithm. I've made a PR that adds some information about `[[AssociatedMediaStreams]]` and that it's used in the SDP generation process.

**Comment by jan-ivar** [comment]
Thanks @adam-be! I've been swamped.
