### ISSUE TITLE
rtp media api: when is a receiver created

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1241]
(possibly dupe into #1128 but i wanted to make sure this doesn't get lost)
http://w3c.github.io/webrtc-pc/#rtp-media-api
says
> RTCRtpReceiver s, on the other hand, are created when remote signaling indicates new tracks are available, and each new MediaStreamTrack and its associated RTCRtpReceiver are surfaced to the application via the ontrack event.

This contradicts what i learned from @jan-ivar in the other issue so the text here is misleading. Probably it just describes the pre-transceiver behaviour.

**Comment by taylor-b** [comment]
This seems like an editorial issue. We've already decided that receivers get created along with transceivers; this is just an obsolete paragraph that's carried over from pre-transceiver days.
