### ISSUE TITLE
rtcsessiondescription: attributes are not mutable

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1242]
http://w3c.github.io/webrtc-pc/#rtcsessiondescription-class
says
> Attributes on this interface are mutable for legacy reasons.

The IDL specifies them as readonly. I'm a bit confused by the back and forth but my reading of #573 is that they are not mutable in the spec anymore even if they still are in the wild. If that is the case this sentence should be removed.

**Comment by aboba** [comment]
@fippo Can you submit a PR?
