### ISSUE TITLE
setParameters woes

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1248]
http://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-setparameters

while I was overjoyed to learn that I do not have to go through an O/A cycle to change the bandwidth I am sending I have a couple of questions.

* what are the parameters modifyable by setParameters? I assume ptime (within the bounds of maxptime from the sdp), bitrate (within the bounds of b= from the SDP) and frameRate (within the range of max-fr in the sdp for vp8).After writing this i found http://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters which gives me such a list.
* should the algorithm describe that those values must be checked against their maximums?
* how does it learn (without parsing the SDP) the maximum value that can be set? this would imply read-only maximum* and read-write current*

**Comment by fippo** [comment]
speaking of http://w3c.github.io/webrtc-pc/#dom-rtcrtpparameters ...
* fec, rtx and rid are described as read-only in the table but not in the text like it is done for ssrc.
* maxFrameRate is limited by things like max-fr from the sdp.
* maxBitrate is a target bitrate as described in https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-targetbitrate -- it would be good to have a consistent description in both places (h/t @vr000m)

**Comment by aboba** [comment]
@fippo We just merged a PR related to this.  Can you review it? 
https://rawgit.com/w3c/webrtc-pc/master/webrtc.html

**Comment by vr000m** [comment]
IMO, I the targetBitrate is the current output of the congestion control. as per: "It is the current target bitrate configured for this particular SSRC". I could clarify that it is the most recent output of the congestion control algorithm.

We could expose maxBitrate which would then be the same as the one rtcrtpparameters.

**Comment by aboba** [comment]
Closing this based on lack of response.  If this is still an issue, please reopen.
