### ISSUE TITLE
RTCDtlsTransport: why is there no getCertificates?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1250]
http://w3c.github.io/webrtc-pc/#rtcdtlstransport-interface
doesn't allow querying the dtls certificates the transport was created with.

Is there a reason for that? The certificates should also be available from pc.getConfiguration() but we have ways to get both local and remote parameters on the ice transport

@aboba?

**Comment by aboba** [comment]
At the virtual interim there was consensus not to add a getCertificates() method.
