### ISSUE TITLE
lastOffer on the PC 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1255]
SetLocalDescrption step 2 and 3 refer to lastOffer and lastAnswer. Need to clarify these are the last ones on this PC.

**Comment by aboba** [comment]
Related to  Issues https://github.com/w3c/webrtc-pc/issues/1309 and https://github.com/w3c/webrtc-pc/issues/1330  and PR https://github.com/w3c/webrtc-pc/pull/1333
