### ISSUE TITLE
MTI specification of crypto for certs

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1258]
I think the parts in section 4.10 that specify which cryto must be support for the certs should be normatively defined  in the IETF specs not the w3c spec.

**Comment by stefhak** [comment]
See #1315 as well. Can you propose something @fluffy

**Comment by aboba** [comment]
@martinthomson Is this something you want to incorporate into the RTCWEB Security or Security-Arch documents?

**Comment by aboba** [comment]
@fluffy @stefhak The logical place for this to go would be [draft-ietf-rtcweb-security-arch ](https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-12#page-16)Section 5.5.

**Comment by stefhak** [comment]
Thanks @aboba!

**Comment by alvestrand** [comment]
After some more discussion - the practical requirement for being able to generate both kinds of certificates comes from the interoperability requirements when the default changed. Being able to generate both is good for interoperability with "old stuff", but it doesn't seem to be related to IETF mandates.
