### ISSUE TITLE
Failure of transmission of isolated stream

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1264]
Related to to section 10.4.1. Is there a way to find out that the peer has not done the ALPN marking to indicate it will respect stream confidentiality. If there is not a way now, we likely need a way for the JS to figure out this error

**Comment by stefhak** [comment]
Can this found out from stats? Assigning to @martinthomson

**Comment by aboba** [comment]
@fluffy Is this still an issue now that we have RTCError and improved statistics?

**Comment by stefhak** [comment]
@fluffy ping!

**Comment by fluffy** [comment]
I'm not aware of how RTCerror or the stats solve this. Is there something I am missing? I think that as we move Identity out, we should move the isolated streams with it because that is where it is needed. So this problem would move with it.

**Comment by stefhak** [comment]
I was thinking stats could play a role (at least that is one way for the app to determine whether any data is going out or not).
Anyway, I think we should not close this Issue until we have determined that it will indeed be dealt with in the new Identity spec.

**Comment by dontcallmedom** [comment]
Since isolated streams have moved to webrtc-identity, I've moved [that issue there](https://github.com/w3c/webrtc-identity/issues/27) as well; closing this one as a result
