### ISSUE TITLE
Spec has reference to WEBIDL-1 and WEBIDL

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1266]
Suspect the WEBIDL is just a typo as it does not seem to be used anywhere and the correct reference is WEBILD-1

**Comment by fluffy** [comment]
This is weird. I can't find what in the HTML causes us to have the [WEBIDL] reference.

**Comment by fluffy** [comment]
@dontcallmedom - you have any idea what causes the [WEBIDL] reference? Thanks

**Comment by dontcallmedom** [comment]
it's apparently [added automatically by ReSpec](https://github.com/w3c/respec/issues/1105) (which would kind of make sense if we didn't already have a WebIDL-1 reference).
