### ISSUE TITLE
Missing steps on handling direction argument in addTransceiver

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1268]
In the steps for `addTransceiver`, there are a few missing steps on handling the `direction` argument: 

- Take the `direction` value from `RTCRtpTransceiverInit` dictionary if present.
- Otherwise let `direction` be `sendrecv`.
- Pass it as an argument when calling the steps to create an `RTCRtpTransceiver`.
- Set `direction` attribute of `RTCRtpTransceiver` in steps to create an `RTCRtpTransceiver`.

**Comment by stefhak** [comment]
Related to #1321

**Comment by soareschen** [comment]
Correct. So this is a duplicate of #1206.
