### ISSUE TITLE
Section 4.3.1: operations queue and setDescription

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1277]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

(operations queue)
This algorith seems to imply that operation is run synchronously
if the queue depth is one (step 6) whereas if it's not, it's run
asynchronously. This definitely isn't invisible in the callback
version (reentrancy) and isn't actually invisible in the promises
version because these operations have side effects. Is it really
the expectation that we should (for instance) start sending
media before the promise resolves? That seems odd.

(setDescription)
The says:
    To set an RTCSessionDescription description on an RTCPeerConnection
    object connection, enqueue the following steps:

    1. Let p be a new promise.

I may be confused, but I don't think that the promise creation and
resolution is in fact queued.

    2. If elements of the SDP were modified, then reject p with a newly created InvalidModificationError and abort these steps.

This only applies to local decriptions.

This algorithm is extremely prescriptive about which error checks
you need to perform and in which order. This is externally observable
because I throw different errors. For instance, why is it the
spec's business whether I check for being in the right state before
or after I check for the SDP being modified.

    5. If the content of description is invalid, then reject p with a
    newly created InvalidAccessError and abort these steps.

What would invalid be here? Anything else?

    2. If description is applied successfully, the user agent must
    queue a task that ru ns the following steps:

Didn't we already queue above?

**Comment by soareschen** [comment]
Note: the first part of this is related to #1218.

**Comment by stefhak** [comment]
Re-assigning to @jan-ivar

**Comment by jan-ivar** [comment]
I think all issues reported here have been addressed by now, so we can close this issue.

> (operations queue)
This algorithm seems to imply that operation is run synchronously
if the queue depth is one (step 6) whereas if it's not, it's run
asynchronously.

This was discussed in https://github.com/w3c/webrtc-pc/pull/1397 and closed. Only an operation's chained preamble ever runs synchronously—matching how `async` functions work—so reentrancy shouldn't be an issue.

> `1. Let p be a new promise.`

The latest version of the [chain an operation](https://w3c.github.io/webrtc-pc/#dfn-chain-an-operation) algorithm returns a promise, which the outer steps return appropriately, so this should be fixed.

> `2. If elements of the SDP were modified, then reject p with InvalidModificationError`
> 
> This only applies to local decriptions.

Fixed. In [SLD](http://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription) only now (see **[[LastCreatedOffer]]** and *[[LastCreatedAnswer]]**.

> `5. If the content of description is invalid, then reject p with a
newly created InvalidAccessError and abort these steps.`
> 
> What would invalid be here? Anything else?

This is when SDP is syntactically valid, but violates some SDP offer/answer or JSEP rule. E.g. direction in an answer is incompatible with what was in the offer, or changing a mid in an answer. Firefox [uses it](https://searchfox.org/mozilla-central/rev/b38e3beb658b80e1ed03e0fdf64d225bd4a40327/media/webrtc/signaling/src/jsep/JsepSessionImpl.cpp#697) FWIW.

> `2. If description is applied successfully, the user agent must
queue a task that ru ns the following steps:`

Queue a task gets us back to main thread.
