### ISSUE TITLE
Section 4.2.3 (createOffer)

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1278]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

   4. Return the result of enqueuing the following steps:
      1. Let p be a new promise.

This seems like another situation where a generic algorithm would
help.

(createAnswer)
   setLocalDescription without causing an error as long as
   setLocalDescription is called reasonably soon.

I have no idea what "reasonably soon" means

(setLocalDescription)
This algorithm leaves the state of the PC changed in case of
bogus inputs. However, JSEP requires that the state be unchanged
(see JSEP S 5.8)

(addIceCandidate)

   3. If both sdpMid and sdpMLineIndex are null, return a promise
   rejected with a newly created TypeError.

See above about consistency. Why is the promise rejected here
immediately but otherwise these are enqueued? How does that help?

(setConfiguration)

    3. For each url in server.urls parse url and obtain scheme
    name. If the scheme name is not implemented by the browser, or if
    parsing based on the syntax defined in [ RFC7064] and [RFC7065]
    fails, throw a SyntaxError.

This seems unwise as it makes it very hard to introduce new schemes.
Why aren't they just ignored?

**Comment by stefhak** [comment]
Split up into Issues
https://github.com/w3c/webrtc-pc/issues/1342
https://github.com/w3c/webrtc-pc/issues/1343
https://github.com/w3c/webrtc-pc/issues/1344
https://github.com/w3c/webrtc-pc/issues/1345

**Comment by aboba** [comment]
Split up into sub-issues, so closing.
