### ISSUE TITLE
Section 4.3.3: optional methods

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1279]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    Supporting the methods in this section is optional. However, if
    these methods are supported it is mandatory to implement according
    to what is specified here.

This doesn't match my memory of what we agreed when we added promises. When was this decision made?

**Comment by stefhak** [comment]
@ekr what part do you remember differently? Is it the part about the legacy API being optional, or that it has to be implemented according to "what is specified here"?

**Comment by dontcallmedom** [comment]
see #1086 where the discussion that led to the addition of the text (in #1119) happened

**Comment by stefhak** [comment]
Adding "Needs submitter action" label as we need input from @ekr (who is the submitter)

**Comment by stefhak** [comment]
No input from @ekr, closing this Issue.
