### ISSUE TITLE
Section 4.8.1: missing attributes

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1280]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

Seems like we are missing:

- component-id
- extension-att-name
- extension-att-value

Arguably, we don't need the last two but we do need component-id

Also, you need to cite the relevant parts of 5245 here.

**Comment by stefhak** [comment]
We did add component-id last week.

**Comment by stefhak** [comment]
@taylor-b any comment?

**Comment by taylor-b** [comment]
Yes, the component ID is added. And in another issue (I'm having trouble finding it), we decided to not worry about extended attributes, since that would be a new feature, and the application can parse the SDP string if it really needs them. I wouldn't personally be opposed to adding them, though.

**Comment by aboba** [comment]
I agree that adding extended attributes/values is a new feature, and since the information is otherwise available, not a necessary one.  My suggestion is to resolve this by adding a reference to RFC 5245.
