### ISSUE TITLE
Section 4.8.3: Buried treasure

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1281]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    If no host candidate can reach the server, errorCode will be set
    to the value 701 which is outside the STUN error code
    range. This error is only fired once per server URL while in the
    RTCIceGatheringState of "gathering".

This is kinda buried..

**Comment by stefhak** [comment]
@ekr can you clarify?

**Comment by taylor-b** [comment]
Ping @ekr. Do you have a suggestion for where else we can describe this behavior to make it less buried? Section 5.6 (`RTCIceTransport` interface)?

**Comment by aboba** [comment]
As noted in the comments on PR https://github.com/w3c/webrtc-pc/pull/1458, discussion of the 701 error code fits well in the ErrorCode definition, and moving it might actually increase the likelihood it is overlooked.
