### ISSUE TITLE
Section 5.3: track.label initialization

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1284]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    Initialize track.label to the result of concatenating the string "remote " with kind.

Does this mean I will have a lot of tracks labelled "remote video"? That seems unfortunate.

**Comment by stefhak** [comment]
@ekr do you have a better proposal?

**Comment by adam-be** [comment]
Ping @ekr

The Media Capture spec says the following about the label attribute.

> User Agents MAY label audio and video sources (e.g., "Internal microphone" or "External USB Webcam"). The label attribute MUST return the label of the object's corresponding source, if any. If the corresponding source has or had no label, the attribute MUST instead return the empty string.

It doesn't really matter that there are lots of tracks with the same label since its purpose is to provide a hint about the source. In this case the source is remote.

I propose we close this issue.

**Comment by aboba** [comment]
Closing issue due to lack of response.
