### ISSUE TITLE
Section 6.1: label length

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1286]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    6. If negotiated is false and label is longer than 65535 bytes long,
throw a TypeError.
    7. If negotiated is false and protocol is longer than 65535 bytes long,
throw a TypeError.

Why not just restrict this to 65k in general.

**Comment by stefhak** [comment]
@ekr can you clarify? We don't follow.

**Comment by aboba** [comment]
@stefhak The descriptions of the label and protocol attributes do not say that they need to be 65535 bytes long or less.  So perhaps that should be stated.
