### ISSUE TITLE
Section 6.2: when data cannot be sent

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1287]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    5. Attempt to send data on channel's underlying data transport; if
    the data cannot be sent, e.g. because it would need to be buffered
    but the buffer is full, the user agent must abruptly close
    channel's underlying data transport with an error.

This seems like a very unsafe API. Why not instead have it fail?

**Comment by aboba** [comment]
Related Issue: https://github.com/w3c/webrtc-pc/issues/1148

**Comment by lgrahl** [comment]
I agree that letting it fail makes much more sense.

**Comment by aboba** [comment]
Related PR: https://github.com/w3c/webrtc-pc/pull/1209
