### ISSUE TITLE
Section 9.4: peerIdentity mismatches

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1292]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

It seems like some text about how to handle peerIdentity mismatches
would be helpful here, although I recognize the normative text is
elsewhere. I can supply some if people would like.

**Comment by aboba** [comment]
@ekr A PR would be welcome.

**Comment by stefhak** [comment]
Pinging @ekr

**Comment by stefhak** [comment]
Labeling "Editorial" based on @ekr 's comment in https://github.com/w3c/webrtc-pc/issues/1292#issue-232627333 that the normative text is elsewhere.
