### ISSUE TITLE
Section 10.4.1: target peerIdentity

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1294]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

Do you think we should have have the target peerIdentity, not just isolated.

**Comment by aboba** [comment]
@ekr Are you suggesting: 

partial interface MediaStreamTrack {
    readonly attribute DOMString peerIdentity; 
};

**Comment by ekr** [comment]
@aboba: yes, that's what I was proposing.
