### ISSUE TITLE
Section 11.6: Diagram

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1296]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

has anyone checked this diagram recently?

**Comment by aboba** [comment]
@ekr The diagram was last revised via PR https://github.com/w3c/webrtc-pc/pull/1087

Do you see any issues with it?

**Comment by aboba** [comment]
@fippo Are there any remaining issues in the diagram that need to be fixed?

**Comment by fippo** [comment]
I can *always* find issues (or imagine them)

We intentionally omit the empty callbacks to improve readability, right? If not there are a couple of places where that is missing. I don't think adding them will improve the diagram nor will renaming "callback" to "resolve".

46: pranswer confuses me. I think this is correct but can someone please double-check this is consistent with the spec: the signaling state is have-local-pranswer; in this state we can call createAnswer again, it resolves with an answer we can use in setLocalDescription.

51: (old 50) this changes from iceTransportPolicy: relay without setConfiguration and an ice restart. Probably easiest to change "SRTP without relay" to "SRTP" and make it go through Bob's TURN server.
I hope there is no way that a change in iceTransportPolicy between the two createAnswer can cause non-relay candidates to be gathered.

**Comment by aboba** [comment]
@fippo I think that the "SRTP without relay" is occurring because an ICE check succeeded without relay candidates. So it's not related to a change in iceTransportPolicy.
