### ISSUE TITLE
Section 5.2: transactionId restrictions

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1300]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

An unique identifier for the last set of parameters
applied. Ensures that setParameters can only be called based on a
previous getParameters, and that there are no intervening changes.

Are there any restrictions on how this is generated.

Shouldn't the definition RTCRtpEncodingParameters mark a bunch of stuff readonly?

**Comment by aboba** [comment]
@ekr RTCRtpEncodingParameters is a dictionary, not an interface, so the table in Section 5.2 is the best we can do.

**Comment by aboba** [comment]
@ekr @stefhak Are you referring to uniqueness requirements on the transactionId ?

**Comment by stefhak** [comment]
I looked at https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-last-event-id - nothing is mentioned about restrictions on how that is generated. I propose we close this issue.

**Comment by stefhak** [comment]
Closing. @ekr feel free to re-open if you think my conclusion is wrong.
