### ISSUE TITLE
Missing definition for obtaining list of all RTCIceTransport and RTCDtlsTransport

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1306]
The computation for appropriate states for `RTCIceGatheringState`, `RTCPeerConnectionState`, and `RTCIceConnectionState` require obtaining a list of all `RTCIceTransport` and `RTCDtlsTransport` of a peer connection. However it is not well defined on how to obtain such lists. 

As of now, the only public approach that I am aware of is:

- For `RTCDtlsTransport`, for each transceivers in _CollectTransceivers_, for each sender and receiver in transceiver, add sender's and receiver's `transport` and `rtcpTransport` value to the result set if not null. Also add the `transport` value in `peerconnection.sctp` to result set if not null.
- For `RTCIceTransport`, for each dtls transport in the peer connection, add the `transport` value of the dtls transport to the result set.

This is a very verbose and expensive way of getting list of available `RTCIceTransport` and `RTCDtlsTransport`. While browsers could have internal mechanism to compute such list, it is better to specify that in the spec so that we can be confident that all browsers always compute the same list in a given scenario.

For testing and diagnostic purpose, it would also be helpful to have public methods to retrieve the lists directly, instead of having to iterate through all transceivers to get them.

**Comment by aboba** [comment]
As you say, it is currently possible to retrieve all of the IceTransports and DtlsTransports.  In practice, this won't be expensive, since most applications will use RTP/RTCP mux and BUNDLE.

**Comment by taylor-b** [comment]
This issue may be related: https://github.com/w3c/webrtc-pc/issues/1178

**Comment by soareschen** [comment]
By expensive I mean that the userland JS code would need to do unnecessary works to retrieve the list of IceTransports and DtlsTransports. Due to mux and bundle there might be only one instance of each transport, but the userland code nevertheless have to iterate through all senders/receivers/sctp because there is no guarantee that they are the same transport.

I faced this issue during testing, but I suspect this might happen in practice as well. What happen is I try to obtain an instance of IceTransport and DtlsTransport, doesn't matter where they come from, but there is no simple way to get that. 

- In `RTCRtpSender` and `RTCRtpReceiver`, the `transport` and `rtcpTransport` attributes are nullable.
- In `RTCPeerConnection`, the `sctp` attribute is nullable.
- If we want to wait for any of these attributes to become non-null, the only option seems to be listen for the `connectionstatechange` event, then iterate through the senders/receivers/sctp to collect the DtlsTransport.
- More specifically, the spec doesn't specify when the `transport`, `rtcpTransport`, and `sctp` attributes are set to non-null, and how can application wait for such changes.
- The `icegatheringstatechange` and `iceconnectionstatechange` events are useless for this use case. Because any IceTransport created is inaccessible until there is a DtlsTransport connecting to it and attached to a sender/receiver/sctp.
- Curiously the spec seems to rely on the same approach to collect list of transports. This can be found in step 5 and 6 of the `close` method of `RTCPeerConnection`. (It has missed the DtlsTransport in `sctp`)
- There seems to be a circular dependency on how the spec implement the `connectionstatechange` event. (4.3.1.3) If the peer connection have no idea how many IceTransports and DtlsTransports it has, and that they can be added to any one of the null attributes at any time, then it can only constantly poll for the attribute changes just to fire the event.

Surely there are better way to specify how the transports are obtained?

**Comment by aboba** [comment]
As Taylor noted, there is an existing issue relating to when the Ice and DTLS transports are created, which when fixed will tell us when receiver/sender.transport and receiver.sender.transport.transport will be non-null, which makes enumeration considerably simpler.  

Even if we had native getIceTransports() and getDtlsTransports() methods (or developed them based on the existing APIs), calling these methods before Ice or DTLS transports are created would not provide all the transports.   So you'd need to figure out which RtpSenders/Receivers had transports and which didn't to determine which transports were missing - the same problem you noted without those methods.  Even if they did return all the Ice or DTLS transports, if you needed to know which RtpSenders/RtpReceivers they corresponded to, then you'd still need to enumerate all the senders and receivers.

**Comment by soareschen** [comment]
> As Taylor noted, there is an existing issue relating to when the Ice and DTLS transports are created, which when fixed will tell us when receiver/sender.transport and receiver.sender.transport.transport will be non-null, which makes enumeration considerably simpler.

Got it then. Having something like an `ontransport` event on the sender/receiver could simplify a lot on the transport management.

I agree that having public getIceTransports() and getDtlsTransports() methods might not help much in most other cases. Although would it be helpful to have private sections in the spec to describe the steps to get all Ice and DTLS transports? That could be refactored/modified out from the `close()` method and be shared with other sections such as the connection state change event sections.

**Comment by aboba** [comment]
This issue was discussed at the virtual interim on June 28.  WG consensus was not to add APIs to the specification to enumerate ICE and DTLS transports.

**Comment by taylor-b** [comment]
> Although would it be helpful to have private sections in the spec to describe the steps to get all Ice and DTLS transports?

We could still do this, in a "note" div, also explaining that transports will only be created as a result of applying a description.
