### ISSUE TITLE
when voiceActivityDetection is false, browser must send media even if it is silent

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1308]
from https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html.

@fluffy , could you supply a PR?

**Comment by aboba** [comment]
@fluffy @stefhak   Currently the explanation for dtx says: 

"For an RTCRtpSender, indicates whether discontinuous transmission will be used. Setting it to disabled causes discontinuous transmission to be turned off. Setting it to enabled causes discontinuous transmission to be turned on if it was negotiated (either via a codec-specific parameter or via negotiation of the CN codec). This attribute is ignored by a video sender."

Perhaps we should add this: 

"If it was not negotiated (such as when setting voiceActivityDetection to "false" in RTCOfferOptions), then discontinuous operation will be turned off regardless of the value of dtx,  and media will sent even when silence is detected."
