### ISSUE TITLE
Check for state when "setting an RTCSessionDescription description"

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1309]
from https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html.

"The algorithm for applying local / remote SDP does not deal with errors caused when setting things state where that is not allowed - an error should be generated. This is in step 3 and for of step 2 of stuff that starts with “To set an RTCSessionDescription description"

**Comment by stefhak** [comment]
@taylor-b WDYT?

**Comment by taylor-b** [comment]
Just to clarify: it sounds like the issue is that we say:

> If the description's type is invalid for the current signaling state of connection, then reject p with a newly created InvalidStateError and abort these steps.

But we don't define what makes a type "invalid". I think pointing to sections 5.5 and 5.6 of JSEP would resolve this.

**Comment by aboba** [comment]
@taylor-b Agree that a reference to JSEP is all that is needed here.  Added this to PR https://github.com/w3c/webrtc-pc/pull/1333
