### ISSUE TITLE
addIceCandidate should not be callable when PeerConnection is closed

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#131]
> Originally reported on W3C Bugzilla [ISSUE-26027](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26027) Tue, 10 Jun 2014 10:13:33 GMT
> Reported by Harald Alvestrand
> Assigned to 

addStream() has as part of its procedure:

If connection's RTCPeerConnection signalingState is closed, throw an InvalidStateError exception and abort these steps.

This check should also be done in addIceCandidate (and any other procedure that would otherwise enqueue a callback, except GetStats).

**Comment by stefhak** [comment]
I think this is now done.
