### ISSUE TITLE
Make 4.3.1. referenceable

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1310]
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html

The algorithm in 4.3.1 is 6 pages long. We need a way to references the steps in it. One way to do this would make all the numbers increment for the whole section and sub lists be like 3.4.5 so I could refer to step 3.4.5. I don’t care how we do it but really hard for implementers to even put in comments that link the code with appropriate part of spec when writing this way.

**Comment by burnburn** [comment]
@fluffy this issue is about a year old.  I just took a look at it, and it's not clear to me right now which section used to be 4.3.1.  Can you take a look and see what still needs to be done on this one?

**Comment by fluffy** [comment]
I don't mind tracking this down - I'm going to checkout out a version from around the time I entered this  -  but whats advice do we want to give people about how to provide comments such that this is not an issue.

**Comment by fluffy** [comment]
This became section 4.4.1 and someone already broke it into subsections so I think we can mark this as fixed and close it.
