### ISSUE TITLE
Extend privacy note to clarify regarding defaultIceServers

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1313]
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html

"The note about defaultIceServers privacy needs to be updated to say that if the user thinks a proxy has been configured but it is not used, that causes significant privacy problems because there IP address gets revealed when they expected the proxy to hide it. A browser sometime using a discovered proxy for and sometimes not or chasing this behavior between version will cause loss privacy in some cases."

**Comment by dontcallmedom** [comment]
I'm not entirely sure who the suggested note would be drawing attention from. Maybe we could note somewhere that `defaultIceServers` is not a privacy-perserving mechanism since its use is optional by applications.

**Comment by stefhak** [comment]
@dontcallmedom that sounds like a reasonable proposal to me. Could you draft?
