### ISSUE TITLE
Do we need to control what is in SNI and Certname of DTLS connections

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1316]
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html

"Do we need to control what is in SNI and Certname of DTLS connections"

**Comment by stefhak** [comment]
@martinthomson could you have a look?

**Comment by ekr** [comment]
SNI isn't relevant for this spec (it's a protocol issue). Perhaps you mean SAN? In any case, we shouldn't take a position on what's in the names of the certs.

**Comment by martinthomson** [comment]
As a protocol issue, that's something for something in the RFC series, I suspect.  SNI shouldn't be used.  SAN calls back to #1318: nothing in the cert is useful except the public key.

**Comment by stefhak** [comment]
Thanks @ekr and @martinthomson, closing.
