### ISSUE TITLE
More granular data channel error reporting

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1317]
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html

"In data channel, a type error is not what I really expect if a string is the right type but too long. Having multiple different types of mistakes all  generate the same error sounds really bad. Could we actually get the API to report what went wrong"

**Comment by alvestrand** [comment]
Keeping "TypeError". It seems consistent with other pieces of Web platform stuff.
