### ISSUE TITLE
guideline of when to time out an IdP

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1319]
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html

"I think the draft need to provide a SHOULD level guideline of when to time out an IdP. This gives browsers advice on what to implement and provides IdP a target of what they need to meet. Without standardization of this, it’s a crap shoot for both the IdP and Browsers."

**Comment by martinthomson** [comment]
When do browsers expire a page load?  Or a subresource load?  Until those are also defined, we have no frame of reference for this.

**Comment by stefhak** [comment]
Closing per @martinthomson's comment.
