### ISSUE TITLE
capitalization of 2119 works 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1328]
reporting bug sent to me by someone else ....

The respec seems to have moved the 2119 words to lower case but they are required to be in upper case to be the words in 2119.

**Comment by aboba** [comment]
@fluffy Ugh.  This is apparently a "feature" of respec 12.2.2, but not 8.7.1.

**Comment by aboba** [comment]
@dontcallmedom  @adam-be Can we get this bug addressed?  Should we revert to an earlier version of respec?
