### ISSUE TITLE
Streams that become isolated generate errors on PC

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#133]
> Originally reported on W3C Bugzilla [ISSUE-25859](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25859) Wed, 21 May 2014 19:34:53 GMT
> Reported by Martin Thomson
> Assigned to 

When a stream becomes isolated (see 25856) we should surface an error and stop sending media for that track (we might have to continue transmission - ask the IETF group - but no content can be sent).

The only exception to this is if the stream is isolated and peerIdentity tagged.  Those can potentially be transmitted.

Proposal is:

partial interface RTCPeerConnection : EventTarget {
  attribute EventHandler? onerror;
};

[Constructor(TrackIsolatedEventInit args)]
interface TrackIsolatedEvent : Event {
  attribute MediaStreamTrack track;
};

Alternatively:

partial interface RTCRtpSender : EventTarget {
  attribute EventHandler? onerror;
};

Which might be a little better because the error can be generic.

**Comment by fluffy** [comment]
I don't think this is an enhancement this seems like a pretty key part of how the media privacy works

**Comment by alvestrand** [comment]
@martinthomson is this still valid?

**Comment by martinthomson** [comment]
I think that we discussed having a property and event on tracks that could be used to identify when they are isolated or not.

**Comment by dontcallmedom** [comment]
The current spec has an `isolated` attribute and an `isolationchange` event, so I think this is already solved.
