### ISSUE TITLE
Session description attribute not specified for some steps in check if negotiation is needed

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1331]
In Section 4.7.3, the following steps do not specify how the SDP comparison is done:

- If connection has created any RTCDataChannels, and no m= section has been negotiated yet for data, return "true".
- If t isn't stopped and isn't yet associated with an m= section according to [JSEP] (section 3.4.1.), return "true".
- If t isn't stopped and is associated with an m= section according to [JSEP] (section 3.4.1.), then perform the following checks:

The remaining steps are clear that the comparison is done against `currentLocalDescription` or `currentRemoteDescription`.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?
