### ISSUE TITLE
New feature: Track swapping

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#134]
> Originally reported on W3C Bugzilla [ISSUE-27227](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27227) Mon, 03 Nov 2014 23:17:47 GMT
> Reported by Harald Alvestrand
> Assigned to 

Presented in

https://www.w3.org/2011/04/webrtc/wiki/images/6/6c/WebRTC_RTCSender-Receiver%2C_TPAC_2014.pdf

slide 16. This would make RTPsender.track be a mutable attribute, leading to the ability to switch which video is sent with no signalling.

Compatible tracks are required, and it means that one loses the ability to correlate sendertrack.id with receivertrack.id - this needs to be explicit in the proposal. More work needed, but there was interest in pursuing this.

**Comment by dontcallmedom** [comment]
I think this is now tracked as #189; if so, please close this one

**Comment by stefhak** [comment]
Yes, tracked as #189 - closing this one.
