### ISSUE TITLE
Consider using generic algorithm

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1342]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

    Return the result of enqueuing the following steps:
        Let p be a new promise.

This seems like another situation where a generic algorithm would
help.

See https://github.com/w3c/webrtc-pc/issues/1278 for context.

**Comment by adam-be** [comment]
Clicking the `enqueuing` link takes you to the algorithm that describes how the following steps should be queued.

**Comment by stefhak** [comment]
I think we can close this Issue. Unless someone objects I'll close it one of the coming days.

**Comment by stefhak** [comment]
Closing.
