### ISSUE TITLE
Define "reasonably soon"

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1343]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

```(createAnswer)
setLocalDescription without causing an error as long as
setLocalDescription is called reasonably soon.
```

I have no idea what "reasonably soon" means

See https://github.com/w3c/webrtc-pc/issues/1278 for context.

**Comment by adam-be** [comment]
The next sentence specifies the following:

> The session descriptions MUST remain usable by
<code>setLocalDescription</code> without causing an error until
at least the end of the fulfillment callback of the returned
promise.

So I think the sentence with "reasonably soon" is redundant and can be removed (for both createOffer/Answer functions).
