### ISSUE TITLE
Don't update state if setLocalD is called with bogus input

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1344]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

(setLocalDescription)
This algorithm leaves the state of the PC changed in case of
bogus inputs. However, JSEP requires that the state be unchanged
(see JSEP S 5.8)

See https://github.com/w3c/webrtc-pc/issues/1278 for context.

**Comment by adam-be** [comment]
@ekr, can you be more specific about where some state is updated even though the input is bogus?

**Comment by stefhak** [comment]
FWIW I read the relevant parts of the spec, and I think the state does _not_ change if the input is bogus.

**Comment by aboba** [comment]
@stefak I don't believe that the intent is to change the state.  However, the text makes it sounds like `lastOffer` and `lastAnswer` are variables which are set as a result of calling setLocalDescription regardless of whether the input is bogus or not.  This is not the case - both `lastOffer` and `lastAnswer` represent internal slots set by `createOffer` and `createAnswer`, respectively.  

Related: Issues https://github.com/w3c/webrtc-pc/issues/1309 and https://github.com/w3c/webrtc-pc/issues/1330 .
