### ISSUE TITLE
Make promise rejection/enqueing consistent

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1345]
From EKR: https://lists.w3.org/Archives/Public/public-webrtc/2017May/0166.html

(addIceCandidate)

  ```  If both sdpMid and sdpMLineIndex are null, return a promise
    rejected with a newly created TypeError.
```

See above about consistency. Why is the promise rejected here
immediately but otherwise these are enqueued? How does that help?

See https://github.com/w3c/webrtc-pc/issues/1278 for context.

**Comment by adam-be** [comment]
If an error can be determined directly, we return a rejected promise right away. That's how it's done in the promise writing guide [1]. Otherwise we return a "pending" promise that can be rejected or fulfilled later.

[1] https://www.w3.org/2001/tag/doc/promises-guide#example-validated-delay

**Comment by stefhak** [comment]
Labeling this as "Needs submitter action" since I would like @ekr (who is the real submitter) to verify he is OK with Adam's response.

**Comment by soareschen** [comment]
I think it is inconsistent because if you call `close()` right after `addIceCandidate({ sdpMid: null, sdpMLineIndex: null })`, the promise rejects. While in other cases, e.g. `remoteDescription` is `null`, the promise is never resolved.

**Comment by soareschen** [comment]
Note that I wrote a test specifically for this: https://github.com/w3c/web-platform-tests/blob/eb99716a47e1db691e287eba963589274ee6bbfb/webrtc/RTCPeerConnection-addIceCandidate.html#L415

The test case currently timeout on both Chrome and Firefox. In other words current browsers already interpret step 3 inside of enqueing operation.

I am going to comment out the test case and defer it until this issue is resolved.

**Comment by stefhak** [comment]
@adam-be can you comment on https://github.com/w3c/webrtc-pc/issues/1345#issuecomment-308948831 and https://github.com/w3c/webrtc-pc/issues/1345#issuecomment-309706862 ?

**Comment by stefhak** [comment]
Assigning @adam-be - if he thinks neither https://github.com/w3c/webrtc-pc/issues/1345#issuecomment-308948831 nor https://github.com/w3c/webrtc-pc/issues/1345#issuecomment-309706862 leads to more work needed we should close this issue.

**Comment by stefhak** [comment]
@soareschen can you verify that this is still an Issue?

**Comment by stefhak** [comment]
Closing due to lack of feedback. @soareschen (or anyone else): please feel free to re-open if you think it should be re-opened.
