### ISSUE TITLE
Enqueue an operation vs queue a task

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1347]
Section 3 imports the concept of queue a task from HTML5.

Section 4.3.1.2 defines _"Enqueue an operation"_ which has an operation queue of running one task at a time.

I tried searching through the spec and there are two phrases being used:

1. queue a task that runs the following steps
2. enqueue the following steps

I'd guess that (1) refers to the HTML5 task and (2) refers to the operation queue. If so, the only section that make use of enqueue operation is 4.3.1.6 _"Set the RTCSessionSessionDescription"_.

If that is correct, I think the sections should be better organized to document the use. In particular, place the _"Enqueue an operation"_ side by side with _"Set the RTCSessionSessionDescription"_, and add a note to clarify that the remaining sections refer to the HTML5 task.

Because _"Enqueue an operation"_ is introduced so early and prominently in the spec, I have been wrongly assuming that all tasks are enqueued as operation instead of HTML5 task. :(

**Comment by adam-be** [comment]
The operations queue is used by createOffer, createAnswer and addIceCandidate as well. In those steps it's referred to as `Return the result of enqueuing the following steps`. These references are also linked.

**Comment by soareschen** [comment]
I see. I was searching the word "enqueue" and missed those steps because they use the word "enqueuing".

I feel that the terminology for _"enqueue the following steps"_ need to be more distinguishable from _"queue a task"_. The words "enqueue" vs "queue" look too similar and does not signify that they have fundamentally different semantics.

Perhaps _"enqueue the following steps to connection's operation queue"_ is better fit for the descriptions? It is more easily searchable and also signifies _which_ operation queue that is being enqueued to.

**Comment by adam-be** [comment]
I think what you're suggesting would be an improvement.

**Comment by stefhak** [comment]
I'm labeling this issue as editorial based on the discussion above. @soareschen would you be willing to provide a PR for this?

**Comment by soareschen** [comment]
Yes I can work on this next week. Currently prioritizing on WPT tasks for WebRTC first.
