### ISSUE TITLE
Rationale for use of USVString in RTCPeerConnection.prototype.createDataChannel

### ISSUE THREAD

**Issue by rwaldron** [w3c/webrtc-pc#1354]
Regarding:

> RTCDataChannel createDataChannel(USVString label,
>                                     optional RTCDataChannelInit dataChannelDict);

I'm wondering if anyone can offer any insight about this? Thanks in advance!

**Comment by soareschen** [comment]
I think it is related to #543.

**Comment by rwaldron** [comment]
Yep, that's what I was looking for. Thanks!
