### ISSUE TITLE
Editorial: consistent Internal slot names e.g. [[IsClosed]] vs [[isClosed]]?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1360]
I can't find a TAG link for this, just cargo-culting from the html and webidl specs. Seems less likely to name clash with API names as well.

I'm filing this issue rather than asking for internal consistency in https://github.com/w3c/webrtc-pc/pull/1321 review.

**Comment by jan-ivar** [comment]
[Apparently](https://github.com/w3c/webrtc-pc/issues/1112#issuecomment-308846383) slot names are fairly ad hoc atm. but we should at least make them consistent within the same spec.

**Comment by aboba** [comment]
Note:  [Dom suggests Capitalized Case. ](https://github.com/w3c/webrtc-pc/pull/1395)
