### ISSUE TITLE
Relating RTCDtlsTransportState to RTCIceTransportState and RTCIceGathererState

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1362]
Each `RTCDtlsTransport` have an underlying `RTCIceTransport`. Intuitively the transport state for the DTLS connection is dependent on the state of the underlying ICE connection. e.g.:

- When `RTCDtlsTransportState` is `connected`, underlying `RTCIceTransportState` should be `completed` (or `connected`?) and underlying `RTCIceGathererState` should be `complete` (or `gathering`?)
- When `RTCIceTransportState` is `closed`, the associated `RTCDtlsTransportState` must be either `closed` or `failed`.
- Nonsense state relation should be disallowed, e.g. having `RTCDtlsTransportState` to be `connected`, but underlying `RTCIceTransportState` is `failed`.

Is there any way the spec allow us to make these kind of assumptions? Or should the spec impose requirements about the state relation between DTLS and ICE?

**Comment by aboba** [comment]
@soareschen  Your "intuition" is wrong.   DTLS packets are transported over a "virtual circuit" created by ICE.   The ICE virtual circuit can change selected pairs, can lose and then recover connectivity, etc. without necessarily affecting the state of the DTLS connection.  

So all three of your assertions are incorrect.

**Comment by soareschen** [comment]
I see. Good to know that.

I suppose then we can have a non-normative note stating that user should make no assumption of the underlying `RTCIceTransport` states when accessing it from `RTCDtlsTransport`.

**Comment by aboba** [comment]
The relationship between DTLS and the underlying ICE transport (including the "virtual transport" behavior) is described in IETF protocol specifications, so this is outside the scope of the WebRTC specification.

**Comment by soareschen** [comment]
Right. So this issue can be closed then. Thanks for clarifying!
