### ISSUE TITLE
no getStats() for dtls and ice transports?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1365]
We have getStats methods both for the [RTPSender](http://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-getstats()) and the [RTPReceiver](http://w3c.github.io/webrtc-pc/#dom-rtcrtpreceiver-getstats()).
But apparently we don't have them for the [ice](http://w3c.github.io/webrtc-pc/#rtcicetransport) and [dtls](http://w3c.github.io/webrtc-pc/#rtcdtlstransport-interface) transports.

For API completeness I think we should have them.

editorial drive-by nit: http://w3c.github.io/webrtc-pc/#rtcicetransport should be http://w3c.github.io/webrtc-pc/#rtcicetransport-interface for consistency of anchor names

**Comment by aboba** [comment]
This was discussed at the virtual interim on June 28.  Resolution was not to enhance the specification to support this.
