### ISSUE TITLE
editorial: inconsistent use of dfn in section names

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1366]
In the image below some terminology shown in orange. In a very inconsistent and confusing way :-/
![inconsistent](https://user-images.githubusercontent.com/289731/26964640-d8866ab8-4cf2-11e7-85e4-e5e39acf765c.png)

The DTMFSender uses this:
```
      <h3 id="h-rtcdtmfsender" resource="#h-rtcdtmfsender"><span property="xhv:role" resource="xhv:heading"><span class="secno">7.2 </span><dfn data-dfn-for="" data-dfn-type="dfn" id="dom-rtcdtmfsender" data-idl="" data-title="RTCDTMFSender"><code>RTCDTMFSender</code></dfn></span>
      </h3>
```
while the DTMFToneChangeEvent does not uses 
```
      <h3 id="h-rtcdtmftonechangeevent" resource="#h-rtcdtmftonechangeevent"><span property="xhv:role" resource="xhv:heading"><span class="secno">7.3 </span>RTCDTMFToneChangeEvent</span>
     </h3>
```

The amount of work required to fix this might be tremendous :-/

**Comment by aboba** [comment]
@fippo I have fixed a few instances of the problem (dictionaries and enums).
