### ISSUE TITLE
Public accessor for isClosed

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1367]
Given that many peer connection methods throw or reject when `[[isClosed]]` is true, it is expected that well designed user applications would want to check the close state as well before calling the methods.

Currently there are indirect ways to check the close state of peer connection, by comparing `signalingState`, `iceGatheringState`, etc with the string `"closed"`. But that means there is no one canonical way to check it, and users would have to resort to conventions to check for the closed state.

Would it make sense to have a read only attribute `isClosed` on `RTCPeerConnection` to expose the value of `[[isClosed]]`?

**Comment by taylor-b** [comment]
Why doesn't a `signalingState` of `"closed"` work?

**Comment by aboba** [comment]
@taylor-b Yes, `signalingState` handles this. We could perhaps clarify that calling  `close()` sets  `signalingState` to `"closed"` (the steps currently don't mention this).

**Comment by soareschen** [comment]
> Why doesn't a signalingState of "closed" work?

It is more of an enhancement request. Since users may check on other states like `iceGatheringState` and make the application code look confusing. 

Alternatively a guideline note can be added to say something like _"To check if a connection is closed, check if `signalingState` is equal `"closed"`"_
