### ISSUE TITLE
Editorial: Use consistent syntax for enum values and strings

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#1370]
Now we just have to decide on an approach. :)

**Comment by jan-ivar** [comment]
FWIW WebIDL [enumeration values](https://heycam.github.io/webidl/#idl-enums) are strings. Both in all observable JS ways, and in WebIDL definitions. e.g. http://w3c.github.io/webrtc-pc/#rtcpeerconnectionstate-enum

**Comment by jan-ivar** [comment]
In binding code it varies I think. In c++ implementation's they're c++ enum. In JS-implemented code they're strings.

**Comment by burnburn** [comment]
With #1485 I think this is done.
