### ISSUE TITLE
Section 8.2: Null selector properly handled by getStats?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1374]
From fippo:

we might have an issue in the text @vr000m cites:
http://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions-2
That step (4) does not seem to cover the case that selector is null.

**Comment by fippo** [comment]
Mostly a style question how to resolve this. One way:
4. If selectorArg is null, let selector be null.
5. If selectorArg is a valid MediaStreamTrack let selector be a RTCRtpSender or RTCRtpReceiver on connection which track member matches selectorArg. If no such sender or receiver exists, or if more than one sender or receiver fit this criteria, return a promise rejected with a newly created InvalidAccessError.

Also I am not sure if the [definition of valid](http://w3c.github.io/webrtc-pc/#introduction-1) allows the InvalidAccessError to be thrown. Possibly "valid" in step 3 should be removed?

**Comment by aboba** [comment]
@fippo Can you submit a PR?
