### ISSUE TITLE
Checks for negotiation-needed are underspecified when currentLocalDescription/currentRemoteDescription are not set

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#1375]
The following language does not work if the PC has not performed an initial negotiation. (Transceivers are expected to be associated before offer/answer completes, so this language can apply in this situation)

"

- If t's direction is "sendrecv" or "sendonly", and the associated m= section in connection's currentLocalDescription doesn't contain an "a=msid" line, return "true".

- If connection's currentLocalDescription if of type "offer", and the direction of the associated m= section in neither the offer nor answer matches t's direction, return "true".

- If connection's currentLocalDescription if of type "answer", and the direction of the associated m= section in the answer does not match t's direction intersected with the offered direction (as described in [JSEP] (section 5.3.1.)), return "true".

"

**Comment by jan-ivar** [comment]
@adam-be Any progress here? Seems valid.

**Comment by stefhak** [comment]
I think this issue is invalid. Before these three bullets it's said:
"If transceiver isn't stopped and isn't yet associated with an m= section in description, return true.", and the text in https://github.com/w3c/webrtc-pc/issues/1375#issue-235282017 would only come into play if the transceiver is associated with a m= section.

**Comment by stefhak** [comment]
@docfaraday do you think we can close this issue?

**Comment by stefhak** [comment]
Closing due to lack of submitter input. Feel free to reopen if you think this is wrong.
