### ISSUE TITLE
pc.close() method should close sctp transport

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1381]
Picking out from #1306.

In the `close()` method, it iterates through the `DtlsTransport` for each sender/receiver for each transceiver and close them. However the `SctpTransport` at `sctp` attribute is missed so its underlying `DtlsTransport` is not closed.

**Comment by aboba** [comment]
Related Issue: https://github.com/w3c/webrtc-pc/issues/1288
