### ISSUE TITLE
iceGatheringState on connection with data channel only before setRemoteDescription(answer) is set

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1382]
According to JSEP, ICE gathering is started as soon as `setLocalDescription()` is called. This is also the observed behavior with current browser implementations. As a result, it is expected that at this point the `iceGatheringState` starts to change.

However when applying to the `RTCIceGatheringState` rules to offerer with data channel only, the `iceGatheringState` stays at `new` until `setRemoteDescription(answer)` is called. This is because the SCTP transport is only initialized when setting answer description. Before this there is no instance of `RTCIceTransport` accessible from anywhere in the spec.

The bug doesn't apply to `RTCRtpTransceiver`, because the `transport` attribute is nullable and can be set at any time outside the scope of the spec.

**Comment by aboba** [comment]
Section 4.4.2 states that `iceGatheringState` transitions to `gathering` if "Any of the `RTCIceTransport`s are in the gathering state."  So the transition will occur when an `RTCIceTransport` object is created and is in the gathering state.  This is not affected by the presence or absence of an SCTP transport, since the SCTP transport runs over the ICE transport.

**Comment by soareschen** [comment]
Got it then. So the conclusion is that browser implementations are allowed to keep an internal list of `RTCIceTransport`s, possibly through the implementation specific ICE agent, and compute states based on that list.

So we just have to fix #1306 to clarify that `RTCIceGatheringState` value is derived from given internal list.

I encountered this issue when testing for the correctness of `RTCIceGatheringState` values in w3c/web-platform-tests#6224. Will mark the relevant sections as non-testable then.

**Comment by aboba** [comment]
Closing since #1306 is now resolved.
