### ISSUE TITLE
WebRTC spec should explicitly specify all causes of a PeerConnection-sourced track being muted

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#139]
> Originally reported on W3C Bugzilla [ISSUE-25513](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25513) Wed, 30 Apr 2014 07:12:28 GMT
> Reported by Kiran
> Assigned to 

As discussed in Bug 25361 [1], WebRTC spec should explicitly specify all the muted events of a MediaStramTrack related to RTCPeerConnection

1. Tracks sourced from m-mline and marked as RecvOnly in SDP should be considered muted tracks.
2. Muted state resulted due to doohickey actions.

// May be some more other events related to PeerConnection.

[1] https://www.w3.org/Bugs/Public/show_bug.cgi?id=25361

**Comment by stefhak** [comment]
Closing since #220 has been merged.
