### ISSUE TITLE
removeTrack: does not always cause createOffer to mark media description

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1390]
In the last few steps for `removeTrack`, `transceiver.direction` is altered based on the value of its `currentDirection`, not `direction`. However `currentDirection` is nullable and only changes after session descriptions.

This means if `removeTrack` is called when `currentDirection` is null, such as before setting session descriptions, the transceiver's direction is not changed. Is this intentional?

**Comment by aboba** [comment]
The text for removeTrack says: 

"Stops sending media from sender. The `RTCRtpSender` will still appear in `getSenders`. Doing so will cause future calls to `createOffer` to mark the media description for the corresponding transceiver as `recvonly` or `inactive`, as defined in [JSEP] (section 5.2.2.)."

**Comment by taylor-b** [comment]
This is an issue in JSEP as well. Filed: https://github.com/rtcweb-wg/jsep/issues/757
