### ISSUE TITLE
Setting session description section should have step to set transceiver currentDirection 

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1391]
In JSEP it is specified that `currentDirection` is set when an answer description is applied.

> The currentDirection property indicates the last negotiated direction for the transceiver's associated m= section.  More specifically, it indicates the [RFC3264] directional attribute of the associated m= section in the last applied answer, with "send" and "recv" directions reversed if it was a remote answer.

The setting session description section should have steps to set the currentDirection, instead of leaving readers to figure it out through JSEP.

**Comment by aboba** [comment]
As noted in Section 4.3: 

"The [JSEP] specification, as a whole, describes the details of how the RTCPeerConnection operates. References to specific subsections of [JSEP] are provided as appropriate."

**Comment by aboba** [comment]
Section 4.4.1.6 says: 

"7. If description is set as a local description, then run the following steps for each media description in description that is not yet associated with an RTCRtpTransceiver object...  If description is of type "answer", then set transceiver's [[CurrentDirection]] slot to an RTCRtpTransceiverDirection value representing the direction of the corresponding media description."

**Comment by soareschen** [comment]
So this has now been fixed on master branch after merging #1321. Closing this.
