### ISSUE TITLE
Setting a pranswer should change RTCRtpTransceiver's currentDirection

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1394]
From PR #1321, we have an explicit step for changing the `currentDirection` attribute:

> If *description* is of type "answer", set *transceiver*'s [[CurrentDirection]] slot *direction*.

But this should apply to "pranswers" as well. JSEP says `currentDirection` returns the direction in the last applied answer, and a "pranswer" is a type of answer. Plus, logically `currentDirection` is meant to represent the direction "in effect" - the one that the media plane cares about. And setting a "pranswer" does affect the media send/recv status, so it would be logically consistent to have it affect `currentDirection`.

**Comment by aboba** [comment]
@taylor-b This makes sense.
