### ISSUE TITLE
In data channel send(), remove the condition "If channel's underlying data transport is not established yet, then abort these steps"

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1396]
Missed this when reviewing #1209. The data can still be queued while channel's underlying data transport is being established. Ignoring it would cause initial data being sent to be silently dropped.

It is also possible that the condition is unreachable, since the new step 2 already guard against non-open `readyState`.

**Comment by taylor-b** [comment]
I agree this can be removed; even before #1209, an `InvalidStateError` would be thrown due to `readyState` being `"connecting"`.

**Comment by nils-ohlmeier** [comment]
Just to make sure we are all on the same page: step 2 stays and we eliminate only step 4 as it is redundant, right?

**Comment by aboba** [comment]
@nils-ohlmeier Right. I believe that Step 2 removes the need for Step 4.  Note that PR https://github.com/w3c/webrtc-pc/pull/1404 removes all of step 4 whereas PR https://github.com/w3c/webrtc-pc/pull/1398 still checks whether the closing procedure has been started.

**Comment by nils-ohlmeier** [comment]
@aboba Good point. I think PR #1404 is the right to do here.

When reading this I initially got nervous that it would allow calling send() even on data channels which are not open yet (forcing the implementations to buffer until the channel opens). But that would lead to trouble as we only learn the max-message-size when the SDP answer is received.
