### ISSUE TITLE
`addTransceiver(track)` doesn't mention checking the origin of track

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1407]
From Issue https://github.com/w3c/webrtc-pc/issues/1386: 

- `addTrack` mentions about checking the origin of track, `addTransceiver(track)` doesn't.

**Comment by adam-be** [comment]
I assume that you're referring to the text about a track being inaccessible to the application (e.g. by peerIdentity). We might want to make that piece general and reference it from both addTrack and addTransceiver.

**Comment by adam-be** [comment]
Btw, should that text emit any errors to the application?
