### ISSUE TITLE
ResourceInUse exception is not defined

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1412]
There are two occurrences of `ResourceInUse` exception mentioned in the spec. However I cannot find any definition of `ResourceInUse`, both in the spec and in WebIDL.

**Comment by aboba** [comment]
@dontcallmedom Any ideas?

**Comment by dontcallmedom** [comment]
yes, `ResourceInUse` does not exist; I would suggest `OperationError` instead
