### ISSUE TITLE
Should even/odd id validation be enforced in createDataChannel when negotiated is false (in-band negotiation)?

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1413]
The draft-ietf-rtcweb-data-protocol spec states that:

> To avoid collisions where both sides try to open a Data Channel with the same Stream Identifiers, each side MUST use Streams with either even or odd Stream Identifiers when sending a DATA_CHANNEL_OPEN message. When using SCTP over DTLS [I-D.ietf-tsvwg-sctp-dtls-encaps], the method used to determine which side uses odd or even is based on the underlying DTLS connection role: the side acting as the DTLS client MUST use Streams with even Stream Identifiers, the side acting as the DTLS server MUST use Streams with odd Stream Identifiers.

Currently `createDataChannel()` allows arbitrary `id` value to be provided, as long as they are within valid range. But creating a data channel with odd/even `id` of the opposite side when `negotiated` is ~`true`~ (Update: `false` - in-band negotiation) violates the MUST clause in the protocol.

It is not clear how we can enforce this even/odd ID validation with the current API design, since data channels can be created before the DTLS connection is established.

**Comment by taylor-b** [comment]
My assumption was that this "MUST" only applies to generated IDs, not IDs selected by the application. If the application is selecting IDs itself, it seems like it would be the application's responsibility to avoid collisions.

**Comment by soareschen** [comment]
> My assumption was that this "MUST" only applies to generated IDs, not IDs selected by the application. If the application is selecting IDs itself, it seems like it would be the application's responsibility to avoid collisions.

It seems that your assumption only applies when `negotiated` is false. Section 6.5 of draft-ietf-rtcweb-data-channel-13 states that:

> When one side wants to open a channel using out-of-band negotiation, it picks a stream.  Unless otherwise defined or negotiated, the streams are picked based on the DTLS role (the client picks even stream identifiers, the server odd stream identifiers).  However, the application is responsible for avoiding collisions with existing streams.

My understanding is the the requirement in draft-ietf-rtcweb-data-protocol is enforced on the `DATA_CHANNEL_OPEN` message sent, regardless of how the message was generated. So unless the API call doesn't result in sending `DATA_CHANNEL_OPEN` message, i.e. when `negotiated` is false, the user agent must ensure the protocol is followed.

Section 6 of draft-ietf-rtcweb-data-protocol also states that:

> If the DATA_CHANNEL_OPEN message doesn't satisfy the conditions above, for instance ..., the odd/even rule is violated ..., the receiver MUST close the corresponding Data Channel using the procedure described in [I-D.ietf-rtcweb-data-channel] and MUST NOT send a DATA_CHANNEL_ACK message in response to the received message.

So perhaps the behavior of the current spec is that if an odd/even-violated ID is provided, the data channel should never be established and error event is eventually fired. This could be pretty confusing to unfamiliar users.

But I don't really follow the motivation behind allowing custom ID to be set for all cases. It makes sense to provide ID when `negotiated` is false, but when `negotiated` is true, it doesn't really make sense for applications to be exposed to this kind of low level details.

**Comment by taylor-b** [comment]
> But I don't really follow the motivation behind allowing custom ID to be set for all cases. It makes sense to provide ID when negotiated is false, but when negotiated is true, it doesn't really make sense for applications to be exposed to this kind of low level details.

I agree. So, I see three options:

1. Say "you can only specify the ID when `negotiated` is `true`". Would break existing apps (though I don't know why they'd need this functionality in the first place).
2. Once the DTLS role is determined, close the data channel with an error if the ID is invalid. Is also bound to break existing apps, though it would be following draft-ietf-rtcweb-data-protocol to the letter.
3. Change the draft-ietf-rtcweb-data-protocol requirement to only apply to IDs generated by the user agent.

**Comment by jesup** [comment]
> Say "you can only specify the ID when negotiated is true". Would break existing apps (though I don't know why they'd need this functionality in the first place).
Specifying the ID with negotiated = false should be ignored.  If you want, we could complain or reject it.  I suspect the only people doing it are doing it by accident (specify everything!) and aren't depending on it (since it does nothing currently).

> Once the DTLS role is determined, close the data channel with an error if the ID is invalid. Is also bound to break existing apps, though it would be following draft-ietf-rtcweb-data-protocol to the letter.
I wonder how many people are using negotiated=true (and actually have a reason to do so)

> Change the draft-ietf-rtcweb-data-protocol requirement to only apply to IDs generated by the user agent.
There was a lot of discussion about this in the IETF meetings... (maybe in webrtc ones).  Someone should pull the minutes and check.  Honestly it was long enough ago and argued over enough (lots of opinions) that I honestly can't remember how we ended up here and what the expected way of dealing with opening-before-connection was.

**Comment by jesup** [comment]
Ugh.  Silly github

**Comment by soareschen** [comment]
Sorry, I got the notion of `negotiated` wrong the entire time. (Was wrongly deliberately remembering that `negotiated` have a default value of `true` in `RTCDataChannelInit`, when it is actually false and `ordered` is the one having that WebIDL-violating default value of `true`.)

To clarify, I have updated the title and my previous comments. I'd also suggest using the terms in-band / out-of-band negotiation as described in rtcweb-datachannel to avoid further confusion.

**Comment by lgrahl** [comment]
My personal understanding was that the `id` parameter is invalid for in-band negotiated data channels. So, I'd vote for @taylor-b option 1 with a proposal:

If the `id` is coupled with `negotiated`, then why not just remove the `negotiated` field and just leave in `id` which also triggers out-of-band negotiation? Backwards compatibility would be ensured by just ignoring the `negotiated` field.

**Comment by taylor-b** [comment]
The [resolution from the June 28 interim](https://www.w3.org/2017/06/28-webrtc-minutes#item08) was to ignore the `id` parameter when `negotiated` is `false`. I like your suggestion too, but it could have a higher risk of breaking existing apps.
