### ISSUE TITLE
transceiver.currentDirection should be set to null when stopped

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1417]
The attribute description for `currentDirection` says _"if the transceiver is stopped, the value is null"_. But in the `stop()` description there is no step to set `currentDescription` to `null`.

In section _4.4.1.6 Set the RTCSessionSessionDescription_, the relevant steps for setting answer description should also check if the transceiver is stopped before setting the transceiver's `currentDirection`.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?

**Comment by adam-be** [comment]
The second point is a good observation. @soareschen, I'm creating a separate issue for that.
