### ISSUE TITLE
At risk text in wrong location

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1420]
If you look at https://w3c.github.io/webrtc-pc/#rtcrtcpmuxpolicy-enum and look at "Feature at risk note", it has the text "Support for the rtcpTransport attribute within the RTCRtpSender and RTCRtpReceiver ." in it. That text makes no sense here and should be moved.

**Comment by burnburn** [comment]
@fluffy are you sure this is true?  The rtcpTransport attribute will only have a value when RTCP mux is *not* used, a situation that implementers have not committed to supporting.  Thus, this feature is at risk precisely because of the situation described in the note.

**Comment by aboba** [comment]
@dontcallmedom Rather than including a separate note for the rtcpTransport attribute, the current text considers all aspects of RTP/RTCP non-mux as the "feature at risk".  How are things usually done in W3C specifications?

**Comment by fluffy** [comment]
I'll look it it again ... I'm not disagreeing on the feature we are talking about is at risk. But the note seemed to be attached to the wrong thing las time I looked at the rendered HTML.

**Comment by aboba** [comment]
@stefhak Should we close this?

**Comment by stefhak** [comment]
Yes, I think we should close. Closing.
