### ISSUE TITLE
What happens if you set a remote description with two tracks with the same ID?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1424]
This is possible even without SDP munging today:

```
sender1 = pc.addTrack(trackA);
// Do offer/answer.
sender1.replaceTrack(trackB);  // Still uses ID "A"; replaceTrack doesn't affect signaling.
sender2 = pc.addTrack(trackA);
```

Why would you do this? I don't know. But what should happen on the remote side? Do you get two tracks with ID "A"?

**Comment by aboba** [comment]
This issue was discussed at the virtual interim on June 28, and the decision made was to close it.
