### ISSUE TITLE
We shouldn't rely on the public API to access objects in the specification

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#1435]
From RTCRtpTransceiver.stop

```
7. Send an RTCP BYE for each SSRC in
  transceiver.sender.getParameters().encodings[i].ssrc,
  transceiver.sender.getParameters().encodings[i].fec.ssrc and
  transceiver.sender.getParameters().encodings[i].rtx.ssrc where i goes from 0 to
  transceiver.sender.getParameters().encodings.length-1.
```

**Comment by taylor-b** [comment]
This could probably change to "Send an RTCP BYE for each outgoing RTP stream being used by the sender," or something like that. I think that's clear enough to implementers.

**Comment by adam-be** [comment]
That sounds good to me. Can we reference JSEP perhaps?

**Comment by taylor-b** [comment]
There's nothing in JSEP to reference but we can reference RFC3550 (RTP).
