### ISSUE TITLE
Should refer to enums in a consistent way

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1438]
Should we refer to enums:

1. In a code block? `connected`
2. In quotes? "connected"
3. Both? `"connected"`

Since it's both code and a string, I'd prefer the latter.

**Comment by burnburn** [comment]
@aboba , you say that PR #1485 is a partial fix.  What remains?

**Comment by aboba** [comment]
@burnburn AFAIK it is fixed.  If there are any remaining issues we can reopen it.
