### ISSUE TITLE
RTCSctpTransport.maxMessageSize 0 case

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1446]
This spec's `RTCSctpTransport.maxMessageSize` description says:

> The maximum size of data that can be passed to RTCDataChannel's send() method.

In [the related SDP spec](https://tools.ietf.org/html/draft-ietf-mmusic-sctp-sdp-26#page-8), it's specified that

> If the SDP 'max-message-size' attribute contains a maximum message
size value of zero, it indicates the SCTP endpoint will handle
messages of any size, subject to memory capacity etc.

So, there is a `maxMessageSize = 0` case we need to handle in some way.

While messages of arbitrary size may not be possible in the browser as this specification does not provide a way to deliver partial messages (e.g. for this spec, all messages need to be buffered until they are complete), other implementations may support this (one already does).

This has been discussed in https://github.com/w3c/ortc/issues/626 as well.

**Comment by taylor-b** [comment]
My assumption was that the `maxMessageSize` attribute would return the intersection of the remote endpoint's capabilities and the browser's supported max message size. So if the remote endpoint says "max-message-size=0", but the implementation does have a limit, the attribute would return that limit.

So maybe we just need to make that more clear? And future-proof ourselves by handling the max size of 0 where we currently say:

> If the size of _data_ exceeds the value of `maxMessageSize` on _channel_'s associated `RTCSctpTransport`, throw a `TypeError`.

**Comment by lgrahl** [comment]
So, the browser should not blindly announce the maximum message size of the remote peer when it is not capable of sending such a large message? I completely agree. In code, I'd say:

```python
mms = can_send_mms if remote_mms == 0 else min(remote_mms, can_send_mms)
```
Would you agree with that?

**Comment by taylor-b** [comment]
Agreed.

**Comment by lgrahl** [comment]
@taylor-b It was been a while. Should I make a PR for this?

**Comment by lgrahl** [comment]
Correction, the algorithm would have to be:

```python
if can_send_mms == 0 or remote_mms == 0:
    mms = max(can_send_mms, remote_mms)
else:
    mms = min(can_send_mms, remote_mms)
```

**Comment by taylor-b** [comment]
@lgrahl Would be much appreciated, thanks!

**Comment by nils-ohlmeier** [comment]
@lgrahl lets clarify one thing in your described algorithm (I doesn't appear to affect the text in PR #1650 ): local_mms is some implementations internal send buffer size which never gets written out into SDP!
The mms value in the SDP only announces the receive buffer size. So do NOT mix the mms values from offer and answer, because then you are combining the receive buffers from both sides. But what you need to look at are the local send buffer + the remote receive buffer (taken from the remote's SDP's mms value).

**Comment by lgrahl** [comment]
Sh.., you're right, I did mix that up. What was I thinking...

```python
remote_mms = get_mms(remote_description, default=65535)
if can_send_mms == 0 or remote_mms == 0:
    mms = max(can_send_mms, remote_mms)
else:
    mms = min(can_send_mms, remote_mms)
```

Would you agree with that one @nils-ohlmeier?

**Comment by nils-ohlmeier** [comment]
Yep that looks better to me.

**Comment by adam-be** [comment]
I made a PR for #1650, but it feels like fixing this one would solve it all. @lgrahl, were you planning on baking a PR?

**Comment by lgrahl** [comment]
I was planning that but it may take a while until I'm able to do so. If you want to go for it - I'm happy with that. The algorithm should be fine now (hopefully). :)

**Comment by adam-be** [comment]
I did some work on `RTCSctpTransport` a few days ago and prepared for this change, so I can take a stab at it.

**Comment by adam-be** [comment]
The algorithm above, does it rely on the `can_send_mms` being defined the same way as `remote_mms` when it comes to he value 0?

**Comment by lgrahl** [comment]
If `can_send_mms` is `0`, then that means the implementation can handle incoming messages of arbitrary size. Did you mean that?

**Comment by adam-be** [comment]
Yes. The local value is also compared to 0.

**Comment by adam-be** [comment]
@lgrahl, Any thoughts on the case when `can_send_mms == 0`and `remote_mms == 0`?

**Comment by adam-be** [comment]
The fact that `can_send_mms` affects the value of the `maxMessageSize` attribute makes it a bit tricky to write a test for this feature. One option would be to expose that value as a read only attribute. Advanced apps talking to a WebRTC enabled server endpoint might wan to read it to be able to generate an SDP and get an expected `maxMessageSize` value.

**Comment by lgrahl** [comment]
If both are `0`, the result should be `0` meaning both the local peer can send messages of arbitrary size and the remote peer can receive messages of arbitrary size. Ping me again if that wasn't your question. :)

> Advanced apps talking to a WebRTC enabled server endpoint might wan to read it to be able to generate a custom SDP to get an expected `maxMessageSize` value.

I'm not sure what one would gain by that. Can you elaborate?

**Comment by adam-be** [comment]
> If both are 0, the result should be 0 meaning both the local peer can send messages of arbitrary size and the remote peer can receive messages of arbitrary size.

Then we need to update the `send()` method to handle that case. As currently specified, it would throw for any message if `maxMessageSize` is 0.

**Comment by adam-be** [comment]
> I'm not sure what one would gain by that. Can you elaborate?

Me neither. :) What I'm after here is that it's tricky to predict the value of `maxMessageSize` and make a test where you can compare with an expected value. The reason being the unknown `can_send_mms` that affects the outcome. I guess you could figure out what `can_send_mms` is by offering 0.

**Comment by lgrahl** [comment]
> Then we need to update the `send()` method to handle that case. As currently specified, it would throw for any message if `maxMessageSize` is 0.

You're absolutely right. (For some reason I thought we already had that description in there. I guess my brain mixed up spec work and the adapter PR I wrote.)

> What I'm after here is that it's tricky to predict the value of `maxMessageSize` and make a test where you can compare with an expected value.

So, in the tests, you do not know `can_send_mms` beforehand?

> I guess you could figure out what `can_send_mms` is by offering 0.

That would be a nice workaround and a test at the same time. Win-win. :)

**Comment by adam-be** [comment]
> So, in the tests, you do not know `can_send_mms` beforehand?

No. It's internal to the browser.

The tricky thing with testing this is that one would like to test for different values of `can_send_mms`, but it is what it is.

**Comment by lgrahl** [comment]
FWIW, I referred to `65535` in my examples. However, the correct default remote maximum mesage size is `65536`.
