### ISSUE TITLE
setConfiguration throwing InvalidModificationError with default values

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1447]
In set configuration, the fields `bundlePolicy`, `rtcpMuxPolicy`, and `iceCandidatePoolSize` are checked against the original values and if they are not the same, `InvalidModificationError` is thrown. e.g.:

> If configuration.bundlePolicy is set and its value differs from the connection's bundle policy, throw an InvalidModificationError.

But there is a problem with the wording _"if ___ is set"_. Because these fields all have default values as defined in `RTCConfiguration`, this means they are always set. So the following example would throw error:

```javascript
const pc = new RTCPeerConnection({ bundlePolicy: 'max-bundle' });
// throws InvalidModificationError because provided default bundlePolicy is 'balanced'
pc.setConfiguration({});
```

**Comment by taylor-b** [comment]
Do we just need to change the wording to be more clear, or do you think the error being thrown is a problem? If an application does this, then things should work fine:

```
var config = { bundlePolicy: 'max-bundle' };
const pc = new RTCPeerConnection(config);

// Later on, fiddle with some bits of |config|.
config.iceServers = [...]
pc.setConfiguration(config);
```

Which seems like more maintainable code anyway.

**Comment by aboba** [comment]
While I would suggest removing the "is set" statements for attributes with defaults, the errors are being thrown correctly (a dictionary entry is being changed and that is forbidden).

**Comment by soareschen** [comment]
> Do we just need to change the wording to be more clear, or do you think the error being thrown is a problem?

In general I find the behavior of default values in `setConfiguration` to be unintuitive and may bring surprise to unfamiliar users. Other than the issues mentioned above and #1454, the default value for `iceTransportPolicy` can also cause unexpected bug:

```javascript
const pc = new RTCPeerConnection({ iceTransportPolicy: 'relay' });
pc.setConfiguration({});

pc.getConfiguration().iceTransportPolicy; // now become 'all'
```

The coding convention @taylor-b mentioned above can workaround the issue. But that means users would need to follow the convention to avoid unexpected bugs, and there should be notes some where to recommend the coding convention.

**Comment by taylor-b** [comment]
> there should be notes some where to recommend the coding convention.

Assuming people don't want to change the behavior, that seems like the best resolution.
