### ISSUE TITLE
updateIce should be called setConfiguration

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#145]
> Originally reported on W3C Bugzilla [ISSUE-25596](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25596) Thu, 08 May 2014 06:00:44 GMT
> Reported by Harald Alvestrand
> Assigned to 

After discussion on the list (May 2014), it seems agreed that:

- updateIce is a bad name for the function, since it updates more than ICE
- it makes sense to just give a single call that updates the configuration given to the RTCPeerCOnnection constructor
- setConfiguration() is a good name for this function
- we also need getConfiguration() to provide the ability to modify a configuration parameter

This seems ready for editing.

**Comment by dontcallmedom** [comment]
addressed in #185 (but that one will itself likely be split into new PRs)

**Comment by alvestrand** [comment]
New PR is #211

**Comment by alvestrand** [comment]
#211 has been merged.
