### ISSUE TITLE
No way to associate streams using addTransceiver()

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1452]
As I mention in https://github.com/w3c/webrtc-pc/issues/1237#issuecomment-313210542, JSEP says:
 * *"For each MediaStream that was associated with the transceiver when it was created via addTrack or addTransceiver, an "a=msid" line, as specified in [I-D.ietf-mmusic-msid]"*

But there's no way to associate a MediaStream with a transceiver using `addTransceiver`. Omission or bug in JSEP?

E.g. the [warm-up example](http://w3c.github.io/webrtc-pc/#advanced-peer-to-peer-example-with-warm-up) and [simulcast example](http://w3c.github.io/webrtc-pc/#simulcast-example) in the spec are only possible with zero stream associations.

**Comment by taylor-b** [comment]
> But there's no way to associate a MediaStream with a transceiver using addTransceiver.

JSEP says:

> At the time of creation, the application can also specify ...  a set of MediaStreams which the transceiver is associated with

And in WebRTC 1.0, `RTCRtpTransceiverInit` contains a sequence of streams. So I don't see what's missing.

**Comment by jan-ivar** [comment]
@taylor-b You're right. Don't know how I missed that.
