### ISSUE TITLE
setLocalDescription() with null sdp is not applicable

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1465]
The IDL definition for `setLocalDescription()` accepts an `RTCSessionDescriptionInit`, not `RTCSessionDescription`. The `sdp` field in `RTCSessionDescriptionInit` is optional but not nullable, and have a default value `''`. So the step in `setLocalDescription()` for using the last offer/answer if `description.sdp` is `null` is not applicable.

**Comment by aboba** [comment]
Looks like [Section 4.4.2](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#dom-rtcpeerconnection-setlocaldescription) steps 4 and 5 should test for `''` instead of `null`.
