### ISSUE TITLE
RTCTrackEvent's type parameter

### ISSUE THREAD

**Issue by rwaldron** [w3c/webrtc-pc#1467]
I'm trying to understand what the role of the RTCTrackEvent's `type` parameter is, as it's defined: 

Parameter | Type | Nullable | Optional | Description
-- | -- | -- | -- | --
type | DOMString | ✘ | ✘ |  
eventInitDict | RTCTrackEventInit | ✘ | ✘

Questions: 

1. What are the valid values for this parameter? As far as I can tell, there are none. 
    - Run the following in Safari Technology Preview (the only browser I have that supports everything below): 
        ```js
        var pc = new RTCPeerConnection();
        var transceiver = pc.addTransceiver('audio');
        var { receiver, receiver: { track } } = transceiver;

        var trackEvent = new RTCTrackEvent('this is obviously bogus', {
          receiver, track, transceiver
        });

        console.log(trackEvent.type); // 'this is obviously bogus'
        ```    

2. If there are no explicitly defined valid values, or such a thing is not really necessary: can the specification define a default, which also overrides any user input?

**Comment by fippo** [comment]
running this in Firefox (from the wpt SRD test)
```
    const sdp = `v=0
o=- 166855176514521964 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:someufrag
a=ice-pwd:somelongpwdwithenoughrandomness
a=fingerprint:sha-256 8C:71:B3:8D:A5:38:FD:8F:A4:2E:A2:65:6C:86:52:BC:E0:6E:94:F2:9F:7C:4D:B5:DF:AF:AA:6F:44:90:8D:F4
a=setup:actpass
a=rtcp-mux
a=mid:mid1
a=sendonly
a=rtpmap:111 opus/48000/2
a=msid:stream1 track1
a=ssrc:1001 cname:some
`;
var pc = new RTCPeerConnection();
    pc.ontrack = (event => {
      console.log("ontrack", event.type);
    });

    pc.setRemoteDescription(new RTCSessionDescription({type: 'offer', sdp: sdp}))
```
suggests 'track', i.e. the event name.

**Comment by jan-ivar** [comment]
The `type` and `eventInitDict` parameters are [required for Events](https://dom.spec.whatwg.org/#constructing-events). Best practice is to include constructors for shims to use.

We *[fire a track event](http://w3c.github.io/webrtc-pc/#fire-track-event) [named](https://dom.spec.whatwg.org/#firing-events) "track"* [here](http://w3c.github.io/webrtc-pc/#set-description), but you can set it to anything you want.
