### ISSUE TITLE
Performing rollback via the other set*Description

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1470]
JSEP 4.1.8.2. says:

> A rollback is performed by supplying a session description of type "rollback" with empty contents to either setLocalDescription or setRemoteDescription, depending on which was most recently used (i.e. if the new offer was supplied to setLocalDescription, the rollback should be done using setLocalDescription as well).

The current spec doesn't seem to impose such restriction. So say if one calls `setLocalDescription(offer)` then `setRemoteDescription(rollback)`, should there be error thrown?

**Comment by aboba** [comment]
Looks like steps should be added to 4.4.1.6 Set the RTCSessionSessionDescription to check for invalid rollback. Also, it may make sense to file an issue against JSEP.

**Comment by fluffy** [comment]
Given rollback is one of the way to recover from an some errors, my preference is pretty much no matter what state you are in, and no matter which set* got called, exactly the same things happens which is you roll back to last stable state. If you are in a stable state, then it just stays at that same stable state. What I am trying to avoid is needing error handling for my error handling code. It would be really nice if doing a rollback did not cause an error. That would make is easy to use for when a error happened and it would just move you back to basically last known good  state. From an implementation point of view in the browsers, I don't think this changes very much what needs to be implemented.

**Comment by fluffy** [comment]
As side note, JSEP has bugs with this same conversation going on. I suspect that JSEP is the right place to figure out what we want to have happen then figure out how to reflect any call or errors needed into the API.
