### ISSUE TITLE
Clarify that rollback in stable state should throw InvalidStateError

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1471]
Step 2.1.2. of set session description says:

> If the description's type is invalid for the current signaling state of connection as described in [JSEP] (section 5.5. and section 5.6.), then reject p with a newly created InvalidStateError and abort these steps.

But the state validation for rollback is mentioned in JSEP section 4.1.8.2.:

> Rollback can only be used to cancel proposed changes; there is no support for rolling back from a stable state to a previous stable state

So step 2.1.2. should add one more reference to JSEP 4.1.8.2. to make it clear that `InvalidStateError` is thrown if rollback is called in stable state.

**Comment by aboba** [comment]
JSEP section 5.5 already refers to section 4.1.8.2, so we don't need a reference in WebRTC-PC as well.
