### ISSUE TITLE
Data Channel ID assignment after SCTP renegotiation

### ISSUE THREAD

**Issue by rshpount** [w3c/webrtc-pc#1475]
As far as I understand, underlying SCTP association can be renegotiated for the same datachannel. What happens with channel ID auto-assignment if SCTP association gets renegotiated? Do they even/off assignment rules flip or do they stay with the original assignment?

**Comment by taylor-b** [comment]
> As far as I understand, underlying SCTP association can be renegotiated for the same datachannel.

Not as I understood it. Some excerpts from rtcweb-data-channel:

>    The realization of a data channel is a pair of one incoming stream
>    and one outgoing SCTP stream having the same SCTP stream identifier.

>    SCTP defines a stream as a unidirectional logical channel existing
>    within an SCTP association to another SCTP endpoint.  

>    If an SCTP association is closed in a graceful way, all of its data
>    channels are closed.  In case of a non-graceful teardown, all data
>    channels are also closed, but an error indication SHOULD be provided
>    if possible.

WebRTC 1.0 is consistent with this, though it uses the phrase "underlying data transport" in place of "SCTP association".

**Comment by rshpount** [comment]
This makes sense. Sorry for misunderstanding.

**Comment by taylor-b** [comment]
No problem; closing issue in that case.
