### ISSUE TITLE
Minor inconsistencies around RTCSessionDescription vs. RTCSessionDescriptionInit

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1477]
I noticed some minor issues related to the use of `RTCSessionDescription` (the interface) and `RTCSessionDescriptionInit` (the dictionary):

- There's a section called "Set the RTCSessionSessionDescription". That's one too many "Session"s.
- This section talks about setting an `RTCSessionDescription`, but it's actually an `RTCSessionDescriptionInit` that goes into `setLocalDescription` and `setRemoteDescription`. Is there a missing "construct `RTCSessionDescription` from `RTCSessionDescriptionInit` step"?
- If we do go that route, then the constructor of `RTCSessionDescription` is no longer just for legacy purposes.

It may also be nice to explain somewhere in human-readable language _why_ we have two things. Is it just for legacy purposes, to support the following?

`pc.setLocalDescription(new RTCSessionDescription({sdp: sdpString, type: "offer"}));`

But does this work? `setLocalDescription` and `setRemoteDescription` no longer accept `RTCSessionDescription` as arguments. Or do they, because an `RTCSessionDescription` is capable of being converted to an `RTCSessionDescriptionInit`?

**Comment by jan-ivar** [comment]
The reason we have two things is that dictionaries cannot be attributes:
```js
readonly attribute RTCSessionDescription? localDescription;
```
...yet at the same time we want to write:
```js
pc.setLocalDescription({sdp: sdpString, type: "offer"});
```
> an RTCSessionDescription is capable of being converted to an RTCSessionDescriptionInit?

👍
The former browser object is valid input to a method expecting the latter dictionary, but not vise versa.

Conceptually they're interchangeable. Unfortunately, the better name is taken by the legacy constructor. We have prose that mixes concept and type in places, like:

*"The initial value of `mid` is null. Setting a new `RTCSessionDescription` may change it to a non-null value, as defined in [JSEP] (section 5.5. and section 5.6.)."*

In this case, [section 5.5](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-5.5) actually uses "SessionDescription" (though [section 4.1.8](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-4.1.8) suggests this means `RTCSessionDescription`). In either case, it sounds odd to say:

*"The initial value of `mid` is null. Setting a new `RTCSessionDescriptionInit` may change it to a non-null value, as defined in [JSEP] (section 5.5. and section 5.6.)."*

...even though we probably should. This also highlights that we should probably link to our own [setting an RTCSessionDescription](https://rawgit.com/fippo/webrtc-pc/cb8db929324c094144574ff6c8ce03f28f2640bb/webrtc.html#set-description) algorithm here.

**Comment by aboba** [comment]
@jan-ivar What do we need to do here?

**Comment by henbos** [comment]
Nag ping ;)

**Comment by jan-ivar** [comment]
Will do a pass to root out uses of RTCSessionDescription as a concept in favor of just "description"
