### ISSUE TITLE
toJSON Dfn needed

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1484]
The current "[tip of tree](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html)" draft shows the following warning: 

"No dfn for toJSON in RTCSessionDescription. Please define it and link to spec that declares it. See https://github.com/w3c/respec/wiki/data--cite"

**Comment by dontcallmedom** [comment]
This will be fixed when we upgrade ReSpec, cf https://github.com/w3c/respec/issues/1309

Since @vivienlacourba  owns the ReSpec upgrade workflow, re-assigning to him

**Comment by aboba** [comment]
I tried respec v16.0.  Didn't fix the issue.

**Comment by aboba** [comment]
This issue has been resolved.
