### ISSUE TITLE
Result returned from receiver.getParameters() when no session description is set

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1490]
The current description for `RTCRtpReceiver`'s `getParameters()` seems to apply based on the local/remote description set. It is not clear what should be the result if `set*Description()` have not been called before.

The spec should also be more clear of which exact session description affects the result of `getParameters()`. i.e. `currentRemoteDescription` of the associated connection object, instead of just "current remote description".

**Comment by aboba** [comment]
The `sendEncodings` can be set by `addTransceiver` before SLD/SRD is called, and this should also affect `getParameters`.

**Comment by soareschen** [comment]
The `sendEncodings` passed to `addTransceiver` only applies to `RTCRtpSender`, not `RTCRtpReceiver`.  "current remote description" works as well, just less concise.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?

**Comment by soareschen** [comment]
Upon rereading I realize it might not be a good idea to tightly couple the result of getParameters with the session description. RTCRtpSender's setParameters suggest that setting parameters do not require SDP renegotiation. I suppose that means the remote receiver's parameters can be affected based on the RTP connection as well?

If so the description for getParameters can be left as is, and we leave it to lower level protocols to determine the result. This issue can be closed then.
