### ISSUE TITLE
Required fields in RTCRtpParameters returned from getParameters

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1493]
This is similar to  #1476.

Currently all fields in RTCRtpParameters are defined to be optional. This means when writing applications and tests we cannot make assumption of any of the field returned from `getParameters()` is defined.

I have a feeling that `encodings`, `headerExtensions`, and `codecs` should at least be empty list, and that all if not most of the readonly fields in `RTCRtpCodecParameters`, `RTCRtpHeaderExtensionParameters`, and `RTCRtcpParameters` should be required?

**Comment by aboba** [comment]
The fields in `RTCRtpParameters` that are set will depend on the signaling state as well as whether `addTransceiver` or `setParameters` has been called.

**Comment by soareschen** [comment]
I realize that the reason the WebIDL definition has all dictionary fields as optional is because it is used in multiple cases such as sender/receiver's getParameters, and there is different required fields for each case.

In that case the definitions for `getParameters()` in `RTCRtpSender` and `RTCRtpReceiver` should respectively list out the fields that are required to be set. Currently the requirements are somehow already there, but the wordings are pretty loose so it is a bit hard to get normative about it. For example:

> rtcp.cname is set to the CNAME of the associated RTCPeerConnection. rtcp.reducedSize is set to true if reduced-size RTCP has been negotiated for sending, and false otherwise.

This implies that `rtcp` field should be set, because you can't set attributes on `undefined`. `rtcp.cname` and `rtcp.reducedSize` seems to be required to be set as well, but it is not clear if `undefined` is allowed, e.g. before RTP connection is established?

> The headerExtensions sequence is populated based on the header extensions that have been negotiated for sending. 

This implies `headerExtensions` should at least be set to empty array.

> The codecs sequence is populated based on the codecs that have been negotiated for sending, and which the user agent is currently capable of sending.

It is not very clear if `codecs` can be empty array. Implementation should be expected to return at least one codecs. In any case `codecs` likely shouldn't be `undefined`.

> degradationPreference is set to the last value passed into setParameters, or the default value of "balanced" if setParameters hasn't been called. 

This is actually an optional field, because `degradationPreference` can be unset through `setParameters()`.

For `RTCRtpHeaderExtensionParameters`, according to RFC5285, at least the `uri` and `id` fields should be set, if `headerExtensions` contains any elements?

**Comment by jan-ivar** [comment]
This is a good example of why we can't use `required` *solely* to guarantee what's being returned, because the same dictionary is also the input to `setParameters` where its primary normative meaning causes `TypeErrors` in that method if members are missing.

At the same time, it may be a good example of where the two requirements align, allowing us to do just that.

In general, this may be a good measuring stick: for any get method returning a dictionary, imagine a future set method taking that argument, if one does not currently exist, and use that to guide what should be `required`. If that ends up matching what we want, great!

It seems to me we could at least make [transactionId](http://w3c.github.io/webrtc-pc/#dom-rtcrtpparameters-transactionid) `required`, based on its stated intent.

**Comment by jan-ivar** [comment]
Ugh, I didn't see `transactionId` is only used by senders. Should we perhaps move `transactionId` and `degradationPreference` into an inherited dictionary instead?
```js
dictionary RTCSendRtpParameters : RTCRtpParameters {
    DOMString                transactionId;
    RTCDegradationPreference degradationPreference;
};
```

> encodings, headerExtensions, and codecs should at least be empty list

Agree.

**Comment by aboba** [comment]
@jan-ivar Can you file a more specific issue?

**Comment by jan-ivar** [comment]
On re-reading the spec, the intent behind `transactionId` and [[LastReturnedParameters]], appears to be to require JS to only call `setParameters()` with modified results from the most recent `getParameters()`. With that in mind, I agree with @soareschen using `required` is clearer.

I have a PR with this and the split I suggested [above](https://github.com/w3c/webrtc-pc/issues/1493#issuecomment-324949511), so I'm re-opening to add it here.
