### ISSUE TITLE
Processing Remote MediaStreamTracks should pass on receiver when constructing track event

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1499]
In the last step of 5.1.1 Processing Remote MediaStreamTracks:

> Queue a task to fire an event named track with transceiver, track, and streams at the connection object.

It missed out the receiver attribute in ` RTCTrackEvent`, which we know is simply getting from `transceiver.receiver`.

**Comment by stefhak** [comment]
I think this is on purpose, as you say the app can easily get hold of the receiver via the Transceiver.

**Comment by jan-ivar** [comment]
```js
pc.ontrack = e => e.tranceiver.receiver;
```

**Comment by soareschen** [comment]
What I mean is the WebIDL definition for `RTCTrackEvent` has a `receiver` field. So that attribute should either be removed or filled with `transceiver.receiver`, no?

**Comment by jan-ivar** [comment]
@soareschen Yeah that seems redundant to me. We should remove both the `receiver` readonly attribute and the corresponding member in `RTCTrackEventInit` IMHO.

**Comment by jan-ivar** [comment]
Since Firefox already supports `e.receiver`, we'd continue to for a while for legacy reasons.

**Comment by stefhak** [comment]
@soareschen got it (https://github.com/w3c/webrtc-pc/issues/1499#issuecomment-319687209). Could you provide a PR?

**Comment by jan-ivar** [comment]
PR up.

**Comment by soareschen** [comment]
Thanks @jan-ivar!

@stefhak sorry I am rushing on another project, didn't get the time to work on it.

**Comment by jan-ivar** [comment]
Doh, I misread @stefhak's message as coming from @soareschen 🙂

**Comment by jan-ivar** [comment]
I've closed https://github.com/w3c/webrtc-pc/pull/1532.

@soareschen can you add a PR to fill in `event.receiver` with `transceiver.receiver` instead?

**Comment by stefhak** [comment]
Ping @soareschen !

**Comment by stefhak** [comment]
This has been a while now. @jan-ivar, what would be the gain of 
> fill in `event.receiver` with `transceiver.receiver` instead
?

It seems to me we can leave things as they are
