### ISSUE TITLE
setIdentityProvider should throw error if protocol contains invalid characters

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1500]
Description for `protocol` field in `RTCIdentityProviderOptions`:

> The name of the protocol that is used by the identity provider. This MUST NOT include '/' (U+002F) or '\' (U+005C) characters. This value defaults to "default" if not provided.

Right now there is no step for validating `protocol` in `setIdentityProvider()`. It should instead throw specific kind of error. (`InvalidAccessError` perhaps?)

**Comment by martinthomson** [comment]
Not a question, just a bug.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?
