### ISSUE TITLE
Format of provider string for setIdentityProvider and validation

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1501]
Currently there is no mention of what kind of format should the `provider` string be. My understanding is that it should be the `host` portion of a URL, which include domain name and port.

`setIdentityProvider()` should throw specific error if the `provider` string is not of the right format.

**Comment by martinthomson** [comment]
Duplicate of #1502.

**Comment by soareschen** [comment]
This is not exactly a duplicate of #1502. Here at #1501 is about the format for `provider` in `setIdentityProvider`; #1502 is about the format for `domain` in `RTCIdentityProviderDetails`.
