### ISSUE TITLE
Identity assertion process should wait for certificate to be generated

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1503]
Indentity assertion requires use of certificate fingerprint. In steps to create offer/answer, the step for waiting for certificate generation should go before waiting for identity assertion process.

The certificate generation should also be triggered in other places, such as in `getIdentityAssertion()` and section 9.3 Requesting Identity Assertions. Some refactoring can be done to simplify the steps.

**Comment by martinthomson** [comment]
This isn't a question, it's just an issue to track a (reasonable) change to the algorithm.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?
