### ISSUE TITLE
Origin value for IdP proxy script

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1504]
In rtcweb-security-arch section 6.4.1.  PeerConnection Origin Check:

> In order to prevent this attack, we require that all signatures be tied to a specific origin ("rtcweb://...") which cannot be produced by content JavaScript.

Does this means that in section 9.1.2 Instantiating an IdP Proxy, it should specify that the origin value inside the IdP proxy script would be using the `rtcweb://` protocol instead of `https://`?

**Comment by martinthomson** [comment]
See https://github.com/rtcweb-wg/security-arch/issues/41
