### ISSUE TITLE
setRemoteDescription should fail if target peer identity is set but no a=identity in SDP

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1512]
Currently the identity assertion validation is only done if an a=identity line is present. This means an impostor can simply not include any a=identity line and get connected to a victim.

**Comment by martinthomson** [comment]
Seems reasonable.

You had me worried there for a minute.  In we check the identity every time.  If `a=identity` isn't present, then we set the actual identity to `null`.  If we have a target identity, then `setRemoteDescription` without `a=identity` causes a failure.

**Comment by soareschen** [comment]
>  In we check the identity every time. If a=identity isn't present, then we set the actual identity to null. If we have a target identity, then setRemoteDescription without a=identity causes a failure.

If so then the spec should add some steps to clarify. For example something like:

> (Introduce new variable, e.g. _newPeerIdentity_)
>
> If an a=identity attribute is present in the session description, let _newPeerIdentity_ be the result of validating the identity assertion. Else let _newPeerIdentity_ be null.
>
> If target peer identity is set and is different from _newPeerIdentity_, the user agent MUST reject the returned promise with a newly created InvalidModificationError and abort this operation. The RTCPeerConnection MUST be closed if the validated peer identity does not match the target peer identity. Else set target peer identity to _newPeerIdentity_.

This would have a few implications:

- If SRD is first called with a=identity then without it, the operation fails with `InvalidModificationError` and the connection closes.
- If SRD is first called with no a=identity then with it, the operation also fails with `InvalidModificationError` and the connection closes.
