### ISSUE TITLE
insertDTMF when transceiver.currentDirection is null

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1515]
Currently step 4 of `insertDTMF` throws `InvalidStateError` when `currentDirection` is `recvonly` or `inactive`. But `currentDirection` is only set after setting answer description.

Since it probably doesn't make sense to send DTMF before connection is established, we can probably make `insertDTMF` throw `InvalidStateError` as well when `currentDirection` is `null`.

One minor issue remain is that `insertDTMF` can be called before the RTP connection is fully established. Though I guess that just means the tone sent is lost and it is up to the application to control the UI to prevent sending before connected.

**Comment by aboba** [comment]
@soareschen Can you submit a PR?

**Comment by soareschen** [comment]
I can work on that. Btw the current behavior for Firefox is that `insertDTMF()` works as soon as sender is created. So the proposed solution of throwing error if `currentDirection` is `null` doesn't work if we want to maintain backward compatibility.

It seems a bit tricky to modify this in a consistent way. Perhaps we could make it check the value of `direction` instead if `currentDirection` is `null`.

**Comment by taylor-b** [comment]
Checking `direction` wouldn't really make sense; the point of checking `currentDirection` is to tell if it's impossible for `insertDTMF` to do anything, due to the required SDP negotiation not being done yet, but `direction` doesn't tell you anything in that regard.

**Comment by soareschen** [comment]
In that case I think the best way is to keep the current behavior and allow `insertDTMF()` when `[[CurrentDirection]]` is `null`. That is the current behavior of Firefox and we probably don't want to break compatibility.

Will close this issue unless there are better solution out there.
