### ISSUE TITLE
Constructor for RTCDTMFToneChangeEvent does not validate format of tone

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1518]
Currently it is possible to manually construct `RTCDTMFToneChangeEvent` instances with `tone` having arbitrary characters of any length.

The fix is to add a step in the constructor:

- If `tone` contains any unrecognized characters, or if `tone` has more than one character, throw an `InvalidCharacterError`.

**Comment by taylor-b** [comment]
I don't think we need to worry about doing input validation for event constructors, since only the browser is expected to use them.
