### ISSUE TITLE
setParameters does input validation in parallel, and doesn't actually apply parameters?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1520]
The only steps listed in the `setParameters` algorithm do input validation. It's not clear why these steps are done in parallel, especially where they interact with `getParameters` (which is synchronous), which introduces race conditions.

If the reason we made `setParameters` promise-based was because it may involve I/O operations that can fail, then a more sensible algorithm to me would be:

1. Do input validation synchronously.
2. In parallel, attempt to start using parameters, resolving or rejecting promise appropriately.

**Comment by burnburn** [comment]
+1

**Comment by adam-be** [comment]
+1
