### ISSUE TITLE
What happens if RTCDataChannelInit.negotiated is true, but id is absent?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1529]
This is the inverse of #1413: an application negotiating the data channel out-of-band, but _not_ providing an ID. This is guaranteed to not work, since one side would select an even ID and one side would select an odd ID, and they wouldn't match up. So unless I'm missing something, I think we should throw an error when this is attempted.

**Comment by lgrahl** [comment]
> I think we should throw an error when this is attempted.

:+1: for an explicit API.

Again, I believe we should eventually unify `negotiated` and `id` unless there's a use case for having them separate (as [commented here earlier](https://github.com/w3c/webrtc-pc/issues/1413#issuecomment-314169219)).

**Comment by stefhak** [comment]
@adam-be to provide a PR.

**Comment by adam-be** [comment]
Patched our current behavior, but I agree that the single attribute API mentioned above is preferable.
