### ISSUE TITLE
Normative language in upper case

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1537]
Normative language is back in lower case: must, should, etc. 

We changed webrtc.css earlier to show RFC2119 keywords in small-caps.  Why did it revert?

**Comment by dontcallmedom** [comment]
I don't think it was reverted - the change was brought to `master` on June 6, whereas the latest editors draft is dated June 5. I assume it will show as expected once `gh-pages` is upgraded to match `master`.

**Comment by aboba** [comment]
Still showing as lower case in "tip of tree": https://rawgit.com/w3c/webrtc-pc/master/webrtc.html

**Comment by dontcallmedom** [comment]
I fixed it with https://github.com/w3c/webrtc-pc/commit/f798246477c7ba709287b92f9ee520376c1f8f74
