### ISSUE TITLE
Unable to access certificate information in the API

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#154]
> Originally reported on W3C Bugzilla [ISSUE-21879](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21879) Tue, 30 Apr 2013 17:36:50 GMT
> Reported by Martin Thomson
> Assigned to 

The identity of the peer for an RTCPeerConnection is valuable information.  Current work concentrates on the mechanisms for authenticating this peer and presenting identification information on browser chrome.  No API surface is provided for inspecting the certificate presented by the peer.  No API surface is provided for inspecting the certificate that will be presented to the peer.

Providing access to certificates allows an application to make in-content assertions about the peer identity, as well as provide additional checks.  For instance, an application might be unable to use peer identity, but can provide their own assurances about peer identity.

In terms of what information is provided, this doesn't need to be robust.  I don't know what the WebCrypto group has done so far on this, but taking advantage of any API defined there is probably sensible.  At a minimum, this should provide access to the CN, DER-encoded certificate and a couple of certificate fingerprints (SHA-1 and SHA-256 probably).

**Comment by dontcallmedom** [comment]
Is this a dup #147?

**Comment by martinthomson** [comment]
> Is this a dup #147?

Yes.

**Comment by dontcallmedom** [comment]
Thus closing
