### ISSUE TITLE
Invalid JSON in examples

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#1543]
Many of the examples got changed from  something like 
{ "a" : 1 } 
to 
{ a:1 }
But that is not valid JSON and given much of the examples are JSON passed to other things, I think it would be better if the examples were valid JSON.

**Comment by dontcallmedom** [comment]
the change was proposed in #1444 and made in #1462. /cc @taylor-b & @aboba

**Comment by aboba** [comment]
[RFC 7159](https://tools.ietf.org/html/rfc7159) Section 7 specifies the use of quotation marks: 

string = quotation-mark *char quotation-mark

@taylor-b Is there a reason not to revert this?

**Comment by dontcallmedom** [comment]
While the quotes are required in JSON, they're not in regular JavaScript, and the examples either call `JSON.stringify` which take care of all the syntactic changes needed for JSON, or would not be expected a priori to be shared via JSON (e.g. `getUserMedia` parameter, or configuration options for `RTCPeerConnection`.

All that to say - this is a cosmetic decision, there isn't one wrong per se. From my arbirtrary perspective, using quote-less property names for JavaScript objects increase readability. (i.e. I would prefer that we do not revert - but I don't feel very strongly)

**Comment by fluffy** [comment]
There are some things like candidates that we say are JSON and those I think do need to have quotes but when I looked at the things the PR changed, none of them were things that get passed to far side or they had the JSON.stringify so I think either the quote or non quote are "OK" - it is more style. Now that have I looked at all the changes in the PR that changed this (thank Dom for pointing that out), I can live with this either way.

**Comment by aboba** [comment]
I am going to close this.  Feel free to reopen if there is something that needs to be changed.

**Comment by alvestrand** [comment]
{ a:1 } is valid Javascript.
The examples are Javascript not JSON.
Where do we say candidates are JSON?
