### ISSUE TITLE
Use automatically generated default toJSON() method (when available)

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#1546]
We currently specify the description of our default toJSON method. Respec.js might do this automatically in the future.

Related https://github.com/w3c/respec/issues/1309

**Comment by stefhak** [comment]
AFAICT this has been fixed. Can you verify @jan-ivar . I'll close if you agree.

**Comment by stefhak** [comment]
I'll draft a PR that makes use of the `Default` behavior.

**Comment by jan-ivar** [comment]
Looks like we can remove our toJSON prose now in cases where we don't need special behavior (worked when I tried it).
