### ISSUE TITLE
getLocalStreams and getRemoteStreams should return empty sequence after Peerconnection::close

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#155]
> Originally reported on W3C Bugzilla [ISSUE-21086](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21086) Fri, 22 Feb 2013 12:21:19 GMT
> Reported by Per
> Assigned to 

I suggest PeerConnection::getLocalStream and getRemoteStreams() return empy sequence after PeerConnection::close has been called.

**Comment by dontcallmedom** [comment]
these have landed so I think this can be closed as OBE @stefhak @alvestrand

**Comment by jan-ivar** [comment]
Not that I have an opinion, but does the same question not exist for getSenders() and getReceivers() ?

**Comment by juberti** [comment]
I thought the plan was for these APIs to return the state that existed immediately prior to close(). I believe that is the case for setLocal/setRemote, and so we should be consistent with that.

**Comment by martinthomson** [comment]
I thought the same as Justin.  There's work involved in cleaning all that stuff up and we need to continue to report stats.  Reporting stats for things that had to be cleaned up will be annoying to consume.

**Comment by jan-ivar** [comment]
Works for me.

**Comment by alvestrand** [comment]
Closing as resolved - no change needed.
