### ISSUE TITLE
add note about addtrack being async

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#156]
> Originally reported on W3C Bugzilla [ISSUE-25836](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25836) Tue, 20 May 2014 20:26:49 GMT
> Reported by Cullen Jennings
> Assigned to 

add notes that

Since addTrack is async, and getTracks is not, after you add one, there may be some time before it shows up in getTracks

**Comment by stefhak** [comment]
Message sent to list: https://lists.w3.org/Archives/Public/public-webrtc/2015Apr/0135.html
Waiting for discussion.

**Comment by alvestrand** [comment]
See PR #225 and the discussion in the JSEP repository that it links to.

**Comment by stefhak** [comment]
I think this has been OBE; addTrack and addTransceiver are both synchronous. I propose we close this issue with no action.

**Comment by alvestrand** [comment]
Closing.
