### ISSUE TITLE
Deciding on resolutions with scaleResolutionDownBy

### ISSUE THREAD

**Issue by Pehrsons** [w3c/webrtc-pc#1564]
The spec mentions constraints on the value of `scaleResolutionDownBy` but not how it applies when actually scaling video frames.

I have a couple of cases in mind where it is unclear what resolution will be sent over the wire:

- Common input `640x480`, odd `scaleResolutionDownBy` `x9.0`.
  - You can't scale to `71.111x53.333`
- Odd input (say canvas or application sharing), e.g., `705x529`, `scaleResolutionDownBy` `x2.0`.
  - You can't scale to `78.333x58.778`
- The encoder doesn't handle scaling to certain resolutions
  - webrtc.org requires that all layers have identical aspect ratio, see [1], so a scaling factor where the result has to be rounded (like the two above) need a bit more massaging to be accepted. Not sure about other implementations or hardware encoders.

[1] http://searchfox.org/mozilla-central/rev/b318c7dca7392bd16c0b11929f55b1be133f0b31/media/webrtc/trunk/webrtc/modules/video_coding/codecs/vp8/simulcast_encoder_adapter.cc#62

**Comment by aboba** [comment]
@Pehrsons I am adding this to the list of Issues to be discussed at the WEBRTC WG virtual interim on September 13.

**Comment by stefhak** [comment]
@Pehrsons my understanding was always that the UA would do its best given the input it has, so that would to me mean rounding to the closest resolution it can handle. This would mean that it would vary (including how "closest" is defined) between UAs.

Would you agree that would be an acceptable resolution in your opinion?

And, what does others think?

**Comment by stefhak** [comment]
@Pehrsons ping!

**Comment by Pehrsons** [comment]
Sorry for the late reply.

That would work for me.

My intuition when working with this was that, since we're scaling down, we should pick the closest *lower* resolution when there's no direct match, if one exists. If not, we go up.

I don't have a strong opinion about the approach taken though.

**Comment by stefhak** [comment]
@Pehrsons NP. I would trust your intuition more than mine - you're working with this, I've only been thinking a bit about it.
Thanks in advance for providing a PR! :)

**Comment by Pehrsons** [comment]
I haven't come up with really solid cases for either option.

Some thoughts are:
With scaling down you could end up going much further than you would have otherwise.
Compared to max-fs and the like, scaling up might be surprising. It's not really a substitute then -- but perhaps it shouldn't be.

**Comment by fluffy** [comment]
I find that letting the application set the actual resolution it wants works better than a scale factor but assuming we stay with a scale factor, I think saying that it rounds to nearest integer would clear this up.

**Comment by jan-ivar** [comment]
What about the third case?
> * The encoder doesn't handle scaling to certain resolutions 
>   * webrtc.org requires that all layers have identical aspect ratio, see [1]

Rounding to the nearest integer can create unintended aspect changes. Consider:

```js
await sender.setParameters({encodings: [
  { rid: "high" },                             // 320x240
  { rid: "medium", scaleResolutionDownBy: 2 }, // 160x120 (320*120 - 160*240 = 0)
  { rid: "low", scaleResolutionDownBy: 3 },    // 107x80  (320*80 - 107*240 = -80)
]});
```

**Comment by stefhak** [comment]
I agree to that rounding creates this problem, but saw that as "maintaining aspect ration as far as reasonable" or something like that. Unless we can transmit fractional pixels we will either have this rounding error or would not transmit unless both divisions give integer results.

**Comment by jan-ivar** [comment]
I agree with "as far as reassonable", I just didn't see that reflected in the PR.
