### ISSUE TITLE
Stream rejection not possible

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#157]
> Originally reported on W3C Bugzilla [ISSUE-20809](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20809) Tue, 29 Jan 2013 18:10:13 GMT
> Reported by Matthew Kaufman
> Assigned to 

At the face-to-face meeting in 2012-11, there was a lengthy discussion on how an application might programmatically reject a subset of the RTP streams (i.e. MediaStreamTracks) that arrive on a given RTP session.  There seemed to be consensus that a solution to this problem would be necessary.  There is no specification of this API, nor are there any normative references to documents that describe this API in the current draft.

**Comment by dontcallmedom** [comment]
The spec now has "Rejection of incoming tracks can be done by the application after receiving the ontrack event, by stopping the track."

I think this can be closed @stefhak @alvestrand

**Comment by stefhak** [comment]
Agree, closing.
