### ISSUE TITLE
Section 15 (Security Considerations) is empty

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#159]
> Originally reported on W3C Bugzilla [ISSUE-20806](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20806) Tue, 29 Jan 2013 18:06:49 GMT
> Reported by Matthew Kaufman
> Assigned to 

The Security Considerations section of the WEBRTC specification is empty, despite a large number of identified security considerations regarding opening network connections, sending traffic from a browser frame to other places, and allowing camera and microphone to be attached to those network sessions.

**Comment by dontcallmedom** [comment]
We have a security consideration section now; there are plans for improving it further, but I think that issue can probably be closed now.

**Comment by stefhak** [comment]
Closing as there is a security section in the document now.
