### ISSUE TITLE
Partial removal of a track?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1609]
It is possible for a sender to have multiple streams, resulting in the other endpoint having a receiver with multiple streams.

Let's say we signal that track1 belongs to stream1 and stream2. Is it OK to then signal that the track belongs to another set of streams - let's say stream1, but no longer stream2? In this case, it should be removed from one stream and the receiver's set of associated streams should be updated, but the track should not be muted.

The spec is currently written to "process the removal of a remote track" which set the receiver's associated streams and mutes the track (if not already muted).

If this is to be supported, I believe we need to either:
- If this counts as the removal of a track, the description should be updated to say only mute if the receiver's set of associated streams is empty.
- If this does not count as the removal of a track, we need to add a step to update the set of associated streams of receivers that are not removed.

I'm no SDP guru, is my understanding of this correct?

**Comment by taylor-b** [comment]
I suppose this should be supported. It's not possible to change a sender's set of streams via the API, but it's possible to change a receiver's via SDP munging.

The "removal of a track" steps are only invoked when the direction changes to "sendonly" or "inactive" (meaning, when the track can no longer be received unless renegotiation occurs). So if we want this to supported, we'd need to add an additional step for checking if the set of streams changed and updating them accordingly. I assume this is what you mean by:

> add a step to update the set of associated streams of receivers that are not removed.

**Comment by henbos** [comment]
Yes. Should we have an event on the receiver that fires saying streams updated?

**Comment by taylor-b** [comment]
I don't see why not.
