### ISSUE TITLE
Stats & isolated streams

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#1613]
While doing a [first pass at a security review](https://github.com/w3c/webrtc-stats/issues/99#issuecomment-331979041) for WebRTC stats, I noticed the text on isolated media streams in WebRTC 1.0 leaves open the access to stats for them:

> In particular, the statistics that RTCPeerConnection records are not reduced in capability. New statistics that might compromise isolation MUST be avoided, or explicitly suppressed for isolated streams.

It sounds like stats might leak a lot about isolated streams to the JavaScript layer, so @aboba suggested I raise an issue so that we look more closely into this.

**Comment by aboba** [comment]
@vr00m What do you think?

**Comment by vr000m** [comment]
Do we need a minimum set of stats that does not compromise the isolated stream and still helps with debugging issues? or we leave that to the implementors to pick?

**Comment by dontcallmedom** [comment]
I don't see why we should not leave it to implementors - this needs to be interoperable as far as I can tell.

**Comment by alvestrand** [comment]
@dontcallmedom one too many "not" in that sentence?

**Comment by dontcallmedom** [comment]
yes, I meant "I don't see why we should leave it to implementors" :)

**Comment by alvestrand** [comment]
So far, I know that volume leaks information. The fact that there is a call (and associated info such as IP addresses) doesn't seem to warrant different treatment for isolated vs non-isolated streams.
So what else in track stats should be treated differently, if anything?

**Comment by dontcallmedom** [comment]
This needs to address also CSRC and SSRC and isolated streams

**Comment by alvestrand** [comment]
Dan will take a look at his notes to try to reproduce consensus. @vr000m do you remember?

**Comment by stefhak** [comment]
From TPAC: https://www.w3.org/2017/11/06-webrtc-minutes.html#item18

**Comment by burnburn** [comment]
I confirmed in my notes that Harald was going to do a PR because there is not a blanket answer here across all types of stats.

**Comment by vr000m** [comment]
AFAICR, to do a PR to suggest not reporting stats that leak. IIRC: it was CSRC and volume.
