### ISSUE TITLE
canInsertDTMF transitions not specified

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1619]
There is no text describing when `canInsertDTMF` transitions to `true`.

**Comment by fluffy** [comment]
So I think the value of canInsertDTMF is based on if the remote SDP negotiated it or not. Does that sounds correct to you ?

**Comment by aboba** [comment]
@fluffy  This issue is about specifying the conditions under which canInsertDTMF is true.  For example, a combination of the following: 

1. It's an audio sender. 
2. "telephone-event" is negotiated.
3.  The sender can send: 
      a. current direction is not send/recv or recv-only?
      b. sender.track is non-null?

**Comment by alvestrand** [comment]
After chewing through this in real code for a while, I think that the conditions for canInsertDTMF = true (in addition to "track" being present and being an audio track) are:
1) Negotiation done
2) Direction is sendrecv or sendonly
3) DTMF-capable codec ("telephone-event") negotiated
4) PeerConnection in "connected" state
SInce the last point is a state transition that we have an event for, it may make sense to hang the value change off the text that triggers the event.

**Comment by fluffy** [comment]
So if by negation done, you mean we have an offer and a PR-answer or answer, that sounds about right to me. The one case I am thinking of is you have called 1-800-go-fedex and you might only have a pr-answer but you still want to be able to send DTMF for the the IVR.

**Comment by alvestrand** [comment]
Offer + pr-answer would work fine, I think. I want to make sure I can have a conformant implementation that is only able to send DTMF after the connection has been established (which also requires completing the DTLS handshake).

**Comment by fluffy** [comment]
Yep, that sounds right to me.

**Comment by jan-ivar** [comment]
This is a good idea. Users shouldn't have to [poll on `canInsertDTMF`](https://github.com/webrtc/adapter/pull/789#discussion_r173511934) to figure out when to send.

**Comment by fippo** [comment]
reminder: [test as you commit](https://github.com/w3c/web-platform-tests/pull/9941#pullrequestreview-102874364)

The test is pretty simple: do a signaling handshake, listen to connectionstate, check for canInsertDTMF. The helper from that PR should work even.

**Comment by aboba** [comment]
@jan-ivar @fippo PR submitted. Can you take a look?

**Comment by aboba** [comment]
This issue was addressed by PR https://github.com/w3c/webrtc-pc/pull/1980
