### ISSUE TITLE
change the definition of "enqueue a task" as EKR slides May 20

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#162]
> Originally reported on W3C Bugzilla [ISSUE-25833](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25833) Tue, 20 May 2014 20:14:57 GMT
> Reported by Cullen Jennings
> Assigned to

**Comment by stefhak** [comment]
I think this is addressed with the merge of #314, so I'm closing.
