### ISSUE TITLE
"set an RTCSessionDescription" steps need to be broken up into multiple smaller lists of steps

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1624]
If writing code, it's a good rule of thumb to break code out into a new function once you encounter ~3 levels of nesting. Well, in the "set an RTCSessionDescription" steps, we're up to 6 levels of nesting. So I think it's time to do something.

I'd suggest breaking up the steps into different categories of attributes/objects that need to be updated. For example:

* Signaling state
* Current/pending descriptions
* SCTP transport and data channels
* Transceivers
* Track events
* DTLS/ICE transports

Each of these categories would have its own lists of steps. The main list of steps would then, for the most part, just point to these other lists of steps. Thoughts?

**Comment by henbos** [comment]
Nag ping ;)

**Comment by jan-ivar** [comment]
At this point, I don't think we should do this. The algorithm is quite timing sensitive wrt firing events synchronously in a safe manner, so we probably don't want a major rewrite at this point.
