### ISSUE TITLE
Please do not use datatracker.ietf.org

### ISSUE THREAD

**Issue by annevk** [w3c/webrtc-pc#1629]
Instead of https://datatracker.ietf.org/doc/draft-ietf-rtcweb-overview/ it's easy enough to link to https://tools.ietf.org/html/draft-ietf-rtcweb-overview which is a better experience for the reader as 1) it's more consistent with other references and 2) it's really rather unclear how to get from datatracker to the latest draft other than through URL manipulation.

**Comment by dontcallmedom** [comment]
I've updated specref to use `tools.ietf.org` URLs

**Comment by annevk** [comment]
Thanks @dontcallmedom, much appreciated.
