### ISSUE TITLE
Example ICE state transition appears incorrect

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1630]
One of the transitions is "(any state, ICE restart occurs): new". However, this isn't what I'd expect, since during an ICE restart the existing candidate pair continues being used. So I'd actually expect that the transitions would be:

* connected -> no change
* completed -> connected
* disconnected -> checking?
* failed -> new -> checking

Does that sound right? I guess we may need to revisit the ICE state table such that its definitions take ICE restarts into account, if the behavior is not clear enough as-is.

**Comment by aboba** [comment]
Perhaps the (erroneous) assumption was that an ICE restart would imply construction of a new IceTransport object in the new state.  But this isn't the case, either for WebRTC 1.0 or ORTC.
