### ISSUE TITLE
Why is setDirection a method?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1643]
Sure, [transceiver.setDirection(direction)](http://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver) can throw, but so can attributes!

`transceiver.direction = direction` seems superior. I checked with our DOM folks, and they agree.

The algorithm seems like a shoo-in, setting the (today readonly) `direction` attribute, so no change there.

Also, since setting `direction` merely sets the negotiationneeded flag, there's zero chance of us ever wanting this method to return a promise or anything like that.

We're going over final review of our implementation slated for Firefox 59, and thought this made sense.

@taylor-b @adam-be WDYT?

**Comment by alvestrand** [comment]
I'm not too well versed in the traditions of attribute-setting, but is it kosher to invoke an algorithm as complex as http://w3c.github.io/webrtc-pc/#dfn-update-the-negotiation-needed-flag procedure when setting an attribute?

**Comment by taylor-b** [comment]
I don't see any problem with this suggestion, personally.

**Comment by jan-ivar** [comment]
@alvestrand I don't think there's a complexity limit on attributes compared to methods when it comes to internal algorithms. For all it does, it's updating a user-setting and setting a dirty-flag.

See [binaryType](http://w3c.github.io/webrtc-pc/#dom-rtcdatachannel-binarytype) for an example of an attribute that throws. We'd instead write *"On setting, the user agent MUST run the following steps"*.

**Comment by alvestrand** [comment]
OK, I'm for changing it to an attribute.

**Comment by fippo** [comment]
👍 -- we don't have getDirection either (and I wrote code that tried to use that...)

**Comment by adam-be** [comment]
Since we have `currentDirection` that takes care of reflecting what's negotiated this seems pretty safe.
