### ISSUE TITLE
Adding more values to RTCIceTransportPolicy Enum

### ISSUE THREAD

**Issue by jianjunz** [w3c/webrtc-pc#1644]
[1] defines 4 specific modes for candidate collection. However, RTCIceTransportPolicy Enum only has 2 values. Currently, user agents choose which mode is going to be applied in certain circumstances. Should we add more values to RTCIceTransportPolicy Enum so applications have the chance to change UA's default behavior? UA may request permission from the end user before changes are made.

Here is an example of different candidate collection behaviors between Chrome and Firefox:
Run data channel sample [2] in a machine equipped with two network adapters. Chrome collects candidates on all network adapters. Firefox only collects candidates on default route and associated local addresses.

[1] https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-04
[2] https://webrtc.github.io/samples/src/content/datachannel/basic/

**Comment by alvestrand** [comment]
The two modes specified by RTCIceTransportPolicy are the modes that can be chosen by the Javascript application. They limit what candidates are shown to signalling - based on the premise that the local Javascript can be trusted, but the signalling intermediaries and the remote party can't be.
The four modes described in draft-ietf-rtcweb-ip-handling are the modes that can be chosen by the browser, based on local configuration. They limit what candidates are shown to the Javascript - based on the premise that the Javascript can't be trusted.
It would be a security problem if the application could pass a parameter to loosen the browser's IP candidate policy, so the only values that can be reasonably passed are the ones that make the policy tighter.

Which particular values did you want to add?

**Comment by jianjunz** [comment]
How about making RTCIceTransportPolicy supports all the four modes described in draft-ietf-rtcweb-ip-handling? I agree with you that it will be a security and privacy problem if application could loosen browser's default IP candidate policy without user consent. So I think browser should request permission from the user before loosening candidate policy for a specific website.

If browser does not provide such an API to change its default behavior, data channel applications may not have the chance to collect all candidates even end users allow them to do so.

**Comment by alvestrand** [comment]
The browser has to have UI to change its default behavior, I think. But letting JS invoke that UI runs into issues - including "will the user understand what he's being asked to do?"
The user prompt will likely not be "This web page wants to collect more network information about you. If you're using a VPN to hide your location, give away your real location to this Web page".

**Comment by jianjunz** [comment]
Yes, it is hard for user to understand the consequence of collecting all candidates. But tying this consent to getUserMedia consent as suggested in draft-ietf-rtcweb-ip-handling looks unfair to data channel applications.

For web applications, it is recommended to try default policy before making changes.

**Comment by taylor-b** [comment]
So, to clarify: your request is more motivated by data-only applications getting *more* access to candidates, rather than privacy-motivated applications *restricting* access to candidates?

If so, another avenue to pursue may be adding a standalone API to request network interface permissions, which would fit into [the permissions spec](https://w3c.github.io/permissions/).

**Comment by jianjunz** [comment]
Thanks for pointing out the permissions spec. It could be a solution for this issue.

Do you think we still need to add "Mode 2:  Default route + associated local addresses" and "Mode 3:  Default route only" to RTCIceTransportPolicy so application can limit candidate collection when permission is granted?

**Comment by aboba** [comment]
@jianjunz Can you produce a PR?

**Comment by taylor-b** [comment]
> Do you think we still need to add "Mode 2: Default route + associated local addresses" and "Mode 3: Default route only" to RTCIceTransportPolicy so application can limit candidate collection when permission is granted?

I think that could be accomplished at the application level, by just filtering out candidates based on type ("host" or "srflx") and the "raddr". Right? The more difficult thing would be Mode 1 vs. Mode 2, because the application doesn't have a good way of knowing which is the "default" route. But I imagine there are still ways (the HTTP server that served the page should know what address the request was received from).

**Comment by jianjunz** [comment]
How about adding a new value "default-route-and-relay" which corresponding to Mode 3? "default-route-and-relay" and "relay" can be choose by web application without additional permission request. "all" only available when user granted "collecting all candidates" permission.

Reasons for using Mode 3 and why it does not need permission request:
- Compared with Mode 2, Mode 3 does not provide default route's local address which is unavailable in traditional web applications either.
- The public IP of default route already known by web server because of HTTP traffic. So I think no additional permission are required for "default-route-and-relay".
- Knowing which is the "default" route is a little bit hard for web applications. Many approaches need server side support.
- Exposing the IP of default route may significantly reduce proxy server/relay server's cost, while it still protects VPN user's privacy.

@aboba, I'll submit a PR to this repo if there is no objections to the suggestion above. But I'm afraid I cannot submit PRs to the permission spec at this time since I'm not a member of WebAppSec WG. Maybe I can submit an issue first. 

Here is a related discussion in WebKit community: https://bugs.webkit.org/show_bug.cgi?id=174500

**Comment by nils-ohlmeier** [comment]
> Here is an example of different candidate collection behaviors between Chrome and Firefox:
> Run data channel sample [2] in a machine equipped with two network adapters. Chrome collects candidates on all network adapters. Firefox only collects candidates on default route and associated local addresses.

Chrome and Firefox actually implement the same default policy, which is to collect only default route candidates. Most likely you have given gUM permissions to any of the other webrtc samples which require camera access and therefore Chrome permanently remembers that you trust the domain. In Firefox you have to explicitly tick the option inside the gUM prompt. Very few users do that in Firefox. So the behavior is the same between both browsers.

**Comment by jianjunz** [comment]
Thanks for your explanation. I have run other webrtc samples which require gUM permissions. That should be the reason why Chrome collected all candidates.

**Comment by aboba** [comment]
Notes from TPAC discussion:
https://www.w3.org/2017/11/06-webrtc-minutes.html

**Comment by annmarielarue** [comment]
I would like to announce. I have never said i wanted ALL of anything. In fact ive been trying to give.  Im blocked and lied to.

**Comment by jianjunz** [comment]
As we discussed during TPAC, we will not add new policies to `RTCIceTransportPolicy` at this time. I'm closing this issue.

Quoted from TPAC notes:

> Adding more values to RTCIceTransportPolicy Enum #1644
> 
> PeterT: 2 different issue - one about network permission separate from getUserMedia, the other about giving more control for the app to constraint their routing
> 
> Varun: use cases including routing data through or not VPN
> ... another thing is to enable a relay-first approach to help with establishing a call quickly
> 
> Dom: so if we don't do this, what should we recommend to the OP?
> 
> PeterT: so for the first bit, we need to look into the permissions thing
> ... for the second, give more justification / use case
> 
> Cullen: maybe a way to address the second thing is a way to expose from which route the origin was loaded
> 
> PeterT: it may make sense to close this issue and open one on data-channel only permission, and then maybe one discussion exposing more routing info for selecting ice candidates
