### ISSUE TITLE
JSEP references are out dated

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/webrtc-pc#1651]
Today webrtc-pc references JSEP version 20, but [JSEP is now at version 24](https://datatracker.ietf.org/doc/draft-ietf-rtcweb-jsep/).

The version of JSEP and the mapping of sections should be updated, see [webrtc-pc/jsep-mapping/README.md](https://github.com/w3c/webrtc-pc/blob/master/jsep-mapping/README.md)

ping @dontcallmedom

**Comment by vivienlacourba** [comment]
Likely related the generated respec html code has a few broken anchors to JSEP version 4.2.1 and 4.2.2 :

`<cite><a class="bibref" href="#bib-JSEP">JSEP</a></cite>] (<a href="https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-4.2.">section 4.2.1</a>)</span>.</p>`

and

`[<cite><a class="bibref" href="#bib-JSEP">JSEP</a></cite>] (<a href="https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-4.2.">section 4.2.2</a>)</span>, the user agent <em class="rfc2119" title="MUST">MUST</em> run the above steps`

**Comment by fluffy** [comment]
I think I added all the anchors needed in JSEP - if any more are needed, let me know.

**Comment by aboba** [comment]
Fixed.
