### ISSUE TITLE
relay-first as an option for RTCIceTransportPolicy

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-pc#1658]
Side discussion when discussing #1644 at TPAC 2017.

In the spec, we have `all`, and `relay`, some use-cases might want relay-first. Today, we can do this by starting a peerconnection with relay and start another peerconnection with all. Then attaching the tracks to the sender on the first peerconnection and then later moving this to the other peerconnection whenever it deems reasonable.

**Comment by fippo** [comment]
Last time I tried (early 2015-ish) this was ok in Chrome with a single peerconnection. You add the relay candidates first, wait for a connection, then add the other candidates.

Another option which might be viable now is setting icetransportpolicy to relay, then changing that using setConfiguration and doing an ice restart.

👍 on making the intent more clear though.

**Comment by alvestrand** [comment]
#1649 attempted to do this by adding a new policy, but TPAC consensus was not to do this.
Closing as "no change needed".
