### ISSUE TITLE
Update SOTD text regarding multiple implementations

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#1661]
From TPAC 2017, we need to review the text we have regarding multiple implementations to match what we actually intend to provide.  Possible high-level aspects:
- we know that much of the underlying stacks are the same across browsers, so we will not guarantee independence there
- most of the JS API implementation is independently written across browsers, so the WPT may show this piece
- in our charter we strongly suggest we will provide evidence of actual success in media and data transmission between different browsers, so we should develop some wording around this.

**Comment by alvestrand** [comment]
The current SOTD says:

To go into Proposed Recommendation status, the group expects to demonstrate implementation of each feature in at least two deployed browsers, and at least one implementation of each optional feature. Mandatory feature with only one implementation may be marked as optional in a revised Candidate Recommendation where applicable.

**Comment by dontcallmedom** [comment]
has this been over taken by events?

**Comment by aboba** [comment]
@dontcallmedom I think so. Can we close it?
