### ISSUE TITLE
Point to the Hash Function Textual Names registry

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#1663]
https://w3c.github.io/webrtc-pc/#dom-rtcdtlsfingerprint-algorithm says "One of the the hash function algorithms defined in the 'Hash function Textual Names' registry, initially specified in [RFC4572] Section 8."

That registry now exists:
https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xml

It would be helpful to refer to this directly, since that's where additional values will be added.

I noticed this when looking at a failing test:
https://github.com/w3c/web-platform-tests/blob/8c5d6017f9d992c5f97737c41e43e18f1fb682af/webrtc/RTCCertificate.html#L175

@soareschen FYI

**Comment by foolip** [comment]
@henbos points out in https://github.com/w3c/web-platform-tests/pull/8103#discussion_r150519203 that https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-generatecertificate says ```{ name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" }``` and ```{ name: "ECDSA", namedCurve: "P-256" }```.

This isn't the same definition, but it should be clear that only lowercase values are used in RTCDtlsFingerprint, perhaps with a note.

**Comment by adam-be** [comment]
@foolip, can you clarify what you mean with your second comment please.

**Comment by foolip** [comment]
@adam-be, because there are other places related to WebRTC where uppercase names of algorithms are accepted, and that's used in examples, it would be good to spell out that only lowercase values are possible in https://w3c.github.io/webrtc-pc/#dom-rtcdtlsfingerprint-algorithm

**Comment by adam-be** [comment]
@foolip, thanks for the clarification. I think it might be a bit overkill since it's only an "output value". Meaning it's fine to just pass it as input to some place that accepts both upper and lower case. But I don't think it hurts to ad it either. If you still think it's needed I'll add it. :)

**Comment by foolip** [comment]
That's an editorial decision, I'll leave it to you.
