### ISSUE TITLE
RTCRtpSynchronizationSource.audioLevel in idl should be nullable

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-pc#1665]
RTCRtpSynchronizationSource.audioLevel is missing its nullable marker.

**Comment by jan-ivar** [comment]
Not sure it should, as I think the spec guarantees a non-null value. I noticed this while writing https://github.com/w3c/webrtc-pc/pull/1668 which I think makes this clearer.

**Comment by na-g** [comment]
@jan-ivar Having looked at #1668, I agree.

**Comment by alvestrand** [comment]
#1668 actually makes it nullable in IDL (by inheriting from ContributingSource).

**Comment by jan-ivar** [comment]
@alvestrand Yes with prose to guarantee it is never null, a compromise.
