### ISSUE TITLE
offerToReceive* should ignore stopped transceivers, not unstopped ones.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1675]
I think https://github.com/w3c/webrtc-pc/pull/1672 inadvertently [flipped](https://github.com/w3c/webrtc-pc/pull/1672#discussion_r154195277) the logic test for `stopped` transceivers when deciding to create one from offerToReceive* option.

**Comment by aboba** [comment]
Good catch.
