### ISSUE TITLE
Should updateIce() update the returned value of getConfiguration()?

### ISSUE THREAD

**Issue by ibc** [w3c/webrtc-pc#168]
It is not clear in the latest spec. If I call `updateIce(newPcConfig)` on a `RTCPeerConnection`, should `getConfiguration()` return such a `newPcConfig`?

**Comment by juberti** [comment]
updateIce is now setConfiguration, so... yes.

**Comment by dontcallmedom** [comment]
I think this can be closed @stefhak @alvestrand

**Comment by stefhak** [comment]
I'd like to see the PR land first on this one. When reading the current version it's unclear to me if the configuration is set or not.

**Comment by alvestrand** [comment]
#211 is the current PR.

**Comment by alvestrand** [comment]
Closing now that #211 is merged.
