### ISSUE TITLE
RTCDataChannel.bufferedAmount description confusing

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1680]
I don't understand the following description of `RTCDataChannel.bufferedAmount`:

> [...] If the channel is closed, this attribute's value will only increase with each call to the send() method (the attribute does not reset to zero once the channel closes).

Let me go through that:

> If the channel is closed [...]

So, the channel is closed already.

> [...] this attribute's value will only increase with each call to the send() method [...]

That doesn't make any sense to me as the channel is already closed. Sending in a non-open state will result in an exception being thrown.

> (the attribute does not reset to zero once the channel closes)

Fine.

---

If I understand correctly, this is what it should say:

> [...] This attribute's value will only increase with each call to the send() method as long as the channel is in the `open` state. However, the attribute does not reset to zero once the channel closes.

**Comment by lgrahl** [comment]
Note for myself: This also affects the ORTC spec.

**Comment by Ultrawoman** [comment]
My phone is not working even though I paid. I have found out that the person renting a room down the hall from me has been in my room. He has removed the disc from my laptop. Also, I download PDF'sPDF' s. I do not have a printer and if anything was printed off I did not receive it.

**Comment by Ultrawoman** [comment]
I have also bought 2 different phones from one company that are supposed to be Samsung Galaxy Sol and they are not. They register as Samsung J3. I have found that they have recording devices in them. I have also purchased 3 devices at pawn shops in the past and found that they had also have recording devices in them.

**Comment by taylor-b** [comment]
That sounds reasonable to me
