### ISSUE TITLE
Why is RTCRtpContributingSource.byte required-but-nullable?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#1688]
It seems like we want to represent the "not available" state; that part makes sense.  Why is that represented as null as opposed to just not having the property in the dictionary?

**Comment by jan-ivar** [comment]
We're using `required` as discussed in https://github.com/heycam/webidl/issues/382. I guess we thought there was some value in guaranteeing the presence of the field, as a form of feature detection. But this being a new API with just a few dictionary members, perhaps that's not necessary?

**Comment by bzbarsky** [comment]
Right, what would be being feature detected?

**Comment by jan-ivar** [comment]
Whether the browser supports getContributingSources() but not the audioLevel member, versus it supports it and the RFC 6465 header extension is absent on the incoming packets.

**Comment by bzbarsky** [comment]
Ah, I see.   It's really not clear from the `getContributingSources()` spec that if you don't support audioLevel _then_ you need to modify the dictionary accordingly.  I would expect that any implementor trying to implement `getContributingSources()` in a browser with no audioLevel support and following the current spec would just set the member to null...

**Comment by jan-ivar** [comment]
Since `null` has specific meaning in the spec, I hope implementors don't include it with any other meaning than that of the spec (if they include it). Absence is what I'd expect for an unimplemented feature, because that works for unimplemented features yet to be spec'ed as well.

**Comment by bzbarsky** [comment]
I think the problem is that he "feature" in the implementor's mind is `getContributingSources()` and that feature clearly requires returning a dictionary with the member set; it has no provisions for not including the member.  Then they're forced to think about what to set the member to...

**Comment by alvestrand** [comment]
getContributingSources() will have useful information (what the contributing sources are) whenever CSRCs are present. CSRCs can be present without the RFC 6465 header extension being present, but not vice versa.

Same logic as in the other bug.

**Comment by bzbarsky** [comment]
Let's just keep the discussion in https://github.com/w3c/webrtc-pc/issues/1689 because it's fundamentally the same question.

**Comment by alvestrand** [comment]
Closing this as a duplicate, then. Continuing in #1689.
