### ISSUE TITLE
RTCRtpContributingSource.timestamp needs a clearer definition

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#1690]
It says:

> The timestamp is defined in [HIGHRES-TIME] and corresponds to a local clock.

What does "local clock" mean here?  The definition in HIGHRES-TIME allows DomHighResTimestamp to mean one of three things:

1) A time measured from the time origin of some global (in which case you need to define which one).
2) A time measured on the global monotonic clock.
3) A time measured from some other DOMHighResTimeStamp.

I assume "local clock" is meant to preclude option 2, but it's not clear whether option 1 or option 3 is meant, and in either case more information needs to be provided as to which timebase is used.

**Comment by na-g** [comment]
@bzbarsky see #1497

**Comment by bzbarsky** [comment]
Yes, measuring from the time origin of some clearly specified global would fix #1497 by allowing direct comparison to that global's performance.now()...

**Comment by jan-ivar** [comment]
Would making it match [timestamp](http://w3c.github.io/webrtc-pc/#dom-rtcstats-timestamp) in RTCStats work?

**Comment by bzbarsky** [comment]
Yes, insofar as that one is well-defined.  Unfortunately, it's not terrible very well-defined itself.  See the pains that https://www.w3.org/TR/hr-time-2/#time-origin-timestamp goes through to define something similar for `performance.timeOrigin`; you need to do something like that if you want to define a monotonic thing which kinda (but not really, so you better not be comparing it to `Date.now()` even though it'll be really tempting!) quacks like wall-clock Unix time.

**Comment by alvestrand** [comment]
Since we're in the browser world here, would it be better to define these timestamps in reference to the context's global monotonic clock?
I'd prefer to have something that gives "something like the wall clock" rather than zero-based-to-browsing-context, because that's convenient in so many contexts (logs most of all). I'm not sure how to formulate it properly, though.

**Comment by alvestrand** [comment]
We should have the same clock in GetStats' timestamps and ContributingSource.timestamp.
So whatever we do should be the same thing for both.

**Comment by jan-ivar** [comment]
> define these timestamps in reference to the context's global monotonic clock
> ... prefer to have something that gives "something like the wall clock"

@alvestrand It sounds like you want a timestamp that's comparable to

```js
performance.timing.navigationStart + performance.now()
```
Is that correct?

> you better not be comparing it to Date.now() even though it'll be really tempting!

As @bzbarsky points out, [a bit of a footgun](https://jsfiddle.net/jib1/zqpo4kcq/), but an improvement over *getStats*'s timestamp today, and more backwards compatible than say, changing its (zero-)origin from 1970 to page load.

I like it, if we can move both *getStats* and *getContributingSources/getSynchronizationSources* to it.

**Comment by bzbarsky** [comment]
> `performance.timing.navigationStart + performance.now()`

Do you want that, or `performance.timeOrigin + performance.now()`?  (Note that `performance.timeOrigin` may not be "Unix time"; I'm seeing it differ from `performance.timing.navigationStart` by quite a bit in some cases... but note that navigationStart does NOT come from a monotonic clock.)

**Comment by bzbarsky** [comment]
(And in particular, depending on how OS sleep affects the passage of time on the monotonic clock, the two values can drift pretty arbitrarily far apart.  On some of my browser instances, they're days apart.)

**Comment by jan-ivar** [comment]
@bzbarsky Thanks, I wasn't aware of the difference. I'm prepping slides, so I'll put both alternatives up there.

**Comment by jan-ivar** [comment]
@bzbarsky FWIW, `timeOrigin` appears [significantly off](https://jsfiddle.net/jib1/t1vmjvvw/) in Firefox, not in Chrome. A bug? I've had both instances on for less than a day.

**Comment by bzbarsky** [comment]
The timeOrigin implementation is Firefox is really simple: take the monotonic clock timestamp at navigation start, subtract a process-global initialization timestamp, add the wall-clock time of said initialization.

The navigationStart implementation is just a snapshot of wall-clock time at navigation start.

So if there is a difference, it's due to skew between the monotonic and wall clocks over the period between process init and navigation start.  I suspect based on the number I'm seeing that in Firefox the monotonic clock doesn't run while the computer is asleep, which can easily introduce significant skew given that content process lifetimes in Firefox are a good bit longer than in Chrome.

**Comment by alvestrand** [comment]
January VI decision: Use performance.timeOrigin + performance.now(). this should also be applied in webrtc-stats.
