### ISSUE TITLE
Data channel closing procedure

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1699]
The [data channel closing procedure](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#data-transport-closing-procedure) lacks information how implementations should gracefully close data channels. It only mentions:

> An RTCDataChannel object's underlying data transport may be torn down in a non-abrupt manner by running the closing procedure. When that happens the user agent must, unless the procedure was initiated by the close method, queue a task that sets the object's [[ReadyState]] slot to closing. This will eventually render the data transport closed.

As far as I can see, that is the whole closing procedure description the `close` method references, too.

We need to add a few detailed steps and should probably reference [draft-ietf-rtcweb-data-cannel, section 6.7](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.7) which describes how a data channel can be closed gracefully.

Related bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1413198

---

I'm also confused by the following statement of the closing procedure:

> [...] This will eventually render the data transport closed.

I don't believe that's actually true. Why would that be the case? Only the data channel will be closed, not the transport.

---

Mention: @taylor-b

**Comment by taylor-b** [comment]
I was using a loose interpretation of some of these phrases. I assumed "underlying data transport" didn't refer to the SCTP transport, but the SCTP stream pair used to implement the data channel.

Agreed that this could be clarified a lot more, though. And it doesn't currently describe how a non-graceful closure works.

**Comment by lgrahl** [comment]
> I assumed "underlying data transport" didn't refer to the SCTP transport, but the SCTP stream pair used to implement the data channel.

I see. A suggestion:

> This will eventually reset the associated incoming and outgoing SCTP stream.

---

Regarding the closing procedure for graceful closing: I can provide a PR but it may take some time. If anyone else wants to go for it, feel free and also feel free to ping me for reviewing.

**Comment by aboba** [comment]
The text relating to [`RTCSctpTransportState`](https://www.w3.org/TR/webrtc/#dom-rtcsctptransportstate) refers to the state of the SCTP transport, but it would be easy for a reader to assume that this is the `underlying data transport`, when actually that is the SCTP stream pair.

**Comment by lgrahl** [comment]
While #1722 is a step forward, it still remains confusing. The term *close* just doesn't work for an SCTP stream (pair) as I mentioned in #1722. In SCTP, streams can be *reset* but there's no such thing as closing a stream.

**Comment by taylor-b** [comment]
The "underlying data transport" is more than just an SCTP stream pair, though; it's a stream pair _plus_ the  extra semantics defined by draft-ietf-rtcweb-data-channel.

Is there any reason why we can't just refer to SCTP terminology directly though? Why do we need this hand-wavey terminology in the first place? Is it in case we end up using the RTCDataChannel interface with some other underlying protocol (which seems unlikely)? Can we just cross that bridge when we come to it?

**Comment by lgrahl** [comment]
> The "underlying data transport" is more than just an SCTP stream pair, though; it's a stream pair plus the extra semantics defined by draft-ietf-rtcweb-data-channel.

I guess it would be easier to just refer to the closing procedure:

> An RTCDataChannel object's underlying data transport may be torn down in a non-abrupt manner by running the closing procedure. When that happens the user agent must, unless the procedure was initiated by the close method, queue a task that sets the object's [[ReadyState]] slot to closing and **follow the closing procedure defined for the data transport (for SCTP data channels, see [rtcweb-data-channel section 6.7](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.7)). An implementation must ensure that all pending messages are being delivered (or abandoned in case of a partially reliable channel) before the channel goes into the closing state.**

That would resolve this issue for me. Even though I'm not entirely happy about the *or abandoned in case of a partially reliable channel* section because that of course still means that the implementation has to try sending pending messages.

> Is there any reason why we can't just refer to SCTP terminology directly though? Why do we need this hand-wavey terminology in the first place? Is it in case we end up using the RTCDataChannel interface with some other underlying protocol (which seems unlikely)? Can we just cross that bridge when we come to it?

Well, this abstraction has been in the spec for a long time now. But yeah, there are a lot of sections that would need to be revised (such as `maxMessageSize`) in case another transport comes in.
