### ISSUE TITLE
Should rollback fire addtrack/removetrack events? 

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1706]
SRD(offer) can cause the following events to fire: `track`, `mute`, `addtrack`, and `removetrack`, as well as cause tracks to be added/removed from the remotely managed stream(s).

Should a rollback undo any/all of that? How do we undo the `track` event? E.g should we undo the `mute` event by firing the `unmute` event?

**Comment by docfaraday** [comment]
I guess it depends on whether the intent is to allow sessions to continue functioning normally after a sRD(rollback), without requiring a subsequent negotiation to set the record straight. I _think_ this is the intent, right?

**Comment by stefhak** [comment]
@docfaraday I have the same understanding of the intent (https://github.com/w3c/webrtc-pc/issues/1706#issuecomment-353430767) as you.

**Comment by aboba** [comment]
Consensus from the April VI is for Jan-Ivar to produce a PR along the lines described in the slides.

**Comment by stefhak** [comment]
@jan-ivar do you think we can close this Issue now that #1867 has been merged?

**Comment by jan-ivar** [comment]
No, https://github.com/w3c/webrtc-pc/pull/1867 fixed missing events from remote rejection (https://github.com/w3c/webrtc-pc/issues/1778), not rollback.
