### ISSUE TITLE
Example 14 never sends any media

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1708]
https://w3c.github.io/webrtc-pc/#peer-to-peer-example-with-media-before-signaling

There is no `addTrack` or `replaceTrack`.

**Comment by alvestrand** [comment]
I believe this is by design - the example's focus is on receiving media, not sending it.

**Comment by stefhak** [comment]
The comment in the code - `// get a local stream, show it in a self-view and add it to be sent` makes me think it's not by design. Anyway, we should probably sort out #1709 before going into these details.

**Comment by alvestrand** [comment]
Suggested fix:
- Change the title to "with incoming media before signaling"
- Change the intro to add "This code shows the receiving side"
- Remove the "selfView" code

I think that focuses the example better on what it's supposed to be about.

**Comment by dontcallmedom** [comment]
#1926 proposes removing the example, which would solve the issue
