### ISSUE TITLE
Should we require a reference from RTPSender to RTCPeerConnection?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1712]
One of the design objectives of the "non-PC" model of WebRTC was that we should be able to work without a PeerConnection if we wanted to. So I'm leery of things that require references to the PC.

It seems that we've added such a requirement to RTPSender by this statement in the description of replaceTrack:

"4. If connection's [[IsClosed]] slot is true, return a promise rejected with a newly created InvalidStateError and abort these steps."

For cleanliness, I'd prefer to keep all the pointers going the other way, which can be achieved by either depending on the "stopped" slot of the transceiver (already checked in step 5) or defining that the procedure "Stop sending media with sender" (referenced from the "close" method of PC) leaves a state marker in a sender's internal slot that can be tested instead.

The last approach has the advantage that senders don't have to know about transceivers either, which is a Good Thing (if we're not using SDP, transceivers are a liability not a feature).

**Comment by fippo** [comment]
Are you looking for [RtpSenderIsStopped](http://draft.ortc.org/#dom-rtcrtpsender-stop)?

**Comment by aboba** [comment]
@alvestrand Step 4 could be removed since step 5 checks whether the `transceiver` has been stopped.  Removing transceiver dependencies as well would require adding `RtpSenderIsStopped` and `RtpReceiverIsStopped` slots as in ORTC.

**Comment by alvestrand** [comment]
@fippo yes, that's a solution
@aboba the difference between step 8 (replace track only) and step 10 (replace track and start sending from it) seems to be rather small; we could treat "not associated with SDP" as a special case of "negotiation not needed".
For completely indepenedent operation, I suspect that we need RTPSender to have a complete representation of the allowable operation parameter envelope, and reject ReplaceTrack if the new track is not within the currently set operation parameter envelope. The initial envelope would then be "sender's maximal abilities", and the post-negotiation envelope would be "SDP-negotiated envelope". Bigger task to specify; ORTC does this as part of the send() function.
Getting rid of one level of reference is good for now.
