### ISSUE TITLE
Do not consider direction in "need negotiation" evaluation for replaceTrack

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1730]
Discussed in https://github.com/w3c/webrtc-pc/issues/1728#issuecomment-356386347.

Opening an Issue so it is not forgotten.

**Comment by taylor-b** [comment]
Relevant part of comment:

> I don't think the "determine if negotiation is needed" here is intended to take direction into account. It should be legal to call replaceTrack while the call is put "on hold," so that the correct track is sent as soon as the call is resumed. Otherwise the application would have to wait until it's taken off hold to call replaceTrack, and a frame from the old track could leak out, which isn't ideal.
