### ISSUE TITLE
Sort out unmute and BYE

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1752]
Brought up in https://github.com/w3c/webrtc-pc/pull/1748#discussion_r164882257

It is said that "an out of order packet should not unmute if BYE initiated mute".
@fluffy : should an in order packet received after the BYE unmute?

To me it even seems strange that a BYE for one SSRC should mute in the case that we still receive packets for other SSRCs used for this track. What's the rationale?

**Comment by alvestrand** [comment]
When we discussed this last, the thought was that the BYE for another SSRC could have gotten lost (BYEs are not guaranteed to be delivered) - if we didn't react to just one BYE, we'd not mute the track until the SSRC times out.
I think an in-order packet received after a BYE is a spec violation on the sender's side, but I could be wrong about that.

**Comment by aboba** [comment]
After an source sends a BYE it should not be sending more packets.  However, if it was a conflict that lead to the sending of the BYE then packets could still be sent by the sender who is the rightful owner of the SSRC.

**Comment by stefhak** [comment]
@fluffy is what was added in #1748 enough? Can we close this issue?

**Comment by stefhak** [comment]
Thanks @fluffy - closing.
