### ISSUE TITLE
Transceiver kind attribute

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1765]
It could be useful to add a kind attribute to the transceiver attribute.  Currently, best way to obtain this is via `transceiver.receiver.track.kind`.

**Comment by jan-ivar** [comment]
I think you mean `transceiver.receiver.track.kind`, and it's guaranteed to always be there, so I don't see the need for having two APIs for this. I vote we close.

**Comment by stefhak** [comment]
I'm also unsure about the need for this.

**Comment by aboba** [comment]
@jan-ivar I agree with you.  

@stefhak Feel free to close it (it was opened as a placeholder.

**Comment by alvestrand** [comment]
Somewhat offtopic: the sender has  this problem, since sometimes the sender doesn't have a track. And I really don't like having sender problems solved by linking to the transceiver (for non-SDP reasons).

**Comment by stefhak** [comment]
That's correct. Is your point that we now should add `kind` to sender to be forward compliant? That might make sense.

**Comment by jan-ivar** [comment]
```js
kind = sender => pc.getTransceivers().find(tc => tc.sender == sender).receiver.track.kind;
```

**Comment by jan-ivar** [comment]
We don't generally worry about forward-compliant do we?

**Comment by aboba** [comment]
Because ORTC doesn't have transceivers, both the sender and receiver have a kind attribute. So if a WebRTC 1.0 implementation is built on top of ORTC (either natively or via a shim), kind would be available in the sender and receiver.  However, WebRTC 1.0 implementations are not required to support ORTC, and in WebRTC 1.0 sender.kind and receiver.kind would need to be the same as transceiver.kind.
