### ISSUE TITLE
Semi-sync replaceTrack API pre-initial-negotiation is bizarre.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1769]
As mentioned in this [chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=811265), `replaceTrack` is spec'ed to be [semi-synchronous when](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack) the *"transceiver is not yet associated with a media description"*.

As I recall, this was a compromise reached long ago out of concern there'd be no way to synchronously set a track in time for createOffer, and was made before createOffer became impervious to these timing issues.

But this leaves users with a bizarre API: **if an error happens,  they won't know which one until later**. So it's never a fully synchronous API even in the pre-negotiation phase.

Users would have to write:
```js
sender.replaceTrack(newTrack);
if (sender.track != newTrack) {
  throw Error("An error happened, but we don't know which one (yet)!");
}
```
...if they were called synchronously and are expected to throw an exception for errors.

Of course, if they're not then they can get the error after the fact:
```js
let p = sender.replaceTrack(newTrack);
if (sender.track != newTrack) {
  await p; // rejects
}
```
... but then it begs the question why they're not just using:
```js
await sender.replaceTrack(newTrack);
```

FWIW I think we'd be happy to change Firefox to match Chrome here, and fix the spec.

**Comment by alvestrand** [comment]
Of course this API was written before "await" had consensus in the relevant standards community.

**Comment by jan-ivar** [comment]
This is unrelated to `await`. I merely prefer writing examples with it. Sorry for any confusion. What I mean is *if you're not expected to throw errors synchronously* (i.e. in a promise chain or async function).

**Comment by jan-ivar** [comment]
The reasons are coming back to me: SRD is timing-critical. If users delay calling SRD(offer), the peer connection [won't be ready to receive ICE candidates](https://stackoverflow.com/questions/36839080/webrtc-onicecandidate-am-getting-ice-candidates-with-sdpmid-audio-only-but-not/36851163#36851163).

So e.g. if users were to write:
```js
let getMyTransceiver() = pc.getTransceivers())[0] || pc.addTransceiver("video");

signalingChannel.onmessage = async ({data: {sdp, candidate}}) => {
  if (sdp) {
    await getMyTransceiver().sender.replaceTrack(myVideoTrack); // Delays SRD!
    await pc.setRemoteDescription(sdp);
    if (sdp.type == "offer") {
      await pc.setLocalDescription(await pc.createAnswer());
      sc.send({sdp: pc.localDescription});
    }
  } else if (candidate) await pc.addIceCandidate(candidate);
}
```
...they might occasionally miss ICE candidates, [a hard-to-find bug](https://stackoverflow.com/questions/36839080/webrtc-onicecandidate-am-getting-ice-candidates-with-sdpmid-audio-only-but-not/36851163#36851163).

Possible solutions may be to either:
 1. Enqueue replaceTrack, or
 2. Allow `sender.track = myVideoTrack` IFF "transceiver is not yet associated with a media description"

**Comment by jan-ivar** [comment]
For those unfamiliar with `await` the above example is loosely based on [this working cross-tab fiddle](https://jsfiddle.net/jib1/80xcgwmc/).

**Comment by henbos** [comment]
Even if a promise is immediately resolved/rejected its then() executes asynchronously in the next task. I think a "sometimes partially synchronous" API with promise is unexpected and confusing. +1 to always queuing a task for observable effects.

**Comment by taylor-b** [comment]
> But this leaves users with a bizarre API: if an error happens, they won't know which one until later. So it's never a fully synchronous API even in the pre-negotiation phase.

But the only errors possible at this point are calling `replaceTrack` while the transceiver is stopped, or calling `replaceTrack(audioTrack)` on a video sender, which are both user error. So is this really a problem?

**Comment by alvestrand** [comment]
so (reconstructing argument from memory) the sequence

tc = pc.addTransceiver()
tc.sender.replaceTrack(track)
pc.createOffer()

should have the track as part of the offer; anything else surprises the user.
in order to guarantee that, the setting of the track has to happen in the synchronous section.

thus, this is required in order to be able to construct pc.addTrack() on top of addTransceiver() and replaceTrack().
Seems hard to get away from that.

**Comment by jan-ivar** [comment]
> in order to guarantee that, the setting of the track has to happen in the synchronous section.

No, createOffer now [handles this fine](http://w3c.github.io/webrtc-pc/#dfn-final-steps-to-create-an-offer):

 *"If connection was modified in such a way that additional inspection of the system state is necessary, or if its configured indentity provider is no longer provider, then in parallel begin the steps to create an offer again, given p, and abort these steps."*

**Comment by jan-ivar** [comment]
> which are both user error. So is this really a problem?

@taylor-b Users make mistakes. It's possible to have e.g. intermittent `TypeError`s in JS.

But what bothers me more is the `async` version being able to cause call failure.

Users will get it wrong (e.g. coworker doing maintenance interprets missing `await` as a bug and adds it back to "fix" it, causing intermittent connection failures).

**Comment by alvestrand** [comment]
OK, solved by double dispatching in createOffer, so that whatever is enqued before createOffer starts is guaranteed to be done before createOffer finishes. Subtle!

In that case, I have no objection to moving the setting of sender.track entirely within the async section.

**Comment by jan-ivar** [comment]
Great. So we'll move it, but we also need to solve the SRD case I think then, so that waiting on replaceTrack ahead of it is safe. It sounds like most prefer the enqueue idea. I can write a PR.

**Comment by henbos** [comment]
I don't think anyone should ever call a promise-based function and expect it to be done before the promise signals that it has resolved. Do we have any other APIs like this except [legacy APIs](https://w3c.github.io/webrtc-pc/#legacy-interface-extensions) which I assume use promises to be compatible with other promise-based code?
