### ISSUE TITLE
Simplify candidate interaction by allowing Null

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1773]
We see a lot of code like this (this is a change from Firefox to making it work on Chrome)
<pre>
var onIceCandidateToSecond = function(event) {
-    gFirstConnection.addIceCandidate(event.candidate);
+    if (event.candidate) {
+      gFirstConnection.addIceCandidate(event.candidate);
+    }
   };
</pre>

Life for developers would be easier if they could just write the "addiceCandidate" and not the "if".
This requires inserting a line in "addIceCandidate" processing that says "If candidate is null, abort these steps and return". All existing code should still work, since nothing new is being forbidden.

This has been discussed before. Not a big issue, but reducing the number of things developers have to think about is generally a Good Thing.

**Comment by fippo** [comment]
see also #1213 and note that we have no implementations emitting {sdpMid, candidate:""}. I would still like to have addIceCandidate(null) as a "end-of-candidates for all media descriptions" since I don't see much of a use-case for doing that per ice-transport

**Comment by lgrahl** [comment]
This has been partly discussed in #1077 (albeit a bit chaotic).

**Comment by alvestrand** [comment]
Decision: No change needed.
