### ISSUE TITLE
DTMF should not send before connecting

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1774]
Current language:
https://w3c.github.io/webrtc-pc/#dom-rtcdtmfsender-insertdtmf

4. If transceiver's [[CurrentDirection]] slot is recvonly or inactive, throw an InvalidStateError.

However, before negotiation is completed, we don't know if it will be possible to send, and therefore we shouldn't do so.

Suggested change:

4. If transceiver's [[CurrentDirection]] slot is not sendonly or sendrecv, throw an InvalidStateError.

This requires a change to the following WPT tests so that they establish a call before testing DTMF:

RTCDTMFSender-insertDTMF.https
RTCDTMFSender-ontonechange-long.https
RTCDTMFSender-ontonechange.https

**Comment by alvestrand** [comment]
Note - the test for currentDirection should also be done when giving a value to canInsertDTMF, I think.

**Comment by aboba** [comment]
Yes.  Related to: https://github.com/w3c/webrtc-pc/issues/1619

**Comment by alvestrand** [comment]
Should be resolved in #1619.
