### ISSUE TITLE
Duplicate definitions errors (following update to respec 19.6.0)

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/webrtc-pc#1781]
Hi, following code changes in respec and the webrtc-respec-ci toolchain I had to move webrtc-pc to a newer respec release.

This new respec release (19.6.0) now reports new errors such as:
```
Errors
    Duplicate definitions of 'peeridentity' at: 1, 2, 3.
    Duplicate definitions of 'closed' at: 1, 2, 3, 4.
    (...)
```
And one warning:
```
Warnings
    Found linkless element for 'rtcrtpsender' with text 'getparameters' but no matching <dfn>.
```
See: https://w3c.github.io/webrtc-pc/

I am hoping one of the editor can look at this and my sincere apologies for the trouble. Thx.

**Comment by aboba** [comment]
@vivienlacourba Have some ideas about the warning (there are two getParameters methods, one for the RtpSender and another for the RtpReceiver).  But the Identity section has always been brittle.  Any way to revert this change until we figure out how to fix the errors?  This is now breaking the PR check process.

**Comment by vivienlacourba** [comment]
@aboba the PR CI checks were already broken on all WebRTC docs that did not use a fixed respec release (ie all of them but webrtc-pc and mediacapture-main). Failure reports from @alvestrand, suhas and dom got me started working on this after .

Those issues came from a change of dependencies in newer respec releases (move to Chromium and Puppeteer) which had to be taken into account in webrtc-respec-ci our CI toolchain.
This also meant I had to update the version of respec that was used in webrtc-pc and mediacapture-main as the version previously in use was not compatible with the new dependencies.

See: https://github.com/w3c/respec/issues/1522 and https://github.com/w3c/webrtc-respec-ci/pull/25
