### ISSUE TITLE
Define description.sdp for rollback for setLocalDescription

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1783]
For `setLocalDescription`; if the `description.type` is `rollback` (and then `description.sdp` is presumably null), there is no text about what is used for `description.sdp` when doing `Set the RTCSessionDescription`

**Comment by jan-ivar** [comment]
@stefhak I don't see `description.sdp` referenced explicitly, except in cases where after `description.type` is first tested to be something other than `"rollback"`. Did I miss one?

What I do see, are phrases like *"for each media description in description"*. There are zero media descriptions in the case of rollback, therefore such steps do not run at all on rollback. This is https://github.com/w3c/webrtc-pc/issues/1706 I believe, unless there are other things missing?

**Comment by stefhak** [comment]
@jan-ivar you're correct (and this is what is said in JSEP as well).

I'm closing this issue, but I think we likely have some stuff related to `rollback` to sort out (#1706 is one thing) yet.

**Comment by stefhak** [comment]
I created #1801 to handle the immediate problem I see.
