### ISSUE TITLE
Editorial: Some interfaces are missing links

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#1793]
The problem seem to affect the second half of the spec.

**Comment by Orphis** [comment]
I debugged this, it's caused by this issue: https://github.com/w3c/respec/issues/1559

**Comment by Orphis** [comment]
@dontcallmedom The bug in respec has been fixed, you should be able to upgrade it and fix the new warnings now :)

**Comment by Orphis** [comment]
Fixed with #1797
