### ISSUE TITLE
either full check certs or explain why it's not necessary (4.4.1.1 Constructor)

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webrtc-pc#1808]
4.4.1.1 tells the user agent to check a certification expiration but not anything else. ("If the certificates value in configuration is non-empty, check that the expires on each value is in the future.")  Harold has argued that this certificate is just a carrier and that checking the expiry here is a user experience enhancement only - it has no security benefit.  If he's right, please add a sentence or two explaining that.  If he's wrong, then some other things in the cert likely need to be checked.

**Comment by martinthomson** [comment]
These are not domain PKI certificates.  Though we use certificates, they are glorified holders of public keys.  Trust is anchored in the signaling.

The explanation for why checking isn't needed is a few levels of indirection away (in draft-ietf-rtcweb-security-arch, or further).  So no objection to someone adding an explanation here.

**Comment by stefhak** [comment]
Help wanted: can someone draft a PR?

**Comment by aboba** [comment]
@stefhak Done.
