### ISSUE TITLE
RTCDataChannelEventInit is not optional

### ISSUE THREAD

**Issue by nils-ohlmeier** [w3c/webrtc-pc#1811]
As RTCDataChannelEventInit is the last argument in RTCDataChannelEvent it needs to be optional as per https://github.com/heycam/webidl/issues/349#issuecomment-297032629

**Comment by jan-ivar** [comment]
My bad, I gave Nils wrong advice here. Turns out to be a Firefox bug since [we don't have](https://searchfox.org/mozilla-central/source/dom/webidl/RTCDataChannelEvent.webidl#17) the `channel` dictionary member as `required` yet.
