### ISSUE TITLE
DOMException(name=<Exception>) or instances of <Exception>?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1817]
There are a bunch of exceptions that should be raised in various circumstances defined by the spec. Are these of...

1. type `DOMException` with `.name` set (to for example `TypeError`, `OperationError`, ...), or
2. type `TypeError`, `OperationError`, etc.

Since `OperationError` doesn't seem a valid standalone exception class and we're using `OperationError` in the spec, I would assume 1. is correct.
But the WPTs use `TypeError` all the time and there are plenty of tests that pass with this assumption...

So, what's correct?

Note: Depending on the outcome of this we should file an issue for WPT and update adapter.

**Comment by gsnedders** [comment]
WebRTC currently has "created OperationError" where "created" is a citation to WebIDL (first time I looked at this it just sent me to [WebIDL] in the references section and not the definition in WebIDL, weirdly?), where the "created" citation does say that it creates a DOMException.

I'd strongly recommend following what the DOM spec does, with wording like 'throw a "SyntaxError" DOMException', as this makes it unambiguous that a DOMException is being created/thrown.

As with WebIDL 2, I'd expect things throwing TypeError to not throw a DOMException but to throw a TypeError.

**Comment by lgrahl** [comment]
So, if I understand WebIDL correctly, then everything is a `DOMException` unless it is one of the following so called *simple exceptions* that you have to detect by their name: `Error`, `EvalError`, `RangeError`, `ReferenceError`, `TypeError`, `URIError`. :unamused:

**Comment by gsnedders** [comment]
@lgrahl yes.

**Comment by lgrahl** [comment]
@aboba No spec issue from my side. However, I agree with @gsnedders some wordsmithing could be applied. Would you like to create a PR for this, @gsnedders?

**Comment by jan-ivar** [comment]
Seems a consistency issue. I already see this in the spec: *"Reject p with a DOMException object whose name attribute has the value OperationError and abort these steps."* - just need to use it consistently.

**Comment by jan-ivar** [comment]
As to [RTCError](http://w3c.github.io/webrtc-pc/#dfn-rtcerror) that is a new error class (type 2 above)

**Comment by gsnedders** [comment]
@lgrahl I'm unlikely to get around to it, FWIW.

**Comment by lgrahl** [comment]
Okay. FWIW, I can't work on this atm either.

**Comment by henbos** [comment]
In https://github.com/w3c/webrtc-pc/issues/2330 we propose using the old name ('OperationError'), but instanceof RTCError would still be true. Can we close this issue?

**Comment by henbos** [comment]
Or we still need to update WPT tests?

**Comment by dontcallmedom** [comment]
the consistency issue seems to have been addressed. I have marked #2375 with the needs test label; closing that issue
