### ISSUE TITLE
RTCDataChannel.send steps for bufferedAmount

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1824]
Step 3 states:

> Let data be a byte buffer that represents the result of encoding the method's argument as UTF-8 and increase the value of the [[BufferedAmount]] slot with the length of data.

But step 4 raises TypeError in case the message is too large to be sent (> maxMessageSize). So, [[BufferedAmount]] should not be increased before that.

---

Two more things:

* Step 4 should explicitly mention that *size of data* means the size in bytes.
* A typo in two places: *slot with **the the** length*.

**Comment by stefhak** [comment]
@lgrahl please provide a PR
