### ISSUE TITLE
Data channel receive procedure missing?

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1825]
It seems there is no data channel receive procedure that can be followed, e.g. nothing tells us when a *message* event is invoked and what validation steps are required (check for *open* [or *closing*], ...).

The WPT tests reference [this WS spec section](https://html.spec.whatwg.org/multipage/web-sockets.html#feedback-from-the-protocol) (*When a WebSocket message has been received [...]*) and I would propose to copy that.

**Comment by lgrahl** [comment]
We should discuss whether messages can still be received by the peer who initiates the closing procedure or not (see [this discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=559394)).

**Comment by aboba** [comment]
@lgrahl  Agree that the closing procedure doesn't provide enough detail.  As discussed in Issue 559394, when a peer calls close() (resulting in readyState transitioning to "closing") more messages can't be sent, but data can still be received until readyState becomes "closed".
