### ISSUE TITLE
No way to add track with stream associations to a given transceiver 

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1826]
While writing [this blog](https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/), I discovered transceivers only let us answer with stream-less tracks.

That is, we can add a track to a given transceiver, but not with any stream associations:
```js
await pc.setRemoteDescription(description);
let transceiver = foo(pc);
transceiver.direction = "sendrecv";
await transceiver.sender.replaceTrack(cameraStream.getVideoTracks()[0]);  // no stream
await pc.setLocalDescription(await pc.createAnswer());
```
If our transceiver happens to be the first unused one of its kind in `pc.getTransceiver()`, we can use `addTrack` to do it, but this seems incomplete.

There's no general way to add a track with stream associations to a transceiver in the middle of a list of unused transceivers.

Any workaround using `addTrack` would lock in streams for all transceivers ahead in the list.

When working with transceivers, this feels like an awkward omission, leading to contortions.

**Comment by jan-ivar** [comment]
I propose:
```js
transceiver.sender.setStreams([cameraStream]);
```
We could either:
 1. have it throw outside `"have-remote-offer"` or if the transceiver is used, to limit scope, or
 2. explore letting users change existing associations this way as well (have it trigger negotiationneeded in `"stable"` state).

I seem to recall someone asking for the latter not too long ago. One less reason to mangle SPD, which we'll likely [end up supporting](https://github.com/w3c/webrtc-pc/issues/1729#issuecomment-356787787) on the far end anyway.

**Comment by alvestrand** [comment]
setStreams would work for me. It would trigger "negotiation needed".
Also, sender.replaceTrackAndReplaceStreamInfo(track, streams) would work, if it's allowed to trigger negotiation-needed.

**Comment by alvestrand** [comment]
On discussion -  let's just treat the streams list as a separate property of the sender and set it using a separate call. I like Jan-Ivar's proposal.

**Comment by aboba** [comment]
Consensus from the April VI is for Jan-Ivar to create a PR based on his proposal.
