### ISSUE TITLE
RTCDataChannel.send during 'closing' state

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1827]
Let's look at the following scenario: Peer A and B have an `open` data channel. If peer A closes the channel, peer B's channel will go into the `closing` state until all pending messages of both peers have been sent. If peer B calls the `.send` method, it will throw an exception since the channel is not in the `open` state any more. But peer B has no way of knowing that unless it polls `.readyState`.

Do we need to address that with an... (I'm reluctant to say that) event?

**Comment by aboba** [comment]
@lgrahl In other interfaces, state attributes have an onstatechange event handler, but not RTCDataChannel. So I'm also reluctant, but it is not an unreasonable suggestion.  Can you submit a PR?

**Comment by lgrahl** [comment]
As an alternative: What if we simply say to discard the message in case `.readyState` is `closing`?

**Comment by lgrahl** [comment]
Adding an `onclosing` event would be overkill in my opinion. I would like to hear more opinions (and hopefully suggestions) before creating a PR.

**Comment by lgrahl** [comment]
That would probably resolve the issue with `.send` but open another one: The `close` event is an indication that a stream ID can be reused. However, if we set the `closed` state earlier, the application doesn't know when an ID can be reused.

**Comment by jhaenchen** [comment]
@aboba or @lgrahl Excuse me if I'm misinterpreting this, but how would this procedure work for a hard-quit peer, i.e. a browser peer that has been forced to quit and so does not send any reset or anything? I am still stuck in .closing and this scenario and thought it might be relevant here

**Comment by lgrahl** [comment]
@jhaenchen There's no need for cleanup in that case. I was going to write that:

> When the ICE connection state goes into `failed`, all data channels should be in the `closed` state immediately. If they aren't, it's a bug in the implementation.

But I haven't found a procedure in the spec that defines what should happen once the peer connection state goes into `failed`. @aboba, @jan-ivar, anyone? :sweat_smile: But to prevent becoming sidetracked in this issue, perhaps one of you could open a new issue when responding.

Anyhow, even if the procedure is missing, there is no need to do cleanup and the data channels should be in the `closed` state. Whether or not the `close` event should fire is up for debate. However, I would argue that the event should fire because it is triggered by the remote side.

**Comment by aboba** [comment]
@lgrahl Could we fire the `onclosed` event when `readyState` transitions to "closing"?

**Comment by jan-ivar** [comment]
@jhaenchen are you still basing observations on Chrome? Do you get different results in Firefox? This sounds like https://github.com/w3c/webrtc-pc/issues/1020#issuecomment-423280588 again.

**Comment by jan-ivar** [comment]
`onclosing` seems like the simplest solution to me.

**Comment by jhaenchen** [comment]
@jan-ivar that does seem like the bug I’m experiencing. Didn’t see the comment you referenced either, thanks for bringing that to my attention!

**Comment by monktan89** [comment]
m
