### ISSUE TITLE
Data channel minimum amount of streams supported

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1829]
Short question: Do we **require** implementations to support the maximum amount of streams (65535)?

My opinion: Yes. If there's agreement, can we make this crystal clear in the spec?

**Comment by jesup** [comment]
I'll note that the reason we haven't yet done so in our implementation is that the usrsctp library doesn't (yet) support on-demand allocation the memory to track streams; it sizes arrays when it negotiates the number of streams with the far end.  We explicitly removed the requirement to re-negotiate the number of streams (though Firefox supports it) after some slightly contentious discussions in the IETF, where the winning argument was that while the current usrsctp implementation early-allocates, it doesn't need to, and that could be updated, and so we could exclude the complexity of having to make the code wait for renegotation-on-open, deal with errors from it, etc. 

Of course, the fly in this is that this optimization has not happened.  For PCs, this isn't much of an issue, but for low-ram mobile devices or embedded use of WebRTC it's a lot of wasted ram when an app typically wants 1, 2, or *maybe* 5 DataChannels.  (There are a very few apps that use 10's, and a couple (count on your fingers...) that can/do make use of 100's or a 1000 - uproxy was one.)

**Comment by lgrahl** [comment]
The memory usage issue in usrsctp is tracked here: https://github.com/sctplab/usrsctp/issues/121
(And may I also point out that I think the usrsctp folks would appreciate some help in resolving these kind of issues.)

@jesup But what is your opinion when it comes to the spec? It's not really clear whether we do or do not require support for the maximum amount of streams. Is there any reason why we shouldn't require it... other than the mentioned issue?

**Comment by taylor-b** [comment]
Here's the relevant excerpt [from the data channel spec](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#section-6.2):

**Comment by lgrahl** [comment]
Unfortunately, @taylor-b is correct. The question is: If the draft states it's only a SHOULD, can we still specify it as a MUST in the W3C spec? Or propose changing it to a MUST in the draft?

And if we don't, how would the user know how many channels it can create before trying to do so? Add a new attribute `RTCSctpTransport.maxChannels` which contains the negotiated amount of channels (minimum of negotiated incoming/outgoing streams)?

**Comment by lgrahl** [comment]
After a brief discussion on the RTCWeb WG mailing list, it seems clear that we will have to be prepared that at least the other peer may support less than 65535 streams. So, in order to inform the user application about the maximum amount of channels that can be created, I propose to add a new attribute to `RTCSctpTransport`:

```
interface RTCSctpTransport {
    ...
    readonly attribute unsigned short maxChannelId;
    ...
}
```

where `maxChannelId` is the minimum of the negotiated amount of incoming and outgoing streams (@tuexen is that correct to determine the maximum channel ID?).

We would need to add a check to all places where a data channel is being created or an ID is being assigned to comply with this maximum. (Furthermore, having this attribute will make channel ID exhaustion tests easier to write.)

Comments? :slightly_smiling_face:
