### ISSUE TITLE
Illogical specification of peerIdentity in PeerConnection constructor

### ISSUE THREAD

**Issue by Rob--W** [w3c/webrtc-pc#183]
The following fragment looks a bit weird. Why would a connection fail if the authentication succeeds? I think that "unless" has to be replaced with "if".

> **peerIdentity** of type DOMString
> Sets the target peer identity for the RTCPeerConnection. The RTCPeerConnection will establish a connection to a remote peer unless it can be successfully authenticated with the provided name.
> ~ https://w3c.github.io/webrtc-pc/#widl-RTCConfiguration-peerIdentity

/cc @martinthomson because you authored this fragment in bd9cee2c6ca089ea9a9e33892e52d8001ddd80e6

**Comment by martinthomson** [comment]
Yep, something is missing a negation somewhere.

**Comment by burnburn** [comment]
Addressed in commit 4c6d983a88dab6026bc82f98b337466eb063cc17
