### ISSUE TITLE
The "Create an RTCRtpSender" algorithm needs a `kind` argument

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1830]
The [Create an RTCRtpSender](http://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtpsender) algorithm uses undeclared "kind" variable: *"If sender is of kind "audio" "*

Sender has no kind yet, and algorithm needs to tolerate *track* being null.

**Comment by fippo** [comment]
ORTC has a [constructor with "trackOrKind"](http://draft.ortc.org/#rtcrtpsender-interface-definition*) as the first argument for exactly that reason.

**Comment by aboba** [comment]
@fippo In WebRTC 1.0, RTCRtpSender does not have a constructor.
