### ISSUE TITLE
What should sender.getParameters().codecs return before negotiation?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1839]
The current text says

The codecs sequence is populated based on the codecs that have been negotiated for sending, and which the user agent is currently capable of sending.

This seems to indicate that prior to negotiation completing, the set should be empty. Is this intentional, and reasonable?

The other reasonable expectation is that prior to negotiation, the list of codecs should be the one that will be represented in a subsequent createOffer() - ie indicating the capabilities of the codec.

**Comment by aboba** [comment]
If sender.getParameters().codecs is not empty, would that not imply that sender.setParameters() can be used to modify the codec list prior to negotiation?  And if that were true, why would we need setCodecPreferences? 

Questions like this seem to lead... to more questions.

**Comment by alvestrand** [comment]
setCodecPreferences gives a cleaner API surface for when we want to manipulate subsequent rounds of negotiation. I'd prefer to leave it as-is (expect to implement).

The current chrome implementation has the list empty before negotiation, which led to me asking the question and finding that the answer wasn't obvious from the spec.

**Comment by taylor-b** [comment]
> This seems to indicate that prior to negotiation completing, the set should be empty. Is this intentional, and reasonable?

Yes and yes. If you want to know the codecs the browser is capable of (and thus would offer) you can use `RTCRtpSender.getCapabilities`.  `getParameters` is for what is available to send, so the application can pick one and put its payload type in `RTCRtpEncodingParameters`. Until a remote description is set, you don't know what payload types they'll use, so it wouldn't make sense to return anything.

That's my two cents anyway.

**Comment by aboba** [comment]
@taylor-b Wouldn't you want to set the payload type in `RTCRtpEncodingParameters` before Offer/Answer, for example, in the `sendEncodings` argument to addTransceiver?

**Comment by taylor-b** [comment]
@aboba Ideally... though I don't think we've ever had a way to do that.

**Comment by alvestrand** [comment]
Proposed resolution: Keep curent behavior, and make it really obvious.

**Comment by Orphis** [comment]
Should we do the same for headerExtensions as well?
I'd like to have a clarification for the other fields too, especially in relation with a setParameters() call before negotiation, should that even be possible?
