### ISSUE TITLE
What should receiver.getParameters().encodings[] return?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1840]
Section 5.3 defines RTCRtpParameters.getParameters() as follows: 

"The getParameters() method returns the RTCRtpReceiver object's current parameters for how track is decoded. When getParameters is called, the RTCRtpReceiveParameters dictionary is constructed as follows: encodings is populated based on RIDs present in the current remote description, and whether media is actively being decoded or not. The headerExtensions sequence is populated based on the header extensions that the receiver is currently prepared to receive.  The codecs sequence is populated based on the codecs that the receiver is currently prepared to receive."

Some questions; 

a. Since WebRTC 1.0 API does not support configuration of simulcast reception, and no browsers appear to be preparing to support this, do we really expect encodings to be populated based on RIDs?   If not, should we mark simulcast reception as a feature at risk?
b. Since the active attribute is not used by receivers, should we delete the text about "whether media is actively being decoded or not"?
c. Since headerExtensions and codecs is populated based on what the receiver is prepared to receive, does this imply that they are set when SLD is called (on the Offerer) or SRD (on the Answerer)?

**Comment by alvestrand** [comment]
I think it should return what's currently described in section 5.3:

The codecs sequence is populated based on the codecs that the receiver is currently prepared to receive.

NOTE
Both the local and remote description may affect this list of codecs. For example, if three codecs are offered, the receiver will be prepared to receive each of them and will return them all from getParameters. But if the remote endpoint only answers with two, the absent codec will no longer be returned by getParameters as the receiver no longer needs to be prepared to receive it.

**Comment by alvestrand** [comment]
May 2018 VI decision: Delete the vestigal text.
