### ISSUE TITLE
RTCRtpDecodingParameters

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1852]
Currently, RTCRtpDecodingParameters is defined as follows: 

dictionary RTCRtpCodingParameters {
    DOMString rid;
};

dictionary RTCRtpDecodingParameters : RTCRtpCodingParameters {
};

Some questions: 

a. Since WebRTC 1.0 API doesn't support simulcast reception, why is the rid attribute in RTCRtpDecodingParameters?
b. Does codecPayloadType belong in RTCRtpDecodingParameters?

**Comment by aboba** [comment]
@taylor-b Question:  Do we need the codecPayloadType attribute on either the sender or receiver? If so, could it be read-only?

**Comment by taylor-b** [comment]
It was only meant for the sender; the description mentions "This field is not used for RTCRtpReceivers."

**Comment by aboba** [comment]
At the virtual interim, there were no browser vendors indicating the intention to support simulcast reception.  Resolution was to attempt to confirm this on the mailing list, and if so, to remove the rid attribute.
