### ISSUE TITLE
Editorial: Does throwing an error imply aborting the steps?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1856]
We have a number of occurences of:

"Throw an error"

"Throw an error and abort these steps"

that seem to assume that these have equivalent behavior.

We should use only one pattern, and make sure our assumptions about the behavior of throws is valid.

**Comment by lgrahl** [comment]
I agree this should be consistent. From my point of view, raising an error is sufficient to abort all steps of the enclosing task.

**Comment by alvestrand** [comment]
@domenic can you confirm that throwing an error implies aborting the steps of that task?
I couldn't figure it out from the references on "throw an error".

**Comment by domenic** [comment]
Yeah, we had this inconsistency problem in various places before, and have settled on just throwing the error. This was encoded in https://infra.spec.whatwg.org/#algorithm-control-flow.
