### ISSUE TITLE
What happens when an answerer stops a transceiver that others are "bundled" on?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#1858]
The BUNDLE spec says:

> When an answerer wants to reject a bundled "m=" section in an answer, it MUST first check the following criterium:
> 
> -In the corresponding offer, an offerer BUNDLE address:port (previously selected [Section 8.3.1] or newly suggested [Section 8.5.1]) has been assigned to the "m=" section by the offerer.
> 
> If the criterium above is fulfilled the answerer can not reject the "m=" section in the answer (unless the answerer rejects each bundled "m=" section within the BUNDLE group).  The answerer can either reject the whole offer, reject each bundled "m=" section within the BUNDLE group, or keep the "m=" section within the BUNDLE group in the answer and later create an offer where the "m=" section is disabled within the BUNDLE group [Section 8.5.4].

Or, in [this PR](https://github.com/cdh4u/draft-sdp-bundle/pull/59/files) which changes the terminology:

> When an answerer wants to reject a bundled "m=" section in an answer, it MUST first check the following criterium:
> 
> - In the corresponding offer, the "m=" section is the offerer tagged "m=" section.
> 
> If the criterium above is fulfilled the answerer can not reject the "m=" section in the answer. The answerer can either reject the whole offer, reject each bundled "m=" section within the BUNDLE group, or keep the "m=" section within the BUNDLE group in the answer and later create an offer where the "m=" section is disabled within the BUNDLE group.

Either way, the point is the same. If you have an established bundle group, "a=BUNDLE audio video", the answerer can't reject the "audio" section without rejecting "video" as well.

So: how should this play with `RTCRtpTransceiver.stop`, specifically when called in the "have-remote-offer" state? Should stopping the audio transceiver automatically cause the video transceiver to be stopped as well? Or should the answerer keep the audio m= section (as "inactive", maybe?), then stop it in a subsequent offer triggered by `onnegotiationneeded`?

And does this require JSEP changes?

**Comment by jan-ivar** [comment]
Is there a way in the API to know that BUNDLE is being used? If not, then if `stop()` sometimes were to stop other transceivers, there's no way to predict the outcome.

**Comment by taylor-b** [comment]
> Is there a way in the API to know that BUNDLE is being used? 

Yes; if `transceiver1.receiver.transport == transceiver2.receiver.transport`, they're currently bundled together and would be affected by this. That still doesn't tell you which is the special one that can't be rejected, but you could tell by parsing the "a=group:BUNDLE" in the offer.

By the way, the conclusions at the virtual interim were:
* We should just reject all bundled m= sections if this happens, because that's simpler.
* The other rejected m= sections' transceivers shouldn't be stopped until `setLocalDescription(answer)`

**Comment by jan-ivar** [comment]
What determines which one is special? The implementation? This seems like a downside of having implementation details influence APIs.

**Comment by taylor-b** [comment]
> What determines which one is special? The implementation?

Yes, though every implementation I've seen just picks the first m= section in the order it appears in SDP. Or in other words, the first transceiver added.

If this is a concern, it wouldn't be hard to add an argument to `createOffer`; for example, `createOffer({bundleOnMid:"audio"})`. Such that the application could choose a transceiver it knows is not likely to be rejected.

**Comment by taylor-b** [comment]
Meaning, have one m= section that's dedicated exclusively to containing the transport parameters for BUNDLE? I've asked that myself, and the answer I got was "we considered that approach but decided against it". I assume the concern was that non-BUNDLE endpoints would be confused at receiving such an offer.

Regardless of the reasons, that would definitely require JSEP changes, so I don't think a change of that magnitude is feasible at this point.

**Comment by taylor-b** [comment]
Consensus at VI was to just reject all the m= sections in the bundle group: https://www.w3.org/2018/05/22-webrtc-minutes#item06

**Comment by henbos** [comment]
Related to #1919 with list discussion needed

**Comment by henbos** [comment]
This will be fixed by #2049

**Comment by aboba** [comment]
@henbos Can we close this issue?

**Comment by henbos** [comment]
Yes!
