### ISSUE TITLE
How to prevent tracks from being renegotiated after rejection

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#187]
Situation:

1. A adds a track and sends an offer.
2. B applies the offer, but rejects the track (calls .stop() on it).
3. A receives the answer and doesn't send the track.
4. A creates a second offer.

As currently specified, the second offer will include the rejected track.

@juberti suggests that we mark the corresponding RtpSender (maybe it can have a `rejected` property).

Also to consider: what if A *wants* to include the track in the second offer?  Should it be forced to remove the dead track and re-add it?  Maybe the `rejected` property can be made mutable, so that it can be set back to false.

**Comment by stefhak** [comment]
Could not that sender move to a closed state (with a close event being fired)? Subsequent offers will not contain the track, and if the application wants to try to send it again it can add it directly (no need to remove it because it is closed and not part of "this RTCPeerConnection object's set of [active] senders.").

**Comment by juberti** [comment]
Senders don't have any states at the moment, but this sounds similar to what Martin/I mentioned above.
I prefer 'closed'/'ended' to 'rejected'. I also think readding makes more sense than making the closed state mutable.

**Comment by juberti** [comment]
@pthatcherg wdyt?

**Comment by juberti** [comment]
@pthatcherg ping

**Comment by pthatcherg** [comment]
I think having an RtpSender.state == "closed" makes a lot of sense (I don't like "rejected").  I think having other states such as "active" or "inactive" depending on the state of the m-line direction also makes sense (sendrecv/sendonly/recvonly/inactive).

However, if an m-line has a port 0, doesn't that "close" the m-line for both the RtpSender and the RtpReceiver with that MID?  If the answerer called addTrack() to create an RtpSender, and then called receiver.track.stop() to close the m-line, wouldn't the closing of the m-line also close the RtpSender just created?  If that's the case, I think we should have an API point that makes this more clear (something like closeSenderAndReceiver).  Or am I wrong and it's possible to close an m-line just for the receiver, but not for the sender?
