### ISSUE TITLE
localDescription, remoteDescription et al. need internal slots

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#1871]
Both Chrome and Firefox fail a basic test of:
```js
  await pc1.setLocalDescription(await pc1.createOffer());
  console.log(pc1.localDescription == pc1.localDescription); // false; should be true!
```
That's because we're returning a new instance on getting. Instead, we (and the spec) should return the value of an internal slot of type `RTCSessionDescription`.

**Comment by aboba** [comment]
@jan-ivar Can you submit a PR?
