### ISSUE TITLE
sendEncodings in "create an RTPSender" should reflect platform capabilities

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1872]
At the moment, the "create an RTPSender" steps says:

If sendEncodings is given as input to this algorithm, and is non-empty, set the [[SendEncodings]] slot to sendEncodings.
Otherwise, set it to a list containing a single RTCRtpEncodingParameters with active set to true.

This does not inform about the ability of the sender to accept multiple encoding layers.

Suggested replacement:

Initialize the [[SendEncodings]] slot to a list of RTCRtpEncodingParameters with "active" set to false. The length of the list reflects the UA's ability to send simulcast encodings.
If sendEncodings is given as input to this algorithm, copy the content of the sendEncodings into the first slots of the [[SendEncodings]] array. If sendEncodings is longer than [[SendEncodings]], discard the last values of sendEncodings.
If sendEncodings is not given, set "active" of the first element in [[SendEncodings]] to true.

**Comment by jan-ivar** [comment]
> This does not inform about the ability of the sender to accept multiple encoding layers.

Wasn't this solved by https://github.com/w3c/webrtc-pc/pull/1862 already?

**Comment by alvestrand** [comment]
#1862 certainly makes a difference, but it doesn't allow the user to change from unicast to simulcast after creating the sender, or to figure out whether the sender can support more layers than initially configured.

Tangential: There's a problem with the #1862-added text in the case where one wishes to start off with one layer of simulcast and activate new layers later - in that step 14 in "create an RTCRtpSender" removes the RID, and since RID is not modifiable via setParameters, we can't set it afterwards.
That means that if the sender wants to use simulcast, he MUST start off with the max # of layers he ever wants to support, and just set "active" = false on the layers he doesn't want in the beginning.

**Comment by jan-ivar** [comment]
> That means that if the sender wants to use simulcast, he MUST start off with the max # of layers he ever wants to support, and just set "active" = false on the layers he doesn't want

Is that not sufficient as an API?

**Comment by alvestrand** [comment]
WG decision (May 2018 VI): We don't need to allow switching from unicast to simulcast, and we don't need to show that the platform is able to support simulcast to people who don't ask for it.
If the user wants "standby" encoding layers, he can specify them with active=false in addTransceiver.

Closing issue as "no change needed".
