### ISSUE TITLE
Add RTCRtpSender.replaceTrack

### ISSUE THREAD

**Issue by juberti** [w3c/webrtc-pc#189]
partial interface RTCRtpSender {
  Promise<void> replaceTrack(MediaStreamTrack track)
};

This allows apps to do things like front/back camera switching, without the signaling that addTrack/removeTrack would require.

Jan-Ivar and I got assigned this at TPAC.

**Comment by jan-ivar** [comment]
PR #195

**Comment by wzhan12** [comment]
what is the status of this issue. If there is no the feature support, what way we can change streams without signaling?

**Comment by stefhak** [comment]
This was addressed with the landing of #303
