### ISSUE TITLE
does rtcrtpheaderextensionparameters need a direction?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1912]
iiuc https://w3c.github.io/webrtc-pc/#rtcrtpheaderextensionparameters will be returned by getParameters and (quoting @alvestrand) to check "are the things I expected present" in terms of functionality available on an RTP connection.

Do we need a direction member to allow discovering whether a header extension is sent, received, sent and received or negotiated but inactive?

ORTC mentions the direction here: http://draft.ortc.org/#rtcrtpheaderextensionparameters*
but does not include a direction member either (and the text there seems to be in the wrong section but i'll file an issue there)

**Comment by alvestrand** [comment]
I think the relevant section about direction is this one:
https://tools.ietf.org/html/rfc5285#section-6

Is anyone using direction attributes in extmaps? It seems logical to surface them here if they're used.

**Comment by fippo** [comment]
Firefox uses them for the ssrc-audio-level -- see https://bugs.chromium.org/p/webrtc/issues/detail?id=7477 for the issues this caused (causes)

**Comment by alvestrand** [comment]
Just for fun, the extensions that are negotiated away can still appear on the media  stream as long as they're signalled in the original offer. Quote:

   Either party MAY include extensions in the stream other than those
   negotiated, or those negotiated as "inactive", for example, for the
   benefit of intermediate nodes.  Only extensions that appeared with an
   identifier in the valid range in SDP originated by the sender can be
   sent.

The RFCs continue to be a source of surprises!

**Comment by ibc** [comment]
> ORTC mentions the direction here: http://draft.ortc.org/#rtcrtpheaderextensionparameters*
but does not include a direction member either

Such a `direction` attribute is not needed in ORTC `RTCRtpHeaderExtensionParameters` because those params are given to a sender or to a receiver, so the direction is implicit.

But, probably the `direction` attribute should be present in the `RTCRtpHeaderExtension` dictionary (within the `RTCRtpCapabilities`) to tell the app whether a specific RTP header extension can be used for sending and/or receiving.

**Comment by nils-ohlmeier** [comment]
I think the `direction` attribute is needed, because since PeerConnection uses SDP you need a way to find out what is/was the result after Offer/Answer concluded. Except if we wanted to let applications parse the SDP them self. But I guess that would defeat the purpose of these APIs.

**Comment by aboba** [comment]
@fippo @nils-ohlmeier Seems that the result after Offer/Answer can be determined based on whether a header extension is included in `receiver.getParameters` and/or `sender.getParameters`? So not clear that `direction` is needed in `RTCRtpHeaderExtensionParameters`. 

In `RTCRtpHeaderExtension` `direction` would only be needed if a header extension wasn't capable of being used in either direction. Do we have an example of a header extension with such a potential limitation?

**Comment by nils-ohlmeier** [comment]
@aboba I think you are right. Presence of an extension in either <code>receiver.getParameters</code> or <code>sender.getParameters</code> should indicate which direction the extension is being used for. The extension getting dropped by the answerer should result in the extension not being in either of these two sets (as it's not being used). The only question I see is how to handle if the answerer sets the extension to <code>inactive</code>?
But I would suggest to simply handle this in the same way as an extension not being negotiated. As the JS applications don't really have a means any way to force turning on an <code>inactive</code> extension.

**Comment by aboba** [comment]
We believe that this issue is fixed by the merger of PR https://github.com/w3c/webrtc-pc/pull/1924

Please reopen if this is not the case.
