### ISSUE TITLE
rename RTCIceCandidate.ip to address?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1913]
We expose the ICE candidate IP in https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-ip

Given Safaris plans to use mdns hostnames here (@youennf probably knows the tracking bug) should we rename this field to `address` or `connectionAddress`?

https://tools.ietf.org/html/rfc5245#section-15.1 calls it connectionAddress and defines the content as 
```
<connection-address>:  is taken from RFC 4566 [RFC4566].  It is the
      IP address of the candidate, allowing for IPv4 addresses, IPv6
      addresses, and fully qualified domain names (FQDNs).
```

I hate late-stange renames but AFAIK nobody has shipped RTCIceCandidate properties yet (apart from adapter shimming it)

**Comment by lgrahl** [comment]
Wouldn't this clash with ORTC implementations that shim WebRTC?

**Comment by a2sheppy** [comment]
FWIW, from a docs standpoint, I agree with this proposal to rename `ip` to `address`, for a couple of reasons:

1. As @fippo notes, if anyone implements a scenario in which the address is not an IP address, the name becomes obsolescent.
2. This one sounds frivolous but I'm actually serious: property names as short as `ip` are an oddity in documentation, in that they can be difficult to read and to differentiate, potentially resulting in developers missing details as they read. When possible, I feel that 3 or 4 characters is a practical minimum for property names, with certain exceptions like coordinate axis names in some cases.

**Comment by jan-ivar** [comment]
Since we already have [relatedAddress](http://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-relatedaddress) and [relatedPort](http://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-relatedport) `s/ip/address/` seems reasonable to me.

**Comment by alvestrand** [comment]
Mapping an IP to a FQDN is impossible in principle.
We can make it a requirement to store the FQDN that the IP was learned from, and report that in "address", but that's the way we have to phrase it.
For remote peer-reflexive addresses (I think that was the name), we don't have the FQDN that it was learned from (we pick up the address from the from address an incoming STUN packet on one of our announced interfaces).

WRT the DNS processing returning multiple candidates, this is now covered by https://tools.ietf.org/html/draft-ietf-mmusic-ice-sip-sdp-16 section 5.1, with slightly more convoluted language:

"
                                                                               An IP
      address SHOULD be used, but an FQDN MAY be used in place of an IP
      address.  In that case, when receiving an offer or answer
      containing an FQDN in an a=candidate attribute, the FQDN is looked
      up in the DNS first using an AAAA record (assuming the agent
      supports IPv6), and if no result is found or the agent only
      supports IPv4, using an A record.  The rules from section 6 of
      [RFC6724] is followed by fixing the source address to be one from
      the candidate pair to be matched against destination addresses
      reported by FQDN, in cases where the DNS query returns more than
      one IP address."

I'm not completely sure what the last portion means.

**Comment by fippo** [comment]
> Implementations will likely need to map ips back to FQDNs here.

No. Implementations should at a very low level only return the hostname-or-address. Otherwise you risk issues like resolving the hostname and then using it in a subsequent offer, thereby leaking the ip.

**Comment by jan-ivar** [comment]
Under the hood I suspect implementations can do whatever they want, as long as they hang on to and only expose the relevant FQDNs, right?

**Comment by jan-ivar** [comment]
TBC this issue only covers renaming the attribute, which I guess does not technically need to block on having it represent mDNS names.

**Comment by fippo** [comment]
chrome should actually handle addresses now: https://bugs.chromium.org/p/webrtc/issues/detail?id=4165

**Comment by jan-ivar** [comment]
@aboba [section 15.1](https://tools.ietf.org/html/rfc5245#section-15.1) says: *"An IP address SHOULD be used, but an FQDN MAY be used in place of an IP address."*

Ok to merge PR?

**Comment by jan-ivar** [comment]
Note there are two PRs here, one for webrtc-pc and one for webrtc-stats.

**Comment by vr000m** [comment]
LGTM
