### ISSUE TITLE
RTCIceTransport.component is at the wrong abstraction layer

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1916]
The "component" of an RTCIceTransport returns either "rtp" or "rtcp", depending on what the ICE transport is used for.

This is a layering mistake; if RTCIceTransport is to be a reusable component of other structures (like QUIC or data-channel-only sessions), this needs to be on the containing object, not on the contained object.
The "component" is also present on the RTCIceCandidate, but there it serves to route a candidate to the correct transport when presented to the peerconnection; the peerconnection already knows which transport is the RTP and which is the RTCP if both are used.

I suggest deleting this component from the interface.

**Comment by taylor-b** [comment]
Couldn't we leave this as a convenience for `RTCIceTransport`s created by `RTCPeerConnection`s, and leave it off of `RTCIceTransport`s constructed independently (via the extension spec)? I don't see a downside to that.

**Comment by aboba** [comment]
When ICE candidates are constructed independently, the component needs to be determined. In ORTC (which supports both "rtp" and "rtcp" components), it is determined from IceTransport.component.

**Comment by lgrahl** [comment]
My impression in the f2f meeting was that we want to remove support for not bundling components. Is that for 1.0? Or maybe I misinterpreted? :slightly_smiling_face:

**Comment by aboba** [comment]
Seems like this is an issue for the WebRTC-ICE Extension specification.

**Comment by fippo** [comment]
I don't think this was/is a problem. The component is 1 (rtp) even for SCTP -- see #1201
