### ISSUE TITLE
detecting a remote ICE restart?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1918]
is there a way in the API that allows me to detect the remote side tried an ice restart after SRD is done?

There are ways to detect it such as parsing the SDP and
* comparing the incoming ufrag to the current remote description before calling SRD
* comparing the new answer ufrag before SLD
but both variants require SDP parsing.

With RTCIceTransport.getRemoteParameters() once can probably avoid parsing the SDP at least.
Do we need a better way like firing an event on the transport?

**Comment by nils-ohlmeier** [comment]
I guess the assumption so far was always that in WebRTC the application logic should know that it initiated an ICE restart. If the JS in browser needs to know this without being informed by the application logic, then I'm currently not aware of an easy way to get that information. Although I would assume that one an event after the fact is not that useful at all. I would assume that the JS would want to learn about this before applying the remote SDP?

**Comment by fippo** [comment]
> Although I would assume that one an event after the fact is not that useful at all. I would assume that the JS would want to learn about this before applying the remote SDP?

That depends on "when" after the fact. In the case I was looking at I was keeping some ice-related state and not resetting it when the remote end did an ice restart. Knowing this before processing any new local candidates would have been sufficient.

Another indicator: icegatheringstatechange fires with a new state of gathering after createAnswer + SLD. Probably covered by https://w3c.github.io/webrtc-pc/#rtcicetransport

**Comment by aboba** [comment]
@fippo To determine that an ICE restart occurred after calling SRD, `getRemoteParameters()` should do the job. If you want an event, `icegatheringstatechange` will fire with a new state of `gathering`  (and `statechange` with a new state of `new`) after SRD.

**Comment by fippo** [comment]
That sounds reasonable. Now I'll go and pester vendors to do so.
Thanks you @aboba!
