### ISSUE TITLE
Unable to figure out which receivers are "active".

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#1920]
Based on discussions at #1890, we are unable to figure out which receivers are "active" or not after setRemoteDescription().
```
1. const offer = await caller.createOffer();
2. await caller.setLocalDescription(offer);
3. await callee.setRemoteDescription(offer);
4. const answer = await callee.createAnswer();
5. await callee.setLocalDescription(answer);
6. await caller.setRemoteDescription(answer);
```
The recever's currentDirection is updated at step 5 (half-way through the answer). Likely the application would like to know at 3 when the ontrack events fire.

Today the application is forced to piece together from ontrack and other events what the state of the receivers really are. It's confusing having a pc with a set of receivers and not be able to figure out what their state are without wiring up events and listening to history.

We no longer support getRemoteStreams() but it should be possible to do the equivalent, i.e. "get active receivers".

**Comment by henbos** [comment]
@alvestrand at https://github.com/w3c/webrtc-pc/issues/1890#issuecomment-401280500 asked:
> A good question wrt "what are the active receivers" is "why do you want to know?".

Active is the equivalent to what has been offered, it's the stuff you wire up to your video element or the tracks you filter out from getStats(). You rarely ever care about inactive receivers, getting the complete set of transceivers is more useful for debugging, high control of SDP and making sure you were able to achieve that early media by reusing offered ones. getReceivers() for basic use cases is muddied with a bunch of objects most people probably wouldn't know why they should care about.

That said this info is available if you have access to the history of ontrack events firing, it's just not easily accessible.

**Comment by alvestrand** [comment]
A track is muted when it is created. https://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtpreceiver
It isn't unmuted until it gets data. https://w3c.github.io/webrtc-pc/#mediastreamtrack-network-use

Seems "active", the way you describe it, is more like [[Receptive]] than anything else. Then we should expose that.
(BTW, I think [[Receptive]] shoud be a receiver property. It's going to be useful without transceivers.)

**Comment by aboba** [comment]
`RTCRtpTransceiver.currentDirection` seems like it contains the needed information, but it is awkward to obtain unless the developer has built the necessary infrastructure.

**Comment by henbos** [comment]
@aboba `currentDirection` would have been what you want except this is not set when you set the offer with `setRemoteDescription()`, rather it is set half-way through the answer (`setLocalDescription(answer)`). This is unlike the `ontrack` events, the legacy APIs and as far as I understand something you don't event have to do in order to receive early media.
```
let transceiver = pc.addTransceiver('audio');
// O/A cycle; we are offering to receive
await pc.setRemoteDescription(offer);
// Early media is possible, and [[Receptive]] true,
// but transceiver.currentDirection is still null
await pc.setLocalDescription(await pc.createAnswer());
// Now transceiver.currentDirection is updated
```

@alvestrand `[[Receptive]]` sounds more like it, though it is set at `setLocalDescription()` so a receiver is said to be receptive if we are prepared to offer and only becomes non-receptive when we `setRemoteDescription()`. Meaning:
```
let transceiver = pc.addTransceiver('audio');
await pc.setLocalDescription(await pc.createOffer());
// transceiver.[[Receptive]] is true
```

It would seem strange to get an "active receiver" every time you do `addTrack()`, even if it's never used.

**Comment by henbos** [comment]
`[[FiredDirection]]` might do the trick, I have to check the spec.

**Comment by henbos** [comment]
Is the reason we set `currentDirection` ”late” - in the SLD(answer) as opposed to the SRD(offer) - because we want to give the client an opportunity to reject the transceiver?

Two proposals and a question:

1. Is there any harm to set the `currentDirection` at SRD(offer) too? It can always be overridden at SRD(answer) if the client wants to do that. A small tweak would allow `currentDirection` to reflect if it is "active" or not.

2. Otherwise, add `isReceiving` to receiver which is essentially set to (currentDirection == 'sendrecv' || currentDirection == 'recvonly') except we also set it to true at SRD(offer) when the remote side has offered to send us something on that receiver, but before we have set the answer to make that decision final.

Question:

Is the receiver able to receive as soon as you do SRD(offer), or will receiving not happen until later? At SLD(answer)? When the answer has been signaled to the remote endpoint?

**Comment by henbos** [comment]
Answer to my question above:

> Is the receiver able to receive as soon as you do SRD(offer), or will receiving not happen until later? At SLD(answer)? When the answer has been signaled to the remote endpoint?

For the answerer, according to [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24) 4.1.9, transmission does not start until SLD(answer). Here's the relevant quote:

> If setRemoteDescription was previously called with an offer, and
> setLocalDescription is called with an answer (provisional or final),
> and the media directions are compatible, and media is available to
> send, this will result in the starting of media transmission.

And for the offerer, transmission does not start until SRD(answer):

> If setLocalDescription was previously called with an offer, and
> setRemoteDescription is called with an answer (provisional or final),
> and the media directions are compatible, and media is available to
> send, this will result in the starting of media transmission.

At this point the full offer-answer cycle has occurred.

That means `isReceiving` would be misleading name. It's more like "sending is on offer, will receive if you complete the O/A without rejecting".
(Side-note: so "early media" only applies answerer -> offerer, not offerer -> answerer?)

**Comment by henbos** [comment]
To summarize:
- [[Direction]] is whatever we want to negotiate. This does not work for either offerer or answerer because the notion of "active" implies some negotiation has taken place.
- [[CurrentDirection]] is defined as _the last applied answer_. This works for the offerer, but not the answerer until answerer does SLD(answer). The notion of "active" includes the "ontrack"-transceivers, but SLD(answer) happens after "ontrack".
- [[FiredDirection]] is defined as the last applied SDP direction, regardless if it is an offer or answer. This works for the answerer, but for the offerer this would include non-"ontrack"-transceivers that have not been confirmed by the remote endpoint yet.

This gets trickier. For early media, a receiver might become "active" either by applying a remote description, or by early media arriving to unmute the track.

**Proposal**

I think if _any_ of the following is true the receiver is "active":
- `transceiver.currentDirection == 'sendrecv' || transceiver.currentDirection == 'recvonly'`: This covers any case where answer has been applied (such as when we are in a stable state, or when we have setLocalDescription(answer) and rejected transceivers that were previously offered by the remote endpoint).
- `transceiver.receiver.track.muted == false`: This covers case where media has arrived, even if answer has not been applied yet, such as when receiving _early media_ from the answerer to the offerer.
- `pc.signalingState == 'have-remote-offer' && (transceiver.[[FiredDirection]] == 'sendrecv' || transceiver.[[FiredDirection]] == 'recvonly')`: This covers "ontrack"-transceivers that were fired by setRemoteDescription(offer), but whose currentDirection does not reflect this because we have not done setLocalDescription(answer) yet.

We should add:
```
partial interface RTCRtpReceiver {
    readonly attribute boolean isActive;
}
```
That is defined as any of the above criteria being true. This is not applicable to ORTC since it is dependent on RTCPeerConnection and the state of SDP offer/answer.

**Comment by jan-ivar** [comment]
> (Side-note: so "early media" only applies answerer -> offerer, not offerer -> answerer?)

I believe so. An answerer can send media in parallel with its answer (from [example](http://w3c.github.io/webrtc-pc/#peer-to-peer-example-with-media-before-signaling)). So early media reception is only a thing on the offerer side, where `tranceiver.direction` already tells you which receivers you can expect reception on.

> await pc.setRemoteDescription(offer);
// Early media is possible, and [[Receptive]] true,
// but transceiver.currentDirection is still null

This is the answerer side, where early media can't happen, and reception doesn't start—i.e. [[Receptive]] isn't true—until SLD(answer).

> [[FiredDirection]] is defined as the last applied SDP direction, regardless if it is an offer or answer. This works for the answerer, but for the offerer this would include non-"ontrack"-transceivers that have not been confirmed by the remote endpoint yet.

I don't think that's right. [[FiredDirection]] is only set in SRD(offer) and SRD(answer) where events are fired. It specifically tracks the direction we've fired events from.

> isActive

Taking a step back, symmetrically, answerer-side reception starts after SLD(answer), and offerer-side reception starts either at the same time or after SRD(answer). I.e. **reception starts after answers.**

The asymmetry is that while offerer-side events fire in SRD(**answer**) which makes sense, answerer-side events fire early in SRD(offer), ***not*** SLD(**answer**), which does not make sense.

In hindsight, a mistake. I believe the only reason we fire events in SRD(offer) is because `track.stop()` was the initial API for rejecting incoming media many moons ago, so you needed the tracks to reject. That is no longer the case, but we may be stuck with it.

The last piece of this puzzle is that we can now [defer playback until `unmute`](https://blog.mozilla.org/webrtc/when-should-you-display-incoming-webrtc-video/):
```js
pc.ontrack = e => e.track.onunmute = () => video.srcObject = e.streams[0];
```

So I think it's a pilot error to expect to make any decisions about reception before SLD(answer).

... and the only thing people should be doing before SLD(answer) is reject things (by either modifying `tranceiver.direction` or calling `transceiver.stop()`.

**Comment by henbos** [comment]
> > (Side-note: so "early media" only applies answerer -> offerer, not offerer -> answerer?)
> 
> I believe so. An answerer can send media in parallel with its answer (from example). So early media reception is only a thing on the offerer side, where tranceiver.direction already tells you which receivers you can expect reception on.

Hmm, but transceiver.[[Receiver]].[[Receiver[Rtcp]Transport]] is not set until SRD(answer)? Doesn't sound like media is able to arrive any earlier than always creating new transceivers? Is "early media" entirely hypothetical?

> [...] I.e. reception starts after answers.
> 
> The asymmetry is that while offerer-side events fire in SRD(answer) which makes sense, answerer-side events fire early in SRD(offer), not SLD(answer), which does not make sense.
> 
> In hindsight, a mistake. I believe the only reason we fire events in SRD(offer) is because track.stop() was the initial API for rejecting incoming media many moons ago, so you needed the tracks to reject. That is no longer the case, but we may be stuck with it.
> 
> [...]
> 
> ... and the only thing people should be doing before SLD(answer) is reject things (by either modifying tranceiver.direction or calling transceiver.stop().

Thanks for the enlightening comments. I'm no longer sure "isActive" is needed. This all is surprisingly complicated though.

**Comment by jan-ivar** [comment]
> Hmm, but transceiver.[[Receiver]].[[Receiver[Rtcp]Transport]] is not set until SRD(answer)?

FWIW [[ReceiverTransport]] appears set in both SLD(offer) and again SRD(answer), but dtls yeah.

> Doesn't sound like media is able to arrive any earlier than always creating new transceivers?

I've been told early media can happen on renegotiation or after pranswer, when dtls is already up.

> Is "early media" entirely hypothetical?

Firefox does not implement it yet, if that's what you're asking.

> I'm no longer sure "isActive" is needed. This all is surprisingly complicated though.

A bit. TL;DR: if users wait for SLD(answer) they should be fine and can look at `currentDirection`.

**Comment by henbos** [comment]
Yeah, "if you care about rejecting transceivers or wiring up tracks early, listen to ontrack, otherwise wait for their state to be finalized at SLD(answer)". Closing this then.
