### ISSUE TITLE
Move Isolated Streams from [[WEBRTC]] to [[WEBRTC-IDENTITY]]

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1929]
The suggestion has been raised that "Isolated streams" belongs in the identity spec, not in the main spec.
All the references in the main doc after applying #1915 seem to be within the section, so this appears to be an easy editorial task.

Since we said the opposite thing at the interim, I thought I should raise it as an issue before doing it.
Assigning @martinthomson for comment.

**Comment by martinthomson** [comment]
I suggested that we do this, so I'm OK with it.

If you kept it, it might be a risk to having two interoperable implementations of WebRTC, because you can't really do isolated streams without identity.
