### ISSUE TITLE
Should / does the order of replaceTrack and direction matter?

### ISSUE THREAD

**Issue by itsthetaste** [w3c/webrtc-pc#1933]
I've been debugging an issue where in Firefox 61+ I am unable to hear the audio being sent from firefox to other peers.

I had my code setup like in the blog @jan-ivar had posted last year, specifically the update for firefox 59, which forced me to use transcievers. https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/, where by, I created an inactive transceivers like;

`var audioTransceiver = RTCPeerConnection.addTransceiver("audio", { direction : 'inactive'}); `

then when wanting to send my mic, I was calling;

```
audioTransceiver.sender.replaceTrack(track);
audioTransceiver.direction = "sendonly";
```

and then negotiating.

I notice that the warm start up example (https://w3c.github.io/webrtc-pc/#advanced-peer-to-peer-example-with-warm-up) has the direction change before the replaceTrack as does the new(ish) blog post by @jan-ivar (https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/).

If I change my js to be this way around, then now, Firefox 61+ thinks my track is enabled and doesn't send silence.  But, the order doesn't seem to matter to my camera and I can get it to work either way.

So, should / does the order matter?

**Comment by jan-ivar** [comment]
The order should not matter. I'm [able to reproduce this](https://jsfiddle.net/jib1/v7xrf6ut/
) in the latest Firefox Nightly. The problem only happens the first time. To work around this, repeat the `replaceTrack` after changing direction.

Please file a bug on Firefox. And thanks for finding this!

**Comment by itsthetaste** [comment]
Thanks, I'll post one now.

**Comment by jan-ivar** [comment]
[Bug 1475884](https://bugzilla.mozilla.org/show_bug.cgi?id=1475884) for reference.
