### ISSUE TITLE
Cannot update associated remote streams for a track once added

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-pc#1937]
In the RTCRtpSender we have [setStream](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-setstreams) which will changes the stream IDs inserted into the SDP.

On the remote side, the algorithm **set the associated remote streams** is only run in the **process the addition of a remote track** algorithm.

Should `setRemoteDescription` always **set the associated remote streams** for each media section, regardless if the track was added or not?

**Comment by alvestrand** [comment]
I think it should.

**Comment by fippo** [comment]
how does an application learn that the other side updated the associated streams?

**Comment by alvestrand** [comment]
either it can always poll after a setremotedescription() succeeds, or we can reinvent onaddstream

**Comment by henbos** [comment]
replaceTrack() does not require re-negotiation, but setStream() does. But setStreams() was added to complement replaceTrack(), meaning the use-case that was in mind was to do both things, but doing both things would mean half of the operation happens immediately and the other half happens after an exchange. This seems awkward?

This now may lead to more events and complexity. What's the compelling use case for changing streams?

If we truly want to repurpose a transceiver with a renegotiation (same thing as adding a new transceiver except we are done with the old usage and don't want to waste m= sections) then this might be achievable with an setter-API that on the other endpoint ends up with processing the removal of the old stuff and then firing another ontrack with the same transceiver but the new track and streams.

**Comment by stefhak** [comment]
I share @henbos concern regarding complexity. It seems to me that if the app wants to control/change the stream associations for a track, it could use the PeerConnection with just tracks (not supplying any streams), and signal the stream associations (and changes thereof) separately.

I may be overlooking something!

**Comment by henbos** [comment]
Fixed by https://github.com/w3c/webrtc-pc/pull/1947
