### ISSUE TITLE
Promise should be rejected if transceiver is stopped

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1938]
Looking at [replaceTrack](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack), it seems to me that if transceiver has been stopped when reaching the point of `Queue a task that runs the following steps` (6.4.4 in [replaceTrack](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack)) the promise should be rejected with an `InvalidStateError`. Came up when looking at #1389.

**Comment by jan-ivar** [comment]
Currently it aborts with neither resolving nor rejecting the promise. This is consistent with the other async methods in our spec. Last time we decided on this was in https://github.com/w3c/webrtc-pc/issues/150#issuecomment-152333247.

**Comment by jan-ivar** [comment]
I guess the difference is that stopping isn't an entirely deterministic event like close is.

**Comment by stefhak** [comment]
I guess I had forgotten about the discussion in #150. Maybe we should just leave it as it is? 
I reacted on that if the Transceiver is stopped when the script does replaceTrack a rejected promise is returned, but if the Transceiver is not stopped at that point in time, but is once the actual track replace is to happen then it silently fails IIUC.

**Comment by stefhak** [comment]
Closing per the discussion above.
