### ISSUE TITLE
setLocal and setRemote wrong

### ISSUE THREAD

**Issue by boldt** [w3c/webrtc-pc#1950]
In [subsection 4.3.1 RTCSignalingState Enum](https://www.w3.org/TR/webrtc/#rtcsignalingstate-enum) you write:

> Caller transition:
>
>        new RTCPeerConnection(): stable
>        setLocal(offer): have-local-offer
>        setRemote(pranswer): have-remote-pranswer
>        setRemote(answer): stable
>
> Callee transition:
>
>        new RTCPeerConnection(): stable
>        setRemote(offer): have-remote-offer
>        setLocal(pranswer): have-local-pranswer
>        setLocal(answer): stable

`setLocal` must be `setLocalDescription` and `setRemote` must be `setRemoteDescription`.
The same goes for the Figure in the same subsection.

**Comment by jan-ivar** [comment]
Correct. Maybe the shorter names were probably used for brevity in the diagram?
