### ISSUE TITLE
Failed to execute 'insertDTMF' on 'RTCDTMFSender': The 'canInsertDTMF' attribute is false: this sender cannot send DTMF.

### ISSUE THREAD

**Issue by jiaguolin** [w3c/webrtc-pc#1958]
```        
           let peerconnection = this.session.connection;
            var dtmfSender = peerconnection.getSenders()[0].dtmf;
            if (dtmfSender) {
                var duration = 500;
                dtmfSender.insertDTMF('1234', 400, 50);
            } else {
               log.error("DTMF function not available");
            }
```

I'm use jssip.but jssip send DTMF is sip info 

My server does not handle DTMF for sip INFO, but I will use the above method to relax DTMF and I will get an error.

`Failed to execute 'insertDTMF' on 'RTCDTMFSender': The 'canInsertDTMF' attribute is false: this sender cannot send DTMF.`

**Comment by fippo** [comment]
What is the specification issue here?

You might want to compare to https://webrtc.github.io/samples/src/content/peerconnection/dtmf/, debug what is causing canInsertDTMF to be false (e.g. dtmf is not negotiated) and then fix the bug where appropriate.

**Comment by aboba** [comment]
@jiaguolin  canInsertDTMF false indicates that you cannot send DTMF, so you should check it first.
PR https://github.com/w3c/webrtc-pc/pull/1957  elucidates the reasons why canInsertDTMF can be false, such as: 

1. sender does not have a track or track.kind isn't "audio"
2. DTMF codec ("audio/telephone-event") is not negotiated
3. pc.currentDirection is not "sendrecv" or "sendonly"
