### ISSUE TITLE
Gatherer state vs gathering state

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-pc#1959]
The RTCIceTransport has an attribute `gatheringState` of type `RTCIceGathererState`. It also fires an event of type `icegatheringstatechange`.

Would it make sense to use the same name for the enum and the attribute/event type?

Proposal:
* Change `gatheringState` to `gathererState`
* Change `icegatheringstatechange` to `icegathererstatechange` (and associated event handler attribute)

**Comment by steveanton** [comment]
I see now that we have both enums RTCIceGatheringState and RTCIceGathererState. The former aggregating the latter over possibly many ICE transports in a PeerConnection.

**Comment by fippo** [comment]
that sounds like it came from ORTC. @aboba ^^

**Comment by aboba** [comment]
@steveanton Within the `RTCIceTransport` object, we have `RTCIceGathererState` `gatheringState` to express the gathering state of an individual `RTCIceTransport`, and an `ongatheringstatechange` EventHandler for when the state changes. Within the `RTCPeerConnection` we have `RTCIceGatheringState` `iceGatheringState` which represents the aggregate gathering state, and an `onicegatheringstatechange` EventHandler for when the state changes.  While the enum values are the same, the meanings are different .  In ORTC's `RTCIceGatherer`, we have `RTCIceGathererState` `state` and an `onstatechange` EventHandler.
