### ISSUE TITLE
Effect of RTCRtpSendParameters on Simulcast

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#1964]
The effect of `RTCRtpSendParameters` on simulcast is under-specified.  Some questions: 

1. Is congestion control affected by the value of `RTCRtpSendParameters.degradationPreference`? For example, if `degradationPreference` = `maintain-resolution` does this imply that framerate is lowered before higher resolution simulcast layers are dropped? Does the opposite happen if `degradationPreference` has the value `maintain-framerate`?

2. What effect does `parameters.encodings[].priority` have?  Do the values influence which simulcast layers are dropped? 

3. What effect does `parameters.encodings[].maxBitrate` have?  Do the values of `parameters.encodings[].maxBitrate` influence which simulcast layers are dropped?  If there is insufficient bandwidth, is bandwidth allocated to the layers in proportion to the values of `maxBitrate`? 

4. What effect does `parameters.encodings[].maxFramerate` have? Do the values of `parameters.encodings[].maxFramerate` influence which simulcast layers are dropped?  If there is insufficient bandwidth, is bandwidth allocated to the layers in proportion to the values of `maxFramerate`?

**Comment by alvestrand** [comment]
For [2], the priority definition in -transport gives the answer: If both a priority "low" and a priority "high" stream is available, and neither can fit within the bandwidth set by congestion control, one is supposed to send 4 bytes from the "high" priority stream for every byte sent from the "low" priority stream (chunked into packets, of course). Neither stream should be fully dropped, unless it's impossible to produce an useful stream at that bandwidth that satisfies the configuration constraints..

I think the simulcast document needs to have an introduction/terminology section that defines the words used to describe sending, reconfiguring and dropping of simulcast layers. If we can get a straightforward principle established that says "the sender platform keeps a list of simulcast streams, with the most easily sent stream being at the top and the one that requires most resources to send at the bottom; when limitations such as bandwidth restrictions make the bottom stream have no extra value, the platform is allowed to stop sending the stream". Or something like that.

**Comment by shampson** [comment]
> If both a priority "low" and a priority "high" stream is available, and neither can fit within the bandwidth set by congestion control, one is supposed to send 4 bytes from the "high" priority stream for every byte sent from the "low" priority 

Currently this is done above the minimum of each stream. So after the minimum amount for a stream is satisfied, the bandwidth is allocated proportionally. But this is specific to streams (RtpSenders), not for simulcast layers. 

As far as dropping a stream/layer I don't think it makes sense necessarily to drop the stream with a priority of low. As Taylor pointed out in [issue 1625](https://github.com/w3c/webrtc-pc/issues/1625), the _priority_ is different than the [networkPriority](https://w3c.github.io/webrtc-dscp-exp/#networkPriority). The common case here would be that you want to keep the low quality layer and drop higher quality layers first. For streams this is dropping audio before video, but for layers maybe this might mean keeping a thumbnail while dropping your HD layer.

For [3] I don't think maxBitrate should affect how layers are dropped or how bandwidth is allocated. Shouldn't they be dropped based on (a hidden) minimum configured bitrate? Doesn't the proportional allocation happen with the priority?

**Comment by aboba** [comment]
@shampson @alvestrand PR https://github.com/w3c/webrtc-pc/pull/1995 recommends moving priority from encoding to sending parameters.  This would effectively remove priority as a consideration in simulcast congestion control.  I would also agree that neither maxBitrate nor maxFramerate should influence which layers are dropped. 

There has been discussion of potentially using the ordering of the layers to determine which ones are dropped when congestion occurs.   That would make sense if there are common scenarios where the typical approach (dropping higher quality layers first) is inadequate.   Personally, I have never encountered a scenario where it made sense to drop a lower quality layer first automaticallly, although there may be times when an SFU might want to tell the user agent to stop sending a lower quality layer (e.g. if all endpoints were receiving high quality so that the low quality stream wasn't being forwarded).

**Comment by aboba** [comment]
Closing this due to merged PRs.
