### ISSUE TITLE
Properly define origin (and handling thereof) for PeerConnection

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1969]
See https://github.com/w3c/webrtc-pc/pull/1966#discussion_r211494617

**Comment by jan-ivar** [comment]
That comment link seems broken.

**Comment by stefhak** [comment]
Still, if I go to that comment and select "Copy URL", https://github.com/w3c/webrtc-pc/pull/1966#discussion_r211494217 is what I get. Anyway, it's this comment from @annevk (in context of 
```
 <p><a>Fire an event</a> named <code><a>message</a></code> using the 
          <code title="event-datachannel-message"><a>message</a></code> interface
          with the <code>origin</code> attribute initialized
```
):
"This seems too vague. You need to define that RTCPeerConnection holds a document in a slot somewhere and use that concept here. And define how the slot gets filled when creating RTCPeerConnection."

**Comment by jan-ivar** [comment]
Thanks for quoting it. Odd, a github bug?

Makes sense. Revisiting this made me question why we bother with filling in the `origin` field at all, but then I see websocket does it, so I guess that's why.
