### ISSUE TITLE
Make possible to select TURN allocation address family (to avoid IPv6 confusion)

### ISSUE THREAD

**Issue by misi** [w3c/webrtc-pc#1972]
Make possible to set TURN client the REQUESTED-ADDRESS-FAMILY attribute to avoid confusion.

WebRTC implementations don't send REQUESTED-ADDRESS-FAMILY STUN/TURN attribute.
https://tools.ietf.org/html/rfc6156#section-4.1.1

```
If the REQUESTED-ADDRESS-FAMILY attribute is absent, the server MUST
allocate an IPv4-relayed transport address for the TURN client.
```
This way TURN servers will allocate IPv4 address even if the Allocation
request sent on IPv6 connection to the TURN server.

This may cause confusion in developers, 
and so we should make it configurable in WebRTC API.

**The proposed values of the new knob on turnserver**:

- not send any REQUESTED-ADDRESS-FAMILY (Actual behavior)
- Request IPv4 family
- Request IPv6 family
- Dual allocation IPv4 and IPv6 in one shot.

**Comment by alvestrand** [comment]
Is dual allocation possible given RFC 6156 (only one Allocate per request)?
Or do you propose giving a value of the tuning knob that will send two Allocate requests?

**Comment by alvestrand** [comment]
Spec intention was that we should request both IPv4 and IPv6 if we have both available. But it's unclear where it's specified that we should do that.

**Comment by aboba** [comment]
I think this is a protocol issue (and possibly an implementation issue), not a WebRTC API issue.

**Comment by misi** [comment]
@alvestrand
AFAIU it could happen both way.
- It could happen in one request, or one socket. It is implemented in coTURN in both way:
See: https://tools.ietf.org/html/draft-martinsen-tram-ssoda-01
- Or it could happen with two allocation as you mentioned.

I agree with @aboba, that is implementation detail, we should allow both..
IMHO we should focus only about only on Dual allocation from the browser point of view.

**Comment by misi** [comment]
See also ADDITIONAL-ADDRESS-FAMILY in https://tools.ietf.org/html/draft-ietf-tram-turnbis-20#section-16.11

**Comment by misi** [comment]
@alvestrand @aboba  
PR exists #2018

**Comment by misi** [comment]
@aboba You tagged this issue as enhancment. I want argue that it is much more regression then a new feature. Please remove this tag..

Lack of it will cause confusion why a IPv6 TURN relay allocates IPv4 relay address instead of IPv6  And why a user can't allocate in webrtc 1.0 an IPv6 relay address on TURN servers. If you don't change actual webrtc standard then users can only allocate IPv4 relay address, even though they communicate with TURN server on IPv6.

**Comment by dontcallmedom** [comment]
#2018 was closed saying there was no consensus to add this; does that mean this issue should be closed as well @alvestrand ?

**Comment by alvestrand** [comment]
Since #2018 had no consensus to add, I think this one has "no consensus to solve".
