### ISSUE TITLE
RTCDataChannel.bufferedAmountLowThreshold not handled correctly

### ISSUE THREAD

**Issue by ErikHellman** [w3c/webrtc-pc#1974]
If you assign a negative value to the `bufferedAmountLowThreshold` of a `RTCDataChannel`, it will be assigned an overflow value.

A more reasonable way of handling it is described in the [design principles document](https://w3ctag.github.io/design-principles/#numeric-types);

> Any nonnegative JavaScript number in the integer-representable range, throwing a TypeError outside the range and rounding inside of it

**Comment by alvestrand** [comment]
It would be more correct to say that "a more reasonable way" is described in the design principles document. It's correct as specified, which doesn't mean that it's reasonable.

**Comment by lgrahl** [comment]
I would definitely upvote changing that but we shouldn't stop there. In my opinion, every settable u8, u16, u32, u64 (oh wait, that's too much for JS to handle, I forgot) should be strict (with `[EnforceRange]`).

**Comment by lgrahl** [comment]
I think we should have `[EnforceRange]` for attributes of `RTCDataChannelInit`, too. Is that possible with WebIDL for an interface?
