### ISSUE TITLE
createAnswer conflicted about whether it takes an options argument or not

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#199]
In spite of its WebIDL showing no such arg, createAnswer says:
"The options parameter may be supplied to provide additional control over the generated answer."

I would add a patch to remove mention of options, except I hear that rumors of its demise are overstated?

**Comment by juberti** [comment]
See PR #171

**Comment by fluffy** [comment]
+1 on it needs an option

**Comment by stefhak** [comment]
Closing, #171 has landed and defines options for createAnswer.
