### ISSUE TITLE
Define what happens if maxFramerate is 0?

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1992]
I don't think we've defined what should happen. OTOH, it seems that the options for the UA are not that many. The only case I can think of when different interpretations could be made would be for the case the UA is about to transmit, or has started to transmit, a frame when `setParameters` is called with 'maxFramerate` being `0.0`. This could be a big one (I-frame), and the options would be to either transmit that frame or abort before finalizing the transmission. Being a corner case means that perhaps we can just leave it as is?

**Comment by alvestrand** [comment]
we seem to have two options:
- Max framerate = 0 means "send one frame and then stop" (freeze picture)
- Max framerate = 0 is silly, reject it.
Thoughts?

**Comment by alvestrand** [comment]
Suggested alternative #1.
