### ISSUE TITLE
Need to define what to do on very low bitrates

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2003]
If bitrate is so low that it's unreasonable (doesn't allow sending a frame in a reasonable time), is the implementation allowed to emit a frame at all, is it allowed to exceed the bitrate over a short interval, or should it reject the parameter?

**Comment by fippo** [comment]
and what if the bitrate is reasonable for the track currently attached to the sender (says 320x240@15fps) and then that track is replaced with a 4k@30fps screenshare?

**Comment by alvestrand** [comment]
Agree that the configured bitrate (and the bitrate from BWE) should never be exceeded when averaged over a long enough period. (But what's long enough?)
When sending a single frame, it makes sense to me to send it as fast as possible within the constraints given by BWE, no matter what the maxBitrate value says - but then it may take a long time until we send the next one.

**Comment by shampson** [comment]
A relevant webrtc bug:
https://bugs.chromium.org/p/webrtc/issues/detail?id=9141

**Comment by Orphis** [comment]
Regarding this issue, should we treat maxBitrate == 0 the same as maxFramerate == 0 for consistency?
Both could be equivalent to setting active to false.
