### ISSUE TITLE
Matching of origin for RTCCertificate objects is unclear

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2011]
The spec says "If the [[Origin]] internal slot of the certificate does not match the current origin, throw an InvalidAccessError"

This wording is unclear to me.
One possibility would be to refer to the "same origin" algorithm as defined in https://html.spec.whatwg.org/multipage/origin.html#same-origin

**Comment by alvestrand** [comment]
Let's just use the same-origin algorithm.

**Comment by youennf** [comment]
Submitted PR https://github.com/w3c/webrtc-pc/pull/2041

**Comment by youennf** [comment]
This PR is somehow covered by https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCCertificate-postMessage.html

**Comment by youennf** [comment]
Fixed by PR #2041
