### ISSUE TITLE
Valid RID values mismatch between specs

### ISSUE THREAD

**Issue by Orphis** [w3c/webrtc-pc#2013]
According to WebRTC's addTransceiver(), the RID format is:

> Verify that each rid value in sendEncodings is composed only of alphanumeric characters (a-z, A-Z, 0-9) up to a maximum of 16 characters.

But according to https://tools.ietf.org/html/draft-ietf-mmusic-rid-15 , we have:

> rid-id            = 1*(alpha-numeric / "-" / "_")

Which is correct?

**Comment by aboba** [comment]
@orphis @hta I'd assume that the IETF specification takes precedence.  The ABNF has been stable for quite a while so I'm not sure how the specifications got out of sync.

**Comment by amithilbuch** [comment]
I would assume that IETF takes precedence, but i also found inconsistency in ietf.
According to: https://tools.ietf.org/html/draft-ietf-avtext-rid-09#section-3
   As with all SDES items, RtpStreamId and RepairedRtpStreamId are
   limited to a total of 255 octets in length.  RtpStreamId and
   RepairedStreamId are constrained to contain only alphanumeric
   characters.  For avoidance of doubt, the only allowed byte values for
   these IDs are decimal 48 through 57, 65 through 90, and 97 through
   122.

That draft has expired, but i haven't found a newer version.

**Comment by amithilbuch** [comment]
also found some firefox examples in related simulcast issues that show rids 'hi', 'med', 'low' so we should make sure not to restrict to anything less than 3 characters.

**Comment by jan-ivar** [comment]
What's the effective rid length limit here now? We're trying to fix [web-platform-tests/wptwebrtc/RTCPeerConnection-addTransceiver.https.html](https://github.com/web-platform-tests/wpt/blob/ffbaf43aa0253856f14d7343e49b0ba5d1b50a26/webrtc/RTCPeerConnection-addTransceiver.https.html#L345) which still says 16 bytes.

**Comment by amithilbuch** [comment]
i think it needs to fit in a header extension, so i believe 16 is the right number.
Implementations and applications should prefer smaller values (like a single byte) to reduce packet size.

**Comment by jan-ivar** [comment]
@amithilbuch Thanks, can you help me locate the spec support for that? Just making sure I'm not missing it.

**Comment by amithilbuch** [comment]
we've actually decided not to formally specify it and refer to the specification in ietf.
> Verify that each rid value in sendEncodings conforms to the grammar specified in Section 10 of
> [MMUSIC-RID]. If one of the RIDs does not meet these requirements, throw a TypeError.
so it's referring to this:
https://tools.ietf.org/html/draft-ietf-mmusic-rid-15#section-10

it's out of date and might need a revision because it currently indicates a single character.

**Comment by jan-ivar** [comment]
That's a normative reference, so that seems problematic if we want to allow 3 or 16 characters. Do we need to open an issue?

**Comment by amithilbuch** [comment]
@jan-ivar can you ask Mr. Roach what the original intent was? and if an upcoming draft is due that addresses this? if not, then i guess we should file an issue on the ietf spec.

**Comment by jan-ivar** [comment]
@adamroach thoughts?
