### ISSUE TITLE
Start using new issue labels

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2019]
Suggested labels:

- "WebRTC 1.0"
- "Post WebRTC 1.0"
- "Has WPT issue"

**Comment by youennf** [comment]
WebRTC 1.0/Post WebRTC 1.0 sound great to me.
I guess the goal would be to iterate through all existing issues as well as any newly filed issue.

I am less sure about the meaning of 'Has WPT issue'.
Do we want to flag PRs that have missing test coverage?
Do we want for every PRs (or issue triggering a PR) to have some comments describing the testing status?

**Comment by henbos** [comment]
We want to ensure test coverage for everything, but I don't think we should block a PR from landing because the test coverage has not been added yet, but we could block it from landing unless there is a corresponding WPT issue to add coverage for it.

We could assign WPT issues as part of issue duties to make sure that list does not grow over time.

**Comment by henbos** [comment]
In terms of ensuring ourselves we have test coverage such a label would make it clear what has or has not been covered by WPT issues - at least going forward.

**Comment by aboba** [comment]
"Extension" is the label we have been using for things that are beyond the scope of WebRTC 1.0.  Other issues are assumed to relate to WebRTC 1.0 (since they are filed in the webrtc-pc repository).

**Comment by youennf** [comment]
There is also "LATER" that might be similar to these two.
It is not clear whether "Question" is in or out of scope(maybe these need investigation to understand whether 1.0 or not). Ditto for "Editorial".

Mentioning clearly WebRTC 1.0 (or WebRTC 1.0 PR) might make things clearer and it would be nice to know which are the mandatory issue to close for PR.

Quickly going through the list:
#2012 seems like an improvement.
#1979 could be marked post 1.0?
#1918 might be "post 1.0" as well
#1742/#1727 might require coordination with other WGs (might take time). It is not clear whether this is mandatory for WebRTC 1.0 or not. From the lack of labels, I would think it is mandatory to fix this.

**Comment by alvestrand** [comment]
I don't like "post 1.0" as a label - I'd prefer "WebRTC NV". Always focus on where you're going, not on where you've been...

**Comment by alvestrand** [comment]
Change label "enhancement" to "WebRTC NV".

**Comment by henbos** [comment]
@henbos to put a document somewhere (README file?) to say what to do with the labels. We discussed: "Needs Test" for things needing non-WPT tests, filing issues on WPT for things that needs WPT tests, and using a "WebRTC 1.0" and "WebRTC NV"
