### ISSUE TITLE
Should peerIdentity mechanism be moved to webrtc-identity?

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2021]
webrtc-pc has some peerIdentity related text:
- peerIdentity member in RTCConfiguration dictionary
- peerIdentity member use in RTCPeerConnection set configuration, setRemoteDescription
- isolated stream concept definition

We could define peerIdentity inside webrtc-identity and monkey patch set configuration, setRemoteDescription.
Ditto for addTrack step 10

**Comment by alvestrand** [comment]
Isolated streams concept is already in webrtc-identity: https://w3c.github.io/webrtc-identity/identity.html#isolated-media-streams. It's defined in webrtc-pc by reference to webrtc-identity.

**Comment by alvestrand** [comment]
Part of the split was that we would allow normative references in both directions between the specs. Monkey-patching the algorithms is a little more worrisome than just monkey-patching the dictionary (it's only the RTCConfiguration that has it as a member).
I'm in two minds.

**Comment by aboba** [comment]
Moving all  mentions of peerIdentity to the Identity specification would require readers of webrtc-pc to go back and forth between webrtc-pc and the Identity document in roughly half a dozen places. One of the reasons we did not split out simulcast is that this kind of split would make the document more difficult to read.  So this is not a change that is easy to make.
