### ISSUE TITLE
callback-based https://w3c.github.io/webrtc-pc/#method-extensions are not covered by WPT tests

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2022]
Looking at WPT webrtc tests, I do not find any testing for callback-based createOffer and addIceCandidate.
Are there already tests covering these somewhere?
It would be nice to add such WPT tests if not already covered.

**Comment by aboba** [comment]
addIceCandidate: https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCPeerConnection-addIceCandidate.html
createOffer: https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCPeerConnection-createOffer.html

**Comment by youennf** [comment]
These tests are testing the promise based createOffer/addIceCandidate.
I was trying to find tests for callback-based createOffer/addIceCandidate.
I will change the issue title to make it clear.

**Comment by youennf** [comment]
Edited the title and the initial comment for clarity

**Comment by aboba** [comment]
I believe the legacy APIs aren't in the WPT tests because they are documented rather than being considered part of the 1.0 CR.  WPT is therefore a conformance test based on the 1.0 CR rather than an application compatibility test suite.  To ensure that browsers can run legacy applications, there are more tests that would need to be added for things that are deprecated or have been removed entirely.

**Comment by youennf** [comment]
I am not exactly sure what is the exit CR criteria. AIUI, these legacy APIs are optional to implement but if implemented, MUST follow the spec. This makes me think that we need testing, but maybe not. It would be good to confirm one way or the other (@dontcallmedom maybe?).

We already have testing for some legacy APIs but not for callback based APIs. I also think that whatever the CR criteria is, WPT tests for things defined  in a spec are nice to have.

**Comment by dontcallmedom** [comment]
I agree with @youennf that these APIs should be tested given their description in the spec, possibly guarded by feature testing (i.e. only checking the valid behavior if the support of the callback version of the method can be detected in the browser under test).

**Comment by dontcallmedom** [comment]
should this issue be moved to https://github.com/web-platform-tests/wpt/issues? I'm assuming we'll be using [WPT webrtc issues](https://github.com/web-platform-tests/wpt/issues?q=is%3Aissue+is%3Aopen+callback+webrtc+label%3Awebrtc) as a source of ideas during the [WebRTC test hackathon](https://trac.ietf.org/trac/ietf/meeting/wiki/104hackathon)

**Comment by alvestrand** [comment]
Yes, I think we should move this to the WPT issue list (and we should find a procedure for going through that list on a regular basis).

**Comment by alvestrand** [comment]
Moved to WPT repo.
