### ISSUE TITLE
Should WPT webrtc folder be renamed to webrtc-pc

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2026]
It seems we should do the renaming for consistency with current WPT folder name policy.
A related question would be to decide whether to move some stats tests to webrtc-stats.

**Comment by jan-ivar** [comment]
FWIW we already have other inconsistencies, like `mediacapture-streams` for mediacapture-main... Are there any specific benefits?

**Comment by youennf** [comment]
I filed this issue when I wanted to run tests in http://w3c-test.org/tools/runner/index.html.
If you put webrtc in "Run tests under path", you end up running tests in webrtc, webrtc-identity, and webrtc-stats folders. This is nice but it would also be nice to have the possibility to just run 'webrtc' folder (which is what I actually wanted to do). Renaming would fix that. Clearly, this could also be fixed in WPT tools.

The renaming exercise was done elsewhere (XMLHttpRequest -> xhr) due to WhatWG spec template tooling I believe. This issue might pop up if we want to add links from the specs to WPT tests, which might be nice. Again, that issue might be solved in other ways.
I believe there are only minor incentives to change the name.

**Comment by jan-ivar** [comment]
Sounds reasonable to me. Would there be any fallout from renaming?

**Comment by youennf** [comment]
> Sounds reasonable to me. Would there be any fallout from renaming?

This might require some work in every browser to update their internal CI.
For instance, WebKit is currently marking some tests as flaky or skipped and we would need to update some configuration files with the correct path.

> Separately, I remember youenn saying that we should keep all of webrtc 1.0 well identified so that we can give higher priority on those. Getting stats tests corresponding to normative text in the webrtc 1.0 spec a separate folder to live in would go against that goal.

In theory, we should keep the tests testing getStats in WebRTC/webrtc-pc and the tests testing specific getStats fields in webrtc-stats. Currently they seem intertwined in RTC*-getStats.https.html.
Probably low priority.

**Comment by alvestrand** [comment]
It's a cost to every browser's setup, and a cost to every developer too.... seems good to do in theory, I worry about the cost/benefit tradeoff.
If we go for full consistency, we should move all of them.

**Comment by alvestrand** [comment]
@foolip can you help us guess what the cost is going to be?

**Comment by alvestrand** [comment]
@foolip can you help us guess what the cost is going to be?

**Comment by alvestrand** [comment]
@dontcallmedom ?
