### ISSUE TITLE
special-casing of a=msid:-

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#2027]
https://github.com/rtcweb-wg/jsep/issues/856 has some implications for webrtc-pc.

I think @henbos already identified the two places where this impacts things.
The spec says under set the associated remote streams to:
```
    For each MSID in msids, unless a MediaStream object has previously been created 
   with that id for this connection, create a MediaStream object with that id.
```
From setRemoteDescription when applying a remote description...
```
    If direction is "sendrecv" or "recvonly", let msids be a list of the MSIDs that the media
    description indicates transceiver.[[Receiver]].[[ReceiverTrack]] is to be associated with. 
   Otherwise, let msids be an empty list.
```

I *think* we can get away with changing only the first one (*). If JSEP passes the list of streams as ["-"] including the "no stream" we can special-case both that ("do not create a stream") and handle an empty list (legacy) by creating a "legacy" stream that encompasses all tracks. From what I can see, this is what [Firefox does](https://jsfiddle.net/5jd8Lz97/7/), even if it means the stream will have more than a single audio/video track.

(*)side-note: that text is slightly off as msid "forgets"; the slightly more correct thing to say is that if the receivers streams do not include a stream with that id, create one)

**Comment by henbos** [comment]
The legacy case (no msids so we create our own stream(s)) could be handled in at least two different ways:
- Create a stream that encompasses all tracks.
- Create a stream for each track.

I think Chrome does one new stream per track but I haven't checked if that is true.

**Comment by jan-ivar** [comment]
All we say is *"let* msids *be a list of the MSIDs that the media description* ***indicates*** *transceiver.[[Receiver]].[[ReceiverTrack]] is to be associated with. Otherwise, let* msids *be an empty list"*

*media description* = JSEP.

I think this is for JSEP to fix. I'll file an issue.

**Comment by alvestrand** [comment]
This shouldn't happen. I pushed on a private repo. Reopening.

**Comment by fippo** [comment]
This is going to be fixed in JSEP but I pledge a test for this which we can use to resolve this issue :-)

**Comment by henbos** [comment]
Wait, did the JSEP PRs not merge? I already implemented a fix for this in chromium...

**Comment by alvestrand** [comment]
Coincidentally, I also landed https://github.com/web-platform-tests/wpt/pull/14393 which adds a set of tests for MSID parsing (in protocol/msid-parse.html).
This was done in support of just-published https://tools.ietf.org/html/draft-ietf-mmusic-msid-17 which allows skipping the track in a=msid:

**Comment by dontcallmedom** [comment]
looks that this issue can be closed now?

**Comment by fippo** [comment]
Yes, the jsep issue has been merged on January 9th. Thanks Harald for writing a test!
