### ISSUE TITLE
Make RTCDtlsTransport.getRemoteCertificates asynchronous?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2034]
At the moment, RTCDtlsTransport.getRemoteCertificates is defined as synchronous.
After investigating:
a) Chrome's implementation [1]
b) the wpt.fyi status of the API [2]
I've concluded that:
1) it's not implemented by anyone
2) it's easier to implement it if it returns a promise

Is there any objection to make it a promise?

[1] https://cs.chromium.org/chromium/src/third_party/webrtc/p2p/base/dtlstransport.h?type=cs&q=dtlstransport&g=0&l=124
[2] https://wpt.fyi/results/webrtc/RTCDtlsTransport-getRemoteCertificates.html?label=stable&aligned

**Comment by henbos** [comment]
I suggest having an internal slot that is updated in the same place(s) that [[DtlsTransportState]] is updated, and changing the getter into an attribute. This way all related state information is updated in the same place and we don't end up with chains of async ops where by the time you have piece of information B, piece of information A is no longer valid.

**Comment by alvestrand** [comment]
That works for me.

**Comment by aboba** [comment]
@alvestrand Edge implements getRemoteCertificates.  Since it returns an empty list until the DtlsTransport.state transitions to "connected", getRemoteCertificates() is typically called within the onstatechange EventHandler. A promise would therefore be more convenient.

**Comment by henbos** [comment]
How would a promise be more convenient? It causes a delay and increases uncertainty, and means you can't look at multiple pieces of state information and be assured they are from the same snapshot in time. If you want to know the certificates within onstatechange event then why not return the internal slots here? If you queue another task to get the certificates then in theory you could have disconnected again before having them.

Calling getRemoteCertificates() before we have connected: I think the appropriate thing is to reject the promise, not leave it pending until we may or may not connect depending on other operations.

**Comment by henbos** [comment]
@henbos to add internal slots

**Comment by alvestrand** [comment]
Since Edge has implemented it, let's not change the API surface (no attribute).
