### ISSUE TITLE
More simulcast examples

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2035]
It has been suggested that we include more simulcast examples, so as to potentially uncover areas of the specification that need work.

**Comment by amithilbuch** [comment]
I have been looking at simulcast (and rids) in the last few weeks. i have some ideas around areas that need work. some of them might be real, others might be a result of me being new to webrtc.
Here is a list of things i have yet to understand or track down. These are mostly things described in the spec, but there is a lack of understanding how these originate from the user via the public API:
1. How does the user specify the alternatives in a simulcast layer?
2. How does the user specify restrictions for layers (rids)?
3. How does the user indicate that a layer should be paused?
4. How are dependencies between rids specified by the user?
5. More specifics regarding the receiver of simulcast?

Another issue is that simulcast is a general mechanism for a media channel but all examples (and  scenarios) are only for use in video. An audio example could help with that.

I'll be happy to coordinate on the spec to help clarify these issues and uncover new ones.

**Comment by aboba** [comment]
@amithilbuch Can you explain what you mean by "dependencies between rids"?  Also, by "paused" do you mean for a sender to stop a simulcast layer being sent?

**Comment by amithilbuch** [comment]
[the rid spec](https://tools.ietf.org/html/draft-ietf-mmusic-rid-15#section-11.2) mentions dependencies between rids (using the "depend" restriction). Here is an excerpt: 
Adding scalable layers to a session within a multiparty conference
   gives a selective forwarding unit (SFU) further flexibility to
   selectively forward packets from a source that best match the
   bandwidth and capabilities of diverse receivers.  Scalable encodings
   have dependencies between layers, unlike independent simulcast
   streams.  RIDs can be used to express these dependencies using the
   "depend" restriction.  In the example below, the highest resolution
   is offered to be sent as 2 scalable temporal layers (using MRST).
   See [I-D.ietf-mmusic-sdp-simulcast] for additional detail about
   simulcast usage.

Paused - the simulcast spec talks about offer/answer negotiations specifying streams that are initially paused (using the ~ notation). the layer is still being "sent" and negotiated, but it starts out as paused. i assume that layers can pause as well.

**Comment by Orphis** [comment]
For the paused part, I guess it would map to the "active" flag you can set using get/setParameters(). 
https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-active
I believe this would just be a hint for SFUs and not necessarily required.

As for the rest, I don't believe the WebRTC simulcast APIs currently supports alternatives, restrictions or dependencies between layers. Do we have any use case that would require supporting those in the API?

**Comment by amithilbuch** [comment]
Spec compliance, i assume. if the effort is roughly the same, i see no reason to ignore parts of the spec if we can support it.

**Comment by aboba** [comment]
@amithilbuch I think we can ignore dependencies between RIDs. The problem with the layer dependency model is that it cannot describe all useful SVC modes, such as the "K-SVC" modes in AV1. To enable specification of a wider range of modes, the WG has taken an alternate approach:
https://github.com/w3c/webrtc-svc

**Comment by aboba** [comment]
@Orphis  The `active` member of the `RTCRtpEncodingParameters` dictionary turns simulcast layers on/off, but doesn't affect the SDP.  An application can create its own way to signal layer drop/add to the SFU though.

**Comment by aboba** [comment]
@amithilbuch Can you elaborate on what you mean by "alternatives"?  JSEP does not reference RFC 5939 ("SDP Capability Negotiation") so there's no way to express potential configurations.

**Comment by amithilbuch** [comment]
`RTCEncodingParameters` for `maxFramerate` and `maxBitrate` etc. are not all supported. some of them are simply ignored (or verify that they are not set).
simulcast alternatives appears in the [simulcast spec](https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-13#section-5.1). I'll use SDP as an example:
a=simulcast:send 1;2,3 recv 4
means that i want to send only 2 layers. Rid '1' will be the first layer, and i am specifying rids '2' and '3' as alternatives for the second layer (in preference order).

I do not see any way for the user to signal this to the platform at the moment. I do see a way for the platform to "unroll" the list of all supported formats and artificially create an alternative list, but i think that might be overkill, because it will make negotiation much more difficult.

**Comment by alvestrand** [comment]
we are not using dependencies - simulcast is independent streams.
The WG's choice for SVC was to use another mechanism.

**Comment by dontcallmedom** [comment]
is there any reason to leave that issue open?
