### ISSUE TITLE
Allow addIceCandidate(null) for backwards compatibility w/adapter

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2039]
This is instead of reopening https://github.com/w3c/webrtc-pc/issues/1773, because while no browser ever allowed `addIceCandidate(null)`, [adapter.js](https://github.com/webrtcHacks/adapter) did, and still does, causing some confusion among users. To reproduce:
 1. Open [this fiddle](https://jsfiddle.net/jib1/81o5sa2n/) and allow camera -> success.
 2. Remove `adapter-latest.js` under *Resources* on the left, and re-run it, and you get errors:

```
(index):51 Uncaught (in promise) TypeError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Candidate missing values for both sdpMid and sdpMLineIndex
    at RTCPeerConnection.pc2.onicecandidate.e ((index):51)
(index):50 Uncaught (in promise) TypeError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Candidate missing values for both sdpMid and sdpMLineIndex
    at RTCPeerConnection.pc1.onicecandidate.e ((index):50)
```
They come from the benign-looking:
```js
pc1.onicecandidate = e => pc2.addIceCandidate(e.candidate);
pc2.onicecandidate = e => pc1.addIceCandidate(e.candidate);
```

Without restating https://github.com/w3c/webrtc-pc/issues/1773, while redundant, it seems benign to support this for legacy reasons. [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-24#section-4.1.17) even supports it: *"In the case of an end-of-candidates indication, the absence of both the m= section index and MID fields is interpreted to mean that the indication applies to all m= sections in the specified ICE candidate generation"*. It also appears idempotent.

**Comment by steveanton** [comment]
Interpreting `null` as an end-of-candidates indication for all m= sections seems very sensible to me and allows `pc1.onicecandidate = e => pc2.addIceCandidate(e.candidate);` which is convenient and intuitive.

**Comment by jan-ivar** [comment]
I did some archeology, and judging by https://github.com/w3c/webrtc-pc/issues/1077#issuecomment-287159303 there seemed to be some confusion around what would be needed to fix this.

It's surprisingly simple to support: There's no need to reintroduce nullable. In fact, dictionaries *cannot* be nullable, because `null` is already a valid value for a dictionary in WebIDL, [producing the default dictionary](https://heycam.github.io/webidl/#es-dictionary). E.g. `addIceCandidate(null)` is already indistinguishable from `addIceCandidate({candidate: "",  sdpMid: null, sdpMLineIndex: null}`, which is corroborated by the Chrome errors above.

So all we would need to do, is reintroduce the [original language](https://github.com/w3c/webrtc-pc/pull/1088/files) here, just with s/null/empty string/. I.e.:

*"If* candidate *is not `""` and both* sdpMid *and* sdpMLineIndex *are `null`, return a promise rejected with a newly created TypeError."*

**Comment by lgrahl** [comment]
In any case, sounds like a gotcha that should additionally be noted in a *note* so we don't get confused again. :wink:

**Comment by lgrahl** [comment]
I'd still say: Clarification doesn't hurt. The spec is also looked at by folks using WebRTC since MDN and other resources are often outdated. Speaking as a user, I wouldn't read from the description that I can throw `null` into it.

**Comment by jan-ivar** [comment]
@lgrahl Ok I added a note. PTAL.

**Comment by fippo** [comment]
How many times did we go back and forth on this now?

Note that in https://w3c.github.io/webrtc-pc/#simple-peer-to-peer-example (and other examples) we do not do the "is e.candidate defined" in onicecandidate
