### ISSUE TITLE
Use of JSON.stringify needs reconsideration

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#204]
As per this bug:

https://code.google.com/p/chromium/issues/detail?id=467471

the behavior of DOM object attributes has changed; it seems that such attributes are no longer picked up by JSON.stringify.

This means that our examples can't use JSON.stringify on such objects; more code is needed.

**Comment by adam-be** [comment]
The affected object should be RTCIceCandidate and RTCSessionDescription. We use specific WebIDL serializers [1] on these objects that specifies that all attributes should be included in the serialization so I think we should be fine.

[1] http://heycam.github.io/webidl/#idl-serializers

**Comment by dontcallmedom** [comment]
+1 that we should be fine on this

**Comment by alvestrand** [comment]
IDL serializers have now been implemented in Chrome, and the implementation has been made conformant with the spec again (after understanding the spec better). Issue closed!
