### ISSUE TITLE
set-pc-configuration is unclear on how to match certificates

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2043]
https://w3c.github.io/webrtc-pc/#set-pc-configuration step 4 is checking certificates as follows: "the set of certificates differs from the ones used when connection was constructed".

It is not clear whether that means whether certificate order is significant or not. 
The term 'set' is used, which would tend to make the order insignificant, but certificates are passed as a sequence. WebKit is implementing sequence-matching.

For a RTCCertificate to 'differ' from another, it can mean that the RTCCertificate objects are not the same. WebKit is implementing this interpretation.
Another interpretation might be that a RTCCertificate differ from another if one of its slots (origin, expires, keying material, certificate) is different.

Additional WPT tests might be good in that area.

**Comment by alvestrand** [comment]
With the normal case of getConfiguration/modify/setConfiguration, the certificates will be object-equal. This is simplest to specify and simplest to implement.

**Comment by youennf** [comment]
WPT issue https://github.com/web-platform-tests/wpt/issues/15840

**Comment by youennf** [comment]
Fixed by https://github.com/w3c/webrtc-pc/pull/2113
