### ISSUE TITLE
DTLSTransport: No description of when to fire the error event

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2044]
It seems that we have no description of when the error event in DTLSTransport is fired.
I believe it should be fired:
- when the fingerprint fails to verify the remote certificate
- when the DTLS connection is closed due to an error at the DTLS layer

I believe it should fire before the state change event, but could argue this either way; I think it's important for compatibility that we say whether it is fired before or after the state change event.

I believe it should NOT fire when there's an error in the ICE transport. All ICE transport errors are theoretically recoverable with an ICE restart, and might result in the DTLS transport being able to continue.

**Comment by aboba** [comment]
Agree with above suggestions as to when the error is fired and timing (before the state change event).
