### ISSUE TITLE
Clarifications of certificate expiry

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2045]
A few items could be clarified:

- Computation of the certificate expires value refer to "current time". This could be better defined as you suggested. This should be consistent with the one in the expires future check)
- When the "current time" is actually computed as part of generateCertificate call (call time of generateCertificate, generation of the keying material, creation of the RTCCertificate objects/resolution of the promise)
- If we compare the expires value to a DOMHighResTimeStamp that performance API is providing/defining, we could consider making RTCCertificateExpiration a DOMHighResTimeStamp. We would lose EnforceRange so probably not worth it.
- When the "current time" is executed in the expires future check (one "current time" for all certificate expires checks or one current time per certificate expires check).

**Comment by aboba** [comment]
@youennf Can you prepare a PR?

**Comment by youennf** [comment]
Thanks for pinging me.
I did a first try at https://github.com/w3c/webrtc-pc/pull/2105.

**Comment by youennf** [comment]
Fixed by https://github.com/w3c/webrtc-pc/pull/2105

**Comment by dontcallmedom** [comment]
#2105 fixed this, closing
