### ISSUE TITLE
RTCRtpContributingSource.audioLevel should be present, but if it isn't due to legacy endpoint, don't calculate it

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2046]
The [audioLevel](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcontributingsource-audiolevel) is optional for CSRCs, but for SSRCs the spec says it MUST be present:

> For SSRCs, this MUST be converted from the level value defined in [RFC6464] if the RFC 6464 header extension is present, otherwise the user agent must compute the value from the audio data (the member must never be absent for audio receivers).

I think this implies that if you receive a packet, even if it arrives late and you intent to drop it, you have to waste cycles decoding it for the sake of calculating the audio level. I also wonder if there are performance considerations with having to calculate it.

Perhaps there should be some leeway about not always having to calculate this if the header extension is present? Chrome currently only surfaces this value from the header extension, not from calculating it.

**Comment by henbos** [comment]
That is, Chrome always calculate it on the send side and sends it, but does not calculate it on the receive side if the extensio is missing.

**Comment by aboba** [comment]
@henbos RFC 7874 does not mention RFC 6464 which may be why computing the audioLevel was required even if the extension is not present.  However, with RFC 6464 widely supported at this point, it seems fine to me to require the header extension if the audioLevel is desired.

**Comment by henbos** [comment]
OK. I think I'll add a note that it is expected to be present, indicating that you "SHOULD" be able to rely on it, but in case it's not (because you're talking to a legacy endpoint or whatever) it's OK not to calculate it. Does that make sense?
