### ISSUE TITLE
Do simulcast offers need to contain RIDs of all streams in both directions?

### ISSUE THREAD

**Issue by amithilbuch** [w3c/webrtc-pc#2053]
Spec seems to indicate that an offer to send simulcast needs to also indicate the RID of the single stream it will receive:
`a=simulcast:send 1;2;3 recv 4`
likewise if the offer is generated by the SFU
`a=simulcast:recv 1;2;3 send 4`

This seems to indicate that all the RIDs are known well in advance.
There does not seem to be any advantage to this except adding restrictions to the RIDs.
Analyzing both cases:
1. Simulcast sender is offering - in such a case, there should only be a single receive RID and there is no benefit in adding any restrictions as they could be directly negotiated in the media section.
2. SFU is offering - in such a case, it makes sense for the receive RIDs to be specified explicitly as there are multiple layers and the information about the layers needs to be specified.

Another drawback to this is that it is somewhat inconsistent with current negotiation (of SSRCs) which is asymmetrical (Offer does not contain SSRCs for receive streams). In fact, SSRCs, or RIDs are not required in the incoming stream from the SFU as MID should be sufficient for demuxing.

Furthermore, what should be done in subsequent offers if a RID was not signaled but was discovered in the header.

I have noticed that Firefox examples do not contain both directions.
This should be further clarified in the spec.

**Comment by aboba** [comment]
@amithilbuch Agree that when a browser offers, it should not specify the RID it wishes to receive. No need,  since the Answer will contain the sending RID.  The second example seems trickier.  The SFU needs to tell the receiver layers apart.  But it also may be sending multiple streams to the browser, each with their own RID. Doesn't the browser need to know the RIDs associated with those multiple incoming streams?

**Comment by amithilbuch** [comment]
The browser is the symmetric equivalent of the sender, we should assume that they might also be sending simulcast layers to the server.
The server should pick a single layer and transmit that to the browser (client). This layer can change based on network requirements, app logic (ex. conference calls), or other signalling.
The server negotiates that traffic independently to the client, and can:
1. rewrite the RID to match what the client expects (regardless of which stream is transmitted).
2. drop the rid altogether (because mid is sufficient).
3. negotiate an SSRC because the client does not support RIDs and transmit the chosen stream on the SSRC without any MID/RID extensions.

In all of these options, it seems to me that the client and server can agree to change the relayed stream, without changing the rtp stream it is transferred on. 
As an example, if i click on your video during a conference call, i can signal to the server to send me your video in high quality, but it should be sent over the same RTP stream (with the same MID, RID, SSRC) and this is application logic that is hidden from the WebRTC logic.

This assumes that the video encoder will be able to handle changing resolutions. i'm no expert on that.

**Comment by aboba** [comment]
Consensus from the January 22, 2019 virtual interim is that simulcast offers do not need to contain RIDs in both directions (see PR https://github.com/w3c/webrtc-pc/pull/2075 )
