### ISSUE TITLE
Mismatch between RID restrictions and RTPEncodingParameters

### ISSUE THREAD

**Issue by amithilbuch** [w3c/webrtc-pc#2054]
There is a mismatch between how clients set up streams and how they communicate the created state. This is relevant to the case of Unified Plan and RIDs and is highlighted in the case of simulcast.

A client sets up their streams with a call to `addTransceiver()` in which they provide 'RTPEncodingParameters' also known as `send_encodings`. These encodings describe the layers.
Some of the parameters in `send_encodings` (such as `max_bitrate_bps` and `max_framerate`) match RID restrictions (such as `max-br` and `max-fr`).
However some of the parameters do not match. Specifically the parameters that indicate the resolution of the layer, which are of utmost importance to the simulcast scenario do not match.
In the RID description, they are `max-width` and `max-height` but in the `send_encodings` they are `scale_resolution_down_by`.
This makes communicating the setup during negotiation harder than it needs to be.
This is even harder when the offer is coming from the SFU which does not necessarily know the resolution of the imaging device on the other end. In such a case, there could also be performance impact from choosing "bad" values.

Some possible options to resolve (in no particular order):
1. Offers are only initiated by the simulcast sender.
2. Synchronize the parameters between the two specs (not strictly possible because new restrictions can be added in the future).
3. Fix this in the implementation layer (by passing on the values to the engine) and ignore send_encodings.
4. Put the onus of translating between the two 'formats' on the user that should set up the transceivers accordingly.
5. Ignore incoming restrictions as if they are 'not understood' removing them from the answer (using RIDs only as identifiers).
6.  Signal the information out-of-band and only use the RIDs as identifiers.

**Comment by aboba** [comment]
@amithilbuch In practice, it is sometimes necessary for an Offer to come from a conference server (the simulcast receiver).  Some signaled parameters on a recv rid (e.g. `max_bitrate_bps` and `max_framerate`) correspond to members of `RTCRtpEncodingParameters` and therefore may be surfaced there (while still being changeable by the sender), while others can only be accessed via SDP.

**Comment by aboba** [comment]
@juberti Were rid restrictions discussed during the development of JSEP?

**Comment by aboba** [comment]
Consensus from the January 22, 2019 virtual interim is that restrictions are not supported (see PR https://github.com/w3c/webrtc-pc/pull/2075 )
