### ISSUE TITLE
Send transferable data

### ISSUE THREAD

**Issue by jimmywarting** [w3c/webrtc-pc#2055]
Hi. 
I'm using DataChannel to transfer a large file to another peer. While monitoring the performance of my javascript (in chrome v71) I notice `channel.send(uInt8Array)` takes up the most of the scripting time
![skarmavbild 2019-01-12 kl 23 12 58](https://user-images.githubusercontent.com/1148376/51079006-aa1b6f00-16bf-11e9-8ec9-be6a6b8403f8.png)

I assume that it has to has to copy the ArrayBufferView and that is why it block the main thread for a bit? since i might still have a reference to it somewhere... Now my proposal is make it optional to make it transferable just like postMessage is able to do. 
`port1.postMessage(message, [transfer])`
`dataChannel.send(message, [transfer])`
I don't need the data after that point so there is no need for it to be copied. it would also help to free memory

**Comment by lgrahl** [comment]
This sounds like a reasonable approach. Has this been discussed before?

/cc @jesup

**Comment by aboba** [comment]
Copied to the WebRTC-NV repo as Issue https://github.com/w3c/webrtc-nv-use-cases/issues/42
