### ISSUE TITLE
Can RTCDtlsTransport's iceTransport attribute change?

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#2056]
http://w3c.github.io/webrtc-pc/#dom-rtcdtlstransport

The attribute description is "The iceTransport attribute is the underlying transport that is used to send and receive packets. The underlying transport may not be shared between multiple active RTCDtlsTransport objects."

I think that means it can't change. If so, please add `[SameObject]` to make this even more clear.

**Comment by henbos** [comment]
> Otherwise, let transport and rtcpTransport be newly created RTCDtlsTransport objects, each with a new underlying RTCIceTransport. Though if RTCP multiplexing is negotiated according to [RFC5761], or if connection's RTCRtcpMuxPolicy is require, do not create any RTCP-specific transport objects, and instead let rtcpTransport equal transport.

RTCDtlsTransport and RTCIceTransport are created at the same place, and as far as I can tell there is nothing in the spec that can change which ice transport is used by a dtls transport, effectively making this a "const".

**Comment by henbos** [comment]
Note: The transports of a transceiver can change, but the ICE and DTLS transports always comes in pairs AFAIK.

**Comment by alvestrand** [comment]
I want that attribute to be immutable; our current implementation is, and I'd like it to stay that way. [SameObject] makes sense as a way to state that.
(One could imagine an implementation that implemented ICE restart by throwing away the ICETransport object and starting over. I want such an implementation to be non-conformant.)

**Comment by lgrahl** [comment]
Mh...

    A new DTLS association must be established between two endpoints
    after a successful SDP offer/answer exchange in the following cases:

    o  The negotiated DTLS setup roles change; or

    o  One or more fingerprint values are modified, added or removed in
      either an SDP offer or answer; or

    o  The intent to establish a new DTLS association is explicitly
      signaled using SDP, by changing the value of the SDP 'tls-id'
      attribute defined in this document;

Source: https://tools.ietf.org/html/draft-ietf-mmusic-dtls-sdp-32#section-3.1

**Comment by lgrahl** [comment]
Ah, the ICE transport reference of the DTLS transport, never mind! Carry on.

**Comment by fippo** [comment]
see also https://github.com/w3c/webrtc-pc/issues/1357#issuecomment-309252166

**Comment by aboba** [comment]
@foolip Yes, the `RTCIceTransport` is immutable (e.g. in ORTC there was no `setTransport` method in the `RTCDtlsTransport` to allow it to be changed).

**Comment by foolip** [comment]
Alright, sounds like a simple spec fix then.

**Comment by alvestrand** [comment]
The language lgrahl quotes indicates that multiple DTLS transports can exist that refer to the same ICE transport object (the "old one" and the "new one"). But that's a separate problem, not this bug.
