### ISSUE TITLE
rtcpTransport should be null when multiplexing RTCP

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2057]
There seems to be an inconsistency between the following two statements:

"Otherwise, let transport and rtcpTransport be newly created RTCDtlsTransport objects, each with a new underlying RTCIceTransport. Though if RTCP multiplexing is negotiated according to [RFC5761], or if connection's RTCRtcpMuxPolicy is require, do not create any RTCP-specific transport objects, and instead let rtcpTransport equal transport." (4.4.1.6 Set the RTCSessionDescription, bullet 2.2.7.1.1.5)

"rtcpTransport of type RTCDtlsTransport, readonly, nullable
The rtcpTransport attribute is the transport over which RTCP is sent and received. Prior to construction of the RTCDtlsTransport object, the rtcpTransport attribute will be null. When RTCP mux is used (or bundling, which mandates RTCP mux), rtcpTransport will be null, and both RTP and RTCP traffic will flow over the transport described by transport.

On getting, the attribute MUST return the value of the [[SenderRtcpTransport]] slot." (section 5.2 RTCRtpSender interface, rtcpTransport attribute).

Suggested fix: Modify 4.4.1.6 bullet 2.2.7.1.1.5 to set rtcpTransport to null.

**Comment by aboba** [comment]
Agreed.
