### ISSUE TITLE
RTCErrorEvent constructor's RTCErrorEventInit parameter should be optional

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2070]
Because RTCErrorEventInit contains not required attributes, and as such can be constructed from {}, the recommendation (@foolip) is that when this type is used as an argument, that argument is optional. That is:

```
Constructor(DOMString type, optional RTCErrorEventInit eventInitDict)
```
Here: https://w3c.github.io/webrtc-pc/#dom-rtcerrorevent

**Comment by foolip** [comment]
I can't find the wording in the Web IDL spec now, but https://github.com/heycam/webidl/issues/130 has more background.

**Comment by henbos** [comment]
This is obsolete, final stuff in #2070.
