### ISSUE TITLE
"Create an RTP sender" doesn't handle creating from SDP

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2072]
The section on applying a remote description says:

If no suitable transceiver is found (transceiver is unset), run the following steps:
- Create an RTCRtpSender, sender, from the media description.

The link to "Create an RTCRtpSender" goes to:

To create an RTCRtpSender with a MediaStreamTrack, track, a string, kind, a list of MediaStream objects, streams, and optionally a list of RTCRtpEncodingParameters objects, sendEncodings, run the following steps:

It's not obvious how to construct the parameter list to this algorithm from the media description.
(In particular I was looking for a place to attach the description of how one constructs a list of RTCRtpEncodingParameters from the SDP description. I think I know what to write, but it's not obvious where to attach it.)

**Comment by aboba** [comment]
On applying a remote description, the transceiver's sender `RTCRtpEncodingParameters` will be set based on what the remote peer has indicated it wants to receive. This will principally be based on the "a=simulcast" line and recv rids. Other dictionary members (e.g. scaleResolutionDownBy, maxFramerate, etc.) will not be set.

**Comment by aboba** [comment]
@alvestrand Can you submit a PR?

**Comment by amithilbuch** [comment]
After PR #2085 was merged, the section now reads:

> 
> If no suitable transceiver is found (transceiver is unset), run the following steps:
> 
> If the description is of type "offer" and contains a request to receive simulcast, use the order of the rid values specified in the simulcast attribute to create an RTCRtpEncodingParameters dictionary for each of the simulcast layers, populating the rid member according to the corresponding rid value, and let sendEncodings be the list containing the created dictionaries. Otherwise, let sendEncodings be an empty list.
> 
> Create an RTCRtpSender, sender, from the media description using sendEncodings.
> 

So the algorithm now explicitly states that you pass along the sendEncodings and explains exactly how to create them from the SDP. This should cover this issue as well.

**Comment by aboba** [comment]
Closing.  If there is something else needed, we can reopen it.
