### ISSUE TITLE
Simulcast: Which layer gets dropped first?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2080]
This is a spin-off from #1896 - we need a section that describes "things that happen during a call", and it should say which order we drop layers in.

@amithilbuch says that the description of a=simulcast says "highest priority layer goes first", so the order of drops and the order of declarations should be the same.

**Comment by alvestrand** [comment]
https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-10#section-6.2.2

"The
   order of the listed simulcast streams in the "send" direction
   suggests a proposed order of preference, in decreasing order: the
   rid-id listed first is the most preferred and subsequent streams have
   progressively lower preference.  The order of the listed rid-id in
   the "recv" direction expresses which simulcast streams that are
   preferred, with the leftmost being most preferred.  This can be of
   importance if the number of actually sent simulcast streams have to
   be reduced for some reason."

**Comment by murillo128** [comment]
I disagree that #2141 is a duplicate of this, anyway:

> "highest priority layer goes first"

What does it mean "highest priority", I may want a layer with more bandwidth but that is dropped the first, is it the highest or the lowest priority layer?

**Comment by aboba** [comment]
Decision from April Interim: Harald to develop PR highlighting currently supported solution.

**Comment by alvestrand** [comment]
At the moment, there's a note in the "createOffer" section saying

NOTE
[SDP-SIMULCAST] section 5.2 specifies that the order of RIDs in the a=simulcast line suggests a proposed order of preference. If the browser decides not to transmit all encodings, one should expect it to stop sending the last encoding in the list first.

This was added in #2071, merged Jan 31.

I think this is necessary and sufficient to close this issue.
