### ISSUE TITLE
Make RTCError inherit from DOMException?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2082]
According to @domenic it is now possible to define IDL types that inherit from DOMException.
This would allow us to do a pure IDL specification of RTCError, which is a far simpler specification than the one we're doing now (and comports with the one in-progress implementation I know about).

DOMException spec:
https://heycam.github.io/webidl/#idl-DOMException

Should we do this?

**Comment by henbos** [comment]
This would also be a lot simpler to implement (I'll update my CL to verify). The RTCError is not implemented by any browser yet and in my [intent to implement & ship](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/TsJA1XX7mTE) we got pushback.

Should we do this? I think so.

**Comment by foolip** [comment]
This is great if possible. One thing that needs to be decided is what `new RTCError().code` should return, probably zero.

**Comment by henbos** [comment]
Implementing RTCError to extend DOMException in chromium was trivial.
