### ISSUE TITLE
It is not clear that RTCErrorDetailType is referencing things defined in another repo

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2083]
The [RTCErrorDetailType](https://w3c.github.io/webrtc-pc/#rtcerrordetailtype-enum) has several "idp-*" values, none of which are referenced from anywhere else in the document, and the description of "idp-need-login" says "The identity provider requires the user to login. The idpLoginUrl attribute is set to the URL that can be used to login." but there's no attribute named in this spec.

These are all part of the identity spec. We should add links to that spec to clarify what is being referenced. This was not clear from reading the enum definitions.

**Comment by henbos** [comment]
I guess these are leftovers from #1931.

**Comment by alvestrand** [comment]
Yes, these are leftovers - I had promised to move them, but forgot. I can take on the move.

**Comment by alvestrand** [comment]
Unfortunately partial enums are still not in WebIDL, so we can't simply move the enum values - @domenic https://www.w3.org/Bugs/Public/show_bug.cgi?id=27048 is still untouched, and appears to have been forgotten, while https://github.com/heycam/webidl/issues/184 was closed as a duplicate - care to comment?

Until this changes, the best we can do is to move the descriptions and say "these are defined in the identity spec".

**Comment by domenic** [comment]
My comment is that Web IDL has a lot of open bugs and few editing resources, and it's not very kind to say that the bug has been forgotten. I imagine the editors are very aware of the high bug count, and I'm sure they would welcome a pull request to fix such open bugs.
