### ISSUE TITLE
How to handle Glare

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2095]
I got a question recently about what to do in the event of Glare (e.g. receiving an Offer when the local peer has already sent an Offer).  My instinct would be to just call pc1.close(), then construct pc2 and then call pc2.setRemoteDescription(remoteOffer).  However, I've been asked how the same goal might be accomplished by rolling back the call to pc1.setLocalDescription(localOffer). 

Even if this were well supported, there are still some loose ends to clean up.  Prior to sending the Offer, the local peer probably called addTransceiver.  Rolling back setLocalDescription does not remove those transceivers, which may have been set up with parameters that may not be compatible with the remote Offer.  For example, the remoteOffer is an Offer to receive simulcast with 3 streams but pc1.addTransceiver only included only 1 encoding in sendEncodings.  So it seems desirable to call transceiver.stop() on the previously created local transceivers and then pc1.setRemoteDescription(remoteOffer) which will produce a set of usable transceivers.

So is the following a (viable? better?) solution?

1. Roll back pc1.setLocalDescription(localOffer)
2. Call transceiver.stop() on the locally created transceivers
3. Call pc1.setRemoteDescription(remoteOffer)

**Comment by jan-ivar** [comment]
> So is the following a (viable? better?) solution?

Yes, I think so. I'm working on a blog post about this, how *rollback*, when used properly, should be able to tackle arbitrary remote changes, much like *negotiationneeded* (once Chrome fixes it) tackles arbitrary local changes, for *"perfect negotiation"*. That is: fully abstract away the negotiation process, handling all glare.

I just need to prove to myself that it works in all instances, or at least the common ones. If we assume the other peer is sane, then `"have-local-offer"` should be all we need to support rollback of—e.g. if we receive an offer in `"have-remote-pranswer"` then the other side is messing with us, and we just ignore it.

An edge-case may be receiving an offer in `have-remote-offer`. Do we take the new one or finish the old one? It would be up to the app how to handle this.

**Comment by jan-ivar** [comment]
> If we receive an offer in `"have-remote-pranswer"` then the other side is messing with us

...or the other user hit Page Refresh. In that case there's nothing to salvage, so `pc.close()` away.

**Comment by aboba** [comment]
Closing since there are no changes needed to the spec.
