### ISSUE TITLE
addTransceiver-transceivers should get associated with offered m= sections

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2108]
The steps for SRD(offer) says:

> As described by [JSEP] ([section 5.10.](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.10)), attempt to find an existing RTCRtpTransceiver object, transceiver, to represent the media description. [... otherwise we create a new transceiver.]

Which references:

>             If the m= section is sendrecv or recvonly, and there are
>             RtpTransceivers of the same type that were added to the
>             PeerConnection by addTrack and are not associated with any
>             m= section and are not stopped, find the first (according to
>             the canonical order described in Section 5.2.1) such
>             RtpTransceiver.

I was reading this as conditions for associating existing transceivers, addTrack being an example of how transceivers could have been added beforehand. The Chrome implementers interpreted the transceiver being added by addTrack as one of the conditions. That is, a transceiver that was added by addTransceiver does not qualify, even if the resulting set of transceivers is _identical_. This seems silly to me.

This is, by design, able to set up both sending and receiving:
```
pc1.addTrack(track);
pc2.addTrack(track);
O/A exchange

Result:
- pc1's transceiver's currentDirection is sendrecv
- pc2's transceiver's currentDirection is sendrecv
- Both tracks are sent
```

But a consequence of the above is that if you use addTransceiver instead, even though the state of the transceivers are identical at the O/A exchange, pc2 is not able to send its track to pc1:
```
pc1.addTransceiver(track);
pc2.addTransceiver(track);
O/A exchange

Result:
- pc1's transceiver's currentDirection is sendonly
- pc2's has two transceivers: [{currentDirection:null},{currentDirection:recvonly}}
- Only pc1's track is sent
```
This is just confusing. Why should addTransciever-transceivers be blocked from being associated with offers? This forced the application to do workarounds like adding media at a later stage or discouraging you from using the addTransceiver API.

Proposal: Transceivers are associated based on their own merits, not which API caused its creation.

**Comment by henbos** [comment]
Please take a look @jan-ivar

**Comment by henbos** [comment]
CC @titov-artem who experienced this issue

**Comment by henbos** [comment]
CC @steveanton who implemented this stuff

**Comment by murillo128** [comment]
In your example, wouldn't the pc2 fire a negotiation needed flag be set to true and the transceiver be associated on the new SDP O/A?

**Comment by henbos** [comment]
Yes at the cost of additional negotiations (and RTTs) this all works out at the end but I think it is a bug that it doesn't resolve in the first negotiation.

**Comment by murillo128** [comment]
I would not consider it a bug but a expected behavior due to a wrong design decision based on how SDP O/A works.

If I have to choose I prefer consistent API between the m-lines and the transceivers api at the cost of inefficiency.  You can avoid that by using addTrack if you don't care about transceivers.

**Comment by jan-ivar** [comment]
> The Chrome implementers interpreted the transceiver being added by addTrack as one of the conditions.

Firefox does the same, because that is what the spec says, and it was intentional, as I recall. 

The thinking was: if you add a transceiver, you mean to add a new transceiver. If you add a track, then your expectation is (historically) more likely to be symmetrical. By having both methods you get to choose. 

> This forced the application to do workarounds like adding media at a later stage or discouraging you from using the addTransceiver API.

This is why *addTrack* is still in the spec. FWIW I cover both ways of answering in [my blog](https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/), search for *"How to answer ONLY with transceivers"* if you must use *addTransceiver*, and yes, it's highly asymmetrical.

> Proposal: Transceivers are associated based on their own merits, not which API caused its creation.

I personally think this has some merit, but one would need to weigh the trade-offs, and I don't see any new information here.

**Comment by steveanton** [comment]
I recall asking Taylor and/or Peter about this a year ago and they indicated it was a deliberate choice to only enable this behavior for addTrack.

**Comment by dontcallmedom** [comment]
given the history of this, should this issue be closed?

**Comment by henbos** [comment]
> The thinking was: if you add a transceiver, you mean to add a new transceiver. If you add a track, then your expectation is (historically) more likely to be symmetrical.

And if you call addTransceiver(), you do get a new transceiver. So why not use it in the answer? Presumably because you want to ensure that you can offer-to-receive in the future, and...

> By having both methods you get to choose.

...but you do get to choose, even if addTranscievers() are treated the same as addTrack()-transceivers.

If you do addTransceiver() followed by createOffer() your additional transceivers become new m= sections and you're happy.
If you receive an offer after having done addTransceiver(), and your transceiver ended up being used in the answer, this is easily observable, and you can simply call addTransceiver() again (just look at which transceivers have a currentDirection: null when you're in a stable state).

> I personally think this has some merit, but one would need to weigh the trade-offs, and I don't see any new information here.

The benefit of addTrack() over addTransceiver(), in my opinion, is that it doesn't necessarily create a new transceiver, so you avoid having to do extra code for "do I already have one that I can reuse? If so replaceTrack() and change direction manually". This is for convenience and for track-minded people. The track-minded person thinks "adding a track means I can send a track". The transceiver-minded person thinks "a transceiver matches to m= sections". Or with the current design, "a transceiver matches to m= sections, with some caveats that I have to keep track of myself".

Right now whether or not a transceiver is usable is based on historical information that is not explicitly stored anywhere, and is not observable to someone who uses getTransceivers() to get a sense of the state in comparison to the expected O/A behavior.

> given the history of this, should this issue be closed?

I think not. If we want some transceivers to be special we should call it out. Bare minimum with an [[IsUsableInRemoteOffer]] internal slot, but possible even an attribute to expose this to the JS application, so that it can easily figure out whether or not new transceivers are needed. This is currently very much implicit and involves interpreting a JSEP line correctly.

I still think we should consider not making transceivers special though because, as I explained, this special functionality is not needed to achieve what its intention was, and anyone who cares about this should already have a clue about the relationship between transceivers and m= sections.

**Comment by henbos** [comment]
Or if we want to do as little as possible here, add an editorial "NOTE" explaining this stuff.

**Comment by murillo128** [comment]
After working with transceivers and done m-line mapping for local SDP O/A I
feel that current behavior is what I would expect it to be.  IMHO it is
kind of confusing to depend on the remote side offer to know what do to
with my local transceivers.

Most people should just use addTrack if they don't care about transceivers.

**Comment by henbos** [comment]
OK then. I suggest giving this a couple of days in case people want to comment but I get the impression that we can close this and open an editorial issue for adding a note.

**Comment by henbos** [comment]
Related question: If I do addTransceiver() followed by addTrack(), causing the first transceiver to be used for the track, is that transceiver still an ”addTransceiver-transceiver” or did it change to an ”addTrack-transceiver”?

**Comment by jan-ivar** [comment]
Then it's not "added to the PeerConnection by addTrack" I think.
