### ISSUE TITLE
Order of RTCError parameters

### ISSUE THREAD

**Issue by bakkot** [w3c/webrtc-pc#2111]
Please forgive the drive-by comment; we're discussing [a related issue](https://github.com/tc39/proposal-promise-any/issues/14) over at TC39 and I noticed this.

The [RTCError constructor](https://w3c.github.io/webrtc-pc/#rtcerror-interface) takes two arguments, `message` and `init`, where `init` is used to provide values with which to initialize the new object.

The [OverconstrainedError constructor](https://w3c.github.io/mediacapture-main/#overconstrainederror-constructor) from the media capture API similarly takes two arguments, `constraint` and `message`, where `constraint` is used to provide a value with which to initialize the new object.

These are inconsistent in their order. Might the order of the parameters to RTCError be switched? This would also allow making the `message` parameter optional, as it is for most other error constructors (including `DOMException`).

**Comment by henbos** [comment]
Chrome shipped in M73 with this order, is it worth changing?

**Comment by bakkot** [comment]
That's up to the Chrome team, presumably. I think there's very little chance anyone is depending on the current behavior yet, since manually constructing RTCError is a pretty weird thing to do and since 73 is not yet stable, so I would be very surprised if this change broke anyone right now.

For what it's worth, I'd never have noticed this if Chrome hadn't shipped it to the unstable channels. It seems a shame to say that API decisions like this are set in stone at exactly the point at which users can start experimenting with them and giving feedback.

**Comment by henbos** [comment]
Oh sorry, actually RTCError first appeared in M74 (https://chromiumdash.appspot.com/commit/3dfb2b295fcc442ab1ee4ef65bf74af7a625f019). There is still time to change it before it starts it rolling through the beta and stable channels.

**Comment by henbos** [comment]
The M74 cut date is Thursday next week

**Comment by jan-ivar** [comment]
Firefox hasn't implemented this yet FWIW.

**Comment by bakkot** [comment]
Is this a change you'd like to make? I'd be happy to submit a PR here and to [the corresponding web platform test](https://github.com/web-platform-tests/wpt/blob/20715b3f6a3b774b78a9724abde411ccb34a6212/webrtc/RTCError.html), if so.

**Comment by henbos** [comment]
Thanks, I'm happy to update the WPT, that can be done by the same CL that updates Chrome and the WPT import bot can take care of the rest. A PR on this issue would be very much appreciated if you can do it before Thursday morning (that's when we have a spec meeting), otherwise I can do it myself. What do you say?

**Comment by henbos** [comment]
Or Thursday afternoon if you're in Europe :)

**Comment by henbos** [comment]
Here's the Chrome CL, including the WPT changes: https://chromium-review.googlesource.com/c/chromium/src/+/1499613

The new constructor is:
```
Constructor(RTCErrorInit init, optional DOMString message = "")
```
