### ISSUE TITLE
Override peer routing strategy

### ISSUE THREAD

**Issue by ThreaT** [w3c/webrtc-pc#212]
Currently it defaults to use the internet's existing infrastructure to find peers but it should be possible to define how peers are found. In the case where mesh networking is being used it would be useful to define the path that a client node can use to reach another client node. i.e.

**Request**
Start: `192.168.0.1`
Then: `192.168.0.2`
Then: `192.168.0.3`
End: `192.168.0.4`

**Response**
Start: `192.168.0.4`
Then: `192.168.0.5`
Then: `192.168.0.6`
End: `192.168.0.1`

**Comment by alvestrand** [comment]
This is out of scope for this specification, since this specification depends on Internet technology; source routing does not have well defined standard APIs (or wide usage) at this time.

**Comment by ThreaT** [comment]
@alvestrand Is there a better place for this issue to be placed as opposed to being closed completely?

**Comment by alvestrand** [comment]
Send it to the IETF mailing list as a proposal for a new work item.

Until there actually is a specific network where this makes sense to consider, it seems premature to specify an API for it.
