### ISSUE TITLE
RTCIceCandidateInit has no required fields, so should probably be optional in addIceCandidate

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2125]

**Comment by docfaraday** [comment]
Note that this gets kinda ugly with legacy addIceCandidate, since the dictionary is the first arg, and the remaining args are not optional...

**Comment by docfaraday** [comment]
It seems to me that calling pc.addIceCandidate() being interpreted as an end-of-candidates signal is a violation of the principle of least surprise. Maybe we should make RTCIceCandidateInit.candidate required, and have the empty string convey its present meaning?

**Comment by jan-ivar** [comment]
Depends. To discourage anything but `addIceCandidate({candidate: signaledCandidate})`, then yeah we could *require* `addIceCandidate({candidate: ""})` and remove the `""` default. This would make it harder to end candidates "manually" or accidentally.

This is the opposite of WebIDL advice which aims to make calling APIs simpler, but we have a reason. I don't have a strong opinion however.

The legacy API is OK: the dictionary is not in trailing position there and doesn't [need to be optional](https://heycam.github.io/webidl/#dfn-optional-argument-default-value).

**Comment by lgrahl** [comment]
`addIceCandidate({candidate: ""})` is quite weird to me. I like [how the ORTC API has solved this](http://draft.ortc.org/#dom-rtcicecandidatecomplete).

However, I don't have a strong opinion here either and would be fine with keeping it. From a practical perspective, I haven't heard of issues from users and AFAIK browsers haven't even implemented handling this.

**Comment by jan-ivar** [comment]
> addIceCandidate({candidate: ""}) is quite weird to me.

On purpose. Users aren't supposed to have to end candidates manually, just do:
```js
pc.onicecandidate = ({candidate}) => signaling.send({candidate});

signaling.onmessage = async ({data: {description, candidate}}) => {
  if (candidate) await pc.addIceCandidate(candidate);
  if (description) ...
}
```
and the browsers take care of the rest.

**Comment by docfaraday** [comment]
> > addIceCandidate({candidate: ""}) is quite weird to me.
> 
> On purpose. Users aren't supposed to have to end candidates manually, just do:

So, this information can be useful; for instance, an ICE stack might like to know when to stop waiting for remote ICE candidates to be given to it.

**Comment by docfaraday** [comment]
It seems like nobody has a strong opinion here, so I think it would be prudent to just make addIceCandidate (non-legacy) take an optional RTCIceCandidateInit, so we don't break compat.
