### ISSUE TITLE
Misalignment with -stats?

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#2126]
webrtc-pc says on mandatory to implement stats, for RTCVideoReceiverStats, that `framesCorrupted` must be supported. However, webrtc-stats does not define `framesCorrupted`.

**Comment by vr000m** [comment]
We removed framesCorrupted in https://github.com/w3c/webrtc-stats/issues/308

**Comment by alvestrand** [comment]
The old name needs to be added to the "obsolete stats" section, for traceability. That's what it's for.

**Comment by stefhak** [comment]
I can't find that section in webrtc-pc.
