### ISSUE TITLE
getSelectedCandidatePair needs special treatment for PRFLX candidates

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2134]
getSelectedCandidatePair is potentially exposing a used PRFLX candidate.
Given that it does not come from SDP/addIceCandidate, it might contain information not know from the web application, like the IP address.
This should be concealed like done for WebRTC stats.

Also, PRFLX candidates do not have an SDP equivalent, which makes it not straightforward to populate some of RTCIceCandidate properties like 'candidate'.
The spec should describe this.

**Comment by dontcallmedom** [comment]
@youennf can you confirm this issue has been fully addressed by #2182?

**Comment by youennf** [comment]
@dontcallmedom, yes.
