### ISSUE TITLE
Set the configuration is unnecessarily checking for some members being set

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2142]
https://w3c.github.io/webrtc-pc/#set-the-configuration in step 5 is saying:
"If the value of configuration.bundlePolicy is set ..."

This check seems to suggest that the following is allowed:
const pc = new RTCPeerConnection({bundlePolicy: "max-compat"})
pc.setConfiguration({}); // Should not throw.

Given that bundlePolicy takes a default value of "balanced", I would think that configuration.bundlePolicy will always have a value so the above example should fail.

Two options could be envisioned:
- Clarify that this is not allowed by removing the "If the value..." statement in the spec.
- Allow this by removing the default value of bundlePolicy.

The same might apply to rtcpMuxPolicy and iceTransportPolicy.

**Comment by alvestrand** [comment]
Youenn, can you propose a PR?

**Comment by dontcallmedom** [comment]
closed by #2192
