### ISSUE TITLE
Procedure for DataChannelId assignment on transport open not specified

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2144]
The procedure at http://w3c.github.io/webrtc-pc/#connected-procedure (SCTP transport connects) specifies that all the DataChannels will open. It does not specify how IDs will be assigned to those channels that haven't been assigned IDs before.

Suggestion: Add a step between 1 and 2 that allocates an ID if it is currently null. If no ID could be allocated (such as when MaxChannels is <= #open channels) close the channel due to failure.

**Comment by lgrahl** [comment]
Good catch. We can copy & paste most of step 19 of [createDataChannel](http://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions-0) for that purpose.

**Comment by lgrahl** [comment]
Be aware of #1818. So, we could either make a quick fix as proposed in my previous comment or move data channel ID assignment of in-band negotiated channel to the SCTP transport connected procedure and have it always be `null` before, regardless of whether or not the DTLS role has already been established.

**Comment by alvestrand** [comment]
data channel assignment of in-band negotiated channel can't be moved to the SCTP transport connected procedure in general, because when you call createDataChannel() after the SCTP connection has been established, ID assignment should be immediate.

**Comment by lgrahl** [comment]
Right. Then, at least we could make it a separate algorithm referred by both.

**Comment by alvestrand** [comment]
This was already discussed in #1818. Closing as duplicate.
