### ISSUE TITLE
createOffer does not guard against "have-remote-offer"

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2145]
There's no limit on when *createOffer* may be called today. *"Unlike createOffer, repeated call to createAnswer cannot be used again with setLocalDescription because doing so is invalid in stable state."* https://github.com/w3c/webrtc-pc/issues/1183#issue-227312645

It seems the reason is *createOffer* may be called from `"stable"` *and* `"have-local-offer"`.

But @docfaraday pointed out to me that calling *createOffer* in `"have-remote-offer"` makes no sense, and would be difficult to implement. So we should guard against that.

I'll add a PR to reject with ` InvalidStateError` (which is what *createAnswer* uses today).

**Comment by dontcallmedom** [comment]
@jan-ivar could you clarify the status here? Is it that we "just" need to add tests? If so, can this be migrated to WPT issues?

**Comment by aboba** [comment]
The PR has been merged, so I'm closing this issue.
