### ISSUE TITLE
simulcast offer doesn't work with addTrack. An omission

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2147]
https://github.com/w3c/webrtc-pc/pull/2081 put all simulcast processing of offers from SFUs under:

 *"3. If no suitable transceiver is found (transceiver is unset), run the following steps:"*

This means that when a suitable transceiver from *addTrack* **is** found—[section 5.10](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.10) says they're suitable—then we succeed without processing the simulcast rids, a mistake.

To solve this, either we modify JSEP to say it's unsuitable, or add language to set the existing transceiver's [[SendEncodings]].

I see no reason why we can't do the latter. We've seen real-world interest in having *addTrack* work with simulcast.

We may need to bump the [transactionId](http://w3c.github.io/webrtc-pc/#dom-rtcrtpsendparameters-transactionid), but that's a whole other issue.

**Comment by fippo** [comment]
Thanks @jan-ivar! I've run into a couple of bugs in Chrome [here](https://bugs.chromium.org/p/chromium/issues/detail?id=944821)

I do not think that `SRD, then use replaceTrack on a sender` is an API we should promote. Also there seem to be some cases where addTrack works (when called after setRemoteDescription; this is covered by the reuse in the addTrack algorithm afaics).

Quite oddly, calling addTransceiver and then having a remote description which matches the SendEncodings did not seem to match the existing transceiver either. Not an API I would like to see but its a case where we need to decide what to do.

**Comment by jan-ivar** [comment]
> remote description which matches the SendEncodings did not seem to match 

[suitable](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.10) = *"If the m= section is sendrecv or recvonly, and there are RtpTransceivers of the same type that were added to the PeerConnection by addTrack and are not associated with any m= section and are not stopped, find the first (according to the canonical order described in Section 5.2.1) such RtpTransceiver."*

The WG decided that *addTransceiver* should be explicit, not an abstraction. See https://github.com/w3c/webrtc-pc/issues/2108
