### ISSUE TITLE
transceiver.stop() needs more work (avoid BUNDLE footgun)

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2150]
Most API complaints I hear are from people negotiating manually. It's hard to get right, and steeped in historical reasons (needing to munge SDP, Chrome's `negotiationneeded` not working). So let's check in on `negotiationneeded`:

```js
button.onclick = () => pc.getTransceivers()[0].stop();

pc.onnegotiationneeded = async e => {
  await pc1.setLocalDescription(await pc1.createOffer());
  await pc2.setRemoteDescription(pc1.localDescription);
  await pc2.setLocalDescription(await pc2.createAnswer());
  await pc1.setRemoteDescription(pc2.localDescription);
}
```
Clicking the button will most likely stop only the first transceiver, but once in a blue moon it will stop all of them. That's broken. 😞

Quick reason: `stop()` on the first transceiver marks this BUNDLE transport as a goner on next negotiation; hardly noticeable in `"stable"` state, since a new one pops up on next negotiation. But in `"have-remote-offer"` state, there's no allowance for creating or finding a replacement transport in the answer. The BUNDLE spec has painted us in a corner here.

I think we must address this.

### Proposal

~`transceiver.stop()` is already a bit weird, in that it's both instant *and* a negotiated property. I think we can solve this by making `transceiver.[[Stopped]]` more like `transceiver.[[Direction]]`. That is: postpone the effects—and more importantly, the expectations—of stop until negotiation. This should gives us the leeway to avoid rejecting the BUNDLE transport and instead leave the negotiationneeded flag set for next round. This might mean needing a new method—perhaps `transceiver.reject()`—if we're interested in the old behavior.~

**Comment by jan-ivar** [comment]
Due to https://github.com/w3c/webrtc-pc/issues/2176 I no longer think there's a way to make `stop()` work safely with the offerer-tagged m-line being one of the exposed transceivers.

The BUNDLE spec [says](https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54#section-7.2.1): *"It is RECOMMENDED that the suggested offerer tagged "m=" section is a bundled "m=" section that the offerer believes it is unlikely that the answerer will reject, or move out of the BUNDLE group."*

**I see a couple of remaining options**:
 1. Live with it. Ironically, the problem seems easily worked around in JS, like this:
```js
const pc = new RTCPeerConnection(config);
const dummy = pc.addTransceiver("audio", {direction: "inactive"});
```
 2. Have webrtc-pc solve this, by creating an implicit inactive m-line dedicated to BUNDLE, either
     - when the `"max-bundle"` bundle policy is used, or
     - create some new `"safe-bundle"` policy.

 2. Some variation of (2) where the implicit m-line is the data channel m-line (currently disallowed). Assumes all BUNDLE-aware non-browser end-points also support data channel.

**Comment by jan-ivar** [comment]
And:

  4. Fix/violate BUNDLE, by having all browsers support moving the bundle group to an active m-line?

**Comment by jan-ivar** [comment]
> ```js
> const pc = new RTCPeerConnection(config);
> const dummy = pc.addTransceiver("audio", {direction: "inactive"});
> ```

Even this workaround has wrinkles: it [won't work](https://jsfiddle.net/jib1/6ct0b8fq/33/) with *addTrack* which will reuse the dummy.

if we get around that, having both ends do this, means we end up with *two* extra m-lines, not one.

**Comment by jan-ivar** [comment]
More ideas:

  5. Only half-stop the offerer-tagged transceiver in SRD(offer) and lie. Emit BYE and fire `"ended"`, but don't set port 0 in the answer, to save the transport. Locally consider this transceiver `stopped`, and trigger negotiationneeded in `"stable"`. To solve `stop()` now being a dud in the predetermined roles scenario, would require some additional bit ("please stop") in the answer to hand off stopping to the offerer and trigger negotiationneeded there.

  6. Say that `stop()` only affects *createOffer* and not *SRD(offer)*. Add a `reject()` for SRD(offer).

I like (6) because it's simple to explain (negotiating `stop()` requires sending an offer). Predetermined roles would need to rely on their out-of-band channel for stop like anything else. Apps can experiment with `if (tc.stopped) tc.reject()` to expedite stop in negotiationneeded, if they know what they're doing (e.g. using (1)).

**Comment by jan-ivar** [comment]
I plan to present 6, as it doesn't have special behavior only for the offerer-tagged transceiver.

**Comment by henbos** [comment]
We have several issues now (moved to [July Virtual Interim](https://github.com/w3c/webrtc-pc/labels/July%202019%20Virtual%20Interim)). Is this issue still applicable or can it be merged into one of those issues?

**Comment by jan-ivar** [comment]
Still relevant. I'll refer to both issues in the slides.
