### ISSUE TITLE
DatachannelInit "id" attribute description inconsistent with procedure

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2157]
In section 6.1 bullet 13, the spec says that "id" is ignored when "negotiated" is false.

In the attribute description of "id", it says "Overrides the default selection of ID for this channel."

The datachannel tests just merged seemed to assume that "id" would override the selection even when "negotiated" was false. This shows that the description can appear inconsistent.

Suggested fix: Change "id" description to say
```
 "Identifies the channel ID when "negotiated" is true. Ignored when "negotiated" is false.
```

**Comment by lgrahl** [comment]
> The datachannel tests just merged seemed to assume that "id" would override the selection even when "negotiated" was false.

Which ones are you referring to?

Agree with the suggestion, though. :+1:

**Comment by alvestrand** [comment]
RTCPeerConnection-createDataChannel, subtest   `createDataChannel with id ${id} should succeed`

Fix is in https://chromium-review.googlesource.com/c/chromium/src/+/1547975

**Comment by lgrahl** [comment]
Cheers. Good catch! :+1:
