### ISSUE TITLE
Too many test links in the spec, some redundant

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2161]
After https://github.com/w3c/webrtc-pc/pull/2156 merged, I see lots of test links in the spec, which is great! I'm not sure if they are in their final visual form yet (could they be smaller perhaps?), but I think there are too many of them right now, making it a bit hard on the eyes.

Some of them seem redundant. For instance, I don't think steps that create internal slots, like in [create an RTCRtpTransceiver](https://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtptransceiver) are JS observable, so there cannot be a test for this step.

The getters for these, like e.g. [sender](http://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-sender) already have test links, which should suffice I think, so we shouldn't need them on both places. cc @dontcallmedom

**Comment by dontcallmedom** [comment]
Re test links being too noisy, I don't disagree - I think a css rule to hide by default the relevant `<details>` element would be right; I'm working on building a test-dedicated view separately.

Re redundant links, I agree there is probably room for deduplication - as long as we make sure we don't leave normative text without an attached test case.

(I will have very little availability in the upcoming two weeks, so please feel empowered to bring these changes without me :)

**Comment by alvestrand** [comment]
I note that the test links are also missing /webrtc/ - so they all go 404. I guess this is a fixable bug.

**Comment by dontcallmedom** [comment]
I've fixed the links (a / was missing the testSuiteURI in the config)

**Comment by jan-ivar** [comment]
On second thought, I realize the steps I mention set default values, which I gather can and should be tested.
