### ISSUE TITLE
A simpler non-racy rollback

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2166]
In [my latest blog](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/) on *"Perfect negotiation in WebRTC"*, I cover using `negotiationneeded` and `"rollback"` in combination to abstract away negotiation. I describe implementing something I call "the polite peer" (a peer that rolls back in the face of an incoming offer):
```js
io.onmessage = async ({data: {description, candidate}}) => {
  if (description) {
    if (description.type == "offer" && pc.signalingState == "have-local-offer") {
      if (!polite) return;
      await Promise.all([
        pc.setLocalDescription({type: "rollback"}),
        pc.setRemoteDescription(description)
      ]);
    } else {
      await pc.setRemoteDescription(description);
    }
    if (description.type == "offer") {
      await pc.setLocalDescription(await pc.createAnswer());
      send({description: pc.localDescription});
    }
  } else if (candidate) await pc.addIceCandidate(candidate);
}
```
In the blog I cover in depth why the `Promise.all` is needed, but in short, it's there to cover a timing-window where we'd otherwise be vulnerable to *addIceCandidate* getting queued ahead of *setRemoteDescription* and failing.

To make this less of a footgun I think we should come up with a safer rollback API that does the rollback and sets the new description on the same run of the JS event loop. E.g.
```js
pc.allowRollback();
await pc.setRemoteDescription(description);
```
or perhaps
```js
await pc.setRemoteDescription(description, {rollback: true});
```
Open to other ideas.

**Comment by solmaks** [comment]
@jan-ivar , great post , and finally a summary of annoying real world problems with current WebRTC media signalling APIs! A couple of extra thoughts about the proposed API:

- If intent is to simplify life for application developers, then I would suggest going step further and removing the need to provide the {rollback:true} altogether. SRD and current PC state should have all the information to decide whether it should trigger a rollback, or apply a remote answer (current signalling state + description type).

-  It would be great if support for rolling back through SRD would remove the need to have the SLD rollback variant altogether. However, it does not seem to be possible to cover all scenarios with it. Namely, there is still a need to handle timeouts (offer/answer never reached remote endpoint) and errors (remote endpoint rejected offer for some reason), and SLD seems to be a better fit for this.

**Comment by jan-ivar** [comment]
@solmaks Thanks! On implicit rollback, you'll be happy to know that was the [resolution](https://www.w3.org/2019/07/02-webrtc-minutes.html#resolution03).

On timeouts, I think you bring up a good point. The existing mechanism remains in the spec, at least for now.

**Comment by solmaks** [comment]
Referenced PR has rollback option set to false by default. Will you update it to be true by default instead (for true implicit rollback behavior)?
