### ISSUE TITLE
{iceRestart: true} works poorly with negotiationneeded

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2167]
The currrent ICE restart API doesn't work well with `negotiationneeded`. Say you have this:
```js
pc.onnegotiationneeded = async () => {
  await pc.setLocalDescription(await pc.createOffer());
  io.send({desc: pc.localDescription});
}
```
How is the application supposed to restart ICE? Break that abstraction and call the methods directly, duplicating whatever logic the app may have put in there—after of course first checking we're in `"stable"` state and handling glare? That seems error-prone.

Performing an ICE restart is an application choice, often made for external network reasons. I think it deserves a first-class API that works with `negotiationneeded` and survives rollback:
```js
pc.restartIce();
```
This new method would set an internal slot that would cause negotiation to be needed, would invert the default value of the `{iceRestart}` offer option, and would be cleared in SRD(answer).

**Comment by fippo** [comment]
What keeps the app from doing this:
```
async function negotiate(offerOptions) {
  await pc.setLocalDescription(await pc.createOffer(offerOptions));
  io.send({desc: pc.localDescription});
}
pc.onnegotiationneeded = () => negotiate();
pc.oniceconnectionstatechange = (e) => {
  if (pc.icecConnectonState == 'failed') {
    negotiate({iceRestart: true});
  }
};
```
Adding a restartIce method leads down the slippery slope of triggering it based on peerconnection logic, not application logic.

**Comment by jan-ivar** [comment]
@fippo `iceconnectionstatechange` does not wait for `"stable"` state, so that code will fail occasionally. I think safer APIs will avoid these races.

> Adding a restartIce method leads down the slippery slope of triggering it based on peerconnection logic, not application logic.

I don't see that, but feel free to clarify. I see quite the opposite. It's today's API that seems buried in the details of peer connection's negotiation handling.

`negotiationneeded` is meant to help people encapsulate the detail-task of negotiating. If we split application logic up between what goes above that abstraction and what goes below it—with up being higher-level, closer to the app—I think ICE restart belongs above it.
```js
pc.oniceconnectionstatechange = () => pc.icecConnectonState == 'failed' && pc.restartIce();
```
Users shouldn't have to worry about `signalingState` at this level IMHO.

**Comment by alvestrand** [comment]
On general principles, I object to adding new API surface to WebRTC 1.0.

It's not clear to me that the original question is well formed; what in the quoted code indicates that the application ever wants to restart ICE?

**Comment by fippo** [comment]
@jan-ivar ah... i typically write such code to wait for signalingstate=stable or enqueue an operation until signalingstatechange -> stable. Which results in the same thing you do, but avoid ONN

**Comment by jan-ivar** [comment]
@alvestrand This isn't about adding new stuff, rather it's about fixing old stuff so it works with ONN.

I welcome you to read the [blog I just posted](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/), "Perfect negotiation in WebRTC", where I explore the full potential of ONN and rollback. My conclusion is that the WebRTC API is inherently racy, and will be too hard to use safely if we give up on the negotiation-needed spec algorithm. I find that algorithm critical to taming the state machine, and avoiding races in apps. Frankly, I doubt the working group would have gotten consensus for this much complexity without its remedial promise.  

ONN and rollback have been in the spec since, what, inception? Yet they're still not implemented right in the dominant browser. I suspect this has helped conceal that there are still issues around their use.

The fact that `{iceRestart: true}` works poorly with ONN is one of those issues I found. We owe it to users to fix that (and to fix ONN and rollback in all browsers).

I think the method I propose is a simple fix that does not significantly alter or add any new functionality.

> avoid ONN

@fippo Of course you avoid ONN. It's broken in Chrome.

**Comment by fippo** [comment]
hrm. What @jan-ivar proposes is not polyfill-able, right? He has a very good point that without this, ONN seems unfinished.

:+1:

**Comment by fippo** [comment]
one concern I have: I am observing calls to createOffer and look for {iceRestart: true} to determine if an ice restart happened. You are hiding this by using an internal slot.

wdyt about
```
pc.onnegotiationneeded = async () => {
  await pc.setLocalDescription(await pc.createOffer({iceRestart: pc.iceRestarting));
  io.send({desc: pc.localDescription});
}
```

**Comment by jan-ivar** [comment]
@fippo That would make the `restartIce` method a dud unless people explicitly did this? That seems a a bit lame.

I don't think we'd need to compromise `restartIce` to expose something like `pc.iceRestarting`, but TBH I don't understand the use-case for this. If this is for a polyfill, you're probably better off intercepting the `restartIce` method directly to obtain this information.

**Comment by jan-ivar** [comment]
@fippo Couldn't you also observe this by looking at the sdp from `await pc.createOffer()`?

**Comment by fippo** [comment]
@jan-ivar it would still trigger ONN

And yes, this could be observed by comparing the SDP between createOffer calls but that is... :-)

**Comment by jan-ivar** [comment]
But it would trigger ONN, and keep triggering ONN, in a loop...

**Comment by henbos** [comment]
I think restartIce() is a nicer API than createOffer({restartIce:true}) for the ONN reasons mentioned here. It's an action that requires negotiation, and all other things that fall into this category cause ONN. But I do think O/A is inherently a fragile API regardless due to signaling state surprises (what if SRD(offer) happens between createOffer() and setLocalDescription(offer)?), so I'm not sure this will ever be "perfect". As always there is a balance between how much effort we want to spend making things nicer versus how much we want to reach 1.0.

**Comment by jan-ivar** [comment]
> what if SRD(offer) happens between createOffer() and setLocalDescription(offer)?

I guess you didn't read [my blog](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/)? it solves that. See https://github.com/w3c/webrtc-pc/issues/2165.

> so I'm not sure this will ever be "perfect".

Well, I didn't call my blog *"Perfect negotiation in WebRTC"* for nothing. 🙂 I do actually believe I've solved the fragility of it. Happy to have people poke holes in it, if they can.

> making things nicer versus how much we want to reach 1.0.

I'm super cognizant of the need to reach 1.0. That's I think it is critical to make this glare-proof, and to finish up what we started. Negotiationneeded right now is broken as an API IMHO.

That's why I've opened the recent series of issues to tie up lose ends, not create new ones.

**Comment by aboba** [comment]
@fippo In ORTC, an ICE restart can potentially be done in multiple ways, some of which may also supported in [WebRTC-ICE](https://w3c.github.io/webrtc-ice/), such as allowing`RTCIceTransport.start()` to be called multiple times.

**Comment by aboba** [comment]
@alvestrand Not clear to me that a `restart` method can't be emulated:

. . .
var options = {iceRestart: false} ;

async function negotiate() {
  await pc.setLocalDescription(await pc.createOffer(options));
  io.send({desc: pc.localDescription});
}
pc.onnegotiationneeded = () => negotiate();
pc.oniceconnectionstatechange = (e) => {
  if (pc.iceConnectonState == 'failed') {
    options.iceRestart = true);
  }
};
. . .

**Comment by jan-ivar** [comment]
@aboba That won't trigger renegotiation, so it won't do anything.

**Comment by alvestrand** [comment]
pc.onnegotiationneeded = async () => {
  await pc.setLocalDescription(await pc.createOffer());
  io.send({desc: pc.localDescription});
}

actulally allows shimming in a RestartIce method, like this:

RTCPeerConnection.prototype.restartIce = function() {
   this.iceRestartNeeded = true;
   pc.onnegotiationneeded();
}

pc.onnegotiationneeed = async() => {
  await pc.setLocalDescription(await pc.createOffer({iceRestart: this.iceRestartNeeded});
  io.send({desc.pcLocalDescription});
}

and (if you want to emulate your proposed patch perfectly):

pc.addEventListener('signalingstatechange', () => {
   if (this.signalingstate == 'stable) {
     this.iceRestartNeeded = false;
  }
}

Point being - there seems to be nothing in the new API that can't be done by the user if the user desires it.

What I dislike about the new API surface is that it seems like it's doing an imperative action ("RestartIce"), while what it's actually doing is (probably) triggering a negotiation request, which will just call back out to user code. Why should the user call a method to call his own code?

**Comment by jan-ivar** [comment]
>```
> RTCPeerConnection.prototype.restartIce = function() {
>   this.iceRestartNeeded = true;
>   pc.onnegotiationneeded();
> }
> ```

Like @fippo's [above](https://github.com/w3c/webrtc-pc/issues/2167#issuecomment-480880197), this polyfill will throw `InvalidStateError` if called in anything but `"stable"` state. Since the goal of this method is to abstract away knowledge of the signaling state, both of these polyfills fail miserably, proving my point that we need to fix this, and not leave it to JS.

The polyfills also severely underestimate all the corner-cases this method handles. Here are its [WPT tests](https://phabricator.services.mozilla.com/D30978#C975484NL1), which all pass in Firefox's implementation (which I haven't landed yet, as it would upstream tests to WPT prematurely, though I'm happy to do so if there's interest):
* }, "restartIce() returns whether state changed");
* }, "restartIce() fires negotiationneeded");
* }, "restartIce() causes fresh ufrags");
* }, "restartIce() survives remote offer");
* }, "restartIce() is satisfied by remote ICE restart");
* }, "{iceRestart: false} overrides and cancels local restartIce()");
* }, "restartIce() survives rollback");
* }, "restartIce() survives remote offer containing partial restart");

These are all desirable behaviors that are in the PR. They're desirable, because the opposite of any of these behaviors would be surprising, and probably lead to application bugs in real-world situations.

While it may be possible to write a polyfill that does all that, I doubt many would get it right.

> What I dislike about the new API surface is that it seems like it's doing an imperative action ("RestartIce"), while what it's actually doing is (probably) triggering a negotiation request, which will just call back out to user code.

The same can be said about `createDataChannel`, `addTrack`, `removeTrack`, `addTransceiver`, and `direction`. Yet this is the paradigm we've chosen for actions that require negotiation, as @henbos points out [above](https://github.com/w3c/webrtc-pc/issues/2167#issuecomment-481709826). `{iceRestart: true}` is the outlier.

That said, I'm happy to bikeshed. `pc.addIceRestart()`, `pc.restartIce = true;` etc.

> Why should the user call a method to call his own code?

I can appreciate that a working `negotiationneeded` being quite new with Chrome 73, that it might take a while to appreciate the benefits of separating out negotiation as a low-level detail from the rest of one's application logic.

To fully appreciate it, I imagine a hypothetical `RTCPeerConnection` API where all the negotiation methods are removed, `setLocalDescription`, `setRemoteDescription`, `createOffer`, `createAnswer`, `addIceCandidate`, `onicecandidate`, `onnegotiationneeded`, and negotiation is handled automagically for the application. This exercise forces us to consider where in the remaining API to put controls for things the application cares about, like the need to restart ICE.

This isn't merely hypothetical either. It's the premise of [perfect negotiation](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/), my blog which I've added a new preface to. I highly recommend re-reading it before our upcoming virtual interim next week, as I'll be relying on it heavily. A lightbulb went on, is what I'm trying to share.

**Comment by jan-ivar** [comment]
> What I dislike about the new API surface is that it seems like it's doing an imperative action
> ("RestartIce"), while what it's actually doing is (probably) triggering a negotiation request,
> which will just call back out to user code.

Arguably, when `negotiationneeded` is configured correctly, this method ***is*** the imperative action that triggers ICE to be restarted.

It will keep triggering the `negotiationneeded` event until an ICE-restarting negotiation has completed. I don't know what more we would expect an imperative `restartIce()` method to do.

Its predecessor never started negotiation:
```js
await createOffer({iceRestart: true}); // no-op alone
```
