### ISSUE TITLE
Clarify the definition of "playout" for `RTCRtpContributingSource`.

### ISSUE THREAD

**Issue by chxg** [w3c/webrtc-pc#2172]
This is related to [WebRTC Issue 10545](https://bugs.chromium.org/p/webrtc/issues/detail?id=10545).

There seem to be some confusion around the exact definition of "playout" for [RTCRtpContributingSource](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcontributingsource):

1. **After receiving a packet. Before it's added to the jitter buffer.**

This interpretation is supported by:

> The browser MUST keep information from RTP packets _received_ in the previous 10 seconds.

2. **After a packet is removed from the jitter buffer. Before the samples/frames are delivered to `MediaStreamTrack`.**

This interpretation is supported by:

> When the first audio or video frame contained in an RTP packet is _delivered_ to the RTCRtpReceiver's MediaStreamTrack for playout...

3. **Exactly when the packet payload is physically played out on the monitor/speaker.**

This interpretation is supported by:

> The timestamp of type DOMHighResTimeStamp [HIGHRES-TIME], indicating the most recent time of _playout of media_ that arrived in an RTP packet originating from this source.

WebRTC currently implements (1). It updates `RTCRtpContributingSource` when a packet is received from the network. This is problematic. There are, for example, no guarantees that received packets are ever going to be played out (e.g. audio having already done concealment beyond the RTP timestamp of the packet payload). Packet reordering may also cause packets with lower sequence numbers to overwrite the information of packets with a higher sequence number.

I believe that (3) would be ideal in terms of usefulness, and ideal in terms of how a normal person would interpret the spec, but it's unfortunately not implementable in practice. An implementation of the spec will rarely have access to frame-perfect `onPhysicallyPlayedOut()` callbacks.

This leaves us with (2), which should be both implementable and useful.

**Comment by jan-ivar** [comment]
"Playout" is 3. Isn't that clear? This is what Firefox implements. The primary goal of this info is audio bars visually synced with playing video.

**Comment by na-g** [comment]
As @chxg says, physical device playout time isn't knowable in practice. Firefox records the levels into a 10 second rolling history when the packet is received and adjusts the playout time based on the jitter buffer at time of reception. This sounds like what (lib)WebRTC does. In practice this seems to yield good results for the use cases that @jan-ivar mentions.

**Comment by chxg** [comment]
Thanks for the information!

So if I understand it correctly, then Firefox stores a `RTCRtpContributingSource`-like record at (1) but sets its timestamp to be an estimate of (2). Chrome is more naive in that it both records at (1) and timestamps for (1). Neither implementation tries to timestamp for (3) today. The exact lines of code for audio seem to be in [`Channel::OnReceivedPayloadData()`](https://dxr.mozilla.org/mozilla-central/rev/02b89c29412b6c1444fe32a4847e5261e2bb3d00/media/webrtc/trunk/webrtc/voice_engine/channel.cc#721) for Firefox and [`ChannelReceive::OnRtpPacket()`](https://cs.chromium.org/chromium/src/third_party/webrtc/audio/channel_receive.cc?l=594&rcl=852bffb6063aa36814c89a58390581e59643f1fb) for Chrome.

Would it make sense to improve the spec so that it better matches our two implementations?

My proposal would be to make the spec so that:

- Each `RTCRtpContributingSource` stores info about precisely one audio or video frame. This is already strongly hinted at by the existing spec. Aggregated stats that span multiple frames are more appropriately placed in [RTCStats](https://w3c.github.io/webrtc-pc/#rtcstats-dictionary).

- Each `RTCRtpContributingSource` is ideally recorded when the audio or video frame is delivered to RTCRtpReceiver's MediaStreamTrack for playout. I will make changes to WebRTC to move the recording of the info from `OnRtpPacket()` to [`ChannelReceive::GetAudioFrameWithInfo()`](https://cs.chromium.org/chromium/src/third_party/webrtc/audio/channel_receive.cc?l=316&rcl=852bffb6063aa36814c89a58390581e59643f1fb) for audio and [`VideoReceiveStream::OnFrame`](https://cs.chromium.org/chromium/src/third_party/webrtc/video/video_receive_stream.cc?l=487&rcl=852bffb6063aa36814c89a58390581e59643f1fb) for video.

- `RTCRtpContributingSource.timestamp` is re-defined as storing a timestamp of when the audio or video frame is delivered to RTCRtpReceiver's MediaStreamTrack for playout.

I believe that making the spec more precise would be helpful for when we later want to add more detailed breakdowns of per-frame timestamps.

**Comment by henbos** [comment]
@chxg 
> ...when its audio or video frame is delivered to RTCRtpReceiver's MediaStreamTrack for playout...

Playout does not happen on a track. The track is just the middleman, playout happens some time after passing samples/frames off to its sinks. Isn't that right, @guidou ?

@jan-ivar 
> "Playout" is 3. Isn't that clear? This is what Firefox implements. The primary goal of this info is audio bars visually synced with playing video.

Which playout? As far as I can tell, the last step that is within the scope of WebRTC is delivery of samples/frames to the remote MediaStreamTrack. But the track may have 0, 1 or multiple sinks. Each sink could in theory add additional delay. Maybe they cause playout on different speakers, with different software and hardware buffers.

If playout means "the track is handing off samples/frames to its sink" then I think I understand it. If you are going further than that, then it sounds like you are going out-of-scope of WebRTC and Media Capture and Streams.

Am I misunderstanding how this works?

When I was advising the author of https://github.com/w3c/webrtc-pc/issues/2177, @drkron, this is what I told him.

Whether or not "playout" is a sensible description, I do think it needs to be clarified.

**Comment by henbos** [comment]
Different sinks can have different properties and mechanisms for transforming the source stream as well.

**Comment by henbos** [comment]
> Firefox records the levels into a >10 second rolling history when the packet is received and adjusts the playout time based on the jitter buffer at time of reception.

Playout time = receive time + jitter buffer size. Or playout time = time when they exit the jitter buffer?

**Comment by henbos** [comment]
Proposal:
- Define playout as "when samples/frames exit the jitter buffer".

**Comment by chxg** [comment]
I don't believe that it should be defined in terms of "jitter buffer". There are too many other parts (e.g. "frame spacing", "decoding", "rendering delay", "sync buffer", etc.) that may or may not be included in "jitter buffer" depending on implementation.

The best definition seems to be:

> Audio or video frame is delivered to RTCRtpReceiver's MediaStreamTrack.

It's more or less identical to the existing definition, but gets rid of the word "playout" since the latter only causes confusion.

**Comment by henbos** [comment]
I like your definition, it probably most accurately describes "playout" without leaving the scope of this spec.

Btw has it not already been decoded when it exits the jitter buffer? Maybe the difference between "exists the jitter buffer" and "delivered to the track" is splitting hairs? (In case implementation difficulty varies between the two but its not noticeable?)

How does @chxg's definition sound to other browsers, particularly Firefox which I believe is the only browser that has been faithful in trying to interpret playout?

**Comment by chxg** [comment]
> Btw has it not already been decoded when it exits the jitter buffer? Maybe the difference between "exists the jitter buffer" and "delivered to the track" is splitting hairs? (In case implementation difficulty varies between the two but its not noticeable?)

The flow is roughly:

1. Network
2. Jitter Buffer
3. Decoder
4. Sync Buffer (Audio) or Render Buffer (Video)
5. MediaStreamTrack
6. Other kinds of intentional delays?
7. OS and Hardware Buffers
8. Playout

An implementation could decide to pop packets from the jitter buffer as soon as all earlier packets (i.e. packets with lower sequence numbers) have arrived. Frames that are decoded too early (to be sent to the track) could be parked in the sync/render buffer. I think that WebRTC's video code (unlike its audio code) might already behave this way today.

**Comment by henbos** [comment]
OK thanks for clarifying!

**Comment by jan-ivar** [comment]
@na-g knows the Firefox implementation best, so I'll leave it to him to answer the detail questions.

One additional point I'd like to make, since we seem to be asking for tighter specification of this API:

Firefox does not return timestamps in the future. That way, someone naively polling the (synchronous) API would receive information only later once playout time is *now*.

We arrived at this after a good faith audio-bars implementation of the spec: *"including the most recent time a packet that the source contributed to* ***was*** *played out."*

**Comment by na-g** [comment]
@henbos, play-out time = reception time + jitter buffer time depth.

As @chxg pointed out, the playout time will always be an estimate. For the use case of detecting when someone is speaking, which is how I understand this data is to be used, I think that recording at any point in @chxg's flow at or deeper than 2 is sufficient. The further down the flow the data are recorded, the greater accuracy becomes.  If the goal is to achieve that high level of accuracy, then I would think that this would be a callback and not a polling interface. I think the question of original intent is important here. I would to like to float phrasing the playoutTime as an estimate, and allowing implementations to leverage the knowledge of their internals to make the **best possible** estimate.

**Comment by henbos** [comment]
OK. So the estimate updated when the packet arrive, meaning the timestamp observed in JS could be _in the future_?

So getSSRCs/getCSRCs are referring to "latest packet", but timestamp is referring "estimated playout of latest packet"?

**Comment by henbos** [comment]
I am happy with this being the case and the spec clarifying that it is a timestamp. I think having information about latest packet as well as estimates for playout allows extensions covering multiple use cases.

**Comment by chxg** [comment]
How about we do this:

1. I'll first create a PR to make it so that each `RTCRtpContributingSource` SHOULD be recorded when a frame from a RTP packet is delivered to `MediaStreamTrack`. `timestamp` would then be defined in terms of the instant of that delivery. Firefox's current implementation doesn't do the SHOULD, but its `timestamp` is still spec-compliant under the "may be implemented in any manner so long as the end result is equivalent" rule.

2. I'll afterwards create a second issue+PR to add a separate `playoutTimestamp`. We could give it more vague requirements:

> The estimated timestamp of when the frame, indicated by `timestamp`, was (or will be) physically played out. Its reference clock is the same as the reference clock for `timestamp`. The `playoutTimestamp` SHOULD include delays from sound card buffers and rendering, if that information is available. It MAY point to an instant in the future. This member MAY be absent if the user agent doesn't have a better estimate than the value stored in `timestamp`.

**Comment by drkron** [comment]
If I understand correctly, all timestamps will correspond to the same audio/video frame. What do you think of adding the RTP timestamp of that frame as an identifier for the audio/video frame, as suggested in #2177?

**Comment by chxg** [comment]
> If I understand correctly, all timestamps will correspond to the same audio/video frame. What do you think of adding the RTP timestamp of that frame as an identifier for the audio/video frame, as suggested in #2177?

I think that it's a splendid idea, but there are tons of tiny details to think about when speccing it out. Let's have that discussion in the other ticket.
