### ISSUE TITLE
Spec steps on stop() underestimate BUNDLE problem.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2176]
Our [BUNDLE warning](http://w3c.github.io/webrtc-pc/#methods-8) says:
> Note
> 
> If this method is called in between applying a remote offer and creating an answer, and the transceiver is associated with the "offerer tagged" media description as defined in [BUNDLE], this will cause all other transceivers in the bundle group to be stopped as well.

This suggests the problem is limited to calling `stop()` in `"have-remote-offer"`, but the same problem exists if `stop()` has been called *before* SRD(offer).

> To avoid this, one could instead stop the transceiver when signalingState is "stable" and perform a subsequent offer/answer exchange.

This is true only if we replace "a subsequent" with "an immediate", and assume an SRD(offer) cannot come in beforehand. It also assumes our offer isn't rolled back.

**Comment by henbos** [comment]
Stop()... our old nemesis is back. Jan-Ivar I think we need to burn the body once we are done with it for it not to come back alive.

**Comment by jan-ivar** [comment]
Actually, it's more than just the note. Step 6 underestimates the problem as well:

> 6. If connection's signaling state is have-remote-offer and

In the case where `stop()` is called *before* SRD(offer) then step 6 will not stop all bundled transceivcers, leaving them unstopped, even though their underlying transport will be stopped/nonworking.

**Comment by dontcallmedom** [comment]
@jan-ivar can this be closed now that that  #2220 has been merged?

**Comment by aboba** [comment]
PR has been merged, so am closing this issue.
