### ISSUE TITLE
Add RTP timestamp to RTCRtpContributingSource

### ISSUE THREAD

**Issue by drkron** [w3c/webrtc-pc#2177]
One use case for this would be to synchronize external events to the corresponding RTP packets.

**Comment by jan-ivar** [comment]
@drkron What do you mean by "external events"? Can you give an example?

**Comment by alvestrand** [comment]
The longer proposal (a lot more clocks) I made some time ago is here:
https://alvestrand.github.io/webrtc-framelog/

**Comment by na-g** [comment]
RTPContributingSource is provided by polling interface and makes no guarantee that a specific packet in a stream will ever be reported.  Any packets that are not played out may not be reported at all. The timing of its output is based on playback, not network events. All of these reasons make it a difficult interface to correlate to events. A reception time stamp would help with the last of those issues.

**Comment by drkron** [comment]
I'm happy for the discussion.

The use case I have in mind is for a game streaming service that is based on WebRTC. So what we need is a way of tying an input event from the person playing a game to the particular frame that was displayed at that time. By doing this it would be possible for the game engine to compensate for latency in the network (up to a certain level).

So the RTP timestamp is in this case just an ID of the frame.

**Comment by chxg** [comment]
I think that a per-frame ID (of some kind) would be very nice to have for `RTCRtpContributingSource`. For example: It would allow a caller to tell if two consecutive `getContributingSources()` calls returned the info about the exact same frame, or if they returned info about two different frames but `timestamp` didn't have enough resolution to tell the frames apart.

There are a bunch of challenges for the spec:

1. A single RTP packet may contain a payload that maps to multiple frame-deliveries to `MediaStreamTrack`.

    For example:
    - Audio packets store 20 ms of audio but WebRTC delivers 10 ms per `GetAudioFrameWithInfo()` call.

2. Multiple RTP packets may be involved in the decoding of a single frame.

    For example:
    - Video key frames.
    - Audio packets that are not aligned with audio outputs. Say we have a packet with audio for time period [1005, 1025) and another for [1025, 1045), but WebRTC is outputing [1020, 1030). It would then take audio samples from both packets.
    - Audio during acceleration. Similar to the case above.

3. Frames that are decoded from packets that don't follow the usual rules about RTP timestamps and sequence numbers.

    For example:
    - Transport-level forward error correction.
      - E.g. Flexfec.
      - We'll presumably use the recovered RTP timestamp.
    - In-band forward error correction.
      - E.g. Opus FEC where WebRTC can use the data from packet N+1 to decode a low-quality version of packet N.
      - Do we use the RTP timestamp for N+1 or the "would have been" RTP timestamp for N?
      - Probably most sense to compute and use the info for N?
      - Or maybe not record anything for this case at all?
    - Retransmission.
      - The retransmitted packet should have the same RTP timestamp as the original.

**Comment by drkron** [comment]
@chxg Thanks for your comments.
I agree that there are a few edge cases that need to be defined. I just updated the PR according to the review comments and specified it as: "The *last* RTP timestamp of the media played out at timestamp"
To me it make sense to specify that it's the last RTP timestamp. That also solves most of the cases you mentioned and naturally preserves causality.
