### ISSUE TITLE
Define time order of results from getContributingSources() et al

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2189]
When returning a sequence, defining its order whenever possible, helps web compat.

For example: A naive implementation might use this for some purpose:
```js
const {audioLevel} = receiver.getSynchronizationSources()[0];
```

...which would work most of the time, when `receiver.getSynchronizationSources().length` is either `1` (good audioLevel) or `0` (`undefined`).

Except once in a blue moon when the SSRC changes for whatever reason, and `receiver.getSynchronizationSources().length == 2` for about 10 seconds.

A browser that returned oldest first would show outdated audio levels for 10 seconds.

I propose we sort the results from newest->oldest based on timestamp (playout time)

**Comment by jan-ivar** [comment]
I also propose we explicitly omit information with a playout timestamp in the future. See https://github.com/w3c/webrtc-pc/issues/2172#issuecomment-486740788

**Comment by na-g** [comment]
Sorting by descending by playout time seems a reasonable thing to do as the most recently played information is the most relevant. @jan-ivar, as to omitting future results, that is Firefox's behavior (and has been since these APIs were implemented).
