### ISSUE TITLE
Says to count datachannel label & protocol in bytes, but they're USVString

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2191]
[Spec](https://w3c.github.io/webrtc-pc/#dom-peerconnection-createdatachannel) says:
*"If [[DataChannelLabel/DataChannelProtocol]] is longer than 65535 bytes, throw a TypeError. "*

But `label` and `protocol` are `USVString`.

https://github.com/w3c/webrtc-pc/issues/543#issue-140173549 says these are *"mapped into UTF-8 in the underlying protocol"*, so we should specify this conversion before counting in these validation steps.

**Comment by lgrahl** [comment]
FYI, it is defined in [DCEP, sec 5.1](https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-09#section-5.1).

**Comment by alvestrand** [comment]
So "if" should be rewritten as "if the UTF-8 representation of".
