### ISSUE TITLE
Make RTCRtpContributingSource::rtpTimestamp required

### ISSUE THREAD

**Issue by drkron** [w3c/webrtc-pc#2197]
RTP timestamp was added to RTCRtpContributingSource in #2177.
In hindsight I think it should have been marked as "required".

**Comment by jan-ivar** [comment]
Do you mean mandatory to implement? A dictionary member can also have the `required` dictionary, but so far we haven't annotated any of the stats dictionary members as required (the `required` keyword has only marginal normative meaning and are largely for documentation when used in dictionaries that are never used as inputs).

**Comment by alvestrand** [comment]
If it's required, it's a spec violation to not implement it.
I don't like much adding extensions that break compliance of older implementations.

**Comment by jan-ivar** [comment]
Sorry I was thinking about stats.

**Comment by henbos** [comment]
@drkron Can you create a PR?

**Comment by drkron** [comment]
PR created.
