### ISSUE TITLE
Is it possible to manipulate playout-delay extention at SDP of RTCSessionDescription directly affect playout (playback) delay at remote peer connection?

### ISSUE THREAD

**Issue by guest271314** [w3c/webrtc-pc#2213]
Is it possible to manipulate playout-delay extention header at SDP of local RTCSessionDescription directly affect playout (playback) delay at remote peer connection? 

That is, to compose an appropriate character, value pair for the purpose of delaying media being playout (playback) at remote peer, for example, for 10 seconds (given a single or the predominant timing mechanism being used by WebRTC, when local stream is at 10 of playback, remote stream is at 0 of playback)?

Or is the purpose of playout-delay header extension for statistics, i.e., `getStats()`?

-- 

Relevant documentation, Pull Requests, comments

playout-delay https://webrtc.org/experiments/rtp-hdrext/playout-delay/

> The header is attached to the RTP packet by the RTP sender when it needs to change the min and max smoothing delay at the receiver. Once the sender is informed that at least one RTP packet which has the min and max details is delivered, it MAY stop providing details on all further RTP packets until another change warrants communicating the details to the receiver again. This is done as follows:
> 
> RTCP feedback to RTP sender includes the highest sequence number that was seen on the RTP receiver. The RTP sender can track the sequence number on the packet that first had the playout delay extension and then stop sending the extension once the received sequence number is greater than the sequence number on the first packet containing the current values playout delay in this extension.

Chromium source rtp_header_extensions.cc https://chromium.googlesource.com/external/webrtc/+/e2a017725570ead5946a4ca8235af27470ca0df9/webrtc/modules/rtp_rtcp/source/rtp_header_extensions.cc#177

```
//   0                   1                   2                   3
//   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
//  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
//  |  ID   | len=2 |   MIN delay           |   MAX delay           |
//  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

jitterBufferDelay vs playoutDelay #223 https://github.com/w3c/webrtc-stats/issues/223

> SGTM I think playoutDelay is misleading, that could be a different stat if need be. - https://github.com/w3c/webrtc-stats/issues/223#issuecomment-341532688 

Playout delay #216 https://github.com/webrtc/webrtc-org/pull/216

**Comment by henbos** [comment]
This is an experimental header extension in webrtc.org which has not previously been discussed by the WebRTC WG, perhaps file an issue on https://crbug.com/webrtc/ ?

**Comment by guest271314** [comment]
@henbos The existence of the extension 

> which has not previously been discussed by the WebRTC WG

has already caused some confusion in the wild (for users that browse various WebRTC documentations and experiment themselves)

Change playout delay in WebRTC stream https://stackoverflow.com/q/56510151

> This is what i was talking about: https://webrtc.org/experiments/rtp-hdrext/playout-delay/. I can understand what playout-delay means but not how to configure it, or if it's even at all possible 

https://gist.github.com/jimmywarting/2296342bfb7a31ad26068659d1fd9fc9#gistcomment-2945243

> Not sure if that extension is implemented. 

https://gist.github.com/jimmywarting/2296342bfb7a31ad26068659d1fd9fc9#gistcomment-2945251

> I can see the extension implemented in the sdp (chrome)
> 
> ```
> a=mid:0
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:12 urn:3gpp:video-orientation
> a=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> 
> HERE
> a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> 
> a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
> a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
> a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> ```

https://gist.github.com/jimmywarting/2296342bfb7a31ad26068659d1fd9fc9#gistcomment-2945252

> Believe it's option B 
> >  a 10 second delay between each media pack the remote portion of the code receives? 

> I want to use one camera to transfer the live stream to another device and throughout the hole session it should play the video with an added delay on the playback to it so you can see something you did afterwards.

https://gist.github.com/jimmywarting/2296342bfb7a31ad26068659d1fd9fc9#gistcomment-2945272



Instead of attempting to delegate the issue to another board, for clarity and to avoid confusion, can users get a simple answer to the very simple question?

**Comment by guest271314** [comment]
@henbos https://bugs.chromium.org/p/webrtc/issues/detail?id=10759. At the minimum the OP of the SO question should get a complete answer to their inquiry.

**Comment by henbos** [comment]
> Instead of attempting to delegate the issue to another board, for clarity and to avoid confusion, can users get a simple answer to the very simple question?

I'm saying the WG is just as confused as you are ;) I can ask around (since I also work in Chrome) but it appears Chrome is doing something outside of specs of the WG.

**Comment by guest271314** [comment]
@henbos 

> I'm saying the WG is just as confused as you are ;) I can ask around (since I also work in Chrome) but it appears Chrome is doing something outside of specs of the WG.

Am not trying to assess blame. `goog-remb` is described by webrtcHacks (https://webrtchacks.com/wp-content/themes/parament/custom-pages/sdp/68.html) as

 

> The prefix goog- means that is still something implemented only by Google and non standard. 

however, Firefox 69 includes `goog-remb` in the SDP of Mozilla WebRTC implementation (http://lists.w3.org/Archives/Public/public-webrtc-logs/2019Jun/0105.html)

> Chromium  `a=rtcp-fb:102 goog-remb`
> Firefox `a=rtcp-fb:120 goog-remb`

The various concerns can sort out the blame, if any, for extending SPD beyond a given specification. 

Firefox still non-standard `mozCaptureStream()`. 

Am asking _how_ the feature is intended to work.

**Comment by henbos** [comment]
> Am asking how the feature is intended to work.

The WG does not know the intent. The right Chrome people should know, which is why I'm directing you to the chromium/webrtc issue trackers.
