### ISSUE TITLE
Use consistent internal slot terminology (editorial)

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2226]
There are 94 matches for `.[[`, and 165 matches for `'s [[`. It's

> Set *connection*.[[CurrentLocalDescription]] to *connection*.[[PendingLocalDescription]].

vs.

> Set *connection*'s [[CurrentLocalDescription]] internal slot to *connection*'s [[PendingLocalDescription]] internal slot.

We should pick one and be consistent.

I'm partial to the former since it's more compact and predominant in [ECMAScript](https://tc39.es/ecma262/).

Thoughts?

**Comment by aboba** [comment]
My understanding is that the latter approach was considered the favored style (which may explain why it has more matches).  @stefhak may have a better understanding of the history.

**Comment by jan-ivar** [comment]
Some discussion on this can be found in https://github.com/whatwg/streams/issues/178.
