### ISSUE TITLE
restartIce(): Look at only ufrag or (ufrag,pwd)?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2229]
The spec talks only about comparing ufrags, but ICE credentials involves both ice-ufrag and ice-pwd. These are in separate a= lines.

In my [work-in-progress implementation](https://webrtc-review.googlesource.com/c/src/+/144941/10/pc/peer_connection.h#1395) I assumed that "ICE credentials" refers to both, not just the ufrag part, but it would perhaps be strange if changing the pwd counts as a restart? I'm not sure what that would mean though...

@jan-ivar Should we only look at ufrag or at (ufrag,pwd)?

**Comment by steveanton** [comment]
JSEP says an ICE restart is indicated if both the ufrag *and* pwd change in a call to SLD: https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.9

But it also says that an ICE restart is requested by a call to SRD with either ufrag *or* pwd changed: https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.10

**Comment by jan-ivar** [comment]
FWIW Firefox looks at [both](https://searchfox.org/mozilla-central/rev/22b330ecb3edba1536a54887060cbdd09db21c59/media/webrtc/signaling/src/sdp/SdpHelper.cpp#106) when deciding whether to restart.

**Comment by jan-ivar** [comment]
Unfortunate phrasing on my part. Firefox restarts if *either* the ufrag *or* the pwd  has changed (or both. Thanks grammar).

**Comment by jan-ivar** [comment]
[section 5.9](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.9) says: *"Or, if the ICE ufrag and password values have changed, trigger the ICE agent to start an ICE restart"*

English is imprecise, but I think had the intent been to not trigger unless *both* values have changed, then it would have said so: E.g. *"if the ICE ufrag and password values have both changed"*

This is also SLD, where it would be hard to not have both values change when they change.

I'd put more stock in 5.10 (SRD) where it needs to consider invalid inputs. Thus I'd interpret the intent here to be to trigger if the values *as a group* have changed, meaning *either or both* of the values have changed.

It also makes more sense to me that way. If we don't restart when ice-pwd changes, we would need to figure out what should happen then.

Adding a PR.
