### ISSUE TITLE
Factor out RTCConfiguration validation

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#223]
The current description of `updateIce()` allows for a partial application of values, or might be interpreted as doing so.

It makes sense to first validate, then act.  And since this is a process that is also required for the constructor, a separate section makes more sense.

**Comment by stefhak** [comment]
I agree, we should do this.

**Comment by alvestrand** [comment]
I think this is true for the setConfiguration() description in the current github version too - the algorithm says "first set some stuff, then throw an error if some other stuff is wrong". (not yet published as an editors' draft).

**Comment by adam-be** [comment]
Fixed by #211
