### ISSUE TITLE
Mark voiceActivityDetection and dtx as Feature At Risk (Was: Is voiceActivityDetection still needed?)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2236]
With restartIce() we no longer need {iceRestart:true}, and with parameterless setLocalDescription() we don't need createOffer() even!
...or do we? There is one "missing piece", possibly, and that is the voiceActivityDetection in RTCOfferAnswerOptions. Definition:

> Many codecs and systems are capable of detecting "silence" and changing their behavior in this case by doing things such as not transmitting any media. In many cases, such as when dealing with emergency calling or sounds other than spoken voice, it is desirable to be able to turn off this behavior. This option allows the application to provide information about whether it wishes this type of processing enabled or disabled.

I'm not sure how this is supposed to be implemented, but it looks like Chrome is implementing it as [removing all CN codecs from the SDP](https://cs.chromium.org/chromium/src/third_party/webrtc/pc/media_session.h?type=cs&sq=package:chromium&g=0&l=105). I don't think we should have another API for modifying the set of codecs. We already have setCodecPreferences().

In order to make completely createOffer() superflous, discouraged, and perhaps even [one day](https://www.youtube.com/watch?v=vAUOPHqx5Gs) deprecated, should we do one of the following?
1. Deprecate voiceActivityDetection
2. Specify VAD bit as part of codec capabilities or parameters
3. Allow controlling the voiceActivityDetection from setConfiguration() instead of RTCOfferAnswerOptions.

**Comment by henbos** [comment]
@jan-ivar Do we care about voiceActivityDetection?

**Comment by jan-ivar** [comment]
We do not implement it. With my chair hat, I believe we're considering marking VoiceActivityDetection as a feature at risk.

**Comment by Orphis** [comment]
Isn't that the same feature as the encoding parameter [dtx](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-dtx) ? This could be controlled in the application layer then.
Note that no one has implemented this coding parameter yet either to my knowledge.

**Comment by henbos** [comment]
I'll create a PR to mark is feature at risk

**Comment by aboba** [comment]
@orphis `dtx` is about enabling/disabling discontinuous transmission, assuming it was negotiated (e.g. CN codecs in Offer/Answer).  VAD is about whether to negotiate it.  Neither has been implemented AFAIK.

**Comment by aboba** [comment]
@henbos Suggest including both `dtx` and VAD in the "feature at risk" designation.

**Comment by henbos** [comment]
Aye aye, cap'n
