### ISSUE TITLE
 API for codec performance

### ISSUE THREAD

**Issue by chcunningham** [w3c/webrtc-pc#2241]
Hi Group,

I work on the MediaCapabilities (MC) [spec](https://w3c.github.io/media-capabilities/) ([explainer](https://github.com/w3c/media-capabilities/blob/master/explainer.md)). I've had a few requests from WebRTC apps to expand this API to describe WebRTC encode/decode performance. The use cases make sense but I have some ergonomics concerns and I'd like to collab w/ RTC experts here to explore the options. 

**MediaCapabilities today**
- The primary interface is [decodingInfo()](https://w3c.github.io/media-capabilities/). This was designed to replace \<video\>.canPlayType(...). It describes "file" (foo.mp4) and "media-source"  (YouTube, Netflix, ...) [decoding types](https://w3c.github.io/media-capabilities/#mediadecodingtype). It does not include WebRTC. This is implemented in Chrome, Firefox, and Safari. 
- The spec also defines [encodingInfo()](https://w3c.github.io/media-capabilities/#dom-mediacapabilities-encodinginfo), which covers "recording" (MediaRecorder) and "transmission" (WebRTC) [encoding types](https://w3c.github.io/media-capabilities/#mediaencodingtype). This part of the spec is less mature and not shipped by any browser. The "recording" part is conceptually a simple reversal of file-decoding. The "transmission" (WebRTC) type seemed like a natural next step (MediaRecorder after all is ~part of WebRTC family). This interface is very roughly spec'ed; it needs some love (or maybe removal). 

**WebRTC use cases are very similar to those from the media playback world.** Apps would like to know before-hand what limits to set for resolution/framerate/bitrate such that the machine is able to maintain a buttery smooth (timely) user encoding/decoding experience (ignoring the small matter of network issues). WebRTC's reference implementation helps out by automatically adapting encode resolution if the CPU is over-used, but this requires the user to first have a bad experience before adapting back down (meanwhile, the camera may be left open at HD resolution, potentially wasting resources of a starving machine). 

Apps may also ask what codecs can be hardware accelerated to minimize battery drain.  

**Ergonomics: What shape should the API take? Where should it live?**
We took a closer look at implementing MC.encodingInfo() for "transmission" (WebRTC) encoding in Chrome, and a few things gave me pause. 

Most notably, WebRTC has existing capability APIs that seem like a natural place to describe codec performance. 
- The RTCRtpReceiver and RTCRtpSender inferfaces both define a getCapabilities() method, that returns a sequence of [RTCRtpCodecCapabilities](https://www.w3.org/TR/webrtc/#dom-rtcrtpcapabilities). Right away we see that RTC users can  ask about capabilities on both ends of the wire, not just the local machine. This is something MediaCapabilities can't do. 
- RTCRtpCodecCapability does not include performance info (e.g. max framerate, max resolution). But [the ORTC spec](http://draft.ortc.org/#codec-capability-parameters*) proposes new "codec capability parameters" for this object, including codec specific fields like "max-fs" (frame size) and "max-fr" (frame rate). Should this serve as a model to define similar in WebRTC?

Another issue we face is that WebRTC doesn't use the same mime-type codec strings from the \<video\> playback world (e.g. 'video/mp4; codecs="avc1.4d001e"' for \<video\> vs 'video/h264' in RTC). Its a little ugly to consider mixing these into MediaCapabilities and it smells like a hint that we're merging two worlds that might better be kept separate. 

Interested to get your thoughts! Thanks for reading.

**Comment by drkron** [comment]
Please see also issue #2219 which would enable a trial and error approach to the same problem.

**Comment by henbos** [comment]
Being able to tell which codecs are not only possible to use, but are also "smooth" or "efficient", even _before_ you request to use them is something that would be incredibly valuable. Many applications attempt to send HD, not even knowing if the codec has HW or SW support, and relying on degradation to "back down" if we are unable to send it. But like you said, by then you may already have had a bad experience. If you're on a laptop this means it will likely start sounding like a helicopter (at least in Chrome) - it will do what you asked for, but it is likely not the most optimal experience. I just did some CPU measurements and profiling of WebRTC Video in Chrome, and well, it's expensive.

It's good to have an API to let the application do the decision. For example, one application might value quality over everything, in which case being efficient is not a problem as long as it is smooth. Other applications might want to value efficiency over smoothness, as to not drain the battery.

I think even low-hanging fruit like "do we have HW support?" would be of great benefit, and other codec-specific properties. If we could tell what was "smooth" or "efficient" that would be amazing, it does make me wonder - how would we know? WebRTC applications can differ widely in complexity, including 1-1 video calls, or audio calls, or a 10 people all calling in to the same conference with HD cameras. All the [MediaCapabilitiesInfo](https://w3c.github.io/media-capabilities/#media-capabilities-info)s sound very binary. Could [MediaEncodingConfiguration](https://w3c.github.io/media-capabilities/#dictdef-mediaencodingconfiguration) be extended to make more precise quarries to the API, indicating if you are doing 1:1 or 1:10, for instance?

I don't think we should let "perfect" be the enemy of progress/"good enough". As-is, WebRTC could greatly benefit by richer Media Capabilities, and I would be very interested to join in any discussions around these APIs.

**Comment by henbos** [comment]
> The RTCRtpReceiver and RTCRtpSender inferfaces both define a getCapabilities() method, that returns a sequence of RTCRtpCodecCapabilities. Right away we see that RTC users can ask about capabilities on both ends of the wire, not just the local machine. This is something MediaCapabilities can't do.

RTCRtpSender.getCapabilities() lists the codecs and header extensions that can be negotiated for sending, and RTCRtpReceiver.getCapabilities() lists the codecs and header extensions that can be negotiated for receiving. It does not tell you what the other endpoint supports until this is negotiated with SDP (negotiating is performed with createOffer, setLocalDescription, setRemoteDescription and createAnswer, [here's an example](https://codepen.io/anon/pen/JQLEqR?editors=1010)).

Once negotiation is completed, getParameters() will tell you the current settings basically.
RTCRtpReceiver.getParameters() gives you very limited information: it's basically just a list of rids, which doesn't make much sense to me when I think about it, this has to do with simulcast, and while we support sending simulcast, receiving simulcast is kind of outside the spec? (Is this API mature?)
RTCRtpSender.getParameters() tells you about codecs and layers being sent and some properties and control knobs. This is very limited, but lets you know which codec is being sent.

RTCPeerConnection.getStats() also returns information about codecs ([RTCCodecStats](https://w3c.github.io/webrtc-stats/#dom-rtccodecstats)). In a legacy version of the API in Chrome, the [implementation](https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-implementation) string was implemented, and people could use it to figure out if HW or SW codecs was used after the fact, but this was very browser-specific (e.g. "in Chrome, 'libvpx' is used for SW"), and the new getStats() API this has not been implemented (yet), but this is an ugly API surface in my opinion, not designed for interoperability, more like debugging.

If we want to know about stuff like this prior to negotiating, as to allow the application to make wiser decisions, we need "capabilities", not "parameters". getCapabilities() might be one API surface for this, but it is also tied in to RTCPeerConnections and SDP. It would be great if we could de-couple capabilities from signaling protocol.

**Comment by aboba** [comment]
See WebCodecs proposal: https://discourse.wicg.io/t/webcodecs-proposal/3662

**Comment by aboba** [comment]
Copied to WebRTC-NV repo as Issue https://github.com/w3c/webrtc-nv-use-cases/issues/41
