### ISSUE TITLE
Control surface for header extensions

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2243]
For codecs we have getCapabilities() for figuring out what is supported by the browser, setCodecPreferences() for controlling what to negotiate, and getParameters() to see what was actually negotiated. In addition, getStats() can tell you more details (such as if multiple codecs were negotiated, which one is being used right now).

Should we have a similar API for header extensions? There is already getParameter()'s [headerExtensions](https://w3c.github.io/webrtc-pc/#dom-rtcrtpparameters-headerextensions) for reading what RTP header extensions were negotiated, but there is no way to detect what is supported without trial and error, and worse yet, if you want to control which ones are negotiated you have to munge SDP.

@jonex

**Comment by henbos** [comment]
Example: Chrome and Firefox support [abs-send-time](https://webrtc.org/experiments/rtp-hdrext/abs-send-time/) which allow receive-side congestion control by looking at the send-side timestamp. Chrome also supports [transport-wide-cc-extensions-01](https://tools.ietf.org/html/draft-holmer-rmcat-transport-wide-cc-extensions-01) which allows for send-side congestion control when used together with RTCP feedback mechanisms.

Related questions:
- How to control what is negotiated?
- Once negotiated, how to control which header extension-specific features are enabled?

In the case of congestion control, we might want to negotiate both for compatibility, but depending on application we may want to turn one of the congestion controls on or off if both are successfully negotiated.

In today's implementation, if both extensions are negotiated, it will use transport-wide-cc-extensions-01 and not abs-send-time. There may be use cases where we want to use both, and in other cases it would be superfluous to use both at the same time.

**Comment by Orphis** [comment]
[getCapabilities()](https://w3c.github.io/webrtc-pc/#dom-rtcrtpcapabilities-headerextensions) will tell you what is supported already.

**Comment by henbos** [comment]
Oh right, thanks. Based on getCapabilties(), should there be a setHeaderExtensionsPreferences() akin to setCodecPreferences()?

**Comment by alvestrand** [comment]
Given that we've said "no new features": I'd like to put this into the "extensions" category, which should be written up with an use case in webrtc-nv-use-cases and an extension spec to the base spec.

**Comment by aboba** [comment]
Copied to WebRTC-NV Issues: https://github.com/w3c/webrtc-nv-use-cases/issues/40
