### ISSUE TITLE
Mark Oauth as a "feature at risk"

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2246]
There are no current implementations of the [`RTCOauthCredentialDictionary`](https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#rtcoauthcredential-dictionary) so it should be marked as a "feature at risk".

**Comment by misi** [comment]
I want to add that feature.
I am going to implement this feature it in Firefox.

I think it is important to have this feature because
1.  there is no other way to achieve multi tenancy/realm (coTURN?).
2. No other standard RFC that could fit and work for WebRTC & TURN.
          * The REST (from JUberti) is an expired draft. 
          * Long Term Credential (user, realm,passwd) couldn't be hide credential in js application.
