### ISSUE TITLE
RTCDTMFToneChangeEventInit.tone is required

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2253]
As per https://w3c.github.io/webrtc-pc/#dom-rtcdtmftonechangeeventinit, RTCDTMFToneChangeEventInit.tone is mandatory.

As per https://web-platform-tests.live/webrtc/RTCDTMFSender-ontonechange.https.html, Chrome and Firefox treat it as an optional member, which then defaults to the empty string.

Additionally, Chrome requires a RTCDTMFToneChangeEventInit in RTCDTMFToneChangeEvent constructor as per spec.
Firefox makes it optional which allows creating an empty string tone event easily.

https://github.com/w3c/webrtc-pc/issues/789 decided to go with a mandatory attribute.
https://github.com/w3c/webrtc-pc/issues/816 induces that the constructor init is mandatory as well.

Either Chrome, Firefox and WPT test should be updated according the spec, if this is compatible with existing websites.
Or the spec should be updated to better align with implementations.

**Comment by jan-ivar** [comment]
Seems like a simple implementation bug to fix.

**Comment by alvestrand** [comment]
Decision: Change the spec to match the implementations.

**Comment by dontcallmedom** [comment]
this was closed by #2413 (tests at https://github.com/web-platform-tests/wpt/pull/20764)
