### ISSUE TITLE
Mark RTCRtpEncodingParameters.maxFramerate as "feature at risk"

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2260]
There are no current implementations of the `RTCRtpEncodingParameters` dictionary's [maxFramerate](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-maxframerate) member, so it should be marked as a "feature at risk".

**Comment by aboba** [comment]
There was an "intent to implement" statement filed for `maxFramerate`.

**Comment by Orphis** [comment]
Yes, I confirm we want to implement it in Chrome, just didn't have the bandwidth yet for it.
