### ISSUE TITLE
.mid attribute - random or Null when MID is not present in SDP?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#227]
https://github.com/w3c/webrtc-pc/pull/193 added a .mid property that, if there is not a value present in the SDP, will be set to a random value.

Using a random value rather than letting the attribute be null is still controversial; @juberti argued in favor of the random value.

**Comment by alvestrand** [comment]
One side of the exchange will always be WebRTC.
We will always generate an mid in answer, whether or not it is in the offer, so there will always be an mid associated with each m-line. So it's consistent to reflect this value in RTPSender and RTPReceiver objects.

**Comment by martinthomson** [comment]
RTPSender is created before any SDP. Is a null acceptable prior to creating an offer (or answer)? Our should the browser allocate an mid abd change it in the case that it turns out to be the answerer?

**Comment by fluffy** [comment]
@martinthomson - RTPSender is created before SDP in cases where the the browser will always generate a mid. I think the key cases is when the browser gets an Offer that was not generated by another browser and has SDP with no mid. In this case it seems like it's best to represent the SDP received and that had no mid so my knee jerk reaction is use null in the RTPReceiver in that case. But what gets put in the Answer seems like a separate issue. The issue of putting lip sync info in LS groups might complicate this issue.

**Comment by alvestrand** [comment]
It seems legit to include a MID in the answer if there were none in the offer. So the mid would be an attribute that can be null initially, but gets filled in when we decide what to put in an offer or an answer. I think that would work for me.

(Note - when an RTPReceiver and an RTPSender map to the same media section, I assume that they MUST have the same mid value....)

**Comment by fluffy** [comment]
Need to check if the grouping framework allows that

**Comment by juberti** [comment]
I didn't see anything in 5888 that explicitly forbids this; the closest text is in https://tools.ietf.org/html/rfc5888#section-9.1. 

Generally, something that doesn't include a=mid won't understand a=mid either, so it seems harmless.

**Comment by alvestrand** [comment]
Also related to #293.

**Comment by stefhak** [comment]
Given how the spec is written, it seems most appropriate to decide the mid at addTrack time since addTrack returns a RTPSender which in turn has mid as a readonly attribute.

In the simple case that leaves with two basic cases: either we have a session (and here we can be either in stable state or during negotiation having applied an incoming offer) with an existing m-line that this track could be tied to, or we don't.
If we have, the mid is determined by that m-line. If we don't, we have to invent one.
This discussion seems to be related to the case where we have an existing m-line to tie the track/sender to, but the m-line has no mid. The most logical thing to do to me seems to be to invent a new mid (as Justin proposes).
I'm sure we'll find loopholes when we add rollback to the discussion since the rollback can(?) remove the m-line.

**Comment by martinthomson** [comment]
I don't think that this covers the case I described @stefhak. If this attribute is used as the basis for anything in the API, like LS groupings as @fluffy mentions, then we have to consider the possibility that it changes during negotiation.  Of course, as @alvestrand and @juberti note, we can always insert an `a=mid` line.  But what we cannot do is rely on the value being stable.  I think that this is probably OK in practice, but it also eliminates any potential value we might gain by picking an mid value prior to negotiation.  Applications have to rely on the `RTCRtpTransceiver` being the stable entity.

As an aside, why don't we move the `mid` to the `RTCRtpTransceiver`?

**Comment by stefhak** [comment]
@martinthomson I must have missed your case. Can you send a pointer to its description? (I only caught the part of receiving an offer without any MID)

**Comment by martinthomson** [comment]
https://github.com/w3c/webrtc-pc/issues/227#issuecomment-99526290 mentions it; though it's just the basic way that O/A works.

**Comment by martinthomson** [comment]
Oh, and agree regarding the reasoning behind a move, that was my reasoning too.

**Comment by alvestrand** [comment]
RFC 5888 clearly says that "mid" in answer MUST be the same as "mid" in offer, and specifies what one should do when this isn't true (unusually).
It doesn't seem to say anything about "mid" in subsequent offers. This may be intentional or just that the editors thought it was so obvious that it didn't need writing down (it might be obvious that mids could change on any new offer, or it might be obvious that mids should stay the same forever - I'm not sure which was intended, which is sad.)

**Comment by martinthomson** [comment]
I think that the safest thing to assume is that mid doesn't change.  That said, it might be possible to change mid for a recycled line (if we're still doing that, that is).

**Comment by stefhak** [comment]
@alvestrand 5888 sec 9.1 says subsequent offers SHOULD keep the same mid (i.e. not a MUST)
OTOH JSEP says the mid can't be changed (but JSEP is not an RFC yet).

**Comment by stefhak** [comment]
This topic was discussed during TPAC, and if memory serves (but I'm quite unsure, please correct if wrong) we said something like:
* we should remove mid from RTPSenders and Receivers (#)
* a mid value for a new Transceiver is generated at createOffer time, but the Transceiver mid attribute is not set until setLocal succeeds
** here was some additional agreement on how things work with rollback and m-line recycling
* I don't remember what we said for situations where an offer has no mid :(
* life would be easier for the JSEP authors if mids can be changed with new offers

**Comment by elagerway** [comment]
It seems this should be addressed in JSEP in RTCWEB WG

**Comment by alvestrand** [comment]
Do we have a filed issue for JSEP about it to cite?

**Comment by fluffy** [comment]
This is getting updated in JSEP https://github.com/rtcweb-wg/jsep/issues/213

**Comment by fluffy** [comment]
The JSEP draft is clear that if MIDs are generated in the offer. If the received offer has a MID, this is used and put in the answer. And if the the offer does not have a MID, the answer will not have a MID but the ICE candidate objects will have a an local generated one.
