### ISSUE TITLE
Update to constructor operations

### ISSUE THREAD

**Issue by Ms2ger** [w3c/webrtc-pc#2282]
See https://github.com/heycam/webidl/issues/778.

**Comment by dontcallmedom** [comment]
This depends on https://github.com/w3c/respec/issues/2494 (but latest respec seems to trigger a number of errors in the WebRTC spec, so the upgrade is likely not trivial)

**Comment by dontcallmedom** [comment]
see https://github.com/w3c/respec/issues/2495 and https://github.com/w3c/respec/issues/2496 for obstacles to upgrade (we would also want #2287 to be merged)
