### ISSUE TITLE
Merge the steps for updating candidate pair and ice transport state

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2283]
We currently do this in two separately queued tasks:

> When the ICE Agent indicates that the RTCIceTransportState for an RTCIceTransport has changed, the user agent MUST queue a task that runs the following steps:

> When the ICE Agent indicates that the selected candidate pair for an RTCIceTransport has changed, the user agent MUST queue a task that runs the following steps:

There is room for interpretation which task you queue first. In either case, since they are tasks queued separately and each task fires an event, it is observable which thing happened first.

I think the correct behavior would be to update both the ICE state and the candidate pair, and to fire both events (onstatechange, onselectedcandidatepairchanged)

**Comment by henbos** [comment]
;)

**Comment by henbos** [comment]
With the current spec I think it would be spec-compliant to listen to onstatechange and have pairs that contradict the state, or listen to onselectedcandidatepairchanged and have contradicting state, and that different implementations could be observably different and still be compliant.

**Comment by dontcallmedom** [comment]
seems similar (but different) to #2020 which was fixed by #2400 - not clear that it is editorial since it's obversable

**Comment by henbos** [comment]
This is still relevant, but ready for PR.

**Comment by henbos** [comment]
@jan-ivar suggests firing candidate pair changed first and connection state events second
