### ISSUE TITLE
Should peer identity specific steps be marked as "Feature at risk"

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2284]
Identity was marked feature at risk in PR 1114.
There are some mandatory steps in webrtc-pc that might need to be marked as 'feature at risk'

**Comment by dontcallmedom** [comment]
When we move these steps out, let's also plan on reintegrated isolated mediastream somewhere (maybe in getUserMedia)?

**Comment by alvestrand** [comment]
@aboba what's the PR?

**Comment by jan-ivar** [comment]
@aboba Do you have a PR here?

**Comment by aboba** [comment]
@youennf - were you going to provide a PR for this one?

**Comment by youennf** [comment]
I am not sure about which PR we are talking about.
Option 1:
- Remove these steps from webrtc-pc (as @dontcallmedom suggests) and add them to identity spec
Option2:
- Mark these steps as features at risk.

I think we have consensus for doing option 1. Am I correct?

**Comment by henbos** [comment]
TPAC decision: "Migrate the remaining identity steps to webrtc-identity"

Didn't we decide to add some sort of placeholder "no-op steps" in webrtc-pc, and in the identity spec we extend these steps to perform identity logic?

**Comment by henbos** [comment]
Changed from PR exists -> Ready for PR, correct me if that is wrong, but I don't see the a PR for this.

**Comment by henbos** [comment]
Isn’t this a duplicate of #2364 at this point when we know we want to break it out? One is assigned to @youennf and one is assigned go @jan-ivar. Who takes ownership?

**Comment by jan-ivar** [comment]
Closing as dup of https://github.com/w3c/webrtc-pc/issues/2364
