### ISSUE TITLE
Overloaded operations disallowed across partial interfaces in WebIDL

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2289]
[WebIDL disallows defining overloaded operations across partial interfaces](https://heycam.github.io/webidl/#idl-overloading):
> Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

(this has been disallowed [for a very long time](https://github.com/heycam/webidl/commit/bae069cc35773c1d2ed0efdc1829cd7fa924a5b4))

This means our approach in splitting the legacy versions of the operations in a partial interface is invalid from a WebIDL perspective.

(this emerged as part of looking at a ReSpec upgrade for #2282 - see also https://github.com/w3c/respec/issues/2495)

**Comment by alvestrand** [comment]
I thought we'd raised a bug with them before about this, but my github search-fu is not capable of finding it. I know we've discussed this before.

**Comment by dontcallmedom** [comment]
@jan-ivar reminded me that there is some language to deal with this in the spec:
> This section is broken out for readability. Consider partial interfaces here to be part of their main counterparts, as they overload existing methods.

that's probably ok-ish, but our next ReSpec upgrade is going to flag this as an error, which is a bit problematic.

I think we may want to keep the prose as a separate section, but move back the IDL definitions into the main IDL fragment - I'll start a PR to see where that leads us.
