### ISSUE TITLE
Persistent RTC Connection by using iceCandidatePoolSize

### ISSUE THREAD

**Issue by gargvk10** [w3c/webrtc-pc#2299]
Hi,
I am trying to develop a solution for making Persistent RTC Connection to save the few network trips for collecting the ice candidates. For doing that i am creating a rtc peer connection as soon as user open my webrtc page. i want to use the same rtc peer connection object for the next call so i thought of cloning this object and pass it to the call so that current call will only close the cloned object not original peerConnection object. I am not able to clone it properly and always get error while setting up onTrack on cloned object. 
The error for all methods is like 
**connectionState: [Exception: TypeError: Illegal invocation at RTCPeerConnection.invokeGetter (<anonymous>:2:14)]**
can you please help me how can i clone this object or suggest a good method to make RTC Connection persistent for multiple calls ?

**Comment by alvestrand** [comment]
No, there's no way to clone an RTCPeerConnection.
I think what you are looking for won't be doable with the webrtc-pc 1.0 API; I know that @pthatcherg has been talking with some people about extending IceTransport for those use cases.

**Comment by alvestrand** [comment]
Closing as "you can't get there from here in WebRTC 1.0". Sorry.
