### ISSUE TITLE
Add support for WebRTC Data Channel in Workers

### ISSUE THREAD

**Issue by feross** [w3c/webrtc-pc#230]
#### Proposal

Support WebRTC Data Channel in Workers (`WebWorker`, `ServiceWorker`, etc.)

WebRTC DataChannel is basically a drop-in replacement for `WebSocket`, except it's peer-to-peer. For all the same reasons that `WebSocket` was added to the `Worker` spec, we should add WebRTC DataChannel.

#### Use Cases

DataChannel in a `ServiceWorker` would support the use case of "peer assisted delivery" a la [PeerCDN](https://www.peercdn.com/faq.html), CDN/P2P CDN video streaming delivery, file transfer, etc.

DataChannel in a `WebWorker` would support offloading CPU intensive data transfer/processing to another thread.

#### What about security?

Using WebRTC data channels in a worker is no different from a security/privacy perspective than using  WebSocket. There's no user permission prompt to open a WebRTC data channel.

**Comment by silverbucket** [comment]
+1

**Comment by Adria2** [comment]
+11
I'm developing applications where the SharedWorker IS the application, sharing one websocket connection, indexedDB, crypto keys, etc, accessed by light-weight tabs/views which the user can freely open and close. So long as one tab remains open, the applications expensive state is preserved ... Almost.

If the "master" tab is closed, all the WebRTC data channels are blown away, and a new master tab has to be delegated by the SharedWorker.
It's excruciatingly painful.

**Comment by feross** [comment]
Another use case for using WebRTC in a SharedWorker is a DHT, a decentralized/distributed lookup service (similar to a hash table). Useful for routing to nodes in decentralized applications.

**Comment by dennismartensson** [comment]
This would be fantastic! It will really make the WebRTC Data Channel even more powerful.

**Comment by stefhak** [comment]
Hi! You should push for this feature on the WebRTC WG's mailing list, public-webrtc _at_ w3.org.
That is where the community discuss and decide on added functionality and features.

**Comment by gaperik** [comment]
Hi.
+1 to Stefans comment. Bringing it to the W3C WebRTC-list will make it more likely we'll see some work on it in a not-to-distant future. Of course, pushing for features in Chrome, FF and Edge developer communities never hurts (https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer), :-).

**Comment by feross** [comment]
I made a proposal on the mailing list: https://lists.w3.org/Archives/Public/public-webrtc/2015May/0157.html

**Comment by feross** [comment]
Here are the relevant issues in the various developer communities:

Chrome: https://code.google.com/p/webrtc/issues/detail?id=4700
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=922363
Microsoft Edge: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8118837-support-webrtc-datachannels-in-workers

**Comment by shumy** [comment]
+11 Access WebRTC API in Workers and support transfer of MediaStream objects through the Message API.

**Comment by stefhak** [comment]
Given the process on how to determine what is in/out of 1.0 (https://lists.w3.org/Archives/Public/public-webrtc/2015Jul/0060.html) the best thing to do if you'd like to see this feature is probably to create a pull request and try to get some discussion around it.

**Comment by shumy** [comment]
From the answers, it seems like you have to change the WebRTC API ??
Don't change anything, just extend the availability of WebRTC API on Workers.

**Comment by kulicuu** [comment]
+1

**Comment by pashoo2** [comment]
+1

**Comment by mastayoda** [comment]
+1

**Comment by stefhak** [comment]
This was discussed at the WebRTC WG meeting during TPAC, and it was decided to add this functionality pending a security review. That security review has been done, and there are active PRs ( #317 and #445 ). However, more work is needed on those PRs.

**Comment by silverbucket** [comment]
Great news! +1

**Comment by feross** [comment]
Excellent news. Very much looking forward to this!

**Comment by stefhak** [comment]
The PRs ( #317 and #445 ) have issues/are incomplete. Anyone that is interested/willing to contribute to improve them?

**Comment by alvestrand** [comment]
Based on the silence, marking this LATER (beyond 1.0).

**Comment by eligrey** [comment]
Absolutely +1!

**Comment by alvestrand** [comment]
Closing with intent to reopen "later".

**Comment by interfect** [comment]
Is it "later" yet?

There are some really cool tricks one would be able to do with, say, [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs) and a ServiceWorker, to serve assets from the IPFS network and have them appear to the page like normal HTTP-based assets. Currently you have to figure out how to connect a NodeJS-style stream to, say, an `<img>` tag. Browsers already know how to connect a stream to a tag, and it would be really useful to be able to use that functionality for streams that come in from peers.

**Comment by alvestrand** [comment]
No, "later" is after webrtc-pc has gone to CR.
If you want to pursue the change as a separate document (with intent to merge), feel free to write up a draft. It turned out in discussion to be non-trivial in its implications (both spec and implementation).

**Comment by davux** [comment]
@alvestrand, that's very summed up. Would you share a pointer to that discussion and/or maybe a more descriptive summary?
Thanks!

**Comment by ya7ya** [comment]
Hello, Has there been any progress on this ? I looked at the mailing list but I couldn't find the aforementioned discussion.

**Comment by lgrahl** [comment]
I believe this can (and should) be reopened now.

**Comment by benjamingr** [comment]
As a large consumer of `DataChannel`s We would be willing to provide feedback and work with relevant parties in order to help make this happen.

I see a big net positive for users here.

**Comment by v0l** [comment]
+1 this would be a very nice way to implement P2P CDN, many websites could make great use of this!

**Comment by lgrahl** [comment]
To everyone interested: I assume you will reach a broader audience if you write to the mailing list `public-webrtc@w3.org` (not all of them are following GH issues) that we want to reopen the discussion on worker support for data channels. I will support this intention.

**Comment by isaackwan** [comment]
Stupid question - why is creating `RTCPeerConnection` from workers not considered? What's the threat model here?

Workers can get SDP from other methods, such as fetch() from servers, no?

This allows, for example, ServiceWorkers that enables P2P delivery.

**Comment by alvestrand** [comment]
Removed the LATER label since this is under active consideration.
Note that the PRs #317 and #445 remain closed, even though I removed the LATER label; the submitters should consider whether it makes sense to rebase them and anwer the issues raised in the PRs or start over.

**Comment by nkev** [comment]
Creating a browser "refresh resistant" WebRTC data channel in a shared worker could potentially change the way web apps are built forever! It's a shame not much has happened here in over 3 years...

**Comment by jimmywarting** [comment]
It have been quiet for a while now, haven't heard anything new. Some related PR/issues have been closed. So I got some few question.

- Won't service worker get webrtc support?
- What is blocking? is there any other related issues/PR i can follow?
> No, "later" is after webrtc-pc has gone to CR.
- Has webrtc-pc gone to CR yet?

**Comment by benjamingr** [comment]
> What is blocking? is there any other related issues/PR i can follow?

Someone actually doing the work and putting in the time and work to spec and then write support for workers.

**Comment by aboba** [comment]
@jimmywarting @benjamingr The "work" would probably involve implementing the [RTCDtlsTransport](http://draft.ortc.org/#rtcdtlstransport*) and [RTCDataChannel](http://draft.ortc.org/#rtcdatachannel*) interfaces from ORTC, in addition to [WebRTC-ICE](https://w3c.github.io/webrtc-ice/) which had an Origin Trial in Chrome last Spring along with [WebRTC-QUIC](https://w3c.github.io/webrtc-quic/).

The big question is whether there is enough motivation for browser vendors to support RTDataChannel in workers, as opposed to RTCQuicTransport in workers.  [WebTransport API](https://wicg.github.io/web-transport/) seems to be garnering interest, the existing WebRTC data channel not so much.

**Comment by lgrahl** [comment]
> [WebTransport API](https://wicg.github.io/web-transport/) seems to be garnering interest, the existing WebRTC data channel not so much.

Maybe they should focus more on improving what people are actually "stuck with" using right now? Just a thought...

**Comment by subins2000** [comment]
I was excited today to move the WebTorrent part of my app to a worker for increased performance, but then I saw this issue, a big letdown :/

It's a shame that even after 5 years, this hasn't been implemented :(

**Comment by benjamingr** [comment]
> It's a shame that even after 5 years, this hasn't been implemented :(

You have several options for recourse:

 - Put in the work and implement this feature yourself.
 - You can pay for it to be implemented for you by another company.
 - You can find compelling use cases to get other people to do either of the above two things.

**Comment by interfect** [comment]
An implementation of a fix to this issue would be making *just* RTCDataChannel available in *just* (ordinary, Web, non-Service) Workers, right? Along the lines of #317 or #445, you would be able to send an already open RTCDataChannel to a Web Worker, but a Web Worker would not be able to open any new connections (because of not having RTCPeerConnection) and a Service Worker wouldn't be able to use either. (As pointed out [here](https://github.com/w3c/webrtc-pc/pull/317#issuecomment-170763447) by @martinthomson, a Service Worker is supposed to only be spun up for a few seconds at a time to handle a request, and giving it a peer to peer connection causes trouble with that model that people did not want to solve at the time.)

I'm not sure a fix to this issue would then really provide what @jimmywarting, @nkev, and others are asking for, which is a way to host a useful peer-to-peer node in a browser in the background (or at least independent of any single tab), in a context where it can idiomatically service requests.

I'm going to open an issue to track providing the whole WebRTC API to all types of workers (including Service Workers) in a way that is useful for p2p content distribution but which doesn't buy you infinite service worker runtime for every site the user ever visits. Actually fixing that bigger issue is where a lot of the hardness is, it seems, and probably shouldn't block a fix for this issue for whoever actually needs exactly the functionality of shipping an RTCDataChannel specifically to a Web Worker specifically.

**Comment by nkev** [comment]
@interfect Thank you for the useful response and not dismissing this with "build it yourself or pay someone else to build it".

**Comment by interfect** [comment]
@nkev I'm not actually one of the actual spec group project members either; I want this feature for my use case too. But I can see how it can get on their nerves to have people showing up periodically asking why their pet issue isn't ready yet, so I decided to try to grab a metaphorical shovel to the extent that I can.

Where we might still get stuck is browser implementations. I'm pretty sure I can fiddle with a spec document, but I'm not really a qualified browser dev and even if I were I have no leverage to get an implementation merged. I'm hoping some actual browser devs will come by and implement it for me (which might go better if this is attached to the next version of WebRTC like @alvestrand suggested, which is going to need implementing anyway).

**Comment by guest271314** [comment]
Can `self` or `globalThis` be substituted for all references to `window` and `import()` or `importScripts()` be substituted for `document` within https://github.com/rustwasm/wasm-bindgen/tree/master/examples/webrtc_datachannel to be able to use the Rust wasm-bindgen version of `RTCDataChannel` https://rustwasm.github.io/wasm-bindgen/examples/webrtc_datachannel.html in `Worker`?

All the logs at https://rustwasm.github.io/wasm-bindgen/exbuild/webrtc_datachannel/ are on line 333 in index_bg.js:333.

**Comment by guest271314** [comment]
@lgrahl FWIW `QuicTransport` https://github.com/GoogleChrome/samples/blob/gh-pages/quictransport/quic_transport_server.py is defined `Worker` at Chromium 87.

**Comment by lgrahl** [comment]
Linking https://github.com/w3c/webrtc-extensions/issues/64
It's time to recite your use cases. :slightly_smiling_face:

**Comment by amark** [comment]
Hi, I'm a p2p protocol developer with millions of monthly active users.

And unlike the others, I **beg and plead you to NOT** implement this *until*

https://github.com/w3c/webappsec-csp/issues/92

Is fixed.

Any WebWorker feature that allows for external communication is a huge data exfiltration and security risk.

Thank you.

**Comment by lgrahl** [comment]
Transferring to a worker has since been specced in https://github.com/w3c/webrtc-extensions
Only Safari [can do it right now](https://wpt.fyi/results/webrtc-extensions/transfer-datachannel.html?label=master&label=experimental&aligned) but [not to service workers](https://wpt.fyi/results/webrtc-extensions/transfer-datachannel-service-worker.https.html?label=master&label=experimental&aligned). Fear not though, https://github.com/w3c/webappsec-csp/pull/457 is close to get merged and right now you need an active `RTCPeerConnection` living in the main thread.

**Comment by SahilAggarwal2004** [comment]
Any updates on this?

**Comment by aboba** [comment]
The WebRTC-Extensions specification [includes support for WebRTC Data Channel in Workers.](https://w3c.github.io/webrtc-extensions/#rtcdatachannel-transferable)

However, at least one shipping implementation is required to move the spec into WebRTC-PC.

**Comment by Diego-Perez-Botero** [comment]
@aboba - doesn't the following mean that Safari has a shipping implementation of WebRTC Data Channel transfer to workers (including service workers)?

https://wpt.fyi/results/webrtc-extensions/transfer-datachannel.html?label=master&label=stable&product=safari&aligned

https://wpt.fyi/results/webrtc-extensions/transfer-datachannel-service-worker.https.html?label=master&label=stable&product=safari&aligned

**Comment by aboba** [comment]
Yes.  For some reason, the tests have been failing on all browsers recently, so I missed that:
https://wpt.fyi/results/webrtc-extensions?label=experimental&label=master&aligned

**Comment by epaterlini** [comment]
Any news on this? A growing-in-importance topic and no implementations yet... :-(

**Comment by aboba** [comment]
Have you tried Safari Tech _Preview192?  WPT.fyi indicates that tests are passing: 

https://wpt.fyi/results/webrtc-extensions/transfer-datachannel.html?label=experimental&label=master&aligned
https://wpt.fyi/results/webrtc-extensions/transfer-datachannel-service-worker.https.html?label=experimental&label=master&aligned

**Comment by molvqingtai** [comment]
Are there any updates? This requirement has existed for ten years

https://issues.chromium.org/issues/41061583

**Comment by fippo** [comment]
Have you actually tried? Even in Chromium this shipped in 2024.

**Comment by guidou** [comment]
This is already part of the spec. https://w3c.github.io/webrtc-pc/#webidl-rtcdatachannel

**Comment by molvqingtai** [comment]
Maybe I'm looking at the wrong issue, but no browser currently allows creating an `RTCPeerConnection` directly inside a Worker (not transfer/cloning related).

**Comment by fippo** [comment]
RTCPeerConnection in workers is a different beast, see https://github.com/w3c/webrtc-nv-use-cases/issues/60
Unsurprisingly since nobody put in the actual effort no progress has been made.

**Comment by NotASithLord** [comment]
@molvqingtai what use case do you have where transferring a RTCPeerConnection to a Worker doesn't work?

**Comment by molvqingtai** [comment]
> [@molvqingtai](https://github.com/molvqingtai) what use case do you have where transferring a RTCPeerConnection to a Worker doesn't work?

Transferring isn't the problem I'm trying to solve. I'm interested in a SharedWorker owning a single `RTCPeerConnection` so multiple pages can share it and page reloads don't require reconnecting.

**Comment by jcubic** [comment]
I wanted to have similar thing, having Service Worker text based chat library that use WebRTC and expose simple API with EventSource and fetch. With help from [Wayne library](https://github.com/jcubic/wayne).

Right now it's not possible.

**Comment by jimmywarting** [comment]
> > [@molvqingtai](https://github.com/molvqingtai) what use case do you have where transferring a RTCPeerConnection to a Worker doesn't work?
> 
> Transferring isn't the problem I'm trying to solve. I'm interested in a SharedWorker owning a single `RTCPeerConnection` so multiple pages can share it and page reloads don't require reconnecting.

Dito, I also want to remain connected to a single connection (shared across all tabs) and also durning page reload (without having to build a SPA)
Being able to establish a p2p connection on a SharedWorker, without transferring a `DataChannel`, would be very useful.
When a page reload, then the `RTCPeerConnection` closes, and so dose the transfered `DataChannel` along with it.
