### ISSUE TITLE
Prefer variable ptime (audio frame lengths)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2300]
We negotiate a maxptime (in SDP but there is no control knob for), and RTCRtpEncodingParameters.ptime allows preferring a specific ptime.

Questions:
- Today: Is an implementation allowed to vary frame lengths dynamically/autonomously during a call (e.g. depending on network conditions)?
- Do we think that enabling variation would cause backwards compatibility issues?

Possible proposal:
- Do we want an API to control whether or not we prefer varying frame lengths?

**Comment by henbos** [comment]
@jan-ivar @aboba @alvestrand

**Comment by henbos** [comment]
I might want to talk about this at TPAC but until further input I'll remove the label

**Comment by rshpount** [comment]
Using variable frame duration in RTP packets will cause serious interop issues. The problem is jitter buffer implementations that assume that all frames are the same length and estimate packet time based on the RTP sequence number and ptime. If frame size changes, then such estimates will no longer work. Furthermore, RTP packet duration cannot be calculated before decoding (or without understanding packet format). There is a decent chance that this will even break NetEQ jitter buffer, since, I think it is based on number of packets queued not their duration.

Your best option is to renegotiate with the different ptime without codec changes or ICE restart.

**Comment by henbos** [comment]
Thanks Roman. Are you speaking with regards specific browser implementation(s), or SFUs, etc? Chromium is interested in varying them dynamically for the sake of better quality especially during low bitrate conditions, but need to be careful how to proceed depending on the interop landscape and interest/interoperability from other browsers/endpoints.

**Comment by rshpount** [comment]
I am talking about most of the browser implementations including Chromium (they are using NetEq jitter buffer) as well as any WebRTC enabled media servers and transcoding gateways (such as Asterisk or FreeSwitch), or phones connected via some sort of ICE/DTLS-SRTP to SRTP gateway (such as things derived from rtpengine). All of those will have problems. SFU generally would not care.

**Comment by rshpount** [comment]
On the other hand, generating renegotiation needed event, exchanging SDP, changing SSRC, and switching from 20 ms to 30 ms frames should work for low bitrate without many issues.  Such exchange will reset jitter buffer and things should start to work. It is dynamic frame sizing without any notice which would cause problems, not the frame size change on its own.

**Comment by alvestrand** [comment]
The Chrome implementors who proposed varying ptime without negotiation claim to have tried it out without problems. They might not have been looking in the right place, or it might turn out that the code handles it even though it's not "supposed to". Tests would be good.

**Comment by henbos** [comment]
Closing this issue.
This was resolved in webrtc-extensions spec here: https://github.com/henbos/webrtc-extensions/issues/3
See webrtc-pc PR discussions [here](https://github.com/w3c/webrtc-pc/pull/2309), for the final PR having moved to webrtc-extensions and merged [here](https://github.com/w3c/webrtc-pc/pull/2309).
