### ISSUE TITLE
do we need RTCCbrStatus?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#2301]
Do we need RTCCbrStatus for [opus cbr](https://tools.ietf.org/html/rfc7587#section-3.1.2)?
The description would be somewhat similar  to the [dtx one](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-dtx) (which is marked as at-risk?!)

**Comment by fippo** [comment]
Since @aboba asked: even without an API it is still possible to munge the SDP to enable this.
This is second form munging, i.e. on the signaling channel before setRemoteDescription.
Like for dtx we don't have an actual API to tell the sender to create an offer and negotiate it.

**Comment by aboba** [comment]
Moved to https://github.com/w3c/webrtc-nv-use-cases/issues/57
