### ISSUE TITLE
[[SendCodecs]] is updated based on answers, but [[SendEncodings]] is updated based on remote description

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2313]
Because the details of a send codec are determined by the remote description (for example, asymmetric payload type), we need to be paying attention to the remote description when setting [[SendCodecs]].

Also, right now the spec updates [[SendCodecs]] and [[SendEncodings]] at a different time; since the two are linked by payload type, and payload type can change due to negotiation, we have a referential integrity problem. For example, if we receive a remote offer that changes the payload type of a codec, that will be reflected immediately in [[SendEncodings]], but [[SendCodecs]] will still have the old payload type for that codec.

If we intend to continue updating [[SendEncodings]] on remote offers (pre-answer), we probably want to also update [[SendCodecs]]. Unfortunately, the prose around [[SendCodecs]] says these represent what has been negotiated, which would no longer be true. Also, if we do this, we need to specify how rollback/multiple offers works.

If we intend to update [[SendEncodings]] only when offer/answer completes, this ends up being cleaner. However, it would mean that JS would not be able to make changes to [[SendEncodings]] that come from a remote offer until after negotiation is complete, which might be undesirable.

Another approach might be to abandon the use of payload type as the thing that links [[SendEncodings]] to [[SendCodecs]], and instead use rid. rid is more stable than payload type. We could have each entry in [[SendCodecs]] contain a list of rids that it has been negotiated to send, and define the simulcast envelope that way. The potential downside to this is if we allow the rids to be renegotiated (say, we start with 'low', 'med', and 'high', and then a renegotiation happens that changes to rids 'tall', 'grande', and 'venti'). In that case, we have a referential integrity problem again.

Thoughts?

**Comment by alvestrand** [comment]
We can have multiple tracks with the same codec and the same payload type, but different rids; this will be the normal case for simulcast. Also, if the codec used for a track can change, the codec will change, but the rid will not. So rid is not a suitable identifier for codecs.

**Comment by docfaraday** [comment]
Since [[SendCodecs]] lives in RTCRtpSender, they only apply to a single track. Also, if we were to use rid to link [[SendEncodings]] to [[SendCodecs]], the linkage would be in the opposite direction, and we would not be using rid as an identifier for anything besides the stuff in [[SendEncodings]].

**Comment by docfaraday** [comment]
If we need a stable identifier for the stuff in [[SendCodecs]], we'll have to just pick a random id I think. I am not sure we actually _need_ an identifier, though.

**Comment by jan-ivar** [comment]
Dunno if this is the right issue for it, but wanted to write down some notes from offline discussion regarding when to respond to remote changes wrt things like codecs: in SRD(offer) or SLD(answer)?

In short, even though an underlying SDP assumption appears to be that one needs to be prepared to receive pre-answer, in practice DTLS key exchange needs answer, and ICE can’t get candidates pre-SLD.

Even in renegotiation situations where these aren't obstacles, according to @docfaraday, Firefox will still not recognize packets from a new codec until the answer, which simplifies renegotiation and rollback. I'm curious what other browsers do?

@henbos also [suggested](https://github.com/w3c/webrtc-pc/pull/2298#pullrequestreview-300656528) codecs may be changed by JS before the answer, even more reason to hold off until the answer maybe.

**Comment by alvestrand** [comment]
Furthermore .... as I understand codec definitions in SDP, payload types can never *change*.

PTs defined in an offer define a set of codecs (A, B, C).
PTs in an answer (example: B, C, D) mean:
- I'm not willing to receive A
- I'm willing to receive B, perhaps with a more restricted profile (down-negotiating), and may choose to send it according to the profile you originally sent me
- I'm willing to receive C (same as above)
- I'm willing to receive D, but I'm not going to send it, since you haven't said you can receive it

D may be a superset of A's profile ("I want to negotiate up"), or completely unrelated.
So the set of codec descriptions can expand, and some of the descriptions can be rendered unusable ("I am not willing to receive") - but they cannot be redefined, and they cannot be reused.

**Comment by alvestrand** [comment]
Description of building the initial offer's media types: https://tools.ietf.org/html/rfc3264#section-5.1
Description of building the answer's media types: https://tools.ietf.org/html/rfc3264#section-6.1
Description of changing the media type set: https://tools.ietf.org/html/rfc3264#section-8.3.2

**Comment by alvestrand** [comment]
Proposal to WEBRTC Interim Nov 26: Close issue with no change to spec.
The referential issue is gone; other issues can be discussed separately.

**Comment by alvestrand** [comment]
Closed per WG interim consensu.

**Comment by docfaraday** [comment]
> Furthermore .... as I understand codec definitions in SDP, payload types can never _change_.
> 
> PTs defined in an offer define a set of codecs (A, B, C).
> PTs in an answer (example: B, C, D) mean:
> 
>     * I'm not willing to receive A
> 
>     * I'm willing to receive B, perhaps with a more restricted profile (down-negotiating), and may choose to send it according to the profile you originally sent me
> 
>     * I'm willing to receive C (same as above)
> 
>     * I'm willing to receive D, but I'm not going to send it, since you haven't said you can receive it
> 
> 
> D may be a superset of A's profile ("I want to negotiate up"), or completely unrelated.
> So the set of codec descriptions can expand, and some of the descriptions can be rendered unusable ("I am not willing to receive") - but they cannot be redefined, and they cannot be reused.

This is not accurate, unfortunately. The answerer is not permitted to add new codecs to the answer that were not offered. That means D is the same as A, only with a different payload type...

**Comment by rshpount** [comment]
> This is not accurate, unfortunately. The answerer is not permitted to add new codecs to the answer that were not offered. That means D is the same as A, only with a different payload type...

I am not sure this is accurate. According to https://tools.ietf.org/html/rfc3264#section-6.1:

The stream MAY indicate additional media formats, not listed in the corresponding stream in the offer, that the answerer is willing to receive. 

Unless somewhere else it was blocked, adding formats in the answer is allowed.
