### ISSUE TITLE
Can IceTransportState go checking -> completed?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2316]
https://w3c.github.io/webrtc-pc/#rtcicetransportstate shows a non-normative state transition diagram where there's an arrow from "checking" to "completed".
While revising a relevant test (RTCPeerConnection-iceConnectionState.https), I was asked whether this transition could occur in this test.

I was unable to answer. Can it happen? If so, when?

**Comment by henbos** [comment]
Examples:
1. If I have a single candidate and I am able to connect to it. Will I go "new -> checking -> connected -> completed" or "new -> checking -> completed"? I don't know the answer to this question.
2. If my newly created transport is able to connect faster than the UA has time to even create the JS layer object for it, is it allowed to skip the "checking" state? Here I suspect the answer is "no", but this is also not clear to me.

**Comment by henbos** [comment]
3. Is it mandated that the initial state is "new"? This is a version of question 2 above. (By the time I receive a snapshot of the transports on the JS thread perhaps they're already connected or checking)

**Comment by alvestrand** [comment]
3. is answered in the WebRTC spec: "An RTCIceTransport object has the following internal slots:
* [[IceTransportState]] initialized to new"

**Comment by alvestrand** [comment]
Accepted solution in VI:

RTCIceTransport.state reflects the [[IceTransportState]] slot
A single iceTransport can:
* Be set to “new” on creation
* Be updated by the ICE Agent
* Go to “closed” on close()

The “completed” state says:

* The RTCIceTransport has finished gathering, received an indication that there are no more remote candidates, finished checking all candidate pairs and found a connection. - 5 conditions.
* Conditions 1, 2 and 3 can happen while in “checking”.
* Condition 4 (“finished checking”) and condition 5 (“found a connection”) can be the same event - but only if the last checked candidate is the only successful one.

Proposed answer: YES. This should be mentioned in a “Note” paragraph.
