### ISSUE TITLE
Add more specificity on the format of RTCStats.ids

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2319]
Even with unpredictable IDs ([PR](https://github.com/w3c/webrtc-pc/pull/2304)), the spec has nothing to say about which symbols are or are not allowed or what the length of the string may be. Problems:
- This could potentially make it difficult to store stats objects in a database. Weird symbols or long strings.
- If you want to make a dashboard for stats it would be nice to know how long the ids can be for displayability.
- If different user agent's have characteristically different ids this could become a silly API for determining user agent/some amount of fingerprinting.

Proposal:
- Only alphanumerical symbols. (Any reason to include dashes?)
- Always 32 characters long.

One could go even further, but I don't think it's worth over-specifying this since we still want "guidelines" and not a specific algorithm for how to generate the ids, I assume.

**Comment by jan-ivar** [comment]
> Always 32 characters long.

@henbos Exactly 32? Is this necessary? This would make existing implementations non-compliant.

**Comment by henbos** [comment]
Are FF ids unpredictable already? I thought implementations had to update anyway (Chrome IDs are predictable)

**Comment by henbos** [comment]
32 was arbitrary, we can make it something else if that helps

**Comment by alvestrand** [comment]
I don't think it makes sense to make current implementations non-conformant.
Implementation advice is fine - requirements, especially when they make things non-conformant, need to have better reasons than "seems pretty".

**Comment by jan-ivar** [comment]
Agree with @alvestrand. We don't do this for other specs like deviceId.
