### ISSUE TITLE
Removing degradationPreference

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2325]
As noted at TPAC 2019, `degradationPreference` is a "feature at risk" with few prospects for implementation.  Also, the functionality appears to overlap with content-hints (which has been implemented). Rather than moving `degradationPreference` to an extension specification, can we delete it?

Related PR: https://github.com/w3c/mst-content-hint/pull/31

**Comment by Orphis** [comment]
I don't think that we really want to remove it as it does have very valid use case.
Also, I was going to add the feature soon in Chrome, so that would be annoying! :)

**Comment by aboba** [comment]
@orphis We are currently revising content-hints to incorporate some of the behavior in `degradationPreference`:
https://github.com/w3c/mst-content-hint/pull/31

Can you review that PR?

**Comment by dontcallmedom** [comment]
closed by #2399
