### ISSUE TITLE
iceconnectionstatechange event after PeerConnection.close() is called

### ISSUE THREAD

**Issue by jianjunz** [w3c/webrtc-pc#2335]
When the `close` method of `RTCPeerConnection` is invoked, user agent runs the following steps[1]:

> ...
> 3. Set `connection.[[IsClosed]]` to true. 
> ...
> 11. Set connection's ICE connection state to "closed".
> ...

If I understand correctly, "setting connection's ICE connection state to closed"(step 11) runs the  "update the ICE connection state" process[2].

> 1. If `connection.[[IsClosed]]` is true, abort these steps. (**It's always true**)
> 2. Let `newState` be the value of deriving a new state value as described by the `RTCIceConnectionState` enum.
> 3. If connection's ICE connection state is equal to `newState`, abort these steps.
> 4. Set connection's ice connection state to `newState`.
> 5. Fire an event named `iceconnectionstatechange` at `connection`.

As `connection.[[IsClosed]]` is always true in this case, step 2 to step 5 should not be executed. Does it mean user agent should not fire `iceconnectionstatechange` after `PeerConnection.close()` is called?

My observation is Safari doesn't fire `iceconnectionstatechange` after `PeerConnection.close()`, however, Chrome and Firefox do.

[1] https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-close
[2] https://w3c.github.io/webrtc-pc/#update-the-ice-connection-state

**Comment by fippo** [comment]
Safari does the right thing, chrome is wrong.
@henbos [reminder](https://bugs.chromium.org/p/chromium/issues/detail?id=699036)
@jan-ivar: surprised FF does that?

**Comment by alvestrand** [comment]
We need to have the ICE connection state end up in "closed". It wouldn't if step 11 ran the "update the ICE connection state" process, since that would abort.
The close method needs to be explicit that it bypasses the "update the ICE connection state" process, and we need to make a decision on whether or not it fires an iceconnectionstatechange event. (Do we need to make iceConnectionState Yet Another Internal Slot With Procedures??)

**Comment by jianjunz** [comment]
> We need to have the ICE connection state end up in "closed". It wouldn't if step 11 ran the "update the ICE connection state" process, since that would abort.

Yes, if user agents strictly follow the spec, the ICE connection state would not transition to "closed" in this case.

@fippo, thanks for the Chromium's issue link. It looks like the event issue was discussed in #1020 as well.

**Comment by alvestrand** [comment]
Sounds like we have previous consensus not to fire events. So the language in step 11 needs to be clarifiied.

**Comment by alvestrand** [comment]
I made a fix; should not change anything spec-wise, just being explicit. Test needed.

**Comment by jianjunz** [comment]
Thanks for making it clear. I could submit a test case to WPT late this week.

**Comment by alvestrand** [comment]
A test case would be most welcome. It could be added to RTCPeerConnection-IceConnectionState as a new case in that file.

**Comment by alvestrand** [comment]
Taking off the "needs test" label, as a test has been committed.
(And a fix to Chrome's behavior!)
