### ISSUE TITLE
Peer Connection and back/forward cache

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2346]
Current browsers do not add pages that have a live (or connected) peer connection to the b/f cache. It would be interesting to enable this.
One possibility is for these connections to simulate connection failure so that, should the page be  shown from b/f cache, the application logic would try to restart a connection.

**Comment by lgrahl** [comment]
I have no idea what a *b/f* cache is. :woman_shrugging:

**Comment by youennf** [comment]
A 'b/f cache', or 'page cache' is used when user is on Page1, navigates to Page2 and then clicks the back button to go back to Page1.
Some browsers will reuse the exact same page to quickly render Page1 in the same state it was.
Page1 will typically receive a pageshow event when being rendered from page cache.
This can also be used when user clicks the Forward button.

**Comment by alvestrand** [comment]
So you're saying that a page might stay alive in some sense when you navigate away from it?

**Comment by dontcallmedom** [comment]
@youennf is there any example of another spec that deals with these considerations? In particular, is there any existing definitions/spec infrastructure available to help define how a UA should behave?

is this a space where interop is needed (or a space where UAs can differ without particular cost)?

is this a 1.0 thing?

**Comment by youennf** [comment]
> So you're saying that a page might stay alive in some sense when you navigate away from it?

Right, Firefox and Safari are supporting that so that if you navigate back, the page will be in the same state and will be very fast to render.
Previously, whenever a pc was instantiated, the page would not go into the cache.

I don't mind whether this goes in 1.0 or not.
I think we actually want to agree and document the behaviour, then specify it when the b/f cache is standardised.

**Comment by aboba** [comment]
Moved to https://github.com/w3c/webrtc-nv-use-cases/issues/56
