### ISSUE TITLE
Remove dtx, ptime and codecPayloadType from RTCRtpEncodingParameters

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2350]
This is currently at risk. The TPAC decision was to remove these (not move to an extension spec).

**Comment by henbos** [comment]
maxFramerate is also at risk. codecPayloadType was discussed at TPAC, but is not actually marked at risk

**Comment by aboba** [comment]
We did not agree to remove `maxFramerate` at TPAC 2019, since there is an `Intent to Implement` statement filed on it (from January 2018):
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/SV8evGSU_dw
