### ISSUE TITLE
Add hardwareAccelerated field to RTCRtpCodecCapability

### ISSUE THREAD

**Issue by drkron** [w3c/webrtc-pc#2355]
It is sometimes beneficial to be able to tell beforehand if a particular codec has support for hardware acceleration. Currently, the only way to determine if there is hardware acceleration is to start a stream that is using the particular codec and look at the implementation name in getStats().

By knowing beforehand if there is hardware support, a client could use this information to signal back to the server that it should avoid/prefer a particular codec. This is of special importance for high bitrate streams where it's likely that a client will not be able to decode the stream in full fps if there is no support for hardware acceleration.

**Comment by aboba** [comment]
This is likely to be flagged in a privacy review.  See: https://github.com/w3c/webrtc-svc/issues/22

**Comment by alvestrand** [comment]
We do have a feature freeze for WebRTC 1.0 - the new field wouldn't be implemented when added, and is therefore automatically a Feature At Risk.
Can we add it to the "misc extensions" spec instead?

**Comment by drkron** [comment]
I'm aware of the feature freeze, but was advised to float this here initially.
Where do I find the "misc extensions" spec?

**Comment by alvestrand** [comment]
So far, on https://github.com/henbos/webrtc-extensions

**Comment by henbos** [comment]
Moved this to https://github.com/henbos/webrtc-extensions/issues/21. Closing.
