### ISSUE TITLE
Move maxFramerate to extension spec

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2357]
maxFramerate is at risk, however at TPAC 2019 we did not agree to remove it since there is an Intent to Implement statement filed on it (from January 2018):
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/SV8evGSU_dw

We need to decide: remove or keep. Unless someone implements it, it is still at risk. Letting this issue reflect that.

**Comment by sebakerckhof** [comment]
Btw, why is it `maxFramerate` and not `maxFrameRate` (capital R), since in the capture streams spec, it's always `frameRate` (https://www.w3.org/TR/mediacapture-streams/)

**Comment by henbos** [comment]
Good point. If chromium is the only implementer (@Orphis) I guess we can align the spec and implementation to say maxFrameRate, what do you say?

**Comment by Orphis** [comment]
It is probably more important to be consistent with other entries in the dictionary. We already have `maxBitrate`, so we should keep `maxFramerate` that way.

**Comment by henbos** [comment]
OK fair enough
