### ISSUE TITLE
Upgrade to ReSpec 24.32.1 produced 281 warnings

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2358]
After the ReSpec 24.32.1 commit at https://github.com/w3c/webrtc-pc/commit/570e110464cf7900f4ea1d084b1a3e8b5ff1f7dc (where did the PR go?), there are 281 ReSpec warnings, mostly of the type "link to DOMString doesn't have a target".

Can we do something to make those warnings stop? And to not get those every time we upgrade?

**Comment by dontcallmedom** [comment]
@alvestrand I'm a bit confused - I'm not seeting warnings in https://w3c.github.io/webrtc-pc/webrtc.html 

(the upgrade PR was https://github.com/w3c/webrtc-pc/pull/2292 which ultimately upgraded us to 24.33.1)

**Comment by alvestrand** [comment]
It seems to be present on http://w3c.github.io/webrtc-pc/ but not on https://w3c.github.io/webrtc-pc/webrtc.html

I see an error in the log:

respec-w3c-common.js:38 TypeError: Cannot read property 'digest' of undefined
    at f (respec-w3c-common.js:14)
    at e.run (respec-w3c-common.js:14)
    at Object.e.run (respec-w3c-common.js:38)
    at respec-w3c-common.js:14
    at new Promise (<anonymous>)
    at respec-w3c-common.js:14
    at Object.e.runAll (respec-w3c-common.js:14)
    at /webrtc-pc/async http:/w3c.github.io/webrtc-pc/respec-w3c-common.js:14

Changing the access mode from http: to https: seems to be necessary and sufficient in order to avoid the issue.

**Comment by dontcallmedom** [comment]
I can't reproduce it on `http:` either, but in any case, I've made it so the spec is only served on https now, so that should solve any remaining issue.
