### ISSUE TITLE
Transports on offer need to be rolled back

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2363]
Follow-up issue to https://github.com/w3c/webrtc-pc/issues/2338.

When we roll back, we should say to null the internal slots for the transports if they were rolled back.

**Comment by henbos** [comment]
Interim [slide](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit#slide=id.g6b7f95ec98_0_6): revert the transport internal slot on rollback

**Comment by alvestrand** [comment]
Nit: We should say that the previous value of the transport is restored. This will most often be null, but in the case of renegotiation that changes transports (switching from max-compat to max-bundle or vice versa - although I'm not sure that's presently possible), we could end up rolling back to a previous non-null transport.

That's what's on the slide now, but I want to make sure it's recorded in the bug too.

**Comment by henbos** [comment]
Agreed. There is also the case of setting multiple offers in a row. I think we should treat all "reverts" the same: Have an internal slot that we set when we set set an offer unless it's already set, and on rollback we revert to that internal slot. When we reach stable (either through rollback or answer), we null all the revert-slots.
