### ISSUE TITLE
Move identity steps to the identity spec

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2364]
See also marking it "at risk" (https://github.com/w3c/webrtc-pc/issues/2284).

**Comment by henbos** [comment]
Assigning it to Youenn because he's already assigned to the "at risk" one

**Comment by henbos** [comment]
@aboba Is this ready for PR or do we need to discuss this again?

**Comment by henbos** [comment]
Nag ping ;)

**Comment by youennf** [comment]
I'll task a shot at it.

**Comment by henbos** [comment]
Thanks!

**Comment by youennf** [comment]
Uploaded https://github.com/w3c/webrtc-pc/pull/2390, which removes identity steps.

AIUI, the next step is to integrate these steps in the identity spec.
As part of this next step, we might add in webrtc-pc some hooks to ease authoring of the identity spec.

**Comment by jan-ivar** [comment]
I've moved this to identity in https://github.com/w3c/webrtc-identity/pull/30.
