### ISSUE TITLE
Clarify what happens to codecs when rolling back

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2368]
Spin-off from [here](https://github.com/w3c/webrtc-pc/issues/2324#issuecomment-558127202):

> What happens if you swap out codecs? Early media-reasoning would suggest that codecs are applied at SLD(offer) rather than SRD(answer). This implies that existing packets on the wire with an old codec would get dropped while have-local-offer. If offers were proposed to be changed and we roll back, then what we need to do on rollback is the revert codec settings.
> This assumes we don't do anything special for smooth transition when changing codecs.

**Comment by alvestrand** [comment]
What do you mean by "swap out codecs"?
Remembering that a payload type, once assigned, can't be reassigned - what's the scenario that you envision?

**Comment by henbos** [comment]
Are you not allowed to add or remove codecs in follow-up negotiations?

I imagined a VP8-only stream that turns into a VP9-only stream, for example.

**Comment by henbos** [comment]
Even if "swapping out" is not possible, you would have to revert it to null on initial offer and you would also need to revert it for the sake of codec preference order, right?

**Comment by henbos** [comment]
> Remembering that a payload type, once assigned, can't be reassigned - what's the scenario that you envision?

Is there not a difference between a payload type that is on offer, pending approval, and it having been assigned in a stable offer? Imagine the following:

```
pc1: SLD(offer) where PT 101 maps to VP9
pc1: Rollback due to receiving a remote offer
pc2: SRD(offer) where PT 101 maps to H264
pc1 needs to be able to accept pc2's offer... pc2 does not know anything about the rolled back offer
```

**Comment by henbos** [comment]
In any case there are two things here: payload types, which can't change once assigned (though I would argue the above shows that they must not be considered fully assigned until the answer), and the actual codecs included and the order, i.e. what is modifiable with setCodecPreferences(). This is not permanent.

**Comment by henbos** [comment]
Interim [slide](https://docs.google.com/presentation/d/1QEdMf6Ixg1NNvHoZUvO29njrSKn9pdF1WqcrFWI4uX8/edit#slide=id.g6b7f95ec98_0_23): Revert the [[ReceiveCodecs]] internal slot on rollback

**Comment by alvestrand** [comment]
OK, you mean "swapping out" as in offering a new payload type, having that payload type accepted, and then starting to use it for sending, stopping the use of the previous payload type.
Like this:

offer: PT 74=VP8
answer: PT 74=VP8 (accepted)
(offerer sends using VP8)
offer: PT 74=VP8, PT75=VP9
answer: PT74=VP8, PT75=VP9, preference=75, 74
(offerer switches to VP9)

I think removing PT74 in this case would break stuff, so we shouldn't do it.
Note - I think this is JSEP-land. But it's tangential to the rollback question.

On whether the rollback can free up content-types: Yes, I think it should. The theory of rollback is that the other guy never saw the offer, so it has no chance to avoid using those PTs.

**Comment by henbos** [comment]
When I started this issue I wasn't even thinking about payload type mapping, but if a payload assignment is on offer and is then rolled back, using that payload type to map to any codec should be fair game. This is JSEP territory.

As for preferred codecs (i.e. which codecs are included in the list and what the order of that list is), these also need to be rolled back.

The outcome of #2332 is that we need to explicitly list all the steps to perform in webrtc-pc land for "rollback". So it makes sense that one of the internal slots we'll need to revert is [[ReceiveCodecs]].

> I think removing PT74 in this case would break stuff, so we shouldn't do it.
> Note - I think this is JSEP-land. But it's tangential to the rollback question

Separate from the "rollback" issue addressed here, but if the following is illegal due to JSEP rules then we have a bug in webrtc-pc:
```
setCodecPreferences(VP8, VP9);
O/A exchange
setCodecPreference(VP8);
O/A exchange
```

This should work. Whether this continues to list the VP9 payload type in the SDP or not I don't know, but this should generate SDP where VP9 cannot be chosen. That is, the VP9 payload type must not be listed in the "m=video [...] &lt;list of payload types&gt;" line.

**Comment by henbos** [comment]
Alternatively, if this is illegal, then we need to make setCodecPreferences() throw. Do we need to file a separate issue for this (unrelated to rollback)?

**Comment by henbos** [comment]
FYI I filed #2371.
