### ISSUE TITLE
[[ReceiveCodecs]] is only set on answer. How to achieve early media?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2369]
In order to support early media, we have to be prepared to receive streams with the proposed codecs even if we have not yet set the answer. This is not true for sending, which can wait until answer, but for receiving, I think decoders would be configured at setLocalDescription(offer).

Shouldn't this be reflected in [[ReceiveCodecs]]? getParameters() is said to return a value for codecs even if [[SendEncodings]] has not been set by a remote description (#2313).

**Comment by alvestrand** [comment]
My first inclination is to say that [[ReceiveCodecs]] should contain all codecs that have been assigned a definition, which means all PTs from all offers and answers processed for that media section.
That means updating whenever we send *or* receive *either* an offer *or* an answer.
It's possible to negotiate changes to the codec parameters, but not the basic existence of the codec for the PT (I don't think the a=rtpmap line can change, ever, but at least for H.264, the a=fmtp line can) - but I *think* (offhand) that negotation only affects [[SendCodecs]] - what we can receive is unaffected; it's only determined by our reception capabilities.

**Comment by alvestrand** [comment]
VI decision: Accepted. In addition, we make a note that "codecs negotiated for receiving" means that the list is empty when mode is sendonly.
