### ISSUE TITLE
Add a perfect negotiation example

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2370]
The spec doesn't really discuss [perfect negotiation](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/), as it's more of a recommended pattern for users than a concern for implementors. But an example would probably be great.

A need to reference this came up around *addIceCandidate* in https://github.com/w3c/webrtc-pc/issues/2367#issuecomment-558309247.

**Comment by henbos** [comment]
If we cover how to use addIceCandidate safely inside the Perfect Negotiation example, I think we can close #2367.

**Comment by henbos** [comment]
Another thing you may need to take into account: getParameters(), rollback, setParameters(). E.g. #2368
