### ISSUE TITLE
setCodecPreferences() and removing a codec after initial negotiation

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2371]
Spin-off from #2368.

Suppose I do the following:
```
setCodecPreferences(VP8, VP9);
O/A exchange
setCodecPreference(VP8);
O/A exchange
```

What should/does happen?
1. In the second offer, the VP9 payload type is not listed, and the a=video line does not reference it.
2. In the second offer, the VP9 payload type is still listed, but the a=video line does not reference it.
3. Invalid SDP is generated because JSEP demands payload types be set in stone and the a=video line to reference all PTs in some order.

If either 1) or 2) happens then setCodecPreference() has the effect that I though we desired. It was my assumption that 1) is what happens, but if it turns out PTs are more like m= sections and cannot be unlisted, then 2) makes more sense.

On the other hand, if 3) is the case, then we need to update webrtc-pc to say that the second setCodecPreference() throws an exception because we're changing the set of codecs after the initial negotiation. This is not something we currently guard against.

@alvestrand @jan-ivar

**Comment by henbos** [comment]
I made a [codepen](https://codepen.io/henbos/pen/ZEEdKKB), and on Chrome this acts according to 1). I think this works as intended, and I'll remove the slide from the virtual interim and making this not blocking WebRTC 1.0 to PR.

I propose we close this issue, but I'm keeping it open to give people time to react to it.

**Comment by henbos** [comment]
@jan-ivar Can you run the codepen on Firefox and make sure you get the same behavior?

**Comment by alvestrand** [comment]
Put in the spec that this is how it will behave?

**Comment by jan-ivar** [comment]
@henbos Sadly, Firefox does not support `setCodecPreferences` yet ([bug 1396922](https://bugzilla.mozilla.org/show_bug.cgi?id=1396922)).
