### ISSUE TITLE
Move henbos/webrtc-extensions to w3c/webrtc-extensions

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2378]
As discussed during the [November 2019 Virtual Interim](https://www.youtube.com/watch?v=LxGiXdlOEr0), we should move https://github.com/henbos/webrtc-extensions from my personal github to w3c to reflect the fact that it has been adopted by this working group.

**Comment by henbos** [comment]
This may include adding a proper introduction, updating some of the config files and making sure the readme and licenses are correct.

**Comment by henbos** [comment]
I'm happy to write the introductions but I'd appreciate some help with reviewing and fixing "spec configs", readmes, etc.

**Comment by dontcallmedom** [comment]
@henbos can you give me admin rights on https://github.com/henbos/webrtc-extensions and https://github.com/henbos/webrtc-provisional-stats to proceed with the move?

**Comment by henbos** [comment]
I both added you as a collaborator (which was probably not very helpful) and then I clicked to transfer ownership to you. Hope that works?

**Comment by dontcallmedom** [comment]
https://github.com/w3c/webrtc-extensions
