### ISSUE TITLE
Move henbos/webrtc-provisional-stats to w3c/webrtc-provisional-stats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2379]
As discussed during the [November 2019 Virtual Interim](https://www.youtube.com/watch?v=LxGiXdlOEr0), we should move https://github.com/henbos/webrtc-provisional-stats from my personal github to w3c to reflect the fact that it has been adopted by this working group.

This may include adding a proper introduction, updating some of the config files and making sure the readme and licenses are correct.

**Comment by dontcallmedom** [comment]
https://github.com/w3c/webrtc-provisional-stats

**Comment by henbos** [comment]
Thanks!
