### ISSUE TITLE
Editors vs Former editors

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2386]
In https://github.com/w3c/webrtc-pc/pull/2359/files we separated "Editors" and "Former editors" into two separate categories. Cullen Jennings (Cisco) is listed as "Editor" rather than Former editor. When did Cullen stop editing?

**Comment by henbos** [comment]
@dontcallmedom can you take a look?

**Comment by dontcallmedom** [comment]
his [last commit](https://github.com/w3c/webrtc-pc/commits?author=fluffy) was in Nov 2017

**Comment by henbos** [comment]
Thanks I made a PR

**Comment by fluffy** [comment]
I have not stopped editing AFAIC - the chair has asked me not to submit PR for now

**Comment by lgrahl** [comment]
:popcorn:
