### ISSUE TITLE
Update Perfect Negotiation example with the right error code

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2398]
When addIceCandidates rejects candidates belonging to a discarded offer, a specific error code will be returned. The example should show which error code to ignore when doing addIceCandidate, rather than ignoring all offers.

**Comment by jan-ivar** [comment]
Is there a dedicated error for this? Which one is it?

**Comment by alvestrand** [comment]
Likely to be OperationError. Let's check for consistency across browsers by adding a WPT:

**Comment by henbos** [comment]
We might care in a test, but in an application example we probably don't care because we want to discard it anyway
