### ISSUE TITLE
Steps needed to rollback data channels

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2408]
Chrome has [a bug](https://crbug.com/1032987) when rolling back after createDataChannel and setting a remote offer.

```
(async () => {
  try {
    const pc = new RTCPeerConnection(), pc2 = new RTCPeerConnection();
    pc.createDataChannel("dummy");
    pc2.addTransceiver("video");
    const outgoingOffer = await pc.createOffer();
    const incomingOffer = await pc2.createOffer();
    pc.onsignalingstatechange = () => console.log(pc.signalingState);

    const p1 = pc.setLocalDescription(outgoingOffer);
    const p2 = pc.setRemoteDescription(incomingOffer);
    await p1;
    console.log(`After await SLD: ${pc.signalingState}`);
    await p2;
    console.log(`After await SRD: ${pc.signalingState}`);
  } catch(e) {
    console.log(e);
  }
})();
```

This should work but instead we get:

> InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to apply the description for 0: Failed to setup RTCP mux.

Two questions:
1. What, if anything, do you need to rollback with regards to data channels on local offer? (Implementer asking for advice.)
2. Is this JSEP territory-only, or do we need to update our rollback steps in webrtc-pc? (Natural follow-up to 1)

**Comment by henbos** [comment]
@jan-ivar @alvestrand Anything we need to do here blocking PR?

**Comment by jan-ivar** [comment]
AFACT, searching for "sctp" and "data", all JS observable data-channel related changes appear to happen in the answer, so nothing to roll back.

**Comment by henbos** [comment]
I don't find anything that needs to be rolled back either :) Closing issue.
