### ISSUE TITLE
Construct RTCError with name OperationError (take two!)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2437]
I remember merging [a PR that made RTCError construct with "OperationError"](https://github.com/w3c/webrtc-pc/pull/2375), but looking at [the latest spec](https://w3c.github.io/webrtc-pc/#dom-rtcerror) it is being constructed as "RTCError"...

Did we accidentally revert stuff?

**Comment by henbos** [comment]
Do you know what could have happened @dontcallmedom ?

**Comment by dontcallmedom** [comment]
@henbos look like you reverted it in https://github.com/w3c/webrtc-pc/commit/76c20cf5fa3478e69ad8b746f84b7e712744a68c as part of #2380 although it's not clear (to me) why

**Comment by henbos** [comment]
I'm getting confused by the diffs here, but I'm guessing I accidentally reverted it trying to fix travis errors. But OK, I'll make another PR
