### ISSUE TITLE
set{Local|Remote}Description is underspecified

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#244]
I realized that when I added the identity stuff here, it was lean, but I didn't realize how lean.  I know that JSEP defines a lot of this, but when you look at the draft everything seems to hinge on this statement here:

> The user agent must start the process to apply the RTCSessionDescription argument.

And this is completely unsupported with references.  I know that JSEP is going to define this, but it at least needs a reference here, otherwise the reader is left with nothing.

`setRemoteDescription` is worse.

**Comment by martinthomson** [comment]
One particular case that the spec doesn't answer is when the `onaddstream` event fires, or as it seems to be now, the `ontrack` event.  The string "onaddstream" doesn't even appear in the spec!  Why did we remove the description?  Everyone who implements the API has to implement `onaddstream`, so why don't we document it?

**Comment by adam-be** [comment]
`setRemoteDescription()` uses the same processing model as `setLocalDescription()` at the moment but we've talked about extracting it into a separate section. Let's do the move and improve it from there.

**Comment by alvestrand** [comment]
There have been updates; we need to check this against current state of spec.

**Comment by alvestrand** [comment]
The text has been cleared up a lot in recent versions. #266 was especially helpful.
