### ISSUE TITLE
Rejecting invalid session description

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2441]
Current step 3.1.6 of setting a session description reads:
> If the content of description is invalid, then reject p with a newly created `InvalidAccessError` and abort these steps.

It's not clear what kind of invalidity is meant; step 4 deals with invalid SDP, step 5 with invalid RIDs, step 7 will all other kind of errors.

**Comment by alvestrand** [comment]
For remote descriptions, I think it would be the result of "Next, the SessionDescription is parsed into a data structure, as described in Section 5.8 below.  If parsing fails for any reason, processing MUST stop and an error MUST be returned."
I think the assumption is that JSEP section 5.6 returns information about what failed.

**Comment by dontcallmedom** [comment]
so, the invalid SDP step (3.1.4) would be about syntax, whereas step 3.1.6 would be about sematics verification per [JSEP 5.8.3](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-26#section-5.8.3)? I wonder if any implementation distinguishes between the two at the moment.

In any case, if that is indeed the distinction, I'll be happy to provide a pull request to clarify that.

**Comment by alvestrand** [comment]
I wonder how we can write a test case for it. Perhaps we should mark this "test needed"; if browsers are consistent, we can make the spec say what the browsers do.

**Comment by jan-ivar** [comment]
I think we can test this in https://github.com/w3c/webrtc-pc/pull/2514.
