### ISSUE TITLE
Review test coverage of the entire document

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2442]
:) sorry guys

**Comment by alvestrand** [comment]
Need guidance from Dom on the notations - and in particular how one decides that a section should be left as white (no test needed)?
Is there documentation?

**Comment by alvestrand** [comment]
Assignments for next week:
- 4: Jan Ivar
- 5: Youenn
- 6 and 7: Harald
- 8: Henrik
- 9 and 11: Bernard

**Comment by dontcallmedom** [comment]
The test coverage system tries to automatically identify the normative pieces of the spec that needs test coverage, using the following algorithm:
* anything that uses an RFC keyword is expected to need test
* anything in an algorithm step (marked up with `<ol>`) is expected to need test

To complete these automatic annotations, there are 3 annotations that can be set with a `class` attribute on elements:
* `class="untestable"`: something that is normative, but can't be meaningfully tested (e.g. "if something unexpected happens, throw an error")
* `class="no-test-needed"`: something that is part of a normative piece of the spec and flagged as such by the automatic detection of things that needs test, but that in practice doesn't need to be tested (e.g. naming the variables representing the values of a method parameters)
* `class="needs-test"`: something not automatically flagged as needing test, but in fact needing test.

The resulting view shows in red things that should be tested but aren't, in green the things that are tested (determined by the `data-tests` attribute), and in white the things that aren't expecting tests.

**Comment by youennf** [comment]
Is there a pointer to the test coverage report?

**Comment by dontcallmedom** [comment]
the test coverage is available via the ReSpec pill at the top of the spec ("Toggle test coverage view")

**Comment by jan-ivar** [comment]
> * `class="needs-test"`: something not automatically flagged as needing test, but in fact needing test.
> 
> The resulting view shows in red things that should be tested but aren't

@dontcallmedom So `<td class="needs-test">` should show up as red? It's not working for me.

However, `<td data-tests="">` does show in red, so I'm using that.

**Comment by dontcallmedom** [comment]
it should have read `needs-tests` - but your approach is perfectly valid as well.

**Comment by aboba** [comment]
@dontcallmedom Have found some "untestable" normative statements. If a normative statement isn't verifiable, it seems like a sign that we should revisit it, no?

**Comment by henbos** [comment]
Closing as obsolete, sufficient test coverage documented
