### ISSUE TITLE
add back addstream event

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#245]
When we changed from AddStream to AddTrack on the sender side, we also removed the "addstream" event (specified in http://w3c.github.io/webrtc-pc/archives/20150202/webrtc.html).

Discussion on the list in June 2015 indicated a desire to put it back into the spec, either as a backwards compatibility feature or as a permanent feature (it's not trivial to see when setRemoteDescription results in new streams vs changes to old streams).

**Comment by fluffy** [comment]
bulk of people I have talked to think that theses should not have been removed and should be put back until the list discussion concludes ..

**Comment by juberti** [comment]
Are you saying that this cannot be polyfilled?

**Comment by ekr** [comment]
I would like to see a much stronger argument for re-adding this than I have seen so far

**Comment by juberti** [comment]
likewise

**Comment by alvestrand** [comment]
note that "this" is the addstream event (and onaddstream handler). Polyfilling AddStream is trivial.
@fluffy can you present more argument here?

**Comment by fluffy** [comment]
Note my comment was people though the spec should not have changed until the list was clear on what change should be. I was not arguing one way or another for what the list should decide.

**Comment by stefhak** [comment]
We haven't hear more arguments for adding this back in, and polyfilling should work. Closing.
