### ISSUE TITLE
Use p class="note" and div class="note"

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2451]
Sometimes we use &lt;p class="note"&gt; and sometimes we use &lt;div class="note"&gt;. Should we be consistent here or is this question not even worth asking?

**Comment by dontcallmedom** [comment]
I think we can safely have that level of inconsistency :)

(I would say use div if there is more than one paragraphs in the note, but...)

**Comment by henbos** [comment]
OK, closing as "don't really care" :)
