### ISSUE TITLE
Follow-up to set variables outside queued task when handling ICE state and candidate pair changes in the same task

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2454]
Follow-up from https://github.com/w3c/webrtc-pc/pull/2444.

**Comment by jan-ivar** [comment]
Please add back the `IsClosed` check as well https://github.com/w3c/webrtc-pc/pull/2444#issuecomment-577716623

**Comment by henbos** [comment]
The IsClosed check is already there (need to show more lines to see it)

**Comment by henbos** [comment]
@jan-ivar I'm taking a look at this now a few months later and I don't remember what this issue is about. Is a change needed?
Did you want me to set some variable before queuing the task or...?

**Comment by henbos** [comment]
Removing the Ready for PR level since I don't know what I should do with it until I get feedback
