### ISSUE TITLE
How to refer to "disassociated transcievers"

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2455]
See [comment](https://github.com/w3c/webrtc-pc/pull/2445#pullrequestreview-348054866): Should we say disassociated, dissociate, unassociated, etc?
Should we define its keyword where we already define **[associated](https://w3c.github.io/webrtc-pc/#rtcrtptransceiver-interface)**?

Created this follow-up issue so that the discussion doesn't get lost. @jan-ivar

**Comment by henbos** [comment]
Proposal: "unassociated"

**Comment by jan-ivar** [comment]
I just noticed [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.10) uses "disassociated" (2 hits) and "dissociated" (1 hit), not "unassociated" (0 hits).

So I think we should leave this alone.
