### ISSUE TITLE
RTCIceCandidatePairStats.priority is listed as MTI but is obsolete

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2457]
`RTCIceCandidatePairStats.priority` is listed as a mandatory to implement stat, but it is [obsolete in the stats spec](https://w3c.github.io/webrtc-stats/webrtc-stats.html#dom-rtcicecandidatepairstats-priority)

**Comment by henbos** [comment]
Let's remove it, it was removed for privacy reasons.
