### ISSUE TITLE
RTCIceCandidate's sdpMid and sdpMLineIndex members

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#246]
The spec currently says:
"When constructed, values for candidate and either sdpMid or sdpMLineIndex MUST be provided."

We need to either specify that an error should be throw when the dictionary is constructed or check this in the addIceCandidate() steps. 

Depends on the outcome of: https://github.com/w3c/mediacapture-main/issues/189

**Comment by adam-be** [comment]
PR #407 should resolve this issue

**Comment by dontcallmedom** [comment]
PR #407 was merged, so I assume this can be closed
