### ISSUE TITLE
Unit of RTCRtpEncodingParameters::maxBitrate is only implicitly defined

### ISSUE THREAD

**Issue by rasmusbrandt** [w3c/webrtc-pc#2462]
The WebRTC spec does not explicitly specify the unit of [RTCRtpEncodingParameters::maxBitrate](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-maxbitrate). Rather, the value of the field itself is defined as the `TIAS bandwidth` from [RFC3890](https://tools.ietf.org/html/rfc3890). In [Section 6.2.2](https://tools.ietf.org/html/rfc3890#section-6.2.2) of that RFC, it's clear that the `maxBitrate` field should be set in `bps`.

In order to help novice users/quick readers of the spec, it might be worth spelling out the unit explicitly in the spec itself.

**Comment by rasmusbrandt** [comment]
cc @alvestrand @henbos @Orphis for thoughts.

**Comment by henbos** [comment]
Good idea, ready for PR

**Comment by rasmusbrandt** [comment]
PR: https://github.com/w3c/webrtc-pc/pull/2485
