### ISSUE TITLE
disallow pairing ice-tcp candidates with local ip addresses

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#2465]
After reading [the post about using onicecandidateerror for portscanning](https://medium.com/tenable-techblog/using-webrtc-ice-servers-for-port-scanning-in-chrome-ce17b19dd474) (see also #2426) I wondered if ICE-TCP can be used to detect whether a TCP port is open as well.
It is possible (in Chrome) even if the remote port never responds to any stun requests.

With @alvestrand's help I've just landed a change in chrome/webrtc.org that disallows pairing with an ICE-TCP candidate that has a local IP address:
  https://webrtc.googlesource.com/src.git/+/712ebbb5b73baf30f11711efdceb6f08248fac38
It seems unlikely that ICE-TCP is used often on the local network (which would imply UDP is blocked) but if you know cases where this would now be broken please holler.

We'll also need some text in the security considerations.

**Comment by henbos** [comment]
I propose we treat "port closed" and "port open but it isn't ICE" the same way we time out if we don't get a response at all. Only if we get back valid ICE do we fire errors.

**Comment by fippo** [comment]
https://github.com/w3c/webrtc-pc/issues/2426#issuecomment-572612509 -- you would to hold off incrementing bytesSent until you received a response which sounds complicated and error-prone.

**Comment by nils-ohlmeier** [comment]
As a word of caution: we tried something like this (don't pair candidates from different RFC1918 ranges) in Firefox and ended up disabling that feature/protection after too many users with unusual VPN setups complained.

**Comment by alvestrand** [comment]
It seems that we do have users of this configuration with Chrome too.

**Comment by aboba** [comment]
Based on experience in FF and Chromium (where it's in the process of being reverted), the proposed change is probably not viable.
