### ISSUE TITLE
What is the behavior when the RTP extension for rotation is sent?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2483]
In the rtcweb-video spec, it says that WebRTC endpoints MUST support the RTP header extension for camera rotation. What should happen to the mediastreams produced by WebRTC in that case?
This was noticed as an issue when considering https://github.com/w3c/mediacapture-main/issues/660

**Comment by jan-ivar** [comment]
Example:
```
a=extmap:13 urn:3gpp:video-orientation
```

**Comment by aboba** [comment]
Here is the specification that defines the RTP header extension: 
https://www.etsi.org/deliver/etsi_ts/126100_126199/126114/13.02.00_60/ts_126114v130200p.pdf

**Comment by henbos** [comment]
I would assume that supporting this header extension is relevant for the browser sending and receiving so that the video has the correct side up, but in terms of the JavaScript API, we don't expose this. Is it relevant for the JS layer to expose it?

**Comment by aboba** [comment]
It would appear that only the camera rotation bits are implemented. The Flip and Camera Front/Back bits seem like privacy issues so lack of implementation is probably a good thing.

**Comment by lgrahl** [comment]
I don't see how the rotation is any less of a privacy issue. :slightly_smiling_face:

**Comment by alvestrand** [comment]
This seems to be a matter for the specification of the RTP extension to clarify, which is out of scope for this group. Closing.
