### ISSUE TITLE
Close other peer's dtls & datachannel after unload

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2490]
From https://github.com/w3c/webrtc-pc/issues/2489#issuecomment-597949645 [it appears](https://jsfiddle.net/jib1/df0juyxk/) Firefox & Chrome 82 [close](https://w3c.github.io/webrtc-pc/#dfn-close) other peer's datachannels after [unload](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event).

This covers closing a tab/window, navigation and reload. This seems useful to specify.

It would probably suffice to run (part of) the [close](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-close) algorithm on all peer-connections on the page, including iframes, on tear-down (this is what Firefox does).

**Comment by jan-ivar** [comment]
On second thought, it might be useful to only shut down the transport objects, to leave the door open to bfcaching a peer connection. @youennf thoughts?

**Comment by youennf** [comment]
Related to https://github.com/w3c/webrtc-nv-use-cases/issues/56.

I do not see why we are special casing data channel here.
Isn't closing a data channel similar to stopping a transceiver?

I am not exactly sure what you mean by shutting down the transport objects.
If the DTLS connection is closed, the SCTP will get closed so the data channel will be closed, right?

If we simulate a network error or a freeze of the whole process doing networking, we would probably end up going in disconnected or failed ICE  transport state after some time spent in the b/f cache (except the page will only be notified of those changes if resurrected from the b/f cache). If we just go back and forth (like I wrongly navigated and went back), the connection would probably remain the same.

**Comment by jan-ivar** [comment]
> I do not see why we are special casing data channel here.

Happy to include dtls if it helps the discussion, as long as we're specific.

> If the DTLS connection is closed, the SCTP will get closed

That's [one way](https://w3c.github.io/webrtc-pc/#idl-def-RTCSctpTransportState.closed) (through "[close_notify alert](https://w3c.github.io/webrtc-pc/#dom-rtcdtlstransportstate-closed)"), the other being reception of SCTP ABORT. The [pc.close](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-close) algorithm mentions _"sending an SCTP ABORT chunk"_, so I'm not 100% sure which one gets the credit.

Regardless, they're intentional termination signals. But how terminal are they to our objects?

> Isn't closing a data channel similar to stopping a transceiver?

I think we're talking about [closing](https://w3c.github.io/webrtc-pc/#idl-def-RTCSctpTransportState.closed) the SctpTransport (`pc.sctp`), i.e. _all_ datachannels permanently. See https://github.com/w3c/webrtc-pc/issues/2486. It's not clear to me this is recoverable. if I `pc.createDataChannel("onemore")` and renegotiate, what happens?

In contrast, stopping a transceiver is a negotiated property (without negotiation it sends RTCP BYE which merely mutes the remote track).

> If we just go back and forth (like I wrongly navigated and went back), the connection would probably remain the same.

Then we'd need to avoid all terminal steps in the [pc.close](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-close) algorithm. It's a bit unclear to me what those are, but I fear it's most of them.

**Comment by alvestrand** [comment]
Seems like we have a simpler world if page.onunload() triggers pc.close() automatically. Recovery is complicated, and we have had no use cases where recovery is helpful.

Things may be different in webrtc-nv.

**Comment by jan-ivar** [comment]
To be addressed by PR in https://github.com/w3c/webrtc-pc/issues/2516
