### ISSUE TITLE
Mark voiceActivityFlag as at risk

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2496]
The spec requires that`RTCRtpSynchronizationSource` exposes a [`voiceActivityFlag`](https://w3c.github.io/webrtc-pc/webrtc.html#dom-rtcrtpsynchronizationsource-voiceactivityflag) boolean, but this has not been implemented anywhere, nor am I aware that anyone is planning to implement this in the short term.

As a result, I think we should mark the feature as at risk for our next publication.

**Comment by aboba** [comment]
March 30, 2020 interim decision:  mark as a "Feature at Risk".
