### ISSUE TITLE
Mark multiple DTLS certificates at risk

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#2498]
None of the implementations tested in WPT pass the [test of supporting multiple certificates](https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCCertificate.html#L237) when creating (or configuring) an `RTCPeerConnection` object, as [required by the spec](https://w3c.github.io/webrtc-pc/webrtc.html#dom-rtcconfiguration-certificates).

The relevant [Chromium bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=5934) hasn't seen much activity recently, and the relevant [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1531880) is marked P3.

Should this feature be marked at risk?

**Comment by fippo** [comment]
@taylor-b can you comment since you've been the owner of the chromium bug a long time ago?

**Comment by taylor-b** [comment]
I'm not aware of any opposition to this feature, it's just one of the many things that hasn't been high priority enough to get implemented yet.

**Comment by henbos** [comment]
This was discussed at the [March 30th virtual interim](https://docs.google.com/presentation/d/14ndue3gU9n970tltc7kIeW3LNS1KTdQS1JmUogECr-g/edit#slide=id.g81abe42132_0_0).

If I understood this issue correctly, the assumption was that multiple certificates was added to support multiple kinds of certificates in case all types were not supported? But with full support for DTLS 1.2, this is no longer relevant, and TLS is being deprecated.

@aboba Was the consensus to mark multiple certificates as at risk or to remove the support altogether?

**Comment by dontcallmedom** [comment]
my understanding is that the resolution was to change the spec to say that only the first certificates of the list is used and the others are ignored (but the API still allows for a list for legacy reasons)
