### ISSUE TITLE
connectionState error: State with no defined outcome

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2499]
Imagine the following:
- SDP-negotiate a PeerConnection with two *unbundled* m-sections
- Fire ICE candidates at only the first m-section. Don't negotiate the second one.

The result is that the first DTLS transport gets to "connected", the second DTLS transport remains "new".
In the table in https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnectionstate, there is no description that corresponds to the combination of "new" and "connected" transports.

What should the state be?

Thanks to @fippo for demonstrating the bug. (It currently results in state "connecting" in Chrome, but media flows on the first m-section.)

**Comment by fippo** [comment]
We thought this would reproduce the issue we saw but the reproduction is a bit more complicated and media does (for reasons that I do not understand yet; we might have found a bug discussing another bug) for the first m-section. Instead:
* on local pc negotiate audio+video
* on remote pc add a bogus third m-line, remove bundle, call SRD.
* create answer on remote, SLD
* remove third bogus m-line, call SRD on first
* filter ice candidates with sdpMLineIndex > 1 from remote to local

Result:
- local states are all connected which allows sending
- remote ice transport states end up being [connected, connected, new]
- remote dtls transport states end up being [connected, connected, new]
As a result the remote iceconnectionstate is checking and the connectionState connecting.
The video plays on the remote end.

[partially-connected.txt](https://github.com/w3c/webrtc-pc/files/4387430/partially-connected.txt) -- rename to .html

**Comment by alvestrand** [comment]
We're not fully connected, so it's not "connected".
If we add candidates, we can complete connection, so it's not "failed".
Media is flowing, so it's not "disconnected".
Seems like "connecting" is the logical one.

**Comment by henbos** [comment]
"connecting" makes sense considering how we deal with other partial-connections. Let's add a note though as a heads-up
