### ISSUE TITLE
Identity provider should be listed as product in the Conformance section

### ISSUE THREAD

**Issue by tidoust** [w3c/webrtc-pc#250]
If I understand correctly, the Identity provider (IdP) will implement the [`RTCIdentityProvider`](http://w3c.github.io/webrtc-pc/#idl-def-RTCIdentityProvider) interface, which makes it a **product** of the specification that should be identified as such in the [Conformance](http://w3c.github.io/webrtc-pc/#conformance) section.

The definition of `user agent` in that Conformance section should also be slightly updated to reflect the fact that it does not implement the `RTCIdentityProvider` interface.

**Comment by fluffy** [comment]
See if that text looks about right and just tell me what it should say if it is not
