### ISSUE TITLE
respec error: non-existant Web Platform Test

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2500]
The current "tip of tree" shows the following respec error: 

"Linter (wpt-tests-exist): Non-existent Web Platform Tests: RTCPeerConnection-close.html. Please fix the tests mentioned. See developer console. Occured at: 1, 2."

**Comment by jan-ivar** [comment]
Should be RTCPeerConnection-onsignalingstatechanged.https.html
