### ISSUE TITLE
Update RTCTrackEvent to use FrozenArray<>

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#251]
s/MediaStream[]/FrozenArray<MediaStream>/

http://www.w3.org/mid/BLUPR03MB38939AF0981AFF796FE3640F8990@BLUPR03MB389.namprd03.prod.outlook.com

**Comment by annevk** [comment]
Note that the dictionary should take `sequence<MediaStream>`. That it uses `[]` is wrong.

**Comment by alvestrand** [comment]
@martinthomson, is it still wrong? Can you make a PR to fix it?
