### ISSUE TITLE
Calling SRD twice isn't web compatible

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2512]
Calling SRD twice (ditto SLD) may be well-defined in webrtc-pc, but it's not in JSEP.

![state diagram](https://w3c.github.io/webrtc-pc/images/peerstates.svg)

Firefox does something akin to a silent mini-rollback in-between, whereas Chrome does not, instead [failing](https://jsfiddle.net/jib1/xtk7np5m/) all offers different¹ from the first:
```js
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection':
Failed to set remote offer sdp: The order of m-lines in subsequent offer doesn't match
order from previous offer/answer.
```
In Firefox these succeed² instead. But its aggressive mini-rollbacks produce different transceiver objects even with identical offers, which doesn't seem great either. 

Who's right? Who won? You decide!

<sub>1) Turns out Chrome [allows m-lines to grow](https://jsfiddle.net/jib1/pk84hex9/), but not shrink. Also [media kinds cannot change](https://jsfiddle.net/jib1/fye9wcp1/).</sub>
<sub>2) We're fixing [some disappearing transceivers](https://bugzil.la/1630029) in Firefox atm, but that shouldn't distract from the different interpretations.</sub>

**Comment by jan-ivar** [comment]
Last I heard of a real-world use case for offer trumping was the ["pushy SFU"](https://docs.google.com/presentation/d/1UrXARLbAfwmfK686rX_9W_-FGIc62ZDwVd079wIoX7I/edit?ts=5cdd966f#slide=id.g5b048ace1b_21_24) use case.

**Comment by jan-ivar** [comment]
It was mentioned to me that a simple workaround for the pushy SFU case is as described in that slide: queue requests, basically visit `"stable"` in-between. So failure here may not matter much. OTOH it might inform how it should work.

**Comment by fippo** [comment]
yeah, i've typically done a "if there is a cycle pending, put the operation into a queue, take stuff from the queue on next signalingstatechange to stable".
What this avoids is the following flow:
* SRD (1)
* SRD (2)
* createAnswer (1)
* createAnswer (2)
* SLD (1)
* SLD (2, :boom: can't call SLD twice)

**Comment by jan-ivar** [comment]
Good point that [SLD](https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription) will throw `InvalidModificationError` if called with anything other than [[LastCreatedAnswer]] or [[LastCreatedOffer]]. The [diagram](https://github.com/w3c/webrtc-pc/issues/2512#issue-599837550) is only for `InvalidStateError`.

I think this suggests Chrome's behavior is sufficient.

**Comment by jan-ivar** [comment]
I think the remaining question then is whether Chrome's behavior is worth specifying. Or simpler:
 1. undefined behavior
 1. throw `InvalidModificationError` if SRD called twice
 1. throw `InvalidModificationError` if called with something not identical to the last description
 1. throw `InvalidModificationError` if called with fewer m-lines or different kind
 1. throw `InvalidModificationError` like Chrome does, which may be the same as 4 or not?

**Comment by alvestrand** [comment]
Chrome's behavior is probably "Run the check for subsequent offers, and if those checks pass, accept it". That might be *relatively* easy to specify.
