### ISSUE TITLE
What happens to PC when page suspends?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2513]
At the risk of recycling some of the discussion, this is a follow-up to [What happens to the peer connection when the laptop lid closes?](https://github.com/w3c/webrtc-pc/issues/2489) The conclusion of that issue was that nothing happens to the PC, and what happens to tracks is a [separate issue](https://github.com/w3c/mediacapture-main/issues/668).

However if the page suspends (which _may_ or _may not_ happen when lid closes, depending on OS, system, settings, browser, etc) we may want to specify what happens.

The PC should not close, that should only happen on close(), but for example it might be useful to send RTCP_BYE to let the other endpoint know that the PC is will not be active anymore.

Old discussion for reference: https://mailarchive.ietf.org/arch/msg/rtcweb/Qx0BvT0KbEvDpWfV5ZI2amodTC4/

**Comment by henbos** [comment]
Conclusion from dscussion: nothing happens.

**Comment by alvestrand** [comment]
Conclusion from discussion: Nothing happens, we specify nothing.
