### ISSUE TITLE
Does a PC depend on the page context?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2516]
In a recent bug, we discovered that code in RTCPeerConnection depended on having a valid execution context.
This is no longer true if, for instance, the RTCPeerConnection's "window" is an iframe that has been destroyed - but references to the RTCPeerConnection may survive the iframe it was created in.
Apparently, some objects work fine without an execution context; some others don't. So it's up to the specification to say whether or not they are context dependent, and what happens if the context dies.

Alternatives I see (spec-wise):
- When the execution context dies, the RTCPeerConnection is closed, a "signalingStateChange" event is fired at it, and no further operation on it is possible.
- When the execution context dies, the RTCPeerConnection remains active and usable.

This may be related to the question in #2513 (another lifecycle issue).

**Comment by youennf** [comment]
> * When the execution context dies, the RTCPeerConnection is closed, a "signalingStateChange" event is fired at it, and no further operation on it is possible.

When context dies, we probably do not want to fire an event.

> * When the execution context dies, the RTCPeerConnection remains active and usable.

There is obviously a time where the peer connection would need to go away so I am not sure we want that either.

It would be interesting to test the existing behavior in current implementations.
I would think that Safari is basically neutering the RTCPeerConnection, as if close() was called.

**Comment by youennf** [comment]
WebKit has some limited tests in that area: https://github.com/WebKit/webkit/blob/master/LayoutTests/webrtc/pc-detached-document.html
It seems a great area for new WPT tests.

**Comment by youennf** [comment]
For the above WebKit test, Chrome passes the two tests, not Firefox.
The second test seems to indicate that Chrome considers a detached RTCPeerConnection as if it was closed.

**Comment by alvestrand** [comment]
It's important to specify whether we run the close algorithm or just close/discard the PC.

**Comment by henbos** [comment]
See also #2490. Conclusion: run the close steps (don't fire any events) when page goes away

**Comment by henbos** [comment]
Right before onpageunload I guess?

**Comment by alvestrand** [comment]
Suggestion: Add to https://w3c.github.io/webrtc-pc/#garbage-collection
- Rename section to "Object lifecycle concerns"
- Add a paragraph:

When the <find reference>controlling object (or whatever is the right name for it)</> is destroyed, execute the PeerConnection's "close" algorithm.

Note: Closing fires a dozen events on a dozen objects. If we want to block them all, we'll have to do a real audit of the text.

**Comment by henbos** [comment]
PC-layer events should be suppressed, if they don't we have a bug but as for transport-layer or data channel events I don't know, and I would bet that receiver.track.onmute/oneneded fires

**Comment by alvestrand** [comment]
dtlstransport.onstatechange, sctptransport.onstatechange, icetransport.onstatechange are those that are obvious. If "PC-layer" is constructed as "events fired at the PC only", then I think we're good.

**Comment by youennf** [comment]
I wrote a simple test for RTCPeerConnection, RTCDataChannel and local/remote tracks.
All browsers seem to consistently not fire any event for RTCPeerConnection and RTCDataChannel.
Chrome and Safari do not fire events for tracks, Firefox fires the ended event for both local and remote tracks.
