### ISSUE TITLE
Audio sometimes fails to capture, sometimes dissapear during call

### ISSUE THREAD

**Issue by DevJhns** [w3c/webrtc-pc#2520]
Problem lies in header,
I have 4 ppl mesh webrtc with turn/stun,
sometimes participant A can't hear participant B,
but B hears A, sometimes it happens on call start, sometimes it happens during call,
no errors, my idea was: this may be related to disconnect and reconnect and bad connection(on start)
after page refresh it may be solved, or with another refresh, usually it happens with apple, 
mac/ios (even with chrome on mac),
problem is this happens not with me, so I can't check stats and try anything, what may happen, any ideas?
May it be related to sdp? Like, on disconnect, navigator tries next codec?
Strange that video always shown, but not audio.

**Comment by Sean-Der** [comment]
Hey @DevJhns 

This isn't a place for support. Mind moving your question to Stackoverflow, happy to help there!

**Comment by DevJhns** [comment]
@Sean-Der sorry, couldn't find anything about this problem, only 1 same question asked 1,5 years ago on stackoverflow :(

**Comment by Sean-Der** [comment]
No need to apologize! I am happy to help, mind linking to the SO question and I can give a better answer?

**Comment by DevJhns** [comment]
@Sean-Der it would be nice, any direction that may help, becouse I have no idea where problem may be.
