### ISSUE TITLE
[Question] Is it guaranteed that the mid property value of transceiver is the same for setLocalDescription()(sender) and ontrack(receiver)?

### ISSUE THREAD

**Issue by gtk2k** [w3c/webrtc-pc#2527]
I wrote the code.

[gist](https://gist.github.com/gtk2k/00f8c6473372a00a6302692242206bc2)

Video elements are selected and displayed based on their mid property value, but if the transmitter changes the order in which transceivers are created, the receiver mids will no longer match.
(Chrome 81)

**Comment by alvestrand** [comment]
If they are not, file a bug on the relevant browser.
Chrome allocates MIDs as 0, 1, 2 in the order of creation of the transceiver - but this is something that may change at any time; what MID values are assigned is not part of the standard.
Note - mids are allocated on the offerer at createOffer() time, not at transceiver creation time, and are made visible at the answerer after setRemoteDescription(). This may confuse.

**Comment by gtk2k** [comment]
thanks!
