### ISSUE TITLE
Describe what happens with administratively prohibited candidates

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2531]
If a TCP candidate is connecting to a port on the Do-not-connect list (from Fetch), something should happen to the candidate, and a connection attempt should not be made.

It seems OK to do what Chrome currently does, and just ignore the candidate - it does not show up in stats, in remote-description or in GetRemoteCandidates.

**Comment by fippo** [comment]
rejecting would be nice but then what would we do with a remote description containing the same candidate?
Silently ignore it is...
