### ISSUE TITLE
Spec says scaleResolutionDownBy must default to 1, but browsers differ

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2535]
The [spec](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-scaleresolutiondownby) says: _"By default, the sender will not apply any scaling, (i.e., scaleResolutionDownBy will be 1.0)"_.

This is correct in Firefox (78 using a [fiddle](https://fiddle.jshell.net/jib1/yvg81otc/45/show) where `scaleResolutionDownBy` is commented out):
* Three videos of the same size

But incorrect in Chrome ([crbug 1088200](https://bugs.chromium.org/p/chromium/issues/detail?id=1088200)):
* One large, one medium, and one small video.

Unfortunately, the incorrect behavior is clearly a more _useful_ default, making it a web compat issue. I'm filing this spec issue for visibility and clarification of intent. Do we fix Chrome or change the spec? And if we change the spec, then to what?

cc @alvestrand @guidou

**Comment by aboba** [comment]
We need a more complete picture of what existing behavior is. In Firefox, when `scaleResolutionDownBy` is not specified, it is **always** assumed to be 1.0, regardless of the method (e.g. `setParameters`, `addTransceiver`, etc.)?

When there is more than one simulcast encoding, the Chrome default behavior in `addTransceiver` is to assume a default scaling ratio of 2:1.  However, when `scaleResolutionDownBy` isn't specified in setParameters(), is a default value of 1.0 assumed, or some other value (e.g. the existing value)?

**Comment by guidou** [comment]
cc @Orphis

**Comment by jan-ivar** [comment]
> In Firefox, when scaleResolutionDownBy is not specified, it is always assumed to be 1.0, regardless of the method (e.g. setParameters, addTransceiver, etc.)?

@aboba Yes (Firefox [only supports](https://bugzil.la/1396918) setting via setParameters atm.)

> When there is more than one simulcast encoding, the Chrome default behavior in addTransceiver is to assume a default scaling ratio of 2:1. However, when scaleResolutionDownBy isn't specified in setParameters(), is a default value of 1.0 assumed, or some other value (e.g. the existing value)?

No, 1.0 is **_not_** assumed in Chrome, or the fiddle [above](https://github.com/w3c/webrtc-pc/issues/2535#issue-627794824) would have produced 3 same-size videos (it does not, instead showing the 2:1 ratio (large, medium, small).

The behavior is the same if I [comment out setParameters entirely & dump the params](https://jsfiddle.net/jib1/yvg81otc/46/) showing that the defaults are unharmed and invisible (not exposed in `getParameters`).

**Comment by Orphis** [comment]
A lot of applications are expecting to have scaling factors automatically applied as some sort of simulcast support was added before scaleResolutionDownBy was implemented. For backward compatibility, when no scaleResolutionDownBy is specified, then the scaling factors are applied.

If any layer has a value for scaleResolutionDownBy, even if it's 1, then the non conforming default behavior is not used.

It's a trade-off between backward compatibility for existing applications and moving forward with the new parameter. Since the parameter has been introduced a while ago now, it might be time to consider depreciating that old behavior.

**Comment by jan-ivar** [comment]
Thanks @Orphis I can confirm that setting `scaleResolutionDownBy: 1` on [any](https://jsfiddle.net/jib1/yvg81otc/52/) of the layers produces 3 same-size videos in Chrome.

Does Chrome have % usage of simulcast without specifying `scaleResolutionDownBy` on any layer?

**Comment by Orphis** [comment]
I don't think we have any counters on this. I can look into adding that when I'm back to work in a few weeks and possibly drafting a deprecation plan with warnings for our users to set the right values.

Though, there is also another non-conformant behavior in play at the moment in Chrome where we disable layers automatically if the source is considered too small. It can be triggered if you set a low enough capture resolution or if any adaptation happens from a source that was at first big enough. 

The general problem with this is that there is little to no good signal the application can have to know when adaptation is happening to replicate a similar behavior. I tried disabling that feature and ran into issues from HW encoders refusing to work with small odd sizes, which you can get easily with a scaling factor of 4 and a low capture resolution.
If you have explicit scaleResolutionDownBy parameters and adaptation happens, you may want to react and adjust the layer count and scaling factors. It is hard to do that now, but combining the 2 non conformant behaviors, you get some sensible behavior.

It is tricky.

**Comment by alvestrand** [comment]
A default of 1:2:4 (scaleResolutionDownBy= 2^(layer index starting from 0)) would make sense. I am not sure Chrome's old behavior was 1:2:4 or 4:2:1, but 1:2:4 seems to make much more sense.

**Comment by alvestrand** [comment]
Does the UA have license to alter "active" when it feels like it? In that case, disabling the smallest layers when they get too small is acceptable.

**Comment by Orphis** [comment]
4:2:1 would be preferred, or even 2:1 if only 2 layers as we want the smaller sizes to be first.

The problem with the deactivation of layers is that it will disable from the highest resolution and shift the scaling factors down. Also, it doesn't take into account I believe any scaleResolutionDownBy values, which should probably be the case when adapting the streams down.

**Comment by jan-ivar** [comment]
Note that 4 is smallest, 2 is medium, 1 is biggest, just to make sure we're on the same page. 😉

Regarding `active`, it looks like a JS control API to me, so it wouldn't work to have the UA set it as well, I think (UA fighting with JS).

**Wrinkle:** `active` is [also set by SDP](https://w3c.github.io/webrtc-pc/#set-description): _"Update the paused status as indicated by [MMUSIC-SIMULCAST] of each simulcast layer by setting the active member on the corresponding dictionaries in transceiver."_

**Comment by ibc** [comment]
Just in case, Chrome crashes when applying scaleResolutionDownBy:1 to two simulcast encodings and the shared browser tab goes to full screen:

https://bugs.chromium.org/p/webrtc/issues/detail?id=11649

**Comment by alvestrand** [comment]
Yes, the order of deactivation is defined in the simulcast SDP spec, so 4:2:1 is the sensible way (the largest layer will be dropped first).

**Comment by ibc** [comment]
> Yes, the order of deactivation is defined in the simulcast SDP spec, so 4:2:1 is the sensible way (the largest layer will be dropped first).

This assumes that multiple `sendEncodings` means "simulcast". Wrong assumption at implementation level. I may want to send two encodings, both with same resolution (`scaleResolutionDownBy: 1`) and different `maxBitrate`. Ideally I'd like to have per encoding `maxFrameRate` but such a useful setting did never officially land in the spec.

For instance, for screen sharing is much more important to keep the original resolution (even at lower frame rate in lowest simulcast layer) than keeping bitrate by lowering the resolution.

**Comment by jan-ivar** [comment]
Good point, but being practical, unless Chrome removes its useful defaults asap, it makes it hard for other browsers to implement anything else without being perceived as underperforming.

**Comment by Orphis** [comment]
`maxFramerate` is now in the webrtc-extensions repository. Once we finally ship the WebRTC spec, I guess we'll look into moving those to the main spec. It's shipped in Chrome.

Should you want a layer to have higher priority than another one, from my understanding of what we have now, you'd put it first in the `encodings` array to have it work the way you describe.

**Comment by ibc** [comment]
> `maxFramerate` is now in the webrtc-extensions repository. Once we finally ship the WebRTC spec, I guess we'll look into moving those to the main spec. It's shipped in Chrome.

Awesome, good to know. It works BTW, tested right now.
