### ISSUE TITLE
How to truncate simulcast layers?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2537]
In #2535 we seem to say that order of layers should be 4:2:1, but we have language saying...

> Let supportedEncodings be the maximum number of encodings that the implementation can support. If the length of sendEncodings is greater than supportedEncodings, truncate sendEncodings so that its length is supportedEncodings.

Are we truncating the end or the beginning of the list? It would make more sense to cut off the start if its 4:2:1, but it would make sense to cut off the end if the order was 1:2:4

**Comment by alvestrand** [comment]
the spec SHOULD be in https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-14 - not found yet.

**Comment by alvestrand** [comment]
https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-14#section-5.2

   The listed number of simulcast streams for a direction sets a limit
   to the number of supported simulcast streams in that direction.  The
   order of the listed simulcast streams in the "send" direction
   suggests a proposed order of preference, in decreasing order: the
   rid-id listed first is the most preferred and subsequent streams have
   progressively lower preference.  The order of the listed rid-id in
   the "recv" direction expresses which simulcast streams that are
   preferred, with the leftmost being most preferred.  This can be of
   importance if the number of actually sent simulcast streams have to
   be reduced for some reason.

**Comment by henbos** [comment]
Isn't the preference different depending on if this is during negotiation or if this is which layers should be active?

For example, if I successfully negotiate 4:2:1 I would want 1 to be dropped first if BW does not support it.
However, if I attempt to negotiate 4:2:1 but only two layers are supported, then truncation according to preference order results in 4:2. This means that I will never send the highest resolution layer because it doesn't exist.
Perhaps it would make sense to shift the layers by the number of layers removed, so that we end up with 2:1 instead. However, it may be up to the application if which resolution makes more sense to prioritize, and if a custom scaleResolutionDownBy then we shouldn't be doing any guessing.

Perhaps the solution should be to truncate according to spec and if an application's layers get truncated it is up to the application to adjust scaleResolutionDownBy if it wants HD.

**Comment by henbos** [comment]
Proposal:
- When doing addTransceiver, we default scaleResolutionDownBy according to the supported layers.
- When negotiating, if all layers are not supported, we truncate according to https://tools.ietf.org/html/draft-ietf-mmusic-sdp-simulcast-14#section-5.2 and cut off the end of the list, even if that results in no layer with scaleResolutionDownBy:1
