### ISSUE TITLE
Rollback throws InvalidStateError on mobile Safari

### ISSUE THREAD

**Issue by goekhancimsir** [w3c/webrtc-pc#2538]
## Versions affected

**mobile Safari, iOS 13.4.1**

**adapter.js (latest)**

## Description
Rollback of the peer connection state by calling `pc.setLocalDescription({type: "rollback"})` throws an error of type InvalidStateError.

## Steps to reproduce
- Open [jsfiddle](https://jsfiddle.net/8eap2t9r/1/) in mobile Safari
- Click / Press "Run"

## Expected results
`pc.setLocalDescription({type: "rollback"})` should not throw any error and rollback the peer connections signaling state to "stable"

## Actual results
Rollback of the peer connections state to "stable" fails since an error is thrown.

**Comment by dontcallmedom** [comment]
dear @goekhancimsir 

This repo is the one where the standard for the WebRTC JavaScript API is developed, and issues reported here should be about bugs in the specification, not in one of the implementations. Bugs on specific implementations should be reported in the relevant bug tracker (e.g. [WebKit Bugzilla](https://bugs.webkit.org/)).

This particular bug seems to have [already been reported there](https://bugs.webkit.org/show_bug.cgi?id=174656).

**Comment by goekhancimsir** [comment]
Thank you @dontcallmedom for clarification. Seemed to be the right place at first sight for me. But now it makes sense. And yes, that particular bug you've mentioned is exactly the one I was referring to here. Sad to see that it has been reported almost 3 years ago and obiously nothing happened.
