### ISSUE TITLE
What happens if you make values undefined in setParameters?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2556]
Example:
p = getParameters()
remove p.scaleResolutionDownBy
setParameters(p)

What's the desired outcome? Use old value, default to 1, throw an exception or re-run the "4:2:1" algorithm?

What about other parameters?

**Comment by henbos** [comment]
Proposal: throw an exception rather than re-run defaulting algorithms

**Comment by alvestrand** [comment]
I think deleting an attribute constitutes a change, so it's consistent to reject the modification.

**Comment by henbos** [comment]
Proposal: Simple PR to change the sentence to say that the scaleResolutionDownBy has a value and is bla bla

**Comment by jan-ivar** [comment]
I recommend rewording from:
_"Verify that each scaleResolutionDownBy value in encodings is greater than or equal to 1.0."_ to
_"Verify that each encoding has a scaleResolutionDownBy value greater than or equal to 1.0."_
