### ISSUE TITLE
Should stopping the bundle-owning transceiver kill datachannels?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#2562]
While implementing transceiver.stop, I found the following test:
```
  promise_test(async t => {
    const pc1 = new RTCPeerConnection({bundlePolicy: "max-bundle"});
    const pc2 = new RTCPeerConnection();
    t.add_cleanup(() => pc1.close());
    t.add_cleanup(() => pc2.close());
    const stream = await getNoiseStream({audio: true, video: true});
    t.add_cleanup(() => stopTracks(stream));
    const audio = stream.getAudioTracks()[0];
    const video = stream.getVideoTracks()[0];
    pc1.addTrack(audio, stream);
    pc1.addTrack(video, stream);
    const [dc1, dc2] = await createDataChannelPair(t, options, pc1, pc2);

    pc2.getTransceivers()[0].stop();
    const dc1Closed = new Promise(r => dc1.onclose = r);
    await exchangeOfferAnswer(pc1, pc2);
    await dc1Closed;
  }, `Stopping the bundle-tag when there is a ${mode} in the bundle ` +
     `should kill the DataChannel`);
```
Clearly the test-writer expected that when one stops a transceiver, the transport should close, and therefore the DC should close.

1) Is this written in the spec?
2) Is it the right thing to do?

The alternate reading is that the offer/answer with the stopped transceiver should move the transport data to another media section, and let that be the bundle leader. I don't know if we do that either.

**Comment by jan-ivar** [comment]
@docfaraday

**Comment by alvestrand** [comment]
I think the relevant part of BUNDLE is https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-54#section-7.5 - in particular "pick one bundled m-section as the offerer-tagged m-section".

**Comment by alvestrand** [comment]
And PC2 is in 7.3.3 -    If the criterium above is fulfilled the answerer can not reject the
   "m=" section in the answer.  The answerer can either reject the whole
   offer, reject each bundled "m=" section within the BUNDLE group, or
   keep the "m=" section within the BUNDLE group in the answer and later
   create an offer where the "m=" section is disabled within the BUNDLE
   group [Section 7.5.3].

So I think the point of "stopping" was that we wanted to end up in the last of the 3 listed alternatives; the offer/answer results in negotiationNeeded at PC2 after the offer/answer exchange.

**Comment by alvestrand** [comment]
Conclusion on editors chat:
- This test is wrong and should be deleted
- This area is complex enough that we need lots of tests for it!
