### ISSUE TITLE
ICE Candidate should have accessors for protocol-relevant items

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#257]
The ICECandidate object is:

interface RTCIceCandidate {
                attribute DOMString       candidate;
                attribute DOMString?      sdpMid;
                attribute unsigned short? sdpMLineIndex;
    serializer = {attribute};
};

The stats doc has:

dictionary RTCIceCandidateAttributes : RTCStats {
             DOMString                ipAddress;
             long                     portNumber;
             DOMString                transport;
             RTCStatsIceCandidateType candidateType;
             long                     priority;
             DOMString                addressSourceUrl;
};

Somewhat more easily accessible.

Suggestion: Add the same fields as accessors on RTCIceCandidate.

**Comment by martinthomson** [comment]
Easy problem: the serializer will then pick up the redundant information.

Bigger problem: now this has redundant information.  Do the extra attributes need to change when attributes are modified?  That implies custom setters, which blows.

I'd prefer to remove the RTCIceCandidate interface entirely and just use the dictionary.

**Comment by alvestrand** [comment]
That's the cute thing about having an interface rather than a dictionary.
If we list the attributes we want in the serialization in the "serializer" attribute, what we specify happens.

WRT modification: I'd prefer to have all the attributes readonly - I think not making the existing ones readonly in the first place was a mistake. Modifying them for local candidates can cause nothing but confusion, and I don't see an use case for having them on remote candidates.
I could be persuaded either way about whehter there is a variant of the constructor arguments that has the "decomposed" form rather than the SDP string.

**Comment by ekr** [comment]
Let's  just make the existing ones readonly too if we can. It's not like there's anything to
do by modifying them, right?

**Comment by stpeter** [comment]
+1 to readonly attributes. I agree with @alvestrand's reasoning here.

**Comment by stefhak** [comment]
@alvestrand In the latest version (has maybe not made it to an Ed's draft yet) there are many fields added to the candidate interface. Does that address this issue?

**Comment by alvestrand** [comment]
I'll take a look.

**Comment by alvestrand** [comment]
https://github.com/w3c/webrtc-stats/pull/32 tries to change webrtc-stats to conform to webrtc-pc. PTAL.

**Comment by alvestrand** [comment]
I think we're OK now.
