### ISSUE TITLE
Are sdpMid and candidate.sdpMLineIndex both allowed to be NULL? (spec and implementation differ)

### ISSUE THREAD

**Issue by Sean-Der** [w3c/webrtc-pc#2571]
https://w3c.github.io/webrtc-pc/#dom-peerconnection-addicecandidate states

```
If both candidate.sdpMid and candidate.sdpMLineIndex are null, then this applies to all media descriptions.
```

But I can't find any browsers that behave as the spec says.

**FireFox**
![Screen Shot 2020-09-01 at 11 42 55](https://user-images.githubusercontent.com/1302304/91892940-4d7c1780-ec48-11ea-933b-ba828f0c8a09.png)

**Chromium**
![Screen Shot 2020-09-01 at 11 42 38](https://user-images.githubusercontent.com/1302304/91892944-4e14ae00-ec48-11ea-8a30-37527b3ce958.png)

**Comment by alvestrand** [comment]
The language was added to permit adding a null candidate to indicate end-of-candidates for all M-sections.
It wasn't intended to permit adding a candidate to all m-sections.
The language may be clumsy.
(And handling of end-of-candidates isn't implemented according to spec in Chrome anyway.)

**Comment by Sean-Der** [comment]
@alvestrand that makes sense! Is there anyway it can be updated (can/should I make a PR?)

**Comment by alvestrand** [comment]
@Sean-Der see if #2577 works for you.

**Comment by Sean-Der** [comment]
Yea! Thanks for doing that @alvestrand. Hopefully this is actually a good suggestion, and not just me being clueless :)
