### ISSUE TITLE
Should transceiver.stop() cause transciever.receiver.track.onended to fire?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2581]
When we do pc.close() we explicitly make sure in several places not to fire events. But transceiver.stop() executes "stop sending and receiving", including:

> If disappear is false [which it is], execute the steps for receiver.[[ReceiverTrack]] to be ended. This fires an event.

Was this a mistake or on purpose? I get that it should fire in response to SRD, but transceiver.stop() is a synchronous API.

**Comment by alvestrand** [comment]
I think an argument made at the time was that one spec shouldn't prevent events from firing that were specified in another spec to be fired (but we don't care too much about when it is fired).

**Comment by henbos** [comment]
Works as intended. Closing issue.
