### ISSUE TITLE
Use VP9 when only receiving video

### ISSUE THREAD

**Issue by jim-king-2000** [w3c/webrtc-pc#2592]
If the caller can send video, it is viable to change the codec to vp9 and [here](https://webrtc.github.io/samples/src/content/peerconnection/change-codecs/) is the sample code. But how to change the codec to VP9 when only receiving video stream? No transceiver of the caller could be acquired since there is no video stream being added to peerConnection before the call.

**Comment by aboba** [comment]
Call `pc.addTransceiver()` with `init.direction = 'recvonly'`.  See: https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiverinit

**Comment by jim-king-2000** [comment]
The following is the code snippet of caller of adding `pc.addTransceiver()`. The browser(Chrome 86) complains with the error message:

```
OperationError: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.
```

```javascript
// code snippet of caller
export class RTCCaller {
  constructor(configuration) {
    const { config, stream, signaling, callback, metadata } = configuration;
    initSignaling(configuration);
    const peerConnection = createPeerConnection(config, callback, stream);
    const channel = peerConnection.createDataChannel('mouseEvent');
    channel.addEventListener('open', () => {
      console.log('webrtc data channel open.');
    })

    if (stream) {
      peerConnection.addEventListener(
        'negotiationneeded',
        () => createOffer(signaling, peerConnection, metadata));
    } else {
      peerConnection.addTransceiver('video', { direction: 'recvonly' });
      if (!RTCRtpSender.getCapabilities) return;

      const { codecs } = RTCRtpSender.getCapabilities('video');
      const [ transceiver ] = peerConnection.getTransceivers();

      const vp9_profile_2 = codecs.find(c => c.mimeType === 'video/VP9' && c.sdpFmtpLine === 'profile-id=2');
      if (vp9_profile_2) {
        console.log([vp9_profile_2]);
        transceiver.setCodecPreferences([ vp9_profile_2 ]);
        createOffer(signaling, peerConnection, metadata);
    }

      const vp9_codecs = codecs.filter(c => c.mimeType === 'video/VP9');
      const preferedCodecs = vp9_codecs.length > 0 ? vp9_codecs : codecs;
      console.log(preferedCodecs);
      transceiver.setCodecPreferences(preferedCodecs);
      createOffer(signaling, peerConnection, metadata);
    }
...
```

**Comment by fippo** [comment]
You're calling createOffer twice, no?

There is an interesting conceptual problem that is related:
  https://jsfiddle.net/fippo/36frscdg/1/
This calls setCodecPreferences with [vp9, vp8]
But since the remote SDP indicated VP8 first the answering peerconnection will send VP8.
Restricting setCodecPreferences to VP9 does work but how does one figure out the remote understands VP9 from the offer (without parsing SDP :-))?

**Comment by alvestrand** [comment]
sender.getParameters().codecs is supposed to return the list of codecs currently negotiated.

https://w3c.github.io/webrtc-pc/archives/20171002/webrtc.html#dom-rtcrtpsender-getparameters()

**Comment by jim-king-2000** [comment]
> You're calling createOffer twice, no?
Awkwardly, yes. I'll add a `return` statement and try again.

**Comment by jim-king-2000** [comment]
It works! Finally! Thank you, guys.

**Comment by jim-king-2000** [comment]
> This calls setCodecPreferences with [vp9, vp8]
> But since the remote SDP indicated VP8 first the answering peerconnection will send VP8.
> Restricting setCodecPreferences to VP9 does work but how does one figure out the remote understands VP9 from the offer (without parsing SDP :-))?

In my case, both the caller and the callee are wrote by me. So, I call setCodecPreferences with [vp9, vp8] on both side. I hope it could use VP9.

Actually, my real requirements is that, the advanced codec (`VP9, profile-id=2` here, since `av1` is not available yet) should always be selected whenever possible. But it seems that Chrome always takes VP8 as precedence. Firefox does the same until I change the flag `media.peerconnection.video.vp9_preferred` to true.

I insist that Chrome should take VP9 as precedence. There is no reason to stick to VP8 when the more advanced codec is available.

Lastly, WebRTC is such a fantastic technique that I predict it will be more and more popular and eventually dominate the internet video & audio field.

**Comment by jim-king-2000** [comment]
The code for 'take vp9 as precedence' so far is still a little bit tedious. I hope it could be done in one API call (or without any API call).

**Comment by jim-king-2000** [comment]
On the laptop of my office, chrome insists `VP8`. But it use `VP9` on the laptop in my home. It's weird. How can I debug it?
