### ISSUE TITLE
RTCPeerConnectionIceErrorEvent.errorText seems to correspond to RTCPeerConnectionIceErrorEventInit.statusText

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2603]
Having two names for the same thing is misleading.
How about migrating RTCPeerConnectionIceErrorEventInit.statusText to RTCPeerConnectionIceErrorEventInit.errorText?

**Comment by youennf** [comment]
Looking at WPT, I do not see any test written that uses statusText.

**Comment by alvestrand** [comment]
I think we should rename it - it's a mistake.

**Comment by alvestrand** [comment]
@dontcallmedom how do we deal with this given the state of the spec? (Chrome is as far as we know the only implementation of the mistake)

**Comment by jan-ivar** [comment]
To clarify: we should rename the init dictionary (`.statusText`) since they're rarely used in practice, to what's on the actual event (`.errorText`).

**Comment by dontcallmedom** [comment]
having looked into this, given that it's a substantive (i.e. implementations have to adapt) but really minor change (esp from an IPR perspective), the suggestion is to make the change in the spec and get implementors confirmations they're OK with the change should allow us to move to PR without another CR cycle.

**Comment by youennf** [comment]
> the suggestion is to make the change in the spec and get implementors confirmations they're OK with the change should allow us to move to PR without another CR cycle.

That works for me. onicecandidaterror was just added to WebKit and is using errorText everywhere.

**Comment by alvestrand** [comment]
I can say that Chrome will adapt.

**Comment by jan-ivar** [comment]
Works for me as well.

**Comment by alvestrand** [comment]
Change to Chrome is done in https://chromium-review.googlesource.com/c/chromium/src/+/2555078
