### ISSUE TITLE
fractionLost missing from MTI stats list

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-pc#2620]
I noticed that fractionLost is missing from the RTCRemoteInboundRtpStreamStats category. fractionLost reported in the RTCP Receiver Report is an important metric to exposes fraction of packets lost at the remote enduser to the local enduser. It that should be MTI.

If needed, I can make a PR.

**Comment by dontcallmedom** [comment]
Hi @vr000m, at this stage of the process, we cannot realistically add `fractionLost` as MTI to the spec before its publication as a Recommendation (expected later this month); but assuming it is implemented in several browsers, it could be part of a first batch of [candidate changes](https://www.w3.org/2020/Process-20200915/#candidate-changes) we bring to the spec post-Rec.

Any insights on the current implementation status of that stats?

**Comment by vr000m** [comment]
@henbos @jan-ivar should weigh in.

**Comment by henbos** [comment]
This didn't make PR because it hasn't been implemented.
