### ISSUE TITLE
replaceTrack() called on a sender object from getSenders() on RTCPeerConnection does not work at receiver's end.

### ISSUE THREAD

**Issue by anitoanto** [w3c/webrtc-pc#2628]
Issue is detailed in [this stackoverflow post.](https://stackoverflow.com/questions/63692531/webrtc-replacing-rtcpeerconnection-tracks-increases-streaming-delay-on-receive)
This works perfectly from the sender's end in a RTCPeerConnection connection. There is issue with the receiver's end even if the code on the both end is same.

**Comment by fippo** [comment]
I don't think this is a spec bug but that it also exists in Firefox now is concerning.
See https://bugs.chromium.org/p/chromium/issues/detail?id=1124292 for the chrome bug I filed a while ago. Maybe @henbos can investigate that one.

**Comment by henbos** [comment]
I suggest making some noise over at the browsers' issue trackers, perhaps https://bugs.chromium.org/p/chromium/issues/detail?id=1124292, closing this issue on the spec.
