### ISSUE TITLE
over riding default ice servers

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#263]
Some browsers are setting a default TURN and / or STUN servers. There has to be a clear way to override this so they are not used. 

var configuration =  { "iceServers": [] };
pc = new RTCPeerConnection(configuration);

is a fine way to that but the spec would need to be updated to make it clear that over wrote any default servers.  Thoughts on if this is the right way to do it?

**Comment by jan-ivar** [comment]
FWIW Mozilla's default STUN server [has been removed in Firefox 41](https://bugzil.la/1143827), but how you show it is indeed how one would override it today in FF39.

**Comment by jan-ivar** [comment]
I should clarify that: Firefox still offers users (and/or add-ons) the ability to set default TURN and STUN servers using the `about:config` setting `media.peerconnection.default_iceservers`, it's just that it'll default to `[]` starting with FF41 whereas before it defaulted to a mozilla server. So the question here is still relevant for us.

**Comment by juberti** [comment]
I think we should just forbid this.

**Comment by juberti** [comment]
(that is, browsers setting default STUN/TURN servers). It's not clear that this is good for applications.

**Comment by fluffy** [comment]
Related, we do need some way for browser used in an enterprise context to configure the enterprise TURN server and perhaps for the JS to discover that.

**Comment by martinthomson** [comment]
I agree that there is an advantage in having a proxy configuration option for browsers, but that doesn't need API support.

Discovery through the API doesn't seem that important. Do you have use cases where an application benefits from having this knowledge?

**Comment by juberti** [comment]
Agree with Martin. The enterprise TURN server doesn't need to be exposed to JS, just like HTTP proxies aren't exposed to JS today.

**Comment by juberti** [comment]
Suggest that we close this issue accordingly.

**Comment by fluffy** [comment]
So discussion at TPAC is we will add a new function where the JS app can get a list of ICE servers provisioned into the browser. The JS can then uses theses if it wants in creating the list of servers passed to the existing calls.

**Comment by fluffy** [comment]
LGTM

**Comment by alvestrand** [comment]
Solved by #365
