### ISSUE TITLE
How reuse transceiver

### ISSUE THREAD

**Issue by medved276** [w3c/webrtc-pc#2639]
I use peerConnection with multiple transceivers to got all people in chat.
For each man, I use 2 transceivers: video and audio.
But when someone leaving, and new man join, in pc.ontrack I got transceiver that was used by person, who already leaves.
I understand it as reusing transceiver.
In video-transceiver I see transceiver.receiver.track.readyState = 'live', but in audio-transceiver this status is 'ended'!
This status set at moment when someone leaves and not changing when new man 'reuse' it.
How do it correctly to avoid 'ended' state?

**Comment by henbos** [comment]
`transceiver.stop()` will irreversible stop the transceiver so that it cannot be reused.

`transceiver.direction = "inactive"` or `"recvonly"` (which is also what happens when you do pc.removeTrack(sender)) on the sender side is reversible.

You can reuse transceivers with...

```
transceiver.direction = "sendonly" or "sendrecv"
await transceiver.sender.replaceTrack(newTrack);
/* perform O/A */
```

**Comment by henbos** [comment]
But anyway, this github repo isn't a support forum, issues here are for keeping track of changes that need to be made on the spec: https://w3c.github.io/webrtc-pc/

Closing this

**Comment by henbos** [comment]
You can ask questions over at https://groups.google.com/g/discuss-webrtc

**Comment by henbos** [comment]
Also if you have an issue with audio but not video maybe you're changing ssrcs in the SDP and you're hitting issue https://crbug.com/1121454 ? which is a bug
