### ISSUE TITLE
[Question] How to recognize a new incomin track as one representing screensharing

### ISSUE THREAD

**Issue by mickel8** [w3c/webrtc-pc#2647]
Hi, I can't get one thing. There are couple of identifiers for tracks. We have `mid` `msid` for tracks but also `ssrc` `cname`  for RTP stream. How can I know that a new incoming track represents e.g. screensharing? I am asking about screensharing because in most cases it is being displayed in a different manner than other video tracks.

Should I use signaling server for this? Something like `Hey, on this track id I will send screensharing`.  In case of SFU this information has to be broadcasted to all conference participants. Is there any better way?

**Comment by fippo** [comment]
https://stackoverflow.com/questions/65408744/in-webrtc-how-do-i-label-a-local-mediastream-so-that-a-remote-peer-can-identify has some pretty good answers. You'll need some custom non-sdp signalling to associate your stream with a content type.
stream ids should be stable between local and remote, track ids are *not*

**Comment by mickel8** [comment]
> streams ids should be stable between local and remote, track ids are not

You mean that the track that is being sent by one peer to another can have different id on peer that sends it and on peer that receives it but id of stream that track belongs to is always the same on both peers?

**Comment by jan-ivar** [comment]
Correct. Use `stream.id` or transciever.mid` instead. See [this blog](https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/) for why.
