### ISSUE TITLE
Unclear how URLs are processed

### ISSUE THREAD

**Issue by annevk** [w3c/webrtc-pc#2660]
Chrome throws an exception for
```js
new RTCPeerConnection({ iceServers: [{ urls:["stun:turn.example.org/test"] }] });
```
whereas Firefox and Safari do not.

Where does https://w3c.github.io/webrtc-pc/#dom-peerconnection process these?

Some processing appears to happen in https://w3c.github.io/webrtc-pc/#set-the-configuration but that does not seem to be invoked from the constructor. (That also suggests using a URL parser that browsers do not have, which seems somewhat dubious.)

**Comment by annevk** [comment]
There's other issues that follow from this as well, such as whether
```js
new RTCPeerConnection({ iceServers: [{ urls:[] }] });
```
ought to throw. It does in Firefox, but not Chrome and Safari. Are there no web-platform-tests for all these cases?

**Comment by annevk** [comment]
Thanks! Not sure how I missed that. So I guess this comes down to:

1. How to parse and process those URLs given that browsers aim to implement https://url.spec.whatwg.org/, not RFC3986.
2. Tests.

**Comment by jan-ivar** [comment]
> Missing tests is a big no no of course. :slightly_smiling_face: 

The tests [already exist](https://wpt.fyi/results/webrtc/RTCConfiguration-iceServers.html):
* "new RTCPeerConnection(config) - with invalid stun url should throw SyntaxError"
* "new RTCPeerConnection(config) - with invalid turn url should throw SyntaxError"
* "new RTCPeerConnection(config) - with empty urls should throw SyntaxError"

**Comment by alvestrand** [comment]
the URL specified in https://datatracker.ietf.org/doc/html/rfc7065#section-3.1 explicitly does not allow a path component.

I don't know if the URL spec parse algorithm has an argument to it that says "fail if a path is attempted". Does it?

**Comment by alvestrand** [comment]
Note: the browsers do have a parser for TURN URL parsing; for Chrome, it is https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/pc/ice_server_parsing.cc;drc=65c9257f1777731d6d0669598f6fe6fe65fa61d3;l=149?q=webrtc::ParseIceServers&ss=chromium

**Comment by annevk** [comment]
@alvestrand you'll get a path given how these URLs look. (That's also the case with RFC3986 btw, see https://datatracker.ietf.org/doc/html/rfc3986#section-3.) I tried to spell out in https://github.com/w3c/webrtc-pc/pull/2694#discussion_r741251135 in some detail how the resulting URL record ought to be processed.

(And yeah, some browsers have per-scheme URL parsers. That goes against a generic URL syntax and is something we should avoid enshrining to the extent possible.)

**Comment by annevk** [comment]
I sketched an algorithm for this in https://bugs.webkit.org/show_bug.cgi?id=164508#c10. I would appreciate feedback from the WG.

**Comment by fippo** [comment]
FWIW.
STUN and TURN urls are special by the  IETF:
https://www.rfc-editor.org/rfc/rfc7064
https://www.rfc-editor.org/rfc/rfc7065

I am not sure that attempting to fit them into a generic URL scheme is something that should be done at W3C level .
Neither is it at implementation level where even "easy" things like throwing when a STUN url contains a "?transport" causes web compat issues such as https://github.com/twilio/twilio-video.js/issues/1934. Notably Firefox does not enforce this as [seen on stackoverflow](https://stackoverflow.com/questions/75822672/webrtc-peerconnection-is-not-establishing-in-chrome-and-edge).

**Comment by annevk** [comment]
What does "are special" mean? We need to define processing for them that is compatible with the URL Standard. We can certainly ignore query parameters as well. My processing model attempted to match the RFC syntax requirements, but we can also do something else, I don't really care, as long as we don't need a different URL parser.

**Comment by fippo** [comment]
It is not clear to me why webrtc-pc even tries to specify how to parse those urls.

These are passed to the "ICE agent" (however, JSEP is silent about this [here](https://datatracker.ietf.org/doc/html/rfc8829#section-4.1.18)).

@alvestrand:
> the browsers do have a parser for TURN URL parsing

Why? (and why is it not consistent with the underlying one...)

**Comment by annevk** [comment]
Well, that's consistent with how we treat URLs elsewhere in the platform. Parse them early to avoid surprises with IDNA, IPv4, etc. Also, the lower layer has to be consistent with that anyway so either way this needs to be defined.

**Comment by annevk** [comment]
Sure, but that shouldn't handle them differently from the browser or have a different idea as to what the host might be. And we do validate and normalize hosts upfront in the web platform and I don't think this has to be different here.

**Comment by jan-ivar** [comment]
> I sketched an algorithm for this in https://bugs.webkit.org/show_bug.cgi?id=164508#c10. I would appreciate feedback from the WG.

Thanks! I can do a new PR based on that. Except this line:

> * If inputURL's query or fragment is non-null, then return failure.

I think here we need to not throw on `?transport=udp` and `?transport=tcp` defined in https://www.rfc-editor.org/rfc/rfc7065#section-3.1. If we can reuse the query parser for that, that would be nice! Appreciate help on how to write that.

**Comment by jan-ivar** [comment]
> It is not clear to me why webrtc-pc even tries to specify how to parse those urls.
> 
> These are passed to the "ICE agent" (however, JSEP is silent about this [here](https://datatracker.ietf.org/doc/html/rfc8829#section-4.1.18)).

https://w3c.github.io/webrtc-pc/#set-pc-configuration does input validation of the configuration ahead of it to the ice agent, so JSEP doesn't need to.

> Neither is it at implementation level where even "easy" things like throwing when a STUN url contains a "?transport" causes web compat issues such as https://github.com/twilio/twilio-video.js/issues/1934. Notably Firefox does not enforce this as [seen on stackoverflow](https://stackoverflow.com/questions/75822672/webrtc-peerconnection-is-not-establishing-in-chrome-and-edge).

Thanks for finding that. I think this is a good argument for specifying url validation better, and we should probably fix Firefox here.
