### ISSUE TITLE
SDP exchange

### ISSUE THREAD

**Issue by Rados13** [w3c/webrtc-pc#2667]
Hi, I have a question regarding SDP offer/answer model for SFU - how the exchange process should look like? 
When client wants to join to some conference room it creates an initial SDP offer in which it puts tracks it is willing to send but it knows nothing about tracks from the other side so it cannot advertise ability to receive any tracks from the SFU - it doesn't know how many peers are already in the room. As SDP answer has to have exactly the same number of m-lines and their order has to be the same both in SDP offer and in SDP answer, SFU cannot add any tracks in SDP answer. In such a case, the first offer (from client to SFU) could be rejected and the server could send its own offer based on the client's offer. However, this approach is quite problematic when we want to use simulcast. According to JSEP specification the client during generating SDP answer for SDP offer with simulcast will ignore simulcast lines. 
I saw that for example Janus is using two separate RTCPPeerConnection, one for receiving and another for sending and I want to ask if this is a correct way? Who should send an initial SDP offer, can SDP offer be rejected and the other side can create a new one based on the initial one?

**Comment by alvestrand** [comment]
The best resource for getting advice is probably either stackoverflow or the mailing list discuss-webrtc@google.com.

I think your description is ~right - note that when an offer/answer completes, either end can initiate a new offer with more m-lines.
