### ISSUE TITLE
what error is thrown for an SDP without a a=fingerprint attribute

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#2672]
Writing a test about rejecting SDES I found that browsers differ in the type of error they reject the following with:
```
const sdp = `v=0
o=- 0 3 IN IP4 127.0.0.1
s=-
t=0 0
m=video 9 UDP/TLS/RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendonly
a=mid:video
a=rtpmap:100 VP8/90000
a=fmtp:100 max-fr=30;max-fs=3600
a=crypto:0 AES_CM_128_HMAC_SHA1_80 inline:2nra27hTUb9ilyn2rEkBEQN9WOFts26F/jvofasw
a=ice-ufrag:ETEn
a=ice-pwd:OtSK0WpNtpUjkY4+86js7Z/l
`;

promise_test(async t => {
  const pc = new RTCPeerConnection();
  t.add_cleanup(() => pc.close());

  
  return promise_rejects_dom(t, 'SomeError',
    pc.setRemoteDescription({type: 'offer', sdp}));
}, 'rejects a remote offer that only includes SDES and no DTLS');
```
Chrome rejects with `InvalidAccessError`
Firefox with `OperationError`
This suggests they run into different branches of step 4
https://w3c.github.io/webrtc-pc/#set-description
either
```
6. If the content of description is invalid, then reject p with a newly created
  InvalidAccessError and abort these steps.
7. For all other errors, reject p with a newly created OperationError.
```
Which one is correct?
Vote :laughing: for "InvalidAccessError", :eyes: for "OperationError"

**Comment by alvestrand** [comment]
I'll vote :laughing: for obvious reasons :-) - no DTLS? Just Say No!

**Comment by lgrahl** [comment]
The distinction between these two isn't really well defined, is it? What falls into the category _invalid_ and what falls into the category _other_? Clarifying this should resolve the question. :slightly_smiling_face:

**Comment by pthatcher** [comment]
I can't imagine a scenario where anyone cares one way or the other, but if they did, they would probably want the behavior to not change, so, all other things being equal, I'd go with "InvalidAccessError".

**Comment by fippo** [comment]
JSEP has "no a=crypto:" as a MUST level requirement so it seems legit to explicitly reject this instead of running into the more generic OperationError. I'll update the WPT.
