### ISSUE TITLE
Connection establishment should be "failed" even without candidates

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2698]
I tried to detect connection establishment failure by withholding all candidates, while still signaling end-of-candidates. The spec says I should see ["failed"](https://w3c.github.io/webrtc-pc/#dom-rtcicetransportstate-failed) fired: _"The RTCIceTransport has finished gathering, received an indication that there are no more remote candidates, finished checking all candidate pairs, and all pairs have either failed connectivity checks or have lost consent."_

There are zero candidate pairs in this case, which is a 🚩 perhaps, but still passes a pedantic (robot) test: "I have have finished all zero of them", or "there were zero successful pairs with consent", if you will. Zero shoes that fit.

 But none of the browsers appear to fire anything indicating failure. Things just stall. This seems wrong since the UA knows nothing more can happen, but fails to communicate this.

Here's a diff of a [fiddle](https://jsfiddle.net/jib1/uq6pk40r/)'s output in Chrome (which comes closest) compared to what I'd expect according to the spec:
```diff
  ice1.state = new
  ice1.gatheringState = new
  ice1.getSelectedCandidatePair() = null
+ ice1.state = gathering
  pc1.iceGatheringState = gathering
  ice2.state = new
  ice2.gatheringState = new
  ice2.getSelectedCandidatePair() = null
+ ice2.state = gathering
  pc2.iceGatheringState = gathering
  ice1.gatheringState = complete
  pc1.iceGatheringState = complete
+ ice1.state = failed
+ pc1.connectionState = failed
+ pc1.iceConnectionState = failed
  ice2.gatheringState = complete
  pc2.iceGatheringState = complete
+ ice2.state = failed
+ pc2.connectionState = failed
+ pc2.iceConnectionState = failed
```
Importantly, the connection state would have to go directly from "new" to "failed" here, bypassing ["checking"](https://w3c.github.io/webrtc-pc/#dom-rtcicetransportstate-checking) which says: _"The RTCIceTransport has received at least one remote candidate ..."_

But when I look at the [state transition diagram](https://w3c.github.io/webrtc-pc/#fig-non-normative-ice-transport-state-transition-diagram), and there's no arrow from "new" to "failed":

<img width="626" alt="image" src="https://user-images.githubusercontent.com/3136226/142705007-29cb8f6e-098a-4e0e-a811-8cc77f2f6a7d.png">

I think we should draw an arrow, and add some tests.

**Comment by jan-ivar** [comment]
This situation might also come into play for candidates that are [administratively prohibited](https://w3c.github.io/webrtc-pc/#dfn-administratively-prohibited) by one user agent but not another.

**Comment by alvestrand** [comment]
Did the fiddle send in a null AddIceCandidate to indicate no more remote candidates? In that case, it encounters a known bug (Chrome ignores end-of-candidates).

**Comment by jan-ivar** [comment]
Yes it sends in a null addCandidate. I gather you mean [crbug 935898](https://crbug.com/935898). Firefox has [bug 1535690](https://bugzil.la/1535690).

The spec seems clear about what should happen if at least one (useless) remote candidate was received before eoc:
```
ice1.state = new
ice1.state = gathering
ice1.state = checking
ice1.state = failed
```

I think the spec question is what should happen if zero remote candidates were received before eoc. Usefully, I hope:
```
ice1.state = new
ice1.state = gathering
ice1.state = failed
```
...but since [failed](https://w3c.github.io/webrtc-pc/#dom-rtcicetransportstate-failed) uses the phrase _"finished checking"_, and the lack of an arrow in the state diagram, it's not super clear I feel.

**Comment by docfaraday** [comment]
Hmm. Just because we have received no candidates from the other end does not mean we're sunk. If the other side is able to get an ICE check to land on us, that gives us a peer reflexive candidate to work with, and ICE can then succeed.

**Comment by lgrahl** [comment]
This might be different because `end-of-candidates` is explicit. If one sets `end-of-candidates` without **any** prior candidates, not even `host` with mDNS obfuscation, then it clearly is a case of "I don't want to talk to you", isn't it?

Whether that's actually useful is another question.

**Comment by jan-ivar** [comment]
> Hmm. Just because we have received no candidates from the other end does not mean we're sunk. If the other side is able to get an ICE check to land on us, that gives us a peer reflexive candidate to work with, and ICE can then succeed.

@docfaraday Interesting, that undermines my "UA knows nothing more can happen" rationale above for sure.

The spec nonetheless appears to say we're sunk unless this happens before end-of-candidates. But since nobody implements that, it's not too late to change of course. But to what? A timeout? What's the plausible use case?

> This might be different because `end-of-candidates` is explicit.

@lgrahl It's actually implicit, because the [spec mandates](https://w3c.github.io/webrtc-pc/#rtcicetransport) browsers emit an `icecandiate` event with a candidate whose member _"candidate is set to an empty string"_. Most JS signaling will blindly shuffle this Trojan marker to  [addIceCandidate](https://w3c.github.io/webrtc-pc/#dom-peerconnection-addicecandidate) where it indicates _"the end of remote candidates when called with an empty string for the candidate member"_. 

Firefox implements this. See the second-to-last line in this output from https://jsfiddle.net/jib1/agjcdm4k/
```js
candidate.candidate = "candidate:0 1 UDP 2122252543 192.168.1.XXX 64950 typ host"
candidate.candidate = "candidate:2 1 TCP 2105524479 192.168.1.XXX 9 typ host tcptype active"
candidate.candidate = "candidate:0 2 UDP 2122252542 192.168.1.XXX 63094 typ host"
candidate.candidate = "candidate:2 2 TCP 2105524478 192.168.1.XXX 9 typ host tcptype active"
candidate.candidate = "candidate:1 1 UDP 1686052863 XXX.XXX.XXX.XXX 64950 typ srflx raddr 192.168.1.XXX rport 64950"
candidate.candidate = "candidate:1 2 UDP 1686052862 XXX.XXX.XXX.XXX 63094 typ srflx raddr 192.168.1.XXX rport 63094"
candidate.candidate = ""
candidate = null
```
OTOH, it's explicit in the sense that JS has the ability to override this by delaying end-of-candidates. But I hope I've shown above that we must assume it is signaled by default.

**Comment by jan-ivar** [comment]
Can we reuse [expiration of consent](https://www.rfc-editor.org/rfc/rfc7675#section-5.1) as the timeout?

**Comment by lgrahl** [comment]
> Hmm. Just because we have received no candidates from the other end does not mean we're sunk. If the other side is able to get an ICE check to land on us, that gives us a peer reflexive candidate to work with, and ICE can then succeed.

I can't follow tbh. In which case would the UA not emit **any** candidates (not even mDNS ones), then signal `end-of-candidates` but still be able to send connectivity checks?

**Comment by docfaraday** [comment]
> > Hmm. Just because we have received no candidates from the other end does not mean we're sunk. If the other side is able to get an ICE check to land on us, that gives us a peer reflexive candidate to work with, and ICE can then succeed.
> 
> I can't follow tbh. In which case would the UA not emit **any** candidates (not even mDNS ones), then signal `end-of-candidates` but still be able to send connectivity checks?

If there are no STUN/TURN servers configured, and the service (or browser) is configured to hide host candidates, and the browser is behind a NAT, we will end up in this exact situation.

**Comment by juberti** [comment]
And this is a real-world situation, as explained in https://datatracker.ietf.org/doc/rfc8863/.

**Comment by juberti** [comment]
I would agree that if both browsers send zero candidates, failure should be declared.

**Comment by jan-ivar** [comment]
Based on that info, I'd suggest a PR to allow a new→failed path, then take it once end-of-candidates is reached after zero candidates in _both_ `addIceCandidate` and `onicecandidate`, or once the PAC timer expires (absent connection), whichever is sooner.

This should unblock https://github.com/w3c/webrtc-extensions/pull/81 by giving us a near-instant failure path in the common case where both peers are blocked by CSP (in contrast, if only one side is blocked, the other side could wait 39.5 seconds before failing).

Of course, a peer blocked by CSP doesn't inherently need to wait for remote signals before going to failed, since it knows it can never succeed, but that would reveal that CSP is in effect, so we might want to refrain from optimizing that.
