### ISSUE TITLE
addTransceiver does not check for missing rid properties

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2734]
Spec has validation steps for rid properties that are present in sendEncodings, but does not have any validation steps related to encodings without a rid property. We want to allow rid to be absent when there is only one encoding, but if there is more than one encoding we need to throw (TypeError probably) if any of those encodings are missing a rid.

**Comment by jan-ivar** [comment]
[RESOLUTION](https://www.w3.org/2022/09/12-webrtc-minutes.html#t09): +1 +1
