### ISSUE TITLE
webrtc-pc specifies using '~' in a=simulcast, but does not support RFC 7728 (RTP pause), which is a prerequisite 

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2735]
webrtc-pc has support for pausing simulcast encodings, which RFC 8853 says requires support for RFC 7728, at least in an answer:

"An answerer that receives an offer without RTP stream pause/resume
   capability MUST NOT mark any simulcast streams as initially paused in
   the answer."

However, RFC 7728 allows partial implementation; there are 8 different "profiles" (that are negotiated with a=rtcp-fb:ccm pause config=\<number\>):

https://datatracker.ietf.org/doc/html/rfc7728#section-9

webrtc-pc probably ought to specify the minimum level of support for RFC 7728.

**Comment by docfaraday** [comment]
We could maybe live with config=1 if we don't explicitly spell it out.

**Comment by aboba** [comment]
RFC 8853 does not mandate or even recommend support for RFC 7728, which has not been implemented in any browser.  Given the lack of implementation (and also the [IPR encumbrance](https://datatracker.ietf.org/ipr/search/?submit=draft&id=draft-ietf-mmusic-sdp-simulcast)), referencing RFC 7728 is not appropriate in WebRTC-PC.

**Comment by docfaraday** [comment]
> RFC 8853 does not mandate or even recommend support for RFC 7728, which has not been implemented in any browser. Given the lack of implementation (and also the [IPR encumbrance](https://datatracker.ietf.org/ipr/search/?submit=draft&id=draft-ietf-mmusic-sdp-simulcast)), referencing RFC 7728 in WebRTC-PC is problematic.

It does require it if you're going to use paused rids in SDP simulcast attributes, which we do require in webrtc-pc right now.

"If RTP stream pause/resume [RFC7728] is supported, any rid-id MAY be
   prefixed by a "~" character to indicate that the corresponding
   simulcast stream is paused already from the start of the RTP session.
   In this case, support for RTP stream pause/resume MUST also be
   included under the same "m=" line where "a=simulcast" is included."

"An answerer that receives an offer without RTP stream pause/resume
capability MUST NOT mark any simulcast streams as initially paused in
the answer."

"An RTP stream answerer capable of pause/resume that receives an offer
   with RTP stream pause/resume capability MAY mark any rid-ids that
   refer to pause/resume capable formats as initially paused in the
   answer."

That said, if we dropped the requirement for using paused rids in webrtc-pc, we won't need RFC 7728 support in order to maintain compliance with the base spec.

**Comment by aboba** [comment]
RTP stream pause/resume (RFC. 7728) is an IPR encumbered specification based on TMMBR/TMMBN.  The pause/resume functionality that has been implemented in WebRTC-compatible browsers uses the `active` dictionary member, not the RFC 7728 protocol functionality.

The means that the sentence starting with "If RTP stream pause/resume [RFC7728] is supported" doesn't apply, because it's not supported.

**Comment by docfaraday** [comment]
It would be totally fine to keep the `active` dictionary member, but we're not allowed to use '~' to signal it or negotiate it in SDP without having support for 7728, according to 8853.

**Comment by fippo** [comment]
Given that Chrome's support for this is a [trainwreck](https://bugs.chromium.org/p/webrtc/issues/detail?id=12044) and technically would cause setParameters to trigger the need for a new SDP I'd rather not do the `~` at all...

**Comment by docfaraday** [comment]
Looks like I am late to the party here:

https://bugs.chromium.org/p/webrtc/issues/detail?id=12044#c4

This details the problem with using `~` without 7728 support. Seems like removing `~` from webrtc-pc is a pretty viable way forward.

**Comment by docfaraday** [comment]
@aboba I've changed the bug description to better capture the problem, without suggesting a particular solution. Is this something we can clear the `wontfix` on?

**Comment by aboba** [comment]
There is still a very basic problem - `setParameters()` attributes such as `active` are *never* signaled in SDP.  The VLA RTP extension handles telling the other peer when simulcast streams are pasued. So the ~ should not be in the SDP.

**Comment by docfaraday** [comment]
Ok, so I guess we can remove the bit about setting `active` based on remote answers in 4.4.1.5; is there anyplace else where we refer to `~`?

**Comment by aboba** [comment]
Feedback from June 19, 2022 WEBRTC WG Virtual Interim: "Ready for PR"
