### ISSUE TITLE
webrtc-pc does not say to clear RTCRtpCodingParameters.rid when sRD rejects simulcast

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2736]
Spec says to truncate [[SendEncodings]] to size 1, but does not say anything about clearing the rid on that last encoding. Maybe this is harmless? Seems a bit weird to leave rid in there when nothing is using it, but maybe having a stable identifier is worth it?

Also, I guess I should point out that if scaleResolutionDownBy was auto-filled with powers of 2, truncating to size 1 leaves us with the thumbnail encoding, which also may be a little surprising.

**Comment by docfaraday** [comment]
The more I think about this, the more I think it is a mistake to omit the rid when there is a (single) rid in SDP negotiation. This is because a reoffer could potentially go from this:

a=simulcast:recv 1;2;3

to this

a=simulcast:recv 2

That is, the remote side has decided to switch from simulcast to unicast, but wishes to keep the _second_ encoding. It would be impossible to signal this appropriately to JS without keeping the rid property.

**Comment by jan-ivar** [comment]
Sounds like the way it already works is most desirable. Closing.

**Comment by jan-ivar** [comment]
Additionally, removing the rid would create a loophole out of the narrow-only logic.
