### ISSUE TITLE
Add API points for creating the ICE/DTLS transport and RtpSender without sending media

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#274]
In order to accelerate call startup, we want to be able to get ICE and DTLS established, and an RtpSender negotiated and ready to send, but not send any media through it.   Various possible ways for doing this have been thought of:

PeerConnection.createRtpSender({kind: "audio"});
PeerConnection.addTrack(null, {kind: "audio"});
PeerConnection.addTrack(new MediaStreamTrack("audio"));

The first two could be done in the WebRTC spec.  The third would have to be part of the getUserMedia spec.

**Comment by alvestrand** [comment]
This is useful for the case where we want to establish a PeerConnection with a pre-negotiated audio media section, but do not want to touch the audio device that will be used - typically when we have an incoming call; when the phone starts ringing, the microphone should be off, but when the "answer" button is pressed, the connection should be ready to start sending as soon as the microphone is online.

**Comment by stefhak** [comment]
Now we have pc.addTransceiver for this purpose. Closing.
