### ISSUE TITLE
Enum RTCIceCredentialType with only one value

### ISSUE THREAD

**Issue by Orphis** [w3c/webrtc-pc#2746]
Currently, the enum has a single possible value, which is the default one in `RTCIceServer`.
Do we have plans to bring back an `oauth` or alternate type or should we try to remove this?

As I can see on WPT, Firefox is the only browser that has implemented this.

See https://w3c.github.io/webrtc-pc/#rtcicecredentialtype-enum

**Comment by aboba** [comment]
AFAICT there isn’t much implementer interest in `oath`, and I’m not aware of a suggestion for an alternate type.  Would you like to discuss this at the next virtual interim (July 19)?

**Comment by Orphis** [comment]
I can certainly give a few words at the next interim "It doesn't do anything nor bring any value at the moment".

**Comment by aboba** [comment]
Feedback from June 19, 2022 WEBRTC WG Virtual Interim: "Ready for PR"
