### ISSUE TITLE
Control to turn on Client-to-Mixer Audio Level in offers

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#276]
Client-to-Mixer Audio Level is MTI for browsers but we need to decide when it is used. It is only used when negotiated in SDP but should the browser always include it in the offer or should we have a control surface for the JS to turn that on and off.

**Comment by juberti** [comment]
For 1.0, I think it should always be offered by browsers. The remote side, if it is not a browser, can reject it; if it is a browser, it will be harmlessly accepted.

**Comment by fluffy** [comment]
Justin's proposal works for me

**Comment by alvestrand** [comment]
This doesn't need to be in the API, then. JSEP needs to say that we negotiate it; mention that we use it should go into JSEP or Transport, I think.

**Comment by juberti** [comment]
I think this already is in the docs mentioned above.

**Comment by alvestrand** [comment]
RTP-usage-25 section 5.2.2: "MUST be implemented". Nothing about usage.

JSEP-11:ssrc-audio-level is shown in the examples, but looking for the word "audio" does not locate it.

audio-08: No mention of this header extension.

What did I miss?

**Comment by juberti** [comment]
JSEP, S 5.2.1 says this:

For each supported RTP header extension, an "a=extmap" line, as
      specified in [RFC5285], Section 5.  The list of header extensions
      that SHOULD/MUST be supported is specified in
      [I-D.ietf-rtcweb-rtp-usage], Section 5.2.  Any header extensions
      that require encryption MUST be specified as indicated in
      [RFC6904], Section 4.

**Comment by alvestrand** [comment]
Change to JSEP, not to this document. Closing.
