### ISSUE TITLE
Handling of simulcast attributes with multiple choices in a version seems to be underspecified

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2769]
ie; a=simulcast:recv 1,2,3;4,5,6;7,8,9

This is legal syntax, and its meaning is:

"I want you to send me three simulcast streams. For the first stream, you have a choice between rids 1, 2, and 3. For the second, you have a choice between 4, 5, and 6. For the third, you have a choice of 7, 8, and 9."

We obviously do not support this "multiple choices" semantics, so it is sensible to just pick the first choice whenever there are multiple, but I don't think we have written that down anywhere.

**Comment by alvestrand** [comment]
The RID specification has a huge amount of syntax we don't use!

"If there are comma separated alternatives, pick the first one. All other parameters are ignored." seems adequate.

This processing really belongs in JSEP (RFC 8829 section 5.10), but it seems to have been missed in that section.
