### ISSUE TITLE
Side-effects of mitigations for #179 in demo pages 

### ISSUE THREAD

**Issue by juberti** [w3c/webrtc-pc#277]
Consider a self-contained demo page, with no STUN/TURN server configured (like most of the ones out there). If we stop surfacing local candidates, this page will break.

One way around this is to surface a localhost candidate in the case where there are no STUN/TURN servers configured. However, there may be cases where real applications (as opposed to demo pages) have no STUN/TURN servers (e.g. an app running on a publicly accessible IP). We probably don't want to push up localhost in this case, and transmit/check a useless candidate.

Therefore we need some way of distinguishing between "no ICE config specified, use localhost if needed", and "no STUN/TURN servers specified, but don't use localhost". Ideally, this could happen with no changes to existing demo pages.

Suggestion:
- null for RTCIceServers (or null RTCConfiguration) --> use localhost
- any valid array for RTCIceServers, including [] --> don't use localhost

**Comment by juberti** [comment]
link for #179

**Comment by juberti** [comment]
Experimentation indicates that null for RTCIceServers is not accepted by either chrome or ff, but undefined is. So the proposal becomes that undefined for config or iceServers --> use localhost.

**Comment by juberti** [comment]
We're now suggesting that we always want to surface a host candidate (by default), so no need for a localhost candidate. We can close this. @stefhak @alvestrand

**Comment by alvestrand** [comment]
Closing per @juberti

**Comment by alvestrand** [comment]
Seems I didn't close it. Trying again.
