### ISSUE TITLE
How does the JS know if ICE is connected but DTLS isn't?

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#278]
The discussion around what happens when DTLS-SRTP fails and how we should signal that up to the JS isn't resolved.  Most people like a generic "PeerConnection.onerror" or "PeerConnection.onconnectionbusted".  I went to write a PR for PeerConnection.onerror, but found it very hard to define it in way that's useful for the JS.  

The more I thought about it, the more I realized that the real fundamental issue is that JS apps really want to know if the PeerConnection is "connected", "connecting", "disconnected, but could reconnect if you kicked it", or "completely busted".  The state we currently have, and which is currently used by JS apps is PeerConnection.iceconnectionstate.  But it's ICE-specific and the information the JS really wants is if the whole PeerConnection is working, including both ICE and DTLS.

This is particularly a problem is something goes wrong with DTLS, even if only temporarily.  For example, if ICE succeeds, but DTLS fails, how does the JS know that?  Or if DTLS takes 10 seconds longer to connect than ICE, how does the JS know that?  Or, in my original mailing list post, what if something goes wrong with DTLS-SRTP, how does the JS know that?  

I thought maybe PeerConnection.onerror could solve this, but as I went to write the PR, I found it didn't really fit as a solution.  

I'd like to see us address this f2f at the interim in September.

**Comment by alvestrand** [comment]
The other use case I've seen argued for "onerror" is stuff that doesn't map neatly to a state, such as when the credentials used towards the TURN server don't validate.
The effect on ICE connection state is difficult to figure out (it depends on whether any of the other candidates succeed), but it's definitely something that's bogus and that the browser can't fix.

**Comment by ekr** [comment]
Peter, I think we should address this. Generally, I think we want to have two orthogonal categories:

- Severity (OK, connecting, busted but recovering, busted, ...)
- Where the problem happened (ICE, DTLS, internal...)

**Comment by juberti** [comment]
I was going to make a specific PR for TURN errors, so that might help inform this discussion.

**Comment by alvestrand** [comment]
Fixed by #291
