### ISSUE TITLE
Handling of duplicate rids in sRD seems underspecified

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2780]
For example, a=simulcast:recv foo;foo

While this is pretty silly, I don't see anything in RFC 8853 that forbids it. I see two reasonable options:

1. Ignore any duplicates.
2. Fail the sRD, probably with an InvalidAccessError.

I think I prefer option 1. We might want to consider consistency with #2769

**Comment by jan-ivar** [comment]
> Ignore any duplicates.

Do you mean A) ignore the second foo, or B) ignore both foos?

**Comment by docfaraday** [comment]
I mean A.

**Comment by jan-ivar** [comment]
It seems simple enough to mandate that an answer ignore duplicates in an offer.
