### ISSUE TITLE
Couldn’t find “framesDropped“, for “RTCReceivedRtpStreamStats”,

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2790]
From https://github.com/w3c/webrtc-pc/actions/runs/3290497589/jobs/5423417580:

> Couldn’t find “framesDropped“, for “RTCReceivedRtpStreamStats”,  in this document or other cited documents: [dom], [fileapi], [hr-time], [html], [infra], [mediacapture-streams], [webidl], [webrtc-stats], [websockets], and [xhr].

**Comment by henbos** [comment]
I'll fix, framesDropped was moved in https://github.com/w3c/webrtc-stats/pull/702 so we should only reference the inbound-rtp, not remote-inbound-rtp
