### ISSUE TITLE
Handling of RTCRtpEncodingParameters.maxFramerate for audio encodings is probably underspecified

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2793]
Right now, we do not do anything if content sets a maxFramerate on an audio RTCRtpEncodingParameters. We probably either want to unset it (like we do for scaleResolutionDownBy), or throw some sort of error.

**Comment by jan-ivar** [comment]
It seems to me we should be consistent with `scaleResolutionDownBy` here, the other video-only parameters.

**Comment by docfaraday** [comment]
Seems reasonable to me.
