### ISSUE TITLE
is addTrack(track, stream, stream) allowed?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#2803]
This came up while looking at how Chrome parses msid:

https://jsfiddle.net/fippo/y2xso6Lq/1/
results in
* two identical a=msid lines being generated
* In Chrome ontrack being called with two MediaStreams which are not identical. In Firefox only one MediaStream is generated

My interpretation of https://www.rfc-editor.org/rfc/rfc8830.html#section-3.2.2 is that the Chrome is parsing this is not valid.

https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack
has a step saying
For each stream in streams, add stream.id to [[[AssociatedMediaStreamIds]]](https://w3c.github.io/webrtc-pc/#dfn-associatedmediastreamids) **if it's not already there**

which means all browsers fail to generate the correct SDP?

**Comment by fippo** [comment]
https://w3c.github.io/webrtc-pc/#dfn-create-an-rtcrtpsender
also says "if not already there". Having both seems not harmful but why not have this being dealt with when the sender is created?

**Comment by YasserElkersh** [comment]
getting hacked my ex wife sara elhegazy 4 averne street cranboure via her friends in egypt and based to bully me and survalence me even after relationship OVERRR

**Comment by fippo** [comment]
WPT are here:
https://wpt.fyi/results/webrtc/protocol/msid-parse.html?label=experimental&label=master&aligned&view=subtest
https://wpt.fyi/results/webrtc/protocol/msid-generate.html?label=experimental&label=master&aligned&view=subtest

**Comment by fippo** [comment]
The libWebRTC implementation was fixed in
  https://bugs.chromium.org/p/webrtc/issues/detail?id=14769 and
  https://bugs.chromium.org/p/webrtc/issues/detail?id=14745
so closing, no spec action required.
