### ISSUE TITLE
need more clarifying? about example in MDN WebRTC perfect negotiation pattern

### ISSUE THREAD

**Issue by Adamkaram** [w3c/webrtc-pc#2806]
here i belive they miss something unless i do   
what they recommended to do in new api to do that   

```

 let handleRenegotiation = async (description) => {
 try {
    if (description) {

 const offerCollision = description.type == "offer" &&
        (makingOffer || yourConn.signalingState != "stable");
     
        ignoreOffer = !polite && offerCollision;


 if (ignoreOffer) {
          return;
      }

 yourConn.setRemoteDescription(description)
 if (description.type == "offer") {
  await yourConn.setLocalDescription();
       
            wbsc.emit("SEND_EVENT_EMIT_CALL_AUDIO", {
              data: { type: "answer", answer: yourConn.localDescription, id: connectedUser },
            });
      }
    }


  }catch (e) {
    console.log(e);
  }
  }
```

i believe this could work if i'm impolite peer 

what if i'm polite peer 

how to do it should i split the conditions there to check who am i specifically    ? as in [here](https://github.com/w3c/webrtc-pc/issues/2167#issuecomment-499475161) or similar to

or how i can access 2 peersConnection without  clarify that

yourConn = new RTCPeerConnection(config);

yourConn2 = new RTCPeerConnection(config);

can i use 1 object in this case for both connection to work for both end points in generaly without   
yourConn and yourConn2?

or i missed the configuration of onnegotiationneeded ?

also is this how i implementing onnegotiationneeded  on both side   

```
 yourConn.onnegotiationneeded = async () => {
                  console.warn("yourConn.onnegotiationneeded");
                  try {
                    makingOffer = true;
                    await yourConn.setLocalDescription();
                    wbsc.emit("SEND_EVENT_EMIT_CALL_AUDIO", {
                      data: {
                        type: "negotiation",
                        description: yourConn.localDescription,
                        id: connectedUser,
                      },
                    });
                  } catch (e) {
                    console.log("renegotiationneded fail is ", e);
                  } finally {
                    makingOffer = false;
                  }
                };

yourConn2.onnegotiationneeded = async () => {
              console.warn("yourConn2.onnegotiationneeded");
              const offer = await yourConn2.createOffer();
              try { 
                makingOffer = true;
                await yourConn2.setLocalDescription(); 
                wbsc.emit("SEND_EVENT_EMIT_CALL_AUDIO", {
                  data: { type: "negotiation", description: yourConn2.localDescription, id: connectedUser },
                })
              }
              catch (e) {console.log("renegotiationneded fail is ",e) }
              finally { makingOffer = false }

            }
            
```

if so how in `handleRenegotiation ()`  
i accept description with `yourConn.setRemoteDescription(description)` that rollback my offer and then create answer and send it to  the remote peer  (does it here roll back it's offer and create answer but if based on what it did and creating answer based on any offer if the impolitePeer is returned silently ? 
 yourConn.setRemoteDescription(description) what description is that ? mine as a polite or his and in my case i'm imagining now that i who restart ice as a polite and impolite doesn't do anything for now ?
as i'm the one who sent the offer !! what i did here is wrong and should be fix?
 also onnegotiationneeded fires when or where?  i''m keep in mind that restartIce will keep trigger on negotiation until it success and the ice is restarted !
________________________________________
as i guees  as a polite peer do  
iceRestart() -> onnegotiationneeded (sending localdesscription ) to handleRenegotiation ()  
pass ignoreOffer guard in await yourConn.setLocalDescription(); does it rollback my existing offer or what should it do?  
after that what happend with onnegotiationneeded does i throw to next step or webrtc will re run onnegotiationneeded again ?  
and within it what happend to my sdp and icecandidate if that the logic i should stick with as they recomended  
who restart ice first and making the other peer restart his ice secondly

**Comment by jan-ivar** [comment]
Hi Adam, thanks for your interest in perfect negotiation! — It sounds like you have basic questions on how to write perfect negotiation code. Unfortunately, this issue tracker is only for discussing and requesting changes to the WebRTC specification itself, so I'm going to have to close this issue, as it is the wrong venue for code help questions.

For code help and general questions, I recommend reaching out on https://stackoverflow.com/search?q=%5Bwebrtc%5D+perfect (feel free to [ping me there](https://stackoverflow.com/users/918910/jib))

> can i use 1 object in this case for both connection to work for both end points in generaly without 
yourConn and yourConn2?

I'm not sure I follow your questions. It might help to familiarize yourself with regular negotiation first. Here's a simpler demo with regular (imperfect) negotiation https://jsfiddle.net/yxbLvjm6/ and my [blog](https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/) detailing its shortcomings (glare).

Note the canonical perfect negotiation needed example is https://www.w3.org/TR/webrtc/#perfect-negotiation-example, not MDN.

Lastly, here's a working jsfiddle demonstrating the perfect negotiation pattern: https://jsfiddle.net/jib1/Lhztcv89/

Hope that helps.

**Comment by Adamkaram** [comment]
i'm sorry for late respones but i appreciate your response but i figuer it out and your blog was a lot helpful i'm admire with your work 
thanx again
