### ISSUE TITLE
maxFramerate probably should not be allowed in addTransceiver/setParameters for audio senders

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#2815]
maxFramerate appears to be intended as a video-only parameter, so we probably ought to throw an error in the audio cases of addTransceiver and setParameters.

Formerly filed as WebRTC-Extensions https://github.com/w3c/webrtc-extensions/issues/107

**Comment by aboba** [comment]
Feedback from June 19, 2022 WEBRTC WG Virtual Interim: "Ready for PR"

**Comment by Orphis** [comment]
https://w3c.github.io/webrtc-pc/#dfn-addtransceiver-sendencodings-validation-steps:

> If kind is "audio", remove the [scaleResolutionDownBy](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-scaleresolutiondownby) and [maxFramerate](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-maxframerate) members from all encodings that [contain](https://infra.spec.whatwg.org/#map-exists) any of them.

**Comment by henbos** [comment]
This was already fixed at some point
