### ISSUE TITLE
Why is RTCIceCandidatePairStats.totalRoundTripTime mandatory to implement, but not responsesReceived?

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2819]
totalRoundTripTime is useless without responsesReceived. Does it really need to be in the mandatory-to-implement list?

**Comment by fippo** [comment]
Very much agree, I even had https://github.com/fippo/webrtc-pc/commit/efd99bd7101b5440c4cc0b1d1bb897d579cf44ad last monday but then realized this probably needs to be amended which makes it somewhat complicated.

**Comment by dontcallmedom** [comment]
if the complication comes from having it show up as a candidate addition to the Rec (as part of amendments management), I think it shouldn't bee too complicated and would be happy to deal with that part of the PR if that's indeed the direction we go with (I was reading @docfaraday as suggesting to instead remove `totalRoundTripTime`)

**Comment by fippo** [comment]
@dontcallmedom heh, I am just slightly scared ;-)

Lets put this on the agenda for the next meeting? Should be fairly quickly to get a decision on either
* make both totalRoundTripTime and responsesReceived MTI
* make neither totalRoundTripTime nor responsesReceived MTI

**Comment by fippo** [comment]
Added a slide for the eeting this week.

**Comment by jan-ivar** [comment]
Based on [bug 1542938](https://bugzilla.mozilla.org/show_bug.cgi?id=1542938#c10) I think Firefox would rather implement [smoothedRoundTripTime](https://w3c.github.io/webrtc-provisional-stats/#dom-rtcsctptransportstats-smoothedroundtriptime) than `totalRoundTripTime` and `responsesReceived`.

**Comment by alvestrand** [comment]
ICE RTT, RTP RTT and SCTP RTT are three different measurements.
When you change your selected candidate pair, the ICE RTT for the old pair and the new pair will be different numbers.

All that said - the users have already had to deal with the lack of these numbers because of Mozilla not implementing them, so I guess they can live without them.

**Comment by alvestrand** [comment]
(Also, the only reason why smoothedRoundTripTime is acceptable as a stat is that it is already a specified number in the SCTP specification. Letting the platform compute the RTT (or any "average" number) without exposing the information on how it's computed to the user is a Really Bad Thing, in my opinion, and specifically warned against  in the stats introductory chapters.)

**Comment by jan-ivar** [comment]
> Note that we don't ask for totalRoundTripTime on remote-inbound-rtp as MTI either.

Yes we seem to have discrepancies in both approach (preference/redundancy), naming, and MTI for RTT:

| stats type | naming | divisor naming | [MTI](https://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats) |
|--|--|--|--|
| "remote-inbound-rtp" | [roundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime) | | Yes |
|  | [totalRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime) | [roundTripTimeMeasurements](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements) | No |
| "remote-outbound-rtp" | [roundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime) | | No |
|  | [totalRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime) | [roundTripTimeMeasurements](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-roundtriptimemeasurements) | No |
| "candidate-pair" | [currentRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime) | | Yes |
| | [totalRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-totalroundtriptime) | [responsesReceived](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-responsesreceived) | Yes / No |
| "sctp-transport" | [smoothedRoundTripTime](https://w3c.github.io/webrtc-provisional-stats/#dom-rtcsctptransportstats-smoothedroundtriptime) | | No |

Is it too late to make naming consistent (x vs currentX vs smoothedX, and XMeasurements vs responsesReceived)?
Is it too late to make MTI consistent (x vs totalX/divisor vs both as MTI)?

That being said, [responsesReceived](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-responsesreceived) not being MTI seems like a bug, so a PR to match it to [totalRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-totalroundtriptime) seems editorial, which would close out this issue. OTOH, looking at the table above, mandating totalX/divisor looks inconsistent.

@docfaraday correct me if I'm wrong, but no answer to this issue would help Firefox though, unless we also remove MTI from "candidate-pair"'s [currentRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime), isn't that so?

> All that said - the users have already had to deal with the lack of these numbers because of Mozilla not implementing them, so I guess they can live without them.

Yes, I think Mozilla's preference would be to remove [currentRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime), [totalRoundTripTime](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime) and [smoothedRoundTripTime](https://w3c.github.io/webrtc-provisional-stats/#dom-rtcsctptransportstats-smoothedroundtriptime) from MTI for this reason. But I'm not sure we have consensus to do so.

**Comment by fippo** [comment]
This issue can be closed, it was fixed by #2832
