### ISSUE TITLE
Maybe setParameters/insertDtmf/replaceTrack should reject on [[Stopping]] as well as [[Stopped]]?

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2820]
Based on this wpt, it appears that all browsers set [[Stopped]] if the transceiver has never been used before (including the ones that support [[Stopping]]):

https://wpt.fyi/results/webrtc/RTCRtpSender-setParameters.html?label=experimental&label=master&aligned&view=subtest

Should we make the spec consistent with this?

**Comment by docfaraday** [comment]
On further inspection, it seems that it is not that other browsers set [[Stopped]] immediately, but rather that other browsers bail out of setParameters/replaceTrack/insertDtmf if [[Stopping]] or [[Stopped]] is set. That's an easier spec modification, and seems sensible anyway.

**Comment by jan-ivar** [comment]
These WPTs likely predate the spec adding [[Stopping]], and reflect that these methods serve not purpose after [stop()](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-stop) which _"will immediately cause the transceiver's sender to no longer send, and its receiver to no longer receive."_

Updating the methods to check [[Stopping]] here seems sensible, and gives web devs early feedback.

**Comment by jan-ivar** [comment]
A precedent is [here](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-direction):
```js
transceiver.stop();
transceiver.direction = "sendrecv"`; // throws InvalidStateError
```

**Comment by jan-ivar** [comment]
Turns out [WPT](https://github.com/web-platform-tests/wpt/blob/c29a0343e99749d4607cb7e6ac64a8de1538288e/webrtc/RTCRtpTransceiver.https.html#L1232) already checks for this, so only a spec-text update is needed to match.

**Comment by aboba** [comment]
@jan-ivar Should we put this on the interim agenda?
