### ISSUE TITLE
RTCSctpTransport.maxMessageSize is a floating point type

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#2822]
Surely we want an unsigned int of some type, right?

**Comment by lgrahl** [comment]
IIRC the reason for it was that it can be positive infinity, see 6.1.1.2.4.

**Comment by lgrahl** [comment]
Did this clear up the issue?

**Comment by docfaraday** [comment]
Seems like it would make more sense for this to be an unsigned integer type, and to set the value to UINT*_MAX instead of infinity, but I guess there's probably someone out there that is value testing for infinity that this will break.
