### ISSUE TITLE
If you close your data channel before first offer, does the "m=application" line still show up?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2839]
In Chromium, we recently fixed a bug that would leave closed RTCDataChannels in a "closing" state indefinitely if it was never negotiated.
When we fixed this bug, we found out that if there are no other DCs then the first offer will not have the "m=application" line until more DCs are created.

Now the question is: should we or should we not have an m=application line in this case?

**Comment by henbos** [comment]
For reference, if you stop() a transceiver before it is offered, then it is never added to the SDP. Not adding the m=application line would be consistent with that, but one difference between transceivers and data channels is that once you have an SCTP transport it is possible to create DC without follow-up negotiations and there is no way to ask for the m=application line without having a DC

**Comment by alvestrand** [comment]
If the m=application isn't present in the first offer/answer, adding a datachannel should trigger onnegotiationneeded, I think. So changing this to say "if all data channels are closed, don't add SCTP" would make such apps (which may include data-only apps that never renegotiate for any other reason) have to support renegotiation where they otherwise wouldn't have to.

**Comment by fippo** [comment]
> If the m=application isn't present in the first offer/answer, adding a datachannel should trigger onnegotiationneeded

But if you close it immediately you will end up with an offer with 0 m-lines? Which is valid but confusing. And then you get the issue about not seeing a need to renegotiate...

👍 for always adding the section which is how both Firefox and old Chrome versions behaved.

**Comment by lgrahl** [comment]
I'd ask what kind of use case there could possibly be where one creates a data channel but then decides against it. If there is none that would make any sense (which I suspect), then I'd suggest to keep it simple and carry on with negotiating data channels for the lifetime of the peer connection.

**Comment by henbos** [comment]
Agree, I think we should make Chrome have the m=application line. If you usedd DC for even a second you’ve shown interest and may want to create more later without renegotiation

**Comment by fippo** [comment]
> then I'd suggest to keep it simple and carry on with negotiating data channels for the lifetime of the peer connection.

👍 you can't remove m-lines anway. However, we might want assert with a test that if you close all datachannel and then create an offer this does not mark the corresponding m-line as rejected.

**Comment by henbos** [comment]
Sounds like we have agreement on what to do, and Chrome [has a fix](https://webrtc-review.googlesource.com/c/src/+/297860).

Question remains: any clarification needed on the spec side? JSEP:

> Lastly, if a data channel has been created, an "m=" section MUST be generated for data. The <media> field MUST be set to "application", and the <proto> field MUST be set to "UDP/DTLS/SCTP" [[RFC8841](https://www.rfc-editor.org/rfc/rfc8829.html#RFC8841)]. The <fmt> value MUST be set to "webrtc-datachannel" as specified in [[RFC8841](https://www.rfc-editor.org/rfc/rfc8829.html#RFC8841)], [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc8841#section-4.2.2).

"has been created" includes any past created ones, even if closed. So close this issue?
