### ISSUE TITLE
RTCRtpEncodingParameters.active flag and the ~ in the SDP

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2848]
If an encoding is inactive and you negotiate SDP we put a ~ in front of the RID to signify that it is inactive.

Now first of all, that seems rather useless, because the active flag can change at any moment without triggering re-negotiation, so I'm not sure what the other endpoint is supposed to do with that information when there is no guarantee that the ~ is up to date. So far, the ~ just seems pointless and misleading, but not causing any serious harm. But it gets worse.

It turns out that Chromium will look the existence or non-existence of the ~ in remote SDP and _update the encodings[i].active flag based on this information_.

This is madness! Case and point:
1. active=true; createOffer and send it to the other endpoint.
2. active=false due to user clicking mute button.
3. Other endpoint gets the SDP offer, sees active encodings and naturally creates an answer containing no ~.
4. We get the answer back, do SRD(answer) and boom. Now active=true, unmuting the stream.

I expect real world apps to also do replaceTrack(null) when muting to avoid this becoming a privacy issue, but I find the remote endpoint being able to control the active flag completely unacceptable.

Qs:
1. Is Chromium's use of this flag a bug or a feature?
2. Regardless if this is intentional or not, can we either remove ~ or clarify in the spec that one must NOT update the local active status based on SDP?

**Comment by fippo** [comment]
We already agreed this is bad in #2735

**Comment by henbos** [comment]
So, spec already says not to update the active flag? Then it is an implementation bug that we have not updated to match the spec?

**Comment by henbos** [comment]
https://crbug.com/webrtc/12044
