### ISSUE TITLE
nit: "audio stream” and “video stream" mentions

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#287]
Under [#dictionary-rtcofferoptions-members](http://w3c.github.io/webrtc-pc/#dictionary-rtcofferoptions-members) (x2):
> This option allows an application to indicate its preferences for the number of audio streams to receive when creating an offer.

s/stream/track/

There's also text under createOffer that seems old:
> “including descriptions of the local MediaStreams attached to this RTCPeerConnection,”, “such as addition or removal of streams"

s/stream/track/

There's also a mention of "RTP media stream" under DTMF. Not sure about that one.

**Comment by jan-ivar** [comment]
There's also this under `getStats`:
> “For a track to be a valid selector, it MUST be a member of a MediaStream that is sent or received by the RTCPeerConnection object on which the stats request was issued"

Which I think is technically accurate, but should probably be reworded since we don't normally think of MediaStreams being sent over peerConnection (rather their tracks).

**Comment by alvestrand** [comment]
Fixed by #323
