### ISSUE TITLE
Consider making RTCIceCandidatePair an interface

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2930]
Currently, [RTCIceCandidatePair](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidatepair) is a dictionary containing two interfaces:
```webidl
dictionary RTCIceCandidatePair {
  RTCIceCandidate local;
  RTCIceCandidate remote;
};
```
This seems like a mistake, allowing JS to compose invalid pairs and pass them as inputs.

Valid pairs are [formed](https://w3c.github.io/webrtc-extensions/#dfn-form) exclusively by the ICE Agent, a reality better expressed by a more restrictive contract:
```webidl
[Exposed=Window]
interface RTCIceCandidatePair {
  readonly attribute RTCIceCandidate local;
  readonly attribute RTCIceCandidate remote;
};
```
This would benefit web developers by enforcing an invariant, and spec writers by improved WebIDL type checking, simpler algorithms, and even simpler APIs in the future.

I believe this should be mostly backwards compatible since all APIs that take pairs expect valid ones. cc @sam-vi

I propose we make this change.

**Comment by jan-ivar** [comment]
@sam-vi thoughts on this? Should we discuss it at the next meeting perhaps?

**Comment by foolip** [comment]
This dictionary is also used as a method argument in webrtc-extensions. How would that be affected?

**Comment by jan-ivar** [comment]
I think the goal would be for [selectCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-selectcandidatepair) and [removeCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-removecandidatepair) to take the interface object (instead of a dictionary with two member interface objects).

The two methods throw `NotFoundError` on invalid pairs already. Pairs serve as handles to resources effectively.

I didn't find any WPT tests for these methods, so they're hopefully not implemented yet @sam-vi is that right?

**Comment by jan-ivar** [comment]
> Pairs serve as handles to resources effectively.

Not in an owning way, I should say. E.g. we could have used IDs for this instead,  but interface objects seem better.

**Comment by sam-vi** [comment]
> @sam-vi thoughts on this? Should we discuss it at the next meeting perhaps?

I agree with this proposal. I will work on some next steps.

> This seems like a mistake, allowing JS to compose invalid pairs and pass them as inputs.

I can't be certain about the motivation for the original definition as a dictionary. But I imagine that prior to [selectCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-selectcandidatepair) and [removeCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-removecandidatepair), when the only use of RTCIceCandidatePair was as a return value for [getSelectedCandidatePair](https://w3c.github.io/webrtc-pc/#dom-rtcicetransport-getselectedcandidatepair), a less restrictive definition was adequate and there was no possibility of misuse of a malformed candidate pair.

> I think the goal would be for [selectCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-selectcandidatepair) and [removeCandidatePair](https://w3c.github.io/webrtc-extensions/#dom-rtcicetransport-removecandidatepair) to take the interface object (instead of a dictionary with two member interface objects).

+1. With [[[CandidatePairs]]](https://w3c.github.io/webrtc-extensions/#dfn-candidatepairs), it is also possible to avoid pitfalls such as #2906.

> I didn't find any WPT tests for these methods, so they're hopefully not implemented yet @sam-vi is that right?

Correct. I recently got back from parental leave. I will continue work on the implementation and next steps for the spec.
