### ISSUE TITLE
Existing setCodecPreferences NOTE is wrong and should be deleted

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#2933]
The second NOTE under [setCodecPreferences](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setcodecpreferences) says:
> NOTE
> Due to a recommendation in [[SDP](https://w3c.github.io/webrtc-pc/#bib-sdp)], calls to [createAnswer](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-createanswer) SHOULD use only the common subset of the codec preferences and the codecs that appear in the offer. For example, if codec preferences are "C, B, A", but only codecs "A, B" were offered, the answer should only contain codecs "B, A". However, [[RFC8829](https://w3c.github.io/webrtc-pc/#bib-rfc8829)] ([section 5.3.1.](https://www.rfc-editor.org/rfc/rfc8829#section-5.3.1)) allows adding codecs that were not in the offer, so implementations can behave differently.

This does not advocate what we want for the unidirectional use case and I can't find a justification for it. I think it's probably based on a misunderstanding about the [difference between preferences and PT mappings](https://github.com/w3c/webrtc-pc/issues/2932).

Proposal: Delete this note.

**Comment by fippo** [comment]
This is fine, it refers to this text in 5.3.1?
> In either case, the media formats in the answer MUST include at least one format that is present in the offer but MAY include 
> formats that are locally supported but not present in the offer, as mentioned in [[RFC3264](https://www.rfc-
> editor.org/rfc/rfc8829.html#RFC3264)], [Section 6.1](https://www.rfc-editor.org/rfc/rfc3264#section-6.1)

**Comment by henbos** [comment]
JSEP says MAY add new formats, this note says SHOULD as in, should NOT add new formats but it could "so implementations can behave different", and [createAnswer](https://w3c.github.io/webrtc-pc/#dfn-final-steps-to-create-an-answer) says to use the preferences from `setCodecPreferences`, which has normative steps to use the preference, I take that as we MUST not follow this NOTE.

Am I confused or is the note confused?

**Comment by fippo** [comment]
It says the answer SHOULD be a subset of the offer which is a good expectation in general. But I agree, this seems redundant to JSEP and not helpful at this level.

**Comment by alvestrand** [comment]
I tried to make the rules for what codecs to include more explicit in https://github.com/w3c/webrtc-pc/pull/2935 - I don't know if I succeeded, but I didn't touch the note there.

**Comment by alvestrand** [comment]
Discussion on WG meeting Feb 20, 2024: Delete the note.

**Comment by fippo** [comment]
Will add a test along the lines of
````
A: sCP(vp8, vp9)
B: sCP(h264, vp9, vp8)
Answer from B says (vp9, vp8)
```
which should sufficiently cover the note that is going to be gone soon. 🤞 that the additional codecs used are available on all browsers.

**Comment by fippo** [comment]
![image](https://github.com/w3c/webrtc-pc/assets/289731/7a2edeeb-1ba1-47ee-a2b0-6ddd4315f5ec)
[As expected](https://wpt.fyi/results/webrtc/RTCRtpTransceiver-setCodecPreferences.html?label=master&label=experimental&aligned) 🎉
