### ISSUE TITLE
Guidance for extending objects vs extending Stats needed

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#295]
As discussed in the Seattle F2F:
At the moment, the RTPSender / Transport / ... tree is very duplicative of the stats tree.
We should have a paragraph or two of guidance on when we add things to the object tree, the stats tree or both.

**Comment by burnburn** [comment]
TPAC 2016:  There was general agreement to do this.  A request to create getStats() individually on each lower-level object should be created as a separate issue though.

**Comment by vr000m** [comment]
Some discussion around StatsGatherer.

@pthatcherg proposed:
StatsGatherer is aware of all objects.
And the application be able to subscribe to particular objects.

**Comment by vr000m** [comment]
Although, the question remains, how the application know which objects to subscribe to?

**Comment by dontcallmedom** [comment]
what's the plan to make progress on this? this is our oldest open issue at this time :)

**Comment by alvestrand** [comment]
The stats document has grown some architectural advice on stats objects' relationship to WebRTC objects. This seems to satisfy the request - please reopen on webrtc-stats if more is needed.
