### ISSUE TITLE
Write WPT to check RTCIceCandidatePair is now an interface

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2978]
From #2961:
> this is the kind of PR that updates the IDL fragments on which the idl harness relies: https://github.com/web-platform-tests/wpt/pull/46056
> 
> again, the WPT PR would only get generated some days after this WebRTC PR gets merged, so let's not block on it (but instead, let's file an issue when this PR gets merged)

The idl harness will hopefully test `window.RTCIceCandidatePair` exists, but we should expound on existing WPT webrtc tests to check that what's being returned by UAs are `instanceof` the right type. cc @sam-vi

**Comment by dontcallmedom** [comment]
I think https://github.com/web-platform-tests/wpt/pull/46655 accomplishes what we need (although without actual implementation, it's a bit hard to verify)
