### ISSUE TITLE
codec input to setParameters shouldn't be validated by preferred receive codecs

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#2989]
Step 4 of the [setParameters validation steps](https://w3c.github.io/webrtc-pc/#dfn-setparameters-validation-steps) says: _"If choosableCodecs is an empty list, set choosableCodecs to transceiver.[[[PreferredCodecs]]](https://w3c.github.io/webrtc-pc/#dfn-preferredcodecs)."_.

transceiver.[[[PreferredCodecs]]](https://w3c.github.io/webrtc-pc/#dfn-preferredcodecs) are _receive_ codecs set through [setCodecPreferences](https://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-setcodecpreferences) and shouldn't be used to validate send [codec](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters-codec).

**Comment by alvestrand** [comment]
Actually [[PreferredCodecs]] includes send codecs if set by [this section:](https://w3c.github.io/webrtc-pc/#ref-for-dfn-preferredcodecs-1)

Agree that this is unclear. Ideally, we should validate it over the set of codecs in the remote description, if set; if remote description is not set, it seems to me that it can only be validated over the set of implemented send codecs. (And we may want to include language saying that we enable any implemented send codec that is selected by setParameters).

**Comment by docfaraday** [comment]
> Actually [[PreferredCodecs]] includes send codecs if set by [this section:](https://w3c.github.io/webrtc-pc/#ref-for-dfn-preferredcodecs-1)
> 
> Agree that this is unclear. Ideally, we should validate it over the set of codecs in the remote description, if set; if remote description is not set, it seems to me that it can only be validated over the set of implemented send codecs. (And we may want to include language saying that we enable any implemented send codec that is selected by setParameters).

I don't see that section setting [[PreferredCodecs]]. It does seem to assume that [[PreferredCodecs]] might contain send codecs, but I do not see anywhere that will put send codecs in there. The language probably needs to be updated to reflect that this will only contain recv codecs.

**Comment by henbos** [comment]
Regarding whether preferences are send, receive or both, this was discussed at TPAC. We need to go through the spec and make sure everything is consistent with this decision, but I filed #3006 for this work in order to close all the overlapping codec issues such as this one
