### ISSUE TITLE
operations array prose is broken

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#299]
See https://github.com/w3c/webrtc-pc/pull/236#issuecomment-138804157 and please re-open that PR.

**Comment by jan-ivar** [comment]
Tl;dr; the current operations prose was written for `void`-returning methods with callback-args, and is completely broken for `promise`-returning methods.

**Comment by jan-ivar** [comment]
I was asked to clarify the problem here:

The existing text pushes objects on an array without returning anything to the caller, yet the caller is expecting a promise in return. That wont work.

Each method has a synchronous portion in its processing model, which needs to be executed synchronously, but isn't.

**Comment by jan-ivar** [comment]
In other words, the old text doesn't return any promises is the problem, or allow the synchronous parts of the operations to run, and they need to run synchronously, since they're the ones creating the promises.

**Comment by martinthomson** [comment]
I think that this is a fair summary.  If people are concerned about the use of promise-based language, which I can agree could be construed as being too complex, then I have no concern with adding prose to make the intent clearer.

If people are concerned about making the spec longer, that's a poor argument given its present length and lack of specificity (it needs to be longer).

Note: #236 was a precise description of the implementation of this in Firefox.  I'm sure that we can do better, but what we have isn't correct and should be fixed as per https://github.com/w3c/webrtc-pc/issues/299#issuecomment-142379985

**Comment by jan-ivar** [comment]
Note that https://github.com/w3c/webrtc-pc/issues/307 is the latest PR with earlier feedback from @adam-be addressed.

**Comment by adam-be** [comment]
The end of the title of #236 shouldn't have been "preserving existing behavior.". It should have been "to fix a lot of broken stuff". :) But let's fix it now.

**Comment by alvestrand** [comment]
Solved by #314
