### ISSUE TITLE
Align spec /w codec direction decision

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#3006]
How to deal with codecs and directionality was discussed at TPAC 2024:
- [Minutes](https://www.w3.org/2024/09/24-webrtc-minutes.html#4c6d)
- [Slides](https://docs.google.com/presentation/d/1dFntwgSd9MrLnd1Sf58eBHstkodUd30WSKGIaK5K2CM/edit#slide=id.g302dfc81162_4_26)
- [Recording](https://www.youtube.com/watch?v=aDKpOfGhbXk&t=44m39s)

There was a strong preference for Proposal A, i.e. to "keep it simple": sendonly transceivers can do all send codecs, recvonly transcievers can do all receive codecs, and sendrecv transceivers can only do codecs and profiles that you can BOTH send AND receive with. So if you want to do fancy unidirectional codecs or profiles you use multiple m= sections.

Let this issue track making sure the spec aligns with Proposal A and allow us to merge other codec related issues as fixed by this issue

**Comment by henbos** [comment]
The TPAC decision made it clear which direction to go on, but we never touched on what happens if the transceiver direction makes it such that none of your codec preferences are applicable anymore (e.g. transceiver is sendrecv but preferences only include recvonly codecs). This issue was pointed out in #2939

**Comment by henbos** [comment]
Adding "Discuss at next meeting" label to reflect we need to discuss error handling as per previous comment

**Comment by henbos** [comment]
The spec used to say a preference is a send codec OR receive codec, this was actually changed in an [amendment](https://github.com/w3c/webrtc-pc/pull/2926/files). So I wonder what our implementation does, if it still does both send and receive or if it was updated as per PR, do you know @fippo @alvestrand ?

**Comment by henbos** [comment]
Filing crbug to align with any spec changes happening here: https://crbug.com/370792782

**Comment by henbos** [comment]
To be discussed at October Virtual Interim ([slides](https://docs.google.com/presentation/d/1tfFiR2xqyEybbmnGUALqdWHpDx2W47YnlO65gI0HvBA/edit#slide=id.g2d9e0f01af2_0_11))

**Comment by fippo** [comment]
I do not think there needs to be more alignment, we are already doing what RFC 3550 says:
* [VP9](https://jsfiddle.net/fippo/msu6akj9/) (Firefox is not supporting more than the default profile=0)
* [H264](https://jsfiddle.net/fippo/msu6akj9/1/) (Firefox is only supporting CBP so not testable)

As usual we do need tests though.

**Comment by henbos** [comment]
We still need to align the spec with the decision such that setCodecPreferences does not throw if you set a sendonly codec (e.g. sendonly transceiver use case)

**Comment by fippo** [comment]
I thought we had been discussing this before and agreed no changes are needed?

https://www.rfc-editor.org/rfc/rfc9429#section-4.2.6
> It only affects which codecs the implementation indicates that it prefers to receive, via the offer or answer

**Comment by henbos** [comment]
We discussed this at TPAC and there was a preference for Proposal A, see [slides](https://docs.google.com/presentation/d/1dFntwgSd9MrLnd1Sf58eBHstkodUd30WSKGIaK5K2CM/edit#slide=id.g302dfc81162_4_26) and [recording](https://www.youtube.com/watch?v=aDKpOfGhbXk&t=44m39s). This issue is about doing what we decided to do.

**Comment by aboba** [comment]
@fippo IETF RTCWEB and AVTCORE WGs discussed RFC 9429 Section 4.2.6 - and the conclusion was that it was being interpretted by WEBRTC WG in a way that was inconsistent with RFC 3264. The decision at TPAC 2024 confirms that.

**Comment by henbos** [comment]
Yep, and to really spell this out, the following should work:
```
const sendOnlyTransceiver = pc1.addTransceiver('video', {direction: 'sendonly'});
sendOnlyTransceiver.setCodecPreferences([sendOnlyCodec]);

const recvOnlyTransceiver = pc1.addTransceiver('video', {direction: 'recvonly'});
recvOnlyTransceiver.setCodecPreferences([recvOnlyCodec]);

const sendRecvTransceiver = pc1.addTransceiver('video', {direction: 'sendrecv'});
sendRecvTransceiver.setCodecPreferences([sendRecvCodec]);

await pc1.setLocalDescription();
await pc2.setRemoteDescription(pc1.localDescription);
await pc2.setLocalDescription();  // Notice how pc2 does not need to set any preference of their own
await pc1.setRemoteDescription(pc2.localDescription);
```

But the following should NOT work:
```
const sendRecvTransceiver = pc1.addTransceiver('video', {direction: 'sendrecv'});
sendRecvTransceiver.setCodecPreferences([sendOnlyCodec, recvOnlyCodec]);
... negotiate ....
```

In the next meeting I will discuss how to handle errors (e.g. if the bad example should result in exceptions or if it should be interpreted as "no preference" after filtering). TBD

**Comment by fippo** [comment]
https://www.rfc-editor.org/rfc/rfc8829.html#section-4.2.6-1
remains clear on what setCodecPreferences is intended for: 
> It only affects which codecs the implementation indicates that it prefers to receive, via the offer or answer

I keep looking for a sendonly codec that is not covered by special codec rules like level-asymmetry-allowed which covered the weird ([and likely buggy](https://issues.chromium.org/issues/368478704)) H264 instance we found.

**Comment by henbos** [comment]
It does not affect it directly, but it affects it indirectly. This JSEP reading is what led to this regression in the first place, we decided to fix this.

**Comment by henbos** [comment]
Decision for the remaining error handling was Proposal A of [this slide](https://docs.google.com/presentation/d/1tfFiR2xqyEybbmnGUALqdWHpDx2W47YnlO65gI0HvBA/edit#slide=id.g30790f41697_14_26). This issue is now ready for PR.

**Comment by henbos** [comment]
https://www.w3.org/2024/10/15-webrtc-minutes.html

**Comment by fippo** [comment]
Let me try to clarify this after cappucino and water with hbos:
* In the *past* sCP required the codec to be in send **and** recv. This was a problem for receive-only codecs (which exist in the wild)
* sCP *currently* requires the codec to be in the recv capabilities
* *Future* sCP will allow the codec to be in send **or** recv capabilities. This *allows* a sender to change the *codec order* on a sendonly transceiver too (since the remote will match by default) which seems useful. Since we lack a sendonly codec this is not testable in WPT *currently*.
* Minor ergonomics issue: the input to sCP should probably come from `RTCRtpTransceiver.getCapabilities(kind)` for consistency with how sCP operates on the transceiver?

That part is 👍 

I do not see a need to change those rules based on direction so disagree with the second code block of [this comment](https://github.com/w3c/webrtc-pc/issues/3006#issuecomment-2390771213) but that might have been overtaken by events?

I **question** the conclusion to do "Proposal A" of the slide above. The Working Group seems to make decisions based on opinions while lacking tests which, like [this fiddle](https://jsfiddle.net/fippo/nvjx1r98/) (took five minutes to write... for the second time, I had shown this in February already) which shows that "deployed code" is doing proposal C. Transceivers can get stopped for a number of reasons, applications *must* check what was negotiated anyway.

**Comment by henbos** [comment]
You’re able to recognize the the past sendrecv limitation was a problem for your recvonly use case, but you can’t see that the exact same problem exists for the sendonly usecase? Your questioning of Proposal A has downsides (not fixing sendonly) without upside (what would thay be?). Your opposition also requires not caring what the RFCs referenced in the slides say. I stand by the WG decision.

**Comment by fippo** [comment]
How does Proposal C (m-line is rejected; this has a downside of having a stopped transceiver after SLD), consistent with ["incompatible choices result in a stopped transceiver"](https://jsfiddle.net/fippo/wxhtsyb4/1/) not fix sendonly? Transceivers get stopped, they are cheap.
