### ISSUE TITLE
WebRTC/WebCrypto mismatch: must-be-supported AlgorithmIdentifier value is rejected by WebCrypto normalization process

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-pc#310]
The WebRTC spec states that keygenAlgorithm of generateCertificate uses the WebCrypto AlgorithmIdentifier type and that it must produce a non-error result when normalized according to the WebCrypto algorithm normalization process. It also states that the following value must be supported by the user agent:
{ name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: 65537 }
http://w3c.github.io/webrtc-pc/archives/20150611/webrtc.html#widl-RTCPeerConnection-generateCertificate-Promise-RTCCertificate--AlgorithmIdentifier-keygenAlgorithm

The WebCrypto API on the other hand defines publicExponent as a BigInteger a.k.a. Uint8Array. Parsing the must-be-supported value produces an error result.
https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#RsaKeyGenParams-dictionary

This chromium issue shows the code and error message I got when I tried to normalize:
https://code.google.com/p/chromium/issues/detail?id=534416

**Comment by henbos** [comment]
(Does it make sense for publicExponent to be a BigInteger/Uint8Array when this value can be represented by 3 bytes and JavaScript numbers can support much much larger integer ranges than that? Would you ever want publicExponent's value to exceed the js Number's safe integer range?)

**Comment by martinthomson** [comment]
That is just a mistake in the spec.  The actual implementation uses the
ugly form required by WebCrypto.

E.g.,
https://dxr.mozilla.org/mozilla-central/source/dom/media/tests/mochitest/test_peerConnection_certificates.html?offset=400#137

As for the marvelous choice of form in WebCrypto, I would have been much
happier with a union (BufferSource or unsigned long), but usability didn't
seem to be a high priority for the designers of that API.
