### ISSUE TITLE
We should not reference the public API in algorithms

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#312]
A method in the public API may be overwritten by a script and is therefore not safe to call from internal algorithms.

**Comment by dontcallmedom** [comment]
Looking for "invoke " in the spec, it looks like the only places we do that at the moment is in the legacy→promise bridges; we also use static-looking names to refer to these methods, so fixing it would also partially fix that :)

**Comment by domenic** [comment]
This should be fixed before CR.

**Comment by alvestrand** [comment]
Fixed by #385
