### ISSUE TITLE
Don't use Interface.attribute to refer to properties of instances

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#316]
egreping through the document, I find the following culprits:
* RTCPeerConnection.createOffer
* RTCPeerConnection.setLocalDescription
* RTCPeerConnection.createAnswer
* RTCPeerConnection.setLocalDescription
* RTCPeerConnection.addIceCandiddate
* RTCPeerConnection.getStats
* RTCPeerConnection.close
* RTCPeerConnectionIceEvent.candidate
* RTCRtpEncodingParamters.priority
* RTCPeerConnection.generateCertificate
* Crypto.subtle
* RTCRtpSender.setParameters
* RTCOutboundRTPStreamStats.targetBitrate
* RTCRtpSender.track
* RTCRtpSender.transport
* RTCRtpSender.track
* RTCRtpSender.transport
* RTCRtpSender.rtcpTransport
* RTCRtpSender.transport
* RTCRtpSender.rtcpTransport
* RTCRtpSender.rtcpTransport
* RTCRtpSender.rtcpTransport
* RTCRtpSender.transport
* RTCRtpSender.mid
* RTCRtpSender.getCapabilities
* RTCRtpSender.setParameters
* RTCRtpSender.track
* RTCRtpSender.getParameters
* RTCRtpSender.track
* RTCRtpSender.setParameters
* RTCRtpReceiver.track
* RTCRtpReceiver.transport
* RTCRtpReceiver.track
* RTCRtpReceiver.transport
* RTCRtpReceiver.rtcpTransport
* RTCRtpReceiver.transport
* RTCRtpReceiver.rtcpTransport
* RTCRtpReceiver.rtcpTransport
* RTCRtpReceiver.rtcpTransport
* RTCRtpReceiver.transport
* RTCRtpReceiver.mid
* RTCRtpReceiver.getCapabilities
* RTCDtlsTransport.transport
* RTCTrackEvent.track
* RTCDataChannel.label
* RTCDataChannel.ordered
* RTCDataChannel.maxPacketLifeTime
* RTCDataChannel.maxRetransmits
* RTCDataChannel.protocol
* RTCDataChannel.negotiated
* RTCDataChannel.id
* RTCDataChannel.priority
* RTCDataChannel.readyState
* RTCStats.id

(ignoring the ones in the changelog)

**Comment by martinthomson** [comment]
`RTCPeerConnection.generateCertificate` and `Crypto.subtle` are both static, so maybe that's OK.

**Comment by domenic** [comment]
Looking at the call for review before CR, this jumped out at me as well. This should be fixed before CR.
