### ISSUE TITLE
Section 7.1 typo

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#320]
Currently in Section 7.1 (see:  http://w3c.github.io/webrtc-pc/#rtcrtpsender-interface-extensions) it says: 

7.1 RTCRtpSender Interface Extensions

The Peer-to-peer DTMF API extends the RTCRtpSender interface as described below.

partial interface RTCPeerConnection {
    readonly    attribute RTCDTMFSender? dtmf;
};

this should be: 

partial interface RTCRtpSender  {
    readonly    attribute RTCDTMFSender? dtmf;
};

**Comment by elagerway** [comment]
Closing, PR https://github.com/w3c/webrtc-pc/pull/347 was merged
