### ISSUE TITLE
Section 8.5.1 typo

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#321]
In Section 8.5.1 it says: 

enum RTCStatsType {
    "inbound-rtp",
    "outbound-rtp"
};

This should be: 

enum RTCStatsType {
    "inboundrtp",
    "outboundrtp"
};

**Comment by aboba** [comment]
More typos: 

The timestamp, of type DOMHiResTimeStamp [HIGHRES-TIME], associated with this object. The time is relative to the UNIX epoch (Jan 1, 1970, UTC).

This should be DOMHighResTimestamp.   It is also mispelled in Section 8.5.

**Comment by martinthomson** [comment]
For typos, PR > issue.

**Comment by aboba** [comment]
Yet another typo:  outbund -> outbound

**Comment by elagerway** [comment]
Closing, PR #347 was merged
