### ISSUE TITLE
"none" as a RTCIceCredentialType

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#329]
The spec has an [in-line issue](http://w3c.github.io/webrtc-pc/webrtc.html#idl-def-RTCIceServer) asking whether we should:
> have a "none" type, for cases where no authentication is needed? (e.g. STUN)

(this was added by @juberti in 466ab4be67757a9f4187bf01478f4ae5c64d6d5a as far as I can tell)

**Comment by aboba** [comment]
Should we remove the issue?

**Comment by dontcallmedom** [comment]
I think we don't need `none` since you can simply not include `credential` and `credentialType` when it's not needed; but maybe worth checking with @juberti since he created that in-line issue.

**Comment by aboba** [comment]
Right.  Example 1 shows an RTCIceServer entry for STUN with no username, credential or credentialType attributes.  The text also makes it clear that username/credentials/credentialType is for use with TURN servers: 

credential of type DOMString
If this RTCIceServer object represents a TURN server, then this attribute specifies the credential to use with that TURN server.

credentialType of type RTCIceCredentialType, defaulting to "password"
If this RTCIceServer object represents a TURN server, then this attribute specifies how credential should be used when that TURN server requests authorization.

username of type DOMString
If this RTCIceServer object represents a TURN server, then this attribute specifies the username to use with that TURN server.

**Comment by dontcallmedom** [comment]
This was closed when #409 was merged
