### ISSUE TITLE
Get rid of RTCAnswerOptions?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#330]
`RTCAnswerOptions` is an empty dictionary that extends `RTCOfferAnswerOptions`; should we get rid of `RTCAnswerOptions` and directly reference `RTCOfferAnswerOptions` in `createAnswer`?

Given the direction of WebRTC NV, it doesn't seem we're likely to need to extend the options that ca be used with `createAnswer`, so it's not clear that there is any value in keeping that separate dictionary.

**Comment by stefhak** [comment]
An mail list discussion was initiated at https://lists.w3.org/Archives/Public/public-webrtc/2016Jan/0065.html , but no responses so far. Closing this issue as there seems to be no interest to make this change.
