### ISSUE TITLE
Creating an ICE agent is not defined

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#331]
Step 3 of the [`RTCPeerConnection` constructor](http://localhost/~dom/webrtc-pc/webrtc.html#dom-peerconnection) says "create an ICE agent" as defined in [ICE], but the ICE RFC doesn't define what creating an ICE agent requires.

**Comment by adam-be** [comment]
I think we can just refer to the ICE Agent (the ICE protocol implementation) and we don't need to "create" it. RFC5245 [1] has two ICE Agents in its terminology section: the Contolling and the Controlled Agents.

[1] https://tools.ietf.org/html/rfc5245

**Comment by adam-be** [comment]
#510 tries to address this (and does some general gardening around the ICE Agent text).
