### ISSUE TITLE
Timing of ICE gathering 

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#332]
The RTCPeerConnection constructor step 3 states:
> The ICE Agent will proceed with gathering as soon as the ICE transports setting is not set to none

It seems to mix the condition of starting ICE gathering (ICE transport settings not set to none) with its timing.

Later down, the spec says that during the lifetime of the RTCPeerConnection object, when "ICE events occur" (which seems ill-defined):
> If the RTCPeerConnection ice gathering state is new and the ICE transports setting is not set to none, the user agent MUST queue a task to start gathering ICE addresses and set the ice gathering state to gathering.

So I'm confused as to when the ICE gathering actually starts: is it upon constructing the RTCPeerConnection instance or not?

**Comment by dontcallmedom** [comment]
Also, the spec says:
> At this point the ICE Agent does not know how many ICE components it needs (and hence the number of candidates to gather), but it can make a reasonable assumption such as 2

I think that now that we have iceCandidatePoolSize in RTCConfiguration, this is probably moot; more specifically, if iceCandidatePoolSize has not been set or has been set to 0, no gathering should done.

**Comment by elagerway** [comment]
@adam-be Are you still able to propose something for this? https://docs.google.com/presentation/d/1R7lQeo4LNGu0KKW9GLdkwJ5x8FUmR4qrnhfPFZO3WS8/edit#slide=id.g828c698ba_0_15

**Comment by adam-be** [comment]
@elagerway, Yes

**Comment by adam-be** [comment]
Most of the things brought up here was addressed by #510. I've also pushed an addition commit to deal with the last point (about using candidate pool size).

**Comment by elagerway** [comment]
@adam-be Closing this as the related PR has been merged.
