### ISSUE TITLE
No definition of "applying an ICE candidate"

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#336]
The description of `addIceCandidate` refers to "successfully apply[ing]" an ICE candidate, but I couldn't find a definition of what was meant neither in this spec, nor in JSEP.

I guess the first part of the method description is probably the closest thing to what is meant: "add[ing the candidate] to the remote description", and "[sending] connectivity checks", but if that's indeed what is meant, it should be made explicit, and it should also probably be turned into an algorithmic form, among other things to distinguish what is synchronous and what isn't.

**Comment by adam-be** [comment]
This needs some work indeed. I'll propose something (tomorrow).

**Comment by adam-be** [comment]
PR #507

**Comment by alvestrand** [comment]
#507 solved most of this. There may need to be a JSEP reference, @adam-be will raise an issue.
