### ISSUE TITLE
`RTCPriorityType` not aligned with names in rtcweb-transports

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#340]
`RTCPriorityType` uses very-low, low, medium, high, while  [rtcweb-transports](https://tools.ietf.org/html/draft-ietf-rtcweb-transports-09#section-4) uses "below normal", "normal",  "high" or "very high".

There is a priori no need to re-use the same names, but if we don't, we should at least make the mapping explicit.

**Comment by alvestrand** [comment]
See https://github.com/rtcweb-wg/rtcweb-transport/issues/8 - rtcweb-transport needs to align itself.

**Comment by dontcallmedom** [comment]
Since this was determined to be a bug in rtcweb-transport, I believe this issue can be closed.

**Comment by alvestrand** [comment]
Closing, IETF issue.
