### ISSUE TITLE
[FIPS-180-3] has been replaced by  [FIPS-180-4]

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#341]
When following the reference to [FIPS-180-3], I'm told this is an outdated reference and that  [FIPS-180-4](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf) should be used.

As a boeotian in crypto standards, I prefer to get confirmation that updating the ref is the right thing to; if it is, I'm happy to provide a PR.

**Comment by alvestrand** [comment]
ObReference: https://en.wiktionary.org/wiki/Boeotian
