### ISSUE TITLE
RTCRtpSender section doesn't include the definition for RTCRtpSender

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#348]
This is likely a consequence of using respec, but you will find `RTCRtpSender` in Section 5.2.10, entitled "Dictionary RTCRtpHeaderExtensionCapability Members"

cc @pthatcherg

**Comment by dontcallmedom** [comment]
I believe this was fixed by 7a269b2bda2aac021f659b5d13f42841b10c9ba

**Comment by aboba** [comment]
It does seem to be fixed in the latest Editor's draft: 
http://w3c.github.io/webrtc-pc/#rtcrtpsender-interface
