### ISSUE TITLE
addIceCandidate shall throw a TypeError exception if the candidate parameter is malformed

### ISSUE THREAD

**Issue by zqzhang** [w3c/webrtc-pc#35]
In 4.3.2.3 [1], there is a paragraph:

> If the candidate parameter is malformed, throw a SyntaxError exception and abort these steps.

`malformed` shall mean 'not conforming to a standard type'. For example, if the candidate parameter is an empty string `""`, `addIceCandidate` shall throw a `TypeError` exception rather than a `SyntaxError` per the WebIDL dictionary definition [2]. At least the spec [1] is not clear on this aspect.

[1] http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-addIceCandidate-void-RTCIceCandidate-candidate-VoidFunction-successCallback-RTCPeerConnectionErrorCallback-failureCallback
[2] http://heycam.github.io/webidl/#es-dictionary

**Comment by alvestrand** [comment]
Handling should be consistent with what happens when invalid SDP is passed to Set*Description.

**Comment by jan-ivar** [comment]
`addIceCandidate("")` will throw `TypeError` (on implementations relying on a webidl-compiler for sure). We don't have to spec that since it's implicit in WebIDL. I think the prose here is about candidate validity in ways unique to candidates and undetectable by WebIDL binding code.

About the choice of `SyntaxError`, my understanding is that this error is reserved for JS parsing errors, i.e. when your JS is not JS. Yet the webrtc spec returns it in a couple of places. Should we revisit that? Thoughts, @annevk or @bzbarsky?

**Comment by bzbarsky** [comment]
That was my understanding of SyntaxError too, fwiw.

**Comment by annevk** [comment]
Yes you should revisit that. `TypeError` is usually a safe choice.

**Comment by adam-be** [comment]
I think we can all agree on what @jan-ivar is saying about the WebIDL type checking. Regarding SyntaxError, I think it's a pretty good match from it's definition [1].

"SyntaxError" 	The string did not match the expected pattern.

We expect the candidate string to follow a certain pattern. SyntaxError is for example used by the WebSocket constructor if the argument url is malformed.

[1] https://heycam.github.io/webidl/#syntaxerror

**Comment by bzbarsky** [comment]
That's a link to DOMException with .name == "SyntaxError".  That's not the same thing as a SyntaxError.  Yes, this is unfortunate...  WebSocket throws the DOMException, fwiw.

And it looks like if you make it clear that your definition of "throw" is http://heycam.github.io/webidl/#dfn-throw then in fact "throw a SyntaxError" means "throw a DOMException with .name == SyntaxError".  http://heycam.github.io/webidl/#dfn-simple-exception seemsto be the normative text requiring that, though it really could use being clearer.

So ok, "throw a SyntaxError" is perfectly fine, as long as everyone is on the same page about what it actually means in terms of implementation.  ;)

**Comment by adam-be** [comment]
Yes, it seems that we're not defining what we mean by "throw" anywhere. Can we resolve this issue by simply doing that?

**Comment by annevk** [comment]
Yeah, seems fine.

**Comment by alvestrand** [comment]
OBE - this step in the algorithm has been removed.
