### ISSUE TITLE
Set a priori codec preferences

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#359]
Agreed at TPAC that an ordered list of codecs can be set on `RTCRtpTransceiver`.  This only determines the ordering of the codecs on the corresponding media section generated by `createOffer` or `createAnswer`.  Respecting these is down to the normal SDP rules for codec preferences.

Note that the values that are set should persist.  However, we won't provide an accessor for this.

@juberti notes that we might also want to push certain codecs to the bottom: CN, telephone-event, and all FEC payload types.  That might be best to avoid accidental interoperability issues.

**Comment by aboba** [comment]
One thing that needs to be nailed down is whether only one codec in the codec list can be sending at a time (e.g. whether encodings[i].active can be set to true for only one value of i).  

We've already seen differing interpretations of this within the ORTC API.

**Comment by martinthomson** [comment]
@aboba, I think that's a separable issue.

**Comment by elagerway** [comment]
Closing this as PR #361 was merged.
