### ISSUE TITLE
m-line match up doesn't work with RtpSender.mid or RtpTransceiver.mid

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#363]
Today at TPAC, many people asked that this end up with one m-line:

pc.addTrack(videoTrack);
pc.setRemoteDescription(offer);  // Offers to receive an m-line
pc.createAnswer();

There is a problem with that:  the RtpSender returned by pc.addTrack has a .mid value.  But the m-line in .setRemoteDescription will have a different MID, which means the m-lines can't match up.  To make them match up, we either need:

1.  RtpSender.mid maybe be changed upon setRemoteDescription.
2.  RtpSender.mid will be null until the offer (either setLocalDescription or setRemoteDescription) is called.

I don't think either one works very well.

**Comment by pthatcherg** [comment]
We just thought of a third option:

3. addTrack doesn't return an RtpSender.


Then addTrack could still add a transceiver, but the call to setRemoteDescription could replace the transceiver with a new one.   Effectively, addTrack doesn't know which RtpSender it will ultimately be sent on because it doesn't know which RtpTransceiver it will be sent on.  

If you need an RtpSender, use addTransceiver instead.

Of course, then we need to change removeTrack (or remove it and just use transceiver.stop).

**Comment by juberti** [comment]
What don't you like about (2)?

Changing the behavior of addTrack seems like it's unwinding a lot.

**Comment by pthatcherg** [comment]
For (2), it's not just that RtpSender.mid would be null.  With https://github.com/w3c/webrtc-pc/issues/358, we can just remove RtpSender.mid.  But what about the created RtpTransceiver?  Does it have a null MID?  That seems crazy.

**Comment by pthatcherg** [comment]
Ah, well there is another option, then:

4  Remove RtpSender.mid (like https://github.com/w3c/webrtc-pc/issues/358) and then have this rule:

setRemoteDescription may remove a transceiver created by addTrack and replace it with a new transceiver created by setRemoteDescription (with a different mid) that has the same sender.

It's sort of like changing the MID of the transceiver, but by creating a new transceiver instead.

**Comment by alvestrand** [comment]
If we adopt the setRemoteDescription Peter suggested, this can be stated as "the transceiver created by setRemoteDesc(offer) can adopt a pending sender, which will cause the pending transceiver object to be discarded".
This makes it legal to change the owning transceiver of a sender (which I think is NV-compliant), and it says that the mid that a sender sends in the RTP header extension can change over time (possibly only from null to some-value).

**Comment by pthatcherg** [comment]
It is NV-compliant. 

It would *not* mean the header extension value can change.  Because you would never send until setRemoteDescription is called, which means we we wouldn't set anything until it's set/adopted, and that can only happen once.  

And we should scope it to pending transceivers created by addTrack.  I don't think this should apply to anything created by addTransceiver.

**Comment by martinthomson** [comment]
Ugh, if we are going to describe `addTrack` in terms of `addTransceiver` then this is a terrible idea.

**Comment by pthatcherg** [comment]
To describe addTrack in terms of addTransceiver, we'd need a "this transceiver is allowed to be replaced by another one by setRemoteDescription" flag.

**Comment by stefhak** [comment]
Use JSEP matching rules, mid created at createO/A, set into transceiver at setL/R, rollback resets mid (potentially).

**Comment by fluffy** [comment]
When add track creates a transceiver, the mid is NULL

So MID is created when doing create Offer / create Answer (but just saved in the SDP)

When the setLocal happens, any transceivers that match up to a m line in the SDP, get the mid in the transceiver set to that

**Comment by fluffy** [comment]
Rollback puts it back to null

**Comment by martinthomson** [comment]
createO/A selects a mid value, but does not change the transceiver.mid

setLocal/Remote with an offer takes the offer and assigns a mid to each transceiver.

rollback sets the mid back to null if the mid doesn't correspond to something that is active in the session.

**Comment by dontcallmedom** [comment]
this is addressed in PR #463

**Comment by alvestrand** [comment]
Closing as noted above (#463 is merged).
