### ISSUE TITLE
Browser calls close() on failed rollback

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#364]
In http://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription it says:

> If rollback was not necessary or was completed successfully, let reason be IncompatibleSessionDescriptionError. If rollback was not possible, let reason be InternalError and set connection's signaling state to closed.

AFAICT this is the lone case in the specification where the browser rather than content JS is calling `.close`. This case seems worth reconsidering, given how it reads like a "throw up our hands" last resort.

**Comment by jan-ivar** [comment]
If the browser can call close, then it raises at least one issue which is how would JS learn about it.

**Comment by juberti** [comment]
Does this make sense? Why not just fail the rollback and return the error via the promise? We already need to do this when a rollback is not possible (e.g. nothing to do), so unclear why we would self-destruct in this case.

**Comment by martinthomson** [comment]
I agree with @juberti here.

**Comment by jan-ivar** [comment]
wfm

**Comment by stefhak** [comment]
I can't find that text in the current version of the spec. Can we close this Issue? @jan-ivar

**Comment by jan-ivar** [comment]
It has been refactored, but is still there. See http://w3c.github.io/webrtc-pc/#set-description

3.4. "Otherwise, set connection's signaling state to closed."

**Comment by alvestrand** [comment]
This was modelled on websockets' behavior: "if we messed up royally, we bail out by closing".
May or may not be appropirate.

**Comment by alvestrand** [comment]
Related to #389 and #530 - the two other places where the PC is closed by the UA.
@adam-be is working on those places.

**Comment by adam-be** [comment]
Proposed fix #552

**Comment by alvestrand** [comment]
Merged #552
