### ISSUE TITLE
Add drop option for RTCDegradationPreference 

### ISSUE THREAD

**Issue by mhofman** [w3c/webrtc-pc#370]
At the TPAC meeting last Friday, @martinthomson suggested we add a `drop` option to the quality degradation preference for simulcast parameters.

This would allow the browser to automatically drop a simulcast encoding completely instead of just degrading its quality when getting under bandwidth constraints.
Without this, application have to manually monitor the stream through `getStats`, realize the bandwidth constraints are causing degradation, and manually set the encoding to active=false or remove the encoding altogether.

This would also require the encoding entries in the Plan X `sendEncodings` sequence (#353) to be ordered according to their priority. This actually makes sense since, from what I understand, the order in SDP is representative of the priority.

**Comment by aboba** [comment]
> On Nov 1, 2015, at 07:32, Mathieu Hofman <notifications@github.com> wrote:
> At the TPAC meeting last Friday, @martinthomson suggested we add a drop option to the quality degradation preference for simulcast parameters.
> 
[BA] The degradation preference relates to the tradeoff between framerate and resolution in response to congestion.  At TPAC there were questions about how this works for simulcast. If the preference is set consistently between simulcast streams, the requested framerateScale /resolutionScale ratios can be maintained under degradation. However, if simulcast streams are requested to degrade differently, then the requested ratios may not be attainable - this could result in an over-constraint. So I would question whether we fully understand how degradation preference works in simulcast. 

An alternative is stop sending one or more simulcast streams. This could be controlled from the SFU (e.g. PAUSE/RESUME) or the browser.  Our experience that in simulcast/SVC this works better than attempting to degrade some or all streams. 

IMHO an RtpSender should be allowed to stop sending simulcast streams at its discretion, even if active=true is set on the stream.  In that case, do we really need an explicit drop preference? 

> This would also require the encoding entries in the Plan X sendEncodings sequence (#353) to be ordered according to their priority. This actually makes sense since, from what I understand, the order in SDP is representative of the priority.
> 

[BA] RTCPriorityType is orthogonal to the simulcast/SVC stream relationship, so we should be clear that one is not inferred from the other. However, I do agree that the ordering is meaningful.

**Comment by elagerway** [comment]
@mhofman this issue has been flagged for discussion at the interim on Thursday, do you plan on speaking to this? Slides placeholder: https://docs.google.com/presentation/d/1qfaxn8GMplm__s_ejMq6C3atA_pBnGXsjmAkKNIh3Ds/edit#slide=id.gf7328a83a_1_37

**Comment by mhofman** [comment]
I'm not sure I understand enough about the issue and simulcast to actually speak about it.
I created the issue after TPAC after @martinthomson had the idea and asked me to create an issue to keep track of it.

**Comment by elagerway** [comment]
@mhofman ok thanks, assigning this to martin then.

**Comment by elagerway** [comment]
@aboba indicated he was interested in talk about this tomorrow, adding it back to the interim topics.

**Comment by aboba** [comment]
I believe that consensus from the virtual interim was that <var>priority</var> should not be overloaded to indicate which encodings are dropped first.  Also, that additional encoding parameters (e.g. <var>minQuality</var> from ORTC) should not be added.  If that is an accurate representation, then this issue should be closed as "won't fix".

**Comment by alvestrand** [comment]
Conclusions seems to be that we won't add such a knob at this time. Closing.
