### ISSUE TITLE
peerIdentity and certificates are unused in setConfiguration

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#373]
There is no mention of the `peerIdentity` or `certificates` members of `RTCConfiguration` in
http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-setConfiguration-void-RTCConfiguration-configuration

This seems like an omission. Questions I have are:

 * Can they be changed at any time, or only before initial call?
 * Do either of them have any input validation steps that can make setConfiguration fail?
 * Is an ICE restart required for these changes to take effect?

**Comment by martinthomson** [comment]
It's hard to reason about these changing.  I believe that we have text in other places that states that these cannot change.

**Comment by jan-ivar** [comment]
We should probably mention that, or implementers might get the wrong idea.

**Comment by dontcallmedom** [comment]
I think the gist of this issue will be better handled as part of #382
