### ISSUE TITLE
is `audioLevel` in `RTCRtpContributingSource` positive or negative?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#377]
The spec describes `audioLevel` as ranging from 0 to -127, but refers to RFC6464 which uses positive values to represent that range (by expressing it in the unit -dBov).

**Comment by fluffy** [comment]
Great question. My preference is it returns a negative number 

Sent with my thumbs - sorry

**Comment by dontcallmedom** [comment]
This was closed when #403 was merged
