### ISSUE TITLE
DtlsTransport is not exposed for datachannels

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#379]
RTPSender and Receiver have a transport attribute; there is no equivalent for data channels.

**Comment by dontcallmedom** [comment]
Well, it is, via `pc.sctp`; sorry for the noise.

**Comment by aboba** [comment]
See Section 5.6: 

interface RTCSctpTransport {
    readonly    attribute RTCDtlsTransport transport;
    readonly    attribute unsigned long    maxMessageSize;
};
