### ISSUE TITLE
Rejecting unallowed changes to configuration

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#382]
http://localhost/~dom/webrtc-pc/webrtc.html#widl-RTCConfiguration-certificates claims that changes to the certificates after their initial setting MUST be rejected.

I'm unclear whether it means that calling setConfiguration with an object that has a value in certificates:
*  must throw an error
* must ignore it

The current "set the configuration" algorithm ends up with ignoring it; so it may just be that we need to remove this "MUST be rejected" or turn into something more informative, e.g. "will be ignored".

Also, I think the same treatment would need to be applied to peerIdentity.

**Comment by dontcallmedom** [comment]
I was planning to determine which of ignore/throw to adopt based on current implementations; but it doesn't look like any browser implements `setConfiguration()` at this point, so I guess we have to decide which way to go.

If we choose "ignore", I think we might want to use a separate dictionary for `setConfiguration()` (e.g. `RTCMutableConfiguration`) — that way, the WebIDL itself would express the "ignore" behavior.

**Comment by martinthomson** [comment]
I think that @dontcallmedom has the right approach here.  Given a choice, I think that I would prefer a rejection.  That means that there aren't any surprises when someone tweaks an unchangeable setting and sets it.  That also means an easier path for the spec.
