### ISSUE TITLE
should "none" be a recognized value in RTCIceTransportPolicy?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#384]
JSEP has "all", "public" (cf #8) and "relay", the API has "all", "relay" and "none".

Is "none" still needed or was it useful only when we didn't have iceCandidatePoolSize?

**Comment by aboba** [comment]
WebRTC Section 4.2.1 refers to RTCIceTransportPolicy which has values of "all", "relay" and "none".  Some values appear to relate to sending and receiving ICE connectivity checks (none: "The ICE agent must not send or receive any packets at this point") while other values appear to relate to ICE candidate gathering behavior. 

The JSEP Section 4.1.1 discussion on "ICE candidate policy" refers both to candidate gathering and use, with values of "all", "public" and "relay".  Overall, the language in JSEP seems more clear to me.  

Should we refer to JSEP Section 4.1.1 and update the values of RTCIceTransportPolicy to reflect what is there?

**Comment by dontcallmedom** [comment]
This was closed when #432 was merged

**Comment by aboba** [comment]
Reopening, because there was a question about whether replacing "none" with "public" could cause a backward compatibility problem.  Also, Harald suggested that using a DOMString instead of enum might make more sense.  So review at the upcoming virtual interim is probably a good idea.

**Comment by elagerway** [comment]
Closing this as is duplicated in issue #441
