### ISSUE TITLE
Certificates expiry?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#386]
When generating certificates or obtaining them automatically from the peer connection object, the developer has no control on the expiry date which seems to be implementation dependent.

Why is that? Shouldn't generateCertificate take a parameter to set the expiry time? 
Should there be a common default expiry date for automatically generated certificates (I think both Chrome and Firefox uses a month)?

**Comment by fluffy** [comment]
Can we get this is with web crypto api? 

Sent with my thumbs - sorry

**Comment by alvestrand** [comment]
No, the WebCrypto API does not operate on RTCCertificate objects.
The only common part is the algorithm identifier structure.

(and it would seem reasonable to to have an expiry parameter to generateCertificate. Would you want it as a minimum, a maximum or as "exactly this"?)

**Comment by martinthomson** [comment]
Firefox supports a hidden "expires" attribute for generation: https://dxr.mozilla.org/mozilla-central/source/dom/media/webrtc/RTCCertificate.cpp#70-77

That was primarily for testing purposes.  I can generate a PR if folks are interested in the feature.

**Comment by steely-glint** [comment]
I'd very much welcome such a PR.

 The current 1month default is too long in some cases and too short in others. Basically you want to set it long enough so you can rotate the key before it expires. For a monthly conference call you wouldn't be able to do that.

 - The 'expires' name is likely to be confusing unless the type and value is the same as the certificate.expires field
