### ISSUE TITLE
Ambiguous type of `ssrc` identifier; DOMString or unsigned long?

### ISSUE THREAD

**Issue by Pehrsons** [w3c/webrtc-pc#390]
In webrtc-pc [1] we have the dictionaries `RTCRtpEncodingParameters`, `RTCRtxParameters` and `RTCFecParameters` all containing the member `ssrc of type unsigned long`.

There's also `RTCRtpContributingSource` containing the member
```
source of type unsigned long, readonly
    The CSRC or SSRC value of the contributing source.
```

At the same time we have `RTCRTPStreamStats` with the member `ssrc of type DOMString` in webrtc-stats [2].

The issue here is that we keep ssrc:s with different types around in the APIs.

@jan-ivar  suggested that `ssrc` is a DOMString in the getStats API because all IDs in javascript are DOMStrings, since they are not quantifiable. I can't comment on the truthiness of that, but I'll note that we also have the underlying IETF specification RFC3550 [3] saying that `ssrc` is a 32-bit number.

At the very least all `ssrc` attributes should be of the same type.

[1] https://w3c.github.io/webrtc-pc/archives/20151006/webrtc.html
[2] https://w3c.github.io/webrtc-stats/archives/20151023/webrtc-stats.html
[3] https://tools.ietf.org/html/rfc3550#section-8

**Comment by aboba** [comment]
I believe that SSRC/CSRC is consistently unsigned long everywhere in this document except for stats. 
Given that there are existing implementations, changing dozens of ssrc attributes to an alternative type should be avoided if at all possible.

**Comment by jan-ivar** [comment]
Webidl is arguably way over-typed given its sole client language, and I find its plethora types mostly useful for defining invariants on inputs to implementations. JavaScript doesn't have a concept of unsigned long after all.

For example, the following produces 1280 x 720 in Firefox (which uses webidl-compiled binding-code):

    navigator.mediaDevices.getUserMedia({ video: { width: "1280", height: "720" } })

That said, I think `unsigned long` makes sense given RFC3550, especially now that we take it as input in some places. `getStats` is output only, and could probably tolerate a change from `DOMString` to `unsigned long` for this field.

**Comment by pthatcherg** [comment]
I agree that it should be "unsigned long" everywhere.
