### ISSUE TITLE
Language for onnegotiationneeded is incomplete/inconsistent.

### ISSUE THREAD

**Issue by docfaraday** [w3c/webrtc-pc#392]
The language for onnegotiationneeded says the following should happen when a PC is marked "negotiation-needed" outside of stable:

"Otherwise, do nothing. If necessary, an event will be fired during setLocalDescription or setRemoteDescription processing, as described above."

However, the language for setRemoteDescription does not describe any action wrt negotiation-needed. I also cannot find any part of the spec that alludes to these two things interacting. I suspect the intent was to wait until a transition to stable (from either setLocal or setRemote) and fire the callback then.

**Comment by dontcallmedom** [comment]
Step 3.2.9 of setting an RTCSessionDescription says:
>if  the negotiation-needed flag is set, the User Agent MUST queue a task to fire a simple event named negotiationneeded

**Comment by elagerway** [comment]
Closing as per Dom's comments
