### ISSUE TITLE
getRemoteCertificates() should return a sequence of base64 DOMString instead of sequence <ArrayBuffer>

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#395]
From Harald Alvestrand: 
https://lists.w3.org/Archives/Public/public-webrtc/2015Nov/0015.html

Related ORTC Issue: 
https://github.com/openpeer/ortc/issues/281

**Comment by martinthomson** [comment]
I disagree.  `ArrayBuffer` is the right type.

There is a valid concern regarding serialization.  That could be worked around if s/dictionary/interface/g happened, but I'm guessing that won't happen for stats.

**Comment by aboba** [comment]
I am ok with sequence<ArrayBuffer> myself, just so long as we understand exactly what the sequence means (e.g. a certificate chain, or a sequence of self-signed certificates).  See PR https://github.com/w3c/webrtc-pc/pull/431

**Comment by martinthomson** [comment]
I think that we should actually change this to `readonly attribute FrozenArray<ArrayBuffer> ...` especially now that Respec supports `FrozenArray` properly.

**Comment by alvestrand** [comment]
Decided to leave it as binary.
