### ISSUE TITLE
RFC5245 says nothing about multiple TURN servers, but WebRTC can be supplied with more than one.

### ISSUE THREAD

**Issue by jnoring** [w3c/webrtc-pc#399]
RFC 5245 says nothing about operating with multiple TURN servers.  Per 4.1.1.2,

```
This specification only considers usage of a single STUN or TURN
   server.  When there are multiple choices for that single STUN or TURN
   server (when, for example, they are learned through DNS records and
   multiple results are returned), an agent SHOULD use a single STUN or
   TURN server (based on its IP address) for all candidates for a
   particular session.  This improves the performance of ICE.  The
   result is a set of pairs of host candidates with STUN or TURN
   servers.  The agent then chooses one pair, and sends a Binding or
   Allocate request to the server from that host candidate.  Binding
   requests to a STUN server are not authenticated, and any ALTERNATE-
   SERVER attribute in a response is ignored.  Agents MUST support the
   backwards compatibility mode for the Binding request defined in
   [RFC5389].  Allocate requests SHOULD be authenticated using a long-
   term credential obtained by the client through some other means.
```
...but WebRTC currently allows configuration of multiple TURN servers.  The issue with this is for many WebRTC implementations, the resulting TURN server candidates all end up being the same priority, which is explicitly in violation of section 4.2, which also applies to full-ICE implementations:

```
   Each candidate is assigned a foundation.  The foundation MUST be
   different for two candidates allocated from different IP addresses,
   and MUST be the same otherwise.  A simple integer that increments for
   each IP address will suffice.  In addition, each candidate MUST be
   assigned a unique priority amongst all candidates for the same media
   stream.  This priority SHOULD be equal to:

   priority = (2^24)*(126) +
              (2^8)*(IP precedence) +
              (2^0)*(256 - component ID)
```
The WebRTC codebase gets around this by subscribing priority in decending order based on the order of incoming TURN servers.  Firefox also appears to work this way.  Chrome, however, has its own implementation and simply assigns all TURN servers equal priority.

The webrtc spec should be explicit about priority in the multiple TURN server configuration, even if RFC 5245 avoids the question.

**Comment by pthatcherg** [comment]
This is probably a question more appropriate for the IETF side of things
rather than the W3C side.

And I think the idea of multiple TURN servers isn't unique to WebRTC, so I
think it may be appropriate to bring this up in the ICE WG at the IETF (
ice@ietf.org).  In fact, that WG is already working on an update to 5245
(called "ICEbis"), so it's a good time to bring up things like this.  I'm
sure that WG would welcome your discussion there.

Could you please post your question to the ICE WG, without cross-posting
between the groups?

**Comment by jnoring** [comment]
Sure--could you point me in the direction of the ICE WG?  Sorry, I am completely unfamiliar with how these different groups actually communicate.

**Comment by pthatcherg** [comment]
https://datatracker.ietf.org/wg/ice/charter/

Sign up to the IETF at http://ietf.org/

Email the list at ice@ietf.org.

**Comment by elagerway** [comment]
Closing this as it is an IETF issue
