### ISSUE TITLE
Define what the streams argument (list of MediaStream objects) does in addTrack

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#426]
https://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-addTrack-RTCRtpSender-MediaStreamTrack-track-MediaStream-streams

This doesn't seem to say what to actually do with the streams.

CC @alvestrand

**Comment by alvestrand** [comment]
The expected result is that there are MSIDs for those streams listed in the SDP. This will probably take a JSEP reference (not sure where).

**Comment by bzbarsky** [comment]
Looks identical to https://github.com/w3c/webrtc-pc/issues/369

**Comment by alvestrand** [comment]
I think you're right. Closing as duplicate.
