### ISSUE TITLE
No reference to where TypeError is defined 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#427]
We use things like TypeError, InvalidStateError, InternalError etc without saying they are defined in EcmaScript and we probably need a normative reference to 

[ES6]
Allen Wirfs-Brock. ECMAScript 2015. Standard. URL: http://www.ecma-international.org/ecma-262/6.0/

**Comment by dontcallmedom** [comment]
I don't think we need it, we get these definitions (and the underlying normative reference to ES6) via the ref to WebIDL.

**Comment by fluffy** [comment]
WebIDL does not contain the word InvalidStateError in the spec. I think it is very confusing to people working on this that are not WebIDL experts to find the definitions (and lets face it, most people writing JS have never heard of WebIDL). I think this would help people figure out what was going to be in the rejected promises that get passed back to them. I agree that we technically get it via WebIDL but that is not easy to figure out and it is equally true that they are defined in ES6 and we normatively depend on that but that.

**Comment by dontcallmedom** [comment]
WebIDL does [contain the word InvalidStateError](http://www.w3.org/TR/WebIDL-1/#idl-DOMException-error-names)
(we're not referencing the right version of WebIDL at the moment, but that's another issue)

**Comment by alvestrand** [comment]
Will close this one once we get a PR or issue filed that references updating the WebIDL reference.
