### ISSUE TITLE
How should replaceTrack() behave with an "unused" sender

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#438]
Consider this case
```
var sender = pc.addTrack(track);
sender.replaceTrack(otherTrack);
```
How should replaceTrack() behave in this case? Should we disallow it, or simply replace the track and negotiate the new track, but still use the id from the first?

**Comment by pthatcherg** [comment]
I think that should be the equivalent of:

var sender = pc.addTrack(track);
// ... pc.createOffer, pc.setLocalDescription, pc.setRemoteDescription ... 
sender.replaceTrack(otherTrack);

In other words, it shouldn't matter when you call replaceTrack in relation to negotiation.  The sender should always use the IDs and other info it needs from the first track and use that forever.  I think disallowing it causes unnecessary burden on the application and anything else would be unnecessarily complex.

**Comment by martinthomson** [comment]
I agree with @pthatcherg

**Comment by stefhak** [comment]
That looks like the cleanest solution to me too.

**Comment by elagerway** [comment]
@adam-be can you do a PR for this one?
