### ISSUE TITLE
RTCIceTransports needs to be DOMString not enum?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#441]
In the interest of extensibility to new values, we should make the places where RTCIceTransport is used as a parameter use a DOMString, wiht "values should be from the RTCIceTransport enum".
This avoids exceptions on new values (allowing us to ignore or default them instead).

**Comment by elagerway** [comment]
This issue has been flagged for discussion at the interim on Thursday, slides placeholder: https://docs.google.com/presentation/d/1qfaxn8GMplm__s_ejMq6C3atA_pBnGXsjmAkKNIh3Ds/edit#slide=id.gf7328a83a_1_22

**Comment by dontcallmedom** [comment]
This was discussed on the [Jan 14 interim](https://www.w3.org/2016/01/14-webrtc-minutes#item03.5) where it was determined that an enum is appropriate.

There may needs more discussions on the right value of the enum (should `public` stay in?), but they would belong to a separate issue, so I think that issue can be closed.

**Comment by alvestrand** [comment]
No change needed.
