### ISSUE TITLE
Impossible to know if ICE agent is "finished checking", for "failed" and "completed" states.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#442]
Focusing first on "failed", it's defined as: "The ICE Agent is finished checking all candidate pairs and failed to find a connection for at least one component."

However, even after finishing gathering and checking all current candidate pairs, a new remote candidate could be applied at any time via addIceCandidate, creating new candidate pairs.

The trickle ICE spec addresses this, saying a check list should only go to the Failed state when "the remote agent has sent an end-of-candidates indication for that check list as described in Section 9.3.". The RTCPeerConnectionIceEvent does signal "end-of-candidates", but there are two problems with this:

1. It's only signaled once, but it needs to be signaled once per check list (once per m-line).
2. There's no way to pass the end-of-candidates indication into the browser.

I would propose adding a way to indicate "end of remote candidates" to the browser, either by overloading addIceCandidate or by adding a new method. This indication would ensure an accurate "failed" state (that doesn't flip back to "checking"), and it could also be used to optimize the ICE algorithm, as discussed in trickle ICE.

If we *don't* do that, we should at least make the spec clear in the fact that "failed" is temporary, and it could return to "checking" if a new candidate pair is created.

**Comment by ekr** [comment]
I was going to say that this just worked, but it seems that addIceCandidate doesn't take a nullable candidate, which is what you would want for this.

**Comment by pthatcherg** [comment]
Another option could be to define "failed" as "will only be connected again
with an ICE restart" (different from disconnected which is "may be
connected again without an ICE restart").  For example, when consent is not
refreshed.  Right now, that happens if you don't get any STUN requests or
responses for 30 seconds in the middle of a call.  Could we just make that
the same for the start of a call?  No connection after 30 seconds since
last created candidate pair == failed?  That would be a lot easier to
implement, and would actually be useful if an implementation chooses to
never end candidate gathering.

**Comment by aboba** [comment]
On Jan 6, 2016, at 15:49, Peter Thatcher <notifications@github.com> wrote:
> 
> Another option could be to define "failed" as "will only be connected again
> with an ICE restart" (different from disconnected which is "may be
> connected again without an ICE restart"). For example, when consent is not
> refreshed. Right now, that happens if you don't get any STUN requests or
> responses for 30 seconds in the middle of a call.

[BA] That just invalidates the pair on which consent has failed - but it doesn't necessarily preclude using another pair without an ICE restart. So it is possible for a consent failure to result in a transition to "disconnected", not "failed".

> Could we just make that
> the same for the start of a call? No connection after 30 seconds since
> last created candidate pair == failed? That would be a lot easier to
> implement, and would actually be useful if an implementation chooses to
> never end candidate gathering.

[BA] In the beginning (before candidate pairs are pruned), it is even more likely that a consent failure could be recoverable, particularly if candidate gathering is in progress (or could resume if a new interface comes up). 

On Mon, Dec 28, 2015 at 5:46 PM, ekr <notifications@github.com> wrote:
> 
> > I was going to say that this just worked, but it seems that
> > addIceCandidate doesn't take a nullable candidate, which is what you would
> > want for this.


[BA] Don't existing implementations still support a "special" candidate? Not saying this is ideal, but it does "just work" today - and the best alternative would be a candidatesComplete() method .

**Comment by stefhak** [comment]
@aboba is that special candidate per m-line, or for the aggregate?

**Comment by pthatcherg** [comment]
On Wed, Jan 6, 2016 at 8:36 PM, aboba <notifications@github.com> wrote:

> On Jan 6, 2016, at 15:49, Peter Thatcher <notifications@github.com> wrote:
> >
> > Another option could be to define "failed" as "will only be connected
> again
> > with an ICE restart" (different from disconnected which is "may be
> > connected again without an ICE restart"). For example, when consent is
> not
> > refreshed. Right now, that happens if you don't get any STUN requests or
> > responses for 30 seconds in the middle of a call.
>
> [BA] That just invalidates the pair on which consent has failed - but it
> doesn't necessarily preclude using another pair without an ICE restart. So
> it is possible for a consent failure to result in a transition to
> "disconnected", not "failed".


​Ah, yes.  You are correct.  I was misunderstanding consent freshness.  I
thought that if you lost consent on all candidate pairs, you would just
call the whole thing off until an ICE restart.  But now that I re-read the
consent freshness spec, that's not what it says.  You can indeed always add
more candidate pairs (unless both sides say they are done gathering).


>
> > Could we just make that
> > the same for the start of a call? No connection after 30 seconds since
> > last created candidate pair == failed? That would be a lot easier to
> > implement, and would actually be useful if an implementation chooses to
> > never end candidate gathering.
>
> [BA] In the beginning (before candidate pairs are pruned), it is even more
> likely that a consent failure could be recoverable, particularly if
> candidate gathering is in progress (or could resume if a new interface
> comes up).


> On Mon, Dec 28, 2015 at 5:46 PM, ekr <notifications@github.com> wrote:
> >
> > > I was going to say that this just worked, but it seems that
> > > addIceCandidate doesn't take a nullable candidate, which is what you
> would
> > > want for this.
>
>
> [BA] Don't existing implementations still support a "special" candidate?
> Not saying this is ideal, but it does "just work" today


​As far as I know there is no spec for a special candidate going into the
browser (only out of it).  And we certainly haven't implemented anything in
Chrome.  And the question of how we should implement the failed state
without that special candidate value is exactly what prompted this thread.​
​


> - and the best alternative would be a candidatesComplete() method .


​My guess is that lots of application developers would not remember to
signal/call that method, effectively making the failed state never happen.​
​

**Comment by pthatcherg** [comment]
Per IceTransport, which is per m-line, unless bundled.  In that case, per
bundle group.

And, actually, it's more than that.  It's per ICE generation of each
IceTransport, which means the "special" candidate would need to include
something to indicate the ICE generation (such as ufrag), otherwise if two
generations are in flight simultaneously, you wouldn't know which has ended.

**Comment by stefhak** [comment]
@pthatcherg is your proposal that we should have special candidates signaling "end of candidates" per transport and generation? 
The "30 second timeout" version sounded simpler.

**Comment by pthatcherg** [comment]
​I'm not proposing we add an "end of candidates" message, because I'm not
sure it's the right solution.  I'm saying that if we do ​choose an "end of
candidates", it needs to be per-m-line, and possibly also
per-ICE-generation.

I agree that a timeout is more simple and easy to understand.

**Comment by elagerway** [comment]
This issue has been flagged for discussion at the interim on Thursday, slides placeholder: https://docs.google.com/presentation/d/1qfaxn8GMplm__s_ejMq6C3atA_pBnGXsjmAkKNIh3Ds/edit#slide=id.gf7328a83a_1_17

**Comment by alvestrand** [comment]
Discussion at the interim concluded that we need a more detailed proposal; Taylor and Justin said they would come back after discussing this some more.

**Comment by elagerway** [comment]
@taylor-b 9 days to virtual interim, if there is a new proposal forthcoming please edit the slides referenced above.

**Comment by alvestrand** [comment]
Merged #527
