### ISSUE TITLE
Contributing source(s) missing voice activity flag

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#450]
This issue was filed by Robin Raymond against ORTC but it also applies to WebRTC 1.0: 

In RTCRtpContributingSource there is audio level and csrc/ssrc but no flag indicating whether voice activity is contained within the packet.  Since the "V" bit is only supported in RFC 6464 but not RFC 6465, there is value in exposing the "V" bit to the developer when peers are sending the "client-to-mixer" extension to each other.  Could be "unset" for "mixer-to-client" obtained values and "set" for "client to mixer" obtained values (i.e. when value arrives peer to peer).

ORTC Issue:  https://github.com/openpeer/ortc/issues/263
ORTC PR: https://github.com/openpeer/ortc/pull/326

**Comment by aboba** [comment]
Since the PR has been merged, I think we can close this.

**Comment by alvestrand** [comment]
Closed per merge of #454
