### ISSUE TITLE
Spelling of RTCRtxParameters and RTCFecParameters

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#477]
In ORTC, it is RTCRtpRtxParameters and RTCRtpFecParameters.  Is the difference in spelling intentional?

**Comment by alvestrand** [comment]
Does anyone have an implementation of these - in either API?

**Comment by aboba** [comment]
In ORTC, they are both implemented in ORTC-lib, and we shipped RTCRtpFecParameters in Edge.

**Comment by dontcallmedom** [comment]
I think there is unlikely to be any objection to updating the names in WebRTC to match (where implementations haven't caught up with setParameters afaict)

**Comment by stefhak** [comment]
#486 has been merged.
