### ISSUE TITLE
Clarify relation between a local track's settings and how it is encoded by PeerConnection

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#478]
As discussed in the thread https://lists.w3.org/Archives/Public/public-webrtc/2016Jan/0058.html there is currently no text about the relation between how a local MediaStreamTrack has been set up using constraints (to control things like framerate, width, height and so on) and how it would be encoded when transmitted.
I think everyone has been assuming that the properties should be maintained as far as possible, but the spec does not say anything about it.

**Comment by alvestrand** [comment]
Big issue. Might want to file more issues for detailed handling. Stefan will write a PR with the prose part.

**Comment by stefhak** [comment]
I'm wondering if we can't close this one now that #519 has landed?

**Comment by alvestrand** [comment]
Seems good. Closing.

**Comment by elagerway** [comment]
LGTM
