### ISSUE TITLE
getSenders/getReceivers: optional kind parameter?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#488]
while playing with simulcast I noticed that neither [getSenders](http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-getSenders-sequence-RTCRtpSender) nor [getReceivers](http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-getReceivers-sequence-RTCRtpReceiver) (and getTransceivers?) takes a 'kind' member specifying the media type.

What I was originally looking to do was along the lines of
```
pc.getSenders('video')[0].setParameters(...)
```
to configure simulcast on the first video track. Trivial to work around by using .filter on the array of senders returned:
```
pc.getSenders().filter(function(sender) { return sender.track.kind === 'video'; })[0]
.setParameters(...)
```

But since [getCapabilities](http://w3c.github.io/webrtc-pc/#widl-RTCRtpReceiver-getCapabilities-RTCRtpCapabilities-DOMString-kind) takes an optional kind parameter that seems slightly inconsistent.

**Comment by jan-ivar** [comment]
This seems supefluous to me. What's wrong with:

    pc.getSenders().filter(sender => sender.track.kind == 'video');

?

**Comment by jan-ivar** [comment]
> But since getCapabilities takes an optional kind parameter that seems slightly inconsistent.

I don't think so. If we were talking about mediaStreamTrack.getCapabilities() having a `kind` parameter, then yes I agree it would be consistent with `pc.getSenders()` having one, since those would both be simple dictionary filters.

But `receiver.getCapabilities()` is not that. It's a selector between two value-sets of the same type, since video has `RTCRtpCapabilities`, and audio also has `RTCRtpCapabilities`, but with different values.

**Comment by jan-ivar** [comment]
(mediaStreamTrack.getCapabilities() doesn't really make sense either, but take getSupportedConstraints() where we in fact did have a kind parameter for a brief while, before we realized it was a simple dictionary-filter.

**Comment by jan-ivar** [comment]
In other words:
* the `kind` in `receiver.getCapabilities` is an index
* the `kind` in `pc.getSenders` is a filter

**Comment by fippo** [comment]
at least in Edge, the getCapabilities behaviour seems more like a filter to me.
```
RTCRtpSender.getCapabilities()
```
returns a set of audio and video codecs which could be filtered by looking at their kind. But if you do that, should there not be a consistent way to do this filtering?

This is not true for all things in the capabilities however, for example the fecMechanisms (which are [defined in ORTC](http://ortc.org/wp-content/uploads/2015/11/ortc.html#widl-RTCRtpCapabilities-fecMechanisms) but not in the [peerconnection api](http://w3c.github.io/webrtc-pc/#idl-def-RTCRtpCapabilities)?! @aboba can you check please) can not be filtered as easily since they are just a sequence of DOMStrings

**Comment by jan-ivar** [comment]
If it's a filter then we should get rid of `kind` there too, and use `RTCRtpSender.getCapabilities().filter(someFilter)` but I suspect there isn't a true super-set here, since not all members of this dictionary are arrays?

**Comment by pthatcherg** [comment]
The big difference between getSenders/getReceivers and getCapabilities, is
that sender and receivers are trivially separable by kind, as Jan-Ivar
pointed out.  Capabilities, however, when "merged", are not trivially
separable.   Header extensions do not have a kind, so you can't tell if
they are for audio or video or both.  We could change that, but it would be
additional complexity for no clear benefit.

**Comment by aboba** [comment]
In WebRTC 1.0, receiver.track.kind is always defined, so getReceivers().filter(kindFilter) should always work.  There is no getReceivers() method in ORTC, but if there were it would currently not work well with filter() since receiver.track.kind is not set until calling receive().

**Comment by alvestrand** [comment]
Consensus seems to be against adding this parameter.
