### ISSUE TITLE
should "queue a task to fire a simple event"

### ISSUE THREAD

**Issue by ShijunS** [w3c/webrtc-pc#490]
A minor editorial issue in the spec: 
There are a few places the spec says “fire a simple event”, while typically in W3C specs (incl. WebRTC 1.0 spec), we normally say “queue a task to fire a simple event”.

**Comment by adam-be** [comment]
I wouldn't be surprised if we had some bugs related to this, but there are cases where that kind of wording is intentional. For example, when a task is queued to run some steps, often update some state, and then fire an event. We don't want to queue an other task in that case.

**Comment by adam-be** [comment]
I've looked for all cases where a simple event is fired, and I believe we are queueing tasks when we should and firing synchronously where needed. I think we can close this issue. @ShijunS, if you find a specific location where you think this is wrong, please file a new issue.
