### ISSUE TITLE
avoid risk of reentrancy

### ISSUE THREAD

**Issue by ShijunS** [w3c/webrtc-pc#492]
Open an issue based on discussions with Bernard.  We should avoid any risk of reentrancy, and meanwhile clarify a few places for firing events in the related algorithm steps.

Section 4.3.1
----------
 ...
 If the process to apply description fails for any reason, then user agent must queue a task runs the following steps:
1. If connection's signaling state is closed, then abort these steps.
2. If the content of description is invalid or if description's type is wrong for the current signaling state of connection, then reject p with an InvalidSessionDescriptionError and abort these steps.
3. If description cannot be applied at the media layer, but the User Agent recovered, possibly by rolling back to the previous configuration, then reject p with IncompatibleSessionDescriptionError and abort these steps.
This occurs, for example, when the version of description is older than the one currently being used.
4. Otherwise, set connection's signaling state to closed.
5. Fire a simple event named signalingstatechange at connection. 
**[BA] Allows the signalingstatechange to execute code that could invalidate objects.** 
6. Reject p with InternalError.
...
...
5. If connection's signaling state changed above, fire a simple event named signalingstatechange at connection.
**[BA] Allows code to execute in the signalingstatechange event handler (e.g. PC.close) that could invalidate objects.**
6. If description is set as a local description, connection's ICE gathering state is new, and description contains media, then update connection's ICE gathering state to gathering.
**[BA] ICE gathering state is updated but the state change event isn't fired. Is a task queued for this?** 
7. If the process to apply description resulted in an ICE restart JSEP, then run the following steps:
  If connection is not already gathering, update connection's ICE gathering state to gathering.
  **[BA] ICE gathering state is updated but the state change event isn't fired. Is a task queued for this?** 
  If connection's ICE connection state is completed, update connection's ICE connection state to connected.
  **[BA] ICE connection state is updated but the state change event isn't fired. Is a task queued for this?**
8. If description is set as a remote description with new media descriptions [JSEP], the User Agent must dispatch a receiver for all new media descriptions.
9. If connection's signaling state is now stable, and the negotiation-needed flag is set, the User Agent must queue a task to fire a simple event named negotiationneeded at connection and clear the negotiation-needed flag.
10. Resolve p with undefined.
...

Section 6.2
------
...
2. Set channel's readyState attribute to closed.
3. If the transport was closed with an error, fire an NetworkError event at channel.
**[BA] The NetworkError event should be queued to avoid having an error handler execute prior to the next step.**
3. Fire a simple event named close at channel

**Comment by jan-ivar** [comment]
Reentrant would be code causing itself to run again before exiting, which I don't think can happen here since we're in queued tasks, but it sounds like the concern is allowing content code to run before all steps have completed, is that right?

>  5 . Fire a simple event named signalingstatechange at connection.
> [BA] Allows the signalingstatechange to execute code that could invalidate objects.
>  6 . Reject p with InternalError.

What objects could be invalidated? It seems at this point the peer connection is closed, and the only remaining object operated on after this step is the (still) internal object `p`, which is rejected.

> 5 . If connection's signaling state changed above, fire a simple event named signalingstatechange at connection.
> [BA] Allows code to execute in the signalingstatechange event handler (e.g. PC.close) that could invalidate objects.
> 6 . If description is set as a local description, connection's ICE gathering state is new, and description contains media, then update connection's ICE gathering state to gathering.
> [BA] ICE gathering state is updated but the state change event isn't fired. Is a task queued for this?

(5) seems problematic, and should probably be queued, like (6), (7) and (8) are.
(6), (7) and (8) make sense, since the firing is queued in [update connection's ICE gathering state](http://w3c.github.io/webrtc-pc/#update-ice-gathering-state).

> Section 6.2
>
> ...
> 2 . Set channel's readyState attribute to closed.
> 3 . If the transport was closed with an error, fire an NetworkError event at channel.
> [BA] The NetworkError event should be queued to avoid having an error handler execute prior to the next step.
> 3 . Fire a simple event named close at channel

I don't know enough here to know which order is desired, but does it matter once the channel is closed? Might reordering them accomplish the same thing?

**Comment by ShijunS** [comment]
> but does it matter once the channel is closed? Might reordering them accomplish the same thing?

The question is not about the ordering of the events.  As an example, if the pc object is destroyed or garbage-collected between the two events, would there be any security risk to the UA?

**Comment by jan-ivar** [comment]
I think http://w3c.github.io/webrtc-pc/#garbage-collection says that cannot happen: the pc object "MUST not be garbage collected as long as any event can cause an event handler to be triggered on the object".

**Comment by jan-ivar** [comment]
I guess we're talking about the RTCDataChannel, and there's no specific language there, though I suppose we should assume it to be an extension of the peer connection that follows similar rules.

**Comment by ShijunS** [comment]
As an example, there might no be an event handler registered (for the 2nd event) to start with, or an event handler can always be unregistered between the events.  In general, a UA should avoid reentrancy as much as possible since we can't predict all attack vectors.

**Comment by jan-ivar** [comment]
This is single-threaded, so I believe an event handler can unregister without fear of garbage collection before end-of-completion of this cycle.

**Comment by ShijunS** [comment]
It can be an implementation preference if it works that way in Firefox. You might want to check though.  Again, there are many possible operations once you allow code to run between the steps.  Maybe we should change the perspective a little bit, what would be the problem if we queue at least one of the events in this case?

**Comment by jan-ivar** [comment]
I highly doubt it's an implementation choice. JavaScript generally remains oblivious to garbage collection, thanks to such guarantees.

But rather than speculate on why change *shouldn't* be made, please demonstrate an attack vector justifying the change you are proposing.

**Comment by jan-ivar** [comment]
https://en.wikipedia.org/wiki/Reentrancy_(computing)

**Comment by ShijunS** [comment]
Let's get a concrete conclusion based on major browser implementations.  I'll share with the WG once I collect enough feedbacks.  @jan-ivar, please feel free to ping me in private if you'd like to help with the investigation.

**Comment by Ms2ger** [comment]
There doesn't seem to be any need to change the spec here.

**Comment by alvestrand** [comment]
remaining issues branched off as other bugs.
