### ISSUE TITLE
RID as read-only in setParameters()

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#497]
The current text does not indicate that the RID should be considered read-only within setParameters().

**Comment by adamroach** [comment]
I don't think that's where we settled on the topic. Looking at the minutes from Sapporo (https://www.w3.org/2015/10/28-webrtc-minutes), I see:

  peter: ok JS picks, no more than 16 characters
  martin: not unicode please
  peter: A~&, 0~9, both cases
  all: good

This implies that the JS must have the ability to write the RID.

**Comment by aboba** [comment]
@adamroach - you are correct with respect to addTransceiver()  where init.sendEncodings enables setting of the RID value prior to calling createOffer().  However, the question has arisen as to whether setParameters() can be used to change the RID value.  The text recently added in PR https://github.com/w3c/webrtc-pc/pull/434 states: 

The setParameters does not cause renegotiation at the SDP level
and can only be used to change what the media stack is sending or
receiving within the envelope negotiated by the Offer/Answer.

So the question is whether setParameters() can change the RID value without requiring a new O/A exchange.

**Comment by adamroach** [comment]
@aboba -- Ah, yes, I missed the context here. I agree that this can't be changed once the session is established, since that would require renegotiation.

**Comment by aboba** [comment]
@adamroach - can you look at PR https://github.com/w3c/webrtc-pc/pull/498 to see if it makes sense? 

Also, whether the logic described here is accurate: 
https://lists.w3.org/Archives/Public/public-webrtc/2016Feb/0028.html

**Comment by adamroach** [comment]
@aboba -- The logic in the email is sound, but the proposed change has an issue. I've commented in PR #498 about the issue.

**Comment by jan-ivar** [comment]
@aboba so currently in Firefox Nightly, users can [do this](https://jsfiddle.net/kv14z7r6/):

    var sender = pc.addTrack(stream.getVideoTracks()[0], stream);
    sender.setParameters({ encodings: [{ rid: "A",  maxBitrate: 300000 },
                                       { rid: "B",  maxBitrate: 100000 }] });
    pc.createOffer().then(d => pc1.setLocalDescription(d));

Works without having to use `addTranceiver`. Did we decided this should not work?

**Comment by jan-ivar** [comment]
Note to self: probably need to queue createOffer behind setParameters here now that it is async.

**Comment by aboba** [comment]
I agree with Peter's comment that:  
"Allowing the addition via setParameters means we have to define when that's OK and when that's not OK, and it can get complicated."

Separately, there is the question of whether to allow the RID to be initially set in addTrack as well as addTransceiver.  
Peter's full comment: Full comment: https://lists.w3.org/Archives/Public/public-webrtc/2016Feb/0034.html

**Comment by aboba** [comment]
Can we close this now?
