### ISSUE TITLE
Need API to indicate if temporal or spatial quality is preferred in video compression 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#5]

**Comment by gunnarhm** [comment]
What is the current default quality preference without this parameter?
If it is temporal, then I am satisfied and do not need a parameter.
If it is spatial, I would like to see a possibility to change to temporal.
If it is by choice of codec developer, I would like to see a possibility to set to temporal.

**Comment by stefhak** [comment]
Is part of https://w3c.github.io/webrtc-pc/archives/20151006/webrtc.html.
