### ISSUE TITLE
Add API to control encrypted header extensions for RTP

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#523]
draft-ietf-rtcweb-rtp-usage-25 section 5.2.2 discusses that we need an API to be able to turn on and off RTP header encryption. 

Do we need an API to support this. Many applications can not work with it turned on while some people might want it turned on for privacy reasons.

**Comment by alvestrand** [comment]
Suggest that this may be a "beyond 1.0" feature.
When using SDP, it's possible to do this by SDP munging (negotiate off), but in the NV world, we won't have SDP to munge, so then the need becomes larger.

Not encrypting the volume header allows enough information leakage for rudimentary speech recognition, which is pretty hefty leakage - there probably needs to be explicit information about applications that need to have it in the clear (beyond the obvious PERC use case - I don't think it's realistic to support PERC with 1.0).

**Comment by aboba** [comment]
Currently Section 5.2.8 states that parameters.headerExtensions[].encrypted is read-only, so the value can be read via getParameters(), but not set via setParameters().  Also, addTransceiver() takes init.encodings as an argument, instead of init.parameters (which would include header extensions).  So munging SDP does appear to be the only way to control this.

**Comment by fluffy** [comment]
This is not new - it's been around for years in the specs and I would really rather not have munge SDP to do something like this given that eventually we will need an API for it anyways.

**Comment by elagerway** [comment]
Guys, we would like to shelf the idea of introducing new APIs that have a material effect on the spec at this point. I would propose we revisit this issue after 1.0 makes it to CR.

**Comment by fluffy** [comment]
Again, I don't think this is a new idea. It is simple getting down to cleaning up the missing cracks in the spec. I predict that if we don't have an way to control header encryption, we will have a long argument about if headers and encrypted or not.

**Comment by stefhak** [comment]
This is possible (but a bit painful) to do already by SDP munging. Let's put this one in the "later" category.
