### ISSUE TITLE
NetworkError event is not defined and might not be needed

### ISSUE THREAD

**Issue by ShijunS** [w3c/webrtc-pc#526]
When discussing the following portion of Section 6.2 in issue #492

> 1. ...
> 2. Set channel's readyState attribute to closed.
> 3. If the transport was closed with an error, fire an NetworkError event at channel.
> 4. Fire a simple event named close at channel

@adam-be commented 

> This one is a bit strange. Is the "NetworkError event" even defined somewhere? I think we could do with one event here.

I'm opening a new issue to track this.

**Comment by stefhak** [comment]
Seems like WebSocket uses a close event with reason rather than an error event.

**Comment by adam-be** [comment]
Yes. But there's a simple error event as well [1]. We have a simple close event so it would take some work to align the behaviour.

[1] https://html.spec.whatwg.org/multipage/comms.html#feedback-from-the-protocol

**Comment by adam-be** [comment]
How we want to communicate errors from DataChannel should perhaps be a TPAC or telco topic. It's also a question how current implementations work.

**Comment by dontcallmedom** [comment]
#850 didn't fix this since NetworkError still appears in the draft.

#846 which was closed as a dup had this:
> webrtc-pc Issue #526 "NetworkError event is not defined and might not
be needed": RESOLUTION: we will change our close event to match with
WebSocket’s
> https://lists.w3.org/Archives/Public/public-webrtc/2016Oct/0018.html

**Comment by aboba** [comment]
@adam-be  The Websocket onClose event handler provides the following information:

event.reason, eventWasClean, event.code:

1001    CLOSE_GOING_AWAY
1000    CLOSE_NORMAL
1005    CLOSE_NO_STATUS
1006    CLOSE_ABNORMAL

Note also that in order to provide this information the websocket.close method takes code and reason as arguments: 

void close(in optional unsigned long code, in optional DOMString reason);

So we have agreement that we want to add optional arguments to RTCDataChannel.close()?

**Comment by aboba** [comment]
@stefhak Websockets has a mechanism to communicate the reason for the upper layer closure; there is no equivalent in the data channel. So I don't think it makes sense to add optional arguments to close() or to the onclose EventHandler.

**Comment by aboba** [comment]
@dontcallmedom Section 13 says that the close Event (using the Event interface) is fired when "The RTCDataChannel object's underlying data transport has been closed."  So it does appear that there was an intent to use the close Event for this situation.
