### ISSUE TITLE
MediaStreamTrack clarifications needed(?)

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#529]
The spec says nothing about e.g.
* A track sourced by the PeerConnection should have its ```remote``` attribute set to true
* If the ```readonly``` attribute should be true (should it not? I guess in principle downscaling could be supported though)
* What settings like facingMode, latency ... should read (the SDP does not provide this data, so it should be the default value?)
* How settings like width, height, frameRate, channelCount are populated (presumably from observing the incoming RTP)

**Comment by dontcallmedom** [comment]
The first half would be moot if we remove remote/readonly as per https://github.com/w3c/mediacapture-main/issues/320

**Comment by stefhak** [comment]
I think we can close this issue now that #531 has been merged.
