### ISSUE TITLE
RTCPeerConnectionState is a better home for "closed" than RTCSignalingState is

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#530]
enum RTCSignalingState {
    "stable",
    "have-local-offer",
    "have-remote-offer",
    "have-local-pranswer",
    "have-remote-pranswer",
    "closed" // <-- do I belong here?
};

enum RTCPeerConnectionState {
    "new",
    "connecting",
    "connected",
    "disconnected",
    "failed"
};

**Comment by alvestrand** [comment]
Let's make a PR to move.

**Comment by alvestrand** [comment]
Duplicate of #389
