### ISSUE TITLE
Should remote tracks have .readonly false or true?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#534]
.readonly means you can't call applyConstraints() on it. Is this reasonable+

**Comment by stefhak** [comment]
Quoting mediacapture-main:
```
If the track (audio or video) source is a local microphone or camera that is shared so that constraints applied to the track cannot modify the source's settings, the readonly attribute MUST return the value true. Otherwise, it must return the value false.
```
I think the situation here is similar. But, at least in principle, the UA could downsample to give the track lower resolution, lower frame-rate. That would be valid both in the mediacapture-main scenario and here.

**Comment by dontcallmedom** [comment]
likely to be moot with https://github.com/w3c/mediacapture-main/issues/320

**Comment by stefhak** [comment]
As remote has been removed (https://github.com/w3c/mediacapture-main/pull/321) this is OBE.

**Comment by alvestrand** [comment]
Overtaken by events.
