### ISSUE TITLE
'the process to apply candidate' should link to JSEP

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#550]
Like 'the process to apply description' does. [1]

[1] https://w3c.github.io/webrtc-pc/#set-description

**Comment by alvestrand** [comment]
Agreed, and it should also be clear that it's asynchronous and might fail.

**Comment by dontcallmedom** [comment]
Sounds like a dup of #658 (which links to the relevant JSEP issue)

**Comment by stefhak** [comment]
This one is slightly different than #658 and should be kept open until we've added that link @adam-be talks about.

**Comment by burnburn** [comment]
The link will be addressed by #658.  It looks like this issue is more about structuring the failure wording in the steps underneath this one to parallel the 'set description' language.

**Comment by elagerway** [comment]
This should be taken up in IETF via JSEP
