### ISSUE TITLE
Errors when identifying a m-line in addIceCandidate()

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#551]
We have two pieces of information in an ice candidate to identify a m-line sdpMid and sdpMLineIndex.

The successful case is when both identifiers points to the same m-line or if one identifies an m-line while the other is null.

We have the following uncertain/error cases
1. Both are set, one identifies an m-line while the other is bogus.
2. Both are set and point to different m-lines.
3. One is set, and points to an non-existent m-line (clearly an error).

So the first question is: what should we do in 1 and 2 ?

The second question is where this should be specified. addIceCandidate() is specified to do some synchronous checks on the candidate argument and then start a 'process to apply' the candidate. We could either check for the above errors  in the synchronous section and specify it in the webrtc-pc document. The alternative is to let these checks be part of the 'process to apply' candidate and let the error be asynchronously reported to JavaScript. In the second case, JSEP would need to specify this.

**Comment by alvestrand** [comment]
webrtc-pc would need to specify it in both cases. JSEP can specify exactly how the application process might fail, but webrtc-pc needs to specify where failures go.

**Comment by adam-be** [comment]
Yes. We need to take care of the different failures from the 'process to apply candidate' in the w3c spec.

**Comment by adam-be** [comment]
For peoples convenience to have a look at the unreleased version of addIceCandidate() that I talk about above. Here's a link: http://rawgit.com/w3c/webrtc-pc/master/webrtc.html#widl-RTCPeerConnection-addIceCandidate-Promise-void--RTCIceCandidateInit-RTCIceCandidate-candidate

**Comment by stefhak** [comment]
I filed https://github.com/rtcweb-wg/jsep/issues/272 on JSEP.

**Comment by stefhak** [comment]
There was some discussion in https://github.com/rtcweb-wg/jsep/issues/272 and the conclusion is that 1. is an error, 2. MID has precedence, 3. error.
