### ISSUE TITLE
Normatively cite webrtc-stats for sections 8.x

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-pc#561]
Instead of having information duplication, I propose we remove sections 8.5 and 8.6 from webrtc-pc and point to webrtc-stats normatively.
- remove sections 8.6 
- remove enums and point to webrtc-stats
- For the example assume that the keys exist.

Related to: https://github.com/w3c/webrtc-stats/issues/23

**Comment by alvestrand** [comment]
Discussion with chairs/editors indicate that we should resolve this the other way - keep enough information in webrtc-pc for a basic stats interface.

**Comment by alvestrand** [comment]
Decision at TPAC was that section 8.5 could be deleted from webrtc-pc.
