### ISSUE TITLE
pc.close() never fires any events. On purpose?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#565]
[pc.close()](http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-close-void) never [updates the ICE connection state](http://w3c.github.io/webrtc-pc/#update-ice-connection-state) to `"closed"`, and never fires a simple event named [signalingstatechange](http://w3c.github.io/webrtc-pc/#event-signalingstatechange) at *connection* with `"closed"`. Intentional?

The spec seems unclear:

The text on [signalingstatechange](http://w3c.github.io/webrtc-pc/#event-signalingstatechange) says "The signaling state has changed. This state change is the result of either setLocalDescription() or setRemoteDescription() being invoked. " (which seems to exclude close).

But then the explanation for [*onsignalingstatechange* said until recently](https://w3c.github.io/webrtc-pc/archives/20151123/webrtc.html#widl-RTCPeerConnection-onsignalingstatechange) (the removal seems editorial): "It is called any time the RTCPeerConnection signaling state changes, i.e., from a call to setLocalDescription, a call to setRemoteDescription, or code. It does not fire for the initial state change into new." (which seems to suggest it fires for `"closed"`).

If they are to fire, I have questions about whether they're to fire synchronously (in which case we need to deal with reentrancy), or whether they are to be queued in a task, and if the latter whether the setting of the state is to be queued as well.

Arguably, with the merge of https://github.com/w3c/webrtc-pc/pull/552 there is no need to fire these anymore, since the peer connection will never close on you.

Looking for clarification.

**Comment by jan-ivar** [comment]
If they are not to fire, then close should perhaps normatively update the ICE connection state to "closed" (without firing an event)?

**Comment by adam-be** [comment]
I interpret close as an abrupt close that doesn't start any closing procedures and should therefore update state synchronously and never fire any events. As you mention, it doesn't update all the necessary state as it's currently written.

**Comment by ibc** [comment]
Those things happen when the same object fires ~3 different events indicating the same: that the object has been closed.

**Comment by alvestrand** [comment]
Building on the precedent of track.stop() would seem to indicate that we don't fire events - the application already knows that it is closing the PC.

Other opinions?

**Comment by stefhak** [comment]
List message sent: https://lists.w3.org/Archives/Public/public-webrtc/2016Apr/0080.html

**Comment by stefhak** [comment]
There was only one response to the list message so far, and that said it is correct that pc.close() does not lead to any events being fired.

In the current version on github, it is made clear that as soon as close() is called the pc's connectionState is set to closed. @jan-ivar and others: is there a need to update other states as well?

**Comment by jan-ivar** [comment]
@stefhak I suppose *iceConnectionState* is set indirectly by the close text as well? I'm having a bit of trouble following the implicitness of some of the new language, so please bear with me:

I found not "destruction" procedure for the Ice Agent, and the RTCRtpSender [stopped](https://w3c.github.io/webrtc-pc/#sender-stopped) (why not closed?) procedure amounts to this line: "An RTCRtpSender can be stopped, which indicates that it will no longer send any media."

These are the only things "called" wrt senders from `pc.close()` that I see. I say "called" in quotes, because for the senders, it's not really actively specifying an action IMHO with this passive sentence: "All RTCRtpSenders in connection's set of senders are now considered stopped." It's not clear to me if this is referring to the outcome of some previous action (maybe the vague line above telling me I should be "releasing any relevant resources"?), or if this *is* the action.

Overall I'd preferred text specifying what needs to be done, without having to work backwards from what to expect. Unless I'm missing something, it seems an implementer has to:
 1. read its [enum description](https://w3c.github.io/webrtc-pc/#dom-rtciceconnectionstate-closed): "closed = All of the RTCIceTransports are in the closed state.",
 2. and then go to the transport's state's [enum description](https://w3c.github.io/webrtc-pc/#dom-rtcicetransportstate-closed), which reads: "closed = The RTCIceTransport has shut down and is no longer responding to STUN requests."
 3. And then there's the DtlsTransport state [enum description](https://w3c.github.io/webrtc-pc/#idl-def-rtcdtlstransportstate): "closed = The transport has been closed."
 4. And then there's the IceTransport state [enum description](https://rawgit.com/w3c/webrtc-pc/3775a41a87b257f7baaffebadadb17c353568012/webrtc.html#dom-rtcicetransportstate-closed): "closed = The RTCIceTransport has shut down and is no longer responding to STUN requests."
 5. And finally there's the [RTCRtpSender](https://w3c.github.io/webrtc-pc/#idl-def-rtcrtpsender-partial-1) (note buggered link throughout spec) which contains these transports.

I'm not sure how to best do that, as I'm behind on all these new objects unfortunately.

**Comment by jan-ivar** [comment]
The last line was supposed to follow "Are we missing some closing procedures?"

**Comment by jan-ivar** [comment]
Is "stopped" a state or an action (or both)?

**Comment by stefhak** [comment]
@jan-ivar thanks for the input. It looks like the spec needs to be clearer on a lot of things. I think we should close this issue (because to me it seems to be agreement on that pc.close() should not lead to events being fired), but open new issues to cover the things that are unclear.

**Comment by jan-ivar** [comment]
Filed https://github.com/heycam/webidl/issues/127.
