### ISSUE TITLE
Should we specify how addStream()/"addstream event" should behave?

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#568]
The addStream()/"addstream event" API is widely adopted; it has much better browser support than the new addTrack()/addTranceiver() APIs. The intention is that the old API should be polyfilled using supported API points.

We currently specify how, for example, the legacy callback version of createOffer() should behave. The question is if we need to do the same for the addStream()/"addstream event" API to avoid uncertainties like:
* Which version of the  addStream()/"addstream event" API should be supported? Is it OK to say the last spec where it was present?
* The "addstream event" is not trivial to polyfill.

**Comment by jan-ivar** [comment]
Would we be discussing removeStream as well (never implemented in Firefox), or just addStream?

**Comment by mparis** [comment]
gerLocalStreams() and getRemoteStreams() are also interesting (as commented in issue #670 ç)

**Comment by dontcallmedom** [comment]
The interim confirmed the existing consensus that no effort should be put in the spec to document `addStream` et al; having some description in an informal document might be worth someone's effort.

**Comment by stefhak** [comment]
Yes, we should close this one.

**Comment by gsnedders** [comment]
Previously discussed re-adding it in #245.
