### ISSUE TITLE
Document that addIceCandidate(null) means done gathering

### ISSUE THREAD

**Issue by ekr** [w3c/webrtc-pc#569]

**Comment by aboba** [comment]
In the repo (not yet published in an editor's draft) a statement was added in Section 4.3.2.3: 

"This method can also be used to indicate the end of remote candidates
when called with a <code>null</code> value for <code>candidate</code>. "

**Comment by aboba** [comment]
Since a PR exists (and was merged), can this issue be closed?

**Comment by adam-be** [comment]
The issue title talks about "done gathering" while we recently patched the spec to indicate "end of remote candidates". Done gathering is already a state in the spec so perhaps ekr meant "end of remote candidates". @ekr ?

**Comment by aboba** [comment]
Presumably "Done gathering" refers to the remote peer, not local gathering.

**Comment by alvestrand** [comment]
The draft has been updated to reflect that addIceCandidate(null) means "end of candidates".
