### ISSUE TITLE
Mechanisms for populating the contents of RTCRtpSender/Receiver are missing

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#571]
RTCRtpSender/Receiver has a bunch of attributes that, for example, represent the RTP and RTCP transports. These can't be created as the hosting object is created at all times so we need mechanisms (with events?) to update these when the information is available.

**Comment by alvestrand** [comment]
Suggest that we don't create events to surface these changes (to avoid cluttering up the interface), but let them be created as part of the internal algorithms of the PC (the "while the PC is alive, these things go on" parts).

**Comment by alvestrand** [comment]
@taylor-b can you make a suggestion here?
Text that says "do like JSEP section so-and-so says" is fine, if JSEP does say what to do.

**Comment by taylor-b** [comment]
JSEP doesn't currently say what to do but it probably will. See: https://github.com/rtcweb-wg/jsep/issues/261

**Comment by aboba** [comment]
@adam-be We now have text stating that the DTLS (and ICE) transports are created when the setLocalDescription() and setRemoteDescription() promises are resolved. Are there are any other contents of the RtpSender/RtpReceiver that we need to nail down?

**Comment by alvestrand** [comment]
I think we have them all. Please reopen if we find out there's more.
