### ISSUE TITLE
RTCSessionDescription parameters should be readonly.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#573]
The [current language](http://w3c.github.io/webrtc-pc/#idl-def-RTCSessionDescription) implies that content can modify the local description like this:

    pc.localDescription.type = "answer";

which would be a travesty (an interface as an attribute is by reference).

In light of https://github.com/w3c/webrtc-pc/pull/302 I propose we solve this by changing `RTCSessionDescription`'s parameters to `readonly`, and change `createOffer` and `createAnswer` to resolve with `RTCSessionDescriptionInit` instead.

**Comment by alvestrand** [comment]
"which would be a travesty (an interface as an attribute is by reference)."
I can't parse either the grammar of the sentence, what your opinion is, or why you have it.

The localDescription and remoteDescription parameters of the PC are already readonly, which makes the code you suggest illegal (unless I've misunderstood the properties of a readonly attribute).

4.7.2 says "Attributes on this interface are mutable for legacy reasons." I see no compelling reason to change it.

**Comment by adam-be** [comment]
The type attribute was readonly to begin with, but we changed it to allow scripts to, for example, switch from an "answer" to a "pranswer" before setting.

**Comment by jan-ivar** [comment]
I checked with our DOM guys, and `readonly` just means there's no setter for `.localDescription`. The returned interface is still mutable, which seems problematic.

If we do what I suggest then there's no reason to leave them for legacy reasons, since createOffer would return `RTCSessionDescriptionInit`, a dictionary, instead.

**Comment by jan-ivar** [comment]
Also, dictionaries have copy semantics, whereas interfaces do not. So a conforming implementation of the current webidl MUST work like this:

```js
var pc = new RTCPeerConnection();
pc.createDataChannel("dummy");
pc.createOffer().then(offer => pc.setLocalDescription(offer))
.then(() => {
  console.log(pc.localDescription.type); // offer
  pc.localDescription.type = "answer";
  console.log(pc.localDescription.type); // answer
})
.catch(log);
```
Luckily, neither Firefox nor Chrome are compliant.

**Comment by martinthomson** [comment]
You can't have an attribute with a dictionary type.  The right solution is to make `RTCSessionDescription` immutable itself, as @jan-ivar says originally.  That we are all current in flagrant defiance of expectations here isn't that bad, we just make the attributes `readonly` and move on.

**Comment by jan-ivar** [comment]
Yes I just meant remove the legacy mutability. The interfaces are needed forever for the attributes.

**Comment by foolip** [comment]
https://crbug.com/662898 is a bug originating from @philn with Igalia where they (I presume) they tried to follow the spec but ran into trouble.

@philn, if you think the spec should change, can you file a new issue describing the compat constraints?

**Comment by foolip** [comment]
Somewhat relevant is also https://github.com/heycam/webidl/issues/213, but compat demands what it demands. I've asked on the Chromium issue if appear.in might change in the meantime.

@ShijunS, do you know what the Edge behavior is here?

**Comment by philn** [comment]
In WebKit we're following what the spec defined: https://github.com/WebKit/webkit/blob/master/Source/WebCore/Modules/mediastream/RTCSessionDescription.idl#L41

**Comment by foolip** [comment]
Somewhat related is that RTCSessionDescriptionInit's type is required in the spec but not in Gecko or Blink. I'll sprinkle some use counters in Blink, not sure whether reverting the spec change or trying to match the spec is better overall.

**Comment by bzbarsky** [comment]
I'm 90% sure that both Gecko and Blink implemented RTCSessionDescriptionInit before IDL "required" syntax existed, which is why they're not using it yet...

**Comment by foolip** [comment]
Indeed, no surprise there.

Per https://twitter.com/pnormand/status/795938320224309249 appear.in changed their code, so let's hope that most other usage in the wild doesn't depend on the current behavior. (Use counters in https://codereview.chromium.org/2490543002/)

**Comment by ShijunS** [comment]
Re Edge behavior, we have tried to follow the spec before this change.  However, in our implementation, both localDescription and remoteDescription are new interface objects copied from the media stack.  They can change when app calls setLocalDescription() and setRemoteDescription().  But, we don't pass down any app-level change to the lower level.  There is no major conflict to the change of "type" and "sdp" to readonly.

At this point, setLocalDescription() and setRemoteDescription() still require RTCSessionDescription interface object as input, and will throw exception on RTCSessionDescriptionInit.  Similarly, createOffer() and createAnswer() will return RTCSessionDescription interface object rather than RTCSessionDescriptionInit dictionary.  I expect this option will stay until all major browser implementations and websites have migrated according to the latest spec.

**Comment by jan-ivar** [comment]
> https://crbug.com/662898

Looks like we missed a common use-case when we made this read-only:
```js
new RTCSessionDescription().sdp = "v=0\no=- 627673561523047307...";
```

I suppose we could solve it by using a different interface for the attribute... `RTCSessionDescriptionAttr` ?

**Comment by jan-ivar** [comment]
@foolip Or maybe make `RTCSessionDescription` writable again and `Object.freeze()` the specific attributes instead? Is there some webidl for that?

**Comment by bzbarsky** [comment]
Freeze which attributes?  What are their types?

**Comment by jan-ivar** [comment]
[[Frozen]](https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings#Frozen)

**Comment by jan-ivar** [comment]
@bzbarsky pc.[localDescription](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-localdescription) and friends.

**Comment by bzbarsky** [comment]
I don't see how freezing them would do any good.  What would be the goal?

**Comment by jan-ivar** [comment]
@bzbarsky To prevent `pc.localDescription.type = "answer";` as mentioned at the top of this issue.

**Comment by bzbarsky** [comment]
Freezing it won't prevent that, because the setter isn't mutating any state the freezing freezes.

**Comment by jan-ivar** [comment]
Ok @bzbarsky showed me freezing only [works](https://jsfiddle.net/poh7beyy/) on value properties, not setters, so that won't work.

So I revert to the `RTCReadonlySessionDescription` idea, or since the RTCSessionDescription constructor is legacy, we could just ignore the webcompat on this one and hope it is small.
