### ISSUE TITLE
Congruenting about "The negotiation-needed flag is cleared when setLocalDescription"

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#579]
In this paragraph the explanation about the clearing of the negotiation-needed flag is not proper:
If connection's signaling state is now stable, and the negotiation-needed flag is set, the User Agent MUST queue a task to fire a simple event named negotiationneeded at connection and clear the negotiation-needed flag. [1]

It should be the same that this other paragraph:
The negotiation-needed flag is cleared when setLocalDescription is called...[2]

Refs:
[1] http://w3c.github.io/webrtc-pc/#operation
[2] http://w3c.github.io/webrtc-pc/#clearing-negotiation-needed

**Comment by adam-be** [comment]
Can you please elaborate on what you think is wrong. The text in [2] describes what happens in the 'set an RTCDescription' steps in case the flag wasn't cleared earlier in the steps. In 3.2.2 the flag is cleared if some conditions are met.

**Comment by mparis** [comment]
Hello @adam-be,
the point is that tne negotiation-needed flag should only be cleared when the local description is set and the conditions said in [2] are met.

Firing a negotiationneeded event and clearing the flag (as [1] says) makes no sense.

**Comment by adam-be** [comment]
I guess we need to fire event at [1] to give the script a chance to offer the media that wasn't represented in the description just set. But you're right that the way the negotiation flag is defined, it shouldn't be cleared at that point.

**Comment by adam-be** [comment]
@mparis, please take a look at the proposed fix (#797)

**Comment by mparis** [comment]
@adam-be, it seems OK for me ;)
