### ISSUE TITLE
No error defined for addTransceiver() with a bogus track kind

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#581]
We need an error for:
pc.addTransceiver("bogus");

Some possible types from the WebIDL spec:

"InvalidAccessError" 	The object does not support the operation or argument.
"SyntaxError" 	The string did not match the expected pattern.
"NotSupportedError" 	The operation is not supported.
"InvalidModificationError" 	The object can not be modified in this way.
"OperationError" 	The operation failed for an operation-specific reason.

**Comment by dontcallmedom** [comment]
I would add "TypeError" to that list; if MediaStreamTrack.kind was an enum rather than a generic DOMString, this would be what would be triggered.

**Comment by adam-be** [comment]
True

**Comment by alvestrand** [comment]
TypeError is consistent with other behaviors. I think (not sure) that we've specified this elsewhere too.

**Comment by alvestrand** [comment]
Seems that the conclusion is that TypeError is uncontroversial.

**Comment by alvestrand** [comment]
Fixed in #602
