### ISSUE TITLE
Is it OK to call addTransceiver() with a track already added by addTrack()?

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#583]
Or should it have the same check as addTrack has (step 3 at [1])?

[1] https://w3c.github.io/webrtc-pc/archives/20160215/webrtc.html#widl-RTCPeerConnection-addTrack-RTCRtpSender-MediaStreamTrack-track-MediaStream-streams

**Comment by alvestrand** [comment]
Interesting - I thought sending a track twice was allowed in general.
Good question.

**Comment by martinthomson** [comment]
I think that this can be an easy decision.

`addTrack` is the easy-to-use API.  It adds tracks to the PC, so we can treat it like a set; if already present it can throw (as above).

`addTransceiver` is for experts.  It is the way we enable sending twice.

**Comment by stefhak** [comment]
@martinthomson 's proposal makes sense to me. And note that ´replaceTrack´ already enables sending the same track several times if I read the spec correctly.

**Comment by stefhak** [comment]
It seems we agree here, I'd like to bring this up the the interim to confirm.

**Comment by pthatcherg** [comment]
I agree with Martin's proposal.  He's right that one can already call addTransceiver with no track and then call replaceTrack with the same track twice, so disallowing the call to addTransceiver with the same call twice seems very artificial.

**Comment by dontcallmedom** [comment]
Based on the discussion during Friday, there seems to be consensus that no change is needed here (i.e. `addTransceiver` allows adding the same track multiple times).

**Comment by stefhak** [comment]
Yes, we should just close this Issue.

**Comment by mparis** [comment]
Hello,
as discussed in #954, I think that allowing add the same track multiple times makes not sense.

**Comment by fukemy** [comment]
I am using addTrack to get RTPSender, then using this to replaceTrack when I need to switch from videoCall to share screen. Does it's took any problem?
