### ISSUE TITLE
Unclear if RTCRtpTransceiver.stop() acts right away or requires negotiation

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#585]

**Comment by mparis** [comment]
Related to Related with #632

**Comment by aboba** [comment]
The current text says: 
"The sender of this transceiver will no longer send, and the receiver will no longer receive."
That would seem to imply that the change takes effect immediately.  As noted in Issue https://github.com/w3c/webrtc-pc/issues/674, the negotiation-needed flag is set.  After negotiation, the remote peer's transceiver is also stopped, as though transceiver.stop() were called on the remote peer (and an onended event will will occur on the remote receiver.track). 

Does this make sense?

**Comment by mparis** [comment]
I agree,
but moreover we should take into account the issue #597, because stopping an RTCRtpTransceiver must stops the related RTCRtpReceiver.

**Comment by pthatcherg** [comment]
I agree that RtpTransceiver.stop() should take effect immediately, and that it should also cause renegotiation to take effect on the remote RtpTransceiver.  I don't see how anything else could make sense.

**Comment by alvestrand** [comment]
Fixed.
