### ISSUE TITLE
The InvalidParameter error seems to not exist

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#586]
In the current published spec, we have 2 places where we throw an InvalidParameter exception (expired certificates in 4.3 and track already exists in addTrack).

We need to either get the error defined or use some other name. <sigh>

**Comment by dontcallmedom** [comment]
I believe the latest (unpublished) draft doesn't use InvalidParameter, but `InvalidAccessError` instead (cf #472)

**Comment by alvestrand** [comment]
Closing - I wasn't reading the latest version.
