### ISSUE TITLE
replaceTrack: steps of point 9 in paralell?

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#596]
Hello,
If I am not wrong, I do not think that the steps of 9 point of replaceTrack should be done in parallel.

See:
9. Run the following steps in parallel:
    1. Determine if negotiation is needed to transmit withTrack in place of the sender's existing track. Ignore which MediaStream the track resides in and the id attribute of the track in this determination. If negotiation is needed, then reject p with InvalidModificationError and abort these steps.
    2. Have the sender switch seamlessly to transmitting withTrack in place of what it is sending, without negotiating.
    3. Queue a task that sets sender's track attribute to withTrack, and resolves p with undefined.

Refs
http://w3c.github.io/webrtc-pc/#methods-4

**Comment by jan-ivar** [comment]
@mparis are you suggesting `replaceTrack` should not return a promise?

**Comment by alvestrand** [comment]
Can you give an explanation of why?

The term "in parallel" usually means "run the following sequence of steps, not synchronized with the steps below" - in this case, 9.1, 9.2 and 9.3 would occur in order, but may occur before or after step 10.

This seems like normal promise behavior to me.

**Comment by mparis** [comment]
OK, so I misunderstood the meaning, I understood that 9.1, 9.2 and 9.3 can be done in parallel about themselves.
In that case I agree with it.

**Comment by jan-ivar** [comment]
@mparis your confusion is understandable, since there's no link to a definition.

I believe the definition used is the one here: https://html.spec.whatwg.org/#in-parallel

**Comment by mparis** [comment]
@jan-ivar OK, thanks for the pointer ;)
