### ISSUE TITLE
Calling RTCRtpReceiver.track.stop()

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#597]
What happens if RTCRtpReceiver.track.stop() is called? 

Related ORTC Issue: https://github.com/openpeer/ortc/issues/498

**Comment by alvestrand** [comment]
@aboba what do you think should happen?

**Comment by aboba** [comment]
receiver.track.stop() is final, so that RTCRtpReceiver.track cannot be rendered after that. 

However, receiver.track.stop() does not stop the RTCRtpReceiver so that the decoder remains operational and Receiver Reports continue to be sent, even though track cannot be rendered.

**Comment by mparis** [comment]
Hello,
if the track cannot be rendered and it is not reversible, it makes not sense wasting resources (CPU for encoding, decoding, etc.) and network bandwidth.
So, I think that:

- The decoder should be stopped
- A renegotiation should be performed (set negotiation-needed flag , fire a negotiationneeded event, etc.)

In SDP negotiation this media should be set as "sendonly" or "Inactive" to notify the remote peer (_sender_) that the local peer (_receiver_) will not use the media any more.
So the _sender_ can:

- stop the encoder
- stop sending media through the network.

Best!!

**Comment by pthatcherg** [comment]
I agree that the negotiated state of the RtpTransceiver and RtpReceiver should not be affected by stopping a track.  If an application wants to change negotiated state, it should use the RtpTransceiver.  That's what it's for.

However, I don't think we need to specify that the decoder must stay active. An implementation could choose to stop using CPU or other resources if it knows that nothing will use the decoded frames. I think we could just leave that part about the decoder being active out of the spec.

**Comment by alvestrand** [comment]
The observable part of behavior after track stop is that the RTP session continues to send RTCP saying "I got your packets, thank you". Whether the implementation bit-buckets those packets before or after the decoder should be completely up to the implementation; it's not observable.

**Comment by mparis** [comment]
@pthatcherg, if the app uses the RtpTransceiver.stop(), it stops the RtpReceiver and the RtpSender [1].
So, if it only wants to stop one of them, I think that we should add a stop() method in RtpReceiver and in RtpSender.

Refs
[1] http://w3c.github.io/webrtc-pc/#dom-rtcrtptransceiver-stop

**Comment by pthatcherg** [comment]
I agree with what Harald says: we should send back the same RTCP so that nothing appears to hav e changed.  But implementation can throw those in the bit bucket.  But if the spec says "decoder must be active" or something similar, that makes it sound like we can't throw things in the bit bucket.

If you want to stop the RtpSender only and not the RtpReceiver, then one can use RtpTransceiver.setDirection.

**Comment by mparis** [comment]
It seems that there are many ways to do the same and I would like to have a symmetric and intuitive API.
If with RtpTransceiver.setDirection you can stop de RtpSender:

- Could we stop de RtpReceiver with RtpTransceiver.setDirection(SENDONLY)
- Could we stop de RtpTransceiver with RtpTransceiver.setDirection(INACTIVE)

In that cases, does having the stop() method make sense?
On the other hand, the name of stop() method is more descriptive.

**Comment by pthatcherg** [comment]
setDirection() and stop() do very different things.  And the reason we need both is because of the complexities of the SDP state machine.

**Comment by alvestrand** [comment]
Done.
