### ISSUE TITLE
Faulty step 7 in replaceTrack algo

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#598]
Step 7 says
`If sender is not represented in localDescription, then set sender's track attribute to withTrack, and resolve p with undefined.`
However, p is only introduced in step 8.

**Comment by adam-be** [comment]
True. It should return a promise rejected with a TypeError.

**Comment by adam-be** [comment]
> If sender is not represented in localDescription

We don't say what "represented in a description" actually means. We could express this as if the RTCRtpTransceiver, which sender belongs to, is not yet associated with a media description...". That language is defined in JSEP.
