### ISSUE TITLE
Need API to receive mixer to client audio level information for a track 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#6]
See info in 
https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-17#section-12.2.1

**Comment by stefhak** [comment]
Isn't this covered in 5.3.2 of https://w3c.github.io/webrtc-pc/archives/20151006/webrtc.html ? Inclined to close this issue.

**Comment by aboba** [comment]
Yes, it can be closed.

**Comment by stefhak** [comment]
Closing.
