### ISSUE TITLE
addTrack needs to match media types

### ISSUE THREAD

**Issue by ekr** [w3c/webrtc-pc#607]
The current text says
"If an RTCRtpSender exists in connection's set of senders that has never been used to send (the corresponding media description has always had a direction of recvonly or inactive), then set that sender's track to track and return the sender.

Doing so will cause future calls to createOffer and createAnswer to mark the corresponding media description as sendrecv or sendonly, as defined in [JSEP]."

However, you can't addTrack() an audio track to a video transceiver

**Comment by ekr** [comment]
@juberti @pthatcherg

**Comment by adam-be** [comment]
We should add a type check there.
