### ISSUE TITLE
Move degradationPreference from RTCRtpParameters to RTCRtpEncodingParameters

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#608]
@murillo128

This Issue was opened in the ORTC CG but since it affects the WebRTC 1.0 object model, it has been closed there and opened here: 
See: https://github.com/openpeer/ortc/issues/456

**Comment by aboba** [comment]
While encoding parameters like maxBitrate, priority and maxFramerate can differ between encodings, my take is that degradationPreference needs to be consistent between encodings. 

For example, in a simulcast, does it ever make sense to prefer framerate over resolution for the higher resolution stream, and resolution over framerate for the lower resolution stream?

**Comment by jnoring** [comment]
For simulcast does this setting even make sense?  

The big use case for simulcast is running through an MCU/media server, and in that situation, the problem with degrading any individual stream is a single subscriber with poor network quality can drag down a publisher's quality for everyone else receiving that stream.

**Comment by alvestrand** [comment]
This has been discussed (I think it was in Yokohama), and the WG decided to put it in RTCRtpParameters. No compelling new information has been brought to light on the issue.
