### ISSUE TITLE
Split RTCRtpEncodingParameters in RTCRtpEncodingParameters and RTCRtpDecodingParameters 

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#609]
@murillo128

This issue was opened in the ORTC CG, but since it affects WebRTC 1.0, it has been closed there and opened here: 
https://github.com/openpeer/ortc/issues/440

**Comment by aboba** [comment]
PR 629 above clarifies which attributes are used by senders and receivers and whether they are read or read/write.  So it is not a direct response to this issue but hopefully it makes things more clear.

**Comment by alvestrand** [comment]
The chairs don't see any support for changing the IDL as proposed. The table added in #629 seems sufficient.
