### ISSUE TITLE
Typo in Section 4.3.2.2

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#614]
"The pendingRemoteDescription attribute represents a remote RTCSessionDescription that is in the process of being negotiated, completed with any remote candidates that have been supplied via addIceCandidate() since the offer or answer was created. If the RTCPeerConnection is in the stable state, the value is null. This attribute is updated by setLocalDescription()."

[BA] Shouldn't this say "This attribute is updated by setRemoteDescription()"?

**Comment by adam-be** [comment]
Isn't this fixed in the unreleased version already? Time for a new release perhaps. :)

**Comment by aboba** [comment]
@adam-be I submitted a PR for it, so I don't think so.

**Comment by stefhak** [comment]
hm. When I open the latest version on github this seems to be fixed already.
