### ISSUE TITLE
setDirection()

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#619]
@pthatcherg had said (at the end of the thread relating to PR https://github.com/w3c/webrtc-pc/pull/466):

"I thought about this some more, and I think that if we have {direction: "sendrecv"} in the construction of an RtpTransceiver, we probably ought to have .setDirection instead of .activateSender. That would be easier to specify and would allow the application to change direction in any way (sender/receiver active/inactive).

**Comment by martinthomson** [comment]
`setActiveDirection(s)` perhaps?  After all a transceiver is omnidirectional naturally.

**Comment by pthatcherg** [comment]
Then we'd want to call it {activeDirection: "sendrecv"} in addTransceiver
as well.  I'd prefer just calling it "direction" and "setDirection".
Unless we can come up with a better name than "direction".

**Comment by alvestrand** [comment]
Fixed by #620
