### ISSUE TITLE
What should defaultIceServers be if browser has no default servers?

### ISSUE THREAD

**Issue by a2sheppy** [w3c/webrtc-pc#626]
The RTCPeerConnection.defaultIceServers attribute returns a list of ICE servers configured into the browser for use by default. However, the spec doesn't say what the browser should return if it doesn't offer default servers. Should this be null or an empty list?

**Comment by jan-ivar** [comment]
The attribute is not nullable so it cannot be null, therefore it must return an empty list.

**Comment by a2sheppy** [comment]
Fah, of course. I totally missed it reading the WebIDL and was looking
for it in the explanatory text. Thanks for pointing it out.

> The attribute is not nullable so it cannot be null, therefore it must
> return an empty list.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/webrtc-pc/issues/626#issuecomment-217602029>
>

-- 

Sheppy

**Comment by adam-be** [comment]
Let's close this issue. @a2sheppy, please reopen if you disagree.

**Comment by a2sheppy** [comment]
I'm fine with closing it, although I do feel that adding a couple of
words to the text of the spec to more explicitly call this out would be
helpful. But it probably doesn't matter to most of the people who will
actually read the spec. Those of us referring to it while writing
documentation about coding with WebRTC. :)

> Let's close this issue. @a2sheppy <https://github.com/a2sheppy>,
> please reopen if you disagree.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/webrtc-pc/issues/626#issuecomment-218401198>
>

-- 

Sheppy

**Comment by alvestrand** [comment]
Closing as "it is clear".
