### ISSUE TITLE
defaultIceServers adds to the fingerprinting surface

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#627]
[defaultIceServers](http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-defaultIceServers) exposes potentially user-configured browser settings (e.g if users edit `media.peerconnection.default_iceservers` in *about:config* in Firefox), so maybe it deserves a fingerprint warning, like is done elsewhere?

**Comment by alvestrand** [comment]
Thumbprint should be added, yes.
