### ISSUE TITLE
Custom id/label for tracks

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#628]
Hello,
I think that it would be quite interesting allow  the app can add a custom id or label to tracks, and that this info is exposed in the SDP to create the track of the RtpReceiver of the remote peer instead of doing the step 4.4 in [1]

The idea is that apart from the MSID (that is usually an UUID without any meaning) the app can add useful info about this track, as for example: "front_camera", "back_camera", "screen_share", "laptop_microphone", etc.

I see that in the Media Capture description the MediaStreamTrack object has a _label_ attribute [2] that almost match with my idea, the only problem is that it is readonly, so it cannot be customizable by the app.

In addition, I exposed the same problem in discuss-webrtc [3]

Best regards!!

Refs
[1] http://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks
[2] https://w3c.github.io/mediacapture-main/#widl-MediaStreamTrack-label
[3] https://groups.google.com/forum/#!topic/discuss-webrtc/5ZNpqvZHn9E

**Comment by stefhak** [comment]
This has been discussed in the past, and my recollection is that since it is so easy to accompany the session descriptions with extra info (such as "the track with MSID X is the front camera") there is no need to bake this into the SDPs.

**Comment by mparis** [comment]
Hello @stefhak,
we are doing this workaround in some of our apps, but the idea is managing this through the API instead of munging the SDP at all.
If I am not wrong the goal of the new PC API is that, isn't it?

**Comment by adam-be** [comment]
You don't have to parse the SDP to do that. You get the mid from the RTCRtpTransceiver object associated with the track and then you can send some JSON to the other side pairing any info with the mid.

**Comment by alvestrand** [comment]
The chairs don't see any support for this idea so far.

**Comment by mparis** [comment]
OK, in that case I will close the issue.
Thanks!!
