### ISSUE TITLE
How local peer learns of transceiver.stop() on remote peer

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#632]
What event occurs on the remote peer when transceiver.stop() is called on the local peer? Presumably the negotiation-needed flag is set on the local peer, there is an O/A exchange and somehow the application on the remote peer finds out that the transceiver has been stopped.

**Comment by aboba** [comment]
From @mparis 

I think that an _ended_ event should happen in the track of the related remote RtpReceiver as described in [1], [2] and [3].

Best regards!!

Refs
[1] http://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks
[2] http://w3c.github.io/webrtc-pc/#mediastreamtrack
[3] http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-removeTrack-void-RTCRtpSender-sender

**Comment by jesup** [comment]
"I think that an ended event should happen in the track of the related remote RtpReceiver as described in"

Ah, but how does the far side know that?  Either signaling (negotiationNeeded), or perhaps RTCP BYE

**Comment by mparis** [comment]
I guess that using signalling, that is, with a new SDP negotiation.

**Comment by mparis** [comment]
Related with #585

**Comment by alvestrand** [comment]
The doc should be updated to say that stop() causes negotiation-needed to be set, I think.

**Comment by mparis** [comment]
@alvestrand +1

**Comment by alvestrand** [comment]
Closing as dup of #585
