### ISSUE TITLE
public negotiation-needed flag as readonly

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#645]
Hello,
I think that public the negotiationNeeded flag in PC [1] as a readonly attribute is quite useful for the applications.
What do you think?

Refs
[1] http://w3c.github.io/webrtc-pc/#interface-definition

**Comment by alvestrand** [comment]
Are you proposing to expose the (currently internal) negotiation-needed flag, are you proposing to expose a new flag that exposes whether or not the browser intends to fire "negotiationneeded" event, or are you proposing to expose a new flag that exposes whether or not "negotiationneeded" has been fired?

I note that there seems to be a piece that's at odds with section 4.8 "Session negotiation model", which is in section 4.3.1 on the "negotiationneeded" event:
 
"If connection's signaling state is now stable, and the negotiation-needed flag is set, the User Agent must queue a task to fire a simple event named negotiationneeded at connection and clear the negotiation-needed flag."

Section 4.8 says it's only cleared when set-local-description is called with a satisfactory offer or answer.

**Comment by alvestrand** [comment]
Pinging @adam-be as the negotiation expert.

**Comment by mparis** [comment]
Hello @alvestrand ,
I am proposing to expose the (currently internal) negotiation-needed flag.

**Comment by alvestrand** [comment]
Assigning to Adam. There's some cleanup in the works that concerns this flag too.

**Comment by aboba** [comment]
Not sure what a public flag would be used for - the negotiation-needed event seems like a better approach.

**Comment by mparis** [comment]
@aboba, having a public flag does not remove the event, both are complementary.
Why the flag is useful, even needed?

- It is **needed** if the app subscribes to the event **after** it fired. To fix this case the app should follow the next pattern:

1. Subscribe to the event
2. Check if the flag is set to perform the negotiation

This may make no sense in a web client or in a monothread app, but yes if you are implementing this API in a MediaServer that exposes an RPC, even more if it is distributed.

- It is _useful_ because the app has not to be care about keep the state. Usual case:

1. pc.addTrack()
  This fires the negotiation-needed event, but I do not want to negotiate now because I want to add more tracks
2. pc.addTrack()
  The event is not fired because has been fired before
3. if (pc.negotiationNeeded) {pc.createOffer()}

In addition, there are use cases where this flag eases to much the logic of the app. Summarily, a local PC that receives the media from a remote PC and its remote tracks are added to other local PCs (or not) depending on the app state, the user preferences, etc. In this case, the app only has to check the flag ;).

**Comment by adam-be** [comment]
@mparis, I'm not convinced that it's a big win to make this flag public.

To start with, the script always creates the RTCPeerConnection using the constructor. I.e. an instance is never delivered from some event or such, so there's always an opportunity to register for the event before it's triggered the first time.

Secondly, the flag sometimes get set when state isn't stable in which case it's not wise to start a new negotiation.

**Comment by mparis** [comment]
As I exposed in my last post, from my point of view and talking with some developer, it makes sense and ease the development in the cases I told you.

However, I missed that the internal flag can be set when state isn't stable.
Taking this into account, the point is exposing a public flag that is set if a negotiation is needed.

**Comment by alvestrand** [comment]
Seems to be easy to polyfill:

pc.onnegotiatinonneeded = _ => { pc.my_negotiation_needed_flag = true; }

**Comment by alvestrand** [comment]
Resolution at TPAC: Do not add this.

**Comment by mparis** [comment]
And when do you set the flag to false?

**Comment by alvestrand** [comment]
When your createOffer returns?

**Comment by mparis** [comment]
It should be when setLocalDescription and all conditions to be set to false meet.
That is, you has to keep the same complicated state machine in the app level than in the UA: almost impossible, so I think that it should be provided as a public flag by PeerConnection.

Moreover, it should be trivial.
Why did you decide not to add it? Dis I miss anything?
