### ISSUE TITLE
addTransceiver/addTrack: need to be async?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#651]
addTransceiver() and addTrack() methods produce objects (e.g. RtpSender/RtpReceiver) that have DTLS transport attributes.  However currently it is not clear if the DTLS transport objects have certificates created when the methods return. Should the methods be async? 

Detailed post: https://lists.w3.org/Archives/Public/public-webrtc/2016May/0100.html

**Comment by taylor-b** [comment]
Even ignoring `addTransceiver` and `addTrack`, `setRemoteDescription(offer)` will result in `RtpTransceiver`s being created, with transports that may not yet have certificates, correct?

If so, I don't think these methods need to be async. The `DtlsTransport` just needs to be allowed to be in a state without a certificate.

As a sidenote, I feel like `transport` should be nullable, and populated only when a description is set. In my mental model, it's `setLocalDescription`/`setRemoteDescription` that create (or destroy) transports, set their parameters, and associate them with senders.

**Comment by aboba** [comment]
@taylor-b Does this sound right?
When setRemoteDescription(offer) returns, DTLS/ICE transports exist but DTLS transports may not have certificates. When createAnswer() returns, certificate(s) must exist (and DTLS/ICE transports, because these are created prior to calling createAnswer()).  When createOffer() returns, certificate(s) must exist, but DTLS/ICE transports do not.  When setLocalDescription() returns, DTLS /ICE transports exist as do certificates (because certificates are always created prior to calling setLocalDescription()).  

This begs another question:  If a RtpSender/RtpReceiver is created with a nullable transport attribute, how does the application find out when the transport attribute becomes non-null?  Is there an event?

**Comment by taylor-b** [comment]
That sounds right to me.

To answer your question: If we proceed with the algorithm you suggest, the transport attribute should only become non-null as part of the steps for `setLocalDescription` or `setRemoteDescription`. So the application could check what changed when the promise is resolved.

Of course, there are many other things that could change as a result of setting a description, so it would be convenient to developers if we provide events. In a separate thread we've brought up adding an "ontransceiveradded" event; we could easily add an "ondtlstransportadded" event too.

**Comment by adam-be** [comment]
Related issue: #571

**Comment by alvestrand** [comment]
See discussion on the list too (short: I don't see a need for async here)

**Comment by alvestrand** [comment]
Conclusion at interim was that it did not need to be async.
