### ISSUE TITLE
Need JSEP reference for general RTCPeerConnection description

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#654]
Section 4.3 (RTCPeerConnection Interface) says 

"The general operation of the RTCPeerConnection is described in [JSEP]."

The reference should be made more specific, perhaps to section 4 of JSEP.

This is a work item for issue #337.

**Comment by dontcallmedom** [comment]
I personally don't think that in such a generic reference, a more specific section is needed

**Comment by burnburn** [comment]
Yeah, I tend to agree with you since *all* of JSEP is about RTCPeerConnection, but it has the advantage of making clear that we didn't forget to provide a more specific reference.  Perhaps a better approach is to reword the sentence slightly, along the lines of "The [JSEP] specification, as a whole, describes the details of how the RTCPeerConnection operates.  References to specific subsections of [JSEP] are provided as appropriate."  @dontcallmedom , what do you think?

**Comment by dontcallmedom** [comment]
SGTM
