### ISSUE TITLE
Update JSEP reference to 5.8

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#655]
In section 4.3.1 there is the following:

"If description is set as a remote description with new media descriptions [JSEP], the User Agent MUST dispatch a receiver for all new media descriptions."

The reference needs to be updated to point to section 5.8, possibly after the updates in issue #566.

This is a work item for issue #337.

**Comment by burnburn** [comment]
Will update after issue #566 resolves.

**Comment by aboba** [comment]
@burnburn Looking at https://rawgit.com/w3c/webrtc-pc/master/webrtc.html#operation the reference now points to JSEP Section 5.7.2.   This looks correct.  Can we close this issue?
