### ISSUE TITLE
Update JSEP reference to canTrickleIceCandidates

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#656]
Part of the description for canTrickleIceCandidates says

"The value is determined based on whether a remote description indicates support for trickle ICE, as defined in [JSEP] (section 4.1.11.)."

The reference should point to https://rtcweb-wg.github.io/jsep/#rfc.section.4.1.14

This is a work item for issue #337.

**Comment by dontcallmedom** [comment]
The reference looks already correctly set (it points to 4.1.11, since that's the relevant section number in the latest published JSEP draft; when that gets updated, updating the JSEP map file will make it point to the new section number of 4.1.14)
