### ISSUE TITLE
Update JSEP reference to provisional answers

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#657]
Part of the description for createAnswer says

"An answer can be marked as provisional, as described in [JSEP] (section 4.1.4.1.), by setting the type to pranswer."

The reference should point to https://rtcweb-wg.github.io/jsep/#rfc.section.4.1.7.1

This is a work item for issue #337.

**Comment by dontcallmedom** [comment]
The reference is already correctly set — the section number will be updated to match the latest JSEP toc when the latest JSEP draft is published and the map updated.
