### ISSUE TITLE
Update JSEP reference to rollback

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#660]
Part of the description for RTCSdpType "rollback" says

"If the mid value of an RTCRtpTransceiver was set to a non-null value by an RTCSessionDescription that is rolled back, the mid value will be set back to null, as defined by [JSEP] (section 4.1.4.2.)."

The reference should point to https://rtcweb-wg.github.io/jsep/#rfc.section.4.1.7.2

This is a work item for issue #337.

**Comment by dontcallmedom** [comment]
The reference is already correctly set — the section number will be updated to match the latest JSEP toc when the latest JSEP draft is published and the map updated.
