### ISSUE TITLE
Add informative table of all things that can cause negotiationneeded

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#661]
Just a suggestion to help developers:  consider adding an informative table that links to/points to all the places in the spec where we say negotiationneeded can be triggered.  A nuisance to maintain, but really useful for spec readers.

**Comment by burnburn** [comment]
I will get to writing this non-normative table after my other Issues/PRs (later).

**Comment by henbos** [comment]
We think this isn't needed and has a risk of getting out of sync with the spec. Now we have a perfect negotiation example, so hopefully by the end of it you don't even care :)
