### ISSUE TITLE
RTCPeerConnection.addTransceiver:  add streams arg

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#667]
Hello,
I think that RTCPeerConnection.addTransceiver [1] should have a _streams_ arg as addTrack [2] to can say which are the MediaStreams related with the MediaStreamTrack.
At this point, does make sense having both methods? Could we only provide addTransceiver and remove  addTrack?

Refs
[1] http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtransceiver
[2] http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack

**Comment by adam-be** [comment]
You can add streams in the second argument dictionary.

```
dictionary RTCRtpTransceiverInit {
    RTCRtpTransceiverDirection         direction = "sendrecv";
    sequence<MediaStream>              streams;
    sequence<RTCRtpEncodingParameters> sendEncodings;
};
```

**Comment by mparis** [comment]
@adam-be, you are right.
I missed this detail, thanks!!
