### ISSUE TITLE
RTCPeerConnection: add methods to get local and remote MediaStreams

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#670]
Hello,
I am missing a way of getting the local and remote MediaStreams in RTCPeerConnection [1].
If I am not wrong, with the current API we can only get the local and remote MediaStreamTracks from the RtpSenders and RtpReceivers, but not their related MediaStreams.

What do you think about adding getLocalStreams() and getRemoteStreams()?
Could having a ref to the MediaStream in the MediaSreamTrack be useful?

Refs
[1] http://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions

**Comment by alvestrand** [comment]
This should be covered under #568. Closing as duplicate.
