### ISSUE TITLE
Processing remote MediaStreamTracks without MediaStreams info

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#671]
Hello,
what happens when processing a remothe SDP [1] if there is only the ID of the MediaStreamTrack, but there is not any ID about the MediaStreams which are related to the MediaStreamTrack?

Should the agent use a _default_ MediaStream and add all MediaStreamTracks without any related MedaStream?

Refs
[1] http://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks

**Comment by alvestrand** [comment]
The answer is in the MSID spec. (details forthcoming)

**Comment by elagerway** [comment]
@alvestrand just curious, are you referring to details that you are coming up with or are you specifically pointing mparis to watch the MSID spec for updates?

**Comment by alvestrand** [comment]
Checking the msid spec, the first element is the stream and the second is the track. It's not possible to signal a track without signalling a stream.
This suggests that this question needs answering (we don't have an answer).

**Comment by stefhak** [comment]
Could some reserved word be used for 'no stream' in the stream element in msid? Like "none"?

**Comment by alvestrand** [comment]
This is the obvious solution. SDP syntax doesn't allow empty strings or quoting.

"-" would also do fine. It seems JSEP currently specifies that MSID values are parsed and stored, but doesn't go into what happens next.

Section 5.1.1 "Processing Remote MediaStreamTracks", bullet 3 seems to be the right point.

If we want it in JSEP, the relevant point is in section 5.6.2 "Media Section Parsing", bullet 12 under "If ... RTP".

And there's still the option of updating MSID....

@juberti any opinions on where it should go?

**Comment by alvestrand** [comment]
Followup: I filed these:
https://github.com/alvestrand/rtcweb-msid/issues/15
https://github.com/alvestrand/rtcweb-msid/pull/16
People who care about this issue need to comment on the IETF mmusic WG's mailing list - it is Very Good if people do, so that it's clear to the chairs that this is a needed solution to a real problem.
Pinging @juberti @fluffy @pthatcherg to comment (since they're already mmusic-actives).

**Comment by dontcallmedom** [comment]
Now that https://github.com/alvestrand/rtcweb-msid/pull/16 has been merged, can this be closed @alvestrand ?

**Comment by alvestrand** [comment]
Yes.
Closing as "fixed by update to IETF spec".
