### ISSUE TITLE
Support assertions that identify the recipient

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#678]
When imitating communications between two parties, some systems use assertions that only identify the initiator. However, these assertions have a security weakness in that they can be cut and pasted and sent to many different receiving parties because the intended recipient of the session is not identified in the assertion. Many identity systems, such as the STIR work at IETF, protect against that by including the intended recipient in the assertion. 

The current WebRTC spec can be used with the first type of identity systems but does not well suited for the the second type. To improve the security, the GenerateAssertionCallback  ( https://w3c.github.io/webrtc-pc/#idl-def-generateassertioncallback ) should be extended to allow and option recipientNameHint similar to the existing usernameHint ). 

This will make WebRTC fit into STIR as well as other identity assertion systems without loosing any existing functionally.

**Comment by fluffy** [comment]
Note in cases where one was using peerIdentity, the recipientNameHint would often be the same as the peerIdentity option in https://w3c.github.io/webrtc-pc/#isolated-pc so perhaps peerIdentityHint would be a better name

**Comment by martinthomson** [comment]
That is correct. I am on vacation this week,but i will get to it.

**Comment by alvestrand** [comment]
Ping?

**Comment by fluffy** [comment]
Any update on this one ?

**Comment by Pierpaolo1992** [comment]
sorry if i resume this issue so long after... i'm looking for a WebRTC IdP. Could i use STIR? If yes, in which way? I use Janus as WebRTC gateway.

**Comment by alvestrand** [comment]
Please use the mailing list (public-webrtc@w3.org) for spec issues unrelated to a specific bug, and use discuss-webrtc@googlegroups.com for discussion about webrtc implementations.
The bug tracker's closed issues isn't a good mailing list.
