### ISSUE TITLE
Proper JSEP reference for sendEncodings in subsequent offers?

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#684]
In addTransceiver() in 5.1 it says
"If init.sendEncodings is set, then subsequent calls to createOffer will be configured to send with multiple RTP encodings as defined in \[JSEP\] (section 5.2.2.)."

A neophyte going to JSEP section 5.2.2 would likely be confused since the details of how to apply encoding info to a description is actually in 5.2.1 (and virtually nothing in 5.2.2), although the reference is technically correct since 5.2.2 describes *changes from* 5.2.1 in dealing with subsequent offers.

Would it be better to reference both sections, say as "(section 5.2.2 and 5.2.1)", with 5.2.1 listed second just as a hint for those who are confused at finding limited information about multiple encodings in 5.2.2?

This is a work item for issue #337.

**Comment by dontcallmedom** [comment]
sounds like a good approach to me.

**Comment by aboba** [comment]
Sounds good to me.

**Comment by alvestrand** [comment]
We agree on the proposed approach (and that JSEP could be clearer on the subject).

**Comment by burnburn** [comment]
fixed in commit 0ef34c3b939ea86f5744a9b0e85e1b00c1c7dc84
