### ISSUE TITLE
Update JSEP reference for receipt of multiple RTP encodings

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#685]
In section 5.1 addTransceiver() it says

'When setRemoteDescription is called with a corresponding remote description that is able to receive multiple RTP encodings as defined in \[JSEP\], the RTCRtpSender may send multiple RTP encodings and the parameters retrieved via the transceiver’s sender.getParameters() will reflect the encodings negotiated.'

JSEP issue https://github.com/rtcweb-wg/jsep/issues/285 has been raised to add an appropriate anchor.  When this is done the reference here should be updated.

This is a work item for issue #337.

**Comment by alvestrand** [comment]
The specification of signalling that you can recevie multiple encodings seems to belong in either the RID spec or the JSEP spec.
A decision was made some time back that WebRTC entities are only required to support receiving one incoming stream, but all the specs need to be clear on what that means in practice.

**Comment by alvestrand** [comment]
Assigning Bernard to liaise with IETF to see how this can be worked out.

**Comment by aboba** [comment]
Message posted to IETF RTCWEB mailing list: https://www.ietf.org/mail-archive/web/rtcweb/current/msg15890.html

**Comment by aboba** [comment]
@burnburn @alvestrand

Discussion on the IETF RTCWEB list seems to confirm that it is not the intend for WebRTC 1.0 to support reception of simulcast by browsers, only sending of simulcast.

So the SDP consumed by setRemoteDescription() that indicates the ability to receive simulcast is not created by a browser implementing WebRTC 1.0.  Rather, it created by a Selective Forwarding Unit (SFU),  which will receive multiple encodings, but only forward a single stream to the browser. Therefore I don't think that the reference should be to JSEP, because the browser will not emit SDP indicating the ability to receive simulcast. The reference should instead be to https://tools.ietf.org/html/draft-ietf-mmusic-rid (possibly Section 6.2.2), which describes the SDP that an SFU should emit.

**Comment by alvestrand** [comment]
@aboba I disagree.
The reference should be to JSEP, and JSEP should say how to handle SDP.
If JSEP has assumptions in it that say "we're only parsing SDP that is produced by a JSEP-compliant unit", then JSEP is wrong and needs fixing.

**Comment by aboba** [comment]
Consensus at the virtual interim was that an update to JSEP is required.  A PR will be submitted once the update is posted.

**Comment by fluffy** [comment]
Who should the JSEP authors be expecting the PR from ?

**Comment by alvestrand** [comment]
The issue was discussed at the IETF in Berlin.

**Comment by fluffy** [comment]
My understanding is that  we do not require browsers to implement receiving simulcast, if some device (including a browses) wants to implement receiving simulcast that is fine. Also JSEP does not assume that SDP the browser receives was generated by something that follows the rules that JSEP requires when generating SDP. So something that implements all of JSEP can receive SDP from anything that produces valid SDP and the appropriate negotiation will happen.

**Comment by pthatcherg** [comment]
My understanding is that:

1. WebRTC 1.0 endpoints can receive (if the endpoint supports it well,
which I know some do not) more than one source RTP streams into a single
RtpReceiver as long as it's only "one at a time", AKA switching. Once we
right down the demux rules for JSEP, this should become more obvious.   The
only issue there that I know of is dealing with clock synchronization
between SSRCs.

2.  WebRTC 1.0 endpoints cannot receive multiple source RTP streams
simultaneously into a single RtpReceiver.


So, it depends on your definition of "receive simulcast".  If it's "receive
one stream at a time being forwarded by an SFU that's receiving many" (#1),
then yes.  If it's "receive many streams at a time" (#2), then no.

**Comment by aboba** [comment]
A comment: https://lists.w3.org/Archives/Public/public-webrtc/2016Aug/0040.html:

**Comment by alvestrand** [comment]
Leaving open because JSEP update is not yet completed. We may have to adjust because of JSEP.

**Comment by aboba** [comment]
This is now discussed in Section 3.7 of JSEP.

**Comment by aboba** [comment]
Can we close this now?
