### ISSUE TITLE
Clarify reasoning behind and mitigation of privacy issues (PING review)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#687]
From the PING review:

> In reading privacy/security considerations of the spec, the PING group recognized the various issues, but it was not always clear how issues were solved or mitigated. Can you provide more documentation on countermeasures and why certain decisions were made? Examples:  the concrete reasons to accept changes to the same-origin policy. (e.g., not only because websocket does it.)

**Comment by dontcallmedom** [comment]
> Related items that were of concern, for which a response would be
helpful: leaking of local IP addresses; change to the same-origin policy
because of p2p communication; client-side or device id leakage; ad
networks using WebRTC for accessing IP address.

(I think the above is meant to complete the initial comment — otherwise, I'm not sure what's the question is)

**Comment by alvestrand** [comment]
Thanks - without the comment, I'd close the question as "no answer possible"; with the comment, I think there are 4 comments to be addressed. Should we split this into 4 issues?

**Comment by dontcallmedom** [comment]
So, here is my attempt at documenting design decisions and possible counter-measures for the 4 items mentioned above - @alvestrand does that sound about right?

# Leaking of local IP addresses

As described in the spec and the in the [supporting IETF spec](https://datatracker.ietf.org/doc/draft-ietf-rtcweb-ip-handling/), browsers can operate in 4 modes with regard to their policy of disclosing "local" IP addresses. The 4 modes represent different possible trade-offs users may want to make between limiting exposure of these IP addresses and performance of audio/video communications.
So what drove the design was the recognition that different users will want to make different trade-offs for different Web sites, and the proposed default mode of operation (mode 2 in the IETF document) offers a balance where no sensitive information gets leaked prior to consent on camera/mike usage, while still allowing quicker network path when consent has been granted.
The proposed mitigation is to let users select a stricter (or looser) mode via their user agent.

# Change to the same-origin policy because of p2p communication
WebRTC does not change the same-origin policy: an origin cannot obtain data from another origin using the datachannel API.
WebRTC does offer a more direct transmission path from one browser to another peer (a browser or not) where the server attached to a given origin only needs to be used once for establishing the connection rather than serving as a relay (which is what WebSockets or even XHR enables). But the existence of that transmission path does not alter the restrictions of data across origins.
As a result, it's not clear that this feature needs any specific mitigation.

# Client-side or device id leakage
Beyond IP addresses (addressed above), the usage of the WebRTC API exposes more detailed and client-bound information about underlying software and hardware.
The expected mitigation for this risk is the one used for other similar features: browsers can support a mode where they disclose a uniform set of information instead of the one that would enable the more customized experience.

# Ad networks using WebRTC for accessing IP address
We believe that implementation of the mode 2 described above as the default mode of operation will severely limit that practice since only a limited number of IP addresses will be disclosed by default.

**Comment by dontcallmedom** [comment]
ping @alvestrand

**Comment by alvestrand** [comment]
Under same-origin policy, it should probably read "an origin cannot obtain data from another origin using the datachannel API without its cooperation".

This is so that we don't get hammered for inaccuracy - it's easy to set up a datachannel between two tabs in the same browser where the two tabs have different origins, but it requires the active cooperation of both origins.

**Comment by dontcallmedom** [comment]
updated write up accordingly

**Comment by dontcallmedom** [comment]
sent at https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0013.html

**Comment by stefhak** [comment]
@dontcallmedom any feedback on your write up?

**Comment by dontcallmedom** [comment]
having not heard back in a 4 weeks, I think it's fine to close the issue now; if we hear back from them later, we can always reconsider.
