### ISSUE TITLE
Indicators of usage and data flow (PING review)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#688]
From the PING review:

> As a user, I have concerns about wanting to know, for example, in
> WebEx: when I am speaking and where the data is going. Which items
> (indicators) are going to left up to the application, and which in the
> user agent? For example, camera light should be on when the camera is
> active--that shouldn't be left up to the application.
> What would be helpful here is to describe what kind of risks exist and
> how they are prevented or solved.

**Comment by dontcallmedom** [comment]
Waiting for confirmation from PING that we can close this as belonging to Media Capture and Streams https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0008.html

**Comment by stefhak** [comment]
@dontcallmedom any update?

**Comment by dontcallmedom** [comment]
since we haven't heard back, closing this issue
