### ISSUE TITLE
Information available prior to permission prompt (PING review)

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#690]
from the PING review:

> What information is available prior to a permission prompt? Example: for a Tor activist user, what would they do when they might have to choose between communicating and revealing sensitive local information?

**Comment by alvestrand** [comment]
This issue seems to conflate Media Capture (which has a prompt) with WebRTC peer connections (which don't).

**Comment by dontcallmedom** [comment]
Well, the fact that access to "hidden" IP addresses is now tied to permission granted via Media Capture makes it complicated.

I think a Tor activist user would have its browser configured to use mode 2, 3, or 4 of [RTCWEB-IP-HANDLING](https://tools.ietf.org/html/draft-shieh-rtcweb-ip-handling-00#section-4) where no "hidden" IP address gets revealed.

But more to the point, I think the spec already [addresses this](http://w3c.github.io/webrtc-pc/webrtc.html#revealing-ip-addresses):
> Mitigating the exposure of IP addresses to the application itself requires limiting the IP addresses that can be used, which will impact the ability to communicate on the most direct path between endpoints. Browsers are encouraged to provide appropriate controls for deciding which IP addresses are made available to applications, based on the security posture desired by the user. The choice of which addresses to expose is controlled by local policy (see [RTCWEB-IP-HANDLING] for details).

So I guess I would suggest we get back to PING asking what additional information they would like to see in the spec (and why).

**Comment by gregnorc** [comment]
Hi all, 

I'm happy to chat on here, but if you want all of PING to give feedback, you may want to consider posting to the PING mailing list.

At the high level, personally I'd love to see the spec talk a little more about what their default mode is. (If you are going to use mode 3 or 4, great. If not, I'd like to see a really strong case for why.)

**Comment by dontcallmedom** [comment]
Waiting for feedback from PING at https://lists.w3.org/Archives/Public/public-privacy/2017JanMar/0008.html

**Comment by stefhak** [comment]
@dontcallmedom any update?

**Comment by dontcallmedom** [comment]
since we haven't heard back, closing this issue
