### ISSUE TITLE
JSEP/WebRTC mismatch on empty remote MID

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#698]
In the description for the mid attribute of RTCRtpTransceiver it says "If there is no MID value in the remote SDP, and no MID value was previously assigned, a random value will be created for the mid as described in \[JSEP] (section 3.5.2.1.) when the remote SDP is set".
The text in that section of JSEP (https://rtcweb-wg.github.io/jsep/#rfc.section.3.5.2.1) doesn't talk about assignment of a random value.

**Comment by stefhak** [comment]
Related to #578

**Comment by adam-be** [comment]
I can't seem to find any text in JSEP about generating an mid. I did however find the text below in the section about generating an initial answer.

> Each m= section MUST include the following:
> * If and only if present in the offer, an "a=mid" line, as specified in [RFC5888], Section 9.1. The "mid" > value MUST match that specified in the offer.

I'll bring this up in JSEP

**Comment by alvestrand** [comment]
Not yet linked to a released JSEP's section number. Leaving open.
