### ISSUE TITLE
Add a ufrag attribute to the RTCIceCandidate structure to indicate which ICE context

### ISSUE THREAD

**Issue by ekr** [w3c/webrtc-pc#726]
At IETF 95, we agreed that we should have the ufrag included with ICE candidates so you could disambiguate candidates and end-of-candidates from different ICE generations (restarts). We should
1. Add ufrag to RTCIceCandidate
2. Add ufrag to one of the things that the serializer emits

We should also consider modifying the "done gathering marker" to be not RTCIceCandidate = null but rather RTCIceCandidate = { mid, null} or something.

**Comment by juberti** [comment]
{mid, ufrag, null}

**Comment by ekr** [comment]
thanks.
