### ISSUE TITLE
replaceTrack with the previous one as ended

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#732]
Hello,
what should happen if we try to replaceTrack of an ended track?

If I am not wrong, [1] and [2] say that if a MediaStreamTrack is ended a renegotiation should be performed removing its info from the SDP

On the other hand, replaceTrack doc [2] says that a renegotiation must not be performed:
"Determine if negotiation is needed to transmit withTrack in place of the sender's existing track. Ignore which MediaStream the track resides in and the id attribute of the track in this determination. If negotiation is needed, then reject p with InvalidModificationError and abort these steps. "

So:
1.  if the previous track is ended should a renegotiation take place to notice the peer?
2. Or it cannot take place because the previous track must be in LIVE state?:
    "Attempts to replace the track **being sent** with another track provided, without renegotiation."

Refs
[1] http://w3c.github.io/webrtc-pc/#setting-negotiation-needed
[2] http://w3c.github.io/webrtc-pc/#clearing-negotiation-needed
[3] http://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-replacetrack

**Comment by alvestrand** [comment]
Good topic for next interim meeting, if we have time.

**Comment by aboba** [comment]
Do we really need a negotiation when a MediaStreamTrack is ended?

**Comment by jesup** [comment]
I think it should be up to the application to decide what to do in that case.  The track is still attached; we just won't get any more frames from it, and as benard said, the application could instead ReplaceTrack it  with another device, or with a canvas with "user disconnected their camera", etc - or just leave it.

**Comment by adam-be** [comment]
I like @jesup's suggestion where the app can decide to send something else if a track ends for some reason. That would mean treating the track as muted until some action is taken (negotiation or replaceTrack).

One approach to make is usable would be to make sure the track "ended" event is fired before the "negotiationneeded" event. That way the app can do the replaceTrack call and have the negotiation needed flag cleared by that action (and prevent a negotiation that would stop the sender and make future replaceTrack calls throw).

**Comment by alvestrand** [comment]
The critical point is whether the track on the receiving side is supposed to be ended or not. If it's ended, it can't resurrect (by the semantics of "ended") - and the information that it's ended and not merely paused has to be sent to the receiver somehow. (-msid gives 3 ways to do it - BYE, SSRC timeout and signalling).
If it's not supposed to be "ended", replacing it with a non-ended track is completely OK in terms of the model. If it's supposed to be "ended", it's not OK.

**Comment by adam-be** [comment]
Yes, for this to work, we need to treat it as muted until the app decides what to do. Either replace the track or negotiate as ended.

**Comment by aboba** [comment]
I think we need to distinguish calling RTCRtpReceiver.track.stop() from stopping the RTCRtpReceiver itself.  Section 5.3 says that calling RTCRtpReceiver.track.stop() does not stop the sending of Receiver Reports.  This suggests that RTCRtpTransceiver.stop() causes a BYE to be sent (as well as setting the negotiation-needed flag).  Once transceiver.stop() is called,  transceiver.sender.replaceTrack() will throw an exception, but before then, calling sender.replaceTrack() should still work.

**Comment by alvestrand** [comment]
BYE gets sent from sender to receiver, so that would either be sent after RTCRtpSender.track.stop() or <RTPTransceiver-containing-sender>.stop(), wouldn't it?

**Comment by aboba** [comment]
IMHO, RTCRtpSender.track.stop() does not stop the encoder, just as RTCRtpReceiver.track.stop won't stop the decoder, so I'd say it doesn't cause a BYE to be sent.

There is no RTCRtpSender or RTCRtpReceiver stop() method, only RTCRtpTransceiver.stop().

**Comment by aboba** [comment]
With the PR merged, can we close this issue?

**Comment by mparis** [comment]
I agree with the solution, great work and thanks!! ;)
(Sorry for the delayed response, but I was offline)
