### ISSUE TITLE
Automatically open data channel when connections are established

### ISSUE THREAD

**Issue by tresdin** [w3c/webrtc-pc#735]
I personally think data channel should be opened by default. Developers should not handle this task themselves. There are not much reasons to open a webrtc connection without using the data channel.

And also, after connections are established, webrtc should handle itself every renegotiations via the default data channel.

**Comment by jan-ivar** [comment]
Do you mean *created* or *opened*? AFAIK they're opened automatically (if created).

Data channels are not free, they take up an extra port (~4 extra ICE candidates firing).

Also, how would you get the data channel object?

**Comment by jan-ivar** [comment]
> after connections are established, webrtc should handle itself every renegotiations via the default data channel.

I hear you on this. I proposed something similar [last year](https://lists.w3.org/Archives/Public/public-webrtc/2015May/0195.html). Unfortunately it was [struck down](https://lists.w3.org/Archives/Public/public-webrtc/2015Jun/0007.html), mostly for failing the "minimal API" test. Luckily, it's easily polyfilled.

**Comment by tresdin** [comment]
@jan-ivar 
> Do you mean created or opened?

I actually mean `created`. Or in other words, creating data channels should not be an option in my opinion. 

> Also, how would you get the data channel object?

I think it could be attached with peer connection objects.

> I hear you on this. I proposed something similar last year. Unfortunately it was struck down, mostly for failing the "minimal API" test. Luckily, it's easily polyfilled.

My aim is to reduce the complexity of WebRTC. If this change is implemented, we would no longer need the `onnegotiationeeded` event. That would make WebRTC a little more approachable to beginners.

I got a feeling that WebRTC team are interested in introducing new concepts rather than keeping it as simple as possible for developers.

**Comment by jesup** [comment]
While I emphasize with your goals, as mentioned datachannels aren't free. 

Onnegotiationneeded or some other synchronization events would likely still be needed, even if the actual exchange was over a datachannel.  It would also make server implementations somewhat more complex (need a full datachannel impl for the server as well).  Some use-cases might get more complex.

If anything, the WG is moving in the opposite direction, exposing more low-level building blocks that applications can directly control, and letting new high-level APIs be build in libraries.

You can have a default datachannel trivially: pc.createDataChannel("", {}); before createOffer().  As Jan-Ivar says, handling renegotiation over that channel isn't hard.

**Comment by jan-ivar** [comment]
@tresdin I also like simple, but yeah the group went the other way. [Here's a demo](https://jsfiddle.net/vqv3pqwk/) of an `RTCSimpleConnection` polyfill that should do what you need.

**Comment by tresdin** [comment]
Thanks for the polyfill, @jan-ivar . It does help me alot, especially in its design pattern. BTW, I've got this error `simpleconnect.js:23 Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'` when I tried to send a message.

*P/s. I strongly recommend the WebRTC team to take a look at @jan-ivar 's approach.*

**Comment by jan-ivar** [comment]
@tresdin Please try it again. I broke it for a few hours yesterday as I was trying to make it work with a [simpler case](https://jsfiddle.net/jib1/2r86vn6s/) (avoid needing an explicit `pc.connect()`).

**Comment by tresdin** [comment]
@jan-ivar It works great. I've spent some time on making it clearer by the way. Hope it helps other people too. https://jsfiddle.net/tresdin/1138xw7c/

**Comment by alvestrand** [comment]
Attaching the "later" label and closing. There doesn't seem to be support for reopening this design decision in the WebRTC-1.0 timeframe.
