### ISSUE TITLE
Figure out backward-compatible way to indicate ufrag+mid on end-of-candidates

### ISSUE THREAD

**Issue by juberti** [w3c/webrtc-pc#760]
Split off of https://github.com/w3c/webrtc-pc/issues/726.

Want to indicate end-of-candidates for each mid, as well as a ufrag indicator in both these and the global mid.

Problem is that surfacing an object of type { ufrag, mid, null } may cause some apps to explode since they expect a real candidate. So we need a way to ensure these things are ignored by old apps.

Some proposed options:
1) RTCConfiguration option to turn these on, off by default. [+ clean API, - off by default]
2) New event for end-of-candidates (separate from onicecandidate and onicegatheringstatechange) (+ clean API, - new API, - more work for client)
3) Fake candidates (e.g. ufrag, mid, "candidate: 0 0.0.0.0 0 type blah" ) (+ no new APIs, - ugly, might still break some things)
4) Ufrag decoration on null candidate event (+ no new APIs, - doesn't work for mid, - ufrag in different places for candidate and e-o-c)

**Comment by juberti** [comment]
I think I lean towards 1) and then 2)

**Comment by juberti** [comment]
Note also that these objects need to be fed to addIceCandidate on the remote side, so 2) is less attractive in that it ends up being asymmetric (or we need some other API there, which is also unattractive).

3) is unattractive in that the candidates need to be lexically correct, i.e. a full candidate with a real IP address, priority, type, etc

4) is unattractive because it doesn't work for mid

Which, alas, leaves 1). I think that might be OK since these events are often optional anyway.

**Comment by adam-be** [comment]
I think it's a bit wierd to change the API with an option as 1) proposes. Web developers borrow code from examples and other apps and it complicates things if there's an "API configuration" that needs to match for the code to work. And we would still have an "icecandidate" event that doesn't contain a candidate.

My preference is probably 2). I've been asked numerous times by developers why "end of candidates" isn't an event of its own.

For 4) to work I guess we would need to add everything to the event that we need in case the candidate attribute is null. That could include mid.

**Comment by alvestrand** [comment]
I think we all agree that the end-of-candidates=null candidate marker is a hack, but it's a hack we're bound to support. We should try not to make it worse.

This stuff is linked to an ICE transport. What matters with the candidates is that they're from/for an ICE transport; the MID stuff is a side effect of our SDP reliance, the ufrag is not.

We already have an object called RTCIceTransport that fires events at us:

             attribute EventHandler         onstatechange;
             attribute EventHandler         ongatheringstatechange;
             attribute EventHandler         onselectedcandidatepairchange;

End-of-candidates causes a transition from "gathering" to "completed". (or I think it should - I can't find any text in the document on when the IceGatheringState updates).

So suggestion 5):

Add an "ufrag" attribute (read-only) to RTCIceTransport. Don't change anything else.

**Comment by juberti** [comment]
option 4) doesn't work with mid not because the attribute is missing, but because existing apps won't expect multiple NULLs.

**Comment by juberti** [comment]
@pthatcherg and I discussed this today. I think 1) and 2) are the only proposals we should seriously consider. For WebRTC 1.0, I still lean towards 1) because of its simplicity and the fact that not enabling this option is generally not a big deal.

@adam-be, we already do have an event when ICE gathering is done. It's on icegatheringstatechange. 

The difference between 1) and 2) can be seen when looking at the desired API flow for the following sequence, specifically the handling of the done events in 3, 6, 7, 11, 14, and 15.
Adding a new API (on both sides) for the end-candidate events, might be a small improvement, but I'm not sure it's worth it, since the handling of the event will be almost identical to the existing event (e.g. take object, serialize it, ship it out).
If we do add a new API, I think we should go down the path of @pthatcherg 's suggested .oniceaction, which could handle add-candidate, end-of-candidates, and the new remove-candidate concept we've been looking at in the ICE WG.

1. A: onicecandidate(ufrag: u1, mid: m1, candidate1)
2 A: onicecandidate(ufrag: u1, mid: m1, candidate2)
3 A: onicecandiddate(u1, m1, null) OR icecandidates-done(u1, m1)
4 A: onicecandidate(ufrag: u1, mid: m2, candidate3)
5 A: onicecandidate(ufrag: u1, mid: m2, candidate4)
6 A: onicecandiddate(u1, m2, null) OR onicecandidates done(u1, m2)
7 A: onicecandidate(null) OR (?)
8 A: onicegatheringstatechange
9 B: addIceCandidate(ufrag: u1, mid: m1, candidate1)
10 B: addIceCandidate(ufrag: u1, mid: m1, candidate2)
11 B: addIceCandidate(u1, m1) OR setIceCandidatesDone(u1, m1)
12 B: addIceCandidate(ufrag: u1, mid: m2, candidate3)
13 B: addIcecandidate(ufrag: u1, mid: m2, candidate4)
14 B: addIceCandidate(u1, m2) OR setIceCandidatesDone(u1, m2)
15 B: addIceCandidate(null) OR (?)

**Comment by adam-be** [comment]
I would be interested to hear more about @pthatcherg's thinking around an .oniceaction API as mentioned by @juberti above. I made some notes on the plane home from TPAC how I imagined it could look. Just dumping those in this thread below.

```
// === API ===

partial interface RTCPeerConnection {
    attribute EventHandler oniceaction;

    Promise<void> handleIceAction(RTCIceAction action);
}

dictionary RTCIceAction {
    // not all members are defined for all types of actions
    required RTCIceActionType type;
    DOMString ufrag;
    DOMString sdpMid;
    DOMString sdpMLineIndex;
    DOMString? candidate; // not defined if type is "end-of-candidates"
}

enum RTCIceActionType { "add-candidate", "remove-candidate", "end-of-candidates" };

interface RTCPeerConnectionIceActionEvent : Event {
    RTCIceAction getAction();
    readonly attribute DOMString? url;
};

// === Usage ===

pc.oniceaction = evt => {
    signalingChannel.send(JSON.stringify({ iceAction: evt.getAction() }));  
};

signalingChannel.onmessage = evt => {
    // ...
    if (message.iceAction)
        pc.handleIceAction(message.iceAction).catch(logError);
};
```

**Comment by alvestrand** [comment]
Looks cool. But I think it should be on RTCIceTransport, not on RTCPeerConnection, which means that you really don't need sdpMid and sdpMLineIndex.

Creeping Complexity Warning: We've never had "remove candidate" before. Do we want it very much?

**Comment by aboba** [comment]
Don't we need support for "remove candidate" in Trickle ICE before we can add it to the API?  A thread relating to "remove candidate" is here:
https://www.ietf.org/mail-archive/web/ice/current/msg00387.html

**Comment by alvestrand** [comment]
Could we put the RTCIceAction API on the RTCTransport, and then define the Candiate API (for backwards compatibility) on RTCPeerConnection, defining its actions in terms of calls to the RTCIceAction API?
I don't think we can remove the Candidate API (at least not in implementations) any time soon.

**Comment by aboba** [comment]
@alvestrand With the merger of PR https://github.com/w3c/webrtc-pc/pull/968, I believe this can be closed.
