### ISSUE TITLE
insertDTMF should normalize input

### ISSUE THREAD

**Issue by annevk** [w3c/webrtc-pc#768]
Basically I'd use an ASCII uppercase operation. That makes it easier to write generic code that does something with the attribute values and is also somewhat good practice.

**Comment by aboba** [comment]
The spec refers to charcters A-D and says that "The characters a to d are equivalent to A to D."  So it makes sense that a-d when entered are converted to ASCII upercase, and that browsers would only generate A-D.

**Comment by aboba** [comment]
In the merged PR, I added a statement about normalization.  Are there places where it needs to be made clear that the browser always outputs normalized values?

**Comment by annevk** [comment]
The PR is mostly okay. The main problem is that it's not really phrased as a requirement, but rather as a statement of fact, yet nowhere is there a requirement that supports the statement of fact.

https://ln.hixie.ch/?start=1140242962&count=1 might help.

**Comment by alvestrand** [comment]
Anne, are you saying that the statement "The characters a to d (normalized to uppercase on entry) are equivalent to A to D." should be phrased as "The characters a to d MUST be considered equivalent to A to D"? That's language not changed by this PR (despite being marked in red), so if so, there's a new issue. (The rest of the sentence is full of MUSTs, so count as normative conformance requirements in Hixie's taxonomy).

If you think this matters, please raise an issue on it.
