### ISSUE TITLE
insertDTMF doesn't define what happens with characters that are not supported

### ISSUE THREAD

**Issue by annevk** [w3c/webrtc-pc#769]
E.g., what happens if a user agent doesn't support ","?

**Comment by aboba** [comment]
Presumably it would not  delay 2 seconds.  Is there a good argument for allowing support to be optional, or should we just require support for ","?

**Comment by rshpount** [comment]
We should require support for ",". There is no reason why user agent cannot implement a timer. On the related note, it always bugged me that you can specify tone duration and inter tone gap, but not pause duration. It should be just one more optional parameter in insertDTMF.

**Comment by alvestrand** [comment]
Fixed by #783
