### ISSUE TITLE
What are the units of interToneGap?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#770]
It's an integer number of what?  Milliseconds, I assume, but it should be specified.

**Comment by alvestrand** [comment]
"in ms" occurs in the description of the "duration" parameter of the insertDTMF function. I guess we could scatter a number of "in ms" over the other definitions too.

**Comment by aboba** [comment]
Agree that the unit is milliseconds.

**Comment by aboba** [comment]
With the PR merged, can we close this?

**Comment by alvestrand** [comment]
Not merged yet.

**Comment by alvestrand** [comment]
Fixed by #883
