### ISSUE TITLE
interToneGap definition doesn't quite make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#772]
There are two problems:

1. It doesn't say what should be returned if `insertDTMF` was never called.
2. Talking about "if insertDTMF was called without specifying the interToneGap" makes no sense: that method always passes in a value, because it's defaulted in the IDL.

I assume the intent here is to return `70` if `insertDTMF` was never called or something?

**Comment by aboba** [comment]
Since 70 is the default, presumably that is the value that should be assumed if insertDTMF was never called. It would make more sense to say that if interToneGap is unset a value of 70 should be assumed.

**Comment by aboba** [comment]
With the PR merged, can we close this?

**Comment by alvestrand** [comment]
Issue removed by #852
