### ISSUE TITLE
duration definition on RTCDTMFSender doesn't quite make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#773]
There are two problems:

1. It doesn't say what should be returned if insertDTMF was never called.
2. Talking about "if insertDTMF was called without specifying the duration" makes no sense: that method always passes in a value, because it's defaulted in the IDL.

I assume the intent here is to return `100` if `insertDTMF` was never called or something?

**Comment by aboba** [comment]
Presumbably the default duration (100) is the value if insertDTMF is  never called. It might make more sense to state that if duration is unset (since the argument is optional), a value of 100 is assumed.

**Comment by bzbarsky** [comment]
> Presumbably the default duration (100) is the value if insertDTMF is never called

This is the part that is not specified anywhere.

> It might make more sense to state that if duration is unset (since the argument is optional)

It has a default value, so is never unset.  That's if you're talking about the argument.  If you mean some sort of internal state, then yes, that would need to be specified clearly.

**Comment by alvestrand** [comment]
Issue removed by #852
