### ISSUE TITLE
Handling of invalid characters in the tone buffer is broken

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webrtc-pc#775]
Consider the following operations on a `RTCDTMFSender` named `sender`:

    sender.insertDTMF("ABCD");
    setTimeout(function() {
      sender.insertDTMD("ZZZZ");
    }, 200);

Stepping through <https://www.w3.org/TR/webrtc/#dom-rtcdtmfsender-insertdtmf>, the first time we set the `toneBuffer` to "ABCD", and queue a playout task.  Let's call this time 0.

The playout task runs, pops the "A" from `toneBuffer`, starts playout of it, schedules another playout task for time 170ms.

At time 170ms, the second playout task runs, pops the "B" from `toneBuffer`, starts playout, schedules another playout task for time 340ms.

At time 200ms the timeout fires and `insertDTMF` is called again.  It sets `toneBuffer` to "ZZZZ" and then throws an exception.

At time 340ms the third playout task runs, pops the "Z" from `toneBuffer`, start playout... what does that mean, exactly?

**Comment by alvestrand** [comment]
Swapping #1 and #2 in that algorithm (throwing an exception before modifying the tone buffer) seems reasonable to me.

**Comment by aboba** [comment]
The merged PR checks for unrecognized characters in the tone argument.  Can we close this issue?

**Comment by alvestrand** [comment]
Fixed by #785
