### ISSUE TITLE
RTCDTMFToneChangeEventInit should either make tone required or add default value for tone

### ISSUE THREAD

**Issue by smaug----** [w3c/webrtc-pc#789]
...otherwise it isn't clear what
(new RTCDTMFToneChangeEvent("foo")).tone is.

And the dictionary passed to the event constructor should be marked optional

**Comment by aboba** [comment]
I've submitted PR that makes tone required, as well as an explanation of the tone attribute in the dictionary.  Since tone will always be set, it seems to me that the dictionary will always be present in the event constructor.

**Comment by aboba** [comment]
Can we close this issue now that the PR has been merged?

**Comment by alvestrand** [comment]
Closed.
