### ISSUE TITLE
Specify when a data channel's ID is assigned, and what the `id` attribute returns when no ID is assigned.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#795]
This is an issue I noticed when working on a solution for issue #746.

The [WebRTC data channel establishment spec](https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-08#section-6) requires that DTLS clients choose even stream IDs, and DTLS servers choose odd IDs.

However, the DTLS role may not be known at the time of creating a data channel. So, until the role is determined, what does the `id` attribute return? It's worth noting that both Chrome and Firefox currently return an ID of 65535, which is guaranteed to be out of range (the maximum usable ID is 65534). But it seems more "correct" to make the attribute nullable.

And then, when should a user script expect the ID to be populated? When the stable signaling state is reached with an SCTP media description negotiated? That would seem reasonable to me.

**Comment by alvestrand** [comment]
@taylor-b There was a discussion at TPAC about this - can you make a PR based on your memory of the conclusion?

**Comment by taylor-b** [comment]
Are you sure we discussed this at TPAC? My memory's blanking and I can't find anything in the minutes. It's also not in the slide deck. I filed this issue *as I was making the slides for* issue #746, so it's possible we never touched on it.

**Comment by alvestrand** [comment]
It seems that nobody is able to figure out a precise issue that needs solving under this title, so closing.

**Comment by taylor-b** [comment]
This still is an issue as far as I can tell. Does it need a better title?

**Comment by alvestrand** [comment]
The part we understood seemed to have been covered by #746. Can you try to explain it better?

**Comment by taylor-b** [comment]
#746 deals with calling `createDataChannel` with an invalid ID. This issue deals with calling `createDataChannel` with *no* ID (letting the browser choose the ID). Maybe an example will clear things up:

```
pc = new RTCPeerConnection();
dc = pc.createDataChannel("foo");
// What is dc.id? 65535 or null?
// ...
pc.setLocalDescription(offer);
// ...
pc.setRemoteDescription(answer_with_active_role);
// Now we know the DTLS role. An odd value (1) is chosen for dc.id.
```

I think it would be pretty uncontroversial to say the DTLS role (and thus the data channel ID) is chosen when applying an answer. So the main question is what the `id` attribute returns when no ID is chosen yet.

**Comment by alvestrand** [comment]
I'd think leaving it as null (which means it has to be nullable) would be the clearest way to do it.
Any "marker" value risks being a possibly-useful value if we change the underlying protocol, but null won't be.

Reopening issue.

**Comment by aboba** [comment]
@taylor-b Can you submit a PR?
