### ISSUE TITLE
Description of User Agent/ICE Agent interactions in section 4.3.1 needs to be updated.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#801]
This section currently says:

> - If the ICE Agent has found one or more candidate pairs for each MediaStreamTrack that forms a valid connection, update the ICE connection state to connected.
> - When the ICE Agent finishes checking all candidate pairs, if at least one connection has been found for each media description, update the ICE connection state to completed, otherwise to failed.

These state transitions are pretty incomplete. There are steps in algorithms elsewhere in the spec that are similarly incomplete, such as:

> If the ICE Agent is not currently checking candidate pairs, the ICE Agent must start checking candidate pairs and update connection's ICE connection state to checking.

Can we just add a blanket statement about the interaction between the ICE Agent and User Agent in the `RTCIceTransport` section? Something like: "The User Agent MUST respond to any state changes in the ICE Agent that affect the `RTCIceTransportState`, and queue a task to update the state of the affected `RTCIceTransport`." We can go on to describe how this queued task would update the `RTCPeerConnection`'s `iceConnectionState` and `connectionState`.

**Comment by aboba** [comment]
@taylor-b That seems like a good approach.

**Comment by aboba** [comment]
@taylor-b Looking through the text, there is quite a bit of material that refers to the ICE Agent and the aggregate ICE gathering state that has may have to be cleaned up.  This might not be a bad topic for the virtual interim give the potential extent of the required changes.

**Comment by alvestrand** [comment]
We think this has been fixed by #920.
