### ISSUE TITLE
Rules for negotiation-needed flag need to be updated for transceivers.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#803]
I found a few problems with the current rules regarding the negotiation-needed flag:
- It's still described overall in terms of tracks, not transceivers (such as in section 4.8.1).
- It's only cleared by `setLocalDescription`, but `setRemoteDescription` should be able to clear it as well in some cases.
- `createAnswer` sets the flag? I don't see the reasoning behind this. I'd expect setting a description to possibly set the flag, but not generating one.
- The act of firing `negotiationneeded` after reaching the stable signaling state also clears the flag? This means if the next SDP exchange didn't finish negotiating something (such as if it was initiated by the remote peer), the event wouldn't be fired again.

**Comment by taylor-b** [comment]
Another thing I realized: we need to specify what it means for all transceivers to be represented by the current negotiated description.

If you call `addTrack`, you get a "sendrecv" transceiver. But the remote endpoint may not have a track to send, resulting in the negotiated direction (on the offerer side) being "sendonly". Even though this doesn't match the transceiver's direction, it would be odd to get negotiation-needed in this case.

**Comment by aboba** [comment]
Now that PR 913 has been merged, can we close this issue?

**Comment by taylor-b** [comment]
Yes, the PR addressed all the problems I mentioned above.
