### ISSUE TITLE
Can the ICE gathering state go from completed to gathering without an ICE restart?

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#808]
The ICE gathering state says it can go from completed to gathering, but doesn't say anything about ICE restarts.  Later, text says that adding a TURN server won't cause any regathering until there is an ICE restart.  

So which is it?  Can we go from completed to gathering without an ICE restart?

Specifically, the text says that the gathering state can change when an interface is added.

**Comment by aboba** [comment]
@pthatcherg Once end-of-candidates has been issued, I do not think that we can go back to gathering without an ICE restart. 

However, I couldn't find a statement tying the transition of RTCIceGatheringState of "completed" to issuance of end-of-candidates.  

Also, in Section 5.6, the definition of RTCIceTransportState refers to "finished gathering" at several points, but does not refer to RTCIceGatheringState explicitly.
