### ISSUE TITLE
What does setConfiguration change or not change?

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#814]
I find the text of setConfiguration confusing:

"Let the value of configuration.iceTransportPolicy be the ICE Agent's ICE transports setting."  Does that mean set/change the ICE Agent's transport setting to configuration.iceTransportPolicy?  If so, it could be more clear.

But then there's a problem, I think, with "Let the value of configuration.bundlePolicy be connection's bundle policy."  What does it mean to change a bundle policy if the remote endpoint doesn't support BUNDLE?  Does that mean we potentially re-negotiate or undo negotiation of media sections?  It seems like a mess and I'd prefer not to allow changing the bundle policy.  This is similar to how we don't change the rtcpMuxPolicy.

**Comment by aboba** [comment]
I agree that the setConfiguration text is confusing and incomplete.

**Comment by aboba** [comment]
Can we close this now?
