### ISSUE TITLE
The RTCDTMFToneChangeEvent constructor should have an optional init dict

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#816]
https://w3c.github.io/webrtc-pc/#rtcdtmftonechangeevent

It would also be good to give `tone` a default value so that it doesn't need to be spelled out in prose. In summary:

```WebIDL
[Constructor(DOMString type, optional RTCDTMFToneChangeEventInit eventInitDict)]
interface RTCDTMFToneChangeEvent : Event {
    readonly attribute DOMString tone;
};
dictionary RTCDTMFToneChangeEventInit : EventInit {
    DOMString tone = "";
};
```

**Comment by aboba** [comment]
@foolip eventInitDict is not optional anywhere else in the specification.  Is there a unique reason it should be optional here?

**Comment by foolip** [comment]
The diff in https://github.com/w3c/webrtc-pc/issues/854 clued me in. Once again I'm bitten by the fact that https://w3c.github.io/webrtc-pc/ isn't in sync with master, and has no link to the most recent version :(

In https://rawgit.com/w3c/webrtc-pc/master/webrtc.html `tone` is required, so there is no problem.

However, the same problem still applies to `RTCPeerConnectionIceEvent` and `RTCPeerConnectionIceErrorEvent`, I'll file separate issues.
