### ISSUE TITLE
Need IDP Logon Needed Error

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#824]
Error needs to provide URL for login

**Comment by dontcallmedom** [comment]
I think this is a dup for #555

**Comment by fluffy** [comment]
Yah, I thought 555 was more about defining the meaning and this as passing the info but agree this is all about roughly the same thing. Don't care if two bugs or one as long as we say what it means and how you provide it.

**Comment by fluffy** [comment]
closed due to being dupe
