### ISSUE TITLE
Need Custom Error for IdP 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#830]
IdP JS code needs a way to to pass IDP defined error to the main application

**Comment by fluffy** [comment]
should add to https://github.com/w3c/webrtc-pc/pull/850

**Comment by alvestrand** [comment]
Is this an unbounded-scope problem, where any IdP can return anything, or is there some pattern that we can apply to say "what comes from the IdP has to look like *this*"?

**Comment by fluffy** [comment]
Yes, I think we can do something like say the IDP can pass a single JSON string as the error.

**Comment by fluffy** [comment]
When I look at the text in 9.5and the 9.6, I think this has all been done and we can close this bug as fixed.
