### ISSUE TITLE
Remove support for changing SDP

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-pc#834]
JSEP 16 no longer has a section on configurable SDP parameters (which triggers ReSpec warnings in #833), presumably based on the following change:
> Remove support for changing SDP before calling setLocalDescription.

The API needs to reflect that change.

**Comment by jan-ivar** [comment]
Would this let us deprecate the need to setLocalDescription? It's like that hoop on the back of my cable box that doesn't do anything.

**Comment by aboba** [comment]
Looking through the specification, it appears that there are only two places that reference SDP modification: 

1. "If elements of the SDP were modified in an invalid way as specified in [JSEP] (section 6.), then reject p with an InvalidModificationError and abort these steps."

2. "[JSEP] (section 6.) specifies what elements of the SDP returned by createOffer can be changed before passing it to setLocalDescription."

**Comment by jan-ivar** [comment]
@aboba I don't see how we can remove input validation as long as we pass the string through javascript. We can simplify the validation probably by reducing it to a synchronous string compare.

**Comment by burnburn** [comment]
I do remember this decision.
But all of this assumes, of course, that browsers will actually support all of the new controls before removing the ability to tweak SDP (e.g., setting the 'codecs' parameter).  I'd hate for the UA's to immediately drop support for SDP modification but delay on the rest and then later in CR have us decide that some of the actual new control features don't have enough implementations and get dropped from the spec after removing the only other way to effect those changes.

**Comment by stefhak** [comment]
Being able to inspect the SDP between createOffer/Answer and setLocal enables the app to inspect it, and potentially make changes and create a new one if not happy.

**Comment by stefhak** [comment]
If no one can identify what needs to be changed in the spec because of this we'll just close it.

**Comment by dontcallmedom** [comment]
Hmm... I don't think we can close this issue without action - right now, JSEP and the API are at odds, with API referring to a no-longer existing section of JSEP.

**Comment by aboba** [comment]
@dontcallmedom  Where in the spec is the (now orphaned) reference?

**Comment by dontcallmedom** [comment]
@aboba I had missed that you had  removed the references.

@jan-ivar seemed to indicate that's not sufficient, but I guess I'm not entirely sure why,  so it is in fact probably fine to close from my perspective.

**Comment by jan-ivar** [comment]
@dontcallmedom Nevermind, I misread @aboba 's [comment](https://github.com/w3c/webrtc-pc/issues/834#issuecomment-251863188) (thought both references were removed).

**Comment by dontcallmedom** [comment]
closing then
