### ISSUE TITLE
insertDTMF input validation steps are still out of order a bit

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#836]
The way [it's written right now](https://rawgit.com/w3c/webrtc-pc/c594cd214f0d71ff3c75a28e16be5dd695da15a6/webrtc.html#dom-rtcdtmfsender-insertdtmf), it's possible to observably set the attributes *duration* and *interToneGap* to invalid values by passing in an empty tone buffer. We should move the steps that clamp these to legal values to happen before we can return.

**Comment by aboba** [comment]
With the merger of PR 837, can we close this issue?
