### ISSUE TITLE
Define JSEP terms like "bundle" and "bundle-policy" in terminology section

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#842]
We are using a large number of terms that are defined in JSEP without a reference, including "bundle", "bundle-policy", "ICE", "candidate" and so on.

Suggest doing a sweep over the document and adding "defined in JSEP" to the terminology section.

**Comment by burnburn** [comment]
@alvestrand are you suggesting only a single terminology section entry for 'defined in JSEP', or are you suggesting adding a reference into JSEP for each and every use of the protocol-level terms you list (and others I come across)?

**Comment by alvestrand** [comment]
I think a terminology section with "&lt;dfn>term&lt;/dfn>, term, term, term are defined in [[JSEP]]" is the easiest to maintain. That gives two clicks from an &lt;a> to the JSEP spec, and a search function in JSEP to find the definition.
Functional enough for me. Let's make it simple until someone who wants something complex comes along and offers to do the work.
The error I'm trying to save people from is people reading "froobnitz" and thinking it's the ITU-T recommendation X.agc froobnitz, and not the JSEP froobnitz.

**Comment by aboba** [comment]
@stefhak Can we close this issue or are there more definitions that need to be added?

**Comment by stefhak** [comment]
@aboba yes I think we can close - so I'm closing it now.
