### ISSUE TITLE
DTMF: duration and interToneGap attributes: Do we need them?`

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#843]
Do we need the duration and interToneGap attributes?

**Comment by fluffy** [comment]
I think we need to be able to do a "long pound" as that is commonly used in IVRs. So I see a use case for some way to indicate do DTMF that is a more than a few seconds long. I don't see much use for interToneGap

**Comment by fluffy** [comment]
I can't see any reason we need the attributes (still need the at least the duration parameter in the function call)

**Comment by alvestrand** [comment]
I think removing them makes the API simpler and no less powerful, so I'm happy to see them go.

**Comment by alvestrand** [comment]
Closed by #852

**Comment by smaug----** [comment]
Just a comment from someone who reviews often webidl changes in Gecko: why is the API being changed so often? Does any vendor have data whether the attributes here are used and whether it is safe to remove them?
It is unusual for web specs to be changed so often after there are implementations shipping.
