### ISSUE TITLE
"Throw a FooError" steps not written in a consistent manner

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-pc#845]
I've seen the following:
- "throw a FooError."
- "[throw](http://heycam.github.io/webidl/#dfn-throw) a FooError." (which is the example wording suggested in WebIDL)
- "then throw a FooError exception and abort these steps."
- "throw a FooError and abort these, and all further steps."

And for promises, we have:
- "reject _p_ with FooError, and abort these steps"
- "reject _p_ with a DOMException object whose name attribute has the value FooError, and abort these steps"
- "reject _p_ with a DOMException object whose name attribute has the value FooError and stop processing any more steps"
- "reject _p_ with a DOMException object that has a name of FooError, and abort these steps"

Which formats do we want to use consistently?

For throwing an exception, I'd suggest:

> "[throw](http://heycam.github.io/webidl/#dfn-throw) a FooError."

The link makes it clear what this means, and "abort these steps" is redundant since it's implied that steps are aborted when an exception is thrown.

And for rejecting a promise, I'd suggest:

> "reject _p_ with a newly [created](https://heycam.github.io/webidl/#dfn-create-exception) FooError and abort these steps." 

This also uses wording suggested in WebIDL, and it's pretty short/sweet/to-the-point.

**Comment by adam-be** [comment]
Would be nice to make this consistent. Your suggested alternatives seem right to me.

**Comment by aboba** [comment]
@adam-be Not only is the _wording_ inconsistent, but the errors themselves are not consistent.  We now have a Section 12 on Error Handling, but from what I can tell, we are not using the RTCError event.  Looking at Section 13, RTCDataChannel uses the error event, for example.
