### ISSUE TITLE
How do I get transceiver from sender?

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#866]
I have the following line in some code that works today in FF 49.0:

  videoSender = pc.addTrack(myVideoStream.getVideoTracks()[0], myVideoStream);

Given that I have videoSender, how do I find the RTCRtpTransceiver it's a part of?  It seems there should be a .transceiver attribute on RTCRtpSender.

**Comment by pthatcherg** [comment]
```
videoSender.transceiver = pc.getTransceivers().find(t => t.sender == videoSender);
```

Or if "find" doesn't work on sequences returned by getTransceivers:

```
videoSender.transceiver = find(pc.getTransceivers(), t => t.sender == videoSender);

function find(vals, found) {
  for (var val in vals) {
    if (found(val)) {
      return val;
    }
  }
}
```

The reason for not putting it on RtpSender (other than it being so easy to find) is that all along we've tried to put all the SDP-ish stuff in RtpTransceiver and leave it out of RtpSender/RtpReceiver.  In a WebRTC NV world where you (hopefully) construct RtpSender and RtpReceiver objects directly, a .transceiver would be awkward.

**Comment by jan-ivar** [comment]
`find` works since `getTransceivers()` returns a JS array in practice.

**Comment by burnburn** [comment]
@pthatcherg Yuck, but okay.  .transceiver is not an unreasonable back-reference.  Closing, though, so we can get closer to finishing this spec.
