### ISSUE TITLE
RTCTrackEventInit: streams required? 

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#868]
In Section 5.7 we have: 

partial interface RTCTrackEvent : Event {
    readonly attribute FrozenArray<MediaStream> streams;
};

So it would appear that streams is non-nullable. 

However, we also have: 

dictionary RTCTrackEventInit : EventInit {
    required RTCRtpReceiver        receiver;
    required MediaStreamTrack      track;
             sequence<MediaStream> streams = [];
    required RTCRtpTransceiver     transceiver;
};

This indicates that streams is not required.

**Comment by alvestrand** [comment]
Isn't the "= []" argument just saying that the list can be empty, but if you don't pass in anything for it, it's treated like an empty list?

that is - when it has passed through the WebIDL machinery, it will be non-null (and empty) even if you passed in a null?
