### ISSUE TITLE
rid in addTrack()

### ISSUE THREAD

**Issue by burnburn** [w3c/webrtc-pc#869]
In the description for the RTCRtpEncodingParameters dictionary it says "The RID is not modifiable via setParameters. It can only be set or modified in addTransceiver or addTrack."

How is the RID set via addTrack?

**Comment by aboba** [comment]
Given the current definition of addTrack this would not appear possible.

**Comment by pthatcherg** [comment]
I think we decided to only allow it via addTransceiver, so we can just remove the "or addTrack" part.
