### ISSUE TITLE
How to properly manage TrackEvent or provide the current AddStreamEvent?

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#876]
Hello,
analysing the usage of TrackEvent I think that it is not easy.
The point is that at the end developers need to use MediaStream objects to render the media in a VideoTag, and typically some MediaStreamTracks are included in the same MediaStream.
Taking this into account, with the current API developers have to deal with the next problem:
- Know if the MediaStream associated to the track received in the onTrack handler has been already rendered (because it is the same that the MediaStream associated to a previous track received in the onTrack). For example, if mediaStream has 2 MediaStreamTrack (audio and video) it will be set twice.

`
pc.ontrack = function (evt) {
    mediaStream = evt.streams[0];
    remoteView.srcObject = mediaStream;
};
`

This is a simple case, but the developers can also know which MediaStreamTracks are into the MediaStreams to apply a more complex logic (for example: only render some of them, split them in different MediaStreams, etc.)
In that cases they typically would have to store all MediaStreamTracks/MediaStream received in the  onTrack handler and wait until the setRemoteDescription returns to perform the logic.

Taking this difficulties into account:
- Should we provide an AddStreamEvent and a onAddStream handler as the current implementations?
- Should we provide some examples (or even utilities) to show how to manage this kind of cases?

Best regards!!

**Comment by stefhak** [comment]
The way I've been looking at this is that advanced cases would always be handled by the sending side supplying rendering info on the side (e.g. as extra info piggy backed with the session descriptions that anyway have to be exchanged). That rendering info could say things like "tracks X, Y and Z represents this" and "tracks A and B represents that".  That way the app on the receiving side can create one MediaStream containing X, Y and Z and another containing A and B.

I guess having examples showing this would be helpful.

**Comment by mparis** [comment]
Hello @stefhak and thanks for your proposal,
the point is that the logic of the MediaStream/MediaStreamTrack treatment can be receiver-dependent and not sender-dependent, so your solution only will not match with all use cases.

Moreover, I think that this is a general problem that we should consider to extend the PeerConnection API to handle MediaStreams (onAddStream handler) or provide an utility to achieve that in order to ease the developers' life, as I said in my previous comment.

**Comment by stefhak** [comment]
I'm not sure I understand what a receiver can do based on an ```onaddstream``` event that it could no do with info supplied on the side.

But feel more than welcome to submit a proposal (ideally in the form of a PR), but you should be aware that we did discuss re-introducing some MediaStream related stuff on the PeerConnection in an earlier Virtual Interim, but that proposal was turned down by the group at that time.

**Comment by alvestrand** [comment]
Closing as "no required action, no proposed action".
