### ISSUE TITLE
Clarify the processing of expires setting in generateCertificate

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#879]
When writing https://github.com/w3c/web-platform-tests/pull/4062 I tried this to get an expired certificate:

`RTCPeerConnection.generateCertificate({ name: "ECDSA", namedCurve: "P-256", expires: 0 }`

`DOMTimeStamp` is `unsigned long long`, and there's nothing in the spec that suggests that 0 shouldn't work. It works in Chrome, but not Firefox. This needs spec clarification or at least agreement on the right behavior since we now have two.

When writing tests for this, it would also be good to test -1, 0.1, NaN, Infinity, -Infinity and numbers around 2^31, 2^32, 2^63 and 2^64.

**Comment by martinthomson** [comment]
So Firefox treats 0 the same as absent.  That's probably not cool.  I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1312306

I don't think that we need spec changes.

**Comment by martinthomson** [comment]
OK, I just changed my mind, I think that the definition of expires is sloppy and could use some improvement.  So I will open a PR.
