### ISSUE TITLE
Align getAlgorithm return value with Web Crypto

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#881]
See discussion starting at https://github.com/w3c/webrtc-pc/pull/499#issuecomment-253449024 and suggestions by @ericroman920 at https://github.com/w3c/webrtc-pc/pull/499#issuecomment-254577161.

(Filing a separate issue as requested because that one is since long closed.)

**Comment by martinthomson** [comment]
If we intend to return an attribute it should be immutable (i.e., an interface), and not a dictionary.  We should not repeat the mistakes of webcrypto as suggested.

**Comment by foolip** [comment]
By "return an attribute" do you mean changing it into an attribute instead of a method?

Whether it is an attribute or a method, if it returns the same value every time, then something akin to `FrozenArray<T>` might make sense. That is, some syntax which causes `Object.freeze(returnValue)` to be called on the return value in generated bindings code. @ericroman920, have you considered and rejected something like that for Web Crypto already?

**Comment by ericroman920** [comment]
Not sure if something like that was considered.

**Comment by alvestrand** [comment]
I think the chief usability criterion for getAlgorithm() is that it should return something that's usable with createCertificate - that is:

cert1 = pc.generateCertificate(algorithm)
cert2 = pc.generateCertificate(cert1.getAlgorithm())

should result in two certificates generated with the same algorithm.
(Open question: Should it contain the "expires" attribute, or does the second cert have default lifetime unless overridden?)

**Comment by martinthomson** [comment]
I agree with Harald, and yes, I believe that it should contain the `expires` attribute.

**Comment by martinthomson** [comment]
Having looked at the webcrypto API, and done some investigation on this, I think that I've concluded that we should just accept that this is going to be broken and expose a `readonly object` attribute on `RTCCertificate`.  That will be mutable, it will be ugly, but that's what webcrypto does and I don't see an easy way to fix this otherwise.

Ideally, this would be an immutable interface, but we don't get that luxury because webcrypto is kinda broken already and in order to fix it here, we would have to fix it there as well.

**Comment by alvestrand** [comment]
#896 was relevant, but did not solve this problem.

A function returning an object seems less obnoxiousl than a mutable attribute that doesn't mutate anything.

**Comment by foolip** [comment]
I agree with https://github.com/w3c/webrtc-pc/issues/881#issuecomment-258105210, i.e. doing something as consistent as possible with Web Crypto.

**Comment by alvestrand** [comment]
@foolip can you propose a PR?

**Comment by foolip** [comment]
Giving myself a reminder for some time in January.

**Comment by aboba** [comment]
@foolip Assigning this to you.

**Comment by foolip** [comment]
I have too much on my plate do deal with this I'm afraid. If I were the spec editor, I would just put a warning in the spec asking the first implementer to figure this out and change the spec as they implement.

**Comment by stefhak** [comment]
@alvestrand do we need to do anything more on this one?

**Comment by alvestrand** [comment]
Closing for now, we seem to have some degree of alignment. Can reopen if implementors want changes.

**Comment by foolip** [comment]
The spec still doesn't say what it eventually should, it's just that's nobody is interested in implementing it right now. Can you add a warning that points to an open issue, so that nobody implements and ships it as is?

**Comment by aboba** [comment]
@foolip We could add a note saying that the feature is "at risk".  In Section 4.2.6 such a note is included with respect to RTCMuxPolicy:

"FEATURE AT RISK 1
The value negotiate is marked as a feature at risk, since there is no clear commitment from implementors for the behavior associated with this."

**Comment by alvestrand** [comment]
I think the conclusion of the thread at last close was that the specified API (which is, to remind everyone, a method returning an Object (AlgorithmIdentifier) that might be a dictionary) shouldn't be changed as a result of this thread.

We could wish for many things, including having the object be the WebIDL equivalent of const and being the same value every time, but these changes would reduce, not increase, the alignment with WebCrypto, and there seems little interest in coming up with a specification.

First implementor wins?

**Comment by foolip** [comment]
Marking it at risk sounds great to me if nobody currently has plans to implement.

If I came along and wanted to implement this, I think I'd want to change the spec in one of two ways. Either, return an object that is derived in the same way as https://w3c.github.io/webcrypto/Overview.html#concept-cached-object but is a new object every time. Or, change it to an attribute with this IDL:
```WebIDL
interface RTCCertificate {
    readonly attribute DOMTimeStamp expires;
    readonly attribute FrozenArray<RTCDtlsFingerprint> fingerprints;
    readonly attribute object algorithm;
};
```

And implement it the same way as CryptoKey's algorithm attribute, which returns the same value every time.

The second option seems to most well aligned with Web Crypto, but if I knew crypto well perhaps I'd know of reasons to not do that.

Simply leaving the spec as-is, an unknowing implementer might come along and ship without pondering the options.

**Comment by alvestrand** [comment]
We should mark it as "feature at risk".

**Comment by aboba** [comment]
Should we close this issue for now?

**Comment by foolip** [comment]
That WFM, thanks for adding the warning in the spec!
