### ISSUE TITLE
Should empty (not omitted) username or credential throw in the RTCPeerConnection constructor?

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-pc#885]
This throws in Firefox: `new RTCPeerConnection({iceServers:[{urls:'turn:foo.com',username:'',credential:''}]})`

But the spec says "If scheme name is turn or turns, and either of server.username or server.credential are omitted, then throw an InvalidAccessError and abort these steps."

If the Firefox behavior makes sense, the spec should say "empty or omitted" and https://github.com/w3c/web-platform-tests/blob/master/webrtc/rtcpeerconnection/rtcpeerconnection-constructor.html needs to be updated.

**Comment by foolip** [comment]
FWIW, unless some more strict checking is done, I think it would make sense to not throw, and fail in the same way as when username is a single U+0000, or a space character.

**Comment by jan-ivar** [comment]
@foolip Are there cases where empty user name and/or empty credential make sense? If not, we could default these to "" in webidl and check for length.

**Comment by foolip** [comment]
I really don't know, maybe there's such a thing as an empty password, any way of getting the spec and all implementations in alignment is fine I think. But I do suspect there are strings in addition to the empty string that never work as a username/password for this stun/turn stuff, and if so it might be better to just make sure that error case is covered.

**Comment by jan-ivar** [comment]
OK, I'm happy to fix Firefox then.

**Comment by foolip** [comment]
@jan-ivar, can you review https://github.com/w3c/web-platform-tests/pull/4071? No spec change needed if you're OK with it.

**Comment by foolip** [comment]
https://github.com/w3c/web-platform-tests/pull/4071 has been merged, so I'll close this.
