### ISSUE TITLE
Section 6.2:  Issue 3 - buffered data at transport close

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#888]
Section 6.2 contains the following note on Issue 3: 

ISSUE 3
The data transport protocol will specify what happens to, e.g. buffered data, when the data transport is closed.

**Comment by alvestrand** [comment]
I think we lose the data (hard close). Hard to see what else we can do.

**Comment by taylor-b** [comment]
@alvestrand In Chrome, we send all buffered data before starting the closing procedure. See: https://bugs.chromium.org/p/webrtc/issues/detail?id=4620

Could we maybe introduce two "close" methods, an abrupt close and a graceful close, to better accommodate the needs of different applications? We already have the concept of an abrupt close (which occurs when the buffer is filled to capacity), so this seems simple.

**Comment by feross** [comment]
Yes, please support a way to send the buffered data before close. This is needed for our application, otherwise we can't be sure when to call `close()`

**Comment by jesup** [comment]
Perhaps there's confusion here between datachannel.close(), and a failure or shutdown of the transport (connection failure, or (probably) peerconnection.close()).

In any case, Firefox currently implements a clear of buffered data on close() currently.  If you added a closeWithPromise(), that might be more "webby", though you probably want to be able to say "close now and drop any data" as well (spec close()).  The WebSockets API was designed before promises, of course.

To @feross  's point, the application can add a handshake after a transfer (or explicit I'm-going-to-close-please-ack message).  It can also ask about the amount of buffered data.

**Comment by taylor-b** [comment]
You don't even need signaling; you could set the `bufferedAmountLowThreshold` to 0 and wait for the `bufferedAmountLow` event to tell when the buffer is emptied.

It just seems odd to me that the default `close` is a half-graceful close. The data buffered at the WebRTC level will not be sent, but the data buffered at the SCTP level will. When would an application ever *want* this behavior (as opposed to fully graceful, or fully abrupt)?

**Comment by alvestrand** [comment]
Seen from the user, graceful close is much more useful (easier to reason about) than graceless close.
It does require notification that a graceless close has happened that can work after graceful close has been asked for. TCP has been able to live without API-visible confirmation that graceful close has completed (AFAIK) for many years, so that might not be a necessary function.
