### ISSUE TITLE
Remove RTCSessionDescription constructor or throw error on missing sdp

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#897]
The spec says of [sdp](http://w3c.github.io/webrtc-pc/#dom-rtcsessiondescriptioninit-sdp): *"if type is rollback, this member can be left undefined."* but no processing steps to say what happens if it's undefined for other types. E.g. What does this output?

    console.log(new RTCSessionDescription({type: "answer"}).sdp);

Alternatively, we could deprecate the constructor since it is no longer needed for anything.

Omitting sdp in the set description processing steps already yields `InvalidModificationError`, so I believe we are fine there.

**Comment by bzbarsky** [comment]
> Alternatively, we could deprecate the constructor since it is no longer needed for anything.

Unless "deprecate" means "remove" here, the spec really needs to define its behavior.

**Comment by foolip** [comment]
Don't any problems with this constructor also apply to any context that takes a RTCSessionDescriptionInit dictionary?

https://bigquery.cloud.google.com:443/savedquery/762219082167:4d698184e35549c2accc9fbe6ded90af has 1642 hits, so unless it's a maintenance burden it seems best to just keep it around. The interface itself is used after all, having a constructor is about as harmless (and useless) as many event constructors.

**Comment by foolip** [comment]
(The BigQuery link just shows the query, the results aren't saved. If anyone is interested I can export them.)

**Comment by jan-ivar** [comment]
> Don't any problems with this constructor also apply to any context that takes a RTCSessionDescriptionInit dictionary?

@foolip No because, http://w3c.github.io/webrtc-pc/#set-description already says *"If elements of the SDP were modified in an invalid way as specified in [JSEP] (section 6.), then reject p with an InvalidModificationError and abort these steps."*

**Comment by foolip** [comment]
OK, looked a bit more. AFAICT, in spec and in Blink, a script-created RTCSessionDescription can't really be used for anything, except to pass it to a context expecting a RTCSessionDescriptionInit and depend on that error handling.

So, is it a problem if it's possible to create nonsensical RTCSessionDescription instances? Many event interfaces are like this, where scripts can create combinations of things that are otherwise impossible, but it doesn't actually do anything.

Of course, it might also be an option to throw in the constructor for certain combinations, if use counters or httparchive analysis show them to be very, very uncommon.

**Comment by jan-ivar** [comment]
It's not a problem, but the spec should still define what happens, to avoid browsers doing different things. If we don't have the stomach for removing the constructor, then I suggest we throw or set to empty string (given that the resulting attribute is readonly, throwing probably makes more sense).

**Comment by jan-ivar** [comment]
On second thought, since we can't throw if `type == "rollback"`, let's just default `sdp = ""` in the dictionary and be done with it.

**Comment by foolip** [comment]
Right, with `DOMString  sdp = ""` there would be no doubt about what `new RTCSessionDescription({ type: "offer" }).sdp` is (the empty string). Prose to spell it out that the type/sdp attributes are initialized from the type/sdp members would still be nice, of course.

**Comment by jan-ivar** [comment]
> Prose to spell it out that the type/sdp attributes are initialized from the type/sdp members would still be nice, of course.

Beyond [this](http://w3c.github.io/webrtc-pc/#dom-sessiondescription)?

**Comment by foolip** [comment]
Yes, e.g. like step 4 of https://dom.spec.whatwg.org/#constructing-events or how https://wicg.github.io/IntersectionObserver/#dom-intersectionobserver-intersectionobserver explicitly maps each member to an attribute. I think this is just "nice" though, no honest confusion results from more vague language.

**Comment by jan-ivar** [comment]
@foolip Seems we use this pattern in a couple of places, so perhaps in a separate PR?

**Comment by foolip** [comment]
Yeah, that's fine.
