### ISSUE TITLE
Does RTCRtpReceiver.track.stop() reject the track?

### ISSUE THREAD

**Issue by Pehrsons** [w3c/webrtc-pc#898]
In [**5.1.1 Processing Remote MediaStreamTracks**](https://w3c.github.io/webrtc-pc/archives/20160913/webrtc.html#processing-remote-mediastreamtracks) it says _Rejection of incoming MediaStreamTrack objects can be done by the application, after receiving the track, by stopping it._

It doesn't define _Rejection_, but I'll just assume for now it involves talking to the RTCPeerConnection.

However, [pull request 662](https://github.com/w3c/webrtc-pc/pull/662) added the text _Since `track.stop()` does not implicitly call `RTCRtpReceiver.stop()`, Receiver Reports continue to be sent._ which indicates that no rejection takes place on track.stop(), but rather on receiver.stop().

Though there is no `RTCRtpReceiver.stop()`, so I'll assume for now that it refers to `RTCRtpTransceiver.stop()`, but that again makes it even less clear.

I need clarification on what stopping a received MediaStreamTrack does, and how one rejects a received track.

These questions came up while implementing `MediaStreamTrack.stop()` for received tracks in Firefox. See [bug 1301675](https://bugzilla.mozilla.org/show_bug.cgi?id=1301675).

**Comment by aboba** [comment]
@Pehrsons Removing an m-line can be accomplished by calling RTCRtpTransceiver.stop().  Calling RTCRtpTransceiver.setDirection() can be used to set the transceiver to "sendonly" or "inactive".  Both stop and setDirection set the negotiation-needed flag.

**Comment by Pehrsons** [comment]
That clarifies it for me, thanks.

Shouldn't the reference to RTCRtpReceiver.stop() be dropped as well?

**Comment by aboba** [comment]
@Pehrsons Reference to RTCRtpReceiver.stop() has been removed in the latest build: 
https://cdn.rawgit.com/w3c/webrtc-pc/master/webrtc.html

**Comment by alvestrand** [comment]
Fixed in #900

**Comment by jan-ivar** [comment]
So what does `track.stop()` do?
