### ISSUE TITLE
Does setLocal/SetRemoteDescription modify RTCRtpTransceiver.direction?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#902]
From Taylor: 
https://lists.w3.org/Archives/Public/public-webrtc/2016Nov/0009.html

Here's an example to illustrate the point:

transceiver.setDirection("sendrecv");
// ...
pc.setLocalDescription(sendRecvOffer);
// ...
pc.setRemoteDescription(recvOnlyAnswer);
// What is transceiver.direction now? "sendrecv" or "sendonly"?

Has this question already been decided? If not, it's probably something we should cover at the upcoming virtual interim.

**Comment by aboba** [comment]
Related to JSEP Issue https://github.com/rtcweb-wg/jsep/issues/371

**Comment by taylor-b** [comment]
Pros of the direction changing:

- Can see the negotiated direction without looking at SDP
- Makes the handling of "negotiated-needed" really simple; either the direction matches, or it doesn't.

Cons:

- May force application to call setDirection in between each offer/answer.
- Breaks the common addTrack-type use cases, unless we add even more special rules for addTrack.

**Comment by aboba** [comment]
@taylor-b The Cons seem more persuasive.  But the spec could probably use a note pointing out that the direction reflected in SDP created by createAnswer may not be the same as transceiver.direction (reflected in the last call to transceiver.setDirection()).  setDirection() **always** sets the direction reflected by createOffer(), correct?

**Comment by taylor-b** [comment]
Sounds reasonable; JSEP does now say something to that effect, so we could point to it.

But the `createAnswer` restriction is just a consequence of SDP offer/answer rules; I can't reply "sendrecv" to "sendonly". What also should be noted, if we go this route, is that the transceiver's direction may not match the negotiated direction. It may even be useful to expose separate `desiredDirection`/`negotiatedDirection` attributes, to make this distinction even more clear (and allow you to figure out the negotiated direction without parsing SDP).

**Comment by aboba** [comment]
Since there was conensus at the virtual interim that setLocal/SetRemoteDescription should not modify RTCRtpTransceiver.direction I think we can close this.
