### ISSUE TITLE
Capitalization of RTCDTMFSender

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#903]
DTMF may have been an acronym 50 years ago, but now it is more or less an word like ICE, or RTP. I'd suggest we change this to RTCDtmfSender. (and related changes for other uses of DTMF. ) Note it seems to me that the Initialisms principal applies to the RTC not the Dtmf.

**Comment by martinthomson** [comment]
What is the effect on implementations that have already shipped the API?

**Comment by fluffy** [comment]
I'm sure the clever implementors over there could figure out some way to make both work :-) And it would make this consistent with ORTC.

**Comment by aboba** [comment]
Related issue: https://github.com/w3c/ortc/issues/601

**Comment by martinthomson** [comment]
Yeah, I've done the aliasing thing before, it sucks but it's possible.

**Comment by alvestrand** [comment]
Resolution with advice from the TAG: RTCDTMFSender is the correct casing.
