### ISSUE TITLE
MediaStreamTrack - set source --W3C Documentation missed reference

### ISSUE THREAD

**Issue by IvRRimum** [w3c/webrtc-pc#907]
While reading trough the [documentation][1] i got a hint that it is possible to add source from local media(video/audio) file and stream it using PeerConnection.

But the sentence:
**Note that this document describes the use of microphone and camera type sources only, the use of other source types is described in other documents.**

So, does does someone has these documents?

  [1]: https://w3c.github.io/mediacapture-main/#terminology

**Comment by alvestrand** [comment]
The relevant specs are https://www.w3.org/TR/mediacapture-fromelement/ and https://www.w3.org/TR/screen-capture/. Since the maturity of those specs is (likely) lower than that of this specification, we won't refer to them normatively.
