### ISSUE TITLE
Get Ready for Customized Ring-Back Tone

### ISSUE THREAD

**Issue by warnard** [w3c/webrtc-pc#909]
<h1><strong>Get  Ready for Customized Ring-Back Tone</strong></h1>
<p><strong>Author: </strong><br>
  DONG Wenyu, China Mobile</p>
<h2>1. Introduction </h2>
<p>Customized  Ring-Back Tone (CRBT for short afterwards) has been popular across billions of  telephone subscribers and tens of MNO operators, especially in Asia. Users use CRBT  to express their feelings or passions, and vast positive influence has been  intrigued over musical industry. In fact, CRBT has become the far more powerful  distribution channels than any other channels in some countries.<br>
Thus,  it is reasonable for WebRTC to support CRBT, in order to appeal and please  their users and to boost WebRTC-centric ecosystem.</p>
<h2>2. Technical Requirements </h2>
<p>CRBT  calls for close collaboration among signaling procedure, CRBT media procedure  and users&rsquo; vocal/video media procedure. CRBT requires seamlessly switch between  CRBT media and user media, and this switch has to take place at exactly the  time when the callee&rsquo;s client starts to ring, which can only be precisely derived  from signaling procedure.<br>
  However,  signaling procedure and media procedure in WebRTC are merely loosely coupled. Thus,  necessary technical mechanisms need to be polished.<br>
  Firstly,  a data structure is required to describe the CRBT service. Note, CRBT is  deployed on callee side and is irrelevant to caller side. <br>
  Secondly,  two set of media sessions need to be set up, in accordance with signaling. The  caller should 1) firstly start media exchanging with CRBT service and continue receiving  CRBT media until it is notified that the callee pick up the client; and then 2)  switch to user media exchange at no time.<br>
  <br>
How is  your opinion? On requirements, or on specification </p>

**Comment by stefhak** [comment]
If I understand the concept correctly, it seems like something that can be done with our current toolbox. The ringback tones played to the caller can be supplied by the CRBT service and played in an audio or video element. When the callee has answered, and media becomes available on the incoming track, the caller's app can change the source of the audio or video element to be that track instead of the CRBT provided media.

**Comment by alvestrand** [comment]
Closing as not relevant to this specification. If there is a specific spec change that is being proposed, please reopen.
