### ISSUE TITLE
currentRemoteDescription.sdp -- does it need to match the last SDP set via setRemoteDescription?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#921]
When doing the following:
```
var pc = new RTCPeerConnection();
pc.setRemoteDescription({ type: 'offer', sdp: "v=0\no=- 6276735615230473072 2 IN IP4 127.0.0.1\ns=-\nt=0 0\na=group:BUNDLE audio\na=msid-semantic: WMS *\na=ice-ufrag:nGx0Ag==\na=ice-pwd:MEA9YrgtlxtSZ3/M69h/oc3Svvs2KA==\na=setup:actpass\na=fingerprint:sha-256 05:EC:AE:05:A1:EF:7F:13:8A:7D:E3:C6:05:67:E3:CE:8D:16:6B:7A:78:92:58:F9:18:FC:FB:84:4A:5D:3C:F6\nm=audio 9 UDP/TLS/RTP/SAVPF 111\nc=IN IP4 0.0.0.0\na=rtcp:9 IN IP4 0.0.0.0\na=mid:audio\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\na=maxptime:60\na=recvonly\na=rtcp-mux\na=rtpmap:111 opus/48000/2\na=fmtp:111 minptime=10;useinbandfec=1\n" })
```
I get the following pc.remoteDescription.sdp from Chrome:
```
v=0
o=- 6276735615230473072 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nGx0Ag==
a=ice-pwd:MEA9YrgtlxtSZ3/M69h/oc3Svvs2KA==
a=fingerprint:sha-256 05:EC:AE:05:A1:EF:7F:13:8A:7D:E3:C6:05:67:E3:CE:8D:16:6B:7A:78:92:58:F9:18:FC:FB:84:4A:5D:3C:F6
a=setup:actpass
a=mid:audio
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=maxptime:60
```
i.e. Chrome moved ufrag, pwd and fingerprint.

[the spec](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-currentremotedescription)
describes the currentRemoteDescription as 
```represents the last remote RTCSessionDescription [...] plus any remote candidates that have been supplied via addIceCandidate() since the offer or answer was created.```

Does that mean that the sdp attribute must be exactly the same (ignoring candidates) or are modifications like pulling the fingerprints and ice-ufrags from the session level down to the m-lines allowed? Chromes behaviour is somewhat useful since it allows inspecting its internal state and what parts of the SDP were actually consumed. But it might not be spec-compliant.

**Comment by martinthomson** [comment]
I think that Firefox does similar things and - realistically - I don't think that you will see anything else.  Preserving the original SDP means that you have two SDPs now and only one of them has an actual effect.  Add to that the fact that you have to modify the SDP when candidates arrive, and you find that synthesizing it from an internal model is the only really feasible way.

Now, the spec should probably reflect this, of course.

**Comment by alvestrand** [comment]
This resembles a bit the "getConstraints" problem. It may be quite hard to describe what the requirements on the SDP is - how much can it change?

Possibly this is a JSEP or MMUSIC discussion (define "identical except for candidates").
