### ISSUE TITLE
Remove legacy getStats API?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#924]
In #899 , @henbos said:

"Note that Chromium's outdated callback-based getStats doesn't even use RTCStatsReport. The "equivalent" of RTCStatsReport is called "RTCStatsResponse": https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCStatsResponse.idl?q=RTCLegacyStatsReport+f:%5C.idl&sq=package:chromium&l=29&dr=C and the "equivalent" of RTCStats is called "RTCLegacyStatsReport" (previously called "RTCStatsReport" which caused a naming conflict with the new stats API): https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCLegacyStatsReport.idl?q=RTCLegacyStatsReport+f:%5C.idl&sq=package:chromium&dr=C. But these are not compatible with RTCStatsReport or RTCStats due to differences.

So I'm questioning whether this legacy API is something that will improve compatibility. If it has been implemented by other browsers then yes, but if this was added because of Chromium's callback-based implementation then no."

Having fewer legacy functions seems like a Good Thing.

**Comment by henbos** [comment]
Also Chromium's supply of stats are so different from the spec that you probably have to do browser-specific examination of stats anyway, even if it has a getStats using RTCStatsReport, at least for the Chromium-case.

**Comment by stefhak** [comment]
Sounds like we should just remove the legacy API since no one is implementing it.

**Comment by jan-ivar** [comment]
Firefox does implement the legacy method, but 90% of the RTCStatsTypes are wrong due to [missing hyphens](https://bugzilla.mozilla.org/show_bug.cgi?id=1322503) in the names (when [the spec changed on us in 2015](https://github.com/w3c/webrtc-stats/issues/5)), so it's not to spec either.

So the legacy method in the spec has no real purpose.

**Comment by alvestrand** [comment]
Decision at VI was to remove the legacy API.
