### ISSUE TITLE
What happens when setDirection() is called

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#927]
The current text states:

"The setDirection method sets the direction of the RTCRtpTransceiver. Calls to setDirection() do not take effect immediately. Instead, future calls to createOffer and createAnswer mark the corresponding media description as sendrecv, sendonly, recvonly or inactive as defined in [JSEP] (section 5.2.2. and section 5.3.2.). Calling setDirection() sets the negotiation-needed flag."

However, it would be helpful to have detailed steps.

**Comment by aboba** [comment]
A proposal:

1. Let transceiver be the RTCRtpTransceiver whose direction is to be set.
2. Let newDirection be the argument to setDirection(). 
3. If newDirection is equal to transceiver.direction, abort these steps. 
4. Set transceiver.direction to newDirection. 
5. Let connection be the RTCPeerConnection corresponding to transceiver.
6. Mark connection as needing negotiation.

**Comment by alvestrand** [comment]
From interim: In step 7, should be "queue a task to evaluate negotiation-needed"

**Comment by taylor-b** [comment]
Specifically, step 7 can just read:

`<a>Update the negotiation-needed flag</a> for <var>connection</var>.`
