### ISSUE TITLE
Ambiguous wording in addIceCandidate

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#930]
"If candidate is not null but is missing values for both sdpMid and sdpMLineIndex, return a promise rejected with a TypeError."

Provided candidate is not null, is this

    if (sdpMid === null && sdpMLineIndex === null) { throw new TypeError(); }

or

    if (sdpMid === null || sdpMLineIndex === null) { throw new TypeError(); }

?

I read it as the former (opposite of s/both/either/), but I could see someone reading it as needing "both sdpMid and sdpMLineIndex", for which values can't be missing.

Which one is intended, and is there a better way to write this?

**Comment by jan-ivar** [comment]
Also, both `sdpMid` and `sdpMLineIndex` have `null` default values, so it is impossible for them to be "missing" (`undefined`), so a rewording seems in order on that alone (I'll edit my first comment to fix it to avoid confusion).

**Comment by taylor-b** [comment]
The intention was the former; you just need some way of identifying what the candidate is for. I see how it could be confused though.

**Comment by jan-ivar** [comment]
Also, why is `sdpMid` nullable?

Or asked differently: Is `""` to be considered a "missing value" or a "value"? Is `""` ever a valid id?

Firefox will continue to treat `""` the same as `null` for now until someone chimes in.

**Comment by alvestrand** [comment]
Taylor, can you check if this needs a PR?

**Comment by taylor-b** [comment]
Yes, we can clarify the wording a bit. The intention is "there is SOME piece of information that can tie a candidate to an m= section". You have any suggestion, Jan-Ivar?

**Comment by jan-ivar** [comment]
Here's a PR. I left `sdpMid` nullable, which means `""` is still a valid id. We could make it non-nullable and default it to `""` if we want. Thoughts?

**Comment by taylor-b** [comment]
I think this is fine. The only difference is whether the promise is rejected asynchronously (when the implementation tries to find the `sdpMid` in the SDP) or not.

**Comment by aboba** [comment]
@jan-ivar I believe this is fixed in the latest version of the specification:
https://rawgit.com/w3c/webrtc-pc/master/webrtc.html

If not, you can re-open it.
