### ISSUE TITLE
Can we have more that one IdentityProvider?

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#931]

**Comment by fluffy** [comment]
Given the receiver need to has to trust one of the senders identity providers, I think it would be good to allow the sender to add multiple identity providers and let the receiver select which one it wants to use.

**Comment by martinthomson** [comment]
That's a pretty big change.  setIdentityProvider assumes one.  It's theoretically possible, but what happens when you have two a=identity lines and both are valid?  Which identity do you use?  That interacts poorly with the `peerIdentity` attributes on the PC and the tracks.

**Comment by stefhak** [comment]
Could we close this as "won't fix"?

**Comment by fluffy** [comment]
In the name of getting done, I'm OK with marking this won't fix but I think 90% of what is hard about this we took on once we allowed multiple fingerprints. We probably need to sort out the implications of that in this or another bug.

**Comment by alvestrand** [comment]
Closing this as "we've decided that Webrtc-1.0 has only one".

**Comment by fluffy** [comment]
I think it would be more accurate to say "the API only allows the local side to set an single identity provider" and I don't think it a topic the WG has really discussed and made an informed decision on

**Comment by martinthomson** [comment]
I find the use case fairly compelling, but I think that it's a fair bit of work to sort out all the implications to the design.  "wontfix" sounds wrong though; we usually reserve that status for bugs that are never going to be solved.  "notnow" might be a better label.

**Comment by alvestrand** [comment]
Changing label to LATER.
