### ISSUE TITLE
RTCSessionDescription readonly members is not webcompat

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#933]
Brought up by @foolip in https://github.com/w3c/webrtc-pc/issues/573#issuecomment-259103219:

> https://crbug.com/662898 is a bug originating from @philn with Igalia where they (I presume) they tried to follow the spec but ran into trouble.

There's some discussion on that pre-existing closed issue, but better to continue in a new issue.

I also have a PR proposal.

**Comment by alvestrand** [comment]
I think this is solved. If not, please reopen.
