### ISSUE TITLE
STUN/TURN Auto Discovery handling

### ISSUE THREAD

**Issue by misi** [w3c/webrtc-pc#941]
How to process and pass up from ICE Agent to WebApp the Auto Discovered STUN/TURN servers
See: draft-ietf-tram-turn-server-discovery-10

My idea:
* ICE Agent makes this discovery 
  * when PC created
  * after network or interface change
ICE agent during PC creation gets the “domain name” from PC
From:
  * Local browser hard config, 
  * DHCP (domain-name), 
  * PC identity domain config  (“provider” domain from setIdentity)
* ICE agent discovers STUN/TURN servers based on this “domain name”
   * According  draft-ietf-tram-turn-server-discovery-10 
     * S-NAPTR lookup, DNS-SD discovery, Multicast DNS, Anycast etc,)
* And sending an event to WebApp with a list of discovered STUN/TURN servers
* App could decide to add these auto discovered servers (with additional credential) to iceSevers list.

**Comment by aboba** [comment]
@misi Reading the definition pc.defaultIceServers leads me to wonder whether the "Auto Discovered STUN/TURN server shouldn't be made available in that attribute: 

The defaultIceServers attribute provides a list of ICE servers that are configured into the browser. A browser might be configured to use local or private STUN or TURN servers. This method allows an application to learn about these servers and optionally use them.

**Comment by misi** [comment]
@aboba I am not sure about pc.defaultIceServers is the right solution, 

IMHO it is not really enough to inform the  WebApp/App about a new TURN server discovery through change of pc.defaultIceServers. 
This way, the App needs to monitor changes of pc.defaultIceServers to detect a new server discovery.

IMHO it is important to inform App that a new TURN server uri has discovered.
Furthermore important that discovery normally not contains any credential, for the TURN server.
So the newly discovered TURN server may not usable without a credential, and this way we need to trigger the app to request a credential for this (IP/FQDN) TURN server.

- IMHO an event would better to inform App after a network change has occurred that a TURN client discovered with anycast/dns etc a new TURN server.
- I think inform the App as a new event is more appropriate
  - and app could decide if that this server/IP is trusted/appropriate to use or not, 
  - and get credential for this TURN server
    - may ask for credential from an external "TURN service Auth server" 
  - and after it, configure the TURN server and with the requested credential to the PC on the usual way.

**Comment by juberti** [comment]
I generally think auto-discovered TURN servers should be handled as RETURN servers, i.e., like proxies, and not surfaced to the app directly.

**Comment by misi** [comment]
Please consider that Your approach may works well only in case if TURN server is in-house and you don't need to get credential for authentication from an external AUTH server. 

So if TURN service is inside LAN and no Auth required then it could be handled like the RETURN server or a proxy severs.

But AFAIK you couldn't treat the same way, if WebRTC App works with an external global TURN service that needs Auth.

E.g. The browser discovers  the closest TURN server (from domain name through DNS lookup, or make an Anycast STUN request and receive closest server IP/HOST /in alternate-server/), 
furthermore in case OAuth may every TURN server requires different credential.

( In this case it does not exists a general TURN global domain level credential that is valid for every server, the TURN service use different credential for every server. 
Why? To harden the service and this way the credential is not only time limited but also only valid on the exact discovered TURN server. /or TURN server group in the closest region/)

Only the App knows where is the Auth server for the global external TURN service that App use, where it can request a credential for the exact recently discovered TURN server (Hostname/IP).

The App needs to get  a credential (exactly for the discovered IP/HOST) and on the usual way configure PC, so pass the discovered TURN server with the appropriate (requested) credential to PC.

I don't see how your approach could deal with such a case. 
I am not sure it is suitable to handle it at all.

@juberti  
**What do you think?**
How should we handle such a case?

**All in all**
- I still believe that we need an event to handle such case.
- And flag may also needed to indicate and control  ICE agent(STUN/TURN client) that STUN/TURN auto discovery is needed/appropriate or not for this PC instance.

**Comment by alvestrand** [comment]
I'm not sure this is a WebRTC-PC issue. Does it affect the API?

**Comment by misi** [comment]
@alvestrand 
I strongly believe yes it affects API..

- STUN Discovery results only a URI, FQDN (or in case Anycast) only IP, BUT no credential.
- In other hand TURN server needs also a Credential (+ TURN URI).
=> App is needed to be notified to get credential for the recently discovered TURN server.

(Also concern that credential is not static information and could be only valid for only the discovered IP.
In specific case of OAuth, OAuth client implementation needed to get such credential. 
That fits better to App then browser framework.)

**Comment by alvestrand** [comment]
I'll reformulate .... is there a reason why interfacing to STUN discovery needs to be part of the WebRTC-PC spec, and not its own API?
If there is a separate API for STUN/TURN discovery (including credentials discovery), which results in URIs that can be passed into the WebRTC-PC interface, no changes to WebRTC-PC are needed.

**Comment by misi** [comment]
Reasons to implement in PC Spec:
- AFAIK "draft-ietf-tram-turn-server-discovery" is about server discovery only.
  And so there is no such API defined (Yet or under consideration) that discovers both credential and servers.
  - Furthermore there are multiple ways and big variety how a TURN Service Provider could (authenticate and interact with an App) and release Credential info, may it is not easy to define such API.
    Moving this duty to App level gives more flexibility and freedom, than to hard config few
methods in browser frame for getting credentials.
- WebApp is normally configuring the TURN service during PC creation on App level (or latter on..)
  - Actually in general AFAIU provisioning and getting credential happens on App level.
  -  but TURN server discovery happen in ICE Agent, browser level
 So some communication between the two is probably desired. 
- We need to notify App about newly discovered servers. IMHO polling the
read only ice server list is not the right  approach. (Network change/roaming)
- Think about a use-case when more then one TURN server discovered and may App could detect that they are from different TURN Provider, and may App has also some in-house TURN service.
  - Then how to choose the right one? May browser  (the trust base) should control
this preference, but maybe we leave the control of this to the web App.
   - even the browser has the control and define a preference the browser may still could leave up to the App to get credential for the preferred TURN server.
  - The App may have preference (trusted/untrusted service, having a contract with the TURN SP, etc.) to choose the appropriate TURN service.
  - (Corporate) IP Network Operators could provide more then one trusted closely
   located TURN services and leave the decision up the App or the browser.
  - The App may or not have the freedom to choose what TURN service to use from the list of closest
discovered Servers but getting the credential for the browser preferred could be still handled by the App. (And may the App is trusted and has the freedom to pick one.)
- Why in PC and not a new separated API?
  - The PC controls ICE agent, so it should control TURN discovery case to.
  - The discovery happens low level, inside ICE agent WebRTC engine, 
   but App is the best position to implement a way to negotiate and get a credential for the server..

@alvestrand I hope it makes some sense to you..

**Comment by alvestrand** [comment]
1. is an argument for defining an API.
2. claims that TURN server discovery happens in ICE agent. There's no ICE protocol involved in sections 4 and 5 of -server-discovery.
3. is an argument for an event API.
4. I can't parse.
5. makes negative sense to me, given that I think 2. is false.

I think you argue well for an API to this service, but I am not at all convinced that this is part of WebRTC-PC.

**Comment by misi** [comment]
@alvestrand  


> 2. claims that TURN server discovery happens in ICE agent. There's no ICE protocol involved in sections 4 and 5 of -server-discovery.

Why I thought ICE agent is connected with Discovery and has benefits to implement in PC. 
1. Anycast discovery depends on STUN client functionality (sends an allocate request).
so STUN client functionality is needed for TURN discovery,
and ICE agent implements STUN engine/ client functionality. 
2. PC consumes TURN server list. If browser controls/filters TURN server list then maybe waste of time to discover app level (and may get credentials for all TURN servers), when after PC creation browser policy will filter out some, so apply filter ASAP during discovery may adds some benefits. Filter it low level, and return servers that will be accepted latter, and then get credential only for servers that Browser local policy allows.
3. For Optimization: In PC the ICE Agent needs/consumes a list of TURN servers, so may be beneficial to have a candidate list information in ICE agent ASAP(, or in case of bowser control, a filtered candidate list). Even before it has TURN servers received a credential to maybe pre-setup network TLS connection for faster connect.
4. I thought ICE agent works in webRTC low level and my feeling was that discovery would work better/fits better there, because:
   - could easily recognize network changes, 
   - help TURN discovery fast adoption, because gives a uniform default discovery process, and hides discovery complexity (receives in an event a list of discovered servers, shouldn't do much for it).
5. DNS part is not so closely related to ICE Agent, but needs low level input. A DNS lookup needs low level info e.g DHCP "domain" attribute that is normally not available on WebApp level, but is only accessible in WebRTC engine level.

Because of 1. and 2. 3. I see still some benefits for integration TURN discovery in PC, but now I am less confident about that. 

Not sure if a separated API makes less or more confusion, and helps fast discovery adaptation.

**Comment by alvestrand** [comment]
A separated API certainly means that this issue doesn't delay webrtc-pc.
I suspect a separated API might even go faster, since it doesn't need to wait for the webrtc-pc editing cycles.

**Comment by misi** [comment]
@alvestrand Many thanks for Your comments!

Ok, I feel this is the final word here. 
I fell I pop up this too late, I  accept that according your view the right way is to not add more delay to PC and make it in a separate API.

All in all, If you agree, I close this issue here.
