### ISSUE TITLE
sender.setParameters():  Changing simulcast parameters?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#945]
Section 5.2 says: 

"setParameters does not cause SDP renegotiation and can only be used to change what the media stack is sending or receiving within the envelope negotiated by Offer/Answer. The attributes in the RTCRtpParameters dictionary are designed to not enable this, so attributes like ssrc that cannot be changed are read only. "

[BA] This is reasonable as far as it goes.  However, in addition to changing read/write parameters relevant to simulcast (e.g. maxFramerate, scaleResolutionDownBy, etc.) setParameters() could be used to change things like the number of encodings to be sent. 

Are changes like adding encodings "outside the envelope negotiated by Offer/Answer"? What about removing encodings?

**Comment by aboba** [comment]
@pthatcherg Does the following make sense? 

setParameters cannot set the negotiation-needed flag and therefore must operate within the envelope negotiated by Offer/Answer.  Once setLocalDescription has been called, the envelope is set and the number of simulcast encodings cannot be changed.

If a transceiver is constructed with sendEncodings specifying N simulcast encodings, and setLocalDescription has been called, setParameters cannot be used to increase or decrease the number of simulcast encodings.  However, if setLocalDescription has not yet been called, setParameters can be used to change the number of encodings and the parameters set will be reflected in the SDP produced by createOffer/createAnswer.

setParameters can be used to activate or inactivate a simulcast encoding at any time by setting encodings[].active.  If the desire is to stop sending one or more simulcast encodings, this can be accomplished by setting encodings[].active to "false".  If the desire is to re-enable a simulcast encoding that is inactive, this can be accomplished by setting encodings[].active back to "true".

**Comment by alvestrand** [comment]
Solved by #970
