### ISSUE TITLE
Change SetLocalDescription to require unchanged offer/answer string

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#950]
As per discussions at IETF RTCWEB meeting in Seoul - it was decided some time ago to remove the ability to change the SDP string between createOffer / createAnswer and setLocalDescription. In Seoul, the decision was that a createOffer / answer invalidates all previous descriptions, and increments the version counter - only the last version number can be set with setLocalDescription.

This needs to be reflected in the webrtc-pc spec.

A proposal was also made that setLocalDescription's argument could omit the SDP string and that this would cause the last SDP created with createOffer/createAnswer to be used - since this is strictly an API matter, this ought to be a WEBRTC WG concern.

WG consensus on this needs to be established before doing it.

**Comment by aboba** [comment]
So if description.sdp is the null string, then use description.type?
