### ISSUE TITLE
Do not send silence nor black frame on track muted or ended

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#957]
[1] says to send silence or a black frame if track is muted or ended.
Why was this designed in this way instead of stop sending media to save bandwidth?

Best!!

Refs
[1] https://www.w3.org/TR/webrtc/#dom-rtcrtpsender-track

**Comment by aboba** [comment]
@mparis An application providing an "onended" or "onmute" event handler can choose to stop sending media upon the firing of those events, using several potential mechanisms: 

a. To irreversibly stop sending (and receiving): transceiver.stop()
b. To stop sending in a reversible way: 
   1. Set sender.track to null (e.g. sender.replaceTrack(null)). 
   2. Set encodings[].active to "false" (via sender.setParameters)

**Comment by mparis** [comment]
@aboba, thanks to your explanation now I understand how to do it with the current API ;).
But I have an important doubt: what happens if an implementation stops sending media when the track is ended instead of sending silence/black frames?
It is a no proper implementation or should we allow this behavior when there is not possibility of creating silence/black frames?

**Comment by alvestrand** [comment]
@mparis the implementation would be inconsistent with the spec.
When testing at TPAC, we found that Firefox and Chrome were inconsistent here, so we decided to settle on one set of behaviors (see bernard's comment).

It's reasonable to "send black" by sending a single black frame and then stop sending media, if the need for sending media is what has you worried.

**Comment by mparis** [comment]
OK, thanks for the clarification ;)
