### ISSUE TITLE
Advanced Peer-to-peer Example

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-pc#959]
Currently Section 11.5 has a note (Issue 6) saying that Example 15 is "TODO". 

Proposal:  Get permission from Sam Dutton to use an updated version of his “WebRTC In the Real World”  example: https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

An updated version of this (which runs on Edge, Chrome and Firefox) can be found here:
Server code (node.js): http://internaut.com:8080/~baboba/iit-tutorial/adapter/server.js
Client code: http://internaut.com:8080/~baboba/iit-tutorial/adapter/js/main.js
HTML file: http://internaut.com:8080/~baboba/iit-tutorial/adapter/index.html

**Comment by alvestrand** [comment]
@samdutton do you want to contribute the text mentioned?

**Comment by alvestrand** [comment]
@samdutton ping?

**Comment by samdutton** [comment]
Oops — sorry. Will get onto this, I promise!

**Comment by stefhak** [comment]
Section 11.2 is an advanced example.

**Comment by stefhak** [comment]
@adam-be will create a PR.

**Comment by samdutton** [comment]
@aboba Looking at this again, the example in the article [here](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/) is actually taken from (IIRC) Example 13 in section 11.3.

@adam-be — are you building code for Example 15? 

(BTW: not sure 'the more complete functionality' means in this context.)

**Comment by adam-be** [comment]
@samdutton, at the last editor's meeting we talked about promoting "11.2 Simple Peer-to-peer Example with Warm-up" and let it become an "advanced p2p example". It uses RTCRtpTransceiver and warmup with replaceTrack so I think it qualifies. I guess we can have other "advanced examples" as well that, for example, fiddles around with codec params.
