### ISSUE TITLE
Handing SDP with more than one identity 

### ISSUE THREAD

**Issue by fluffy** [w3c/webrtc-pc#964]
A web browser might only generate a single identity header but draft-ietf-stir-rfc4474bis make is clear that it may need to be able to deal with remote SDP more than one. Need to clarify text on how  to do this. I'd propose if any of the Identities are valid and match the peerIdentity then it is OK to use. Probably need a way to return multiple identities.

**Comment by alvestrand** [comment]
Seems related to #931 - if there are multiple identity headers, is there a defined way to figure out which identity provider vouches for each header?
If #931 is resolved to "no,only one", we can discard all headers that don't verify with "our" identity provider.

**Comment by fluffy** [comment]
No, we already decided that the SDP from the remote side can contain more than one. Identity header. Note this is very different than the number of Identity providers used by the local side. (really even thought one can log on just about every internet service using only goole as an identity provider, some people want more than one)

**Comment by alvestrand** [comment]
Discarding all the identities that we can't validate with our (one) identity provider certainly is a way of handling SDP with more than one identity.
Are there cases where we will have multiple identity headers that validate with the same identity provider?

**Comment by martinthomson** [comment]
The relying party might not have an identity provider.  Or, perhaps more precisely, it doesn't matter what your local configuration is: the identity assertion contains all the information necessary.

The big problem is when you have multiple valid identities.  Does the connection need to continue to have all those identities?  How do you use the `peerIdentity` constraint with such a peer connection?  I can imagine how we might deal with that (have a target peer identity set rather than a single identity, require that renegotiation results in a superset of those identities each time, etc...)

**Comment by alvestrand** [comment]
@martinthomson do you think that we can get answers to these questions in February?
Who would you suggest to come up with appropriate answers?

**Comment by stefhak** [comment]
BTW, where do we define the use of 4474 SDP attributes? It's not mentioned in JSEP.

**Comment by fluffy** [comment]
Also related to https://github.com/rtcweb-wg/jsep/issues/601

**Comment by fluffy** [comment]
I think at a hight level, how this should all work is relatively clear. If the sender uses identity provider A C and F and includes identifies for each of them, and the receiver uses C, D, and F then the receiver can verify the identity of with C or or F and if that works the identity is OK. If it fails, the identity is not. If the sender is not willing to verify using A, C, or F, then the identity has failed.

**Comment by stefhak** [comment]
@fluffy that is one way to handle it, I think there are others as well. I guess we need to define this if we want to support more that one identity.

**Comment by stefhak** [comment]
Labeling as "Icebox" since we won't do anything until something happens at the IETF side.

**Comment by ekr** [comment]
This has been resolved at the IETF: https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-14#section-5.6.4.2

```
   The semantics of multiple identity attributes are undefined.
   Implementations SHOULD only include a single identity attribute in an
   offer and relying parties MAY elect to ignore all but the first
   identity attribute.```

I don't think any change is required here at all on the W3C spec side. @fluffy

**Comment by stefhak** [comment]
Closing given https://github.com/w3c/webrtc-identity/issues/22 has been opened.
