### ISSUE TITLE
How should sender.get/setParameters work on a stopped sender?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-pc#965]
Should it throw `InvalidStateError` like sender.replaceTrack or be a no-op/return last set value?

**Comment by aboba** [comment]
@jan-ivar  How about this? 

setParameters rejects the promise with InvalidStateError if transceiver.stopped is true.  
If sender.track is null or the value of transceiver.currentDirection is recvonly, the sender will not send, but I'd suggest this not cause the promise not be rejected.

**Comment by alvestrand** [comment]
Since getParameters doesn't need to be special-cased, and pc.stop() stops all transceivers, the merge of #966 seems to resolve this issue.
