### ISSUE TITLE
This link is correct or not?

### ISSUE THREAD

**Issue by sussh** [w3c/webrtc-pc#984]
http://joxi.ru/bmo0VjWSxlBVo2
Offer:
1.  AddStream(stream1);
1.1. onNegotiationneded();
1.2. createOffer(onGotOffer);
1.3. onGotOffer(strOffer); // A offer
1.4. setLocalDescription(strOffer);  // "stable" --> "have-local-offer"
1.5. sendSignaling(strOffer);  // A offer

...

2. AddStream(stream2);
2.1. onNegotiationneded();
2.2. createOffer(onGotOffer);
2.3. onGotOffer(strOffer); // B offer
2.4. setLocalDescription(strOffer);  // "have-local-offer" --> "have-local-offer"
2.5. sendRemote(strOffer); // B offer

...

3. onGetRemote(strAnswer); // A answer
3.1. setRemoteDescription(strAnswer);  // "have-local-offer" --> "stable"
3.2. ...

...

4. onGetRemote(strAnswer); // B answer
4.1. setRemoteDescription(strAnswer);   // "stable" --> "stable" ?!?!
4.2. ...

**Comment by alvestrand** [comment]
No, you can't setRemote(answer) in stable state.

The reference is https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-17#section-5.6

**Comment by sussh** [comment]
Thanks for the answer.
Can I then do the following obrazm: http://joxi.ru/KAgPGj8I4Ook3r (in bold)
It will not disturb the interaction between the parties to each other?

**Comment by alvestrand** [comment]
If it works, it is according to spec.
If it doesn't work, file a bug with the browser.

**Comment by sussh** [comment]
No no...
C++

**Comment by sussh** [comment]
Now I'll probably be able to answer your previous letter.
No, you can not do that. There is a sequence of events which still cause an error: http://joxi.ru/xAev0V1fpV0G1r

**Comment by sussh** [comment]
So, this problem can be solved by using only two additional variables:
1. flag for determining a high strony - offer: bool
2. The meter, accounting for the number of requests to the remote side - count: int
http://joxi.ru/Vm697VQcD0zVor
This is very uncomfortable, but I do not see any other options.

**Comment by sussh** [comment]
http://joxi.ru/KAgPGj8I4e67Mr
update theme

**Comment by alvestrand** [comment]
What you're illustrating is called "colliding offers" or "glare".
The spec says that if you do that, you get an error, and it's your problem to sort out what to do next.
SIP has one way of solving it. Other signalling protocols have other ways. Not a WebRTC problem to solve.

**Comment by sussh** [comment]
Until I smoked on the problem, I come up with the following algorithm: http://joxi.ru/V2VdKjBIxVqk7r

But there is one question: correctly so use the "localDescription()"?
C ++ library for "localDescription()" there is a similar
virtual const SessionDescriptionInterface* local_description() const;

**Comment by alvestrand** [comment]
Please - this tracker is about the Javascript API specification.
If you have C++ concerns, the correct forum is discuss-webrtc@googlegroups.com.

**Comment by sussh** [comment]
Ok. You pulled off the problem.
